### DISCUSSION TITLE
Kustomize update image tags to target git commit id

### DISCUSSION THREAD

**Discussion by Fabian-K** [fluxcd/flux2#1002] [Q&A]
Hi,

for every commit, we build docker images with the commit id as a tag. When flux v1 synced the cluster to a new commit, we updated image tags to the commit using the following .flux.yaml

```yaml
version: 1
commandUpdated:
  generators:
    - command: |
        kustomize edit set image image-a:$(git rev-parse HEAD)
        kustomize edit set image image-b:$(git rev-parse HEAD)
        <...>
        kustomize build .
```

I know that in v2 I can update images using https://toolkit.fluxcd.io/components/kustomize/kustomization/#images but I don´t know if there is a way to access e.g. the current git commit id (=> result of $(git rev-parse HEAD))

Thanks!
