### DISCUSSION TITLE
Is it possible to add Kubernetes manifest as a dependent of HelmRelease?

### DISCUSSION THREAD

**Discussion by yershalom** [fluxcd/flux2#1010] [Q&A] [answered]
Hi,

I started using Flux two weeks ago and everything is going great, so thanks!
To the issue now... We are installing cert-manager as HelmRelease and we encountered with an issue with fresh AKS install.
The Issuer and Certificate should have depends on cert-manager HelmRelease but we there is no option to do that, and the kustomize is failing, because cert-manager wasn't installed yet.

Issuer manifest file:
```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
```

Certificate manifest file:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 48h
  renewBefore: 25h
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
    - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth
```

Is there something we can do?
