### DISCUSSION TITLE
how do I get helm-controller to deploy helm releases in different folders without using kustomize-controller

### DISCUSSION THREAD

**Discussion by jack-evans** [fluxcd/flux2#1061] [Q&A]
Hello, we've been using fluxv1 with helm-operator for over a year and I am looking at migrating from that to fluxv2.

Currently, we have a single repo that hold all our charts, releases and individual cluster configuration to apply as values to the releases/helm charts like so:
```
my-repo/
    charts/
    cp-releases/            // releases to only install on our control planes
    shared-releases/        // releases to install in both control and data planes
    dp-releases/            // releases to only install on our data planes
    clusters/
```

This works for our existing setup however not without some adjustment to fluxv2.

Currently in order to get helm-controller to recognise the releases I have to do the following:
1. create a git source to point at the repo
2. create a kustomization.yaml in `cp-releases` or `shared-releases` or `dp-releases` like this:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - releaseA.yaml
  - releaseB.yaml
``` 

3. Create a Kustomization resource to patch the path:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cp-releases
  namespace: flux-system
spec:
  prune: true
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: my-repo
  path: ./cp-releases
```

Is there a way to keep this existing format and bypass the need for the Kustomization resource and just use the GitRepository resource?
