### DISCUSSION TITLE
cert-manager install issues with flux2

### DISCUSSION THREAD

**Discussion by dev-samples** [fluxcd/flux2#1063] [Q&A] [answered]
I have successfully bootstrapped flux into a v1.17.13 k8s cluster:

```
$ kubectl get pods
NAME                                      READY   STATUS    RESTARTS   AGE
helm-controller-996df94bbcc-tglj6          1/1     Running   0          130m
kustomize-controller-99df53296-s624g      1/1     Running   0          130m
notification-controller-71dcddfc7-lthx5   1/1     Running   0          130m
source-controller-85p44bc47b-z5cqq        1/1     Running   0          130m

```
Based on:
https://github.com/fluxcd/flux2-kustomize-helm-example
https://github.com/equinor/sdp-flux/blob/prod/base/standalone-components/cert-manager/helm-release.yaml

I am trying to deploy cert-manager into my cluster having this setup:

```
├── clusters
│   └── my-cluster
│       ├── flux-system
│       │   ├── gotk-components.yaml
│       │   ├── gotk-sync.yaml
│       │   └── kustomization.yaml
│       └── infrastructure
│           ├── cert-manager
│           │   ├── kustomization.yaml
│           │   ├── namespace.yaml
│           │   └── release.yaml
│           ├── kustomization.yaml
│           ├── nginx
│           │   ├── kustomization.yaml
│           │   ├── namespace.yaml
│           │   └── release.yaml
│           └── sources
│               ├── bitnami.yaml
│               └── kustomization.yaml


```
Where:

**infrastructure/cert-manager/kustomization.yaml**

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - release.yaml

```

**infrastructure/cert-manager/namespace.yaml**

```
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
```

**infrastructure/cert-manager/release.yaml**

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
#apiVersion: helm.toolkit.fluxcd.io/v1beta1
#apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: 1.2.0
  values:
    installCRDs: true
    ingressShim:
      defaultIssuerName: letsencrypt-prod
      defaultIssuerKind: ClusterIssuer
      defaultIssuerGroup: cert-manager.io

```

After I have pushed the above its successfully picked up by flux/kustomize-controller but I get the following errors:

```
kubectl logs -f kustomize-controller-88df54496-s620g
...
{"level":"error","ts":"2021-03-08T13:18:13.365Z","logger":"controller.kustomization","msg":"Reconciliation failed after 1.418096882s, next try in 10m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","revision":"flux/bc0e4fe075de75698de3817a35543ad146ed34f8","error":"validation failed: error: error validating \"04d07fa6-f156-4be6-b17a-df520cfff94e.yaml\": error validating data: [ValidationError(HelmRelease.spec.chart): unknown field \"name\" in io.fluxcd.toolkit.helm.v2beta1.HelmRelease.spec.chart, ValidationError(HelmRelease.spec.chart): unknown field \"repository\" in io.fluxcd.toolkit.helm.v2beta1.HelmRelease.spec.chart, ValidationError(HelmRelease.spec.chart): unknown field \"version\" in io.fluxcd.toolkit.helm.v2beta1.HelmRelease.spec.chart, ValidationError(HelmRelease.spec.chart): missing required field \"spec\" in io.fluxcd.toolkit.helm.v2beta1.HelmRelease.spec.chart, ValidationError(HelmRelease.spec): missing required field \"interval\" in io.fluxcd.toolkit.helm.v2beta1.HelmRelease.spec]; if you choose to ignore these errors, turn validation off with --validate=false\n"}

```

Apparently **name**, **repository** and **version** are not known and it says **spec** is missing - which its not.

Any suggestions?

Fyi; I have managed to install nginx with similar approach so it must be something specific for the cert-manager chart?
