### DISCUSSION TITLE
How can I patch the podinfo kustomization of the Get Started example?

### DISCUSSION THREAD

**Discussion by knweiss** [fluxcd/flux2#1133] [Q&A] [answered]
I've created the podinfo kustomization following the Flux v2 [Get Started](https://toolkit.fluxcd.io/get-started/) example. It applies the three manifests from the upstream podinfo `GitRepository` directory`./kustomize`.

As a first test I then wanted to increase the `MinReplicas` of the upstream `HorizontalPodAutoscaler` definition from 2 to 3 by adding an overlay to the kustomization.

Now I'm wondering: What's best way to patch/overlay the upstream manifests using kustomize's `patchesMergeStrategic` feature? 

Would I place my own `patch.yaml` in a new `GitRepository` (I can't modify the upstream podinfo repo directly). But how can I then reference podinfo's `./kustomize` directory as a kustomize base? Is this even possible? Or do I have to copy the upstream manifests into my own repository?

**Comment by somtochiama** [comment, marked as answer]
Hey @knweiss,
You can add the patch in the `patchesMergeStrategic` field in the `Kustomization`.
E.g
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  validation: client
  patchesStrategicMerge:
  - apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    metadata:
      name: podinfo
    spec:
      minReplicas: 3
```
