### DISCUSSION TITLE
401 Unauthorized Error when reconciling Private HelmRepository

### DISCUSSION THREAD

**Discussion by haimari** [fluxcd/flux2#1144] [Q&A] [answered]
I set up ChartMuseum with Plain Auth.
I'm able to authenticate using `curl` command and to `list/push/delete` helm charts successfully.

Then I set up the Flux `HelmRepository` source according to the [Docs Example](https://toolkit.fluxcd.io/components/source/helmrepositories/#spec-examples)

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: example-com-helm
  namespace: flux-system
spec:
  interval: 1m
  url: https://helm.example.com
  secretRef:
    name: https-credentials
  interval: 1m
  ```

I set up a `secret` in the `flux-system` namespace
(Without Any CA, only user and password data) and base64 the credentials before adding them.

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: https-credentials
  namespace: flux-system
type: Opaque
data:
  username: "XXXXXXXXXXXXXXXXXX"
  password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  certFile: ""
  keyFile: ""
  caFile: ""
```

I'm facing this error:

```json
{
	"level": "error",
	"ts": "2021-03-23T08:04:21.213Z",
	"logger": "controller.helmrepository",
	"msg": "Reconciler error",
	"reconciler group": "source.toolkit.fluxcd.io",
	"reconciler kind": "HelmRepository",
	"name": "example-com-helm",
	"namespace": "flux-system",
	"error": "failed to download repository index: failed to fetch https://helm.example.com/index.yaml : 401 Unauthorized"
}
```

What am I missing ?
