### DISCUSSION TITLE
Shared Image Policy

### DISCUSSION THREAD

**Discussion by kav** [fluxcd/flux2#1199] [Proposals]
Kicking the tires on Flux V2 and I'd really love to have an image policy that takes the ImageRepositoryRef from the object it's attached to. That way I can have more general image policies that are shared across the many images, deployments, hrs with the same rules. Centralizing policy updates, dry, etc. 

Perhaps it's a non-starter with the component factoring? Or just a terrible idea?

**Comment by squaremo** [comment]
> an image policy that takes the ImageRepositoryRef from the object it's attached to

Not sure which object this is; would you give a worked example of which bits go where?

**Reply by kingdonb** [reply]
I think the idea is that we scan all YAMLs for Kustomize looking for setter comments, not just those at the end of an ImageRepoRef. Is that true? (I actually don't think that's how image-automation-controller works)

I haven't read the code, but I guess by "component factoring" what is meant is that we don't actually run the imagepolicy or trigger the reflector to check for images at `kustomize build` time (this is a responsibility of ImageUpdateAutomation, right?)

From a layman's understanding, does ImageUpdateAutomation start with each ImagePolicy and scan the repo for references to each? (Or is something scanning the git repo for any kyaml setter comments, then checking each setter for an ImagePolicy that hopefully exists behind the ImagePolicy that's referenced in the comment?) I suppose I could just go read the code...

**Comment by kav** [comment]
Yeah I'm thinking, very much from the perspective of a user and flux v1 user, that the image policy is being "attached" to an image in a deployment. For example:
```yaml
spec:
  containers:
  - name: podinfod
    image: ghcr.io/stefanprodan/podinfo:5.0.0 # {"$imagepolicy": "flux-system:podinfo"}
```
That means I specify an image in the image property I'm commenting on and in the image policy. I'd love if that wasn't needed. To give a fairly contrived example:
```yaml
spec:
  containers:
  - name: podinfod
    image: ghcr.io/stefanprodan/podinfo:5.0.0 # {"$imagepolicy": "flux-system:podinfo"}
  - name: something-else
    image: ghcr.io/stefanprodan/something:3.1.0 # {"$imagepolicy": "flux-system:something-else"}
  - name: another-container-that-also-uses-the-same-tag-rules
    image: ghcr.io/stefanprodan/tag-rules:2.0.0 # {"$imagepolicy": "flux-system:tag-rules"}
```
This is fine with three but in a real cluster with even 100 images that all follow the same tag rules I'd need 100 image policies that only differ in ref.

Perhaps I'm imagining a TagPolicy object that a source controller can use to generate image policy objects? Trying not to get into the implementation details until the UX makes sense so I don't leak current design decisions.

something like
```yaml
spec:
  containers:
  - name: podinfod
    image: ghcr.io/stefanprodan/podinfo:main-5cd23f-1611840548 # {"$tagpolicy": "flux-system:branch-hash-timestamp"}
  - name: something-else
    image: ghcr.io/stefanprodan/something:master-8674cf-1611840559 # {"$tagpolicy": "flux-system:branch-hash-timestamp"}
  - name: another-container-that-also-uses-the-same-tag-rules
    image: ghcr.io/stefanprodan/tag-rules:main-a34de1-1611840876 # {"$tagpolicy": "flux-system:branch-hash-timestamp"}
```

With a TagPolicy of
```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: TagPolicy
metadata:
  name: branch-hash-timestamp
  namespace: flux-system
spec:
  filterTags:
    pattern: '^.+-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
 ```

I could also easily imagine a semvar-minor semvar-patch policys though they wouldn't fit the existing ImagePolicy pattern.
