### DISCUSSION TITLE
Using GCP bucket as helm chart repository

### DISCUSSION THREAD

**Discussion by williambrode** [fluxcd/flux2#1228] [Q&A]
In flux 1 I was able to use a Google storage bucket as a helm chart repository like this:
```
chart:
    repository: gs://bucket-name/
    name: foo-bar
    version: 0.6.2
```
But with flux 2 I've been struggling to figure out how to adapt this to the helm repository.  It says using gs:// is not supported and using https for the bucket fails with an error about converting yaml to json.  Does anyone know how to do this or what change would be needed on flux 2 to support it?
