### DISCUSSION TITLE
Option to deploy development/pre-release charts?

### DISCUSSION THREAD

**Discussion by boxcee** [fluxcd/flux2#1259] [Q&A]
Hi everyone,

is there an option I am not seeing to pull `pre-release` charts?

`helm` has the option to search and pull `pre-release` versions of a chart by specifying the `--devel` option (by default they are omitted). I don't see any option passing an option like this to the `HelmRepository` or `HelmRelease` CRDs.

Is there a workaround? For me this is a missing feature.
We are pushing `pre-release` charts to our `chartmuseum` registry and I cannot install them using FluxV2.

**Comment by hiddeco** [comment]
Can you share a copy of your `HelmRelease`? Selecting prerelease ranges is possible by including a `-0` in your version selector:

```yaml
---
apiVersion: helm.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      # Only select pre-release ranges below v5.0.0
      version: ">=5.0.0-0 <5.0.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default
```

**Reply by boxcee** [reply]
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "^1.0.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default
```

And I was kind of expecting it to match `1.0.0-development.3`, which is not true, but it should match `1.0.1-development.3` correct?
