### DISCUSSION TITLE
Providing custom CRD to kustomize-controller

### DISCUSSION THREAD

**Discussion by stoetti** [fluxcd/flux2#1272] [Q&A]
We are using our own CRDs for deploying our applications within k8s. As we evaluate using flux2 for CD we came with the issue to use kustomization on those custom resources. The Kustomize-doc states that the CRD has to be provided withing the configuration (https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/crds/).

From understanding this means that the CRD has to be pushed to each repo where a manifest based on that CRD is used. I searchd the documentation and issues but didn't find a possiblity to provide the CRDs globally to the kustomize-controller or any other flux-component.

Is there a way?
If not, how could this be solved without copying (and maintaining) the CRD in each multiple repos?

**Comment by stefanprodan** [comment]
Flux reconciles its own custom resources without specifying the CRDs.

**Reply by stoetti** [reply]
So the kustomize running within flux is getting the CRDs from the cluster it is running in?

**Reply by stefanprodan** [reply]
Nop

**Reply by stefanprodan** [reply]
I think Kustomize is moving away from providing CRDs, instead you would provide the OpenAPI validation spec, see docs here https://github.com/kubernetes-sigs/kustomize/blob/master/examples/customOpenAPIschema.md

You haven't given any details on why do you need to provide CRDs, is it due to strategic merge or something else?

**Reply by stoetti** [reply]
I would like to apply a patch on some of the resource defined via our CRD, something like this

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - custom.yml
patches:
  - target:
      kind: Custom
      name: .*
    patch: |-
      - spec:
          customField: kustomizedValue
```
