### DISCUSSION TITLE
Failed  helm hooks aren't delete when upgrade release

### DISCUSSION THREAD

**Discussion by dmitriy-kharchenko** [fluxcd/flux2#1294] [Q&A]
Hey folks!

Please help with Helm release or chart configuration.

When I upgrade the Helm release previous failed hooks are not deleted and the new release version isn't deploying although job annotation `helm.sh/hook-delete-policy` is setted.

Hook configuration:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "hook-failed,before-hook-creation"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: "alpine:3.3"
        command: ["/bin/exit", "0"]
```

Release configuration:

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo
  interval: 1m
  install:
    disableWait: true
  upgrade:
    disableWait: true
  values:
    image:
      tag: 5.2.0
```

Thank you in advance!
