### DISCUSSION TITLE
Controller-notification alert to mark commit used (multiple clusters pointing single bitbucket repo)

### DISCUSSION THREAD

**Discussion by gerardgorrion** [fluxcd/flux2#1322] [Q&A]
Hi all. We are triying to use alert to point commit used into bitbucket repo, with multiple clusters running with flux and same repo. What is the way to do? install podinfo is necessary? is necessary to add every crd at the same repo by every cluster? Thanks,

we use these configurations guides:
[https://toolkit.fluxcd.io/guides/notifications/#git-commit-status](https://toolkit.fluxcd.io/guides/notifications/#git-commit-status)
[https://toolkit.fluxcd.io/guides/installation/#generic-git-server](https://toolkit.fluxcd.io/guides/installation/#generic-git-server)

But is no clear how to configure. We ned to configure duplicate kustomization, a flux repo and alerting to mark the commits?

Thanks!

**Comment by dewe** [comment]
~Any progress here? I'm currently trying the same...~

Got it working with Flux v0.13.2.

```bash
$ kubectl create secret generic bitbucket-app-password \
  --from-literal token=<my-bb-user-name>:<redacted-app-pasword>
```

```yaml
# infrastructure-notification.yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: bitbucket
  namespace: flux-system
spec:
  type: bitbucket
  address: https://bitbucket.org/<workspace>/<repo>
  secretRef:
    name: bitbucket-app-password
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  providerRef:
    name: bitbucket
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: infrastructure
      namespace: flux-system
```
