### DISCUSSION TITLE
Upgrade image automation to v1alpha2 APIs

### DISCUSSION THREAD

**Discussion by stefanprodan** [fluxcd/flux2#1333] [Show and tell]
In the v0.13 release of `flux` we have promoted the image automation APIs from `v1alpha1` to `v1alpha2`, this new version comes with **breaking changes**.

## API changes

For `ImageRepository` and `ImagePolicy` there are no changes to the specification besides the version bump from `image.toolkit.fluxcd.io/v1alpha1` to `image.toolkit.fluxcd.io/v1alpha2`.

For `ImageUpdateAutomation`, `v1alpha2` rearranges the API types to provide for future extension. Here are the differences, and where each `v1alpha1` field goes:

| `v1alpha1` field | change in `v1alpha2` |
|------------------|----------------------|
| `.spec.checkout` | moved to `.spec.git.checkout`, and optional |
|                | `gitRepositoryRef` is now `.spec.sourceRef` |
|                | `branch` is now `ref`, and optional         |
| `.spec.commit`   | moved to `.spec.git.commit` |
|                | `authorName` and `authorEmail` now `author.name` and `author.email` |
| `.spec.push`     | moved to `.spec.git.push` |

For more details, see the `v1alpha2` API [spec documentation](https://toolkit.fluxcd.io/components/image/imageupdateautomations/#example-of-rewriting-a-v1alpha1-object-to-v1alpha2). 

### Upgrade the Flux CLI

Upgrade your Flux CLI to v0.13 by downloading the binary from [GitHub](https://github.com/fluxcd/flux2/releases) or using Homebrew:

```
brew upgrade fluxcd/tap/flux
```

### Upgrade the Flux components

Run bootstrap:

```sh
flux bootstrap git \
 --components-extra=image-reflector-controller,image-automation-controller \
 ......
```

After the upgraded, the image-automation-controller will start logging errors like:

```console
$ flux logs --level=error

ImageUpdateAutomation.image.toolkit.fluxcd.io "flux-system" is invalid: spec.sourceRef: Required value
```

### Update the manifests in Git

Clone the repo locally and change the version of all your  `ImageRepository`, `ImagePolicy`, `ImageUpdateAutomation` manifests:

```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha1

# becomes

apiVersion: image.toolkit.fluxcd.io/v1alpha2
```

Rewrite your `ImageUpdateAutomation`  v1alpha1 manifests to v1alpha2:

From:

```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    branch: main
  interval: 5m
  update:
    strategy: Setters
    path: ./clusters/my-cluster
  commit:
    authorName: fluxbot
    authorEmail: fluxbot@example.com
    messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
  push:
    branch: auto
```

To:

```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sourceRef: # moved from `.spec.checkout`
    kind: GitRepository
    name: flux-system
  interval: 5m
  update:
    strategy: Setters
    path: ./clusters/my-cluster
  git:
    checkout: # moved under `git`, loses `gitRepositoryRef`
      ref:
        branch: main # moved into `ref` struct
    commit: # moved under `git`
      author:
        name: fluxbot  # moved from `authorName`
        email: fluxbot@example.com # moved from `authorEmail`
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push: # moved under `git`
      branch: auto
```

Commit and push the manifests change to Git, then tell flux to pull and apply changes with:

```sh
flux reconcile kustomization flux-system --with-source
```

Finally verify that the image update automation is working again:

```sh
flux get images all --all-namespaces
```
