### DISCUSSION TITLE
Introduce path based kustomization generator

### DISCUSSION THREAD

**Discussion by rverma-dev** [fluxcd/flux2#1338] [Proposals]
With kustomization controllers flux can generate kustomization(k8s) files. It would be nice flux can also generate kustomizations(flux-crd) too(along with sourceignore)

This would be helpful in multi-cluster scenario like 

<img width="377" alt="Screenshot 2021-04-24 at 9 45 00 AM" src="https://user-images.githubusercontent.com/80032502/115946884-caaf1200-a4e1-11eb-92e8-85973040c0ca.png">

If we want to sync all the infrastructure components to a specific tenant we have two options of creating kustomizations.

1. Create a single kustomization which syncs all the components in 1 shot. The disadvantage of this is that its not an itemwise sync and is all/none strategy. We should be okay to sync 9 components if one of 10 is incorrect.
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/k8
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
```

2. Create list of kustomizations for each component in each tenant. The primary issue is its not following DRY and we need to copy paste this in all the tenants. If we push them in base, then the issue comes is what if in a cluster I don't need some of them, and then we started putting patch: delete, which is again not a clear way.
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/k8/cluster-autoscaler
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/k8/external-dns
....
```

To take advantage of 2nd approach we propose to  have kustomization as generation strategy as 
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 10m0s
  generator: recursive
  path: ./infrastructure/k8/external-dns
  sourceignore: |
         kyverno
```
Once this is done we can have the simplicity of 1st approach and flexibility of 2nd approach and still follow DRY.
