### DISCUSSION TITLE
Annotation based healthcheck

### DISCUSSION THREAD

**Discussion by rverma-dev** [fluxcd/flux2#1339] [Proposals]
Currently deployments health-check is part of kustomizaiton config. If we move this to annotation this will reduce the kustomization crds.

E.g.
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/k8/kube-system
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  validation: client
  healthChecks:
    - kind: Deployment
      name: cluster-autoscaler
      namespace: kube-system
    - kind: Deployment
      name: aws-load-balancer-controller
      namespace: kube-system
```

Can be modelled with simply annotating deployment with, 
`flux/health-check: true`
