### DISCUSSION TITLE
kustomize-controller: Expose image field in the kustomization resource

### DISCUSSION THREAD

**Discussion by phillebaba** [fluxcd/flux2#135] [General] [answered]
Being able to use Kustomize image patching in the kustomize.fluxcd.io.Kustomize resource would be a useful feature. In cases where the Kustomization referenced is not owned by the end user, it would allow overriding of those images. This could also be useful for the work being done with automatic image updates.

The change would require a API spec change with an additional field.
```yaml
apiVersion: kustomize.fluxcd.io/v1alpha1
kind: Kustomization
metadata:
  name: backend
spec:
  interval: 5m
  path: "./webapp/backend/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp
  healthChecks:
    - kind: Deployment
      name: backend
      namespace: dev
  timeout: 2m
  images:
    - name: postgres
      newName: my-registry/my-postgres
      newTag: v1
```

Alternatively we could allow overriding many other Kustomization fields in the resource, under its own field.
```yaml
apiVersion: kustomize.fluxcd.io/v1alpha1
kind: Kustomization
metadata:
  name: backend
spec:
  interval: 5m
  path: "./webapp/backend/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp
  healthChecks:
    - kind: Deployment
      name: backend
      namespace: dev
  timeout: 2m
  override:
    images:
      - name: postgres
        newName: my-registry/my-postgres
        newTag: v1
    commonLabels:
      someName: someValue
```

I don't know how far it would be sane to go with the overrides though. If for example json patching would be allowed or now.

**Comment by stefanprodan** [comment]
## Proposal: Patch kustomization.yaml for image updates

An alternative would be for the image update automation to patch the `kustomization.yaml` in Git. This way we don't have to override kustomize fields in the Kustomization CRD.

```yaml
apiVersion: image.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: update-app
spec:
  gitRepository:
    name: app-repo
  update:
    imagePolicy:
      name: app-policy
    kustomization:
      path: "./deploy/overlays/dev" # <- kustomize edit set image app=app:semver
```
