### DISCUSSION TITLE
Can kustomizations be too many?

### DISCUSSION THREAD

**Discussion by yoan-myparcel** [fluxcd/flux2#1400] [Q&A] [answered]
Hi everyone!
First of all, Flux is awesome! ❤️ 

# Background
I have started migrating some clusters to Flux and initially I have created an "apps" Kustomization in the same repository that deploys a set of services:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps
  prune: true
  validation: client
```
And in the `apps` directory I will have a `kustomization.yaml` with the following example contents:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-a
  - service-b
  - service-c
```

If I want to introduce a new microservice I can create a new folder with the manifests and include it in the kustomization.yaml above.

However, now I see benefit of creating Flux Kustomization for each microservice such as refined alerts and clear dependencies between deployments.

# Question
Can flux kustomizations become too many? On a cluster that runs multiple environments with ~30 microservices each that would mean also ~30 Kustomizations as well. I am wondering what would the impact be on cluster resources and also on reconciliation performance?
Do you consider a good practice to deploy individual microservices with their own flux kustomization?

Thanks for the help!
