### DISCUSSION TITLE
How to use the generated ConfigMap's suffix?

### DISCUSSION THREAD

**Discussion by gerryfletch** [fluxcd/flux2#1436] [Q&A] [answered]
Following the [guide](https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize), I am using the Kustomize Controller to load a `values.yaml` into a `ConfigMap` from a Git repository, which generates a unique suffix.

Is it possible to get Flux to automatically update the `HelmRelease#valuesFrom`  property to include the generated suffix?

I can of course disable the suffix entirely:
```yaml
generatorOptions:
 disableNameSuffixHash: true
 ```
 But since the guide includes it, I wondered if there is a way to automatically update it :)

**Comment by stefanprodan** [comment]
> Is it possible to get Flux to automatically update the HelmRelease#valuesFrom property to include the generated suffix?

Yes that’s what the guide shows you, check out the `kustomizeconfig.yaml`

**Comment by iangregsondev** [comment]
@gerryfletch @stefanprodan I can't figure this out :-(

I am also using "disableNameSuffixHash" for it to work.

Am I missing something ? I couldn't get it to us the suffix either. I also checked the guide.

Any ideas ?

**Reply by gerryfletch** [reply]
I'm afraid I couldn't get it to work, so I stuck with `disableNameSuffixHash`. Let me know if you get something working!

**Comment by iangregsondev** [comment]
Here is what I am using in my release

```
  valuesFrom:
    - kind: ConfigMap
      name: kafka-akhq-values
```

but without the following in the kustomization.yml then it fails saying can't find configmap

```
generatorOptions:
  disableNameSuffixHash: true
```

For clarity, here is my configMapGenerator

```
configMapGenerator:
  - name: kafka-akhq-values
    files:
      - files/values.yaml
```

**Comment by lancerushing** [comment]
I've created an example of using generated configmaps and secrets (with hash suffix) in a flux helmrelease valuesFrom.

https://github.com/lancerushing/flux-helmrelease-with-generated-configmap

There is `kustomizeconfig.yaml` bit that makes it work: ([link](https://github.com/lancerushing/flux-helmrelease-with-generated-configmap/blob/main/app/base/kustomizeconfig.yaml))

```yaml
---
## Let Kustomize know how replace the nameReferences
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/valuesFrom/name
    kind: HelmRelease
- kind: Secret
  version: v1
  fieldSpecs:
  - path: spec/valuesFrom/name
    kind: HelmRelease
```
