### DISCUSSION TITLE
Question about Image Update Automation and Notifications

### DISCUSSION THREAD

**Discussion by christiangonre** [fluxcd/flux2#1437] [Q&A]
Hi all!
First of all, thanks a lot for this wonderful product, I love Flux.
I configured ImageUpdateAutomation without any problem in my cluster, but I don´t know if we can get a notification once the Deployment/HelmRelease changes their container image base. I configured Discord as provider and a global alert like the following, but I don´t receive any notifications when I change an image of a Deployment/HelmRelease,etc. I receive others notifications, like "Fetched revision: main/ade9eaf....."

This is the alert than I´m using now to test Flux:

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: alert-all
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: HelmRelease
      name: "*"
```

I checked all the documentation but I don´t see anything like I want, I don´t know if this isn't implemented yet or if I don´t know how to do it.

Thanks in advance for your help!
Regards.
