### DISCUSSION TITLE
Job Controller

### DISCUSSION THREAD

**Discussion by phillebaba** [fluxcd/flux2#146] [General] [answered]
As many know running Jobs with GitOps can be a bit of a pain as they are event drive instead of state driven. A common use case of Jobs would be migrating DB schema, which would only have to run once for specific updates. Currently in Flux there is no easy way of deploying jobs, as they would trigger once and then never again. To force a new run of the same job would require a manual deletion of the Job which Flux would deploy again.

It would be interesting to look into an addition of a JobController to allow triggering of Kubernetes jobs in a GitOps way. What I mean by that is that we achieve a behavior similar to how the automatic image updater will work. Any update is done through Git, to enable an audit trail. In theory this does not have to be specific to Jobs, as it could be any resource. The challenge is figuring out how to re trigger a resource, as there is currently no way of rerunning a Job.

![Untitled Diagram](https://user-images.githubusercontent.com/10550243/89225774-11b74900-d5db-11ea-8096-5d6bc73cece8.png)

The controller would require a resource that specifies the event and resource that should be recreated. The following Trigger contains the selector of the Job that should be updated, and the event type which should trigger it.
```yaml
apiVersion: job.toolkit.fluxcd.io/v1alpha1
kind: Trigger
metadat:
  name: db-migration
  namespace: gitops-system
spec:
  selector:
    app: db
  events:
  - ApplySucceeded
  - HealthCheckFailed
```

If any of the events occur the job controller would commit an update to the resource which would force the JobController to redeploy it. The challenge as stated before is figuring out how to force the re run of a Job.
