### DISCUSSION TITLE
"empty git-upload-pack given" with latest Flux v0.14.1

### DISCUSSION THREAD

**Discussion by jhramey** [fluxcd/flux2#1468] [Q&A]
I am assuming this has to do with the go-git update. Do I need to update a separate controller to fix this error?
I am currently using Flux via operatorhub.io and it was working on version 0.13.4

**Comment by jhramey** [comment]
Looks like theres a bug with go-git. I see comments made on slack pointing to that theory as well.

**Comment by stefanprodan** [comment]
This issue is being tracked here: https://github.com/fluxcd/image-automation-controller/issues/172

The recommended workaround is to switch to `libgit2` in your GitRepositories:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
spec:
  gitImplementation: libgit2
```
