### DISCUSSION TITLE
Implicit scanning for image update automation

### DISCUSSION THREAD

**Discussion by squaremo** [fluxcd/flux2#147] [General] [answered]
One thing in favour of the way automation works in Flux v1 is that the specification is right there with the resources, so if you want to change it, that's where you go; and if a workload is removed, so is the scanning and automation.

I think it would be possible to recreate a similar system by a/the controller examining the workloads in git, and creating ImageRepository and ImagePolicy objects as necessary, then using those as the reference for updates.

For example, an ImageUpdateAutomation object might look like this:

```yaml
kind: ImageUpdateAutomation
spec:
  gitRepository:
    name: config
  update:
    calculateFromAnnotations: {}
```

Then, for a suitably marked-up workload,

```yaml
kind: Deployment
metdata:
  annotations:
    automated.toolkit.fluxcd.io/server: true
    tag.toolkit.fluxcd.io/server: 'semver:1.1.x'
spec:
  template:
    spec:
      containers:
      - name: server
        image: helloworld:1.1.0
```

the controller would create an ImageRepository pointing at `helloworld` and an ImagePolicy with semver `1.1.x`; and when the latter had a latest image to report, it would update it in the workload.

Pros:
 - continuity

Cons:
 - complicated

Unanswered questions:
 - where do credentials come from?
