### DISCUSSION TITLE
Cannot clone public repo

### DISCUSSION THREAD

**Discussion by Tonkonozhenko** [fluxcd/flux2#1474] [Q&A] [answered]
Hi,
I'm not able to clone public repo from GitHub

error:
```
unable to clone 'https://github.com/linkedin/datahub', error: object not found
```

chart:
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: datahub
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/linkedin/datahub
  ignore: |
    /*
    !/datahub-kubernetes/datahub
    !/datahub-kubernetes/prerequisites
```
