### DISCUSSION TITLE
One Kustomization per service?

### DISCUSSION THREAD

**Discussion by emilbillberg** [fluxcd/flux2#1493] [Q&A] [answered]
Hi,

We are starting our journey moving to Flux 🚀 

Currently we are thinking about using one repository for all our services. our directory structure is something like this:
```
- clusters/
  - cluster-01/
  - cluster-02/
- manifests/
  - bases/
  - overlays/
    - staging/
      - service-01/
      - service-02/
```

I was first thinking about using a kustomization file in the root of `manifests/overlays/staging` that includes all services and use that in the path for the `Kustomization` manifests.

```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifests/overlays/staging/
  prune: true
  validation: client
```

... but I was also thinking that it could be better to use one `Kustomization` for each service:
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: service-01
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifests/overlays/staging/service-01
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: service-02
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifests/overlays/staging/service-02
  prune: true
  validation: client
---
...and other services
```

Does it matter performance wise to use many Kustomizations? We have about ~60 services today and maybe more in the future. Any other recommendations or suggestions?
