### DISCUSSION TITLE
Access GitRepository with TLS with local Certificate

### DISCUSSION THREAD

**Discussion by peterzandbergen** [fluxcd/flux2#1507] [Q&A] [answered]
Hi, I want to use fluxcd with a git repository via https. Problem is that the TLS cert is a company one and is not know by fluxcd.

Where do I need to solve this? On the Linux OS level, on the Kubernetes level, on the FluxCD bootstrap level or on the GitRepository configuration level.

Appreciate any help or suggestions.

Cheers, Peter Zandbergen

**Comment by hiddeco** [comment]
You can refer to a secret which contains the a `caFile` field with the certificate blob. See: https://fluxcd.io/docs/components/source/gitrepositories/#https-self-signed-certificates

**Comment by stefanprodan** [comment, marked as answer]
You can supply your cert CA to both `flux bootstrap` and `flux create source git` with `--ca-file=path/to/my/ca.crt`.

**Reply by hiddeco** [reply]
That is the automated way of doing it :-)

**Reply by peterzandbergen** [reply]
Cheers,

Where does FluxCD store the ca-file?

**Reply by hiddeco** [reply]
In the secret that is generated, if you use `--export` you can see (or export) the created manifests.

**Comment by peterzandbergen** [comment]
Thanks, will give it a try

Peter Zandbergen
Tel: +31 6 460 55 872

linkedIn: peterzandbergen <https://www.linkedin.com/in/peterzandbergen>

**Comment by peterzandbergen** [comment]
Hi, I have tried it out but only see the GitRepository resource. Flux version is ```flux version 0.14.1```.

What output should I see?

Command
```
flux create source git my-repo \
--url=https://git.internal/org/repo \
--branch=master \
--username=username \
--password=password \
--ca-file=./cert.pem \
--export
```

Output
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://git.internal/org/repo
```
