### DISCUSSION TITLE
Git update controller

### DISCUSSION THREAD

**Discussion by squaremo** [fluxcd/flux2#151] [General]
The [original image update automation design](https://github.com/squaremo/image-reflector-controller/pull/5) posits a "update job controller" which is used to apply changes to a git repository, and runs independently of the automation itself.

A GitUpdateJob specifies a git repository, a container image, and input parameters for the job. The git update controller arranges for the container to run with a checked-out version of the repository, and to commit and push the changes made, afterward.

There's two motivations for having this extra component:
 - it creates an opportunity to substitute your own update logic, by specifying a particular image to run as part of the job;
 - it can be reused for other kinds of automation, since it can do all the git mechanics and otherwise be generic (given a protocol for the image supplied to be run; e.g., the `kpt fn run` protocol)

A trade-off for git update controller taking on the git-management duties is that other controllers have to do a bit of work to create GitUpdateJob objects and monitor their completion status.

Example spec for a GitUpdateJob (this is the sort of thing the image automation would create to do its work):

```yaml
spec:
  checkout:
    gitRepositoryRef:
      name: config-repo
    branch: main
  update:
    image: fluxcd/update-images:v0.0.8
    functionConfig: # parameters for the container image
      kind: ImageUpdate
      newImage: helloworld:v1.0.1
      selector:
        matchLabels: { app: hello }
  commit:
    messageTemplate: |
      This would probably have to be specific to the container image as well
    generateBranch: image-update- # make a fresh branch using that as the prefix
status:
  result: Completed # | NoChanges | Failed
  revision: 38b213e1386f641daa4b3005c70a2977636a6db3
  branch: image-update-awersdth
```
