### DISCUSSION TITLE
Debugging image policy

### DISCUSSION THREAD

**Discussion by trenslow** [fluxcd/flux2#1518] [Q&A] [answered]
Hi community,

I'm in the process of migrating to Flux v2 and I was wondering if there's some way to debug image policies. Here's an example use-case:

I have images whose tags are composed by semVer, the platform it's built on followed, and the word 'latest'. For example: 1.2-debian-latest. I would expect the following config adapted from the docs to work:

```  
filterTags:
  pattern: '(?P<version>.*)-debian-latest'
  extract: '$version'
policy:
  semver:
    range: '^1.0'
``` 

however, the image controller reports it's unable to determine the latest version from the provided list. Right now my only way to proceed is a bit of guess and check, i.e. rewrite the policy, push to git, and reconcile with Flux. 

I think one way to get a lot of insight into the image policy would be to have a way see the tags that the image controllers see, especially after applying a filter on the tags.

Or is there a better way to get insight into how the image controllers are determining the latest version?

Thanks in advance for any tips you have.
