### DISCUSSION TITLE
HelmRelease crd missing ref from v1 when used with GitRepository kind

### DISCUSSION THREAD

**Discussion by afterlook** [fluxcd/flux2#1523] [Q&A] [answered]
Am I missing something or one can no longer use ref in order to specify which tag for example to use when trying to get a helm chart?

**Comment by hiddeco** [comment, marked as answer]
You still can?

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: webapp
  namespace: flux-system
spec:
  interval: 60m
  url: <your lovely Git repository URL>
  ref:
    tag: <your tag>
	# or
	# semver: <your semver range>
```
