### DISCUSSION TITLE
Flux doesn't pick up changes if values in the yaml file changes ?

### DISCUSSION THREAD

**Discussion by jdeokar95** [fluxcd/flux2#1531] [Q&A]
Hi, 
I am using flux cd with helm charts (with Helm Repository) for my deployments. I have a chart which has multiple yaml files which can defines the values to be used to render a chart. However if I change just one of the values in yaml file (which should trigger a deployment eg: image tag) and push my chart to the Helm Repository, flux doesn't trigger a new deployment. It pulls the new chart but doesn't really apply those changes. Please let me know if I am missing something ?

TIA

```
HelmRelease.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-test-chart
  namespace: flux-system
spec:
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  interval: 1m0s
  chart:
    spec:
      version: "0.2.2"
      chart:   my-test-chart
      sourceRef:
        kind: HelmRepository
        name:  my-test-chart
      valuesFiles:
        - values.yaml
        - qa.yaml
        - image-version.yaml
```
