### DISCUSSION TITLE
HelmRelease with sops decryption in fly

### DISCUSSION THREAD

**Discussion by Drupi** [fluxcd/flux2#1537] [Q&A] [answered]
I was digging very long but I run out of ideas.. 

I have a HelmRelease which is loaded with secrets. (upstream kube-prometheus-stack)
I would like to store it as HelmRelease resource in git with secrets encrypted by SOPS. Is there any chance made it "decrypt in fly"  ? 

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  releaseName: prometheus
  targetNamespace: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 16.7.0
      sourceRef:
        kind: HelmRepository
        name: ***
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
  values:
    value1: ${SOPS_ENCRYPTED_THING}`

```

**Comment by stefanprodan** [comment, marked as answer]
In your Helm release you would refer to a secret in-cluster with `.spec.valuesFrom` (that secret will contain the values.yaml) https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-in-configmap-and-secret-resources. You can store the Kubernetes secret manifest encrypted with sops next to the HelmRelease yaml in Git. You also have to enable decryption in the Flux Kustomization that applies both the Secret and the HelmRelease https://fluxcd.io/docs/components/kustomize/kustomization/#secrets-decryption.

**Reply by Drupi** [reply]
Thanks ! Solved  :)

**Reply by baflo** [reply]
@stefanprodan 
The way I did it is to "offline" generate and encrypt a secret `basic-auth.yaml` using kustomize and sops, then commit the secret and apply it in `valuesFrom`.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: basic-auth
    namespace: app
    files:
      - values.yaml
```

```sh
kubectl kustomize . | sops --encrypt --input-type yaml --output-type yaml /dev/stdin > basic-auth.secret.yaml
```

I used kustomize, because it eases writing normal YAML for the `values.yaml` that is applied by HelmRelease. The other option would be to manually write the Secret, then encrypt. But in that case I had to manually base64 encode my `values.yaml` and paste it into the Secret, then encrypt it.

I wonder if it would be possible to create a kustomization with a `secretGenerator` the full way down. With the documentation from [Refer to values in ConfigMaps generated with Kustomize
](https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize) I was able to make the HelmRelease update the secret name, but now I don't have encryption. 

Optimistically, I'd be looking for a way to just encrypt the `values.yaml`. I am on the right way or won't this be possible?

**Reply by sojinss4u** [reply]
> Optimistically, I'd be looking for a way to just encrypt the values.yaml. I am on the right way or won't this be possible? 
I am also looking for this feature. It would be nice if we can encrypt a specific key directly in values.yaml file using SOPS & HelmRelease decrypt the values file similar to Kustomize.

**Reply by baflo** [reply]
@sojinss4u You won't believe it... it works out-of-the-box! This is my current setup:
* an **sops encrypted** `values.yaml`
* a `kustomization.yaml` with a secretGenerator referring to the `values.yaml`
* a `helm-release.yaml` just immediatly referring to the name of the secret generated by the secretGenerator

<details>
<summary>values.yaml</summary>

```yaml
n8n:
    basicAuthUser: ENC[AES256_GCM,data:lfnf,iv:MUHX,,,yU=,tag:YG/1YW3N+qHIbHJ6lFTCuw==,type:str]
    basicAuthPassword: ENC[AES256_GCM,data:xK68JXb...xplQ==,iv:DlaZPmn9f0q9lic7...AGOw==,type:str]
    encryptionKey: ENC[AES256_GCM,data:iUziLz...8iMmCQu+Qxw==,iv:xDMlv...RhgmZFxT+Drf/t8LwM=,tag:4/cZI...kow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-08T15:03:23Z"
    mac: ENC[AES256_GCM,data:J36...qvQ==,type:str]
    pgp:
        - created_at: "2022-09-08T15:03:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyuaeGE6qAyeAQ//cXzABQuvDJPQ3yhzbPBhO1LqFi7LiDYCe4/gaSnGxRwa
            GrfobStczAuoknvPYyDzcZJQeVgDxza1j6IqKPa43R0/SlnCz1sQY0Ra7P0eIoQ9
            MM5mK/0ygWl4maGmcKOl1u15GZ/bdk0R5JmtRKi1FIUVc0nn97YQg+gtLVLA799C
            7/pUV1e6tl2BhnX2U...............................v9uDd4IjRNCOS8Nc6EAwfS
            XAHrYAKju5MB89EOUtDW1k16xqYHXsEHxIkC41CI/N/8JXo0ZT32AVt3U7o8aLq7
            AL+XhtLM0GnexYOEHp9H+xmU14eGAoHZ5ZlabUnhwsmRkb7lyPh18dP0b+We
            =W99W
            -----END PGP MESSAGE-----
          fp: 84BE281B01D323CCC4BCAF302F51E37CFC456EBA
    encrypted_regex: .*
    version: 3.7.3
```
</details>

<details>
<summary>kustomization.yaml</summary>

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: basic-auth
    namespace: n8n
    files:
      - values.yaml
```
</details>


<details>
<summary>release.yaml</summary>

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  releaseName: n8n
  chart:
    spec:
      chart: n8n
      version: "^1.0.0"
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  values:
    n8n:
      basicAuth: true
      scaling:
        enabled: true
    ingress:
      enabled: true
      hosts:
        - host: n8n.my.domain.com
          paths:
            - path: /
              pathType: Prefix
  valuesFrom:
    - kind: Secret
      name: basic-auth
```
</details>
