### DISCUSSION TITLE
dependent HelmRelease destroying it's dependency (depends_on). Bug or misconfiguration?

### DISCUSSION THREAD

**Discussion by marcelser** [fluxcd/flux2#1539] [Q&A] [answered]
I have 2 HelmReleases where the 2nd is based on another. They pull their charts from same git repo. I have put all in one file that looks like the file below.

The problem with this is that it first deploys the Release called ' infra-app-helm' which is then for a short period of time in `State: Ready with Message "Reconciliation succeeded"` while the second deployment is saying `'app-beta/myapp-app-helm' dependency is not ready`. Then once the first chart is ready flux starts deployment of myapp-app-helm. What now happens is totally confusing to me. Although it said previously that the dependency is not ready it now stops/uninstall the "infra-app-helm' chart completely. I see the new pods starting and the pods from the infra-app-helm terminating at the same time. The stopped/uninstalled chart immediately goes into `State: Failed with Message: Helm upgrade failed: another operation (install/upgrade/rollback) is in progress`. While the scond one myapp-app-helm goes into "Reconciliation failed" because it depends on the stopped/uninstalled one. Then again once the myapp-app-helm times out with this error the infra-app-helm is deployed again then you have a nice loop which never ends. It always does: start infra -> start myapp &kill infra and start over.

Or the 2nd scenario which can also happen is that it takes too long for the 2nd deployment to go into time out and I then see infra in "State: Failed, Message: upgrade retries exhausted".

Is this behaviour a bug or did I do something completely wrong, cause I played around with interval and other stuff but nothing seems to solve the problem. Any help with this would be greatly appreciated

```
release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: infra-app-helm
  namespace: app-beta
spec:
  chart:
    spec:
      chart: ./helm/infra
      sourceRef:
        kind: GitRepository
        name: myapp
  interval: 10m0s
  upgrade:
    remediation:
      remediateLastFailure: true
  targetNamespace: app-beta
  releaseName: app-beta
  valuesFrom:
  - kind: ConfigMap
    name: terraform-config
    valuesKey: values.yaml
    targetPath: global.tf_config
  - kind: ConfigMap
    name: terraform-config
    valuesKey: app-beta.yaml
    targetPath: global.tf_namespace
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myapp-app-helm
  namespace: app-beta
spec:
  chart:
    spec:
      chart: ./helm/myapp
      sourceRef:
        kind: GitRepository
        name: myapp
  dependsOn:
    - name: infra-app-helm
  upgrade:
    remediation:
      remediateLastFailure: true
  interval: 15m0s
  targetNamespace: app-beta
  releaseName: app-beta
  valuesFrom:
    - kind: ConfigMap
      name: terraform-config
      valuesKey: values.yaml
      targetPath: global.tf_config
    - kind: ConfigMap
      name: terraform-config
      valuesKey: app-beta.yaml
      targetPath: global.tf_namespace
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: myapp
  namespace: app-beta
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: myapp-git-auth
  url: https://gitlab.myappdev.systems/platform/
---
```
