### DISCUSSION TITLE
Is is possible to annotate the flux-system namespace during bootstrap?

### DISCUSSION THREAD

**Discussion by nicogl** [fluxcd/flux2#1584] [Q&A] [answered]
Say I want to add an annotation on the _flux-system_ namespace while bootstraping Flux, so when controllers are scheduled the annotation already exists. Is that possible?

The specific reason I need to do this is because I want to ensure that Flux's pods (under _flux-system_ namespace) run on a specific node by using below annotation:

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: SOME_VALUE
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/version: v0.9.1
  name: flux-system
```

I saw this [pull request](https://github.com/fluxcd/flux2/pull/1300) might be related but don't know if the "pre-bootstrap" feature is really available and if so, where to find instructions on how to use it. Thanks.
