### DISCUSSION TITLE
S3 Bucket AWS EKS

### DISCUSSION THREAD

**Discussion by annaic** [fluxcd/flux2#1589] [Q&A] [answered]
Hello, I am a newbie to fluxcd. I am trying to get going with deploying a simple kubernetes deployment.yaml from an S3 bucket.
I have been able to configure the IAM Role correctly for the S3 read for the source-controller service account.
The flux-system code is in github.
The reconcilliation commands for the git source as well as the s3 source seems to work without errors, but my deployment from S3 bucket does not seem to work.
I think something is messed up with how my resources are stored in S3.
Would appreciate some guidance on what I am doing wrong.
My dir structure in github repo is
- clusters - eks - flux-system - all the flux system resources
- clusters-eks-application-fluxcd-bucket.yaml
```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: Bucket
metadata:
  name: fluxcd-bucket
  namespace: flux-system
spec:
  bucketName: fluxcd-bucket
  endpoint: s3.amazonaws.com
  interval: 2m0s
  provider: aws
  region: us-west-2
```  
Inside the s3 bucket fluxcd-bucket, I have the following yaml files in the root
- deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aws-test
  name: aws-test
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-test
  template:
    metadata:
      labels:
        app: aws-test
    spec:
      containers:
        - image: sdscello/awscli:latest
          name: aws-test
          ports:
            - containerPort: 80
      serviceAccountName: source-controller
```
- fluxcd-bucket-kustomization.yaml
```yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: fluxcd-bucket
  namespace: flux-system
spec:
  interval: 2m0s
  prune: true
  sourceRef:
    kind: Bucket
    name: fluxcd-bucket
  validation: client
```
- kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- fluxcd-bucket-kustomization.yaml
- fluxcd-bucket.yaml
- deployment.yaml
```  
Thank you
