### DISCUSSION TITLE
`dependsOn` support across different resource kinds

### DISCUSSION THREAD

**Discussion by aclevername** [fluxcd/flux2#1599] [Proposals] [answered]
Slack discussion: https://cloud-native.slack.com/archives/CLAJ40HV3/p1625149645282400
Previous related issue: https://github.com/fluxcd/kustomize-controller/issues/242

Hello :wave: 

## Feature request
I would like to utilises flux's awesome `dependsOn` feature for resources of different kinds (in particular a `HelmRelease` resource depending on a `Kustomization`)

### Context
`HelmRelease` and `Kustomization` have support for specifying a `dependsOn` field in there spec that determine what resources must be running before deploying the resource. For example from the flux docs:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      ...
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      ...
  dependsOn:
    - name: backend
```

This above configuration ensures that the `backend` `HelmRelease` resource is deployed and running before attempting to depoy the `frontend`.

Currently this cannot be done for resources of different kinds, as `dependsOn` only takes a `name` and `namespace`, and assumes the resource is of the same kind. There is a workaround, which is to wrap every `HelmRelease` resource in a `Kustomization` resource, and add a `healthCheck` to the Kustomization.  [Example](https://cloud-native.slack.com/archives/CLAJ40HV3/p1625150130285900?thread_ts=1625149645.282400&cid=CLAJ40HV3). While this does work, it adds a lot of extra complexity and files to your git repository.

### Proposal
Introduce a `kind` and `apiVersion` to the `dependsOn` field, matching the pattern of [how `sourceRef` works](https://github.com/fluxcd/helm-controller/blob/961856236f57fd41e9520c3e9ce8aad52611b0b7/api/v2beta1/reference_types.go#L21-L42). 

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: Kustomization
metadata:
  name: backend
  namespace: default
spec:
      ...
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      ...
  dependsOn:
    - name: backend
      kind: Kustomization
      apiVersion: source.toolkit.fluxcd.io/v1beta1
```

#### Technical discussion
Hiddeco mentioned a desire not to have the `source-controller` and `helm-controller` API be coupled together, which makes sense. This functionality could follow how `healthChecks` in `Kustomization` works and use the [kstatus](https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus) standard for determining if a resource is ready, without having to hardcore in specific types.

Thoughts? The [eksctl/pitch-black-team](https://github.com/orgs/weaveworks/teams/eksctl) would be happy to work on PRs to implement this :smile:
