### DISCUSSION TITLE
Split GitRepository into GitRepository and GitRepositoryArchive

### DISCUSSION THREAD

**Discussion by bigkevmcd** [fluxcd/flux2#1604] [Proposals]
There are lots of things that it makes sense to reference a `GitRepository` in the sense of a repository, and access to that repository, but without the implied branch or archive access.

I'd like to see `GitRepository` split into two, where an _Archive_ archives a specific ref of a _Repository_ in the same way that the current _Repository_ does.

This would allow building on top of `GitRepository` objects for other references, without having to create a `GitRepository` for the specific ref.

**Comment by squaremo** [comment]
This can't happen exactly as stated, because the types can't change without breaking backward-compatibility. You might, however, have a new version of the API with distinct types (say `GitRepositoryAccess` and `GitRepositoryArchive`).

**Reply by hiddeco** [reply]
If we go that route, I would also like to reconsider having the artifact advertised within the resource, versus having an artifact as a separate resource produced by a source.

**Reply by squaremo** [reply]
Roughly what would be in the `spec` of each kind of object?

**Reply by hiddeco** [reply]
Rough sketch (without `spec` details):

The idea would be that the URL and credentials are in `GitRepositoryAccess`.

User can create a `GitRepositoryArchive` that contains the ref selector, but this ref selector can now match ranges too, or be "rolling" while giving insights into previous revisions, it would also include GC settings for the below object (think K8s jobs).

The `GitRepositoryArchive` produces an `Artifact` resource (with an owner reference) for every ref that matches the selector, these artifacts are handled by another reconciler which knows how to create an artifact based on the absolute reference that is now declared, the artifact is then advertised on this object.

**Reply by bigkevmcd** [reply]
Initially I'm thinking...

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: demo-repository
spec:
  url: https://github.com/fluxcd/source-controller.git
  secretRef: ...
  gitimplementation: ... # not sure about this, I see this as a hint to consumers?
  include:
    - ...
```
 
And the Archive

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepositoryArchive
metadata:
  name: demo-repository-archive
spec:
  repositoryRef:
      name: demo-repository
  interval: 1m
  ref:
    branch: master
  suspend: true
  ignore: ...
  recurseSubmodules:
  gitimplementation: ...
```

**Reply by stefanprodan** [reply]
I am not in favor of this change, for the end-user it adds a lot of toil, instead of 2 resources to sync a repo now they have to create 3 resources with no benefit, but added complexity. I agree that this would be an improvement for other tools that build on top of Flux, but even here I see no big advantage, what's the difference between reusing the Git auth secret in 2 GitRepo vs reusing the GitRepo in 2 GitRepoArchives? The tool still needs to generate 2 things, with less fields but is this worth it to introduce a new API, break everyone's usage of Flux, ask our users to migrate once more?

**Reply by bigkevmcd** [reply]
How about renaming them to just `GitRepositoryArchive` which better reflects what it actually does.

This would allow some sort of central GitRepository non-Flux object?

Most git repositories don't have a single ref in them, so it feels odd to have a `GitRepository` with a single ref.

**Reply by bigkevmcd** [reply]
> I am not in favor of this change, for the end-user it adds a lot of toil,

If this is about users and toil, then renaming it to `GitRepositoryArchive` feels like the most sensible thing, it clarifies the intent of the object and what it's describing.

> instead of 2 resources to sync a repo now they have to create 3 resources with no benefit, but added complexity. 

There are cognitive benefits, but, equally, it would allow building on top of the GitRepository, with things that use it for something other than archiving the source.

> I agree that this would be an improvement for other tools that build on top of Flux, but even here I see no big advantage, 
> what's the difference between reusing the Git auth secret in 2 GitRepo vs reusing the GitRepo in 2 GitRepoArchives? The 
> tool still needs to generate 2 things, with less fields but is this worth it to introduce a new API, break everyone's usage of 
> Flux, ask our users to migrate once more?

Git repositories are central to the model in most GitOps related processes.

I'd accept that reusing the secret in two GitRepositories is not much different, but there's a presumption that everything that references a GitRepository wants the archive, other processes that execute on top of cloned source will want lower-level access than the archive provides, for example hooking into processes that would provide validation of repositories would likely require specific refs, and creating a `GitRepository` for this purpose feels expensive, given the transient nature of the process.

**Reply by stefanprodan** [reply]
> How about renaming them to just GitRepositoryArchive which better reflects what it actually does.

Not a single Flux user complained about the source APIs naming so far, you are the first one. Adding the `Archive` suffix to GitRepository, HelmRepository, HelmChart and Bucket would break our promise to users as renaming means no conversion mechanism (Kubernetes CRDs do no support renaming of the Kind, only fields).

**Reply by hiddeco** [reply]
The issue it solves is not so much an issue for current Flux users (which is why you have not heard any complaints), but more about making the structure of our API objects more friendly for others to built upon, and we have not much feedback to go by there to use as a reference.

**Reply by stefanprodan** [reply]
I'm all for making the API more friendly for others to built upon but not at the expense of end-users. IMO, adding a new resource type as a requirement to do anything with Flux and changing the whole API surface in a backwards incompatible manner would damage Flux image and would push end-users to other solutions.

**Reply by hiddeco** [reply]
API consumers are also our (end-)users, but for the GitOps Toolkit SDK.

I think that shooting an idea because of the impact it has is never a good reason. It is better to weight something based on the value it adds and/or the problem it solves. Once that has been weighted, you can look at the impact, and how this can potentially be worked around and/or reduced.

I feel like the first step was very much skipped because of the second thing.

**Reply by stefanprodan** [reply]
@hiddeco I remember you made a proposal (at one of the Flux dev meetings) for an `Artifact` resource, auto-generated by Flux, that could be used to track revisions, diffing manifests inside the cluster, rollback, etc. I think an auto-generated object that doesn't affect end-users is a great way of helping those that build on top of Flux.

**Reply by hiddeco** [reply]
That is the bottom layer that I described here: https://github.com/fluxcd/flux2/discussions/1604#discussioncomment-979072. Kevin's adds a top one that makes it easier for our own image-automation-controller to just look for a repository reference and credentials, but also for others.

I can absolutely see how this would be valuable, especially in combination with my ~proposal~ rough sketch.

**Reply by stefanprodan** [reply]
If the GitRepository becomes just a reference to a secret with all the cloning config in a different object, then maybe a Kubernetes [secret type](https://kubernetes.io/docs/concepts/configuration/secret/#secret-types) (e.g. `git.fluxcd.io/ssh-auth`, `git.fluxcd.io/basic-auth`) would suffice and IAC could take a reference to a secret with that type.

**Reply by squaremo** [reply]
> If the GitRepository becomes just a reference to a secret with all the cloning config in a different object, then maybe a Kubernetes [secret type](https://kubernetes.io/docs/concepts/configuration/secret/#secret-types) (e.g. `git.fluxcd.io/ssh-auth`, `git.fluxcd.io/basic-auth`) would suffice

Yes, with the URL included (and potentially the only field).

An argument against this is that you might want to hang other things off the object. It might be the location of "namespace access grants", for example, which could solve some awkwardness both for kustomize-controller-style applications and for automation.

**Reply by stefanprodan** [reply]
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: podinfo-auth
type: git.fluxcd.io/basic-auth
data:
  url: <value>
  username: <value>
  password: <value>
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo-releases
spec:
  interval: 1m
  url: # if not specified the value is inferred from the secret (made optional in v1beta2)
  ref:
    semver: ">=3.1.0-rc.1 <3.2.0"
  secretRef:
    name: podinfo-auth
```

Given the above, every time a tag is pushed, source-controller generates an `Artifact` object. From an enduser perspective this doesn't changes much, `flux bootstrap` and `flux create secret git` would append the URL to existing secrets. Then IAC would allow secretRef and deprecate sourceRef, then at GA time,  remove sourceRef. This also ends the cross-namespace dilemma for IAC, as we don't allow cross-ns secrets sharing at all.

**Reply by hiddeco** [reply]
The new problem this would introduce is that it will be impossible to validate the custom secret types (during apply), because:

> You can define and use your own Secret type by assigning a non-empty string as the type value for a Secret object. An empty string is treated as an `Opaque` type. Kubernetes doesn't impose any constraints on the type name. However, if you are using one of the builtin types, you must meet all the requirements defined for that type
> &mdash; https://kubernetes.io/docs/concepts/configuration/secret/#secret-types

**Reply by stefanprodan** [reply]
> The new problem this would introduce is that it will be impossible to validate the custom secret types (during apply)

You can validate it with a custom webhook or OPA/Kyverno. We already impose specific keys in secrets, adding url to the auth secret that already requires username/password is not such a big or impactful change IMO.

**Reply by stefanprodan** [reply]
Regardless of my proposal here, I think we should introduce Flux secret types and use an existing policy solution (OPA/Kyverno) to validate the secret keys, as all our custom resource require secrets in a specific format, from Git to Helm to SOPS to PGP signatures.

**Reply by hiddeco** [reply]
That is something I am in favor of.

I do however think (while setting backwards-compatibility concerns aside for a moment) that having a separate object over a secret type may be more beneficial for the reasons mentioned by Michael, but also because it gives you a concrete (structured) type to work with that is easier to document, understand (as a Flux end-user), and use (as an API consumer).

**Reply by stefanprodan** [reply]
Due to security reasons like at rest encryption of Kubernetes secrets, we can't have a custom resource that replaces the secret. Sure we can have `GitRepositorySecret/HelmRepositorySecret/SOPSSecret/ PGPSecret/AgeSecret` that references a secret, but I don't see any benefits to this for the end-user, just more YAMLs to maintain.

**Reply by hiddeco** [reply]
Yes, I understand how at reset encryption of Kubernetes secrets work, and that we can not introduce our own secret type.

I was more thinking of:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: podinfo-auth
type: git.fluxcd.io/basic-auth
data:
  username: <value>
  password: <value>
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
spec:
  # This is required, and can be validated during apply
  # It can also be shown in e.g. `kubectl get` output
  url: https://github.com/stefanprodan/podinfo.git
  # This is optional, any validation errors can now be reflected on this object
  secretRef:
    name: podinfo-auth
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
# Or another name we reach consensus over
kind: GitRepositoryArchive
metadata:
  name: podinfo
spec:
  interval: 1m
  repositoryRef:
      name: podinfo
  ref:
    branch: master
```
