### DISCUSSION TITLE
HelmRepository & Azure CR

### DISCUSSION THREAD

**Discussion by bitva77** [fluxcd/flux2#1608] [Q&A] [answered]
Hi!  Anyone able to get HelmRepository with charts stored under Azure CR working?  I keep getting this message:

```
failed to download repository index: failed to fetch https://repo.azurecr.io/charts/microservice/index.yaml : 404 Not Found
```

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: commoncr
  namespace: stage
spec:
  interval: 1m
  url: https://repo.azurecr.io/charts/microservice/
  secretRef:
    name: helmrepo-commoncr
```
Using helm (v3), I can login and do a `helm chart pull https://repo.azurecr.io/charts/microservice:0.0.1`

I can see that `/helm/v1/repo/index.yaml` exists and has some old chart when we were first trying things out.  I'm wondering now if we should be pushing charts to the root and ACR updates this `/helm/v1/repo/index.yaml` path?
