### DISCUSSION TITLE
How to ignore events without changes?

### DISCUSSION THREAD

**Discussion by cnwangjie** [fluxcd/flux2#1618] [Q&A]
I'd like to receive notifications if any changes are performed. Because flux will execute regularly and there are no changes, I'll receive so many notifications with the message 'Update completed'. Can I ignore these notifications without changes?

Below is my current config.

```yml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: notification-info
  namespace: flux-system
spec:
  providerRef:
    name: forward-flux-event
  eventSeverity: info
  eventSources:
    # because my current helm repository will return dynamic field so the helm repository events are too many, so I'd rather not notify me
    # - kind: HelmRepository
    #   name: '*'
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'

```
