### DISCUSSION TITLE
Integrate with GitHub Deployments

### DISCUSSION THREAD

**Discussion by billyshambrook** [fluxcd/flux2#1624] [Proposals]
Hey, am playing with the idea of how to use GitHub Deployment API to drive deployments in a gitops way. GitHub Deployments API is nice because it provides a UI within GitHub which shows what commits are currently deployed within each environment. This is also useful for doing pull request deployments you can add a URL to the deployment where the deployment can be accessed from which also shows up in the pull request UI.

Was wondering if it makes sense to allow referencing a deployment environment in the GitRepository API. The controller could then fetch the commit sha from the latest deployment that matches that environment, something like:

```yaml
apiVersion: source.fluxcd.io/v1alpha1
kind: GitRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1m
  url: https://github.com/stefanprodan/podinfo
  ref:
    deployment: production
```

You could then trigger the controller by creating a new deployment like so:

```bash
curl -X POST -H "Authorization: Bearer ${GITHUB_TOKEN} --data '{"ref": "master", "environment": "production"}' https://api.github.com/stefanprodan/podinfo/deployments
```

The new deployment would include the latest sha from the master branch which can be used to grab the latest source.

This however does require the "cluster controller" (e.g. kustomize-controller) to update the deployment status once it has been applied - not sure where this would fit in with regards to the gitops toolkit.

Another problem I can see is that this is GitHub specific but `GitRepository` looks like it should work with any Git provider, not sure if other Git providers have a similar concept which could be used or whether this should be a different kind e.g. `GitHubRepository` or `GitHubDeployment`
