### DISCUSSION TITLE
failed to retrieve source: HelmRepository.source.toolkit.fluxcd.io "traefik" not found

### DISCUSSION THREAD

**Discussion by devsin** [fluxcd/flux2#1631] [Q&A] [answered]
Hello all, newbie here! 

I create HelmRepo and HelmRelease with `flux` command and push to my gitops git repo. But I got these following errors: 
`HelmChart 'traefik/traefik-traefik' is not ready`
`failed to retrieve source: HelmRepository.source.toolkit.fluxcd.io "traefik" not found`
You can also look at the screenshot: [SS](https://ibb.co/3BgKp6w)

What I am missing here? Also I create mongodb with the same folloing steps and I got same error. 
`k8s version: 1.21`

Here are my steps: 

.yaml generation command: 
```
flux create source helm traefik \
--url https://helm.traefik.io/traefik \
--interval 1m0s \
--export > helm.repo.traefik.yaml
```
generated yaml:
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://helm.traefik.io/traefik
```

.yaml generation command: 
```
flux create helmrelease traefik \
  --chart=traefik \
  --source=HelmRepository/traefik \
  --chart-version=10.0.0 \
  --namespace=traefik \
  --interval 10m0s \
  --export  > helm.app.traefik.yaml
```
generated yaml:
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 10.0.0
  install: {}
  interval: 10m0s
```

**Comment by kingdonb** [comment, marked as answer]
It looks like you have made a cross-namespace reference in your HelmRelease which lives in the `traefik` namespace, to the HelmRepository in `flux-system` namespace, but you have not identified the namespace.

This is a context where cross-namespace references are allowed, but your `sourceRef` must be explicit about it, eg:

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      version: 10.0.0
  install: {}
  interval: 10m0s
```

Please give that a try and let us know if it solves your issue!

**Reply by devsin** [reply]
Hey @kingdonb,

You are right, the problem was about the namespace conflict. Thank you very much.  

But the problem solved by when I change the repo namespace. I tried with other combinations but I only solve the problem like following. 

Here are .yaml files last status:

helm.repo.yaml
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1m0s
  url: https://helm.traefik.io/traefik
```

helm.app.yaml
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 10.0.0
  install: { }
  interval: 10m0s

```
