### DISCUSSION TITLE
ImageUpdateAutomation not updating deployment image

### DISCUSSION THREAD

**Discussion by jwerre** [fluxcd/flux2#1638] [Q&A] [answered]
Hello,

I seem to be all set up correctly but from some reason my image isn't being updated.

I have an file structure that looks something like this:

```
├── README.md
├── main
│   ├── api
│   │   ├── deployment.yaml
│   │   ├── automation.yaml
│   │   └── service.yaml
│   ├── app
│   │   ├── deployment.yaml
│   │   ├── automation.yaml
│   │   └── service.yaml
│   ├── flux-system
│   │   ├── gotk-components.yaml
│   │   ├── gotk-sync.yaml
│   │   └── kustomization.yaml
│   ├── image_update_automation.yaml
```

My `api/automation.yaml` is pretty strait-forward:

```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: api
  namespace: flux-system
spec:
  image: xxx/api
  interval: 1m0s
  secretRef:
    name: dockerhub

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: api
  policy:
    semver:
      range: ">=1.0.0"
```

My `image_update_automation.yaml` looks something like this:

```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: deploy@example.com
        name: deployment
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./staging
    strategy: Setters
```

Everything seems to be ok here:

```bash
❯ flux get image repository
NAME	READY	MESSAGE                       	LAST SCAN                	SUSPENDED
api	True 	successful scan, found 23 tags	2021-07-28T17:11:02-06:00	False
app	True 	successful scan, found 18 tags	2021-07-28T17:11:02-06:00	False

❯ flux get image policy
NAME	READY	MESSAGE                                                            	LATEST IMAGE
api	True 	Latest image tag for 'xxx/api' resolved to: 1.0.1	xxx/api:1.0.1
app	True 	Latest image tag for 'xxx/app' resolved to: 3.2.1	xxx/app:3.2.1
```

However when I view the current version of my app and api they have not been updated.

```bash
kubectl get deployment api -n xxx -o json | jq '.spec.template.spec.containers[0].image'
"xxx/api:0.1.5"
```
Any advice on this would be much appreciated.
