### DISCUSSION TITLE
When I try to create a ConfigMap with flux2 I am getting `missing key` error

### DISCUSSION THREAD

**Discussion by devsin** [fluxcd/flux2#1649] [Q&A] [answered]
Hey all, me again!

When I try to create a CM with flux2 I am getting this error: 

`missing key 'values.yaml' in ConfigMap 'default/mydb-init-script'`

Here is the my case:

I wanted to update my current HelmRelease with new CM like following: 

release.yaml
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mydb
  namespace: default
spec:
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 10.20.0
  install: { }
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: mydb-init-script
      valuesKey: values.yaml
  values:
    architecture: replicaset
    auth:
      rootPassword: secretpass
      replicaSetKey: repkey
    initdbScriptsConfigMap: mydb-init-script
```

values.yaml

```
apiVersion: v1
data:
  script.js: |-
    sleep(10000);
    db.getSiblingDB('mydb').createUser({ user: 'myuser', pwd: '12341234', roles: [{role: 'readWrite', db: 'mydb'}] });
kind: ConfigMap
metadata:
  name: mydb-init-script
  namespace: default
```

I pushed these changes my gitops repo. And I got an error that I share above.

**Comment by hiddeco** [comment, marked as answer]
You refer to `values.yaml` in your `valuesKey` but the actual data is in `script.js` (the `data` field of a `ConfigMap` is not seen as a full `values.yaml`, but a key is, with as default `data.values.yaml`).

I had a look at [the `values.yaml` of your chart](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml) but could not discover what you are trying to do exactly, my best guess is that you want to import them as `initdbScripts`, in which case your `ConfigMap` should look more like something of the following:

```yaml
apiVersion: v1
data:
  values.yaml: |-
    initdbScripts:
      script.js: |
        sleep(10000);
        db.getSiblingDB('mydb').createUser({ user: 'myuser', pwd: '12341234', roles: [{role: 'readWrite', db: 'mydb'}] });
kind: ConfigMap
metadata:
  name: mydb-init-script
  namespace: default
```

Another option would be to drop the `valuesFrom` reference from the `HelmRelease` and refer to the `ComfigMap` simply be setting `initdbScriptsConfigMap`, this overwrites the `initdbScripts` configuration. At present, you have both defined which makes one of the options obsolete.

In addition, [reading the documentation about `valuesFrom` references](https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-in-configmap-and-secret-resources) may help you better understand the available flags and how they can be combined.

**Reply by devsin** [reply]
Hey @hiddeco,

Thanks I solved the problem. 


First of all I'll explain what excatly I was trying to do. Before the flux I was creating a ConfigMap with this command: 
`kubectl create configmap mydb-init-script --from-file=script.js`

script.js: 
```
sleep(10000);
db.getSiblingDB('mydb').createUser({ user: 'myuser', pwd: '12341234', roles: [{role: 'readWrite', db: 'mydb'}] });
```

Then when I was creating my helm release with helm command and with this setting`--set initdbScriptsConfigMap: mydb-init-script`;  it was running the initscript on the my helm release.

I just want to reproduce this installation with flux but I couldn't manage that.

But when you spotlight the bitnami/mongodb chart; this time I tried to embed the initscript to the HelmRelease without CM.
I editted my release like following and it worked:

`Please notice that:  initdbScripts: config`

release.yaml
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mydb
  namespace: default
spec:
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 10.20.0
  install: { }
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: mydb-init-script
      valuesKey: values.yaml
  values:
    architecture: replicaset
    auth:
      rootPassword: secretpass
      replicaSetKey: repkey
    initdbScripts:
      scrpit.js: |
        sleep(10000); // it's required to wait primary back after initial restart
        db.getSiblingDB('mydb').createUser({ user: 'mydb', pwd: '12341234', roles: [{role: 'readWrite', db: 'mydb'}] });
```

**Reply by devsin** [reply]
Furthermore, I read  again and again that part you share from ducmentation but I couldn't undertand excatly what was saying. Maybe it is because  lack of my English. Or maybe the documentation it's not really newbie friendly. :) 

For instance:
In that part it says `valuesKey: values-prod.yaml` but I have no idea what it could be that `values-prod.yaml`.

**Reply by hiddeco** [reply]
The `values-prod.yaml` refers to e.g. `data.values-prod.yaml`, for example:

```yaml
apiVersion: v1
data:
  values-prod.yaml: |-
    foo: bar
kind: ConfigMap
metadata:
  name: my-values
  namespace: default
```

Hope this makes it more clear to you :-)
