### DISCUSSION TITLE
Make chart updates more like image updates

### DISCUSSION THREAD

**Discussion by withnale** [fluxcd/flux2#1665] [Proposals] [answered]
To me one of the main strengths of flux is the ability to have an unambiguous definition of state under change control in git.

This works well with image updates, and although it's now more work in fluxv2 compared to fluxv1 I can still roll back my repo to a previous state and know I have the correct running config for that point.

For fluxv2 this is mainly based on comments in the git repo that look something like this:

```yaml
  values:
    myapp:
      image:
        tag: master-v1.0-100-g6491504 # {"$imagepolicy": "flux-system:myapp:tag"}

```

This works fine, and when a new image appears both the repo and cluster get updated with an explicit reference to the new tag.

However, it doesn't work like this with helm chart updates. Consider the snippet below:

```yaml
    chart:
      spec:
        chart: mypersonalchart
        sourceRef:
          kind: HelmRepository
          name: mypersonalrepo
          namespace: flux-system
        version: '> 0.1.0'
```

In the above scenario, the reference to the chart will remain a floating definition. If I ever have to roll back to last Thursdays git repository, it is still going to want to make use of the most recent chart.

Is there any mileage in implementing a similar solution for chart updates to the existing image update approach?
