### DISCUSSION TITLE
Changing HelmRelease value overrides

### DISCUSSION THREAD

**Discussion by stevendick-work** [fluxcd/flux2#1667] [Q&A] [answered]
In our current use of Helm we specify the pod replicaCount as a Helm override so we can change this on a per-environment/per-deployment basis.

I notice when experimenting with Flux that if I modify the replicaCount in the values section of a HelmRelease, Flux reconciles but it does not apply the change to the replicaCount.

I haven't yet experimented with other values we override in the HelmRelease yet to see if they show the same behaviour.

To be clear, I am only changing the values that are applied as Helm overrides - I am keeping the chart name and version the same.

Here's an example HelmRelease manifest:
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ecp-llcd-service
  namespace: iee-ecp
spec:
  chart:
    spec:
      chart: ecp-llcd-service
      sourceRef:
        kind: HelmRepository
        name: devacr
      version: 2.0.28
  install: {}
  interval: 5m0s
  values:
    appconfig:
    - name: appcfg-central-apps-npd-euwe-3
      prefixes:
      - /iee/ietv/central/kafka-3/
      - /iee/ietv/central/lookup/
      - /iee/ietv/central/auth/
    - name: appcfg-ecp-npd-euwe-3
      prefixes:
      - /iee/appinsights/
    correlationId: iee
    image:
      registry: acrietvdeveuwe1.azurecr.io
    ingress:
      host: ecp-llcd-service-iee.npd-3.ietv.swissre.com
    java:
      args:
      - -javaagent:app-insights-agent.jar
      - -XX:+AlwaysActAsServerClassMachine
      - -Xms768m
      - -Xmx768m
      - -Dspring.main.banner-mode=off
      - org.springframework.boot.loader.JarLauncher
    replicaCount: 1
```
