### DISCUSSION TITLE
Trigger build in Kustomization when ConfigMap Changes using  `substituteFrom`

### DISCUSSION THREAD

**Discussion by metasim** [fluxcd/flux2#1680] [Q&A]
In our system, image tags are in a single ConfigMap so we have a cluster-wide single point of authority. We use the `Kustomization/spec/postBuild/substituteFrom` feature to inject the image tags into other downstream `Kustomization` objects. The structure looks something like this:

---

![image](https://user-images.githubusercontent.com/131013/128046631-388aa601-b179-45b0-be68-ad8d538aaec4.png)

---

The problems is when we commit changes to the `versions` ConfigMap, the `kustomize-operator` doesn't seem to be automatically reconciling `app1` and `app2`. We end up having to run `flux reconcile kustomization app1 --with-source` for the deployment to occur as needed.

I've tried adding something like this to the downstream GitRepository resources, but that doesn't seem to work either:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: app1
spec:
....
  include:
    - repository:
        name: flux-system
      fromPath: deployments/versions.yaml
      toPath: deployment/flux
```

Is this kind of workflow supported? Any tips appreciated.
