### DISCUSSION TITLE
toolkit: Reconciliation status as Prometheus metrics

### DISCUSSION THREAD

**Discussion by stefanprodan** [fluxcd/flux2#170] [Proposals] [answered]
The toolkit controllers are recording the reconciliation status in a condition named **Ready**:

```yaml
status:
  conditions:
  - type: Ready
    lastTransitionTime: "<last status change timestamp>"
    message: "<human readable description including errors if any>"
    reason: "<Progressing|Suspended|DependencyNotReady|ReconciliationSucceeded|etc>"
    status: "<Unknown|True|False>"
```

### Metric spec

We could export the ready condition as a Prometheus gauge:

```
gitops_toolkit_ready_condition{kind, name, namespace, reason} [-2,-1,0,1]
```

Gauge values:

* status.Unknown = 0
* status.True = 1
* status.False = -1
* finalizer = -2

Alert manager example:

```yaml
groups:
- name: GitOpsToolkit
  rules:
  - alert: ReconciliationFailure
    expr: gitops_toolkit_ready_condition == -1
    for: 10m
    labels:
      severity: page
    annotations:
      summary: '{{ $labels.kind }} {{ $labels.namespace }}/{{ $labels.name }} reconciliation has been failing with {{ $labels.reason }} for more than ten minutes.'
```

### Implementation spec

Create a `metrics` library in `fluxcd/pkg` that:

* contains the Ready condition struct
* registers the ready condition as a controller-runtime metric
* exposes a function to record the status changes

### Monitoring stack

The ready condition metrics would allow us to build Grafana dashboards for monitoring the reconciliation process and drilldown  to individual objects. The dashboards could be used to diagnose specific issues if we plot the reconciliations failures grouped by kind/namespace/name/reason.
