### DISCUSSION TITLE
RFP: Using OCI artifacts as sources

### DISCUSSION THREAD

**Discussion by squaremo** [fluxcd/flux2#1705] [Proposals]
It's been suggested several times, in different places, to make OCI artifacts* available as a source. A few things recommend using OCI:

 - artifacts are immutable, like git
 - they can be signed, like git
 - there's lots of tooling for building, distributing and serving images (that mostly also works for artifacts)
 - if you are running a CI pipeline to verify your configuration, it makes sense to stick the verified configuration in an immutable, distributable form at the end

*What is an OCI _artifact_ as opposed to an OCI image? An OCI image is the standardised form of a Docker image, that is something you can run. An artifact is the more general specification, which shares the manifest, index and layer bits of OCI images, but you can define your own format. This article does a good job of explaining what artifacts are: https://dlorenc.medium.com/oci-artifacts-explained-8f4a77945c13

Related issues and discussions:

 - There's an issue already for using [Helm charts from OCI registries](https://github.com/fluxcd/source-controller/issues/124).

### Design and implementation notes:

**Handling different media types**

[OCI artifacts](https://github.com/opencontainers/artifacts) come in different formats -- it's not just runnable container images any more, and not just an overlay filesystem in tarballs. In general, formats will _not_ be suitable for distributing Kubernetes configuration; and, each format will have its own layout of files in layers. So I would expect an implementation to handle specific media types, rather than try to be generic across media types.

A particular case is Helm charts in OCI artifacts: these are suitable for consumption by the helm-controller, and not by anything else. But, in the spirit of remaining duck-typed, it's OK to let people mix and match as they wish.

**Relation to image.toolkit.fluxcd.io API**

The image.toolkit.fluxcd.io API has these types:

 - ImageRepository, representing an image repository to be scanned (and referring to secrets needed to do so)
 - ImagePolicy, representing a rule for picking a "latest image" from an ImageRepository
 - ImageUpdateAutomation, which uses the calculate "latest image" from ImagePolicy objects to make changes in a source (which is currently restricted to a git repository).

These stand alone, but there is clear overlap in the arrangement of ImageRepository and ImagePolicy, and what an OCI source would do. There are some alternatives for how to account for this:

 1. **Refer to a policy from the source type**. That is, have a type OCIArtifact that refers to an image policy which selects the particular image to serve to consumers.
 2. **Make an image policy (optionally) behave like a source**. This might involve a switch in the ImagePolicy type `useAsSource`, which is understood by a separate controller (source-controller or another); or, something to switch it on for some subset of ImagePolicy types, from outside, e.g., by namespace.
 3. **Use a disjoint type**. At least the GitRepository type mixes definition of the repository and the policy, so why not do this for OCI artifacts, and have an OCIArtifact type which combines ImageRepository, ImagePolicy, and acting as a source.

**Comment by souleb** [comment]
As an example the tekton project uses OCI artifacts to store `tasks` in a container registry instead of a crd in etcd. The `tasks` can then be referenced with an objectRef in a pipeline declaration.
https://tekton.dev/docs/pipelines/pipelines/#tekton-bundles

**Comment by stefanprodan** [comment]
## Use a disjoint type proposal

I propose we add a command to Flux CLI that bundles a directory containing Kubernetes manifests and/or Kustomize overlays, pushes the artifact to an OCI registry (using the local docker config) and optinally signs the artifact with a [sigstore](https://www.sigstore.dev/) key.

Example command:

```sh
flux bundle -f ./deploy -t ghcr.io/stefanprodan/podinfo-deploy:v1.0.0 -s cosig.key
```

As for the API, I opt for `Use a disjoint type`. I propose we add a new API type to the source-controller named `ArtifactRepository`.

Example of a source that pulls a fixed version from the OCI registry and verifies its authenticity using [sigstore](https://www.sigstore.dev/):

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: ArtifactRepository
metadata:
  name: podinfo-release
  namespace: flux-system
spec:
  interval: 10m
  image: ghcr.io/stefanprodan/podinfo-deploy
  secretRef:
    name: regcred
  tag: "1.0.0"
  verify:
    secretRef:
      name: sigstore-keys
```

Example of a source that pulls the latest tag based on timestamp ordering:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: ArtifactRepository
metadata:
  name: podinfo-nighlty-builds
  namespace: flux-system
spec:
  interval: 10m
  image: ghcr.io/stefanprodan/podinfo-deploy
  secretRef:
    name: regcred
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
```

Example of a source that pulls the latest tag based on semver ordering:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: ArtifactRepository
metadata:
  name: podinfo-release-candidates
  namespace: flux-system
spec:
  interval: 10m
  image: ghcr.io/stefanprodan/podinfo-deploy
  secretRef:
    name: regcred
  filterTags:
    pattern: '.*-rc.*'
  policy:
    semver:
      range: '^1.x-0'
```
