### DISCUSSION TITLE
Override terminationGracePeriodSeconds does not work

### DISCUSSION THREAD

**Discussion by Andreik8s** [fluxcd/flux2#1736] [General]
I have an app running on GKE, deployed as HelmRelease with flux. I want to change the terminationGracePeriodSeconds from the default value 30 to less like 20. But, I'd like to do it from the HelmRelease spec file. I have added it at the HelmRelease spec, then to the pod and deployment section but it does not change.

According to the docs https://fluxcd.io/docs/components/helm/helmreleases/#values-overrides you say is possible to do it via values but this also does not work.

My spec looks like:
```
spec:
  releaseName: name-api
  chart:
    git: git@gitlab link to our chart which is a monochart/template
    path: "."
    ref: v1.0.0
  values:
    terminationGracePeriodSeconds: 20
    nameOverride: "name-api"
    fullnameOverride: "name-api"
    image: our custom image
    imagePullSecrets:
    - docker-registry
    replicaCount: 1
```

Any idea why the values does not help? 

I have also tested this on minikube with the same HelmRelease and still does not possible to override.

Thanks
