### DISCUSSION TITLE
is there a way to customize alert message for ImageUpdateAutomation (like commit one)

### DISCUSSION THREAD

**Discussion by mikalai-t** [fluxcd/flux2#1752] [Q&A]
in order to receive a new image version info instead of just simple Helm upgrade result (in our case Helm chart version is only updated when we introduce new feature/hotfix to the chart itself)
![image](https://user-images.githubusercontent.com/20296197/130815228-041e9523-900b-42ef-9dbd-190969e04a54.png)

**Comment by stefanprodan** [comment]
I think that the image-automation-controller could send an event with the same body as the commit message, so it will display in Slack the same info as in git history. cc @squaremo

**Reply by squaremo** [reply]
I can see this being useful, yep.

Which of these are you advocating for, @stefanprodan:
 - replace the current Info event message with the commit message
 - send another event, with the commit message

The first one might upset people who rely on the set message (but that might be no people); the second one might upset people who only like getting one notification.

Perhaps adding to the API is the way to do it:

```yaml
spec:
  push:
    eventMessageTemplate: |
      Here's what I did, I updated ....
```

That's pretty flexible, but a bit of a pain if you want exactly the commit message.

**Reply by squaremo** [reply]
Alternatively, just switch the additional event on:

```yaml
spec:
  push:
    sendCommitMessageEvent: true
```
