### DISCUSSION TITLE
Postbuild substitution with multilines

### DISCUSSION THREAD

**Discussion by karl-dpg** [fluxcd/flux2#1767] [Q&A] [answered]
Is it possible to use postbuild variables substitutions that contain multiline YAML? Example:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  PROMTAIL_CHART_VERSION: 3.8.1
  AFFINITY: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: k8s.tst.com/node-purpose
                operator: In
                values:
                  - compute-optimized
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tools
  namespace: flux-system
spec:
  interval: 10m0s
  path: .
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/part-of: monitoring
spec:
  releaseName: promtail
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: ${PROMTAIL_CHART_VERSION}
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    fullnameOverride: promtail
    affinity: ${AFFINITY}
```

The above does not work and generates the below error:
```
var substitution failed for 'promtail': YAMLToJSON: yaml: line 21: mapping values are not allowed in this context
```

I think it's a problem of indentation that is producing incorrect YAML but so far I haven't found a way to confirm.

PS: Maybe the solution lies in using `postStartegicMerge`, however I'm exploring the possibility of only using variable substitution mechanism since it greatly simplifies structure and improves readability.

**Comment by xeor** [comment]
Did you come to any conclusion? Looking for the same thing :)

**Reply by kingdonb** [reply]
It is not possible to my knowledge, a multiline string can not be substituted into a Flux config via envsubst aka the Kustomize controller postbuild substitution feature in that way. If you need to update a manifest with a replacement value that contains a multiline YAML, then I think you will have to use a patches directive or patchesStrategicMerge overlay instead.

**Comment by stefanprodan** [comment, marked as answer]
The variables substitution feature in Flux is not meant to replace Helm or become a full featured templating engine for Kubernetes objects. I have added this feature to kustomize-controller to overcome the limitations of kustomize’s vars. If you want to manipulate YAML documents, you can use the Flux [patching capabilities](https://fluxcd.io/docs/components/kustomize/kustomization/#patches) or switch to Helm.

**Reply by airtonix** [reply]
except that https://fluxcd.io/docs/components/kustomize/kustomization/#patches doesn't describe if you can do this: 

```
clusters/
  default/
    flux-system/
      ...
    things-system.yaml        1️⃣
    config-and-secrets.yaml   2️⃣

cluster-systems/
  default/
    things/
      kustomization.yaml      3️⃣
      a-certmanager-thing-issuer-patch.yaml       4️⃣

manifests/
  apps/
    a-certmanager-thing/      
      kustomization.yaml   
      helm-release.yaml
      issuer.yaml             5️⃣
```

<details>
  <summary>1️⃣ things-system.yaml</summary>
  
  ```yaml
  ---
  apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
  kind: Kustomization
  metadata:
    name: apps-system
    namespace: flux-system
  
  spec:
    interval: 5m0s
    dependsOn:
      - name: config-and-secrets
    sourceRef:
      kind: GitRepository
      name: flux-system
    path: ./cluster-systems/default/things
    prune: true
    wait: true
    timeout: 5m0s
    decryption:
      provider: sops
      secretRef:
        name: sops-age
    postBuild:
      substituteFrom:
        - kind: ConfigMap
          name: cluster-config
        - kind: Secret
          name: cluster-secret

  ```
</details>

<details>
  <summary>2️⃣ config-and-secrets.yaml</summary>
    
  ```yaml
  ---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: cluster-config
    namespace: flux-system
  data:
    THING_NAME: this-is-the-thing-name
  ---
  apiVersion: v1
  kind: Secret
  metadata:
      creationTimestamp: null
      name: cluster-secret
      namespace: flux-system
  type: Opaque
  stringData:
      CERTMANAGER_CLOUDFLARE_APIKEY: 😇
      CERTMANAGER_CLOUDFLARE_EMAIL: 😇
  sops:
      kms: []
      gcp_kms: []
      azure_kv: []
      hc_vault: []
      age:
          - recipient: 😇
            enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              😇
              -----END AGE ENCRYPTED FILE-----
      lastmodified: "2022-09-28T10:45:56Z"
      mac: 😇
      pgp: []
      encrypted_regex: ^(data|stringData)$
      version: 3.7.3
  ```
</details>

<details>
  <summary>3️⃣ cluster-systems/default/things/kustomization.yaml</summary>
    
  ```yaml
  ---
  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  resources:
    - ../../../manifests/apps/a-certmanager-thing
  
  patchesStrategicMerge:
    - ./a-certmanager-thing-issuer-patch.yaml
  ```
</details>

<details>
  <summary>4️⃣ cluster-systems/default/things/a-certmanager-thing-issuer-patch.yaml</summary>
    
  ```yaml
  ---
  apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
  kind: Kustomization
  metadata:
    name: podinfo
    namespace: flux-system
  spec:

    patches:
      - patch: |-
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: a-thing-certmanager-issuer
            namespace: a-thing
          
          spec:
            acme:
          
              email: ${CERTMANAGER_CLOUDFLARE_EMAIL}
          
              server: https://acme-v02.api.letsencrypt.org/directory
          
              privateKeySecretRef:
                name: letsencrypt-wildcard
          
              solvers:
                - selector:
                    matchLabels:
                      use-cloudflare-solver: "true"
          
                  dns01:
                    cloudflare:
                      email: ${CERTMANAGER_CLOUDFLARE_EMAIL}
                      apiKeySecretRef:
                        name: cluster-secrets
                        key: CERTMANAGER_CLOUDFLARE_APIKEY    
        target:
          kind: ClusterIssuer

  ```
</details>

<details>
  <summary>5️⃣ manifests/apps/a-certmanager-thing/issuer.yaml</summary>
    
  ```yaml
  ---
  apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: a-thing-certmanager-issuer
    namespace: a-thing
  
  spec:
    acme:
  
      email: ${CERTMANAGER_CLOUDFLARE_EMAIL}
  
      server: https://acme-v02.api.letsencrypt.org/directory
  
      privateKeySecretRef:
        name: letsencrypt-wildcard

  ```
</details>
