### DISCUSSION TITLE
Reference a Git Repository from a different namespace

### DISCUSSION THREAD

**Discussion by lapwat** [fluxcd/flux2#1773] [Q&A] [answered]
Hello, is it possible to tell Flux to use a Git Repository from another namespace ?

# What I would like to do

- `GitRepository` in flux-system
- `ImageUpdateAutomation` in mynamespace
- `ImagePolicy` in mynamespace
- `ImageRepository` in mynamespace

```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: mynamespace # <- image automation should be in this namespace
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: xxx@xxx.xxx
        name: xxx
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: update
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system # <- use git repo of flux system namespace
  update:
    path: ./main
    strategy: Setters
```

# What does not work or has been done wrong

- `GitRepository` in **flux-system**
- `ImageUpdateAutomation` in **flux-system**
- `ImagePolicy` in mynamespace
- `ImageRepository` in mynamespace

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release
  namespace: mynamespace
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/xxx
      version: 'x.x.x'
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    environment: dev
    image: imagetag.imagehash # {"$imagepolicy": "mynamespace:release"}
```

The issue with this approach is that `ImageUpdateAutomation` does not trigger even if `ImagePolicy` fetches the right image. I think it behaves like that because the two resources **are not in the same namespace.**
