### DISCUSSION TITLE
cannot reference default GitRepository in ImageUpdateAutomation

### DISCUSSION THREAD

**Discussion by masterkain** [fluxcd/flux2#1805] [Q&A] [answered]
hello,
I'm not sure what else to check, for an app (sendy) I've put down `ImageRepository`, `ImagePolicy`, `Receiver` in the app namespace `sendy`, now I've written an `ImageUpdateAutomation` referring to the existing GitRepository that flux creates:

```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: sendy
  namespace: sendy
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  update:
    path: ./clusters/mycluster
    strategy: Setters
```

but in the image automation controller I see this `referenced git repository does not exist`

```json
{"level":"error","ts":"2021-09-10T10:06:28.142Z","logger":"controller-runtime.manager.controller.imageupdateautomation","msg":"referenced git repository does not exist","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"sendy","namespace":"sendy","error":"GitRepository.source.toolkit.fluxcd.io \"flux-system\" not found"}
```

do I need to create the same repo in the sendy namespace?

**Comment by masterkain** [comment]
I referenced this repo in some other `HelmRelease` and it worked, but there we are able to specify a namespace:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: errbit
spec:
  releaseName: errbit
  chart:
    spec:
      chart: ./charts/errbit-helm
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
```

I can't see `namespace` support in `sourceRef` spec for ImageAutomation

https://fluxcd.io/docs/components/image/imageupdateautomations/#specification

```go
// SourceReference contains enough information to let you locate the
// typed, referenced source object.
type SourceReference struct {
	// API version of the referent
	// +optional
	APIVersion string `json:"apiVersion,omitempty"`

	// Kind of the referent
	// +kubebuilder:validation:Enum=GitRepository
	// +kubebuilder:default=GitRepository
	// +required
	Kind string `json:"kind"`

	// Name of the referent
	// +required
	Name string `json:"name"`
}
```
