### DISCUSSION TITLE
Kustomize HelmRelease rendered objects

### DISCUSSION THREAD

**Discussion by masterkain** [fluxcd/flux2#1808] [Q&A] [answered]
suppose I have a HelmRelease of this chart, and I want to update this object:

https://github.com/verdaccio/charts/blob/master/charts/verdaccio/templates/ingress.yaml

to bring it up to date with `spec.ingressClass` and whatnot.

is that possibile?

I was thinking that perhaps a file like that:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: verdaccio
  namespace: verdaccio
spec:
  patchesJson6902:
  - target:
      version: extensions/v1beta1
      kind: Ingress
      name: verdaccio
    patch:
    - op: replace
      path: /apiVersion
      value: networking.k8s.io/v1
```

would work but I realize I'm targeting a HelmRelease, not the final helm chart files.

any hint?
