### DISCUSSION TITLE
Secrets with a "hash" sufix

### DISCUSSION THREAD

**Discussion by rodrigoscferraz** [fluxcd/flux2#1841] [Q&A] [answered]
Hello guys! I'm trying to create a  secret with Kustomization like this:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: additional-scrape-configs
    files:
      - prometheus-additional.yaml
resources:
  - release.yaml
```

But for some reason the secret created has a hash suffix, and my chart can't found the secret.

The secret name result:
`additional-scrape-configs-dc2m65cfm9`

There is a way to remove this sufix or i'm doing something wrong?
