### DISCUSSION TITLE
Flux not picking up changes

### DISCUSSION THREAD

**Discussion by dev-samples** [fluxcd/flux2#1860] [Q&A]
Using this as an example:

https://github.com/fluxcd/flux2-kustomize-helm-example

I have a running flux installation in k8s 1.21. But its seems flux operator(s) are not picking up changes that I am pushing to the remote git/flux repo. As an example I have this jenkins release/yaml file:

**my-flux-repo/infrastructure/base/jenkins/release.yaml**

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: jenkins
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: 3.5.19
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system

  values:
    controller:
      JCasC:
        securityRealm: |-
          local:
            allowsSignup: false
            enableCaptcha: false
            users:
            - id: "admin"
              name: "Jenkins Admin"
              password: "secret12345"
        authorizationStrategy: |-
          loggedInUsersCanDoAnything:
            allowAnonymousRead: false    

```
I just added, comitted and pushed the JCasC configuration but my running jenkins pod is not being restarted or the existing configmap being updated even though I have verified that my commit has been picked up by flux:

```
[flux-system@kind-dev] $ flux get kustomizations --watch
NAME       	READY	MESSAGE                                                          	REVISION                                       	SUSPENDED 
flux-system	True 	Applied revision: master/22c047857665011ae46ff1c5b338b2fdcea7fa04	master/22c047857665011ae46ff1c5b338b2fdcea7fa04	False    	
apps	True	Applied revision: master/22c047857665011ae46ff1c5b338b2fdcea7fa04	master/22c047857665011ae46ff1c5b338b2fdcea7fa04	False	
infrastructure	True	Applied revision: master/22c047857665011ae46ff1c5b338b2fdcea7fa04	master/22c047857665011ae46ff1c5b338b2fdcea7fa04	False
```

Which is the expected git SHA.

Are there some files in the flux file tree/git repo that will not sync corresponding changes in the cluster when being updated/pushed?

I would expect that any changes being pushed for e.g. values files would update configmaps and trigger a restart of the pod - not event the configmap is updated when I pushed the above change.
