### DISCUSSION TITLE
Template support for Kustomization patches

### DISCUSSION THREAD

**Discussion by rhart** [fluxcd/flux2#1862] [Proposals]
Are there any plans to support files for the patches in the Kustomize API?  At the moment only inline YAML objects are supported and when there are lots of patches it becomes hard to read.

Maybe something like:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  # ...omitted for brevity
  patches: ["patch1.yaml", "patch2.yaml"]
```

**Comment by deB4SH** [comment]
Is there any news on this proposal? 
We are currently providing a rather modular service-catalog for internal customers to pull manifest of. Sadly the patches need to be inline, which is rather complicated on larger deployments. 

Is there any plan to implement a similar behavior like the kustomize one https://github.com/kubernetes-sigs/kustomize/blob/master/examples/patchMultipleObjects.md with allowing path: /path/to/file instead of inline patching?

**Reply by stefanprodan** [reply]
Use a `kustomization.yaml` to reference files, Flux Kustomizations are Kubernetes objects stored in etcd, there is no path to refer to, there is no file system. A Flux Kustomization can only refer to others Kubernetes objects, such as secrets and configmaps.

**Reply by jeevankuduvaravindran** [reply]
Hi Stefan, What if we need to run the patch only after running a pre job by depending on another kustomization and apply the patch only after the pre job is completed? It will be very useful to have a yaml reference instead of inline patch. This is because since the patch.yaml is looking for a helmrelease that doesnt exist until predeploy is completed and is available only when deploy is started.  something like below will be very helpful.

```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-deploy
  namespace: config-cluster-flux
spec:
  dependsOn:
    - name: demo-pre-deploy
      namespace: config-cluster-flux
  sourceRef:
    kind: GitRepository
    name: services-repository
    namespace: config-cluster-flux
  path: ./services/demo/deploy
  interval: 5m
  timeout: 5m
  prune: true
  wait: true
  patches:
    - path: patch.yaml
```

Patch.yaml has the patch for a helmrelease that is available as part of deploy kustomization.
