### DISCUSSION TITLE
What to expect when using multiple Secrets in substituteFrom?

### DISCUSSION THREAD

**Discussion by ruzickap** [fluxcd/flux2#1875] [Q&A] [answered]
Can anybody tell me what to expect when using multiple Secrets in substituteFrom?
Example:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: group-apps-substitutefrom-secret
  namespace: flux-system
data:
  MY_EMAIL: my_group_base64_encoded_email
  GROUP_VARIABLE: base64_encoded_text
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: cluster-apps-substitutefrom-secret
  namespace: flux-system
data:
  MY_EMAIL: my_cluster_base64_encoded_email
  CLUSTER_VARIABLE: base64_encoded_text
```

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
...
path: ./groups/dev/group-apps/apps
...
spec:
  postBuild:
    substituteFrom:
    - kind: Secret
      name: group-apps-substitutefrom-secret
    - kind: Secret
      name: cluster-apps-substitutefrom-secret
...
```

```yaml
# "groups/dev/group-apps/apps/test.yaml"
...
spec:
  email: ${MY_EMAIL}
  variable_cluster: ${CLUSTER_VARIABLE}
  variable_group: ${GROUP_VARIABLE}
...
```

Questions - In case of using 2 Secrets in substituteFrom:

* Should the variables from both secrets (`group-apps-substitutefrom-secret` and `cluster-apps-substitutefrom-secret`) be merged based on position in the array and then applied by Kustomize? Like:
  ```yaml
  MY_EMAIL: my_cluster_base64_encoded_email    ## should this variable be taken from the last specified "Secret" ?
  CLUSTER_VARIABLE: base64_encoded_text
  GROUP_VARIABLE: base64_encoded_text
  ``` 

Thank you...
