### DISCUSSION TITLE
SOPS support for secretGenerator and envs

### DISCUSSION THREAD

**Discussion by jrauschenbusch** [fluxcd/flux2#1891] [Proposals]
Currently there is no support for SOPS cluster decryption w/ respect to `envs` used within a secretGenerator. Is this planned to be implemented?

Example:
```
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ...
secretGenerator:
  - name: secret-name
    envs:
      - secret.encoded.env
```

Currently it's only possible to use a secretGenerator together w/ SOPS encrypted secrets by using the files notation, right?
