### DISCUSSION TITLE
Add a flag to prevent kustomization from being deleted

### DISCUSSION THREAD

**Discussion by andrey-dubnik** [fluxcd/flux2#1905] [Proposals] [answered]
Hi, deleting kustomization object can have a large blast radius. If Kustomization is somehow gets removed from the git repo it would also remove everything with it. The suggestion is to add a meta object which would prevent kustomization from being deleted by flux if flag is set and only be able to delete it when flag is not set.

e.g.

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: something-important
  namespace: production 
spec:
  protect: true
```

This may contradict the idea of GitOps but same time we can introduce additional measure to protect us from some unexpected events... for instance if teams are managing flux repo with the automation tooling which have a chance to make some damage on the scale

**Comment by stefanprodan** [comment, marked as answer]
Deletion is not enabled by default, `.spec.prune` must be set to `true` for Flux to remove objects from clusters. Please see the docs for more details on garbage collection: https://fluxcd.io/docs/components/kustomize/kustomization/#garbage-collection

**Reply by andrey-dubnik** [reply]
Garbage collecting the resources is a feature which may work in parallel with protection. prune will garbage collect individual objects where protection would prevent the entire kustomization object deletion. 

E.g. the scenario would be a multi-tenant setup where tenants are enrolled via Kustomization. OPS repo is auto-generated with on-boarding scripts and tenant Kuztomization objects are created. In the event which "will never happen" and auto-gen breaks repo could end up being empty which would remove the Kustomization and delete all the tenant infrastructure. If we set prune=true then GC won't be working and tenants would have to GC manually where it would be great if we could keep both GC turned on and overall Kustomization object protected.

**Reply by andrey-dubnik** [reply]
it seem labeling the Kustomization object does the trick and I'm able to keep GC and same time keep Kustomization from being accidentally deleted. Thanks for the help!

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: prune-test
  namespace: prune
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
```
