### DISCUSSION TITLE
Upgrade Flux to the Kustomize v1beta2 API

### DISCUSSION THREAD

**Discussion by stefanprodan** [fluxcd/flux2#1916] [Show and tell]
Starting with v0.18, Flux comes with a [new reconciler](https://github.com/fluxcd/kustomize-controller/pull/426) based on Kubernetes server-side apply and graduates the Flux Kustomize API to `v1beta2`.

## Breaking changes

- Namespaced objects must contain `metadata.namespace`, defaulting to the `default` namespace is no longer supported. Setting a namespace for all objects reconciled by a Kustomization can be done with `spec.targetNamespace`.
- The logs, events and alerts that report Kubernetes namespaced object changes are now using the `Kind/Namespace/Name` format instead of `Kind/Name`.
- The minimum required version of Kubernetes has changed to:

    | Kubernetes version | Minimum required |
    | --- | --- |
    | `v1.16` | `>= 1.16.11` |
    | `v1.17` | `>= 1.17.7` |
    | `v1.18` | `>= 1.18.4` |
    | `v1.19` and later | `>= 1.19.0` |

## Features and improvements

- Being able to validate and reconcile sources that contain both CRDs and CRs.
- Being able to wait for all the applied resources to become ready without requiring users to fill-in the health check list.
- Improve performance (CPU, memory, network, FD usage) and reduce the number of calls to Kubernetes API by replacing `kubectl ` execs with a specialised applier written in Go.
- Detect and report drift between the desired state (git, s3, etc) and cluster state reliably.
- Improve the overall observably of the reconciliation process by reporting in real-time the garbage collection and health assessment actions.
- Reconcile empty sources including pruning of all the resources previously applied.
- Mask secrets data in logs, events and alerts.

## API changes

The `kustomize.toolkit.fluxcd.io/v1beta2` API is **backwards compatible** with `v1beta1`.

Additions, deprecations and removals:
- `.spec.patchesStrategicMerge` deprecated in favour of `.spec.patches`
- `.spec.patchesJson6902` deprecated in favour of `.spec.patches`
- `.spec.validation` deprecated and no longer used (server-side validation is implicit)
- `.spec.wait` added (when enabled, will wait for all the reconciled resources to become ready)
- `.status.snapshot` replaced by `.status.inventory`

## Upgrade procedure

To upgrade your cluster, download the Flux CLI binary from the release page and rerun the `flux bootstrap` command. This will upgrade the Flux components on your cluster to the latest version. Other upgrade options can be found on the [docs website](https://fluxcd.io/docs/installation/#upgrade).

To update the Flux `Kustomization` manifests in Git see the following table:

| Change in the new version  | What you should do |
| -------------------------- | ------------------ |
| Version is now `v1beta2`   | Change the version: `apiVersion: kustomize.toolkit.fluxcd.io/v1beta2`  |
| `.spec.validation` removed | Server-side validation is now assumed. Remove this field from `.spec.` |
| `.spec.patchesStrategicMerge` deprecated in favour of `.spec.patches` | Convert each entry from `.spec.patchesStrategicMerge` into an inline strategic merge patch, like [this example given in the Kustomize documentation](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/#patch-using-inline-strategic-merge), and append to `.spec.patches.`. Note that the value in the patch field is quoted; that is, it is the YAML or JSON of the patch, stringified. |
| `.spec.patchesJson6902` deprecated in favour of `.spec.patches` | Convert each entry from `.spec.patchesJson6902` into [an inline JSON6902 patch](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/#patch-using-inline-json6902), and append to `.spec.patches`. Note that the value in the patch field is quoted; that is, it is the YAML or JSON of the patch, stringified. |
| `.status.snapshot` replaced by `.status.inventory` | `.status` is not kept in files, so you will not need to account for this. |

ℹ️  Note that updating the manifests in Git to `v1beta2` can be done at any time after the Flux components upgrade. All users are encouraged to update the manifests as the deprecated fields will be removed when the next API version will be released.

### Terrafrom upgrade

When using the [Terraform provider for Flux](https://github.com/fluxcd/terraform-provider-flux), you have to manually remove the `v1beta1` Kustomization from the TF state:

```
terraform state rm 'kubectl_manifest.sync["kustomize.toolkit.fluxcd.io/v1beta1/kustomization/flux-system/flux-system"]'
```

**Comment by stefanprodan** [comment]
⚠️ For those of you using [metrics-server](https://github.com/kubernetes-sigs/metrics-server), there was a [bug](https://github.com/kubernetes/kubernetes/pull/98576) in Kubernetes that got fixed [here](https://github.com/kubernetes/kubernetes/pull/98576). The fix was back ported in https://github.com/kubernetes/kubernetes/issues/99046 so if you deploy metrics-server (or any other `APIService`) with a Flux Kustomization, the minimum required version of Kubernetes is:

| Kubernetes version | Minimum required |
| --- | --- |
| `v1.18` | `>= 1.18.18` |
| `v1.19` | `>= 1.19.10` |
| `v1.20` | `>= 1.20.6` |
| `v1.21` and later | `>= 1.21.0` |

## Workaround 

If you can't upgrade your clusters, then use a Flux `HelmRelease` to install metrics-server as Helm doesn't uses server-side apply.

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 60m
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 60m
  targetNamespace: kube-system
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  values:
    args:
     - --metric-resolution=15s
     - --kubelet-insecure-tls
```
