### DISCUSSION TITLE
error: the server could not find the requested resource (patch clusterissuers.cert-manager.io letsencrypt-staging)

### DISCUSSION THREAD

**Discussion by dev-samples** [fluxcd/flux2#1944] [General] [answered]
I am trying to deploy cert-manager and ClusterIssuers using flux. I have organized files like below:

**infrastructure/base/cert-manager/release.yaml**

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: cert-manager
  interval: 5m
  chart:
    #name: cert-manager
    spec:
      chart: cert-manager
      version: 1.5.4
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
    replicaCount: 2
```
**infrastructure/base/cert-manager/namespace.yaml**

```
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
```

**infrastructure/base/cert-manager/cluster-issuer-staging.yaml**
```
#apiVersion: cert-manager.io/v1alpha3
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager  
spec:
  acme:
    email: admin@mail..com
    privateKeySecretRef:
      name: staging-issuer-account-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
```

**infrastructure/base/cert-manager/kustomization.yaml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - release.yaml
  - cluster-issuer-staging.yaml
```

**infrastructure/dev/temp-01/cert-manager/kustomization.yaml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ../../../base/cert-manager

```

But I get this error:

`
infrastructure	False	ClusterIssuer/cert-manager/letsencrypt-staging namespace not specified, error: the server could not find the requested resource (patch clusterissuers.cert-manager.io letsencrypt-staging)...`

Any suggestions? E.g. do I need to separate out the ClusterIssues and make a dependency on the cert-manager (CRDSs etc)?

This seems related:  https://github.com/fluxcd/flux2/discussions/730 but I have not found examples on how to successfully deploy cert-manager with ClusterIssuers using flux yet.

**Comment by stefanprodan** [comment, marked as answer]
If you want to install cert-manager with a `HelmRelease` then you need to use 2 Flux Kustomizations and `dependsOn`, docs here: https://fluxcd.io/docs/components/kustomize/kustomization/#kustomization-dependencies

Instead of Helm you ca use the official release YAML from cert-manager repo like so:

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.yaml
- my-certs.yaml
```

I do recommend the first option.

PS: ClusterIssuer is a global object, you need to remove the `namespace: cert-manager`, see the cert-manager docs for more info.

**Reply by dev-samples** [reply]
Thanks have it working now.

**Reply by stevejr** [reply]
@stefanprodan - I am still seeing the above issue running Flux v0.20.1. Cert-Manager deploys fine but ClusterIssuer will not.

Here is what I have - Flux is boostrapped to look at the folder **clusters/staging/staging1** for all the Flux Kustomizations:

**clusters/staging/staging1/infrastructure.yaml**
```apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/staging/staging1
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
  postBuild:
    substitute:
      <some variable substitutions here>
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-certs
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/certs
  prune: true
  postBuild:
    substitute:
      <some variable substitutions here>
```

**infrastructure/staging/staging1/kustomization.yaml**

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patchesStrategicMerge:
  - helmrelease-patch.yaml
```

**infrastructure/staging/staging1/helmrelease-patch.yaml**

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    serviceAccount:
      create: false
      name: cert-manager
    resources:
      requests:
        cpu: 10m
        memory: 200Mi
      limits:
        cpu: 20m
        memory: 1024Mi
    cainjector:
      resources:
        requests:
          cpu: 10m
          memory: 200Mi
        limits:
          cpu: 20m
          memory: 1024Mi
```

**infrastructure/base/apps/cert-manager/kustomization.yaml**

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - release.yaml
```

**infrastructure/base/apps/cert-manager/release.yaml**

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  storageNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: 1.6.1
  interval: 5m
  install:
    remediation:
      retries: 10
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  test:
    enable: false
  timeout: 5m
  values:
    installCRDs: true
    # Added SecurityContext due to https://github.com/jetstack/cert-manager/issues/1422
    securityContext:
      fsGroup: 65534
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 20m
        memory: 100Mi
    webhook:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 20m
          memory: 64Mi
    cainjector:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 20m
          memory: 100Mi
```

**infrastructure/base/certs/kustomization.yaml**

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterissuer.yaml
```

**infrastructure/base/certs/clusterissuer.yaml**

```
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: letsencrypt-prod
    email: ${CLUSTER_CONTACT_EMAIL}
    solvers:
      - dns01:
          route53:
            region: ${AWS_REGION}
            hostedZoneID: ${ROUTE53_HOSTED_ZONE_ID}
```
