### DISCUSSION TITLE
HelmRelease + CRDs dry-run no matches for kind error (traefik)

### DISCUSSION THREAD

**Discussion by vonera** [fluxcd/flux2#1952] [Q&A] [answered]
Hi I have a problem with flux + helm + crds. 
I want to deploy traefik using helm chart. 
It works as long I do not add any crds. 

here a short example: 

My repository  
```bash
tree .
.
└── clusters
    └── test
        ├── flux-system
        │   ├── gotk-components.yaml
        │   ├── gotk-sync.yaml
        │   └── kustomization.yaml
        └── traefik
            ├── namespace.yaml
            ├── tlsstore.yaml
            ├── traefik-helmrelease.yaml
            └── traefik-source.yaml
```

Contents of traefik folder
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik

spec:
  defaultCertificate:
    secretName: build-tls-secret

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 10.5.0
  interval: 1m0s

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1m0s
  url: https://helm.traefik.io/traefik
```

```bash
flux bootstrap gitlab \
        --hostname=$GITHOST \
        --owner=$OWNER \
        --repository=$REPO \
        --branch=$BRANCH \
        --path=$IN_REPO_PATH \
        --token-auth \
        --personal
...
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
✗ TLSStore/traefik/default dry-run failed, error: no matches for kind "TLSStore" in version "traefik.containo.us/v1alpha1"
CustomResourceDefinition/alerts.notification.toolkit.fluxcd.io configured
CustomResourceDefinition/buckets.source.toolkit.fluxcd.io configured
CustomResourceDefinition/gitrepositories.source.toolkit.fluxcd.io configured
CustomResourceDefinition/helmcharts.source.toolkit.fluxcd.io configured
CustomResourceDefinition/helmreleases.helm.toolkit.fluxcd.io configured
CustomResourceDefinition/helmrepositories.source.toolkit.fluxcd.io configured
CustomResourceDefinition/kustomizations.kustomize.toolkit.fluxcd.io configured
CustomResourceDefinition/providers.notification.toolkit.fluxcd.io configured
CustomResourceDefinition/receivers.notification.toolkit.fluxcd.io configured
Namespace/flux-system configured
Namespace/traefik created

► confirming components are healthy
✔ helm-controller: deployment ready
✔ kustomize-controller: deployment ready
✔ notification-controller: deployment ready
✔ source-controller: deployment ready
✔ all components are healthy
✗ bootstrap failed with 1 health check failure(s)
```
What am I doing wrong?  

Versions: 
```
flux: v0.18.3
helm-controller: v0.12.0
kustomize-controller: v0.15.5
notification-controller: v0.17.1
source-controller: v0.16.0
--
k3s-version:  v1.21.5+k3s2
```
