### DISCUSSION TITLE
ImagePolicy hang at waiting to be reconciled

### DISCUSSION THREAD

**Discussion by phootip** [fluxcd/flux2#1958] [Q&A]
At first, I deployed `ImageRepository` and `ImagePolicy` together in `flux-system` namespace and it was working fine.
example
```
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: app
  namespace: flux-system
spec:
  image: foo-bar/image-url
  interval: 5m0s
  secretRef:
    name: credentials
  accessFrom:
    namespaceSelectors:
      - matchLabels: {}
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: app
    namespace: flux-system
  filterTags:
     ...
```
Now, I'm trying to follow this guide 
https://fluxcd.io/docs/components/image/imagerepositories/#allow-cross-namespace-references
So that I can track them in separate namespaces.
But when I do that the new imagePolicy hang at `waiting to be reconciled`
example
```
NAME                    READY   MESSAGE                         LATEST IMAGE
app     False   waiting to be reconciled
```
```
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: app
  namespace: flux-system
spec:
  image: foo-bar/image-url
  interval: 5m0s
  secretRef:
    name: credentials
  accessFrom:
    namespaceSelectors:
      - matchLabels: {}
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: app
  namespace: app
spec:
  imageRepositoryRef:
    name: app
    namespace: flux-system
  filterTags:
     ...
```
I tried using `kubectl describe`, `flux logs` and `flux trace` but can't figure out what is wrong. Does kustomizations need to be in the same namespace as `ImagePolicy`? That is the only thing I can guess

Thank you for your helps
