### DISCUSSION TITLE
Missing CLI option?

### DISCUSSION THREAD

**Discussion by davosian** [fluxcd/flux2#1991] [Q&A] [answered]
I would like to run `flux create source helm` and include a flag to set the timeout for the `HelmRepository`. I can add it manually following the structure from https://fluxcd.io/docs/components/source/helmrepositories/, but ideally, I can use the CLI to do so. Does this option for the flux cli exist (but is missing from the documentation)?

**Comment by stefanprodan** [comment]
There are many timeout fields in a HelmRelease, not sure if we should map all the fields to flux CLI.

**Reply by davosian** [reply]
This is what I was trying to produce:

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: dandydev-charts
  namespace: flux-system
spec:
  interval: 15m0s
  url: https://dandydeveloper.github.io/charts
  timeout: 3m
```
