### DISCUSSION TITLE
Secret/project-a/ssh-credentials , error: data values must be of type string

### DISCUSSION THREAD

**Discussion by dev-samples** [fluxcd/flux2#1999] [Q&A] [answered]
Based on this guide:

https://github.com/fluxcd/flux2-multi-tenancy#onboard-tenants-with-private-repositories

I have created a SOPS encrypted ssh keypair. But I get this error from flux:

`flux-system 	tenants       	False  	Secret/project-a/ssh-credentials , error: data values must be of type string	master/89fdfb5190***	False    	
`

and:

`kustomize-controller-5b7b8b44f6-8fl6j manager {"level":"error","ts":"2021-10-24T08:44:23.081Z","logger":"controller.kustomization","msg":"Reconciliation failed after 663.051979ms, next try in 5m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"tenants","namespace":"flux-system","revision":"master/89fdfb5190b****","error":"Secret/project-a/ssh-credentials , error: data values must be of type string\n"}`

The encrypted secret in git looks like this:

```
apiVersion: v1
kind: Secret
metadata:
    name: ssh-credentials
    namespace: project-a
stringData:
    identity: ENC[AES256_G.....g==,type:str]
    identity.pub: ENC[AES256...GsGF/cw4w==,type:str]
    known_hosts: ENC[AES25....,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    mac: ENC[AES256_...5lBfjQ==,type:str]
    pgp:
        - created_at: "2021-10-24T08:51:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAwRcK7FPRDGeAQwAgHavWpPINpGQXVFkOjjELOHx3OOFVasmNRSKF8k/hbX0
            ...
            =KHIy
            -----END PGP MESSAGE-----
          fp: 42...E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
```

sops has `--output-type value`:

```
$ sops help | grep output
   --decrypt, -d                            decrypt a file and output the result to stdout
   --encrypt, -e                            encrypt a file and output the result to stdout
   --in-place, -i                           write output back to the same file instead of stdout
   --output-type value                      currently json, yaml, dotenv and binary are supported. If not set, sops will use the input file's extension to determine the output format
```
https://github.com/mozilla/sops/issues/367#issuecomment-557616584

so that does not have **String** but probably this is not the issue.

Any suggestions?

**Comment by stefanprodan** [comment, marked as answer]
Have you enabled decryption in the Flux Kustomization that applies this secret?

**Reply by dev-samples** [reply]
Ah of course was missing:

```
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
```

in

./clusters/kind-dev/tenants.yaml

Thanks!

**Comment by jbpratt** [comment]
Hi @stefanprodan , sorry to bring up an older discussion. I just ran into this though I do have decryption configured and two secrets were already properly decrypted prior to this revision. Decrypting the file manually appears to be correct and the kustomization shows it is configured for sops-age, so I'm not really sure what the issue. Any pointers for further debugging?

```
❯ k describe kustomization/applications -n flux-system
Name:         applications
Namespace:    flux-system
Labels:       kustomize.toolkit.fluxcd.io/name=flux-system
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  <none>
API Version:  kustomize.toolkit.fluxcd.io/v1beta2
Kind:         Kustomization
...
Spec:
  Decryption:
    Provider:  sops
    Secret Ref:
      Name:  sops-age
  Depends On:
    Name:    infrastructure
  Force:     false
  Interval:  10m0s
  Path:      ./applications
  Prune:     true
  Source Ref:
    Kind:  GitRepository
    Name:  flux-system
Status:
  Conditions:
    Last Transition Time:  2022-01-06T11:22:12Z
    Message:               Secret/supertuxkart/credentials , error: data values must be of type string

    Reason:  ReconciliationFailed
    Status:  False
    Type:    Ready
  Inventory:
    Entries:
...
      Id:                   triviabot_chat-token__Secret
      V:                    v1
      Id:                   triviabot_tunnel-credentials__Secret
      V:                    v1
  Last Applied Revision:    main/f7798fda704dd1a59eefefae35a6334e79bd0e34
  Last Attempted Revision:  main/adad5944fa1646c2fe18179762f294f506c55a6d
  Observed Generation:      1
Events:
  Type     Reason  Age   From                  Message
  ----     ------  ----  ----                  -------
...
  Normal   info    17m   kustomize-controller  Reconciliation finished in 177.133382ms, next run in 10m0s
  Warning  error   16m   kustomize-controller  Secret/supertuxkart/credentials , error: data values must be of type string
Namespace/supertuxkart created
  Warning  error  7m42s  kustomize-controller  Secret/supertuxkart/credentials , error: data values must be of type string
```
```
❯ k get secret -n flux-system | grep sops-age
sops-age                                                              Opaque                                1      2d
```

**Comment by jimmidyson** [comment]
I wonder if this is similar to https://github.com/kubernetes/kubernetes/issues/107417?

**Reply by stefanprodan** [reply]
Yes that could be the case, working on a fix here: https://github.com/fluxcd/kustomize-controller/pull/527

**Reply by jimmidyson** [reply]
Nice! Thanks for (nearly) fixing this @stefanprodan :tada:

**Comment by maxkokocom** [comment]
Not exactly reopening this ticket, but I am not sure is it worth to create a new issue. 

I found that the same error message comes not when the issue is with the data field type, but when someone is trying to deploy the secret in a default namespace missing the sops-gpg secret to decrypt it. I find it a bit weird, as I have seen error `no secret/sops-gpg` in other cases, but I got an edge case where deploying to a `default` namespace was returning this error code. Maybe it's default namespace unique edge case only. 

My whole setup which was resulting in this error message:

```yaml
apiVersion: v1
data:
    password: ENC...
    user: ENC...
kind: Secret
metadata:
    creationTimestamp: null
    name: secret-example
    namespace: default (changed to team-example, before the change it was giving the error: data values must be of type string)
sops:
...
```

The kustomization which was deploying this secret:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: team-example-secrets
  namespace: team-example
spec:
  serviceAccountName: team-example
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: team-example
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
```

I think weirdly enough it did deploy this secret to both namespaces `team-example` and `default` once specified to `team-example` in the end. 

PS I am using flux tenants ownership on a serviceAccountName: team-example, I just follow my company naming convention of teams rather then tenants, using the RBACs from multi-tenant repo example. Maybe that's why it's allowed to do it in default namespace, while in other it is raising expected error code?
