### DISCUSSION TITLE
ValuesFrom in HelmRelease with list objects

### DISCUSSION THREAD

**Discussion by carpenike** [fluxcd/flux2#2003] [Q&A]
Hey Everyone,

Hoping this is simple. Per docs, I _should_ be able to override the settings in my HelmRelease like the below (note the list):

```
spec:
  valuesFrom:
    - kind: ConfigMap
      name: matrix-media-ceph-bucket
      valuesKey: BUCKET_NAME
      targetPath: config.datastores[0].opts.bucketName
    - kind: ConfigMap
      name: matrix-media-ceph-bucket
      valuesKey: BUCKET_HOST
      targetPath: config.datastores[0].opts.endpoint
    - kind: Secret
      name: matrix-media-ceph-bucket
      valuesKey: AWS_ACCESS_KEY_ID
      targetPath: config.datastores[0].opts.accessKeyId
    - kind: Secret
      name: matrix-media-ceph-bucket
      valuesKey: AWS_SECRET_ACCESS_KEY
      targetPath: config.datastores[0].opts.accessSecret
```

However, when I deploy / check the helm values, it seems to have been ignored:

```
 ryan in ﴱ ryan-k8s in ~ ❯ helm get values matrix-media-repo -n comms
USER-SUPPLIED VALUES:
config:
  datastores:
  - enabled: true
    forKinds:
    - thumbnails
    - remote_media
    - local_media
    - archives
    opts:
      ssl: false
      tempPath: ""
    type: s3
```

Am I missing something?
