### DISCUSSION TITLE
flux create kustomization command with substituteFrom and substitute parameters

### DISCUSSION THREAD

**Discussion by ruzickap** [fluxcd/flux2#2027] [Proposals] [answered]
Flux supports [Variable substitution](https://fluxcd.io/docs/components/kustomize/kustomization/#variable-substitution), but it is not supported by `flux create kustomization` command.

For example:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
spec:
  interval: 5m
  path: "./apps/"
  postBuild:
    substitute:
      cluster_env: "prod"
      cluster_region: "eu-central-1"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: Secret
        name: cluster-secret-vars
```

May look like:

```
flux create kustomization apps --interval=5m --path="./apps" \
--substitute="cluster_env=prod" \
--substitute="cluster_region=eu-central-1" \
--substituteFrom="ConfigMap/flux-system.cluster-vars" \
--substituteFrom="Secret/flux-system.cluster-secret-vars"
```

Or it may look differently :-)

But it would be nice if `substituteFrom` and `substitute` can be used from flux cli.

Any suggestions ?
