### DISCUSSION TITLE
Resources for monitoring with Datadog

### DISCUSSION THREAD

**Discussion by sa-spag** [fluxcd/flux2#2054] [Proposals]
👋 Hello,

Flux v2 already comes with resources to monitor its components with Prometheus ([see related documentation](https://fluxcd.io/docs/guides/monitoring/)), but not for [Datadog](https://www.datadoghq.com/). It would be great for the community to share curated Datadog dashboards, monitors, and metrics metadata.

We could create a datadog-integration repository in https://github.com/fluxcd-community for sharing documentation on how to monitor Flux v2 with Datadog, Kubernetes manifests patches to integrate with Datadog agents, Terraform configuration or raw JSON to provision Datadog resources.

**Comment by sa-spag** [comment]
Here is a Kustomization that patches Flux's components so they can be discovered by Datadog agents. The goal is to [label Deployments and associated pods with Datadog unified service tags](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes#configuration-1) and [annotate pods to configure the OpenMetrics integration](https://docs.datadoghq.com/agent/kubernetes/prometheus/):

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
patches:
# Annotate Flux components for Datadog
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: flux-component
    spec:
      template:
        metadata:
          annotations:
            ad.datadoghq.com/manager.check_names: |
              ["openmetrics"]
            ad.datadoghq.com/manager.init_configs: |
              [{}]
            ad.datadoghq.com/manager.instances: |
              [
                {
                  "prometheus_url": "http://%%host%%:8080/metrics",
                  "namespace": "flux",
                  "send_distribution_buckets": true,
                  "metrics": [
                    "*"
                  ]
                }
              ]
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=flux
# Add Datadog unified service tags to all Flux components
patchesStrategicMerge:
- |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: helm-controller
      namespace: flux-system
      labels:
        tags.datadoghq.com/source: "helm-controller"
        tags.datadoghq.com/service: "helm-controller"
    spec:
      template:
        metadata:
          labels:
            tags.datadoghq.com/source: "helm-controller"
            tags.datadoghq.com/service: "helm-controller"
- |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: image-automation-controller
      namespace: flux-system
      labels:
        tags.datadoghq.com/source: "image-automation-controller"
        tags.datadoghq.com/service: "image-automation-controller"
    spec:
      template:
        metadata:
          labels:
            tags.datadoghq.com/source: "image-automation-controller"
            tags.datadoghq.com/service: "image-automation-controller"
- |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: image-reflector-controller
      namespace: flux-system
      labels:
        tags.datadoghq.com/source: "image-reflector-controller"
        tags.datadoghq.com/service: "image-reflector-controller"
    spec:
      template:
        metadata:
          labels:
            tags.datadoghq.com/source: "image-reflector-controller"
            tags.datadoghq.com/service: "image-reflector-controller"
- |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: image-reflector-controller
      namespace: flux-system
      labels:
        tags.datadoghq.com/source: "image-reflector-controller"
        tags.datadoghq.com/service: "image-reflector-controller"
    spec:
      template:
        metadata:
          labels:
            tags.datadoghq.com/source: "image-reflector-controller"
            tags.datadoghq.com/service: "image-reflector-controller"
- |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kustomize-controller
      namespace: flux-system
      labels:
        tags.datadoghq.com/source: "kustomize-controller"
        tags.datadoghq.com/service: "kustomize-controller"
    spec:
      template:
        metadata:
          labels:
            tags.datadoghq.com/source: "kustomize-controller"
            tags.datadoghq.com/service: "kustomize-controller"
- |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: notification-controller
      namespace: flux-system
      labels:
        tags.datadoghq.com/source: "notification-controller"
        tags.datadoghq.com/service: "notification-controller"
    spec:
      template:
        metadata:
          labels:
            tags.datadoghq.com/source: "notification-controller"
            tags.datadoghq.com/service: "notification-controller"
- |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: source-controller
      namespace: flux-system
      labels:
        tags.datadoghq.com/source: "source-controller"
        tags.datadoghq.com/service: "source-controller"
    spec:
      template:
        metadata:
          labels:
            tags.datadoghq.com/source: "source-controller"
            tags.datadoghq.com/service: "source-controller"
replacements:
# Add `tags.datadoghq.com/version` label to all Flux components
- source:
    kind: Namespace
    name: flux-system
    fieldPath: metadata.labels.[app.kubernetes.io/version]
  targets:
  - select:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
    fieldPaths:
    - metadata.labels.[tags.datadoghq.com/version]
    - spec.template.metadata.labels.[tags.datadoghq.com/version]
    options:
      create: true
```

I find the whole `patchesStrategicMerge` thingy inelegant but I am not aware of alternative Kustomize features.
