### DISCUSSION TITLE
ImageUpdateAutomation+Deployment+Kustomization with $imagepolicy problem

### DISCUSSION THREAD

**Discussion by scottasmith** [fluxcd/flux2#2084] [Q&A] [answered]
Hi, 

I am having trouble with getting an image to update and the git repo be updated.
I am using the exact methods from [here](https://fluxcd.io/docs/guides/image-update/) but created an ./app directory with its own kustomize.yaml with apiVersion `kustomize.config.k8s.io/v1beta1`.

./app/kustomzation.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- podinfo-deployment.yaml
```

./app/podinfo-deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: default
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:5.0.0 # {"$imagepolicy": "flux-system:podinfo"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
```

included by

./clusters/my-cluster/apps.yaml:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./app
  prune: true
```

The imagepolicy and imagerepository seems fine but its not getting any further
```
NAME                    READY   MESSAGE                         LAST SCAN               SUSPENDED
imagerepository/podinfo True    successful scan, found 22 tags  2021-11-13T23:55:53Z    False

NAME                    READY   MESSAGE                                                                 LATEST IMAGE
imagepolicy/podinfo     True    Latest image tag for 'ghcr.io/stefanprodan/podinfo' resolved to: 5.0.3  ghcr.io/stefanprodan/podinfo:5.0.3
```

No actual deployment update and no git commit to say its done:
```
kubectl get deployment/podinfo -o jsonpath="{$.spec.template.spec.containers[0].image}"
ghcr.io/stefanprodan/podinfo:5.0.0
```

If I move the `podinfo-deployment.yaml` file back into `./clusters/my-cluster` and remove the `apps.yaml` it works fine fine as it should.

I have a feeling that Kustomize is stripping out all comments?

I even followed the guide on having comments in the Kustomize type ie.
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: ghcr.io/stefanprodan/podinfo
  newName: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "flux-system:podinfo:name"}
  newTag: 5.0.0 # {"$imagepolicy": "flux-system:podinfo:tag"}
```

That didn't work either. Tried the `./app` directory in `./clusters./my-cluster`. That didn't work.

**Comment by stefanprodan** [comment, marked as answer]
```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  update:
    path: ./clusters/my-cluster
    strategy: Setters
```

You have to change `spec.update.path` to point to the dir where the image markers are, in your case that’s `./app`.
