### DISCUSSION TITLE
Adding a sidecar container to helm chart's deployment

### DISCUSSION THREAD

**Discussion by davosian** [fluxcd/flux2#2088] [Q&A] [answered]
I am trying to add a sidecar container to a deployment created through a helm chart. The chart definition does not offer such an option through its values file. I therefore would like to leverage kustomize to patch the deployment manifest. I tried the following patch, but for some reason the sidecar container does not get added while flux reports all reconciliations as succesful - probably because my target does not find a match?

```
# kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml

patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/-
        value:
          - image: zerotier/zerotier:1.6.5
            args: ["my_network_id"]
            imagePullPolicy: IfNotPresent
            name: kube-zt
            resources: {}
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
                  - SYS_ADMIN
              privileged: true
    target:
      kind: Deployment
      name: podinfo
      namespace: test
```

```
# helm-release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: test
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: 6.0.3
      sourceRef:
        kind: HelmRepository
        name: podinfo-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - host: "podinfo.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "podinfo.${SECRET_DOMAIN}"
          secretName: "podinfo-tls"
```

**Comment by yebyen** [comment, marked as answer]
The podinfo chart does not include namespace in its templates:

https://github.com/stefanprodan/podinfo/blob/132f4e719209eb10b9485302f8593fc0e680f4fc/charts/podinfo/templates/deployment.yaml#L1-L6

Try patching a target that does not include `namespace` in the target definition. (I think I hit this issue myself last week, on a different chart 👍 it was tricky to discover what went wrong.)

Oh, that was not it -- I missed something else off about your example config, this is one more step beyond the problem that I had:

The Kustomization is not generating the Helm template output, so it will still not match. You need to perform this kustomization patch as a HelmRelease `postRenderer` action, since the HelmRelease reconciles the chart to the cluster, (not the Flux Kustomization), then patching at the Flux Kustomization will not have been effective. So patch at the HelmRelease instead:

https://fluxcd.io/docs/components/helm/helmreleases/#post-renderers

(You can use the same advice from above... since Podinfo chart doesn't include a "namespace" in the template output, don't target that in your postRenderer kustomization. You can target only "name" by a patch, then it it will match, as long as you do it in the HelmRelease.)

**Reply by davosian** [reply]
Thanks a lot @yebyen. Applying both of your inputs (omitting the namespace, using a postrenderer) resulted in the following manifest which creates the sidecar container for podinfo:

```yaml
# helm-release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: test
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: 6.0.3
      sourceRef:
        kind: HelmRepository
        name: podinfo-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - host: "podinfo.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "podinfo.${SECRET_DOMAIN}"
          secretName: "podinfo-tls"
  postRenderers:
    # Instruct helm-controller to use built-in "kustomize" post renderer.
    - kustomize:
        patchesJson6902:
          - patch:
              - op: add
                path: /spec/template/spec/containers/-
                value:
                  image: zerotier/zerotier:1.6.5
                  args: ["${ZEROTIER_NETWORK}"]
                  imagePullPolicy: IfNotPresent
                  name: kube-zt
                  resources: {}
                  securityContext:
                    capabilities:
                      add:
                        - NET_ADMIN
                        - SYS_ADMIN
                    privileged: true
            target:
              kind: Deployment
              name: podinfo
```
