### DISCUSSION TITLE
Remote apply with HelmRelease and Kustomize

### DISCUSSION THREAD

**Discussion by iamwillbar** [fluxcd/flux2#2089] [Q&A]
I'm trying to set up a remote apply configuration where one cluster (manager) has FluxCD installed and the others don't have anything special installed. I want to be able to deploy different applications with different configurations but also to reuse as much between the different clusters as possible. I think I have this working and I wanted to verify whether this is the best approach:

1. On the manager cluster create a secret for each remote cluster with a self-contained kubeconfig.
2. On the manager cluster create a single `GitRepository` resource that fetches the configuration repository.
3. On the manager cluster create a `Kustomize` resource for each cluster that references a subdirectory of the configuration repository.

The configuration repository would be structured as:
```
apps
|- foo
   |- kustomization.yaml
   |- helmrelease.yaml
|- bar
   |- kustomization.yaml
   |- helmrelease.yaml
clusters
|- hello
   |- kustomization.yaml
|- world
   |- kustomization.yaml
```

The `kustomization.yaml` in the `clusters/*` directory looks like this:

```
resources:
- ../../foo
- ../../bar
namePrefix: clustername-
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: not-used
      spec:
        kubeConfig:
          secretRef:
            name: cluster_specific_kubeconfig_secret
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
```

This will clone each of the `HelmRelease` resources with a cluster name prefix and override the `kubeConfig` used by the HelmController to target the specified cluster. It also allows me to choose which apps to install on a cluster by choosing which `resources` to include in that cluster's `kustomization.yaml`.

One thing that I haven't worked out is I may want to also apply Kustomize generated objects directly to the cluster, without Helm, to do that I think I would need two KustomizeController instances per cluster, one to transform and execute the `HelmRelease` resources (which needs to happen on the manager cluster) and one to transform and execute the other kustomizations (which needs to happen against the remote cluster).

Is there an easier way to do this or am I heading in the right direction?
