### DISCUSSION TITLE
LimitRange spec for cpu expected string

### DISCUSSION THREAD

**Discussion by nuriel77** [fluxcd/flux2#2119] [Q&A] [answered]
Hi!

Consider the following yaml spec:
```yaml
# Memory default limit range
apiVersion: v1
kind: LimitRange
metadata:
 name: mem-cpu-limit-range
 namespace: argocd
spec:
 limits:
 - default:
     memory: 256Mi
     cpu: 1                     ### set as integer
   defaultRequest:
     memory: 256Mi
     cpu: 0.5                  ### set as float
   max:
     memory: 2Gi
     cpu: "18"
   min:
     memory: 128Mi
     cpu: "100m"
   type: Container
```

If I run either `kubeval` or even `kubectl apply` on this there is no problem whatsoever for K8S to accept this spec.
However, when I add it to Flux I get the error from the kustomization controller:

```
flux-system   infra         False   LimitRange/reloader/mem-cpu-limit-range dry-run failed, error: failed to create typed patch object: errors:
  .spec.limits[0].default.cpu: expected string, got &value.valueUnstructured{Value:1}
  .spec.limits[0].defaultRequest.cpu: expected string, got &value.valueUnstructured{Value:0.5}
              6d23h
```

I wonder why would it not accept what is deemed by `kubectl` as valid?
