### DISCUSSION TITLE
Semver not updating to the latest version

### DISCUSSION THREAD

**Discussion by Ritvik-rc** [fluxcd/flux2#2140] [Q&A] [answered]
I am using flux v2. I have an image policy as follows:

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: my-app
  namespace: flux2-system
spec:
  imageRepositoryRef:
    name: my-app
  policy:
    semver:
      range: '*'

The latest version in my image repo is 0.7.119 but flux is taking the latest version as 0.7.118. 

The image policy logs show: 
image-reflector-controller  Latest image tag for 'xxx.dkr.ecr.us-east-1.amazonaws.com/test-notification' resolved to: 0.7.118

I am not able to figure out what I am missing. Any pointers or help would be appreciated.
Thanks

**Comment by Ritvik-rc** [comment]
I found out that the repo had a pre release version (0.7.118-bugfix) in the semantic versioning. I am guessing all the versions after the pre release version (which had alphabets) are not taken into consideration. I tried pushing some more versions after the pre release version but the latest image tag was not resolved to any of the newer versions. 

If anyone has any idea on how to fix this, please help. 
Thanks

**Reply by hiddeco** [reply]
To take prereleases into account, you need to add `-0` to your SemVer selector: https://github.com/Masterminds/semver#working-with-prerelease-versions

**Reply by Ritvik-rc** [reply]
Thanks a lot @hiddeco. It worked like a charm🙂

**Comment by Ritvik-rc** [comment, marked as answer]
> To take prereleases into account, you need to add `-0` to your SemVer selector: https://github.com/Masterminds/semver#working-with-prerelease-versions

Thanks @hiddeco. I am closing it now

**Comment by SachithKasthuriarachchi** [comment]
Can you please let me know how would I ask flux helmrelease to listen for all release candidates between version 6.x.x and 7.x.x?

I use `">=6.0.0 <7.0.0"` to filter the main releases. Should I modify it as `">=6.0.0-0 <7.0.0-0"` to listen only for pre-releases?

(asking this since https://go.dev/play/p/dBwAUX7oz0X didn't work)

**Reply by stefanprodan** [reply]
Filtering is only support for Hem OCI:

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: app-chart
  namespace: default
spec:
  interval: 10m
  url: oci://ghcr.io/org/charts/app
  ref:
    semver: ">=6.0.0-0 <7.0.0-0"
    semverFilter: ".*-rc.*" # this only includes RCs
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app
  namespace: default
spec:
  interval: 10m
  releaseName: app
  chartRef:
    kind: OCIRepository
    name: app-chart
```

**Reply by SachithKasthuriarachchi** [reply]
I'm getting the following error from kustomization when I set the `.spec.chartRef`.

```
HelmRelease/default/my-hr dry-run failed (Invalid): HelmRelease.helm.toolkit.fluxcd.io "my-hr" is invalid: spec: Invalid value: "object": either chart or chartRef must be set...
```

Here is my helmRelease and OCIRepository

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-hr
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: my-helm-chart
    namespace: flux-system
  install:
    crds: CreateReplace
  interval: 5m0s
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - /webhooks/0/namespaceSelector/matchExpressions
        target:
          kind: ValidatingWebhookConfiguration
          name: cert-manager-webhook
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 1
  valuesFrom:
    - kind: ConfigMap
      name: values
      valuesKey: values.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: my-helm-chart
  namespace: flux-system
spec:
  interval: 5m
  url: oci://myprivateacr.azurecr.io/helm/my-helm-chart
  ref:
    semver: ">=7.0.0-0 <8.0.0-0"
    semverFilter: ".*-alpha.*"
  secretRef:
    name: my-image-pull-secret
```
