### DISCUSSION TITLE
Is applying SM patch via file reference possible?

### DISCUSSION THREAD

**Discussion by andrey-dubnik** [fluxcd/flux2#2163] [Q&A] [answered]
Hello,

I'm trying to apply a patch (SM) as a file like below 

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: elasticsearch-eck-operator-temporal
  namespace: temporal 
spec:
  interval: 3m
  sourceRef:
    kind: GitRepository
    name: temporal-visibility 
    namespace: temporal
  path: ./base/eck-operator
  prune: true
  validation: client
  patches:
    - patch: elasticsearch-local.yaml
```

[Documentation](https://fluxcd.io/docs/components/kustomize/kustomization/#patches) have only the inline examples where [Accordingly to the Go spec](https://pkg.go.dev/github.com/fluxcd/pkg/apis/kustomize#Patch) where I was hoping for the file based scenario to work per following:

> Patch contains either a StrategicMerge or a JSON6902 patch, either a file or inline, and the target the patch should be applied to.

I can't seem to make it work with the file yet... I have tried placing the file with the same path as Kustomization and ./base/eck-operator which makes no difference

```
 kustomize build failed: trouble configuring builtin PatchTransformer with config: `
           	                                   	     	patch: elasticsearch-local.yaml
           	                                   	     	target: {}
           	                                   	     	`: unable to parse SM or JSON patch from [elasticsearch-local.yaml]
```

Is a file specific patch supported?

If this is supported what would be the root for the patch so I could build a relative config?
