### DISCUSSION TITLE
Set ReconcileStrategy via git

### DISCUSSION THREAD

**Discussion by nickperkins** [fluxcd/flux2#2166] [Q&A] [answered]
How would I set the ReconcileStrategy for a `HelmChart` in a permanent way? Right now I can update the `HelmChart` object but these are generated by the controller, not stored in git.

**Comment by nickperkins** [comment, marked as answer]
Ok so to answer my own question, I stumbled across the reconcileStrategy in the HelmRelease object as well.

```
spec:
  releaseName: staging
  targetNamespace: app-staging
  storageNamespace: app-staging
  chart:
    spec:
      chart: ./charts/app
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: example
```
