### DISCUSSION TITLE
Allow scheduling updates at certain times of the day

### DISCUSSION THREAD

**Discussion by evanrich** [fluxcd/flux2#2200] [Proposals]
To the best of my knowledge, fluxcdv2 remediates changes when they're detected.  While in theory this is fine for most services, there are occasionally some you may want to restart/deploy when they are not in use.   I'm running gitlab and plex media server in a kubernetes environment in my home cluster, and while I have flux checking for update every 12 hours, I would not want it to restart the services in the middle of the day/evening when I or someone else are using them.  I'd prefer instead to have a configuration field that allow me to specify a time to remediate it, say at 3am.

Currently, a manifest is annotated like this:
```
 image: someorg/foopackage:version-va.b.c # {"$imagepolicy": "flux-system:foopackage"}
```

I'd propose one of the following two solutions for this:

proposal 1:

Add an annotation to the deployment/pod/statefulset/etc that has the time you want to remediate it, this could be cron format (0 3 * * *), a time range (0300-0900, etc), etc

proposal 2
edit the image policy to have a remediate time:

```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: foopackage
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: foopackage
  filterTags:
    pattern: '^version-v(?P<version>[0-9]\.[0-9\.]+\.[0-9\.]+)'
    extract: '$version'
  policy:
    semver:
      range: '^0'
  remediateTime: 03:00:00  (3am)  <-----
```

this could also be formatted like a cronjob, say "0 3 * * *", etc 

Proposal 3:

Have a new resource, like "Remediate Policy", something like:
```
apiVersion: remediate.toolkit.fluxcd.io/v1/alpha1
kind: RemediationPolicy
metadata: 
  name: foopackage
  namespace: flux-system
spec:
  imagePolicyRef:
    name: foopackage <----- the name of the image policy/resource you want to schedule updates for)
policy:
   time:
     - 03:00:00 ( HH:MM:SS format)
     - "0 3 * * *"  (cron format)
     - 2300-0400 (world time range, any time between 11PM-04AM)
```

example usage of this:
```
apiVersion: remediate.toolkit.fluxcd.io/v1/alpha1
kind: RemediationPolicy
metadata: 
  name: gitlab-update-policy
  namespace: flux-system
spec:
  imagePolicyRef:
    name: gitlab-image <----- the name of the image policy/resource you want to schedule updates for)
policy:
   time:
     - 03:00:00 (3AM)
```

I don't know if the image policy is where this would go exactly, but it would be nice to be able to have the option so that even if you detect a new image is available at say, 2PM, that you then apply that update at 3AM.

Thanks!
