### DISCUSSION TITLE
How to compose/template large String fields in kustomize controller ?

### DISCUSSION THREAD

**Discussion by gberche-orange** [fluxcd/flux2#2211] [Q&A]
Hello,

I need to provision a custom resource which requires a large string litteral (in my case containing gotemplate)

See https://github.com/cloudfoundry-incubator/service-fabrik-broker/blob/master/docs/Interoperator.md#sfplan

<details>
<summary>sample long string problem</summary>
<pre>
apiVersion: osb.servicefabrik.io/v1alpha1
kind: SFPlan
metadata:
  name: &id 39d7d4c8-6fe2-4c2a-a5ca-b826937d5a88
spec:
  templates:
  - action: status
    type: gotemplate
    content: |
      # Status template for provision call
      {{ $stateString := "in progress" }}
      {{- with .postgresql.status.PostgresClusterStatus }}
        {{- if or (eq . "CreateFailed") (eq . "UpdateFailed") }}
          {{- $stateString = "failed" }}
        {{- else }}
          {{- if eq . "Running"}}
            {{- $stateString = "succeeded" }}
          {{- else }}
            {{- $stateString = "in progress" }}
          {{- end }}
        {{- end }}
      {{- end }}
      provision:
        state: {{ $stateString }}
        description: {{ with .postgresql.status.reason }} {{ printf "%s" . }} {{ else }} "" {{ end }}
      #
      # Status template for bind call
      {{- $dbname := "main" }}
      {{- $host := "" }}
      {{- $enableLoadBalancers := false }}
      {{- with .plan.spec.context.enableLoadBalancers }} {{ $enableLoadBalancers = . }} {{ end }}
      {{- if $enableLoadBalancers }}
        {{- with .svc.status.loadBalancer.ingress }}
          {{- $host = default (index . 0).ip (index . 0).hostname }}
        {{- end }}
      {{- else }}
        {{- with .svc.spec.clusterIP }} {{ $host = . }} {{ end }}
      {{- end }}
      {{- $port := 0 }}
      {{- with .svc.spec.ports }}
        {{- $port = (index . 0).port }}
      {{- end }}
      {{- $pass := "" }}
      {{- with .secret.data.password }} {{ $pass = (b64dec .) }} {{ end }}
      {{- $user := "" }}
      {{- with .secret.data.username }} {{ $user = (b64dec .) }} {{ end }}
      {{- $stateString = "in progress" }}
      {{- if and (not (eq $host "")) (not (eq $pass "")) }}
        {{- $stateString = "succeeded" }}
      {{- end }}
      {{- $responseString := "" }}
      {{- if eq $stateString "succeeded"}}
        {{- $credsMap := dict "dbname" $dbname "hostname" $host  "port" (printf "%d" $port) "username" $user "password" $pass }}
        {{- $_ := set $credsMap "uri"  (printf "postgres://%s:%s@%s:%d/%s?sslmode=require" $user $pass $host $port $dbname) }}
        {{- $responseMap := dict "credentials" $credsMap }}
        {{- $responseString = mustToJson $responseMap | squote }}
      {{ end }}
      bind:
        state: {{ $stateString }}
        error: ""
        response: {{ $responseString }}
      #
      # Status template for unbind call
      {{- $stateString = "succeeded" }}
      unbind:
        state: {{ $stateString }}
        error: ""
      #
      # Status template for deprovision call
      {{- $stateString = "in progress" }}
      {{- with .postgresql }} {{ with .metadata.deletionTimestamp }} {{ $stateString = "in progress" }} {{ end }} {{ else }} {{ $stateString = "succeeded" }}  {{ end }}
      deprovision:
        state: {{ printf "%s" $stateString }}
        error: ""
</pre>
</details>

I'm looking for ways to make such large string manageable in a git ops approach such as splitting into distinct files and concat them with string concatenation

I did not yet find such support in kustomize with either json strategic patches, replacements which don't manipulate the content of a field.

One way might be variable substitution, using configmap generated from files using [kustomize Configmap generator](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/#configmap-from-file). This however pollutes the K8s namespace with a ConfigMap only used by postBuild, and requires a top-level Kustomization from kustomize.toolkit.fluxcd.io/v1beta2. 

Would there be a better way ? Is there otherwise already a proposal drafted somewhere that I missed  ?

<details>
<summary>sample long string approach with variable substitution and configmap generator</summary>

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
[...]
configMapGenerator:
  - name: pxc-default-plan-status-fragments
    files:
      - ./pxc-default-SF-plan-templates/status-bind.gotemplate
      - ./pxc-default-SF-plan-templates/status-unbind.gotemplate
      - ./pxc-default-SF-plan-templates/status-provision.gotemplate
      - ./pxc-default-SF-plan-templates/status-unprovision.gotemplate
```

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sfplan-formatter
spec:
   resources:
   - sfplan.yaml: 
[...]
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: pxc-default-plan-status-fragments
```

`sfplan.yaml`: 

```yaml
apiVersion: osb.servicefabrik.io/v1alpha1
kind: SFPlan
metadata:
  name: &id 39d7d4c8-6fe2-4c2a-a5ca-b826937d5a88
spec:
  templates:
  - action: status
    type: gotemplate
    content: |
      ${status-bind.gotemplate} 
      ${status-unbind.gotemplate} 
      ${status-provision.gotemplate} 
      ${status-unprovision.gotemplate} 
```
</details>

Edit: variable substitution restricts the variable name (see below), which prevents usage of typical file names with extensions such as `status-bind.gotemplate` (while a variable name `status_bind_gotemplate` would be accepted and looked from the generated configmap )

https://fluxcd.io/docs/components/kustomize/kustomization/#variable-substitution
> Note that the name of a variable can contain only alphanumeric and underscore characters. The controller validates the var names using this regular expression: ^[_[:alpha:]][_[:alpha:][:digit:]]*$.

Edit 2: the variable substitution seem to trim the linefeeds in the substituted variable, preventing use of this technique for gotemplate content
