### DISCUSSION TITLE
Replace additional data in addition to tag / image name / image on a kubernetes object

### DISCUSSION THREAD

**Discussion by GregoireW** [fluxcd/flux2#2215] [Proposals]
Sometime we like to set additional annotation / label on our kubernetes object to be able to track / filter changes on automated process / observability tools.

Example: 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-namespace
  labels:
    app: runner-manager
  annotations:
    my.org/application: xxx
    my.org/version: 1.2
    my.org/sha1: 12345678
...
```

Usually we face two types of annotations, 
- the "static" one (like "my.org/application") - fixed one for all at first deployment
- the "dynamic" one (version, sha1, ...) which are linked to the image we deploy, so are modified at each new deployment

To ease integration, image are tagged with value containing all this (following a pattern like  'version-sha1-date' for instance).

Without image automation, doing this may be error prone.

Is it possible, in a future release, to use flux to extract some part of the tag and replace some value in kubernetes yaml ?
Or should I write my own service to do that ?
