### DISCUSSION TITLE
SOPS-managed secret in postBuild/substituteFrom

### DISCUSSION THREAD

**Discussion by rombert** [fluxcd/flux2#2220] [Q&A]
Hi,

I have a `HelmRelease` where I want to substitute some variables based on a secret using `postBuild`, e.g.

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: infrastructure-secret
```

I would like to have the secret also managed by sops, so I can't commit it to git as it.

What would be the preferred solution here - adding an `infrastructure-pre` kustomization that generates the secret in the `flux-system` namespace and that the `infrastructure` kustomization depends on?
