### DISCUSSION TITLE
Update only relevant flux Kustomization resources based on source changes

### DISCUSSION THREAD

**Discussion by Crevil** [fluxcd/flux2#2221] [Q&A] [answered]
# Setup

We are running a setup with a single `GitRepository` that is referenced by >200 flux `Kustomization` resources.
Each of the kustomization resources reference different paths in the source.
We are using a single Git repository to host all of these files and the repository is rather huge at around 90k commits resulting in disk usage of 255 MB. The repo contains resources for multiple environments but so far we are only testing it in one cluster as per below.

```yaml
# ./dev/releases/kube-system/flux2
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cluster-config
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: cluster-config
  timeout: 20s
  url: ssh://git@github.com/lunarway/<repo>.git
---
# ./dev/releases/kube-system/flux2
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: bootstrap
  namespace: flux-system
spec:
  suspend: false
  interval: 10m
  retryInterval: 30s
  path: ./clusters/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-config
---
# there are >200 of these in different paths
# ./clusters/dev/ns/app1
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app1
  namespace: ns
spec:
  interval: 5m0s
  # this path contains raw YAML manifests
  path: ./dev/releases/ns/app1
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
```

## Reasoning

We would like to have separate flux `Kustomization` resources for each app to bulkhead faulty changes between teams, eg. invalid manifests.

# Observations

We see that reconciling all resources takes up to 10 minutes when ever there is a new commit on the `cluster-config` repository.
We have tried different combinations of Kubernetes API limits, concurrency and Pod resource limits with different results but overall we still see that we have to much work to do when the `GitRepository` changes.

What we hoped to see was that whenever the `GitRepository` changed only flux `Kustomization` resources that depended on the changed paths would update.
But instead we see that _all_ resources are reconciled creating waves of delays.

This image shows the workqueue depth and rate. When there is a change in Git the workqueue spikes as all resources needs to be updated. Further more it takes over 6 minutes to get through the queue. Between 10:24 - 10:26 we see the interval of flux `Kustomization` resources kick in doing a check agains the Kubernetes APIs.
These numbers were gathered when running a Pod with 2 cores and 2GB memory limits and the following flags.

```
--kube-api-burst=500
--kube-api-qps=250
--concurrent=4
```

![image](https://user-images.githubusercontent.com/6881694/146347723-23acea3c-32f8-4aed-893a-4a37430ca2bd.png)

![image](https://user-images.githubusercontent.com/6881694/146348465-0e581d5c-19cf-4494-b687-e69cbcf2895a.png)

It might not be related but we also see the memory flatline on it's limits after some time.

![image](https://user-images.githubusercontent.com/6881694/146357068-51ddb215-fc59-4c1a-a391-7fbfd15dbda1.png)

# Question

Are we doing something wrong in the structure of resources?
What can we expect performance wise and can we somehow reduce the work needed to be done, ie. only update kustomizations that are relevant based on the paths?
