### DISCUSSION TITLE
Flux on spot/preemptible instances

### DISCUSSION THREAD

**Discussion by PatrykGala** [fluxcd/flux2#2238] [Q&A] [answered]
Hi,
I'm using Flux v2 with GKE autopilot cluster, for test/dev environments I would like to use Flux with [spot instances](https://cloud.google.com/spot-vms), spot instances restarts when GCP need this resources. Is the setup reliable? Are flux images fault tolerant?

### My configuration

spot_instances.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: not_used
  namespace: flux-system
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
```

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - path: spot_instances.yaml
    target:
      kind: Deployment

resources:
  - gotk-components.yaml
  - gotk-sync.yaml
```

### Kubernetes version / Distro / Cloud provider

1.21.5-gke.1302

### Flux version

# Flux Version: v0.24.1
