### DISCUSSION TITLE
Multiple values file from different git repositories

### DISCUSSION THREAD

**Discussion by ayushkedia357** [fluxcd/flux2#2241] [Q&A] [answered]
I am using FluxCD to deploy helm charts on my K8s cluster and kustomization to combine flux resources.

**Problem:**
Currently I have helm charts and values files placed in the service repository. Number of values file depends on the regions of deployment for the service.

Issue with above implementation -
1. Environment values changing at global and service level
2. Environment values changing at region level but common to all services
3. Environment values changing at service level but common to all regions

I want to reference the above three types of values files which has to be placed at an external git source accessible by all the helm charts and the HelmRelease/HelmChart CRD could handle more than one values file from a single HelmChart that is sourced by a external GitRepository.

Chart Location :
- repository : `services`
- path: `./example/charts/`

Values file location:
- repository : `gitops`
- path: `./values/service/example`
- path: `./values/region`
- path: `./values/global`

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: example
  namespace: default
spec:
  releaseName: example
  chart:
    spec:
      chart: charts/example
      sourceRef:
        kind: GitRepository
        name: example-repo
        namespace: flux-system
      valuesFiles: 
        - values/services/example/values.yaml              # one
        - values/region/values-region.yaml       # two
        - values/global/values-glob.yaml           # three
  interval: 5m
  ```
  
With my current understanding on FluxCD I'm not able to find a way to implement the above problem.

Have gone through the docs, this is what I could find closest to my problem, which has a constraint that multiple values files within the relative path of the sourceRef can referred to the helm charts.
https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.HelmChartTemplateSpec

`flux: v0.24.0`
`kubernetes: v1.22.3`
`Chart Source: Gitrepository`
