### DISCUSSION TITLE
Deploy HelmRelease from a local helm chart path

### DISCUSSION THREAD

**Discussion by ashrafgt** [fluxcd/flux2#2254] [Q&A] [answered]
I'm using flux v2 to deploy my project, and I'd like to use a HelmRelease/HelmRepository to deploy a local helm chart. I'm wondering if this is possible.

Here's the structure of the repository:
```bash
.
├── deployment
│   ├── charts                         # local helm charts
│   │   └── prediction-server            # chart for seldon-core prediction server 
│   │       ├── templates
│   │       ├── Chart.yaml
│   │       └── values.yaml
│   └── manifests                      # flux manifests
│       ├── prediction-server            # prediction server namespace and helm release
│       │   ├── namespace.yaml
│       │   └── release.yaml
│       └── sources                    # helm repostories
│           └── prediction-server.yaml
└── README.md
```

With flux bootstrapped as follows:
```bash
flux bootstrap github \
    --owner=ashrafgt \
    --repository=test \
    --branch=develop \
    --path=deployment/manifests
```

Is it possible to have a HelmRepository that points to the local helm chart somehow? Maybe something like this:
```yaml
# deployment/manifests/sources/prediction-server.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: local
  namespace: flux-system
spec:
  interval: 5m
  url: ../deployment/charts
```

And then have a HelmRelease that deploys the chart like this:
```yaml
# deployment/manifests/prediction-server/release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prediction-server
  namespace: test
spec:
  releaseName: prediction-server
  chart:
    spec:
      chart: prediction-server
      sourceRef:
        kind: HelmRepository
        name: local
        namespace: flux-system
      version: 0.1.0
```

Thank you for any help and advice!

**Comment by stefanprodan** [comment, marked as answer]
Please see the Helm docs here: https://fluxcd.io/docs/guides/helmreleases/#git-repository

PS. A HelmRelease can use a GitRepository as source.

**Reply by ashrafgt** [reply]
Thank you @stefanprodan! That's the solution I ended up using. 

Though, there's a little detail in my approach that I'm not sure about. I noticed that after the bootstrap, flux creates a secret called `flux-system` in the `flux-system` namespace, and that secret has the Git SSH credentials that I would need to create the `GitRepository`, so I went ahead and used it. Is that a common practice, or is it a bad practice?

**Reply by stefanprodan** [reply]
You could reuse the flux-system GitRepository instead of creating a new one.

**Reply by ashrafgt** [reply]
Oh, yes, that's actually what I did as well, just forgot it. Thanks again!

**Comment by jamiezieziula** [comment]
Hi @stefanprodan - I'm following [this](https://fluxcd.io/legacy/helm-operator/helmrelease-guide/chart-sources/#git-repositories) documentation to accomplish the same ask as the op (referencing a local helm chart within a private git repo).  However, I think the documentation is misleading (or I am reading it incorrectly).  Based on the code snippets, I tried the following:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appA
spec:
  interval: 5m
  chart:
    git: git@github.com:org/repo
    ref: main
    path: charts/appA
```
however, this returns this error:
```
 Warning  error   6m2s   kustomize-controller  HelmRelease/default/appA dry-run failed, error: failed to create typed patch object: .spec.chart.path: field not declared in schema
  Warning  error   5m54s  kustomize-controller  HelmRelease/default/appA dry-run failed, error: failed to create typed patch object: .spec.chart.git: field not declared in schema
```
Thanks for your help! cc @jimid27

**Reply by stefanprodan** [reply]
@jamiedick those docs are for Flux v1, see https://fluxcd.io/docs/guides/helmreleases/#git-repository for v2

**Comment by nibatandukar** [comment]
@stefanprodan , I have used the same GitRepository, and Helmrelease, where I am changing the values.yaml with different replica count and image tag, but on the source controller log I am able to see "no changes since last reconcilation", but whenever I change the Chart.yaml "version: 0.3.0" , its deploying the new chnages.

```

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helm
spec:
  interval: 1m0s
  url: https://github.com/nibatandukar/fluxv2.git
  ref:
    branch: main
  secretRef:
    name: github-access-token
```


```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx1
  namespace: default
spec:
  releaseName: nginx1
  chart:
    spec:
      chart: ./niba/nginx
      version: '0.3.*'
      sourceRef:
        kind: GitRepository
        name: helm
  interval: 1m
```

How this can be resolve as, we need to change the image tag only in the values.yaml from the CI pipeline, instead of changing the Chart.yaml "version: 0.3.0"

**Reply by stefanprodan** [reply]
To trigger an upgrade at every commit, you need to set `reconcileStrategy: Revision` under `.spec.chart.spec`, docs here https://fluxcd.io/flux/components/source/helmcharts/#reconcile-strategy

PS. Using a semver range for charts coming from Git has no affect. You can remove the `version` field from your manifest.

**Reply by maulikprajapati** [reply]
@stefanprodan | When I change the Replica count from 2 to 3 in the values file for HPA, it triggers a full deployment, causing all pods to restart. This wasn’t an issue in Flux V1.

**Reply by jfmatth** [reply]
> To trigger an upgrade at every commit, you need to set `reconcileStrategy: Revision` under `.spec.chart.spec`, docs here https://fluxcd.io/flux/components/source/helmcharts/#reconcile-strategy
> 
> PS. Using a semver range for charts coming from Git has no affect. You can remove the `version` field from your manifest.

Hi @stefanprodan I was hoping this would solve my problem, but adding the reconcileStrategy: Revision doesn't seem to help 🥹 

I use a GitRepository as my helm source, here are the files:

```
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: justneverlift
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/jfmatth/justneverlift.com
  ref:
    branch: master
```

HelmChart
```
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: justneverlift
  namespace: flux-system
spec:
  interval: 1m0s
  chart: ./_helm
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: justneverlift
```

HelmRelease
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: justneverlift
  namespace: justneverlift
spec:
  interval: 1m
  chart:
    spec:
      chart: ./_helm
      sourceRef:
        kind: GitRepository
        name: justneverlift
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ghcr.io/jfmatth/justneverlift.com # {"$imagepolicy": "flux-system:justneverlift:name"}
      tag: v2025.11.22.2 # {"$imagepolicy": "flux-system:justneverlift:tag"}
```

What I would like is a change to values.yaml in the source GIT helm chart would trigger Flux to redeploy with the new values.  I've been testing with replica's but no luck.  If I use the default ChartVersion that seems to work.

Any help is appreciated, and I love this project - Thank you for creating / maintaining it.
