### DISCUSSION TITLE
Managing multiple K8s clusters with a single Flux Instance

### DISCUSSION THREAD

**Discussion by linuxbsdfreak** [fluxcd/flux2#2258] [General]
Hi. 

I would like to know the process of configuring multiple K8s clusters via a single Flux instance and a single repo.  I am assuming the following process. Please note cluster provisioning is handled outside of Flux. 

- Setup flux **management** cluster on AKS/EKS

- Boot strap flux on management cluster
```
flux bootstrap github \
--branch=main \
--owner=${GITHUB_USER} \
--repository=${GITHUB_REPO} \
--path=clusters/management \
--components-extra=image-reflector-controller,image-automation-controller \
--personal
```

File is created under clusters/management/*.yaml
```
- Copy gotk-sync.yaml from clusters/management/flux-system/  as clusters/management/production-sync.yaml
- Copy gotk-sync.yaml from clusters/management/flux-system/ as clusters/management/staging-sync.yaml
```

File content clusters/management/production-sync.yaml
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
 name: flux-system
 namespace: flux-system
spec:
 interval: 1m0s
 ref:
  branch: main
 secretRef:
  name: flux-system
 url: URL
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
 name: flux-system
 namespace: flux-system
spec:
 interval: 10m0s
 path: ./clusters/production
 prune: true
 sourceRef:
  kind: GitRepository
  name: flux-system
```

File content staging-sync.yaml
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
 name: flux-system
 namespace: flux-system
spec:
 interval: 1m0s
 ref:
  branch: main
 secretRef:
  name: flux-system
 url: URL
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
 name: flux-system
 namespace: flux-system
spec:
 interval: 10m0s
 path: ./clusters/staging
 prune: true
 sourceRef:
  kind: GitRepository
  name: flux-system
```

— Add the files under clusters/management/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- production-sync.yaml
- staging-sync.yaml
```

- Launch production and staging clusters 

- Add the kubeconfigs as secret follows
 ```
kubectl create secret generic -n flux-system production-kubeconfig --from-file=value.yaml=./kubeconfig
kubectl create secret generic -n flux-system staging-kubeconfig --from-file=value.yaml=./kubeconfig
```

- Add the files under clusters/management/production.yaml

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
 name: production
 namespace: flux-system
spec:
 interval: 10m0s
 kubeConfig:
  secretRef:
   name: production-kubeconfig
 timeout: 2m10s
 path: ./clusters/production/
 prune: true
```

- Add the files under clusters/management/staging.yaml

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
 name: production
 namespace: flux-system
spec:
 interval: 10m0s
 kubeConfig:
  secretRef:
   name: staging-kubeconfig
 timeout: 2m10s
 path: ./clusters/staging/
 prune: true
```

The target is to manage multiple K8s clusters using a single Flux instance.
