### DISCUSSION TITLE
kustomize-controller is treating our plain manifests as patches rather than applying them?

### DISCUSSION THREAD

**Discussion by haines** [fluxcd/flux2#2264] [Q&A] [answered]
I followed the [guide to migrate from Flux v1 read-only mode](https://fluxcd.io/docs/migration/flux-v1-migration/#flux-read-only-mode). Our source repository just contains plain YAML manifests, with no kustomization.yaml.

This is our `Kustomization` resource:

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  namespace: flux
  name: kubernetes-manifests
spec:
  interval: 1m0s
  path: ./production
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
```

Things seemed to be working fine until I discovered

- if I remove a field from a manifest, Flux does not remove it
- if I rename something within a manifest (e.g. a container in a pod template in a deployment), Flux adds the new one but leaves the old one in place

So it seems like the kustomize-controller is patching the resources rather than the old behaviour of just doing `kubectl apply`.

1. Is this a bug or expected behaviour? (perhaps it is due to https://github.com/fluxcd/kustomize-controller/issues/486?)
2. How do I get the old behaviour?
