### DISCUSSION TITLE
Upgrading to 0.18+: are file based patches in kustomize overlays still OK?

### DISCUSSION THREAD

**Discussion by jf647** [fluxcd/flux2#2269] [Q&A] [answered]
I've found myself in a problem with Flux patches and I'm trying to figure out if it's one of my own creation.

When 0.18 came out, I followed the guidance about converting patches{StrategicMerge,JSON6902} to patches with inline patches.  Now I'm trying to do image update automation in one of those patches, but it appears that the imagepolicy tags aren't recognized in that context, e.g.:

```YAML
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: drone
        namespace: drone
      spec:
        values:
          image:
            tag: 1.9.0 # {"$imagepolicy": "flux-system:drone:tag"}
```

The image update controller never rewrite this, even though it works correctly if I used the top-level images replacement mechanism:

```YAML
images:
  - name: drone/drone
    newTag: 2.7.3 # {"$imagepolicy": "flux-system:drone:tag"}
```

While the file was rewritten in the latter case, the helm release doesn't care about that, which is how I ended up trying to do it in a patch (or I suppose a helm postRenderer, but that seems even further afield of normal).

I assume I misinterpreted the guidance and that only the Kustomization in kustomize.toolkit.fluxcd.io/v1beta2 needed to be converted from files to inline patches.  It turns out that I was never using any patches in the CRD Kustomization, which led to me not really grokking https://fluxcd.io/docs/faq/#are-there-two-kustomization-types until today.

I think the path forward is clear; just convert back to files for the overlay Kustomizations, but I wanted to be sure.

Cheers
