### DISCUSSION TITLE
Using valuesFrom to replace objects in a List

### DISCUSSION THREAD

**Discussion by carpenike** [fluxcd/flux2#2293] [Q&A]
Hello!

I have a helm-release manifest that looks like the following, but the valuesFrom does not work. Is it possible to override values within a list?

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matrix-media-repo
  namespace: comms
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ananace.gitlab.io/charts
      chart: matrix-media-repo
      version: 1.0.6
      sourceRef:
        kind: HelmRepository
        name: ananace-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: turt2live/matrix-media-repo
      tag: v1.2.8

    config:
      datastores:
        - type: s3
          enabled: true
          forKinds: ["all"]
          opts:
            tempPath: "/tmp/mediarepo_s3_upload"
            ssl: false

 
...

  valuesFrom:
    - kind: ConfigMap
      name: matrix-media-ceph-bucket
      valuesKey: BUCKET_NAME
      targetPath: config.datastores[0].opts.bucketName
    - kind: ConfigMap
      name: matrix-media-ceph-bucket
      valuesKey: BUCKET_HOST
      targetPath: config.datastores[0].opts.endpoint
    - kind: Secret
      name: matrix-media-ceph-bucket
      valuesKey: AWS_ACCESS_KEY_ID
      targetPath: config.datastores[0].opts.accessKeyId
    - kind: Secret
      name: matrix-media-ceph-bucket
      valuesKey: AWS_SECRET_ACCESS_KEY
      targetPath: config.datastores.opts[0].accessSecret
```
