### DISCUSSION TITLE
Send Notification 'Generic' Providers Alerts to Elastic

### DISCUSSION THREAD

**Discussion by naustin** [fluxcd/flux2#2306] [Q&A] [answered]
Hi, 
   I'd like to send 'generic' provider alerts to Elastic but I keep getting a '401 Unauthorized' error and it seem like the notification controller isn't sending my Elastic user:password info in the header of the POST.

Here's how I'm creating the secret:
```
kubectl create secret generic elastic-token `
--from-literal=address=http://<elastic url>:9200/flux-alerts/_doc `
--from-literal=token=<user>:<password>
```

Here's my provider yaml:
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: flux-alerts-to-elastic
  namespace: flux-system
spec:
  secretRef:
    name: elastic-token
  type: generic
```

Here are the headers from the notification controller request, but no 'authorization' header:

```
host  - <elastic url>:9200
user-agent - Go-http-client/1.1
content-length - 579
content-type - application/json
gotk-component - kustomize-controller
accept-encoding - gzip
l5d-dst-canonical - <elastic url>:9200
```
