### DISCUSSION TITLE
Getting kustomization dry run errors after upgrade of image controllers to v1beta1

### DISCUSSION THREAD

**Discussion by psipider** [fluxcd/flux2#2313] [Q&A] [answered]
Hi, I've upgraded to the latest components and started getting the expected error: `ImageUpdateAutomation.image.toolkit.fluxcd.io "flux-system" is invalid: spec.sourceRef: Required value`

I followed the instructions to modify all imagePolicy, ImageRepository and ImageAutomationUpdate Manifests but now, when I run:  `flux reconcile kustomization flux-system --with-source` (or re-bootstrap) I get the following error:

`✗ Kustomization reconciliation failed: ImageUpdateAutomation/flux-system/flux-system dry-run failed, error: failed to prune fields: failed to convert merged object to last applied version: .spec.git: field not declared in schema` Occasionally it is .spec.sourceRef.

My manifest is:
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation

metadata:
  name: flux-system
  namespace: flux-system

spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: staging
    commit:
      author:
        email: email@obfuscated.com
        name: Flux CD Image Update Automation
      messageTemplate: '[ci skip] Flux CD Image Update Automation'
  interval: 2m
```
Thanks. Edited to add, my flux landscape looks like this:
```
✗ flux 0.25.2 <0.25.3 (new version is available, please upgrade)
✔ Kubernetes 1.21.5-eks-bc4871b >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.15.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.19.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.15.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.19.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.20.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.20.1
✔ all checks passed
```
