### DISCUSSION TITLE
Why are all containers defined in the gotk-component.yaml called "manager"?

### DISCUSSION THREAD

**Discussion by ArtunSubasi** [fluxcd/flux2#2315] [Q&A] [answered]
The gotk-components.yaml file which gets generated by Flux bootstrap or the Flux Terraform provider contains among other things the manifests for the GitOps toolkit components such as the source-controller, helm-controller etc.

The main containers of these components are all named "manager" although the pods are named "source-controller", "helm-controller" etc.

This leads to a confusing overview in monitoring systems when listing containers because all gotk component containers are named manager. See attached screenshot from the Containers view in New Relic:

![Bildschirmfoto 2022-01-20 um 10 41 58](https://user-images.githubusercontent.com/1876805/150313414-99b074cb-b543-477d-8eff-0fe31535ca6f.png)

Is there a specific reason for this naming? It would nice to see the container names which match the pod names.

**Comment by stefanprodan** [comment, marked as answer]
We use the same name for all containers to make patching easy. We have no plans on changing the container names as it would break Flux on all clusters where PsP and other patches are used e.g.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-flux-components
spec:
  template:
    metadata:
      annotations:
        # Required by Kubernetes node autoscaler
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 1337
      containers:
        - name: manager
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
```
