### DISCUSSION TITLE
Does SOPS encrypted secrets using KMS work with SecretGenerator?

### DISCUSSION THREAD

**Discussion by ronaldkan** [fluxcd/flux2#2355] [Q&A]
Thanks in advance, what I'm trying to do is to pass in SOPS encrypted values file that will be used with `helmRelease`.

Based on the document [https://fluxcd.io/docs/components/kustomize/kustomization/#kustomize-secretgenerator](https://fluxcd.io/docs/components/kustomize/kustomization/#kustomize-secretgenerator), I've been trying to generate secrets from sops kms encrypted yaml files. 

But i'm constantly getting the error, `error: data values must be of type string`

Example:
kustomization
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: 
  prune: true
  sourceRef:
    kind: GitRepository
    name: apprepo
    namespace: flux-system
  decryption:
    provider: sops
```

config.yaml
```
env:
  node_env: abc
```

config.yaml.encrypted
```
env:
    node_env: ENC[AES256_GCM,data:8hYW,iv:utS0UL6rQ1klizPfwyH27geXoV2t+IGyzaGowKYaud0=,tag:EIMe3tkljBz8BEo/4RVFlg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms.....
          created_at: ...
          enc: ...
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: ...
    mac: ...
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
```

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: config-yaml
    files:
      - config.yaml=config.yaml.encrypted
```

Result 
```
◎ waiting for Kustomization reconciliation
✗ Kustomization reconciliation failed: Secret/config-yaml-kd7tc994f4 forbidden, error: data values must be of type string
```

**Comment by souleb** [comment]
can you post your encryption command? Also review this page: https://github.com/fluxcd/kustomize-controller/blob/main/docs/spec/v1beta2/kustomization.md#kustomize-secretgenerator

**Reply by ronaldkan** [reply]
Command is as follow

`sops -e --input-type=yaml config.yaml > config.yaml.encrypted `

From the docs, I think the only crucial part is to indicate the decryption provider. Normal secret object seems fine but just now when I'm trying to convert sops encrypt values :/

**Reply by souleb** [reply]
hmm this works fine for me.

```yaml
secretGenerator:
- files:
  - config.yaml=config.yaml.encrypted
  name: config.yaml
```

```yaml
k get secret config.yaml-kt9h9ftf6k -n flux-system -o yaml                                                                                                                  11:12:36
apiVersion: v1
data:
  config.yaml: ZW52OgogICAgbm9kZV9lbnY6IGFiYwo=
kind: Secret
metadata:
  creationTimestamp: "2022-01-31T10:11:25Z"
  labels:
    kustomize.toolkit.fluxcd.io/name: podinfo
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: config.yaml-kt9h9ftf6k
  namespace: flux-system
  resourceVersion: "3451"
  uid: 52c751a2-0b44-4572-b6e1-a7f818a80a5c
type: Opaque
```

There should be something wrong with your encrypted file.

**Reply by ronaldkan** [reply]
strange, last 2 question 

1. you're using KMS key?
2. does your encrypted file looks similar to the follow block? 

```
env:
    node_env: ENC[AES256_GCM,data:8hYW,iv:utS0UL6rQ1klizPfwyH27geXoV2t+IGyzaGowKYaud0=,tag:EIMe3tkljBz8BEo/4RVFlg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms.....
          created_at: ...
          enc: ...
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: ...
    mac: ...
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
```
