### DISCUSSION TITLE
How to troubleshoot "Source is not ready" Error message

### DISCUSSION THREAD

**Discussion by oswalens** [fluxcd/flux2#2362] [Q&A]
Hello Everyone,

I am currently following the steps at https://fluxcd.io/docs/installation/#gitlab-and-gitlab-enterprise in order to bootstrap flux for an RedHat openshift cluster. The installation complete successfully up to the point where the process tries to validate it :
```
❯ flux bootstrap gitlab  --hostname=gitlab.cmt.apps.telenet.be --token-auth  --owner=cloud-and-infrastructure/application-runtime-consumption --repository=flux --branch=master --path=clusters/dev-ocp4
► connecting to https://gitlab.cmt.apps.telenet.be
► cloning branch "master" from Git repository "https://gitlab.cmt.apps.telenet.be/cloud-and-infrastructure/application-runtime-consumption/flux.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ component manifests are up to date
► installing components in "flux-system" namespace
✔ installed components
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
► generating source secret
► applying source secret "flux-system/flux-system"
✔ reconciled source secret
► generating sync manifests
✔ generated sync manifests
✔ sync manifests are up to date
► applying sync manifests
✔ reconciled sync configuration
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
✗ context deadline exceeded
► confirming components are healthy
✗ helm-controller: deployment not ready
✗ kustomize-controller: deployment not ready
✗ notification-controller: deployment not ready
✗ source-controller: deployment not ready
✗ bootstrap failed with 2 health check failure(s)
```

I can see that the following file has been generated In our gitlab repository (and the corresponding objects exist on our OCP cluster): 
```
❯ cat clusters/dev-ocp4/flux-system/gotk-sync.yaml
# This manifest was generated by flux. DO NOT EDIT.
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: https://gitlab.cmt.apps.telenet.be/cloud-and-infrastructure/application-runtime-consumption/flux.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/dev-ocp4
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

The following error message is displayed : 
```
❯ flux logs
2022-02-01T14:51:13.559Z info Kustomization/flux-system.flux-system - Source is not ready, artifact not found
```

I am not sure how to troubleshoot this further. I tried setting the log level to debug into the deployment ressource on OCP hoping to get more verbosity but no luck : 
```
❯ oc get deployment/kustomize-controller -o yaml | yq e '.spec.template.spec.containers[0].args' -
- --events-addr=http://notification-controller.flux-system.svc.cluster.local/
- --watch-all-namespaces=true
- --log-level=debug
- --log-encoding=json
- --enable-leader-election
```
