### DISCUSSION TITLE
HelmChart is not working if base url is different to HelmRepository base url

### DISCUSSION THREAD

**Discussion by kaflake** [fluxcd/flux2#2369] [Q&A]
Hi,
I want to add kube-prometheus-stack behinde a proxy.
For this I have create a HelmRepository with a CA-File as secretRef like this:

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 1m0s
  secretRef:
    name: helm-prometheus-community
  timeout: 1m0s
  url: https://prometheus-community.github.io/helm-charts
```

This Repo is workling. Now I want a HelmRelease like this:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 31.0.0
  interval: 1m0s
```

now a HelmChart is automaticly created, but there is a problem and I get this status:

`chart pull error: failed to download chart for remote reference: Get "https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-31.0.0/kube-prometheus-stack-31.0.0.tgz": x509: certificate is valid for github.com, www.github.com, not prometheus-community.github.io`

I try to set  `passCredentials : true` in the HelmRepository but it do not help. I think the problem is, that the chart-base-url is different from the repository. Is there a way to fix this or is it a bug?
