### DISCUSSION TITLE
Flux Kustomizations are not pruned like other resources

### DISCUSSION THREAD

**Discussion by johannges** [fluxcd/flux2#2374] [Q&A] [answered]
Hey,

i am using per Cluster one "Bootstrap" Flux Kustomization, that created Flux Kustomization per App i want to deploy.

The deploy part is working like a charm, but when i delete an app from the cluster, be removing it from the resources array, the Flux Kustomization of the App is not removed.

If this wanted behavior and can i somehow change that?

For more context:
I am using prune: true in all Kustomizations.

# the cluster bootstrap yaml:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-bootstrap
  namespace: flux-app
spec:
  force: true
  interval: 30s
  path: ./aws/flux/workload-clusters/central/testing2
  prune: true
  sourceRef:
    kind: GitRepository
    name: bootstrap-git-johannes-branch
status:
  inventory:
    entries:
    - id: flux-app_alertmanager-endpoint_kustomize.toolkit.fluxcd.io_Kustomization
      v: v1beta1
```

# The Kustomization Config
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-app
resources:
  - ../../bases/alertmanager-endpoint/main.yaml
```
  
# The alertmanager-endpoint Kustomization:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: alertmanager-endpoint
  namespace: flux-app
spec:
  force: false
  interval: 5m
  path: ./aws/flux/workload-clusters/bases/alertmanager-endpoint
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-kustomization-values
    - kind: Secret
      name: cluster-kustomization-values
  prune: true
  sourceRef:
    kind: GitRepository
    name: bootstrap-git-johannes-branch
  validation: client
```
