### DISCUSSION TITLE
patch a kustomization.yaml in a git repo?

### DISCUSSION THREAD

**Discussion by jr0dd** [fluxcd/flux2#2402] [Q&A] [answered]
So I was adding the flux2 git repo for my base install rather than having gotk-components.yaml. I was wondering if there was any way to patch the kustomization.yaml after the repo gets cloned to exclude `manifests/policies`? I can add an exclude for the `manifests/policies` and `manifests/**/kustomization.yaml` but then flux doesn't reconcile because it doesn't know how to handle the label transformers.
` LabelTransformer/labels dry-run failed, error: no matches for kind "LabelTransformer" in version "builtin"`

GitRepository
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 15m
  # renovate: datasource=github-releases
  url: https://github.com/fluxcd/flux2.git
  ref:
    tag: v0.26.1
  ignore: |
    # exclude all
    /*
    # include manifest dir
    !/manifests
```
Flux/Kustomization
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux
  patches:
    - target:
        kind: Deployment
        name: helm-controller
      patch: |-
        - op: replace
          path: /spec/template/spec/containers/0/resources/requests/memory
          value: 512Mi
        - op: replace
          path: /spec/template/spec/containers/0/resources/limits/memory
          value: 2Gi
```
Kustomize/Kustomization
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - namespace.yaml
  - ../bases/source-controller
  - ../bases/kustomize-controller
  - ../bases/notification-controller
  - ../bases/helm-controller
  - ../bases/image-reflector-controller
  - ../bases/image-automation-controller
  - ../rbac
  - ../policies.           **<<--- line to remove**
transformers:
  - labels.yaml
```
