### DISCUSSION TITLE
Push image updates in batch / opt out from event based triggers

### DISCUSSION THREAD

**Discussion by Wuzyn** [fluxcd/flux2#2461] [Proposals]
Hey all,
In my project, I've encountered a helm release overlap. I have 7 ImageRepository and ImagePolicy objects defined, all of them are deployed in the same helm release. I noticed that ImageRepository scans are triggering ImageUpdateAutomation to push changes to git repo, ignoring its `interval` property. In my project, images are built and pushed one by one, which results in having 7 commits, each per image, which in turn triggers 7 helm upgrades (again, ignoring HelmRelease `interval`), that are overlapping and causing them to fail, because "another process is already in progress" helm error. It's all nice and fancy, but IMO having an option to opt-out from event-based triggers, and running reconciliation based on intervals only, would be a nice feature. What do you guys think?

```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: image
  namespace: mynamespace
spec:
  image: <azure-container-registry>
  interval: 15m
  secretRef:
    name: x
```

```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: policy
  namespace: mynamespace
spec:
  imageRepositoryRef:
    name: image
  filterTags:
    pattern: '^dev-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    alphabetical:
      order: asc
```

```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: image-update-automation
  namespace: mynamespace
spec:
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: this
    namespace: flux-system
  update:
    path: ./clusters/dev/euw
    strategy: Setters
```

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-release
  namespace: mynamespace
spec:
  interval: 15m
  timeout: 3m
  chart:
    spec:
      chart: ./charts/pay-api
      version: '0.x.x'
      sourceRef:
        kind: GitRepository
        name: this
        namespace: flux-system
      interval: 15m
  values:
...
      image: acr/image:dev-42f42eb8-2022-02-22.090030 # {"$imagepolicy": "mynamespace:policy"}
...
```
