### DISCUSSION TITLE
Kustomization git source has frequent 404 errors for GitHub

### DISCUSSION THREAD

**Discussion by cep21** [fluxcd/flux2#2464] [Q&A] [answered]
Hi!

We notify slack on Kustomization errors.  We frequently get errors like this in slack
```
failed to download artifact from http://source-controller.flux-system.svc.cluster.local/./gitrepository/flux-system/flux-deployments/cd6502c6b5ee1c16598ac691f46061442f99e31e.tar.gz, status: 404 Not Found
```

We also have webhooks for GitHub which notifies flux2 if there is a new push.  It's possible the webhooks trigger too quickly and github isn't able to serve the file so soon.

I understand that in one sense, flux2 is just doing what it's told and it's a "GitHub problem", but since GitHub is such a popular source repository I wonder if there is something flux2 can do to reduce this noise.

**Comment by stefanprodan** [comment]
Is the receiver configured for `GitRepository` and `Kustomization` objects? If so, you could remove the `Kustomizations` as a new Git revision will trigger a Kustomization reconciliation.

**Reply by cep21** [reply]
If I do that, I won't know if the kustomization fails to apply (invalid YAML for example).  So I would like to keep that kind of notification, since they are pretty important.

**Reply by stefanprodan** [reply]
I think you're confusing Alerts with Receivers.

**Reply by cep21** [reply]
I may be.  Is there a way to receive messages in slack for errors for kustomize objects to apply while not receiving errors in slack for kustomize objects being unable to download artifacts from a source controller?

**Reply by cep21** [reply]
I found a similar issue here: https://github.com/fluxcd/source-controller/issues/544

**Reply by stefanprodan** [reply]
What I am suggesting is to remove the Kustomizations from the Receivers and have there only GitRepositories.

**Reply by kingdonb** [reply]
I think this is correct, if a Receiver targets both GitRepository and Kustomization, then it will reconcile both as soon as the change comes in. Kustomization is already subscribed to the GitRepository by way of `sourceRef` - when GitRepo is finished updating itself, it will send the notification to Kustomization, so there is no need to have both targeted in the Receiver.

The Receiver is only needed to notify Sources, which are external to the cluster and so cannot auto-negotiate a subscription (Kubernetes cannot go out and configure a webhook using GitHub API, at least not without new machinery)

In Kubernetes, the dominant paradigm is automatic subscription. This just doesn't work for resources that live outside of Kubernetes.

**Reply by cep21** [reply]
Here is my receiver object.  It only notifies on push and ping events from the git repo.  There is no Kustomization configured there.
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: flux-deployments
  labels:
    {{- include "company-flux-v2.labels" . | nindent 4 }}
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: flux-deployments
  resources:
    - kind: GitRepository
      name: flux-deployments
```
