### DISCUSSION TITLE
How to substitute bool value?

### DISCUSSION THREAD

**Discussion by jkittler** [fluxcd/flux2#2469] [Q&A]
I would like to use substitute with bool value and define a variable in Alert to suspend it.
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitops-foo
  namespace: flux-system
spec:
  path: ./foo
  postBuild:
    substitute:
      slack_channel: "flux-notifications"
      disable_flux_info_notifications: true
```
Here I can't please bool value. I get `string value expected`
And this is alert
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: foo-alert
  namespace: flux-system
spec:
  providerRef:
    name: slack-flux-notifications
  eventSeverity: info
  suspend: ${disable_flux_info_notifications:=false}
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: bla
    - kind: HelmRepository
      name: '*'
      namespace: bla
```
It's not possible to place variable ${variable}. I get that bool is expected.

Have you some suggestions on how to do it or find a different way?
Thank you for any advice ...
