### DISCUSSION TITLE
Use existing bootstrap on private repo.

### DISCUSSION THREAD

**Discussion by leviplj** [fluxcd/flux2#2478] [Q&A]
I want to create a way to set up the basics of a cluster using flux. The idea is to have N clusters that start with the same configuration regarding resources (ingress, nginx, apache, etc).

Using the command below, the repo is configured and the gotk files are created.
```bash
export GITHUB_USER=<user>
export GITHUB_TOKEN=<token>
flux bootstrap github --owner=<org> --repository=<repo> --branch=main --path=clusters/kind
```
I then add some files with K8s deployments on the path `clusters/all`, and change gotk-sync.yaml adding:
```yaml

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/all
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```
I push the changes and after a while, my cluster is updated.

Now I want a second [,third, fourth...] cluster that has the same config as the first one.
If I run the same bootstrap cmd again, my gotk-sync.yaml file will be overwritten.
I don't want to run bootstrap with a different path and "import" the files from clusters/kind. Imagine that we have 20 devs, and they'll create their own cluster that must have the same initial setup.

I'm looking for a second command that looks like `flux sync github --owner=<org> --repository=<repo> --branch=main --path=clusters/kind`. This command clones the repo, apply the configuration and stops there, no commit and push to GH.
I know `flux sync` doesn't exist but it expresses my idea of how it would work.

Is there any way of doing this with flux?
Thanks!
