### DISCUSSION TITLE
Kubernetes Environment variable Interpolation & Server-Side Apply

### DISCUSSION THREAD

**Discussion by jdfresser** [fluxcd/flux2#2495] [Q&A] [answered]
Hello,

We've been implementing variables interpolation recently, but have experienced some issues.

Based on https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/,

1/ We had a pod, let's say:
```
apiVersion: v1
kind: Pod
metadata:
  name: dependent-envars-demo
spec:
  containers:
    - name: dependent-envars-demo
      args:
        - while true; do echo -en '\n';  printf SERVICE_ADDRESS=$SERVICE_ADDRESS'\n'; sleep 30; done;
      command:
        - sh
        - -c
      image: busybox
      env:
        - name: SERVICE_ADDRESS
          value: "https://172.17.0.1:80"
```

2/ We found it easier to add interpolation, so we added the SERVICE PORT, SERVICE_IP & PROTOCOL variables, before the variable that referenced them:
```
apiVersion: v1
kind: Pod
metadata:
  name: dependent-envars-demo
spec:
  containers:
    - name: dependent-envars-demo
      args:
        - while true; do echo -en '\n';  printf SERVICE_ADDRESS=$SERVICE_ADDRESS'\n'; sleep 30; done;
      command:
        - sh
        - -c
      image: busybox
      env:
        - name: SERVICE_PORT
          value: "80"
        - name: SERVICE_IP
          value: "172.17.0.1"
        - name: PROTOCOL
          value: "https"
        - name: SERVICE_ADDRESS
          value: "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
```

Kustomize was keeping the same variables order, but the the order changed in Kubernetes:
```
   Environment:
      SERVICE_ADDRESS:  "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
      SERVICE_PORT:      80
      SERVICE_IP:     172.17.0.1
      PROTOCOL:  https
```
I guess this is linked to server-side apply which appends new environment variable, where it should recreate the deployment to support the right env var order.
The variable was not interpolated, and we had to delete the Deployment to let Flux recreate it, this time with the good order, but experiencing a downtime.

I'm writing this down if someone faces the same issues, and to know where this behaviour comes from (server-side apply?)
