### DISCUSSION TITLE
Declare a variable in base and define it in overlay for "non" yaml resources?

### DISCUSSION THREAD

**Discussion by dev-samples** [fluxcd/flux2#2500] [Q&A] [answered]
In a base I need to declare a variable: **SEED_REPO** in an "embedded" groovy script/dsl that I would like to set/define differently depending on which overlay I am in.

Based on:
https://fluxcd.io/docs/components/kustomize/kustomization/#variable-substitution

I have tried something like this:

**apps/base/release.yaml**
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: jenkins
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: 3.11.4      
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
  values:
    controller:
      JCasC:
        defaultConfig: true
        configScripts:
          seed-job: |
            jobs:
              - script: |
                  pipelineJob('seed-job') {
                    definition {
                        cpsScm {
                            scm {
                                git {
                                  remote {
                                      credentials('ssh-key')
                                      url( "${SEED_REPO}")
                                  }
                                  branch('master')
                              }
                            }
                        }
                    }
                  } 
```

**apps/team-a-jenkins/kustomization.yaml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team-a-jenkins
resources:
  - namespace.yaml
  - ../base
patchesStrategicMerge:
  - values.yaml

```

**apps/team-a-jenkins/values.yaml**
```

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    flux.weave.works/automated: "true"
spec:    
  values:
    controller:
      ingress:
        enabled: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: team-a-jenkins
spec:
  interval: 5m
  path: "./apps/team-a-jenkins/"
  postBuild:
    substitute:
      SEED_REPO: "git@team-a.git"
```

But it gives the error:

```
flux-system	apps          	False	kustomize build failed: accumulating resources: accumulation err='accumulating resources from 'team-a-jenkins': 
read /tmp/apps2765732815/apps/team-a-jenkins: is a directory': 
recursed accumulation of path '/tmp/apps2765732815/apps/team-a-jenkins': 
no matches for Id Kustomization.v1beta2.kustomize.toolkit.fluxcd.io/team-a-jenkins.team-a-jenkins; 
failed to find unique target for patch Kustomization.v1beta2.kustomize.toolkit.fluxcd.io/team-a-jenkins.team-a-jenkins

```
Pretty sure I am doing something stupid here also I know that variable substitution/templating is an anti-pattern in kustomize but I need to do it sometimes and also hoped that the additional functionality provided by flux:
https://fluxcd.io/docs/components/kustomize/kustomization/#variable-substitution

can solve this.

Any suggestions?

**Comment by stefanprodan** [comment, marked as answer]
Move the `team-a-jenkins` Flux Kustomization inside clusters/my-cluster

**Reply by dev-samples** [reply]
Ok so for each team I would end up with:

```
clusters/my-cluster/
clusters/my-cluster/team-a-jenkins.yaml #kind: Kustomization with postBuild.substitute
clusters/my-cluster/team-b-jenkins.yaml #kind: Kustomization  with postBuild.substitute
clusters/my-cluster/team-c-jenkins.yaml #kind: Kustomization  with postBuild.substitute

apps/team-a-jenkins/values.yaml
...
apps/team-b-jenkins/values.yaml
...
apps/team-c-jenkins/values.yaml
...

```
I would of course prefer to keep those team/project specific files out of the /clusters tree and only have them in the team/project specific overlays but I guess that's not an option?

**Reply by stefanprodan** [reply]
You can place them anywhere, see here an example: https://github.com/fluxcd/flux2-multi-tenancy

**Reply by stefanprodan** [reply]
The major issue with your manifests is that you placed the Flux Kustomization in a patch `values.yaml`, while there is nothing to be patched, as that object is not declared anywhere.

**Reply by dev-samples** [reply]
But I don't plan on creating separate sources for the teams (it not really multi tenancy), like the example here:
https://github.com/fluxcd/flux2-multi-tenancy/blob/main/tenants/base/dev-team/sync.yaml

I just have one bootstrapped repo per cluster with a single base and then multiple overlays where I need to set some variables in each overlay. E.g:

The base (declaring the variable **SEED_JOB**):

**apps/dev/mycluster/base/release.yaml**

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: jenkins
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: 3.11.4      
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
  values:
    controller:
      JCasC:
        defaultConfig: true
        configScripts:
          seed-job: |
            jobs:
              - script: |
                  pipelineJob('seed-job') {
                    definition {
                        cpsScm {
                            scm {
                                git {
                                  remote {
                                      credentials('ssh-key')
                                      url( "${SEED_REPO}")
                                  }
                                  branch('master')
                              }
                            }
                        }
                    }
                  } 
```



And then the overlay:
**apps/dev/mycluster/team-a-jenkins/kustomization.yaml**

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team-a-jenkins 
resources:
  - namespace.yaml
  - patch.yaml
  - ../base
patchesStrategicMerge:
  - values.yaml
```
where in particular:

**apps/dev/mycluster/team-a-jenkins/patch.yaml**
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: team-a-jenkins
  namespace: team-a-jenkins  
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  validation: client
  path: "./apps/dev/mycluster/team-a-jenkins/"
  postBuild:
    substitute:
      SEED_REPO: "git@team-a.git"
```

 But that gives the error:¨

`team-a-jenkins	team-a-jenkins	False	Source 'GitRepository/flux-system' not found   	                             	False    	
`
So seems in the sourceRef I cannot re-use the current repo?

**Reply by stefanprodan** [reply]
> So seems in the sourceRef I cannot re-use the current repo?

You can reuse sources across namespaces, but you need to specify the namespace:

```yaml
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
```

**Reply by dev-samples** [reply]
Thanks the error I got was:

```
NAMESPACE        	NAME             	READY	MESSAGE                                             	REVISION                     	SUSPENDED 
...
team-a-jenkins	team-a-jenkins	False	decryption secret error: Secret "sops-gpg" not found
```
so based on:
https://github.com/fluxcd/flux2/discussions/391#discussioncomment-115728

I now specify the **flux-system** namespace for the kustomization in both:

**apps/dev/mycluster/team-a-jenkins/kustomization.yaml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - namespace.yaml
  - patch.yaml
  - ../base
patchesStrategicMerge:
  - values.yaml
```
and in:

**apps/dev/mycluster/team-a-jenkins/patch.yaml**
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: team-a-jenkins
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  validation: client
  path: "./apps/dev/mycluster/team-a-jenkins/"
  postBuild:
    substitute:
      SEED_REPO: "git@team-a.git"
```

This means that all my team specific kustomizations as the one above will be created in the flux-system namespace. But as a result I now run into: https://github.com/fluxcd/flux2/discussions/2505
