### DISCUSSION TITLE
may not add resource with an already registered id: ~G_v1_Namespace|~X|flux-system

### DISCUSSION THREAD

**Discussion by dev-samples** [fluxcd/flux2#2505] [Q&A] [answered]
I have the below base:

**apps/mycluster/base/kustomization.yaml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
```

And the below two overlays :

```
##########################################################################
#
# Overlay a
#
##########################################################################
```

**apps/mycluster/team-a-jenkins/kustomization.yaml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - namespace.yaml
  - patch.yaml
  - ../base
```
**apps/mycluster/team-a-jenkins/namespace.yaml**
```
apiVersion: v1
kind: Namespace
metadata:
  name: team-a-jenkins
```
**apps/mycluster/team-a-jenkins/patch.yaml**
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: team-a-jenkins
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  validation: client
  path: "./apps/mycluster/team-a-jenkins/"
  postBuild:
    substitute:
      SEED_REPO: "git@team-a.git"
```
```
##########################################################################
#
# Overlay b
#
##########################################################################
```

**apps/mycluster/team-b-jenkins/kustomization.yaml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - namespace.yaml
  - patch
  - ../base
```
**apps/mycluster/team-b-jenkins/namespace.yaml**
```
apiVersion: v1
kind: Namespace
metadata:
  name: team-b-jenkins
```

**apps/mycluster/team-b-jenkins/patch.yaml**
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: team-b-jenkins
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  validation: client
  path: "./apps/mycluster/team-b-jenkins/"
  postBuild:
    substitute:
      SEED_REPO: "git@team-b.git"
```

Both overlays needs to use the flux-system namespace because that namespace contains a secret they both use - see: https://github.com/fluxcd/flux2/discussions/2500#discussioncomment-2299203

But when I build the above with kustomize (and eventually flux) I get the below error:

```
  kustomize build /home/user/repos/samples/apps/mycluster/
Error: accumulating resources: accumulation err='accumulating resources from 'sandbox-02-devops': '/home/user/repos/samples/apps/mycluster/team-b-jenkins' must resolve to a file': recursed merging from path '/home/user/repos/samples/apps/mycluster/team-b-jenkins': may not add resource with an already registered id: ~G_v1_Namespace|~X|flux-system
```
How do I register multiple overlays in the **flux-system** namespace using the same base?

I know this might be a kustomize specific question but maybe flux offers some tricks to get it to work?

**Comment by kingdonb** [comment]
If the overlay includes the flux-system namespace, you can delete it like this:

https://github.com/kingdonb/github-actions-demo/blob/2c6a88da6e11ffe1e236218a866b53ad165aa476/apps/podinfo/ex1-naive-dev-automation/kustomization.yaml#L12-L18

If you have multiple kustomize overlays in the same Flux kustomization, and they are composed together using Kustomize, they will have to be sure that individually the Kustomize overlays don't create identical resources. In this case they can't all create the flux-system namespace.

**Reply by dev-samples** [reply]
Not sure I understand, why do I want to delete the flux-system namespace? Right now each overlay (should?) only create they own specific resource/namespace.

I updated my post so its more clear that each overlay creates its own/unique namespace and why they need to reference the sops private key secret from the flux-system namespace (I don't want to distribute that secret across other namespaces).

**Reply by kingdonb** [reply]
This error says clearly "what is wrong" in a totally unhelpful way, only since it isn't clear (until reviewing your expanded manifests now) why `flux-system` namespace is tried to be created in the team-b-jenkins app. But now I get it:
> (quote from original post)
```
recursed merging from path '/home/user/repos/samples/apps/mycluster/team-b-jenkins':
may not add resource with an already registered id: ~G_v1_Namespace|~X|flux-system
```

This means that somewhere in your recursing Kustomize bases/resources, there is a definition of the `flux-system` namespace – and it gets repeated again somewhere else in a way that Kustomize stops and balks.

I guessed that was in your base. Now I see the issue:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: team-b-jenkins
```

You create 👆 this namespace in `team-b-jenkins` with the right name but, it gets overridded in the Kustomize overlay:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system    # <<<<<<
resources:
  - namespace.yaml
  - patch
  - ../base
```

I don't think you meant to include this line here. This is not `metadata.namespace` on a Kubernetes resource kind called Kustomization, it's the `namespace` transformer on a `Kustomize` overlay that lives outside the cluster. This sets the name of any `namespace` directives on the YAMLs that are processed by Kustomize, including rewriting the actual team-b namespace itself.

You should be able to reproduce it without Flux, by invoking Kustomize in the same way that Flux does:

https://fluxcd.io/docs/faq/#what-is-the-behavior-of-kustomize-used-by-flux

Find the root of the Kustomize overlay (where Flux Kustomization starts applying from, so like `  path: "./apps/mycluster/team-a-jenkins/"`) and run this command from there:

```
kustomize build --load-restrictor=LoadRestrictionsNone --reorder=legacy . \
| kubectl apply --server-side --dry-run=server -f-
```

Pipe the output into pager like `less` or some file, so you can examine it, and notice that the `flux-system` namespace is created now instead of the namespace that you intended to create there. I guess these teams are created from the same root Kustomization, with the same transformer applied, so it fails, fortunately! You do not want to manage the `flux-system` namespace at all from here. (If it had not failed like this, completely accidental luck I assume that it did fail this way, later on noticing and fixing this issue you might have accidentally deleted the `flux-system` namespace. And now I guess I know how that happens... we've definitely seen it before!)

The reason why I suggested that you might want to delete the namespace manifest is that while most apps like to distribute their kustomize deploy manifests in the app repo with a `Namespace`, so they can be installed at-once on clusters from a remote Kustomize overlay, in a multi-tenant configuration I've noticed it's not really possible for tenant to manage their own namespace.

So when I take the `podinfo` app from its home repo and include it in my cluster as a tenant, I had to delete the included namespace in order to get my manifests to apply correctly as a tenant. Depending on your total repo organization structure, this line of reason may or may not make sense. I have made too many guesses though as I did not have access to the full context in your Flux config repo.

Hope this helps!
