### DISCUSSION TITLE
Migrating from v1 envsubst to v2 substitutions

### DISCUSSION THREAD

**Discussion by zemaj** [fluxcd/flux2#2513] [Q&A] [answered]
I've begun the process of migrating to v2 and I've been stuck on the problem of migrating to substitutions for a couple of days. I've read and re-read the docs several times and I just can't figure out what I'm doing wrong. I can't find any clear examples of how to perform this migration, so looking for help!

My flux v1 repo looked like this;
```
├── base
│   ├── namespace1
│   │   ├── app.yaml
│   │   └── kustomization.yaml
│   └── kustomization.yaml
└── stages
    └── staging
        ├── flux
        └── kustomization.yaml
```

The flux v2 repo looks like;
```
├── base
│   ├── namespace1
│   │   ├── app.yaml
│   │   └── kustomization.yaml
│   └── kustomization.yaml
├── stages
│   └── staging
│       └── kustomization.yaml
└── clusters
    └── staging
        ├── flux-system
        │   ├── gotk-components.yaml
        │   ├── gotk-sync.yaml
        │   └── kustomization.yaml
        ├── cluster-system.yaml
        └── kustomization.yaml
```

Where `clusters/staging/flux-system/gotk-sync.yaml` was created by `flux bootstrap` and looks like;
```
# This manifest was generated by flux. DO NOT EDIT.
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: staging
  secretRef:
    name: flux-system
  url: ssh://git@github.com/org/repo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

I created `clusters/staging/kustomization.yaml`;
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-system.yaml
```

and `clusters/staging/cluster-system.yaml`;
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./stages/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      domain_name: "staging-example.com"
```

Other potentially relevant files
`stages/staging/kustomization.yaml`;
```
bases:
  - ../../base/

patchesStrategicMerge:
  - example-patch.yaml
```

`base/kustomization.yaml`;
```
bases:
  - namespace1/
```

`base/namespace1/kustomization.yaml`;
```
resources:
  - app.yaml
```

`base/namespace1/app.yaml`;
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app
  namespace: namespace1
spec:
  template:
    spec:
      containers:
        - name: app
          args:
            - app.${domain_name}
```

The cluster-system Kustomization is there to perform variable substitutions. It's in the `flux-system` namespace so that it can use the flux-system GitRepository. I don't want to overwrite `clusters/staging/flux-system/gotk-sync.yaml` so that flux bootstrap continues to work.

This setup somewhat works - the files in stages/staging and below are synced - however variable substitutions do not work. They just get replaced with blank strings. In the example above, `app.${domain_name}` turns into `app.`, but it should be `app.staging-example.com`

Do I have this setup all wrong? Do substitution Kustomization need to be in each namespace? If so, do I also have to setup a GitRepository in each namespace?
