### DISCUSSION TITLE
Integrating Automatic Image Updates with Kustomized HelmRelease

### DISCUSSION THREAD

**Discussion by pmatheson-greenphire** [fluxcd/flux2#2517] [Q&A]
We're having an issue integrating automatic image updates with kustomized HelmReleases. Looking for ideas.  

From the docs there are two main methods of auto updating images using #imagepolicy in manifests

You can add #imagepolicy to a CRD definition like HelmRelease/Tekton/Kustomized and flux will find and update the image tag

if you want to kustomize a helmrelease with something like 
_kustomiztion.yaml_
```
patches:
- target:
    kind: HelmRelease
    name: name
  patch: |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: doesnotmatter
    spec:
      values:
        image:
          repository: my.image.repo/name # {"$imagepolicy": "flux-system:hoth-name:name"}
          tag: 0.6.0-alpha.185 # {"$imagepolicy": "flux-system:hoth-name:tag"}
```
This will not work. Flux doesn't find and update these imagepolicy's b/c it's not supported. 

So you may want to try the kustomize method with something like 
_kustomiztion.yaml_
```
images:
- name: my.image.repo/name
  newName: my.image.repo/name # {"$imagepolicy": "flux-system:hoth-name:name"}
  newTag: 0.6.0-alpha.185 # {"$imagepolicy": "flux-system:hoth-name:tag"}
```
This also doesn't work b/c kustomize will not patch images in `HelmRelease.spec.values.image`

Any idea how we might do this? Our environments are configured like

_overlays/env1/kustomization.yaml_ 
```
resources:
   - workloads/
patches:
- target:
    kind: HelmRelease
    labelSelector: source=needsenvironment
  patch: |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: deployment
    spec:
      values:
        source:
          username: username
          password: password
 ```
_workloads/helmrelease.yaml_
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deployment
  labels:
    source: needsenvironment
spec:
  values:
    source:
      static: environment
```

**Comment by kingdonb** [comment]
Debugging for Image Update Automation is hard. Fortunately it has been improved somewhat, but it is still hard.

```
patch: |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: doesnotmatter
    spec:
      values:
        image:
          repository: my.image.repo/name # {"$imagepolicy": "flux-system:hoth-name:name"}
          tag: 0.6.0-alpha.185 # {"$imagepolicy": "flux-system:hoth-name:tag"}
```

This one will not work because `patch: |-` is a block/string literal which `kyaml` cannot parse through. The kyaml setters point to a particular YAML path which is to be overwritten by the Image Update Automation, and this is not a YAML path, but some line in an embedded document which is never parsed as YAML at this level.

```
images:
- name: my.image.repo/name
  newName: my.image.repo/name # {"$imagepolicy": "flux-system:hoth-name:name"}
  newTag: 0.6.0-alpha.185 # {"$imagepolicy": "flux-system:hoth-name:tag"}
```

This one **should** work. If it didn't work, the likely causes are:

* ImageUpdateAutomation resources must all be in the same namespace (ImageUpdateAutomation, ImagePolicy, ImageRepository)
* If cross-namespace refs are disabled for security, then the GitRepository should also be in the same namespace

This is somewhat confusing because `imagepolicy` kyaml markers do have a namespace in them, which seems to me leading in the direction that it could point to different namespaces, but in reality it still has to match between these resources. ImageUpdateAutomation will not act on policies in a different namespace.

The troubleshooting guide for these type of issues has a few more possibilities, it's a bit buried but the link is here:

* https://fluxcd.io/docs/migration/flux-v1-automation-migration/#troubleshooting
