### DISCUSSION TITLE
How to add component age-reflector-controller,image-automation-controller without bootstrap?

### DISCUSSION THREAD

**Discussion by UtorLin** [fluxcd/flux2#2522] [Q&A] [answered]
I tried to use automate image update on my eks cluster.
and my enviorment is AWS Codecommit and AWS ECR.

So I follow this document 
https://fluxcd.io/docs/use-cases/aws-codecommit/
To set up my fluxCD and it's success.
It could sync git repository file to deploy eks, but when I add automate image update that I don't know how to do it.

I can't find the information in document. The document use bootstrap to install it.

Have tried do run command `flux install image-reflector-controller` and `flux install image-automation-controller`, it can be install success but when I set up ImageRepository yaml on eks that give me a error : `ImageRepository/flux-system/xxxx dry-run failed, error: no matches for kind "ImageRepository" in version "image.toolkit.fluxcd.io/v1beta1"`

Is there any way to install these without bootstrap?

**Comment by stefanprodan** [comment, marked as answer]
`flux install --components-extra=image-reflector-controller,image-automation-controller`

**Reply by UtorLin** [reply]
> `flux install --components-extra=image-reflector-controller,image-automation-controller`

Thanks!! 
I can successfully install with the above command

But when I apply following ImageRepository get the error message: `unknown secret type "kubernetes.io/dockercfg"`
from `flux get image repository <repo name>` command


```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: <name>
  namespace: flux-system
spec:
  image: <account-id>.dkr.ecr.ap-northeast-1.amazonaws.com/<repo name>
  interval: 1m0s
  secretRef:
    name: aws-registry
```

**Reply by stefanprodan** [reply]
How did you created that secret? Can you use it to query ECR?

**Reply by UtorLin** [reply]
I created secret use following cronjob yaml.

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aws-registry-credential-cron
  namespace: flux-system
spec:
  schedule: "* */8 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2  
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          serviceAccountName: ecr
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          containers:
          - name: kubectl
            imagePullPolicy: IfNotPresent
            image: xynova/aws-kubectl:latest
            command:
            - "/bin/sh"
            - "-c"
            - |
              DOCKER_REGISTRY_SERVER=https://<accountID>.dkr.ecr.ap-northeast-1.amazonaws.com
              DOCKER_USER=AWS
              DOCKER_PASSWORD=$(aws ecr get-login --region ap-northeast-1 --registry-ids <accountID> | cut -d' ' -f6)
              kubectl delete secret aws-registry || true
              kubectl create secret docker-registry aws-registry \
              --docker-server=$DOCKER_REGISTRY_SERVER \
              --docker-username=$DOCKER_USER \
              --docker-password=$DOCKER_PASSWORD \
              --docker-email=no@email.local
              kubectl patch serviceaccount default -p '{"imagePullSecrets":[{"name":"aws-registry"}]}'
```

I sure serviceaccount : ecr could be login ECR successfully.
But I haven't tried use the secrets to query ecr, I will try this.

So error message `unknown secret type "kubernetes.io/dockercfg` may be because query ECR failed?

**Reply by stefanprodan** [reply]
Using create will fail to update the secret and the token will expire. See here how to change your command: https://github.com/fluxcd/flux2/blob/main/manifests/integrations/registry-credentials-sync/_cronjobs/_base/sync.yaml#L51-L57

**Reply by UtorLin** [reply]
But the content you provide is uses "create" method too, or am I misunderstood?
I check the secret could be query ecr and pull image.

via following pod.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: <name>
  namespace: flux-system
spec:
  containers:
  - name: <name>
    image: <service>/<repository>:1.0.0
    imagePullPolicy: Always
  imagePullSecrets:
  - name: aws-registry
 ```

responses:

```bash
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  19s   default-scheduler  Successfully assigned flux-system/<pod name> to <server domain>
  Normal  Pulling    18s   kubelet            Pulling image "<docker registry>/<repo>:1.0.0"
  Normal  Pulled     18s   kubelet            Successfully pulled image "<docker registry>/<repo>:1.0.0" in 146.469578ms
  Normal  Created    18s   kubelet            Created container <pod name>
  Normal  Started    18s   kubelet            Started container <pod name>
```
