### DISCUSSION TITLE
kustomization path not found in tmp

### DISCUSSION THREAD

**Discussion by ozmodiar192** [fluxcd/flux2#2539] [Q&A] [answered]
Hello,
I'm attempting to deploy raw K8s manifests from a git repository.  I have two files in the /deploy/development/ directory in my gitlab repo; one is a namespace.yaml with just the namespace, and one is a bunch of k8s resources. 

I have created the following kustomization in my flux repository in an attempt to deploy my manifests:
 ```
 apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: patientms
  namespace: flux-system
spec:
  interval: 5m
  path: ./deploy/development/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  healthChecks:
    - kind: Deployment
      name: patient-deployment
      namespace: patientms
  timeout: 80s
  ```

Here is the manifest for the GitRepsitory in question:
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: patientms
  namespace: flux-system
spec:
  interval: 1m
  url: https://gitlab.com/mycompany/platform/domain/member/services/member-ms-core.git
  ref:
    branch: feature/SRE-428
  secretRef:
    name: patientms-gitlab
```

When I attempt to apply this kustomization, I get the error:
``` 
Warning  error   0s     kustomize-controller  kustomization path not found: stat /tmp/patientms2913462404/deploy/development: no such file or directory
```

If I exec into the source-controller, I see the repository extracted in /data/gitrepository/flux-system/patientms.  My manifests are there.  There is nothing in /tmp, however.  This seems to imply my path is incorrect in the kustomization but the files are definitely there.  I attempted to explicitly add a kustomization.yaml to the repo that includes the two resources and that didn't do anything, either.

Any help would be appreciated.
