### DISCUSSION TITLE
ImageUpdateAutomation trouble shooting

### DISCUSSION THREAD

**Discussion by UtorLin** [fluxcd/flux2#2545] [Q&A] [answered]
I created an `ImageUpdateAutomation`.
Works fine in the following command.
`flux get image update --watch`

```bash
NAME       	READY	MESSAGE        	LAST RUN                 	SUSPENDED 
flux-system	True 	no updates made	2022-03-16T16:49:20+08:00	False    	
flux-system	True	no updates made	2022-03-16T16:50:23+08:00	False	
flux-system	True	no updates made	2022-03-16T16:51:26+08:00	False	
flux-system	True	no updates made	2022-03-16T16:52:28+08:00	False
```

The ImageRepository scan repository success.
``` bash
NAME       	READY	MESSAGE                      	LAST SCAN                	SUSPENDED 
<Name>	         True 	successful scan, found 5 tags	2022-03-16T16:54:22+08:00	False    	
<Name>	         True	successful scan, found 5 tags	2022-03-16T16:55:22+08:00	False	
```

I deploy the version 1.0.0 on k8s, and have 1.0.5 version in my docker registry.
ImagePolicy also have correctly found the last version 1.0.5

But in fact, My deployments are not change.

I want to know why `ImageUpdateAutomation` shows the message `no updates made`? But I can't find the log to see how it works.

**Comment by pjbgf** [comment]
@UtorLin a few things that you can do to help troubleshooting the `image-automation-controller`:

1) Confirm that the correct policy is in place and picking up the correct tag:
`flux get images policy`

This should show your image, including the new tag `1.0.5`. If not, probably the problem is in your policy.

2) Confirm that the controller is working as expected by increasing the `log-level` to `debug` in your `kustomization.yaml`:
```
patches:
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/args/2
      value: --log-level=debug
  target:
    kind: Deployment
    name: "image-automation-controller"
```

This will make the controller more verbose, allowing you to identify the tags that are being processed and what the controller is doing about them. The logs will then be available via:

`kubectl logs -n flux-system -l app=image-automation-controller`

**Comment by jegger** [comment]
I am having the same problem. The imageautomation brings a "no updates made" message.

Here is the output of `flux get images all --all-namespaces`:
```
NAMESPACE  	NAME                        	LAST SCAN                	SUSPENDED	READY	MESSAGE
flux-system	imagerepository/vuln-checker	2022-05-30T15:03:05+02:00	False    	True 	successful scan, found 21 tags

NAMESPACE  	NAME                    	LATEST IMAGE                                                	READY	MESSAGE
flux-system	imagepolicy/vuln-checker	xxx.xxx.xxx/stable/vuln-checker:master-41dd0b66-20	True 	Latest image tag for 'xxx.xxx.xxx/stable/vuln-checker' resolved to: master-41dd0b66-20

NAMESPACE  	NAME                                  	LAST RUN                 	SUSPENDED	READY	MESSAGE
flux-system	imageupdateautomation/k8s-fleet-master	2022-05-30T15:02:40+02:00	False    	True 	no updates made
```

I have the following ImageUpdateAutomation file:
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: k8s-fleet-master
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@xxxx.xx
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
  update:
    path: ./sks-stage
    strategy: Setters
```

It works as desired, if I specify a different push branch then 'master' (same as the checkout). E.g adding
```
push:
  branch: flux-test-pusher
```
With this different branch, it creates a new commit and pushes to the "flux-test-pusher" branch as expected. Because of that behavior, I assume that image-scanning and the tag-policy works well. 
Only in the case of the same branch (checkout and push) it does not seem to do anything. In the case of the same branch (and adding the --log-level=trace) I get the following output of the image-automation-controller pod:
```
{"level":"Level(-2)","ts":"2022-05-30T13:05:16.485Z","logger":"controller.imageupdateautomation","msg":"adjusting update path according to .spec.update.path","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"k8s-fleet-master","namespace":"flux-system","base":"/tmp/flux-system-flux-system1524327790","spec-path":"./sks-stage"}
{"level":"debug","ts":"2022-05-30T13:05:16.485Z","logger":"controller.imageupdateautomation","msg":"updating with setters according to image policies","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"k8s-fleet-master","namespace":"flux-system","count":1,"manifests-path":"/tmp/flux-system-flux-system1524327790/sks-stage"}
{"level":"Level(-2)","ts":"2022-05-30T13:05:16.485Z","logger":"controller.imageupdateautomation","msg":"found policy","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"k8s-fleet-master","namespace":"flux-system","namespace":"flux-system","name":"vuln-checker","latest-image":"xxxx.xxx.xxx/stable/vuln-checker:master-41dd0b66-20"}
{"level":"Level(-2)","ts":"2022-05-30T13:05:16.485Z","logger":"controller.imageupdateautomation","msg":"adding setter","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"k8s-fleet-master","namespace":"flux-system","name":"flux-system:vuln-checker"}
{"level":"Level(-2)","ts":"2022-05-30T13:05:16.485Z","logger":"controller.imageupdateautomation","msg":"adding setter","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"k8s-fleet-master","namespace":"flux-system","name":"flux-system:vuln-checker:tag"}
{"level":"Level(-2)","ts":"2022-05-30T13:05:16.485Z","logger":"controller.imageupdateautomation","msg":"adding setter","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"k8s-fleet-master","namespace":"flux-system","name":"flux-system:vuln-checker:name"}
{"level":"Level(-2)","ts":"2022-05-30T13:05:16.485Z","logger":"controller.imageupdateautomation","msg":"scanning files","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"k8s-fleet-master","namespace":"flux-system","path":"/tmp/flux-system-flux-system1524327790/sks-stage","token":"\"$imagepolicy\""}
{"level":"Level(-2)","ts":"2022-05-30T13:05:16.488Z","logger":"controller.imageupdateautomation","msg":"reading file","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"k8s-fleet-master","namespace":"flux-system","path":"piplanning/vuln-check/cronjob.yaml"}
{"level":"debug","ts":"2022-05-30T13:05:16.490Z","logger":"controller.imageupdateautomation","msg":"ran updates to working dir","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"k8s-fleet-master","namespace":"flux-system","working":"/tmp/flux-system-flux-system1524327790"}
{"level":"debug","ts":"2022-05-30T13:05:16.497Z","logger":"controller.imageupdateautomation","msg":"no changes made in working directory; no commit","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"k8s-fleet-master","namespace":"flux-system"}
```
Sadly I can not gain any additional info out of the logs. I'd appreciate if one can maybe explain what the imageautomation controller is actually doing / according to what logic it behaves. Thanks for any tips and explanations

**Comment by kingdonb** [comment]
It's not clear from your post if you have remembered to include the KYaml Setter comment in the resource to be updated.

ImageUpdateAutomation scans resources in the `path` and only operates on YAML lines that include one of these setter comments, matching an existing ImagePolicy with an update:

https://fluxcd.io/docs/guides/image-update/#configure-image-update-for-custom-resources

This is a required step from the image update guide, Update Automation will not function without it. (Have you included one?)

**Comment by jegger** [comment, marked as answer]
Thanks for your answer. 

Yes, I've added that to the actual manifest I wish to update. Here is the source of it:
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: vuln-checker
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: xxxx.xxxxxx.xxx/stable/vuln-checker:master-0179c14e-17 # {"$imagepolicy": "flux-system:k8s-fleet-master"}
            imagePullPolicy: Always
            name: vuln-checker
            stdin: true
            tty: true
          imagePullSecrets:
          - name: harbor3
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
          restartPolicy: OnFailure
  schedule: '30 8 */2 * *'
  successfulJobsHistoryLimit: 3
```

I don't know if it is important, but the resource I want to update is in a different namespace (vuln-check) than the imageAutomation (flux-system).

As said: Everything works as expected it I specify a different Push branch than the checkout branch. This tells me that the rest seems to be configured properly.
