### DISCUSSION TITLE
Way how to use kustomizeconfig generated configmap in different folder

### DISCUSSION THREAD

**Discussion by jprecuch** [fluxcd/flux2#2556] [Q&A] [answered]
Hi
I'm fightning one case where my repo look like this
```
clusters
- dev
-- required
--- kustomization
--- kustomizeconfig.yaml
infra
- dev
-- chart
--- release.yaml
```
In kustomizeconfig.yaml I have to use valuesFrom configmap
```
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/valuesFrom/name
    kind: HelmRelease
```

I want this configmap however be used also outside of cluster directory (in infra).
Hwever when I reference it in HelmRelease
```
  valuesFrom:
  - kind: ConfigMap
    name: my-manifest
```
It is not able to find it. It exists on cluster and is properly created, but the chart I want it to use seems to not know the ID or something?
```
helmrelease/test.test
could not find ConfigMap 'test/my-manifest'
``` 
is there some simple way how to be able to read this configmap outside of cluster folder?
If I move it to cluster it works but I want this to be common chart for multiple clusters instead of single one but still use cluster only resources.

Thanks
