### DISCUSSION TITLE
Using a private base repo for Kustomize

### DISCUSSION THREAD

**Discussion by VamKon** [fluxcd/flux2#2578] [Q&A] [answered]
Hello,

I have my kustomization.yaml for override defined like this:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/My-Enterprise/platform-gitops-base/microservice
namespace: some-namespace

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
  - path: deployment-patch.yaml
    target:
      kind: Deployment
```

But I keep running to kustomize errors during accumulation of resources. Is it possible to use a private GitHub repo to get the base for overlays? Is there a way to pass in auth info to kustomize controller? For security reasons I cannot have my base in a public repo. Is there some other mechanism in flux where I can clone this base repo dynamically and use file paths in my override kustomization file instead?

This works for me locally when I do kustomize build, but that is because I am already authenticated to my private base repo.

I see this issue - https://github.com/fluxcd/kustomize-controller/issues/136, but last comment is from 2020. Are private repos still not supported?

Thank you!!
