### DISCUSSION TITLE
wrong Node Kind for  expected: SequenceNode was MappingNode: value:

### DISCUSSION THREAD

**Discussion by dev-samples** [fluxcd/flux2#2581] [Q&A] [answered]
Based on:

https://fluxcd.io/docs/installation/#customize-flux-manifests

I am trying to increase the mem limits for the helm-controller. I have:

**flux-system/kustomization.yaml**

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

patchesStrategicMerge:
- test-patch.yaml

```
**flux-system/test-patch.yaml**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: helm-controller
  template:
    metadata:
      labels:
        app: helm-controller
    spec:
      containers:
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 64Mi

```

But flux gives this error:

```
flux-system	flux-system              	master/2c919ddf170f90c04a705321fe721d0be10d1e6g	False    	False	kustomize build failed: accumulating resources: accumulation err='accumulating resources from './flux-system': read /tmp/flux-system3422785719/clusters/sample/flux-system: is a directory': recursed accumulation of path '/tmp/flux-system3422785719/clusters/sample/flux-system': wrong Node Kind for  expected: SequenceNode was MappingNode: value: {resources:	
           	                         	                                               	         	     	  limi
```

Any suggestions?
