### DISCUSSION TITLE
How to update the tag on a GitRepository?

### DISCUSSION THREAD

**Discussion by VamKon** [fluxcd/flux2#2588] [Q&A] [answered]
Hello,

I am new to flux, so bear with me. I am trying to use a mono repo to hold my base templates and overrides for my microservices. With a structure like this:
```
base
  service1.yaml
  service2.yaml
  kustomization.yaml
env
  dev
    dev1
      service1_override.yaml
      service2_override.yaml
  qa
```
For higher environments I want to setup the bootstrap pointed at a version tag, so that I can control the sync for those environments when we need to make a new release.

So, my current gotk-sync.yaml file looks like this:

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    tag: v1.0.1
  secretRef:
    name: flux-system
  url: https://github.com/company/my-repo.git
```

What is the best way to update the tag to say v1.0.2 and have flux automatically sync commits from v1.0.2 tag? If I just update the tag ag and push to repo, the commits from new tag don't get picked up. I have only been able to get it to work if I manually apply this yaml on the cluster using kubectl apply -f.

Is there some flux command that I can to point flux at the right version tag? Thanks...

**Comment by kingdonb** [comment, marked as answer]
So the problem here is that, in the v1.0.1 tag, you have this section:

```
spec:
  interval: 1m0s
  ref:
    tag: v1.0.1
```

and Flux is syncing from that tag. Now you want to move to the `v1.0.2` tag, but Flux is still syncing from the `v1.0.1` tag as long as the manifest it's reading has that part in its spec. You obviously cannot just go back and update the `v1.0.1` tag to point at the next tag.

Can you have two different git repositories to avoid this issue? Then Flux will sync from the latest commit on a branch, (this is the default behavior as described in the guides) and when you update that branch with a pointer to a new tag, Flux will sync that tag.

The answer requires using more than one `GitRepository` because tags are not supposed to move, but a system which does not move on its own is not really "automated" in the sense of GitOps definition and pulling changes.

Another option is to use a semver range in the `ref` instead of an explicit tag:

```
spec:
  interval: 1m0s
  ref:
    semver: ^v1.0.1
```

This will select the latest tag, according to the matching of the semver range (so, tags in the 1.x.x range only)

(It's not updated by you then, it is updated by Flux, I'm not sure this is what you wanted, as I think you meant to deploy automatically in staging and then update production manually. But these are both options that could work.)
