### DISCUSSION TITLE
Multi-Tenancy Strategies

### DISCUSSION THREAD

**Discussion by stefanprodan** [fluxcd/flux2#263] [Proposals]
## Personas

**Platform Admin**
- Has cluster admin access to the fleet of clusters
- Has maintainer access to the fleet Git repository
- Manages cluster wide resources (CRDs, controllers, cluster roles, etc)
- Onboards the tenant’s main `GitRepository` and `Kustomization` 
- Manages tenants by assigning namespaces and role binding to the tenant apps

**Tenant** 
- Has admin access to the namespaces assigned to them by the platform admin
- Has maintainer access to the tenant Git repository and apps repositories 
- Manages app deployments with `GitRepositories` and `Kustomizations`
- Manages app releases with `HelmRepositories` and `HelmReleases`

## Current solution

See https://github.com/fluxcd/flux2-multi-tenancy

## Proposal

A tenant should be able to add sources with `GitRepository`, `HelmRepository` and `Bucket` objects in their namespaces and define how those sources are reconciled on the cluster with `Kustomization` and `HelmRelease` objects.

Platform admins should be able to make use of Kubernetes RBAC and restrict the reconciliation scope of a tenant's `Kustomizations` and `HelmReleases`.

![Screenshot 2020-09-27 at 12 00 11](https://user-images.githubusercontent.com/3797675/94360904-5af6b700-00b9-11eb-8bcd-3159b45458da.png)

### Defining tenants

Platform admins can define tenants by creating namespaces, RBAC and role bindings in the Git repository bootstrapped with `flux`.

Tenant with full access to a namespace:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
    name: web-team
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: gotk-reconciler
  namespace: web-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:web-team:reconciler
```

When a `Kustomization` or `HelmRelease` is being reconciled in the `web-team` namespace, it will run under the `gotk:web-team:reconciler` user that's restricted to the  `web-team` namespace only.

A cluster admin can extend the tenant access to be able to create custom resource definitions or any other cluster wide object:

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-admin
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: web-team-crd-reconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:web-team:reconciler
```

### Configuring multi-tenancy

Cluster admins can enable multi-tenancy isolation when installing or upgrading flux.

When a `Kustomization` or `HelmRelease` is being reconciled in a namespace other than the namespace where flux is installed, the reconciliation will run under the `gotk:<NAMESPACE>:reconciler` user. If the user doesn't exists or if the objects being reconciled don't belong to that namespace, the reconcilers will not be able to apply the tenant's sources on the cluster.

The cluster admins can provision tenants with `flux create tenant`, the command generates a namespace and role binding definition that grants the reconcilers full access to that namespace and that namespace only.

Cluster admin workflow:

```sh
# boostrap staging cluster with multi-tenancy enabled
flux bootstrap github \
--owner=org \
--repository=fleet-infra \
--path=staging \
--watch-all-namespaces=true \
--multi-tenancy=true

# clone the repo locally
git clone github.com/org/fleet-infra
cd fleet-infra

# create the dev-team tenant with access to two namespaces
flux create tenant dev-team \
--with-namespace=app1 \
--with-namespace=app2 \
--export > ./staging/dev-team-namespaces.yaml

# add the dev-team-infra repository 
flux create source git dev-team \
--url=https://github.com/org/dev-team-infra \
--branch=main \
--export > ./staging/dev-team-repository.yaml

# reconcile the staging dir of the dev-team-infra repository
flux create kustomization dev-team \
--source=dev-team \
--path="./staging" \
--export > ./staging/dev-team.yaml

# push dev-team tenant
git add -A && git commit -m "Add dev-team to staging" && git push
```

Dev team workflow:

```sh
# clone the repo locally
git clone github.com/org/dev-team-infra
cd dev-team-infra
mkdir staging

# add app1 Git repository
flux -n app1 create source git app1 \
--url=https://github.com/org/app1 \
--branch=staging \
--export > ./staging/app1-repository.yaml

# reconcile app1 on the staging cluster
flux -n app1 create kustomization app1 \
--source=app1 \
--path="./deploy" \
--export >  ./staging/app1.yaml

# add app2 Helm repository
flux -n app2 create source helm app2 \
--url=https://org.github.io/app2-charts \
--export > ./staging/app2-repository.yaml

# reconcile app2 on the staging cluster
flux -n app2 create helmrelease app2 \
--source=HelmRepository/app2 \
--chart=app2 \
--values="./values-staging.yaml" \
--export > ./staging/app2.yaml

# push apps deployments for the staging cluster
git add -A && git commit -m "Add apps to staging" && git push
```

**Comment by squaremo** [comment]
After having this explained to me at length (thanks Stefan!), I think there's a simpler design possible.

To recap, the problem to be solved is how to set things safely up so a tenant can create their own `GitRepository` and `Kustomization` objects (I refer to these together as "syncs", in the following), without being able to step outside the bounds given by the administrator. This means there's a chain of syncs:

    fleet repo --> tenant repo --> app repos

i.e., the fleet config delegates app syncing to the tenant, by syncing a _tenant repo_ containing definitions of GitRepository and Kustomization objects for the app repos.

Since you don't want to give tenant's any access to the system namespace, you can't let them create syncs there. You could create the delegating sync in the tenant namespace; however this means it's accessible to the tenant. Ideally you would want the delegating sync to live inside the system namespace, while anything defined within the tenant repo to be confined to the tenant namespace.

The solution given in the original post is that impersonation of service accounts can be switched off for tenants -- and when it's switched off, a user outside of the control of the tenant is impersonated instead. This has some downsides:

 - the behaviour of impersonation is inconsistent (sometimes it's respected, sometimes it's not)
 - you have to run the controller in a different mode, and you can't change your mind without risking breaking things

The multi-tenancy mode isn't strictly required -- if the tenant is restricted to creating syncs in their namespace(s), they can't impersonate a service account outside it. To achieve this, you have to have a service account (in the system namespace) for the _delegating_ sync, that has the restricted permissions. Then the problem becomes this much simpler one: service accounts are costly at startup time, because crypto, so you don't really want to have to create one per tenant.

A design which doesn't introduce another controller mode is: let syncs specify a _user_ to impersonate. Then the delegating syncs can refer to a user with restricted permissions for the tenant namespace, rather than having to have a service account created for them. App syncs can try to impersonate a service account or user, or leave it to the default -- they won't be able to access outside the namespace they are in.

**Reply by jonathan-innis** [reply]
One thing I wanted to get a better grip on here is how this binding is occurring from the _delegating_ sync to restrict access by the tenants. Is the proposal the same as Stefan's above where there is a role binding to a user that is impersonated by the controller at the time of reconciliation? If so, I think that this solves a lot of problems with the original solution in that tenants were not able to make changes to their _syncs_ without having the ability to elevate outside of their restricted namespaces.

**Reply by squaremo** [reply]
Each delegating sync -- a sync pointing at a tenant repo -- impersonates a user which has access only to the tenant namespace. This is exactly the same:

```
---
apiVersion: v1
kind: Namespace
metadata:
    name: web-team
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: gotk-reconciler
  namespace: web-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:web-team:reconciler
```

In fact I don't think I'm proposing anything different, other than _not_ having a flag for changing behaviour.

The missing bit of information (in both posts) is that flux controllers will default to using the _controller_ account to run syncs. So _just_ running the delegation sync under a user or service account is not enough, since all the tenant has to do is not mention an account in their `Kustomization` or whatever, and they have permission to sync anything. Stefan's proposal covers this by having the tenant isolation flag, which makes any sync running outside the system namespace impersonate a user (though it's not clear whether this is the default, or mandatory). My proposal, by removing the flag, does not cover this problem.

So: I propose in addition that every sync runs, by default, under the default service account of the namespace it's in. This is secure by default. I am prepared for it to give rise to other problems (and be a breaking change), but they may be preferable to either having a modal switch, or privilege escalation.
