### DISCUSSION TITLE
postRenderers from file

### DISCUSSION THREAD

**Discussion by norman-zon** [fluxcd/flux2#2634] [Q&A] [answered]
The documentation shows how to use a `kustomize` postRenderer directly in the `HelmRelease` CR.
Is it possible to somehow get the content of the postRenderer aka the `kustomization.yaml` from a file?

I use a HelmRelease with a GitRepository as source and would love to be able to use the postRenderer to set image tags with `kustomize edit set image`.
I am open to any suggestions how to solve this otherwise, but the postRenderer looks like the smartest and cleanest way to do this. Messing around with `sed` in my CI to set the image tag just feels wrong, when I already have structured data.

**Comment by kingdonb** [comment, marked as answer]
Is this a chart that you have control over the contents and values?

If the chart does not provide `values.yaml` settings for `image` and `tag`, then they should be added. This is a standard convention in nearly all Helm charts; updating the image registry source (eg. to use a localized mirror) and setting the image tag version are both very much standard conventions, and any chart that omits this block is deficient IMHO, if not formally according to best practices: https://github.com/kingdonb/podinfo/blob/8f712e5e4f1daee0b1b73a25b14a706826a2bc44/charts/podinfo/values.yaml#L9-L11

I'm not sure your question exactly because I'm not parsing or understanding what you're asking, get the content of the postRenderer from a file? No, it's part of the HelmRelease, like this:

https://github.com/kingdonb/bootstrap-repo/blob/da8d346bedeff887d9b5b429b166e51c5ae12531/apps/openvpn/helmrelease.yaml#L26-L46

It has to be fully embedded because the HelmRelease isn't an entity on the filesystem when it gets evaluated by the Helm Controller at runtime, it's an already-applied YAML-based resource that now lives in etcd on the cluster, with no relative path to anything or node on any filesystem tree, other than the chart content which doesn't have any mechanism to hold postrenderer content in it AFAIK.

I don't think there's any way to load the postrenderer script from a path inside of the chart. Maybe that could be added as a feature request? I'm not sure anyone has ever asked for this before, either. No idea if anything would block it from being implemented.

(The Flux Kustomization on the other hand has the filesystem of the Source from which it's being applied to work with, and it can do anything with the filesystem that is permitted by the upstream Kustomize API's spec.)

**Comment by norman-zon** [comment]
> It has to be fully embedded because the HelmRelease isn't an entity on the filesystem when it gets evaluated by the Helm Controller at runtime, it's an already-applied YAML-based resource that now lives in etcd on the cluster, with no relative path to anything or node on any filesystem tree, other than the chart content which doesn't have any mechanism to hold postrenderer content in it AFAIK.

This explains it to me. Thanks for the clarification.

My intention was to be able to use the native tooling (`kustomize edit set image`) for setting image tags **from a CI pipeline** instead of having to alter a values file. But I settled on using `yq` to set `image.tag` in the values.yaml directly.

**Reply by kingdonb** [reply]
That's a good solution 👍 

It would be good to provide a way for HelmReleases to incorporate values blocks and merge them in from external sources. Right now the only way to do this in Flux is probably through Kustomize controller, with substitution or with a configmap generator. But this only works for individual values, not values blocks, so it is clunky and impossible if you want to pass an entire section of config, (rather than just a bit of string that does not contain any newlines, and is only for a single value.)

I'm going to have to shift some of my focus back to these CI-based solutions, as Flux has been drawing the line in thicker and we have recommended for a long time already that anything complicated users want to do with respect to manifest generation should be done in CI.

But a cookbook of those examples would be really handy, as experience bears out these important tidbits of knowledge about what combinations will work and where, vs. what alternatives are required in other circumstances. I think that I went straight from `sed` to `jsonnet` in my [Guide to Manifest Generation](https://fluxcd.io/docs/use-cases/gh-actions-manifest-generation/) for Flux, it would be good to have some coverage in between those extremes, either or both solutions that use `kustomize edit set image` and `yq`.

**Comment by agardnerIT** [comment]
Hi, I'm also looking for something similar. I have a helm chart with a number of deployments (say 15) and I want to add a new `label` to each `Deployment`. The `postRenderer` section gets a bit long so rather than:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ...
  namespace: ...
spec:
  chart:
    spec:
      chart: ...
      sourceRef:
        kind: HelmRepository
        name: ...
      version: 0.0.1
  interval: 1m00s
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          # Repeat this block 15 times...
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: ...
            spec:
              template:
                metadata:
                  labels:
                    owner: adteam
                spec:
                  containers:
                  - name: adservice
                    env:
                      - name: owner
                        value: adteam
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: ...
            spec:
              template:
                metadata:
                  labels:
                    owner: checkoutteam
                spec:
                  containers:
                  - name: checkoutservice
                    env:
                      - name: owner
                        value: checkoutteam
```

It would be nice to be able to do this:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ...
  namespace: ...
spec:
  chart:
    spec:
      chart: ...
      sourceRef:
        kind: HelmRepository
        name: ...
      version: 0.0.1
  interval: 1m00s
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - ad-service.yaml
          - checkout-service.yaml
          - # 13 other file includes
```
