### DISCUSSION TITLE
Disable upgrade on values changes

### DISCUSSION THREAD

**Discussion by jprecuch** [fluxcd/flux2#2637] [Q&A] [answered]
Hi,
I noticed one scenario which kind of blocks our pipeline to work properly. 

Story:
We have file in repo which hosts the values.yaml details, from this file we create configmap and that one is referenced in HelmRelease as valuesFrom 

When we perform adjustment to this values.yaml file, it does following:
```
kustomization/0-run-region-deploy.flux-system
ConfigMap/sde/sde-manifest configured
Kustomization/flux-system/3-deploy-helmcharts configured
revision
jaro/cvtchanges/5cf458362296bbf58d18b4acb139110605626feb
```
Then it goes and upgrades also chart relevant to this file to the same release version
```
helmrelease/test.sde
Helm upgrade has started
revision
DEV122
helmrelease/test.sde
Helm upgrade succeeded
revision
DEV122
```
Then the issue surfaced because of following case:

We want to adjust values.yaml file and upgrade to new version of chart. The current helm-controller logic seems to be  following:
1. It configures new configmap
2. It upgrades CURRENT release with new yaml files
3. It upgrades AGAIN to a new release
```
kustomization/0-run-region-deploy.flux-system
ConfigMap/sde/sde-manifest configured
Kustomization/flux-system/3-deploy-helmcharts configured
revision
jaro/cvtchanges/5cf458362296bbf58d18b4acb139110605626feb
helmrelease/test.sde

Helm upgrade has started
revision
DEV122
helmrelease/test.sde
Helm upgrade succeeded
revision
DEV122

helmrelease/test.sde
Helm upgrade has started
revision
DEV125
helmrelease/test.sde
Helm upgrade succeeded
revision
DEV125
```

This bring issue because those new changes will be release specific and we don't want current chart to be upgraded using them, only new release.
Thanks for any soltuion to this

**Comment by kingdonb** [comment, marked as answer]
There are some details about your story that I'm not entirely clear on, that will help to reproduce if there is an issue here.

Are you aware of this:
* Using a git source with different values of `reconcileStrategy` https://fluxcd.io/docs/components/source/helmcharts/#reconcile-strategy

The `values.yaml` or `valuesFiles` in a HelmRelease are considered part of the chart. If you don't set the reconcile strategy to `Revision` then you will never see a new HelmChart artifact triggering a new release, unless the ChartVersion has been changed.

Also, wondering if the issue might be solved if you are made aware of a feature: Kustomize's `configMapGenerator` and `secretGenerator` which can be used with Flux.

This takes advantage of:
* values using configmap -- vs values stored in the chart

https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize

When the configmap or secret is updated through the generator, the name reference in the HelmRelease is updated by the parent Kustomization too, and this triggers an immediate release upgrade.

Hope this helps!

**Reply by jprecuch** [reply]
@kingdonb Thanks for your answer.

We are already using values using configmap. That's why we hit an issue mentioned in first post.
We are trying to do exactly opposite of what you meantioned "When the configmap or secret is updated through the generator, the name reference in the HelmRelease is updated by the parent Kustomization too, and this triggers an immediate release upgrade." 

Is there a way how to disable this? It is simple to reproduce
```
  valuesFrom:
  - kind: ConfigMap
    name: sde-manifest
```
To reproduce this simply do the following:
Have job to deploy charts based on type
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 3-deploy-helmcharts
  namespace: flux-system
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/types/dev-hw
  prune: false
```
regiontype
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: deploy-charts-dev-hw
  
resources:
  - ../../applications/my-chart
 ```
helmrelease
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-chart
  namespace: sde
spec:
  suspend: false
  releaseName: my-chart
  chart:
    spec:
      chart: my-chart
      version: <version>
      sourceRef:
        kind: HelmRepository
        name: testing-repo
        namespace: flux-system
  interval: 2m
  install:
    disableWait: true
    remediation:
      retries: 0
  upgrade:
    disableWait: true
    preserveValues: false
    remediation:
      retries: 0
  valuesFrom:
  - kind: ConfigMap
    name: sde-manifest
```
Have kustomization file with generation of values.yaml and generator off
```
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: sde-manifest
    namespace: sde
    files:
    - values.yaml=../../../manifest-files/gcp-fluxcd5/sde-manifest.yaml
```
Once this is done, then adjust version of helmchart to something else but at the same time adjust the sde-manifest.yaml.
This way the logic I've mentioned in first question post will happen. For now we found only suspend option which would need to be adjusted to prevent upgrade with new values.yaml for old version.
