### DISCUSSION TITLE
preferred way for patching infrastructure configuration for each environment

### DISCUSSION THREAD

**Discussion by mgenov** [fluxcd/flux2#2644] [Q&A] [answered]
With apps looks simple to be patched, but with infrastructure the most examples are using: 

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  prune: true
```
which seems to use the whole infrastructure and this raises the question what is the preferred way for patching infrastructure configuration? For example if we have a redis service deployed on production with 6 nodes, but on development environment we would like to deploy a single node. What is the preferred way for structure these things out?
