### DISCUSSION TITLE
Kustomization not found in tmp

### DISCUSSION THREAD

**Discussion by rgcs88** [fluxcd/flux2#2669] [Q&A] [answered]
👋🏾 

First of all, sorry if I am being too dumb. I am testing flux out and I am stuck at this.

I bootstrapped a cluster and used [flux2-kustomize-helm-example](https://github.com/fluxcd/flux2-kustomize-helm-example) as starting point.

I am using a different file structure:

```
├── clusters
│   ├── develop
│   ├── production
│   └── staging 
├── infrastructure
│   ├── .sources
│   ├── 3p
│   ├── kube-system
│   └── nginx-ingress-controller
└── resources
    ├── base
    ├── develop
    ├── production
    └── staging
```

After bootstrapping the `develop` cluster, `infrastructure` kustomization runs well. The `resources` one is not working. it says that the folder is not found in `/tmp`. The folder exists on the repo and nothing was found on `/tmp` of `kustomize-controller`'s pod.

Can anyone help me debug this?

Here follows some useful (I think) outputs:
```
❯ flux check
► checking prerequisites
✗ flux 0.28.5 <0.29.3 (new version is available, please upgrade)
✔ Kubernetes 1.21.10-gke.2000 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.18.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.22.3
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.22.5
✔ all checks passed
```

```
# ./clusters/develop/infrastructure.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  prune: true
```

```
# ./clusters/develop/resources.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: resources
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./resources/develop/
  prune: false
  wait: true
  timeout: 5m0s
```

Here is the `GitRepository` definition from bootstrapping...
```
# This manifest was generated by flux. DO NOT EDIT.
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/<ORG>/infra-k8s-fleet-mgmt
---
```

Any reconciliation attempt results in this:
```
❯ flux reconcile kustomization resources --with-source --verbose
► annotating GitRepository flux-system in flux-system namespace
✔ GitRepository annotated
◎ waiting for GitRepository reconciliation
✔ fetched revision main/4afad383007eec3cf9dc815c8219157ff407a44a
► annotating Kustomization resources in flux-system namespace
✔ Kustomization annotated
◎ waiting for Kustomization reconciliation
✗ Kustomization reconciliation failed: kustomization path not found: stat /tmp/resources619456544/resources/develop: no such file or directory
```

Finally the describe outputs of kustomization:
```
❯ k -n flux-system describe kustomizations.kustomize.toolkit.fluxcd.io resources
Name:         resources
Namespace:    flux-system
Labels:       kustomize.toolkit.fluxcd.io/name=flux-system
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  reconcile.fluxcd.io/requestedAt: 2022-04-22T11:39:28.984138-03:00
API Version:  kustomize.toolkit.fluxcd.io/v1beta2
Kind:         Kustomization
Metadata:
  Creation Timestamp:  2022-04-22T14:26:18Z
  Finalizers:
    finalizers.fluxcd.io
  Generation:  1
  Managed Fields:
    API Version:  kustomize.toolkit.fluxcd.io/v1beta2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:kustomize.toolkit.fluxcd.io/name:
          f:kustomize.toolkit.fluxcd.io/namespace:
      f:spec:
        f:dependsOn:
        f:interval:
        f:path:
        f:prune:
        f:sourceRef:
          f:kind:
          f:name:
        f:timeout:
        f:wait:
    Manager:      kustomize-controller
    Operation:    Apply
    Time:         2022-04-22T14:26:18Z
    API Version:  kustomize.toolkit.fluxcd.io/v1beta2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:reconcile.fluxcd.io/requestedAt:
    Manager:      flux
    Operation:    Update
    Time:         2022-04-22T14:26:23Z
    API Version:  kustomize.toolkit.fluxcd.io/v1beta2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizers.fluxcd.io":
      f:status:
        f:conditions:
        f:lastAttemptedRevision:
        f:lastHandledReconcileAt:
        f:observedGeneration:
    Manager:         gotk-kustomize-controller
    Operation:       Update
    Time:            2022-04-22T14:26:23Z
  Resource Version:  527068664
  UID:               5be92d3f-c2f2-47bb-b262-5d3d79233a90
Spec:
  Depends On:
    Name:    infrastructure
  Force:     false
  Interval:  5m0s
  Path:      ./resources/develop/
  Prune:     false
  Source Ref:
    Kind:   GitRepository
    Name:   flux-system
  Timeout:  10m0s
  Wait:     true
Status:
  Conditions:
    Last Transition Time:     2022-04-22T15:11:18Z
    Message:                  kustomization path not found: stat /tmp/resources176669695/resources/develop: no such file or directory
    Reason:                   ArtifactFailed
    Status:                   False
    Type:                     Ready
  Last Attempted Revision:    main/4afad383007eec3cf9dc815c8219157ff407a44a
  Last Handled Reconcile At:  2022-04-22T11:39:28.984138-03:00
  Observed Generation:        1
Events:
  Type     Reason          Age                  From                  Message
  ----     ------          ----                 ----                  -------
  Warning  ArtifactFailed  48m                  kustomize-controller  kustomization path not found: stat /tmp/resources1955842673/resources/develop: no such file or directory
  Warning  ArtifactFailed  48m                  kustomize-controller  kustomization path not found: stat /tmp/resources2601607127/resources/develop: no such file or directory
  Warning  ArtifactFailed  43m                  kustomize-controller  kustomization path not found: stat /tmp/resources914500476/resources/develop: no such file or directory
  Warning  ArtifactFailed  38m                  kustomize-controller  kustomization path not found: stat /tmp/resources1329609987/resources/develop: no such file or directory
  Warning  ArtifactFailed  35m                  kustomize-controller  kustomization path not found: stat /tmp/resources619456544/resources/develop: no such file or directory
  Warning  ArtifactFailed  33m                  kustomize-controller  kustomization path not found: stat /tmp/resources1269529111/resources/develop: no such file or directory
  Warning  ArtifactFailed  28m                  kustomize-controller  kustomization path not found: stat /tmp/resources3935436579/resources/develop: no such file or directory
  Warning  ArtifactFailed  23m                  kustomize-controller  kustomization path not found: stat /tmp/resources3582318918/resources/develop: no such file or directory
  Warning  ArtifactFailed  18m                  kustomize-controller  kustomization path not found: stat /tmp/resources3541436241/resources/develop: no such file or directory
  Warning  ArtifactFailed  3m20s (x3 over 13m)  kustomize-controller  (combined from similar events): kustomization path not found: stat /tmp/resources176669695/resources/develop: no such file or directory
```

Sorry for the flood, but any help pointing me to my error would be very appreciated.
