### DISCUSSION TITLE
How to rollback helm chart / helm release?

### DISCUSSION THREAD

**Discussion by Thaval** [fluxcd/flux2#2681] [Q&A] [answered]
Hi,

I'd like to know how to rollback a release using helm. 
My configuration for the helmrelease is as follows
```
 install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    disableHooks: true
    force: true
    recreate: true
    cleanupOnFail: true
    timeout: "5m"
```

However, when the pods are not starting up, the helm release ends in a "Update retries exhausted" error and the pods will remain in the "failed" state. I expect the pods to be removed and the previous pods to be recovered (by the deployment, because the deployment should be rolled back [and all other resources in that helm chart]). 

Once the deployment/pods fail, I see the message in the helm-controller when I fix the errors
```
Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io \"watcher\": the object has been modified; please apply your changes to the latest version and try again
```
Due to that, the HelmRelease is still unchanged, it does not take the new changes. 

The only way out of here is to suspsend and resume the helmrease after the fix.. This is not what my team and me expected. 
Did we configure the rollback maybe in a wrong way?

**Comment by Thaval** [comment, marked as answer]
Could get it to work with this configuration:
```
  install:
    remediation:
      retries: 1
  upgrade:
    # Remediaton configuration for when an Helm upgrade action fails
    remediation:
      # Amount of retries to attempt after a failure,
      # setting this to 0 means no remedation will be
      # attempted
      retries: 1
  # Configuration options for the Helm rollback action
  rollback:
    timeout: 2m
    disableWait: false
    disableHooks: false
    recreate: false
    force: true
    cleanupOnFail: true
```

It does not automatic rollback, but it keeps the running and failed pods. However, when I upload a fix, then the rollback takes places. 
At least it's the behavior I could observe.
