### DISCUSSION TITLE
Integrate values.yaml when using HelmRepository

### DISCUSSION THREAD

**Discussion by Thaval** [fluxcd/flux2#2682] [Q&A] [answered]
Hi, 

I use the flux cli to create a HelmRepository and a HelmRelease. When specifying the values.yaml as parameter, the values are copied into the HelmRelease manifest. As this is not what I want, I just added the "valuesFiles:" to the chart. 
This works when I use the git solution, so the chart is stored in git and the values.yaml is also stored in git.

When I put the chart into a HelmRepository, this no longer works. 
As stated in the documentation ([Chart-File-References](https://fluxcd.io/docs/migration/helm-operator-migration/#chart-file-references)), the valuesFiles should be relative to the sourceRef and is no longer restricted to GitRepository. As my sourceRef is the HelmRepository, I thought I could just reference the values.yaml. However, I'm wondering how to get the values.yaml to my HelmRepository?

Edit:
So it seems to work when the values.yaml is in the root directory of chart but not in some children folder
```
spec:
  chart:
    spec:
      chart: chartName
      reconcileStrategy: ChartVersion
      valuesFiles:
      # - test-values.yaml # this works!
      - /values/app/ctx1/test-values.yaml # this DOES NOT work!
      sourceRef:
        kind: HelmRepository
        name: chartName-Repo
```
