### DISCUSSION TITLE
Is it possible to decrypt SOPs files with "flux build" ?

### DISCUSSION THREAD

**Discussion by Amir-Ahmad** [fluxcd/flux2#2707] [Q&A] [answered]
For example, if i had these two files in a dir:
```
configmap-sops-encrypted.yaml
kustomization.yaml
```

I could use `flux build ks <something> --path <path>` to generate manifest files, which gives me something like this:
```
apiVersion: v1
data:
  KEY1: ENC[AES256_GCM,data:truncated,type:str]
  KEY2: ENC[AES256_GCM,data:truncated,type:str]
kind: ConfigMap
```

Can I use `flux build` to return the decrypted output instead?

**Comment by stefanprodan** [comment, marked as answer]
> Can I use flux build to return the decrypted output instead?

Flux the CLI by design does not have access to the private keys, as they can be in AWS KMS, Vault, etc. You could use SOPS the CLI to decrypt them after running `flux build`.

**Reply by Amir-Ahmad** [reply]
Thanks for the info. I've got it working with this command that I'm noting for anyone else:

```
flux build ks "<ks>" --path "<path>" | sops --input-type=yaml --output-type=yaml --ignore-mac -d /dev/stdin
```

You also need a creation rule in the .sops.yaml:
```
creation_rules:
  - path_regex: /dev/stdin
    age: >-
      AGEKEY
```

EDIT: Also thanks for all your work on this project :)
