### DISCUSSION TITLE
Apply patches to external sources

### DISCUSSION THREAD

**Discussion by ahgraber** [fluxcd/flux2#2712] [Q&A] [answered]
I am trying to apply patch kustomizations to manifests that I am pulling from GitRepository Resources:
As a simple example, I want to add a label `goldilocks.fairwinds.com/enabled: "true"` to the namespace created.  

1. ~When I commit, everything appears to function (i.e., `flux get kustomization -A` does not return any errors), but the namespace that is created is clearly not patched~ 
**EDIT - this does work, I have other issues with more complex kustomizations that resolving point 2 could help**
2. I want to test my kustomization with `flux build kustomization ...` but that seems to require local resources.  Is it possible to use against a GitRepository source, and if so, how?

Here is the source GitRepository:

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cockroachdb-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/cockroachdb/cockroach-operator.git
  ref:
    tag: v2.6.0
  ignore: |
    # exclude all
    /*
    # include install dir with crds
    !/install
```

Here is my flux kustomization with the patch declared:

```yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cockroachdb-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  # wait: true
  sourceRef:
    kind: GitRepository
    name: cockroachdb-source

  # ref: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/inlinePatch.md
  # ref: https://fluxcd.io/docs/components/kustomize/api/
  patches:
    - target:
        version: v1
        kind: Namespace
        name: cockroach-operator-system
      patch: |-
        kind: Namespace
        metadata:
          name: cockroach-operator-system
          labels:
            control-plane: cockroach-operator
            goldilocks.fairwinds.com/enabled: "true"
```
