### DISCUSSION TITLE
Perform incremental upgrades for specific releases.

### DISCUSSION THREAD

**Discussion by gprossliner** [fluxcd/flux2#2731] [General] [answered]
Hi guys!

On a test environment, I test how to upgrade a release of the harbor project chart (https://artifacthub.io/packages/helm/harbor/harbor).
Because it has not been upgraded a while, the installed version on production is `1.7.5`.

If I use fluxcd for the upgrade, and I specify no `version: 1.9*` in the `HelmRelease.spec.chart.spec.version` field, the Helm-Controller  successfully upgrades harbor to `1.9.0`, as shown with `helm history`:

```
$ helm -n harbor history harbor                                
REVISION	UPDATED                 	STATUS    	CHART       	APP VERSION	DESCRIPTION     
1       	Thu May 12 14:51:38 2022	superseded	harbor-1.7.5	2.3.5      	Upgrade complete
2       	Thu May 12 14:55:26 2022	deployed  	harbor-1.9.0	2.5.0      	Upgrade complete

```

So far, so good.

But: Harbor has a known (and very annoying) bug, that if you skip a version, an error is logged in a component named `harbor-core`, telling it is unable to perform a database upgrade, and it creates a new (empty) database.

To avoid this, you need are not allowed to skip a version. If you take a look at the released versions of the chart (they are 1.7.5, 1.8.0, 1.8.1, 1.8.2, 1.9.0).

I would like to instruct flux to perform this when upgrading (e.g. `HelmRelease.spec.upgrade.incremental`, like):

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 1m0s
  upgrade:
    incremental: true #run in incremental mode -> no version is skipped
  chart:    
    spec:
      version: 1.9.*
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: helm-repo
```

The Helm-Controller should perform the upgrade to each version incrementally, resulting in the following history:

```
$ helm -n harbor history harbor                                
REVISION	UPDATED                 	STATUS    	CHART       	APP VERSION	DESCRIPTION     
1       	Thu May 12 15:21:38 2022	superseded	harbor-1.7.5	2.3.5      	Install complete
2       	Thu May 12 15:24:05 2022	superseded	harbor-1.8.0	2.4.0      	Upgrade complete
3       	Thu May 12 15:27:34 2022	superseded	harbor-1.8.1	2.4.1      	Upgrade complete
4       	Thu May 12 15:30:48 2022	superseded	harbor-1.8.2	2.4.2      	Upgrade complete
5       	Thu May 12 15:34:10 2022	deployed  	harbor-1.9.0	2.5.0      	Upgrade complete
```

So I have the following questions: 

* It there a way to make this work in the current version (some configuration I have not seen)?
* Would you consider this a valuable feature for flux?
* Is there a chance that this may be added to flux? I know this would be a lot of work. Currently flux doesn't seem to care about old chart versions. The `status` resource of the helmchart object doesn't show a complete list of versions.

Thanks!
