### DISCUSSION TITLE
ImagePolicy for pgadmin4

### DISCUSSION THREAD

**Discussion by masterkain** [fluxcd/flux2#2737] [Q&A]
I'm trying to write an ImagePolicy for the docker hub repo https://hub.docker.com/r/dpage/pgadmin4/tags

```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: pgadmin
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: pgadmin
  policy:
    semver:
      range: ">=6.9"
```

doesn't work because it's not semver, given how the owner tags his/her images, what's your suggestion to keep the image up to date in this case?

**Comment by kingdonb** [comment]
I am not certain that Flux currently has an answer for this.

Semver depends on 3-digit format, and the other strategies "Alphabetic" and "Numeric" won't work, unless you can fix the first digit?

Do you want the behavior of Semver, where incrementing Major version (the first digit) is assumed to contain breaking changes, so automated upgrades through major versions will not be processed (but minor updates will)? It's hard to guess because I'm not sure what the digits mean, when we're not actually using semver, (*they might not have any formal semantic meaning.)

If so, I think this will work:

```
  filterTags:
    pattern: '^6\.(?P<minor>[0-9]+)'
    extract: '$minor'
  policy:
    numerical:
      order: asc
```

Then, when you're ready to bump the major version, for example change it to:

```
    pattern: '^7\.(?P<minor>[0-9]+)'
```

This is not very elegant, but I think it should work?
