### DISCUSSION TITLE
Patch default values in an HelmRelease

### DISCUSSION THREAD

**Discussion by M-Gregoire** [fluxcd/flux2#2740] [Q&A] [answered]
Hello,

I'm currently installing [rook](https://github.com/rook/rook/) via fluxcd in my cluster.

I want to modify a value from the default [values.yaml](https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml). The value in question is an item of an list (`cephBlockPools/0/spec/replicated/size` [line 390](https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml#L390) )

This means if I do something like:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  chart:
    spec:
      chart: rook-ceph-cluster
      sourceRef:
        kind: HelmRepository
        name: rook-helm-repo
        namespace: rook-ceph
  values:
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: <My new size here>
```

The item I'm passing (`ceph-blockpool`) completely replaces default item, which is not what I want (https://github.com/helm/helm/issues/6569).

It seems the right way to do this is to use [postRenderers](https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.PostRenderer) from HelmRelease, either with a patchesStrategicMerge or a patchesJson6902.

So I did something like:
```
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              - op: replace
                path: "/spec/values/cephBlockPools/0/spec/replicated/size"
                value: <My new size here>
```

But this fails with:
```
error while running post render on files: replace operation does not apply: doc is missing path: /spec/values/cephBlockPools/0/spec │
│ /replicated/size: missing value
```

I imagine this is because `cephBlockPools` is indeed not define in my values, as I want to use all default values.

- Is it possible to modify default values this way?
- If so, what kind of patch is best to do so?

Thank you for any help you might provide.

**Comment by souleb** [comment, marked as answer]
I think you have to specify the `target`, see  https://fluxcd.io/docs/components/helm/helmreleases/#post-renderers.

**Reply by M-Gregoire** [reply]
Thank you for your reply!
However I'm not sure what would be the target, as far as I know, there is not object which represents the default values that I could patch.

**Reply by souleb** [reply]
If you want to Override values, using `.spec.values` or `.spec.valuesFrom` are the way to go. What the helm-controller is doing, is coalescing the specified `values` object with the chart `values.yaml`, giving priority to the values objects. The `coalesces` function states this:

```go
//	- Scalar values and arrays are replaced, maps are merged
````

can you try with:
```yaml
  values:
    cephBlockPools:
      name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: <My new size here>

```

that is using a map instead of a list item?


`spec.Postrenders` patches are applied on the final manifests after the helm-controller as rendered the chart for the release with e.g. the specified `spec.values`.

**Reply by M-Gregoire** [reply]
Thank you for your reply!

As you explained, the objects generated can be patched but not the values per se. I had success with the following:
```
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              - op: replace
                path: "/spec/replicated/size"
                value: 1
            target:
              kind: CephBlockPool
              name: "ceph-blockpool"
```

However, I don't believe the values approach you suggested can work. 
The `cephBlockPools` takes a list, not a map: https://github.com/rook/rook/blob/9b6143baa7442c097bc77466376dd794aa3eda58/deploy/charts/rook-ceph-cluster/values.yaml#L385

Using the values as showed in your example leads to ` mapping values are not allowed in this context in File:`

I would have preferred using the "value" approach but that doesn't seems possible without copying the whole array.

Side note: Would you mind linking me the documentation where you found `//	- Scalar values and arrays are replaced, maps are merged` ?


In any case, thanks a lot for your help, thanks to it, I managed to get a working solution!
