### DISCUSSION TITLE
Best way to patch HelmRelease sub-charts using Kustomization

### DISCUSSION THREAD

**Discussion by shiftychris** [fluxcd/flux2#2744] [Q&A] [answered]
Hoping someone can point me the right direction. I have a HelmRelease chart which has sub charts inside to do multiple deployments for the same container. I need to do some patching to add tolerations/taints to each sub service (servicea, serviceb, servicec, serviced etc). Is there a documented or recommended way to do this without defining an individual patch for each sub service. 

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: service-name
  namespace: default
spec:
  releaseName: servicename-sandbox
  interval: 3m0s
  chart:
    spec:
      chart: ./charts/service-name.tgz
      sourceRef:
        kind: GitRepository
        name: service-repository
        namespace: flux-system
  values:
    global:
      APIKey: aaaabbbbccccc
    sevicea:
      configmap:
        LOG_LEVEL: INFO
        CONFIGVAL: AB
      image:
        repository: repo.io/service.name # {"$imagepolicy": "flux-system:servicename:name"}
        tag: v0.0.1 # {"$imagepolicy": "flux-system:servicename:tag"}
    serviceb:
      configmap:
        LOG_LEVEL: INFO
        CONFIGVAL: AC
      image:
        repository: repo.io/service.name # {"$imagepolicy": "flux-system:servicename:name"}
        tag: v0.0.1 # {"$imagepolicy": "flux-system:servicename:tag"}
    servicec:
        #same as above but with different config
    serviced:
        #same as above but with different config
    servicee:
        #same as above but with different configmap value
```

If not (from my googling I am at a blank), is there any form of support for patch paths supporting any form of regex/wildcard/list/array of paths for example: 

```
spec:
  patches:
    - patch: |
       - op: add
         path: "/spec/values/*/tolerations" or ["/spec/values/servicea/tolerations", "/spec/values/serviceb/tolerations"]
```
