### DISCUSSION TITLE
Context deadline exceeded

### DISCUSSION THREAD

**Discussion by MarsMero** [fluxcd/flux2#2758] [Q&A] [answered]
My source gitrepository/flux-system is stuck, after bootrstraping, on following error:
failed to checkout and determine revision: unable to clone 'https://gitlab.rankomat.pl/rankomat/rankomat-deployment.git': Get "https://gitlab.rankomat.pl/rankomat/rankomat-deployment.git/info/refs?service=git-upload-pack": context deadline exceeded
bootsraping:
```sh
flux bootstrap gitlab \
  --hostname=gitlab.rankomat.pl \
  --owner=rankomat \
  --repository=rankomat-deployment \
  --branch=master \
  --path=clusters/clusterdev \
  --token-auth \
  --personal
```
My gotk-sync.yaml file looks like this:
```yaml
# This manifest was generated by flux. DO NOT EDIT.
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: https://gitlab.rankomat.pl/rankomat/rankomat-deployment.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/clusterdev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```
Values in flux-system secret are correct and when I use them inside the pod/source-controller-* with wget it also works. 
`wget --header 'Authorization: Basic <username and password from secret>' https://gitlab.rankomat.pl/rankomat/rankomat-deployment.git/info/refs?service=git-upload-pack`

I also added another GitRepository for helm charts pointing at the same repo. Here however I added ssh url ssh://git@gitlab.rankomat.pl:22/rankomat/rankomat-deployment.git and ssh credentials in a separate secret and it works. 

Could you please help me solve this problem?

flux version 0.30.2
