### DISCUSSION TITLE
Make API more consistent

### DISCUSSION THREAD

**Discussion by hendrikhalkow** [fluxcd/flux2#2779] [Proposals]
Hi all, with the introduction of OCI support for Helm to Flux, I started thinking about how the API could be updated so that the naming and the structure becomes more consistent. As of now, some object names are confusing.

For example, an `ImageRepository` should be called `OCIRepository`. However, the `GitRepository` is actually not a Git repository, but a reference within a repository. So I came up with this idea to make the API more consistent.

As a benefit, all four types of source could be used updated via source controller. Also, their usage in `HelmRelease` would be much simpler and more consistent like in the following example:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v3alpha1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m
  chart:
    kind: OCIArtifact | HelmArtifact | GitArtifact | BucketArtifact
    name: podinfo
    namespace: flux-system
  values:
    replicaCount: 2
```

## Git

For Git, I propose to rename the resource that is currently called `GitRepository` to `GitArtifact`. The new `GitRepository` is the actual `GitRepository`, referenced by `GitArtifact` and `GitUpdatePolicy`, which is similar to `ImagePolicy`, but for Git repos. An example could look as follows:

```yaml
apiVersion: source.toolkit.fluxcd.io/v2alpha1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  url: https://github.com/stefanprodan/podinfo
  interval: 1m0s
---
apiVersion: update.toolkit.fluxcd.io/v1alpha1
kind: GitUpdatePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  repository:
    name: podinfo
    namespace: flux-system
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'
---
apiVersion: source.toolkit.fluxcd.io/v2alpha1
kind: GitArtifact
metadata:
  name: podinfo-image
  namespace: flux-system
spec:
  interval: 1m0s
  repository:
    name: podinfo
    namespace: flux-system
  ref:
    tag: v1.0.0 # {"$gitupdatepolicy": "flux-system:podinfo:tag"}
    path: /
```

## OCI

Instead of having a `HelmRepository` of type `oci`, I propose using the current `ImageRepository` and rename that to `OCIRepository`, the current `ImagePolicy` to `OCIUpdatePolicy`, and to introduce a new `OCIArtifact` resource that represents a specific image, identified via tag or digest.

```yaml
apiVersion: source.toolkit.fluxcd.io/v2alpha1
kind: OCIRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  repository: ghcr.io/stefanprodan/podinfo
---
apiVersion: update.toolkit.fluxcd.io/v1alpha1
kind: OCIUpdatePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  repository:
    name: podinfo
    namespace: flux-system
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'
---
apiVersion: source.toolkit.fluxcd.io/v2alpha1
kind: OCIArtifact
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  repository:
    name: podinfo
    namespace: flux-system
  ref:
    tag: 1.0.0 # {"$ociupdatepolicy": "flux-system:podinfo:tag"}
```

## Helm

The same for Helm. For consistency reasons, the term `HelmRepository` contains a chart name but not a version so that it works similar to the other repository, update policy and artifact types.

```yaml
apiVersion: source.toolkit.fluxcd.io/v2alpha1
# It's actually a helm chart, but for consistency and since the name `HelmChart`
# is already in use, I'd call it `HelmRepository`
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  url: https://stefanprodan.github.io/podinfo
  chart: podinfo
  interval: 1m0s
---
apiVersion: update.toolkit.fluxcd.io/v1alpha1
kind: HelmUpdatePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  repository:
    name: podinfo
    namespace: flux-system
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'
---
apiVersion: source.toolkit.fluxcd.io/v2alpha1
kind: HelmArtifact
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  repository:
    name: podinfo
    namespace: flux-system
  ref:
    version: v1.0.0 # {"$helmupdatepolicy": "flux-system:podinfo:tag"}
```

## Bucket

The same for bucket. For consistency reasons, the `BucketRepository` and `BucketArtifact ` contains a path with it's elements as array so that they work similar to the other types and that the update via policy would work.

```yaml
apiVersion: source.toolkit.fluxcd.io/v2alpha1
kind: BucketRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  provider: aws
  endpoint: s3.amazonaws.com
  region: us-east-1
  bucketName: podinfo
  path:
  - charts
  - podinfo
---
apiVersion: update.toolkit.fluxcd.io/v1alpha1
kind: BucketUpdatePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  repository:
    name: podinfo
    namespace: flux-system
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'
---
apiVersion: source.toolkit.fluxcd.io/v2alpha1
kind: BucketArtifact
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  repository:
    name: podinfo
    namespace: flux-system
  ref:
    # path elements as list to make it updateable via update policy
    path:
    - v1.0.0 # {"$bucketupdatepolicy": "flux-system:podinfo:tag"}
```

What are your thoughts about this?
