### DISCUSSION TITLE
Flux2 upgrade itself from HelmRelease

### DISCUSSION THREAD

**Discussion by mo-saeed** [fluxcd/flux2#2789] [General] [answered]
Hi,

I have flux2 helmrelease as a part of flux operations and it always fails when it tries to upgrade or to reconcile itself with this error
```
Helm upgrade failed: another operation (install/upgrade/rollback) is in progress
```

maybe i am doing sth wrong here, the helm release has this block 

```
spec:
  releaseName: flux2
  upgrade:
    remediation:
      retries: -1
  install:
    remediation:
      retries: -1
  interval: 5m
```
would appreciate any advice.
