### DISCUSSION TITLE
How to disable rollback in helmrelease

### DISCUSSION THREAD

**Discussion by mo-saeed** [fluxcd/flux2#2793] [General] [answered]
I need to disable rollback for one helm release, in fluxV1 there was a bool to enable or disable.

**Comment by hiddeco** [comment, marked as answer]
These are configured using remediation strategies, see: https://fluxcd.io/docs/components/helm/helmreleases/#configuring-failure-remediation

**Reply by mo-saeed** [reply]
this would do it  ?
```  
  upgrade:
    remediation:
      retries: 0
  install:
    remediation:
      retries: 0

**Reply by hiddeco** [reply]
Correct.

**Reply by mo-saeed** [reply]
Perfect, Thanks a lot

**Reply by mo-saeed** [reply]
Sorry I have a related question, If i want to have infinity retries as this

```
  upgrade:
    remediation:
      retries: -1
  install:
    remediation:
      retries: -1
```
does that mean rollback will never be performed ?

**Reply by mo-saeed** [reply]
mainly this is what i configured for flux1 and i want to convert it to flux2
```
  rollback:
    enable: true
    retry: true
    maxRetries: 0
```
and i am not sure if this is right 

```
  upgrade:
    remediation:
      retries: -1
  install:
    remediation:
      retries: -1
```

**Reply by nalum** [reply]
Yes, that should work for infinite retries, from the docs:

> The `retries` can be set to configure the number of retries after an initial failure. A negative integer results in infinite retries.

**Reply by mo-saeed** [reply]
my question is flux v1 behaviour here 
```
 rollback:
    enable: true
    retry: true
    maxRetries: 0
```
which means infinity number of **rollback** retries

equals to flux2  behaviour ?
 ```
  upgrade:
    remediation:
      retries: -1
  install:
    remediation:
      retries: -1
``` 
coz i think that means infinite number of **upgrade**  retried not **rollback** retries

**Reply by nalum** [reply]
Ah I misunderstood, looking at the spec for the remediation the retries is the count for how many times the upgrade/install action is attempted, the remediation strategy is done between each retry attempt.

> Retries is the number of retries that should be attempted on failures before bailing. Remediation, using ‘Strategy’, is performed between each attempt. Defaults to ‘0’, a negative integer equals to unlimited retries.

https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.UpgradeRemediation

Remediation for upgrades defaults to `rollback`, so yes it will infinitely rollback but it infinitely attempts to upgrade.

That's my understanding, correct me if I'm wrong :smile:

**Reply by mo-saeed** [reply]
I think i understand the same but still I am wondering how it really works, so if i add this 
```
 upgrade:
   remediation:
     retries: -1
 install:
   remediation:
     retries: -1
```
does that mean:
- first upgrade attempt failed
- rollback
- rollback success 
- upgrade again
- fail 
- rollback
- rollback success

or

- first upgrade attempt failed
- rollback 
- rollback success
- done

what i want is  :D 

- first upgrade attempt failed
- rollback
- rollback failed
- rollback again
- rollback success
- done

it's confusing i know..
