### DISCUSSION TITLE
Scheduling and gitrepo

### DISCUSSION THREAD

**Discussion by pmialon** [fluxcd/flux2#2794] [Q&A]
Hi,

We have a lot of "unable to clone 'https://mycompany/gitrepo/repo.git': transport close (potentially due to a timeout)" in our logs.

We tried to increase the `.spec.timeout` and we could see that we had fewer errors. 

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitrepo
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: gitsecret
  timeout: 3m0s
  url: https://mycompany/gitrepo/repo.git
```

My question is can we setup a gitrepo with an interval of 1 minute and a timeout of 5 minutes?

Will flux continue to orchestrate a clone of the code repository every minute, or wait until the previous clone is finished in timeout or not?

Our gitserver is a SAAS so I can't see why the clone operation is failing few times per hour. 

Regards,
