### DISCUSSION TITLE
Why Flux2 can not use one ImageRepository for all images

### DISCUSSION THREAD

**Discussion by rohammosalli** [fluxcd/flux2#2797] [General]
Hi @stefanprodan , I have a question regarding `Configure image scanning` for Image Repositories in Flux2 

We are using the Google artifact repository for our image registry, inside the registry each application has a name & inside the name there are tags. like `europe-west3-docker.pkg.dev/company/team/application1`

```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: flux-image-repository
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/company/team/
  interval: 1m0s
```
The problem is your documents say...
```
Note
If you are using the same image repository in several manifests, you only need one ImageRepository object for it
```

but when I use just my registry address in `spec.image` like `europe-west3-docker.pkg.dev/company/team/` after `flux reconcile kustomization --with-source flux-system` flux can not scan all the registry and images with tags & I have to point to a specific image name so flux2 can find the tags.

since in Flux1 this part was automatically done by flux (scanning images & tags) but in Flux2 for each application in my GitOps I have to define a new ImageRepository kind like this 

```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: flux-image-repository
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/company/team/AnyApplicationName
  interval: 1m0s
```
 How we can define an ImageRepository by just pointing to 1 registry with (image & tags) scan enabled so flux2 can list all images and tags.
