### DISCUSSION TITLE
Understand the behavior of infinity upgrade remediation

### DISCUSSION THREAD

**Discussion by mo-saeed** [fluxcd/flux2#2804] [General] [answered]
Hello,

I would like to achieve this block from flux v1 configuration

```
 rollback:
    enable: true
    retry: true
    maxRetries: 0
```
as per my understanding this can do it 

```
 upgrade:
   remediation:
     retries: -1
 install:
   remediation:
     retries: -1
```
but i am bit not sure how this works exactly, is it one of these scenarios

- first upgrade attempt failed
- rollback
- rollback success
- upgrade again
- fail
- rollback
- rollback success

or

- first upgrade attempt failed
- rollback
- rollback success
- done

what i want is sth like this, which was done in flux v1

- first upgrade attempt failed
- rollback
- rollback failed
- rollback again
- rollback success
- done

thanks alot in advance
