### DISCUSSION TITLE
why do i need to provision the private part of the ssh key to access a gitrepository

### DISCUSSION THREAD

**Discussion by wibed** [fluxcd/flux2#2805] [General] [answered]
example:

i bootstrap a local git repo and define a gitrepository as a resource 
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitsrv
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@192.168.179.6:2222/srv/bird.git
  ref:
    branch: master
  secretRef:
    name: ssh-credentials
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/src/base/gitsrv/gitsrv/
```

now to reconcile 
`flux reconcile source git gitsrv`

i have to provide a secret containing my private ssh key as a secret and expose it to the cluster.
even though i could encrypt it, i would like to know how on earth one could make a case for exposing a private ssh key
