### DISCUSSION TITLE
HelmRelease reconciler does not correct drift

### DISCUSSION THREAD

**Discussion by wibed** [fluxcd/flux2#2812] [Q&A] [answered]
i am looking for a way on how to "redeploy" and reinstate a predictable state.

using:
`flux reconcile helmrelease gitsrv`

does not recreate the deployment or service on the cluster as when i am 
changing the file itself for example.

i tried using upgrade, and install, but both did not reinstall a missing service/deployment once
manually deleted. `kubectl delete deployment,service default-gitsrv`

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitsrv
  namespace: flux-system
spec:
  targetNamespace: default
  upgrade:
    timeout: 60s
  chart:
    spec:
      chart: src/base/gitsrv/gitsrv
      version: '0.1.0'
      sourceRef:
        kind: GitRepository
        name: gitsrv
        namespace: flux-system
      valuesFiles:
        - values.yaml
  interval: 1m
```

it does work if i change the `HelmRelease` file itself
