### DISCUSSION TITLE
Commit Status Notification for `HelmRelease` with `GitRepository`

### DISCUSSION THREAD

**Discussion by dschniepp** [fluxcd/flux2#2819] [Q&A]
According to the [docs](https://fluxcd.io/docs/components/notification/provider/#git-commit-status) git commit status works only with `Kustomization`.  But is there a way to make it work for `HelmRelease` which use a `GitRepository` as in this case from my understanding due to `chart.spec.reconcileStrategy: Revision` the commit hash should also be part or did I miss something?

Thank you for your feedback.

**Comment by phillebaba** [comment]
What is your use case for using HelmReleases. The Kustomization will apply the HelmRelease so you can health check the HelmRelease.

If you are interested in the limitation it is that the event sent to notification controller needs to contain the revision.
https://github.com/fluxcd/notification-controller/blob/b8976736e7b5734d9841d61a9018a04fac032e26/internal/notifier/github.go#L97-L100

**Reply by dschniepp** [reply]
We have repositories for Helm charts which get deployed like in the code samples below based on `reconcileStrategy: Revision`. The idea was to use the **Git Status Commit** for marking the deployed revision in the chart repository. So everybody who checks the repo, can check the mark and knows this revision got deployed.

<details>
<title>Sample Files</title>

```YAML
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-app
  namespace: development
spec:
  releaseName: sample-app
  chart:
    spec:
      chart: ./charts/sample-app
      sourceRef:
        kind: GitRepository
        name: sample-app
      reconcileStrategy: Revision
  interval: 1m0s
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: sample-app
  namespace: development
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: repo-auth
  url: https://git.example.com/example-org/example-app
  recurseSubmodules: true
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - ../base/sample-app
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: git-commit-status
  namespace: development
spec:
  type: github
  address: https://git.example.com/example-org/example-app
  secretRef:
    name: github-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: git-commit-status-alert
  namespace: development
spec:
  providerRef:
    name: git-commit-status
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: example-app
```

</details>
