### DISCUSSION TITLE
Remediation for subcharts?

### DISCUSSION THREAD

**Discussion by ariep** [fluxcd/flux2#2821] [Q&A]
Hi, we run into a problem when trying to upgrade a helm chart through flux.

The upgrade is a tricky one. When done manually:
1. a `helm upgrade` fails consistently;
2. we do a `helm uninstall` of the release;
3. then we `helm install` the new version.

That works, but now we need to do that from flux (because we have a fleet of clusters to apply this upgrade to).

Because of the uninstall step, we have these specs on the HelmRelease, among others:
```
  install:
    timeout: 30m
    remediation:
      retries: 1
  upgrade:
    remediation:
      retries: 1
      strategy: uninstall
```
Now, the problem is that this doesn't work: it doesn't seem that flux does any uninstall after the upgrade first fails. Moreover, from the status it also seems that flux doesn't respect the `retries` value (note the `failures: 76`):
```
  status:
    conditions:
    - lastTransitionTime: "2022-06-07T15:12:47Z"
      message: upgrade retries exhausted
      reason: UpgradeFailed
      status: "False"
      type: Ready
    - lastTransitionTime: "2022-06-07T15:12:47Z"
      message: "Helm upgrade failed: execution error at (zulip/charts/postgresql/templates/secrets.yaml:17:24):
        \nPASSWORDS ERROR: The secret \"zulip-postgresql\" does not contain the key
        \"postgres-password\"\n\n\nLast Helm logs:\n\npreparing upgrade for zulip\nresetting
        values to the chart's original version"
      reason: UpgradeFailed
      status: "False"
      type: Released
    failures: 76
    helmChart: flux-system/stackspin-apps-zulip
    lastAppliedRevision: 0.2.1
    lastAttemptedRevision: 0.3.0
    lastAttemptedValuesChecksum: fd009ed5ae4ca44cc455bf22d9cae6301be4da61
    lastReleaseRevision: 1
    observedGeneration: 2
    upgradeFailures: 2
```

I have one theory about why the remediation doesn't kick in: as you can see from the error message, the failing upgrade is actually of the `postgresql` subchart (dependency chart) of the `zulip` chart. Perhaps the remediation settings are not propagated to the upgrade procedure of the subcharts?

Any help with this is appreciated!
