### DISCUSSION TITLE
Helm AWS ECR OCI repository

### DISCUSSION THREAD

**Discussion by ronaldkan** [fluxcd/flux2#2835] [Q&A] [answered]
Hey there, just curious if anyone have tried using flux with ECR's private OCI helm repository?

I'm trying to leverage on a private ECR helm repository with IAM role and i'm constantly facing with 
`chart pull error: chart pull error: failed to get chart version for remote reference: GET "https://<accountID>.dkr.ecr.<region>.amazonaws.com/v2/helm-template/helm-template/tags/list": credential required for basic auth`. Not sure if there's a way to turn off basic auth and use IAM role?

More Information:

HelmRepository object
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ecr-helm-template
  namespace: flux-system
spec:
  type: oci
  interval: 5m0s
  url: oci://<accountId>.dkr.ecr.<region>.amazonaws.com/helm-template
```

HelmRelease object
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test-app
  namespace: default
spec:
  chart:
    spec:
      chart: helm-template
      version: "0.0.1"
      sourceRef:
        kind: HelmRepository
        name: ecr-helm-template
        namespace: flux-system
```

**Comment by souleb** [comment]
The current implementation only supports credentials from secret as described in https://fluxcd.io/docs/guides/helmreleases/#helm-repository-authentication-with-credentials.

If you want to use IAM role, you would have to automate updating a secret with the generated token somehow I imagine.

**Reply by stefanprodan** [reply]
Like so https://fluxcd.io/docs/guides/cron-job-image-auth/#using-cronjob-to-sync-ecr-credentials-as-a-kubernetes-secret

**Reply by ronaldkan** [reply]
Awesome, thank you both for the prompt response!

**Comment by nalbury** [comment]
Hi sorry to tack onto an already answered discussion, but I'm currently trying to do this with a cronjob and while I can confirm the secret itself is being rotated and the new token is valid:
```
[root@jumbox ~]# kubectl get secret -n flux-system ecr-auth -o json |jq '.data.".dockerconfigjson"' -r |base64 --decode |jq '.auths."<redacted>.dkr.ecr.us-west-2.amazonaws.com/helm".password' -r |helm registry login -u AWS --password-stdin <redacted>.dkr.ecr.us-west-2.amazonaws.com/helm
Login Succeeded
[root@jumpbox ~]# helm show chart oci://<redacted>.dkr.ecr.us-west-2.amazonaws.com/helm/my-chart |grep apiVersion
apiVersion: v2
```

The source controller appears to use the old expired token until its restarted, at which point it reloads the new secret and can pull from ECR. Happy to open an issue somewhere but wasn't sure if this was expected given that the example provided I think creates a secret consumed by the image reflector vs the source controller here?
(edit: adding more output)
```
[root@jumpbox ~]# flux get source chart my-chart
NAME            REVISION	SUSPENDED	READY	MESSAGE
my-chart	0.2.0   	False    	False	chart pull error: chart pull error: failed to get chart version for remote reference: GET "https://<redacted>.dkr.ecr.us-west-2.amazonaws.com/v2/helm/my-chart/tags/list": unexpected status code 403: denied: Your authorization token has expired. Reauthenticate and try again.
[root@jumpbox ~]# kubectl delete pod -n flux-system source-controller-644c69fbf7-vpczd
pod "source-controller-644c69fbf7-vpczd" deleted
[root@jumpbox ~]# flux get source chart my-chart
NAME            REVISION	SUSPENDED	READY	MESSAGE
my-chart	0.2.0   	False    	True 	pulled 'my-chart' chart with version '0.2.0'
```

**Reply by stefanprodan** [reply]
Please open an issue in source-controller repo, it may be that we cache the secret.

**Reply by nalbury** [reply]
Will do, thanks!

**Comment by MatteoMori** [comment]
Hello @stefanprodan,

I am sorry but I was wondering if the above "cache" issue has been resolved? 

Will it work as expected now?

**Reply by stefanprodan** [reply]
Yes please upgrade to Flux 0.32

**Comment by MartinEmrich** [comment]
Hi!

Should this work in Flux 0.35 now, without any workarounds (credentials/secrets)? I get the same error message (`credential required for basic auth`), yet the Kubernetes nodes (as always) have an appropriate AWS IAM Role to access the AWS ACR repository.

Possibly history repeats: https://github.com/fluxcd/image-reflector-controller/pull/174 ff.

So I did some experiments:

As I understand, the source-controller is responsible for fetching OCI repository artifacts.
Also, as the error message looks identical to using the `helm pull`, I assumed it uses the same libraries under the hood. "helm" respects the docker CLI configuration files.

So I hacked together a modified image, including the AWS ECR credential helper (https://github.com/awslabs/amazon-ecr-credential-helper):

````
FROM ghcr.io/fluxcd/source-controller:v0.30.0
USER root
RUN mkdir /.docker
COPY config.json /.docker/config.json
RUN wget https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.6.0/linux-amd64/docker-credential-ecr-login -O/usr/bin/docker-credential-ecr-login
RUN chmod +x /usr/bin/docker-credential-ecr-login
USER 65534
````

With that image, it works for me without juggling any credentials or secrets.

So the solution would be to include the docker credential helper for AWS ECR (and possibly equvalents for GCE, Azure etc.), providing seamless integration.

my .docker/config.json:

````
{
  "credsStore": "ecr-login"
}
````
would most certainly "surprise" users in heterogeneous environments, and wildcard support for registries is not (yet?) available: https://github.com/docker/cli/issues/2928

Any chance to have at least the binary(ies) included in a future release? The docker client configuration file might be added at install time with a `flux install --enable-ecr-whatever` flag via a configMap?

**Reply by stefanprodan** [reply]
You need to set the provider to aws in the HelmRepository, see https://fluxcd.io/flux/components/source/helmrepositories/#aws

**Reply by MartinEmrich** [reply]
@stefanprodan thanks! That shall be my Facepalm Moment of today... :D

**Comment by stefanprodan** [comment, marked as answer]
Starting with v0.35.0, Flux has native support to authenticate automatically using the EKS worker node IAM role or IAM Role for Service Accounts (IRSA). Docs here: https://fluxcd.io/flux/components/source/helmrepositories/#aws

**Reply by fw-harish** [reply]
@stefanprodan I'm using the provider="aws". you can find my yaml file below. 

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: farmerswife
  namespace: default
spec:
  type: "oci"
  interval: 5m0s
  provider: "aws"
  url: oci:/<account id>/.dkr.ecr.eu-west-1.amazonaws.com/charts

```
I'm getting the same error.
failed to login to registry 'oci:/<account id>/.dkr.ecr.eu-west-1.amazonaws.com/charts': login attempt to https://<account id>.dkr.ecr.eu-west-1.amazonaws.com/v2/ failed with status: 400 Bad Request

I even tried to manually authenticate
`aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin <account id>.dkr.ecr.eu-west-1.amazonaws.com`
with response __Login Succeeded__

any suggestions will be really appreciated.
Thanks in advance

**Reply by stefanprodan** [reply]
Have you setup IRSA for the source-controller SA? Make sure to restart the pod for kubelet to mount the certs.

**Reply by fw-harish** [reply]
Here is my Kustomization yaml file from flux-system directory. 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: source-controller
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::<account id>:role/cloud/cloud-workernodes-eu-central-1
    target:
      kind: ServiceAccount
      name: source-controller
```

Here is my new error I got after restarting the pod. 

__failed to get credential from aws: operation error ECR: GetAuthorizationToken, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, https response error StatusCode: 403, RequestID: e8f6120e-f5c6-4640-a8a9-78ffff4a3dbb, api error AccessDenied: Not authorized toperform sts:AssumeRoleWithWebIdentity__

By the way, I really appreciate your flash response.

**Reply by stefanprodan** [reply]
The patch looks good, my guess is the IAM role does not have `arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly`

**Reply by fw-harish** [reply]
Here is the role and the policies attached to it. 
<img width="1275" alt="image" src="https://github.com/fluxcd/flux2/assets/141128004/5f787b8a-b0ea-4fdc-9cb1-231c5947c5ae">

**Reply by stefanprodan** [reply]
OK is this Role assigned to the source-controller Service Account?

**Reply by fw-harish** [reply]
Please find the service account details...
 
__harish@Harish-MacBook-Pro%__ kubectl get serviceaccount source-controller -o=jsonpath='{.metadata.annotations.eks\.amazonaws\.com/role-arn}' 
arn:aws:iam::054331359164:role/cloud/cloud-workernodes-eu-central-1%

**Reply by stefanprodan** [reply]
Hmm why is there a `%` at the end?

**Reply by fw-harish** [reply]
I've no Idea but the actual role arn inside the SA looks good. 

<img width="1016" alt="image" src="https://github.com/fluxcd/flux2/assets/141128004/f37d3459-e63e-431e-909d-f93e6b3f10ff">

FYI: I've tried to replace the __cloud-workernodes-eu-central-1__ with __worker_node_group1-eks-node-group-20230920075133937100000010__. All the permissions attached to both roles were exactly same.

**Reply by stefanprodan** [reply]
Does the AssumeRoleWithWebIdentity have the source-controller service account specified? See the AWS docs https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html

**Reply by fw-harish** [reply]
Thanks a lot @stefanprodan. Actually that's the last missing piece of my puzzle.

**Comment by antoineDievDecath** [comment]
Hi 

I followed steps to use IRSA to pull helm charts from ECR. 
Source-controller log is: 
failed to get credential from aws: could not validate OCI provider aws with URL oci://[my-ecr].dkr.ecr.eu-west-1.amazonaws.com

Flux installed with **terraform 0.0.19**
**EKS 1.23**
**Source-controller v0.30.0**
AWS_ROLE_ARN & AWS_STS_REGIONAL_ENDPOINTS ENV vars are presents

My HelmRepository:
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: discovery
  namespace: kube-system
spec:
  interval: 5m0s
  url: oci://<my-ecr>.dkr.ecr.eu-west-1.amazonaws.com
  type: oci  
  provider: aws
  ```

What am I missing ?

**Reply by MartinEmrich** [reply]
maybe you're missing the repository name in the URL? Should be like `url: oci://<my-account-id>.dkr.ecr.eu-west-1.amazonaws.com/<my-repository>`

**Reply by antoineDievDecath** [reply]
That was my miss thx !

**Reply by antoineDievDecath** [reply]
There is something I don't get. 
My helm-repository is ready when I set `url: oci://<my-account-id>.dkr.ecr.eu-west-1.amazonaws.com/<my-repository>`
But when I reference that repository in an HelmRelease with `spec.chart.spec.chart: <my-repository>` the source-controller try to fetch `oci://<my-account-id>.dkr.ecr.eu-west-1.amazonaws.com/<my-repository>/<my-repository>`  and get a  status code 404: name unknown. 

My HelmRelease looks like that:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: discovery
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: discovery
      version: "22.06.197"
      sourceRef:
        kind: HelmRepository
        name: discovery
        namespace: kube-system
      interval: 1m
  values:
    #my_values
```

And as I understand the aws ecr documentation isn't possible to create "sub repository"
