### DISCUSSION TITLE
HelmRelease and gitlab repo

### DISCUSSION THREAD

**Discussion by slarktits** [fluxcd/flux2#2850] [Q&A] [answered]
Hi all.
recently I did migration from fluxv1 to v2 on my sbx clusters.
For deploy specific apps thru old way I used:
HelmRelease  with old api: helm.fluxcd.io/v1

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: app-sbx
  namespace: app-sbx
spec:
  releaseName: app-sbx
  chart:
    git: git@gitlab.com:mygroup/appname.git
    ref: master
    path: charts/appname
  values:
    image:
      repository: 111111111111.dkr.ecr.us-east-1.amazonaws.com/app
      pullPolicy: IfNotPresent
     ....
     ....
```
this definition was enough for deploy my app from gitlab repo with set of Helm files + template.
like:
Chart.yaml
values.yaml
...
I tried to deploy same app thru new api with new flux2:

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: app-sbx
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: gitlab-repos
  timeout: 60s
  url: ssh://git@gitlab.com/mygroup/appname.git
```
Repo connected successfully.

I tried to use different variations of HelmRelease. One of this >
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-sbx
  namespace: app-sbx
spec:
  interval: 5m
  chart:
    spec:
      chart: app-sbx
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: app-sbx
        namespace: flux-system
      interval: 1m
   values:
     ....
     ....
```
I think something wrong with my new HelmRelease manifest.
I tried to use different params but this is not works.
Also I didn't find correct manual or definition for GitLab repos + HealReleases
Will be very appreciated for your help.
Thank you.
