### DISCUSSION TITLE
MariaDB helmrelease exhausts retries

### DISCUSSION THREAD

**Discussion by lenaxia** [fluxcd/flux2#2858] [Q&A] [answered]
Hey folks, I'm really struggling here. I previously had Bitnami MariaDB working fine, but at some point it somehow corrupted and wasn't self recovering. I decided to drop it from replication mode to standalone mode, but it just won't deploy anymore. I have other helmreleases working fine so I'm not sure what's going on here. 

config-pvc.yaml
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-primary-pvc
  namespace: databases
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
```

helm-release.yaml
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: databases
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      registry: docker.io
      repository: bitnami/mariadb
      tag: 10.5.15-debian-10-r11
      pullPolicy: IfNotPresent
      pullSecrets: []
      debug: false
    architecture: standalone
    auth:
      rootPassword: "${SECRET_MARIADB_PASSWORD}"
      #replicationUser: replicator
      #replicationPassword: "${SECRET_MARIADB_REPLICATION_PASSWORD}"


    primary:
      persistence:
        enabled: true
        existingClaim: "mariadb-primary-pvc"
        storageClass: "longhorn"
      service:
        type: LoadBalancer
        ports:
          mysql: 3306
        #loadBalancerIP: "192.168.5.5"
        externalTrafficPolicy: Cluster
        ## @param primary.service.loadBalancerSourceRanges Address that are allowed when MariaDB Primary service is LoadBalancer
        ## https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
        ## E.g.
        ## loadBalancerSourceRanges:
        ##   - 10.10.10.0/24
        ##
        loadBalancerSourceRanges: []
        annotations:
          metallb.universe.tf/address-pool: dev-infra
        ## @param primary.service.sessionAffinity Session Affinity for Kubernetes service, can be "None" or "ClientIP"
        ## If "ClientIP", consecutive client requests will be directed to the same Pod
        ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
        ##
        sessionAffinity: ClientIP
        sessionAffinityConfig:
          clientIP:
            timeoutSeconds: 300

    secondary:
      replicaCount: 0
#      persistence:
#        enabled: true
#        existingClaim: "mariadb-secondary-pvc"
#        storageClass: "longhorn"
#      service:
#        type: LoadBalancer
#        ports:
#          mysql: 3306
#        #loadBalancerIP: "192.168.5.6"
#        externalTrafficPolicy: Cluster
#        ## @param primary.service.loadBalancerSourceRanges Address that are allowed when MariaDB Primary service is LoadBalancer
#        ## https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
#        ## E.g.
#        ## loadBalancerSourceRanges:
#        ##   - 10.10.10.0/24
#        ##
#        loadBalancerSourceRanges: []
#        annotations:
#          metallb.universe.tf/address-pool: dev-infra
#        ## @param primary.service.sessionAffinity Session Affinity for Kubernetes service, can be "None" or "ClientIP"
#        ## If "ClientIP", consecutive client requests will be directed to the same Pod
#        ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
#        ##
#        sessionAffinity: ClientIP
#        sessionAffinityConfig:
#          clientIP:
#            timeoutSeconds: 300
```

mariadb-values.yaml (patched during kustomize)
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: databases
spec:
  values:
    primary:
      service:
        loadBalancerIP: "${SVC_MARIADB_PRIMARY_ADDR}"
        annotations:
          metallb.universe.tf/address-pool: dev-infra
```

core.yaml
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
    - name: crds
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./components/core/dev
  prune: true
  wait: true
  timeout: 20m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
```

`ka mariadb`

```
NAMESPACE   NAME            READY   STATUS              RESTARTS   AGE
databases   pod/mariadb-0   0/1     ContainerCreating   0          20s

NAMESPACE   NAME              TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
databases   service/mariadb   LoadBalancer   10.43.67.123   192.168.5.5   3306:32194/TCP   59m

NAMESPACE   NAME                       READY   AGE
databases   statefulset.apps/mariadb   0/1     59m
```

`kcd pod mariadb -n databases`

```
Name:           mariadb-0
Namespace:      databases
Priority:       0
Node:           k3-agent-02/192.168.2.62
Start Time:     Tue, 21 Jun 2022 18:53:57 +0000
Labels:         app.kubernetes.io/component=primary
                app.kubernetes.io/instance=mariadb
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=mariadb
                controller-revision-hash=mariadb-bf89776bb
                helm.sh/chart=mariadb-11.0.13
                statefulset.kubernetes.io/pod-name=mariadb-0
Annotations:    checksum/configuration: 529a4ada4f153047a52b13f51e8c0fecc2df9c48d3ba361aa81a121bde731418
Status:         Pending
IP:
IPs:            <none>
Controlled By:  StatefulSet/mariadb
Containers:
  mariadb:
    Container ID:
    Image:          docker.io/bitnami/mariadb:10.5.15-debian-10-r11
    Image ID:
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Liveness:       exec [/bin/bash -ec password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
    password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
fi
mysqladmin status -uroot -p"${password_aux}"
] delay=120s timeout=1s period=10s #success=1 #failure=3
    Readiness:  exec [/bin/bash -ec password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
    password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
fi
mysqladmin status -uroot -p"${password_aux}"
] delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment:
      BITNAMI_DEBUG:          false
      MARIADB_ROOT_PASSWORD:  <set to the key 'mariadb-root-password' in secret 'mariadb'>  Optional: false
      MARIADB_DATABASE:       my_database
    Mounts:
      /bitnami/mariadb from data (rw)
      /opt/bitnami/mariadb/conf/my.cnf from config (rw,path="my.cnf")
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      mariadb
    Optional:  false
  data:
    Type:        PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:   mariadb-primary-pvc
    ReadOnly:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason              Age   From                     Message
  ----     ------              ----  ----                     -------
  Normal   Scheduled           10s   default-scheduler        Successfully assigned databases/mariadb-0 to k3-agent-02
  Warning  FailedMount         9s    kubelet                  MountVolume.SetUp failed for volume "config" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedAttachVolume  7s    attachdetach-controller  AttachVolume.Attach failed for volume "pvc-26ac7e71-323d-4d89-af5c-60619de6f4b8" : rpc error: code = DeadlineExceeded desc = volume pvc-26ac7e71-323d-4d89-af5c-60619de6f4b8 failed to attach to node k3-agent-02
```

`flux get helmrelease`

```
Every 2.0s: flux get hr --all-namespaces                                                                                                                                                                                                   terraform: Tue Jun 21 18:55:25 2022

NAMESPACE       NAME            REVISION        SUSPENDED       READY   MESSAGE
networking      metallb         0.12.1          False           True    Release reconciliation succeeded
cert-manager    cert-manager    v1.7.1          False           True    Release reconciliation succeeded
networking      traefik         10.15.0         False           True    Release reconciliation succeeded
nginx           nginx           9.1.11          False           True    Release reconciliation succeeded
default         echo-server     0.3.1           False           True    Release reconciliation succeeded
media           nzbget          12.3.2          False           True    Release reconciliation succeeded
media           sonarr          16.2.3          False           True    Release reconciliation succeeded
media           radarr          16.2.3          False           True    Release reconciliation succeeded
podinfo         podinfo         6.1.6           False           True    Release reconciliation succeeded
iot             mosquitto       4.4.0           False           True    Release reconciliation succeeded
media           bookstack       4.2.2           False           True    Release reconciliation succeeded
longhorn-system longhorn        1.3.0           False           True    Release reconciliation succeeded
databases       mariadb                         False           False   Helm install failed: timed out waiting for the condition
```
