### DISCUSSION TITLE
Pulling secret from AWS Secrets Manager

### DISCUSSION THREAD

**Discussion by jerzykiller** [fluxcd/flux2#2865] [Q&A]
Hi,

I have a flux running on eks cluster and I'm trying to configure `kind: GitRepository` to connect to github using PAT stored in AWS Secrets Manager. Unfortunately I'm getting `{"level":"error","ts":"2022-06-23T14:17:38.855Z","logger":"controller.imageupdateautomation","msg":"Reconciler error","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","error":"unable to fetch-connect to remote 'https://github.com/<repo>.git': unhandled HTTP error 401 Authorization Required"}` in logs of `image-automation-controller`.

Secret 
```
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: flux-git-auth
  namespace: flux-system
spec:
  stringDataFrom:
    secretsManagerSecretRef: 
      secretId: github-pat
```
GitRepository object
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: <repo>
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  secretRef:
    name: flux-git-auth
  url: https://github.com/<repo>.git
```

Have I made a mistake with referencing this secret? It works fine with other resources, so EKS is able to pull it.
