### DISCUSSION TITLE
Kustomization "resource.yaml must be a directory so that it can used as a build root"

### DISCUSSION THREAD

**Discussion by netthier** [fluxcd/flux2#2876] [Q&A] [answered]
My repo is structured like this:
```
apps/
    base/
        my_app/
            a-secret.yaml
            gitrepository.yaml
            helmrelease.yaml
    dev/
        my_app/
            master.yaml
cluster/
```
master.yaml contains
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: my_app-master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my_app
  namespace: my_app-master
spec:
  targetNamespace: my_app-master
  path: "./apps/base/my_app"
  prune: true
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
    # etc.
```
and `cluster/` contains a Kustomization pointing at `apps/dev`.

However, when reconciling the `my_app` Kustomization, I get this error:
```
✗ Kustomization reconciliation failed: kustomize build failed: accumulating resources: accumulation err='merging resources from 'a-secret.yaml': may not add resource with an already registered id: SealedSecret.v1alpha1.bitnami.com/a-secret.[noNs]': '/tmp/kustomization-2485085500/apps/base/my_app/a-secret.yaml' must be a directory so that it can used as a build root
```

What do I need to change to fix this? I want to have multiple kustomizations in `apps/dev/my_app` to deploy multiple versions of my_app with different patches.
(Also, it there a word missing in "so that it can used as a build root"?)
