### DISCUSSION TITLE
Kustomize patches not being applied?

### DISCUSSION THREAD

**Discussion by netthier** [fluxcd/flux2#2878] [Q&A] [answered]
I have this Kustomization:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my_app
  namespace: my_app-master
spec:
  targetNamespace: my_app-master
  path: "./apps/base/my_app"
  prune: true
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
  - patch: |-
      apiVersion: bitnami.com/v1alpha1
      kind: SealedSecret
      metadata:
        name: foobar
      spec:
        template:
          metadata:
            namespace: my_app-master
    target:
      kind: SealedSecret
      namespace: my_app-master
  - patch: |-
      apiVersion: source.toolkit.fluxcd.io/v1beta1
      kind: GitRepository
      metadata:
        name: foobar
      spec:
        ref:
          branch: master
    target:
      kind: GitRepository
      name: my_app
      namespace: my_app-master
```
with a SealedSecret looking like this:
```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: my_app-secret
spec:
  encryptedData:
    # etc.
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: my_app-secret
      namespace: foobar.invalid
```
and the GitRepository like this:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my_app
spec:
  interval: 1m0s
  ref:
    branch: foobar.invalid
  secretRef:
    name: azure-git-secret
  url: www.example.com
  gitImplementation: libgit2
```
The patches should patch all sealed secrets in the namespace so that the namespace in the template is also correct, and set the branch of the git repo.
The `foobar.invalid` values are intended as placeholders to be patched.
The `metadata.name` in the patches, `foobar`, isn't used anywhere else, but from my understanding it should be ignored?
