### DISCUSSION TITLE
is it possible to partial update manifest on a image update?

### DISCUSSION THREAD

**Discussion by jack-evans** [fluxcd/flux2#2880] [Q&A] [answered]
I am using the [olm helm chart](https://github.com/operator-framework/operator-lifecycle-manager/tree/master/deploy/chart) to deploy onto out cluster. As we are in an air gapped environment we are pulling, re-tagging the images and then use flux to update the manifests however one of the values.yamls properties is not just an image i.e.

```yaml
catalog:
  replicaCount: 1
  commandArgs: --configmapServerImage=quay.io/operator-framework/configmap-operator-registry:latest
```

If I try to use the image automation controller with our own tagged images, the `--configmapServerImage=`  is removed... Is there a way to do this in flux2 today without removing the `--configmapServerImage=` or is the only way for me to do a bit of editing of the helm chart?

**Comment by stefanprodan** [comment, marked as answer]
For Flux to update the image, that Helm chart should expose the image in dedicated field, like Helm recommends, e.g.

```yaml
configmapServer:
  image: quay.io/operator-framework/configmap-operator-registry
  tag: latest
```
