### DISCUSSION TITLE
How to Garbage Collect Child Flux Kustomizations?

### DISCUSSION THREAD

**Discussion by deB4SH** [fluxcd/flux2#2882] [Q&A] [answered]
Hi all,
I'm currently experiencing an issue with a not working garbage collection on flux kustomizations. 

To describe our current setup:
We're providing a "hook" to deploy custom workloads into a cluster via a prepared flux kustomization which points towards a kustomization where users add their own flux kustomizations. 

To start with: the initial flux kustomization.
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: custom
  namespace: flux-system
spec:
  timeout: 5m
  dependsOn:
    - name: service-catalog
      namespace: flux-system
  interval: 10m0s
  retryInterval: 15s
  path: ./clusters.custom/custom-workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-clusters
  validation: client
```

Which picks up the following kustomization which provides all flux kustomizations that should be deployed afterwards.
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: custom-catalog

resources:
  - nginx/release-nginx.yaml
```

Last but not least the flux kustomization for the nginx release.
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: release-nginx
  namespace: custom-catalog
spec:
  interval: 30m0s
  path: ./clusters.custom/custom-workloads/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-clusters
    namespace: flux-system
  validation: client
```
The nginx folder provides its own kustomization with all required artifacts described in it. (Deployment, Service, Secrets, &&).
When deleting those manifests the garbage collection removes them accordingly. 

When removing the nginx flux-kustomization from git and the reference in the kustomization the installed flux kustomization isn't removed from the cluster and flux still references it. It seems that the garbage collection isn't picking up this change.

The occuring issue is a no such file or directory problem inside the cluster.
`kustomization path not found: stat /tmp/kustomization-1480258660/clusters.custom/custom-workloads/nginx: no such file or directory`

Am I missing something to prune flux kustomizations or is this even an wanted feature to protect this references against unwanted changes inside git?
