### DISCUSSION TITLE
Image policy tags move after SOPS encrypts file to line above

### DISCUSSION THREAD

**Discussion by hrvatskibogmars** [fluxcd/flux2#2886] [Q&A] [answered]
```
image:
  # {"$imagepolicy": "flux-system:service-dev-policy:name"}
  repository: 1231231.dkr.ecr.cn-northwest-1.amazonaws.com.cn/service
  # {"$imagepolicy": "flux-system:service-dev-policy:tag"}
  tag: dev-c73e5f97-1648811781
  pullPolicy: IfNotPresent
```

Is anyone having a problem with the formatting of the YAML file? Seems like each time a new image is pushed and sops encrypts the file it moves the image policy tags line above repository & tag instead of inline and  this breaks auto-deployment.

It should stay like this
```
image:
  repository: 1231231.dkr.ecr.cn-northwest-1.amazonaws.com.cn/service # {"$imagepolicy": "flux-system:service-dev-policy:name"}
  tag: dev-c73e5f97-1648811781   # {"$imagepolicy": "flux-system:service-dev-policy:tag"}
  pullPolicy: IfNotPresent
```
