### DISCUSSION TITLE
Flux tries to decrypt unencrypted keys with SOPS when patching with kustomize?

### DISCUSSION THREAD

**Discussion by theadzik** [fluxcd/flux2#2887] [Q&A] [answered]
I'm not sure if this is flux or sops problem so I'm posting here to maybe get some pointers.

## Problem description 
I have a helm deployment and a patch file to it. Installation fails and when I do `kubectl get kustomizations.kustomize.toolkit.fluxcd.io -n flux-system monitoring` I see the status: 

>decryption failed for 'monitoring': failed to decrypt and format 'monitoring/monitoring' HelmRelease data: error decrypting sops tree: Error walking tree: Could not decrypt value: Input string http://mimir-distributed-querier.monitoring:8080/prometheus does not match sops' data format

## Configuration 

I encrypt my files with `.sops.yaml`:

```yaml
creation_rules:
  - path_regex: .*alert-manager-patch-secret\.yaml
    encrypted_regex: ^(url)$
    azure_keyvault: https://mykeyvault.vault.azure.net/keys/sops/1234
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData|primaryKey|client_secret|secureJsonData|.*username|.*password)$
    azure_keyvault: https://mykeyvault.vault.azure.net/keys/sops/1234
```

In `prometheus-stack.yaml` below:
`url` is not encrypted ✅
`secureJsonData` is encrypted ✅
`encrypted_regex` matches file name ✅

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: monitoring
spec:
    interval: 5m
    chart:
        spec:
            chart: kube-prometheus-stack
            version: 35.0.0
            sourceRef:
                kind: HelmRepository
                name: monitoring
            interval: 1h
    values:
        grafana:
            additionalDataSources:
                - name: prometheus
                  type: prometheus
                  url: http://mimir-distributed-querier.monitoring:8080/prometheus
                  secureJsonData:
                    httpHeaderValue1: ENC[ENCRYPTED DATA HERE]

...some irrelevant stuff...

sops:
...some irrelevant stuff...
    encrypted_regex: ^(data|stringData|primaryKey|client_secret|secureJsonData|.*username|.*password)$
    version: 3.7.1
```

Then I have a patch for the HelmRelease `alert-manager-patch-secret.yaml` where
`url` is encrypted ✅
`encrypted_regex` matches file name ✅

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: monitoring
spec:
    values:
        alertmanager:
            config:
                receivers:
                    - name: critical-alerts
                      webhook_configs:
                        - url: ENC[ENCRYPTED URL]
sops:
...some irrelevant stuff...
    encrypted_regex: ^(url)$
    version: 3.7.3
```

My main kuztomize file:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - prometheus-stack.yaml
  - more-irrelevant-stuff-here.yaml
```

and a patch:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base

patchesStrategicMerge:
  - alert-manager-patch-secret.yaml
  - some-other-patches.yaml
```

## Question

Is the problem caused by patching files encrypted with different patterns? Can I make flux aware of patterns it should use while patching? I've had some problems with patching encrypted files before, is that even recommended?

I can just encrypt all `url` keys in both files but I would like to avoid it.
