### DISCUSSION TITLE
IRSA for AWS Code Commit gitrepository source

### DISCUSSION THREAD

**Discussion by savagete2860** [fluxcd/flux2#2907] [Q&A]
I am using an AWS code commit source and the repo username/password is set as a secretRef on the gitrepository manifest. These credentials are IAM user credentials which I would like to get rid of (the IAM user in general, not just the password). Is it possible to use an IRSA role for authentication into code commit rather than a user/pass via IAM user?

ex instead of this:

```
apiVersion: v1
items:
- apiVersion: source.toolkit.fluxcd.io/v1beta2
  ...
  spec:
    gitImplementation: libgit2
    interval: 1m0s
    ref:
      branch: master
    secretRef:
      name: flux-system
    url: <CODE-COMMIT-URL>    
```

It would drop the secret ref and add the role annotation and look like:
```
apiVersion: v1
metadata:
  annotations:
    eks.amazonaws.com/role-arn: <IAM-ROLE-ARN>
items:
- apiVersion: source.toolkit.fluxcd.io/v1beta2
  spec:
    gitImplementation: libgit2
    interval: 1m0s
    ref:
      branch: master
    url: <CODE-COMMIT-URL>    
```
