### DISCUSSION TITLE
flux redeploying same container images over and over?

### DISCUSSION THREAD

**Discussion by pdeva** [fluxcd/flux2#2935] [Q&A] [answered]
see below:

redeploying images..

<img width="717" alt="Screen Shot 2022-07-26 at 7 10 34 PM" src="https://user-images.githubusercontent.com/3190176/181145430-6da48228-b482-46ed-8f33-2e179edfbb4e.png">

and deploying them yet again...

<img width="704" alt="Screen Shot 2022-07-26 at 7 10 45 PM" src="https://user-images.githubusercontent.com/3190176/181145441-449a08d8-792e-4b9f-83d3-e7c60687a239.png">

this is the `HelmRelease` definition i am using:

```yml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: datadog
  namespace: flux-system
spec:
  interval: 240m
  url: https://helm.datadoghq.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dd
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: "datadog"
      interval: 1m
      version: "2.x.x"
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: flux-system
```

Am i doing something wrong? Or is this a bug in FluxCD?
