### DISCUSSION TITLE
HelmRelease is downgrading chart versions....

### DISCUSSION THREAD

**Discussion by pdeva** [fluxcd/flux2#2939] [Q&A]
See screenshots from our slack notifications channel below:

<img width="820" alt="Screen Shot 2022-07-28 at 7 32 24 AM" src="https://user-images.githubusercontent.com/3190176/181564959-b8c10646-9d34-4039-a938-ba20f523c0a1.png">

and:

<img width="1013" alt="Screen Shot 2022-07-28 at 7 34 21 AM" src="https://user-images.githubusercontent.com/3190176/181565010-80f12c3d-483d-44f2-bbc4-0ac6d8fbab1d.png">

source:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1m0s
  values:
    adminUser:
      create: true
      username: adm
      passwordHash: $2a$10$tlSNjulbxwlEfzwBoviKB.K2FwdXTxyGvpulDDC85eLf5A6XfX2Vq
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://helm.gitops.weave.works
```

`kubectl describe helmrelease ww-gitops -n flux-system` :

```
Name:         ww-gitops
Namespace:    flux-system
Labels:       kustomize.toolkit.fluxcd.io/name=flux-system
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  <none>
API Version:  helm.toolkit.fluxcd.io/v2beta1
Kind:         HelmRelease
Metadata:
  Creation Timestamp:  2022-07-25T02:15:05Z
  Finalizers:
    finalizers.fluxcd.io
  Generation:  1
  Managed Fields:
    API Version:  helm.toolkit.fluxcd.io/v2beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:kustomize.toolkit.fluxcd.io/name:
          f:kustomize.toolkit.fluxcd.io/namespace:
      f:spec:
        f:chart:
          f:spec:
            f:chart:
            f:sourceRef:
              f:kind:
              f:name:
        f:interval:
        f:values:
    Manager:      kustomize-controller
    Operation:    Apply
    Time:         2022-07-25T02:15:05Z
    API Version:  helm.toolkit.fluxcd.io/v2beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizers.fluxcd.io":
      f:status:
        f:conditions:
        f:helmChart:
        f:lastAppliedRevision:
        f:lastAttemptedRevision:
        f:lastAttemptedValuesChecksum:
        f:lastReleaseRevision:
        f:observedGeneration:
    Manager:         helm-controller
    Operation:       Update
    Time:            2022-07-25T02:15:19Z
  Resource Version:  248038788
  UID:               3f57628f-f520-48d7-9a08-0f76c388dc1d
Spec:
  Chart:
    Spec:
      Chart:               weave-gitops
      Reconcile Strategy:  ChartVersion
      Source Ref:
        Kind:   HelmRepository
        Name:   ww-gitops
      Version:  *
  Interval:     1m0s
  Values:
    Admin User:
      Create:         true
      Password Hash:  $2a$10$tlSNjulbxwlEfzwBoviKB.K2FwdXTxyGvpulDDC85eLf5A6XfX2Vq
      Username:       pdeva
Status:
  Conditions:
    Last Transition Time:          2022-07-28T13:59:31Z
    Message:                       Release reconciliation succeeded
    Reason:                        ReconciliationSucceeded
    Status:                        True
    Type:                          Ready
    Last Transition Time:          2022-07-28T13:59:31Z
    Message:                       Helm upgrade succeeded
    Reason:                        UpgradeSucceeded
    Status:                        True
    Type:                          Released
  Helm Chart:                      flux-system/flux-system-ww-gitops
  Last Applied Revision:           2.2.5
  Last Attempted Revision:         2.2.5
  Last Attempted Values Checksum:  60288ea44be05c1548eb6e0481bb3b40134c464f
  Last Release Revision:           52
  Observed Generation:             1
Events:
  Type     Reason  Age                   From             Message
  ----     ------  ----                  ----             -------
  Warning  error   59m                   helm-controller  reconciliation failed: Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "ww-gitops": the object has been modified; please apply your changes to the latest version and try again
  Normal   info    47m (x51 over 2d21h)  helm-controller  Helm upgrade has started
  Normal   info    47m (x51 over 2d21h)  helm-controller  Helm upgrade succeeded
```

`helm ls -n flux-system`  : 

```
NAME     	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART             	APP VERSION
ww-gitops	flux-system	52      	2022-07-28 13:59:29.906057532 +0000 UTC	deployed	weave-gitops-2.2.5	v0.9.1 
```
