### DISCUSSION TITLE
Relation between prometheus alert and reconcilation interval

### DISCUSSION THREAD

**Discussion by matejhasul** [fluxcd/flux2#2942] [Q&A] [answered]
Hi there,
I've question regarding relation between kustomization reconcilation interval and prometheus alert query `for` duration.

We are using prometheus alert query as described in the doc - https://fluxcd.io/docs/guides/monitoring/#metrics, but we are using `for: 15m` instead of `10m`. The alert looks like this:
```
groups:
  - name: Flux
    rules:
      - alert: ReconciliationFailure
        expr: max(gotk_reconcile_condition{status="False",type="Ready"}) by (exported_namespace, name, kind) + on(exported_namespace, name, kind) (max(gotk_reconcile_condition{status="Deleted"}) by (exported_namespace, name, kind)) * 2 == 1
        for: 15m
        labels:
          severity: page
        annotations:
          summary: '{{ $labels.kind }} {{ $labels.exported_namespace }}/{{ $labels.name }} reconciliation has been failing for more than ten minutes.'
```
We have reconciliation interval for kustomization set to 10min. Kustomization can be failing for hours but the alert is not fired. Alerting condition must hold for 15 minutes (`for: 15m` in the alert definition`) but kustomization is reconciled every 10 minutes (`interval` in kustomization definition) which result into gaps (as can be seen on the picture, gap is every 10 minutes).
![Screenshot from 2022-07-29 15-07-42](https://user-images.githubusercontent.com/8996498/181769492-47bf128d-ce95-46e9-bfa8-985f002b9f37.png)
These gaps breaks the alerting condition and alert is never fired.

My question is if this is known limitation (alert `for` duration < kustomization `interval` duration) or bug?
