### DISCUSSION TITLE
HelmRelease with chart in a GitRepository behaviour

### DISCUSSION THREAD

**Discussion by masterkain** [fluxcd/flux2#2953] [Q&A] [answered]
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
spec:
  releaseName: code-server
  chart:
    spec:
      chart: ./ci/helm-chart
      sourceRef:
        kind: GitRepository
        name: code-server
        namespace: flux-system
  interval: 10m0s
  ...
```

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: code-server
spec:
  interval: 15m0s
  url: https://github.com/coder/code-server
  ref:
    branch: main
```

applying this helm release works as expected -- in this case when does an upgrade reconciliation happens? when new commits are added to the GitRepository? this does not seems to be the case.

I'm not sure how to automatically trigger reconciliation with the newest commits and make the HelmRelease follow the `main` source branch.
Does an upgrade happen when the Chart.yaml gets committed with a version bump?
