### DISCUSSION TITLE
Kustomization variable substitution type issue

### DISCUSSION THREAD

**Discussion by netthier** [fluxcd/flux2#2957] [Q&A] [answered]
I'm attempting to use the variable substitution feature in Flux's Kustomizations, but I'm getting weird issues with ambiguous strings (e.g. "20220802.5"):
```
Kustomization/my-namespace/my-ks dry-run failed, error: failed to create typed patch object (my-namespace/my-ks dry-run; kustomize.toolkit.fluxcd.io/v1beta2, Kind=Kustomization): .spec.postBuild.substitute.dd_tag: expected string, got &value.valueUnstructured{Value:2.02208025e+07}
```
I quoted each occurrence of `${dd_tag}`, but that doesnt seem to help.

EDIT:
For more context, this error is being thrown by this Kustomization:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: other-namespace
  namespace: other-ks
spec:
  path: "./apps/some/path/dev"
  targetNamespace: my-namespace
  prune: true
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      namespace: "my-namespace"
      dd_commit: "bba2c2d53adeed14b838efd256c55c47490bb10e"
      dd_tag: "20220802.5"
```
where `./apps/some/path/dev` contains the Kustomization `my-ks`, which looks more or less like this:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-ks
spec:
  targetNamespace: ${namespace}
  path: "./apps/some/path/base"
  prune: true
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      namespace: "${namespace}"
      dd_commit: "${dd_commit:=main}"
      dd_tag: "${dd_tag:=latest}"
  patches:
  # etc.
```
So the variable in question is actually passing through two Kustomizations before being applied to resources in `./apps/some/path/base`

Changing the value of `dd_tag` such that it's not ambiguous anymore (string/float) fully fixes this issue, but is undesirable.
