### DISCUSSION TITLE
HelmRelease does not find helm chart inside a directory (oci repository)

### DISCUSSION THREAD

**Discussion by paucampana** [fluxcd/flux2#2959] [Q&A] [answered]
Hi all,

I am having problems with a HelmRelease pointing to a helm chart that is inside a folder. I am using a helm oci repository. The registry that I am using is Harbor.

I am using a HelmRelease with a HelmRepository. My chart is available in: `registry.example.com/example-repository/directory1/charts/chart-name`

If I configure the HelmRepository url with the repository and the directories, and then I only specify the name of the chart in the HelmRelease, it works:
 ```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: example-repository
  namespace: default
spec:  
  url: "oci://registry.example.com/example-repository/directory1/charts"
  type: oci 
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chart-name
  namespace: default
spec:
  releaseName: chart-name
  targetNamespace: default
  chart:
    spec:
      chart: chart-name
      version: 0.0.1
      sourceRef:
        kind: HelmRepository
        name: example-repository
        namespace: default
```

But, when I modify the HelmRepository url to only point to the repository, and then I write all the path in the HelmRelease, it is not working:
 ```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: example-repository
  namespace: default
spec:  
  url: "oci://registry.example.com/example-repository"
  type: oci 
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chart-name
  namespace: default
spec:
  releaseName: chart-name
  targetNamespace: default
  chart:
    spec:
      chart: directory1/charts/chart-name
      # chart: "/directory1/charts/chart-name" is not working either
      version: 0.0.1
      sourceRef:
        kind: HelmRepository
        name: example-repository
        namespace: default
```
I get the error `message: HelmChart `default/chart-name' is not ready`

It is not something about permissions because I am using admin user. 

Any idea what can be happening?
Thanks
