### DISCUSSION TITLE
Submodules on AzureDevOps with flux2

### DISCUSSION THREAD

**Discussion by hcecille** [fluxcd/flux2#2969] [Q&A] [answered]
Hello,

We try ton install flux2 with two submodules that we'd like to add to our main repository on AzureDevOps.
We've seen on documentation that we can't have go-git for gitImplementation, only libgit2 with AzureDevOps. We can't use the --recurse-submodules option.

We try to use the include option : https://fluxcd.io/docs/components/source/gitrepositories/#include
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux
  namespace: myapp-rec
spec:
  interval: 30s
  path: overlays/rec
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux
  namespace: myapp-rec
spec:
  include:
    - repository:
        name: dailyclean-kustomization
      fromPath: .
      toPath: base/common/dailyclean-kustomization
  gitImplementation: libgit2
  interval: 10s
  ref:
    branch: rec
  url: https://xxx/Kubernetes/_git/kubernetes-myapp
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dailyclean-kustomization
  namespace: myapp-rec
spec:
  gitImplementation: libgit2
  interval: 10s
  ref:
    branch: flux2
  url: https://xxx/Kubernetes/_git/dailyclean-kustomization
```

But on the kustomize, it's like there is no directory to include...
Can you please help us ?

Thanks a lot !
