### DISCUSSION TITLE
Troubleshooting Kustomization Reconciliation Length

### DISCUSSION THREAD

**Discussion by ChuckQuinnIV** [fluxcd/flux2#2987] [Q&A]
Hey all! Big Flux fan, just had a question around reconciliation troubleshooting.

## Context

I have a large Kustomization object that is taking a long time to reconcile. I'd like to get more information around which step is hanging, but can't find any timing metrics more granular than the total reconciliation length.

- Number of Objects: 1264
- Average Reconciliation Length: 2h8m
- Object Type Breakdown:
  - 85 Namespaces
  - 85 ResourceQuotas
  - 85 ClusterRoleBindings
  - 85 LimitRanges
  - 425 RoleBindings
  - 499 NetworkPolicies

The same reconciliation in Flux 1 takes around 3 minutes to complete.

## Questions
- Are there any tools available to troubleshoot how long a Kustomization reconciliation is taking on each object? The log level on the kustomize-controller is set to `trace`, but I'm not seeing any more granular information around timing.
- Are there any recommendations to reduce the amount of time an individual Kustomization takes to reconcile?

Thanks!

**Comment by kingdonb** [comment]
What version of Flux are you using exactly, for more information about this? That does seem like a long excessive time for one Flux Kustomization to run its reconciliation to completion. Especially if Flux v1 was able to process it so much more quickly.

Flux v2 does wait for things that Flux v1 did not wait for. There must be some explanation and there could be some workaround. What is your `spec.timeout` and can you possibly provide the entire Flux Kustomization spec so that we can make some better informed guesses about what could be the cause of this issue?

**Reply by ChuckQuinnIV** [reply]
Thanks Kingdon! 

Timeout is currently defaulting to our interval value (6h), but can experiment with other values there.

Flux Version: `0.31.5`
kustomize-controller Version: `v0.26.3`

Kustomization YAML:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
# ...
spec:
  interval: 6h
  sourceRef:
    kind: GitRepository
    name: tenants
  path: ./eks/engineering-test/csts-eks-ln-0
  prune: false
  force: false
```

**Reply by somtochiama** [reply]
Do you have `spec.healthChecks` or `spec.DependsOn` set?
What is the status of the Kustomization during the reconciliation i.e when you run `flux get ks`

**Reply by ChuckQuinnIV** [reply]
Nope, neither is set - the above YAML snippet is the full `spec` for my Kustomization.

Status is `Unknown` while reconciling:
```yaml
status:
  conditions:
  - lastTransitionTime: "2022-08-18T19:06:48Z"
    message: reconciliation in progress
    reason: Progressing
    status: Unknown
    type: Ready
```

And `flux get ks` output: 
```
> flux get ks
NAME                        	READY  	MESSAGE                                                                 	REVISION                                              	SUSPENDED
flux-system                 	True   	Applied revision: csts-eks-ln-0/5d6680b88babb0aa82565b253c3f485553d68021	csts-eks-ln-0/5d6680b88babb0aa82565b253c3f485553d68021	False
tenants              	        Unknown	reconciliation in progress                                              	master/ad4831f31b0d19e72f8495ce87c5af6906f92e0b       	False
```

**Reply by kingdonb** [reply]
If you set `timeout` to a shorter interval, you can see the result of the health check or failing problem at the end of the timeout.

I would generally set `timeout` to 5m or less, and also set `retryInterval` – since you don't want a failing apply at 1:00 to persist for `6h` until 7:00 before trying again. The `interval` setting can be set to `6h` if that's what you want, that's fine, but you definitely want to explore those `timeout` and `retryInterval` options as it will make Flux actually usable for debugging issues such as this one.

In the Flux Kustomization's associated events under `kubectl describe kustomization ...` you can usually find the information after a Flux controller has had some event that caused its apply to fail. But the Kubernetes timeline for default livecycle preserving events is very short, much shorter than 6h. If it failed more than 1h ago, you would probably not see anything in the events unless you had any other way of capturing and preserving those events outside of Kubernetes.

Personally I find even the default interval of `10m` is too long to wait to retry failures. I start with this setting on every Flux Kustomization and tune these numbers upward as needed based on how long rollouts have historically taken, multiplied by a factor (usually not more than 2x)

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-oci-production
  namespace: podinfo
spec:
  interval: 10m
  timeout: 1m30s
  retryInterval: 30s
  targetNamespace: podinfo-flux-oci
  sourceRef:
    kind: OCIRepository
    name: podinfo
    namespace: podinfo-flux-oci
  path: ./deploy/overlays/production
  wait: true
  prune: true
```

This way Flux will dry-run and check for changes to apply once every 10 minutes, wait no more than 1m30s to give up and signal an event with the failure if something should fail the health check, then try again 30s after the failure in case it succeeds the next time.

**Reply by ChuckQuinnIV** [reply]
Thanks for the suggestion around those values! Tried lowering the retryInterval & timeout as suggested, but am still seeing the same results.

Updated Kustomization spec:
```yaml
spec:
  interval: 6h
  timeout: 1m30s
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: tenants
  path: ./eks/engineering-test/csts-eks-ln-0
  prune: false
  force: false
```

Most recent result:
`Normal  ReconciliationSucceeded  8s  kustomize-controller  Reconciliation finished in 2h10m0.314248633s, next run in 6h0m0s`

Not sure if this helps narrow down where the Kustomization could be waiting, if the timeout value didn't change how long the reconciliation laste?
