### DISCUSSION TITLE
Is there a way to tell flux to give up on deploying a commit?

### DISCUSSION THREAD

**Discussion by myers** [fluxcd/flux2#2989] [Q&A] [answered]
I made a change to my flux repo.  I made a mistake, used `envFrom.configMapRef` when it should have been `envFrom.secretRef`.  I commited (`505c6f71b7cd7d75efc0e101098f30d39b9b92ae`) and pushed.  I see the mistake using `kubectl`, commit a fix (`76f7292`), and pushed.

Now 15 minutes later `flux get all` says:

```
NAME                            READY   MESSAGE                         REVISION        SUSPENDED
gitrepository/flux-system       True    Fetched revision: main/76f7292  main/76f7292    False

NAME                            READY   MESSAGE                                         REVISION                                        SUSPENDED
kustomization/flux-system       True    Applied revision: main/76f7292                  main/76f7292                                    False

kustomization/infrastructure    True    Applied revision: main/76f7292                  main/76f7292                                    False

kustomization/apps              Unknown running health checks with a timeout of 5m0s    main/505c6f71b7cd7d75efc0e101098f30d39b9b92ae   False
```

How can I get `kustomization/apps` to give up on the broken commit `505c6f71b7cd7d75efc0e101098f30d39b9b92ae` and move on to `76f7292`?  

EDIT: I posted the wrong thing first
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
  - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/brainframe
  prune: true
  wait: true
  timeout: 5m0s
```

Thanks!
