### DISCUSSION TITLE
A gitops action to automatically push new helm chart versions for flux2

### DISCUSSION THREAD

**Discussion by cep21** [fluxcd/flux2#2991] [Show and tell] [answered]
I recently wrote [helm-autoupdate](https://github.com/cresta/helm-autoupdate).  We use it to automatically push new helm chart versions with flux.

The existing way:
```
     sourceRef:
        kind: HelmRepository
        name: aws
      version: "*"
```

Does not feel very gitops to us since we cannot track in git when a deployment happens.  We also cannot use `git revert` or setup a PR for the change before it goes into production.  Instead we use helm-autoupdate and our HelmRelease object looks like this:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-vpc-cni
spec:
  chart:
    spec:
      chart: aws-vpc-cni
      sourceRef:
        kind: HelmRepository
        name: aws
      version: 0.0.1 # helm:autoupdate:aws-vpc-cni
  interval: 1m0s
  timeout: 10m
  values:
    replicaCount: 1
```

With this system, we can cron helm-autoupdate (as well as manually trigger it when we build internal charts) and have PRs (with all our PR status checks) for new helm chart releases.
