### DISCUSSION TITLE
Don't want namespace as prefix for HelmRelease artifacts

### DISCUSSION THREAD

**Discussion by rishinair11** [fluxcd/flux2#3001] [Q&A] [answered]
## Backstory
I am using HelmRelease custom resource to install a Helm Chart in my cluster.
Below is the YAML:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: operator
  namespace: operator
spec:
  chart:
    spec:
      chart: <redacted>
      sourceRef:
        kind: GitRepository
        name: <redacted>
        namespace: flux-system
  interval: 2m
  install:
    remediation:
      retries: 3
```
As you can see, the key `releaseName` has not been specified.
Still, when I see the resources created by the HelmRelease, I see that a prefix has been applied to all the resources, which is the `namespace` of the HelmRelease resource.
I referred the API docs [here](https://fluxcd.io/docs/components/helm/helmreleases), where it is mentioned that `releaseName` will default to `targetNamespace`, which in term defaults to the namespace of the HelmRelease resource.

## Problem
I have another operator, which is created using Flux and Kustomize (not HelmRelease), and that operator depends on the resources of the operator created by HelmRelease (mentioned above) to have a specific name, but `releaseName` prefix is altering it, causing my dependent operator to not identify the initial operator resources. 

**Is there a way to not add a prefix to the HelmRelease resources?**

Thanks in advance :)
