### DISCUSSION TITLE
Deploy cert-manager with Flux

### DISCUSSION THREAD

**Discussion by patrickc-sb** [fluxcd/flux2#3009] [Q&A] [answered]
Hello,

I'm currently trying to deploy cert-manager with Flux and cert-manager is not being reconciled properly. I'm currently trying to gain some experience with Kubernetes, so I'm fairly new to both, Kubernetes and also Flux.

I have Flux successfully deployed into my cluster and have also already successfully deployed ingress-nginx and sealed-secrets, I think. With cert-manager however I haven't been successful yet. 

My cluster-setup right now looks as follows:
```bash
clusters
└── prod
    ├── flux-system
    │   ├── gotk-components.yaml
    │   ├── gotk-sync.yaml
    │   └── kustomization.yaml
    ├── infra
    │   ├── READEME.md
    │   ├── cert-manager
    │   │   ├── kustomization.yaml
    │   │   ├── namespace.yaml
    │   │   ├── release.yaml
    │   │   ├── source-git-certmanager.yaml
    │   │   └── source-helm-certmanager.yaml
    │   ├── kustomization.yaml_
    │   ├── nginx-ingress
    │   │   ├── nginx-ingress-controller-lb.yaml
    │   │   └── nginx-ingress-lb.yaml_
    │   └── sealed-secrets
    │       ├── release-sealedsecrets.yaml
    │       └── source-sealedsecrets.yaml
```
 with release.yaml:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: jetstack/cert-manager
      version: 'v1.9.1'
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 1m
```
source.yaml:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.jetstack.io

```
and kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
- namespace.yaml
- release.yaml
```

I learned from the Flux documentation on [this](https://fluxcd.io/docs/components/kustomize/kustomization/#kustomization-dependencies) page that I need to split the installation up into two kustomizations. I also tried these exact kustomizations but it didnt work. So far with the issues I found on this topic I wasnt able to understand exactly how cert-manager needs to be deployed or where I'm going wrong with this. I feel like I'm missing or not understanding something basic. 

Right now I'm kind of stuck. Sorry for the general question but can anyone give me some input on where I might go wrong with this?
If you need any more information let me know, I appreciate any feedback.

**Comment by somtochiama** [comment]
Hey @patrickc-sb , What error are you getting / how are you stuck?
What's the out put you have when you run `flux get ks cert-manager`?

The link from the docs is depency ordering, when you need one set of resources deployed before you can apply another. You would need two separate flux `Kustomization`. One for the `cert-manager` and another for the certs. But from the repository structure you  posted, it doesn't look like you have any certs yet.

**Comment by patrickc-sb** [comment]
Hey @somtochiama,

thanks for responding so quickly! The output of `flux get ks cert-manager` is `no Kustomization objects found in flux-system namespace` with the setup from my initial post. 

> The link from the docs is depency ordering, when you need one set of resources deployed before you can apply another. You would need two separate flux Kustomization. One for the cert-manager and another for the certs. But from the repository structure you posted, it doesn't look like you have any certs yet.

I just added a kustomization file to my repo with the content from the documentation link. 
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  path: "./cert-manager/controller"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: certs
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 5m
  path: "./cert-manager/certs"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

Yes so far I dont have any certs, I also didnt deploy the cluster-issuer yet. I wanted to setup cert-manager first and then start deploying a service. I also dont see any logs regarding my deployment in `flux logs` after the deployment. `flux get ks cert-manager` also still shows `no Kustomization objects found in flux-system namespace`. I'm just not sure what I'm missing, I cant seem to figure out how exactly I need to put things together for cert-manager to be deployed properly.
