### DISCUSSION TITLE
Flux components customization doesn't work after bootstrap with Terraform

### DISCUSSION THREAD

**Discussion by agilevich1** [fluxcd/flux2#3010] [Q&A] [answered]
Hey, folks!

I was able to bootstrap Flux to the EKS cluster using these docs https://github.com/fluxcd/terraform-provider-flux/blob/main/docs/guides/github.md. That works fine, Flux picks up updates from github and isntall them into EKS!
Now I would like to customize Flux components (add affinities, tolerations, adjust replicas etc.), I used these docs https://github.com/fluxcd/terraform-provider-flux/blob/main/docs/guides/customize-flux.md to create a patch. When I apply changes with Terraform, I can see that patch file `patch-fluxcd-deployments.yaml` has been committed to github as well as kustomization.yaml file has been updated:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-sync.yaml
- gotk-components.yaml
patchesStrategicMerge:
- patch-fluxcd-deployments.yaml
```
However flux components on the EKS cluster itself won't get updated .. Am I missing something ? I tried a couple of things, but flux just ignores the patches ...

I tried:
- run flux reconcile source git flux-system
- taint/apply flux components to rebootstrap

Thanks for help in advance.

**Comment by somtochiama** [comment]
Hey. What does your `patch-fluxcd-deployments.yaml` yaml look like?

**Comment by agilevich1** [comment]
@somtochiama hey
here's the file content
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        # Required by Kubernetes node autoscaler
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      tolerations:
        - key: dedicated
          operator: Equal
          value: infra
          effect: NoSchedule
```
running `kustimize build . ` from the `flux-system` folder seems to be working, pathcing works without errors ...
