### DISCUSSION TITLE
postRenderers subchart

### DISCUSSION THREAD

**Discussion by masterkain** [fluxcd/flux2#3021] [Q&A] [answered]
I have a HelmRelease using a custom chart with a bitnami `postgresql` subchart as its dependency.
for reasons beyond this discusion I'm trying from my HelmRelease to replace the image directly in the resulting postgres StatefulSet instead of manipulating the subchart values, here's an attempt

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blabla
spec:
...
  values:
    postgresql:
      enabled: true
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - kind: StatefulSet
        apiVersion: apps/v1
        metadata:
          name: blabla-postgresql
        spec:
          template:
            spec:
              containers:
              - name: postgresql
                image: myregistry/myimage:mytag
```

however this isn't working

```
Helm install failed: error while running post render on files: no matches for Id StatefulSet.v1.apps/blabla-postgresql.[noNs]; failed to find unique target for patch StatefulSet.v1.apps/blabla-postgresql.[noNs[]
```

am I just missing the right target or is something that cannot be done?
