### DISCUSSION TITLE
Allow bootstrap command to read from a config file

### DISCUSSION THREAD

**Discussion by onedr0p** [fluxcd/flux2#304] [Proposals]
With addition to CLI flags, it would be nice if gotk could also read from a config file. This could be checked into source control and be easily shared with team members.

For example, this would be equal:

```bash
gotk bootstrap github \
  --components=source-controller,kustomize-controller,helm-controller,notification-controller \
  --path=my-prod-cluster \
  --version=latest
```

and 

```bash
gotk bootstrap -f prod-config.yaml
```

```yaml
# prod-config.yaml
---
provider: github
path: my-prod-cluster
version: latest
components:
- source-controller
- kustomize-controller
- helm-controller
- notification-controller
```
