### DISCUSSION TITLE
Is it possible to inject config map values into environment variables within a release.

### DISCUSSION THREAD

**Discussion by mjallday** [fluxcd/flux2#3058] [Q&A]
I have a generic chart I use for apps that allows the running app to have a customized set of environment variables that it expects. 

I want to have a common config map with all the variables for a specific environment and then I want to inject them into the environment depending on which app is running. 

e.g. 

App1 expects `DB_URI`
App2 expects `POSTGRES_URI`

I was hoping that there was a way to do this but so far the answer has eluded me. 

I've got a HelmRelease that looks like this

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: App1
  namespace: gitops
spec:
  targetNamespace: app1-service
  interval: 5m
  chart:
    spec:
      chart: my-generic-chart
  valuesFrom:
  - kind: ConfigMap
    name: common
  values:
        environment:
          DB_URI:
            valueFrom:
              configMapKeyRef:
                name: common
                key: database_url
```

and then in the second app have something similar but with

```yaml
...
  values:
        environment:
          POSTGRES_URI:
            valueFrom:
              configMapKeyRef:
                name: common
                key: database_url
```

Is there any way to achieve this? My kustomize-fu is not quite up to scratch.
