### DISCUSSION TITLE
Enable `HTTPS` for source artifact URL defined in `.status.artifact.url`

### DISCUSSION THREAD

**Discussion by rashedkvm** [fluxcd/flux2#3066] [Proposals]
### Motivation

Flux source-controller to support TLS enabled `HTTPS` scheme for `status.artifact.url`.  The `Artifact` type has the `URL` field, which exposes the `HTTP` address of the Artifact for downstream consumption. Flux source-controller is a component of our application development platform. During a recent security review of our platform, we discussed the need for enabling TLS in `status.artifact.url`, and the ask is "_secure-at-all-times_". 

I am very aware of the scope and the change this proposal can bring to Source Controller and its API sets. However, this is a worthwhile addition to the Source Controller offerings. 

### Goals

- Add support for HTTPS in Flux source-controller source artifact download url. 
- Add support for providing and updating the certificate/key pair required for enabling TLS
- Supported artifact download schemes
  - HTTP only
  - HTTPS only
  - HTTP + HTTPS (both schemes)
- Provide a way to share the certificate so a client can connect over TLS

### Proposal

- Add a fixed named secret that contains the TLS key and certificate
- Source Controller manager deployment will use the secret in a mounted volume
- Use `cert-manager` to issue a certificate and rotate expired certificates
- Add a new type, `SecureArtifact` that has all the existing fields available in the existing `Artifact` type plus a new field called `CABundle`. The `CABundle` is a string field that contains the client certificate key/value pair  
- The `URL` field for `SecureArtifact` will contain the `HTTPS` download URL
- Source Controller APIs `Status` will include `SecureArtifact` as well as existing `Artifact` and maintain backward compatibility

Here is a mock shape of the fixed name `secret`
```yaml
apiVersion: v1
data:
  ca.crt: …
  tls.crt: …
  tls.key: …
kind: Secret
metadata:
  name: source-server-cert
  namespace: flux-system
type: kubernetes.io/tls
```

Here is a mock of the proposed API status
```yaml
status:
  artifact:                 # existing type `Artifact`
    ...
    url: "http://..."
  secureArtifact:           # New type `SecureArtifact` = `Artifact` + CABundle
    ...
    url: "https://..."
    caBundle: ""
```
