### DISCUSSION TITLE
Add common labels for components

### DISCUSSION THREAD

**Discussion by artem-nefedov** [fluxcd/flux2#3100] [Proposals] [answered]
It's great that Flux manifests are now uploaded to OCI registries, and therefore can be installed with Kustomize controller.
However, one thing that's not convenient to do is disabling certain components.
A potentially good solution here is to add component-based labels (or annotations) to all resources.

For example, if all resources related to image-reflector-controller (Deployment, Service, CRD, etc.) would have a label `kind: image-reflector-controller`, then I could use a following Kustomization to deploy flux while disabling all image-reflector-controller components:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux-system
  prune: false
  patches:
  - target:
      labelSelector: kind=image-reflector-controller
    patch: |
      $patch: delete
      kind: ignored
      apiVersion: ignored
      metadata:
        name: ignored
  sourceRef:
    kind: OCIRepository
    name: flux
```
