### DISCUSSION TITLE
How to deploy multiple helm charts in  EKS cluster using flux

### DISCUSSION THREAD

**Discussion by Dotisandhyarani** [fluxcd/flux2#3103] [General] [answered]
I am able to deploy single helm chart at a time to EKS using flux cd.

But wanted to deploy multiple helm charts, having an issue with the path:
my manifest files:

my folder structure for helm chart applications looks like this
```

root
├── charts
│   ├── release  << released charts (archives)
│   └── src      << chart source (in dev)
│       ├── ...
│       └── analytics
│           ├── ...
│           └── fleet1-api
│           └── fleet2-api     
└── README.md
```
```

# HelmRelease manifest
resource "kubectl_manifest" "eco_helm_release" {
  yaml_body = <<YAML
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-helm
  namespace: flux-system
spec:
  install:
    disableWait: true
  upgrade:
    disableWait: true
  interval: 5m
  chart:
    spec:
      chart: ./charts/src/analytics/fleet1-api/
      version: '4.0.x'
      sourceRef:
        kind: GitRepository
        name: fleet-helm
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
YAML
}
```

in above chart.spec.chart - when I give single helm chart path it works.
but since I wanted to deploy all helm charts under `analytics` directory from above file structure.

when  I try the path `chart.spec.chart : ./charts/src/analytics/**/`  throws below error when I check `flux get all`

               
`helmchart/flux-system-fleet-helm	0.1.5   	False    	False	invalid chart reference: stat /tmp/helmchart-flux-system-flux-system-eco-helm-2140938400/source/charts/src/analytics/**: no such file or directory	
`

Any help would be appreciated.
