### DISCUSSION TITLE
How can we debug 403 error on imageupdateautomation resource

### DISCUSSION THREAD

**Discussion by mnehalb-lab** [fluxcd/flux2#3112] [Q&A] [answered]
Hi FluxCD Team, i have been running kubernetes with flux, everything is working fine but my imageUpdateAutomation object is giving "unhandled HTTP error 403 forbidden" and i am not able to find from where to debug it? I have check all controller logs of flux but still no information from it?

**Comment by stefanprodan** [comment, marked as answer]
This usually happens when Flux has no write access to the repo. Have you used `flux bootstrap --read-write-key`? Docs here: https://fluxcd.io/flux/guides/image-update/#install-flux

**Reply by mnehalb-lab** [reply]
Hi @stefanprodan, i tried to run this example "https://fluxcd.io/flux/guides/image-update/" to check if that is the case but it's not giving me 403 error. I remove "--read-write-key" to check if that is the reason for this 403 error

Flux Command:
```
flux bootstrap github \
  --components-extra=image-reflector-controller,image-automation-controller \
  --owner=$GITHUB_USER \
  --repository=flux-image-updates \
  --branch=main \
  --path=clusters/my-cluster \
  --personal
```

![why](https://user-images.githubusercontent.com/96332398/190881283-70277798-2536-45d0-bebf-e1ebbded099a.PNG)
![Capture234](https://user-images.githubusercontent.com/96332398/190881284-fee303ec-6423-4ab3-884e-dfe0960ff936.PNG)

**Reply by stefanprodan** [reply]
Can you post here the ImageUpdateAutomation and the GitRepository YAML that it references? My guess is that you're using Git over HTTPS instead of SSH, and that's the reason you see a different error.

**Reply by mnehalb-lab** [reply]
Hi @stefanprodan ,  Please see below YAML files and for reference, you can check this gitrepo (https://github.com/mnhomelab66/flux-image-updates)

![GitRepository](https://user-images.githubusercontent.com/96332398/191065533-41292a1c-d508-430c-8bae-cba64498ac2f.PNG)
![ImageAutomationUpdate](https://user-images.githubusercontent.com/96332398/191065526-51432eec-bf52-400e-972d-9ee799baafce.PNG)

**Reply by kingdonb** [reply]
If you have bootstrapped the same cluster twice, `flux bootstrap` only creates a secret `flux-system` if one did not exist already. So if you ran the second bootstrap with the `read-write-key` option, then it may not have had any effect at all.

Try deleting the `flux-system` secret and replacing it with a new invocation of `flux bootstrap` that uses `--read-write-key`

Your GitRepository is correctly using the ssh URL as far as I can see, so this is the only possibility I can think of that remains.

**Comment by chuegel** [comment]
I get the same `unhandled HTTP error 403 Forbidden`error

```
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: podinfo
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@example.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: podinfo
    namespace: flux-system
  update:
    strategy: Setters
```

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: master
  secretRef:
    name: flux-scm
  url: https://<on-prem-gitlab>/k8s-podinfo-flux-automation.git
```

Edit:
interestingly I don't get any 403 errors when deployed in the default namespace but the image doesn't update:

```
flux get images all --all-namespaces
NAMESPACE	NAME                   	LAST SCAN                	SUSPENDED	READY	MESSAGE
default  	imagerepository/podinfo	2022-10-13T16:43:39+02:00	False    	True 	successful scan, found 35 tags

NAMESPACE	NAME               	LATEST IMAGE                      	READY	MESSAGE
default  	imagepolicy/podinfo	ghcr.io/stefanprodan/podinfo:6.2.1	True 	Latest image tag for 'ghcr.io/stefanprodan/podinfo' resolved to: 6.2.1

NAMESPACE	NAME                         	LAST RUN                 	SUSPENDED	READY	MESSAGE
default  	imageupdateautomation/podinfo	2022-10-13T16:43:41+02:00	False    	True 	no updates made
```

```
kubectl get deployments.apps podinfo -o wide
NAME      READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES                               SELECTOR
podinfo   1/1     1            1           11m   podinfod     ghcr.io/stefanprodan/podinfo:5.0.3   app=podinfo
```

 Edit 2:

So it turned out that 
```
  secretRef:
    name: flux-scm
```

above didn't hat write access to the repo. Created another secret with a personal access token with proper rights:
```
flux get image all
NAME                   	LAST SCAN                	SUSPENDED	READY	MESSAGE
imagerepository/podinfo	2022-10-13T19:29:45+02:00	False    	True 	successful scan, found 35 tags

NAME               	LATEST IMAGE                      	READY	MESSAGE
imagepolicy/podinfo	ghcr.io/stefanprodan/podinfo:6.2.1	True 	Latest image tag for 'ghcr.io/stefanprodan/podinfo' resolved to: 6.2.1

NAME                         	LAST RUN                 	SUSPENDED	READY	MESSAGE
imageupdateautomation/podinfo	2022-10-13T19:29:59+02:00	False    	True 	no updates made
```
