### DISCUSSION TITLE
Auto recreate pods when new commit in helm charts repo using flux CD

### DISCUSSION THREAD

**Discussion by Dotisandhyarani** [fluxcd/flux2#3114] [General]
I auto deploy helm charts to aws EKS cluster using fluxCD with terraform , it works fine.

****Two repos:****

- infrastructure repo
- helm repo

I have synced the helm repo with infrastructure repo.  But when I update the helm charts and commit to bitbucket, 
Using `flux get kustomizations --watch` I see `kustomizations` picks latest commit from 'helm-repo' which is correct, but pods not recreating. 

Pods are  recreated only when I increment version in `chart.yaml` every single time when commit to helm-repo. 

**Helmrelease.yaml** config:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-api
  namespace: flux-system
spec:
  install:
    disableWait: true
  upgrade:
    disableWait: true
  interval: 5m
  chart:
    spec:
      chart: ./charts/src/analytics/sample-api/
      sourceRef:
        kind: GitRepository
        name: helm
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 3

```

How do I avoid incrementing version in `chart.yaml` and automatically recreate pods when  I do commits in `helm-repo`. I'm using terraform `data_sync` resource to add helm-repo to flux.

Any suggestions !
