### DISCUSSION TITLE
How does flux pass env variables dynamically to helm charts using terraform

### DISCUSSION THREAD

**Discussion by Dotisandhyarani** [fluxcd/flux2#3130] [General] [answered]
Auto deploying helm charts with Flux.

I have deployed helm charts using flux in EKS cluster and wanted to pass the env variables to helm charts from terraform.

I have some services deployed with terraform (infra repo) and would like to pass some of those values dynamically to helm charts (helm-repo) as env varaibles .  And I have envVariables in `values.yaml` and would like to pass the values to those env variables using terraform dynamically.

I have defined `HelmRelease` for each helm chart, I can pass values here but don't want to hardcord in the helmrelease.

HelmRelease
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: analytics
  namespace: flux-system
spec:
  install:
    disableWait: true
  upgrade:
    disableWait: true
  interval: 5m
  chart:
    spec:
      chart: ./charts/src/analytics/analytics/
      sourceRef:
        kind: GitRepository
        name: helm-repo
        namespace: flux-system
      interval: 1m
## We can define values overrides inline via spec.values
#  values:
#    autoscaling:
#      minReplicas: 2


```

**Comment by stefanprodan** [comment, marked as answer]
From TF create a Secret or ConfigMap a in the `flux-system` namespace in this format:
```
apiVersion: v1
kind: Secret
metadata:
  namespace: flux-system
  name: tf-values
stringData:
  values.yaml: |
     someKey: someValue
```

Then in the HelmRelease use the Secret:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: analytics
  namespace: flux-system
spec:
  valuesFrom:
  - kind: Secret
    name: tf-values
```

**Reply by Dotisandhyarani** [reply]
Excellent, that worked!  Thanks for the inputs

Created `ConfigMap` in terraform like below:
```

resource "kubernetes_config_map" "analytics-api" {
  metadata {
    name = "analytics-api"
    namespace = "flux-system"
  }
  data = {
    "values.yaml" =  <<YAML
envVariables:
  TABLEPREFIX: ${var.resource_prefix}
YAML
  }
}
```

and in HelmRelease used the `configMap` name `analytics-api` in `valuesFrom` as

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: analytics-tank
  namespace: flux-system
spec:
  install:
    disableWait: true
  upgrade:
    disableWait: true
  interval: 5m
  chart:
    spec:
      chart: ./charts/src/analytics/analytics-api/
      sourceRef:
        kind: GitRepository
        name: helm-repo
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: analytics-api
      valuesKey: values.yaml


```
