### DISCUSSION TITLE
Helm controller how to over-ride a value at custom values.yaml

### DISCUSSION THREAD

**Discussion by DevopsCareer** [fluxcd/flux2#3132] [Q&A] [answered]
Hi,

My helm release currently looks like this :
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test-chart
  namespace: test
spec:
  interval: 5m
  chart:
    spec:
      chart: test-chart
      version: "0.1.0"  
      sourceRef:
        kind: HelmRepository
        name: test-repo
        namespace: test
      valuesFiles:
        - environments/dev/values-dev.yaml 
```
I want to use custom values.yaml to render my templates hence I am using custom `valuesFiles` with relative path `environments/dev/values-dev.yaml . `

My question is how can I override just a specific value at custom values file `environments/dev/values-dev.yaml ` ?
For example say I want to override a attribute a value `az=zone_a` in `environments/dev/values-dev.yaml ` .

The idea is to use the same custom value file `environments/dev/values-dev.yaml` but probably create say 2 different HelmRelease one with overriding value  as `az=az=zone_a` and second with overiding value as `az=az=zone_b`.
Can i use `spec.values` along with `spec.valuesFrom` ? 

Something like :
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test-chart
  namespace: test
spec:
  interval: 5m
  chart:
    spec:
      chart: test-chart
      version: "0.1.0"  
      sourceRef:
        kind: HelmRepository
        name: test-repo
        namespace: test
      valuesFiles:
        - environments/dev/values-dev.yaml 
      values:
          az: zone_a

```
Order of operation is to use valuesFiles `environments/dev/values-dev.yaml ` file overriding default values.yaml and finally value `az` only key override just value `az` as final override in `environments/dev/values-dev.yaml `

**Comment by kingdonb** [comment, marked as answer]
https://fluxcd.io/flux/components/helm/helmreleases/#values-overrides

^ You can use `values` and `valuesFrom` all together with `valuesFiles`, yes. The order of application is explained under this entry.

This may be the change you needed to see:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test-chart
  namespace: test
spec:
  interval: 5m
  chart:
    spec:
      chart: test-chart
      version: "0.1.0"  
      sourceRef:
        kind: HelmRepository
        name: test-repo
        namespace: test
      valuesFiles:
        - environments/dev/values-dev.yaml 
  values:
      az: zone_a
```

Note that `values` is under `HelmReleases.spec` (not down beneath where you have it located under `spec.chart.spec`)
