### DISCUSSION TITLE
Support Branch Pattern for ImageUpdateAutomation

### DISCUSSION THREAD

**Discussion by craigbryson** [fluxcd/flux2#3135] [Proposals]
Hi Folks, not sure if this is a question or a proposal, lets see:

I currently have Image Automation set up and its working well, pushes change to a new branch and a GitHub Action creates a PR. the issue with my current design is that if another image updates (from the same setters path but a different image) before the PR is closed the new change is pushed to the same branch and as such included in the same PR.
Is it possible to do something like branch: mybranch-$random so that each image update pushes to a different branch that follows some pattern?

Maybe however, this is the wrong flow and I should create an ImageUpdateAutomation for each app independently? Currently I have something like:

``` yaml
    push:
      branch: flux-apps-image-updates
  update:
    path: ./apps
    strategy: Setters
```
