### DISCUSSION TITLE
Fluxv2 datadog integration

### DISCUSSION THREAD

**Discussion by melchiormoulin** [fluxcd/flux2#3157] [Show and tell]
Hello just to inform you that Blablacar developed a [Datadog integration for flux2 ](https://github.com/DataDog/integrations-extras/tree/master/fluxcd)
This enable to scrape metrics from datadog agent.

**Comment by stefanprodan** [comment]
@melchiormoulin this looks great, we could add the integration to https://fluxcd.io/ecosystem/#integrations 

cc @dholbach

**Reply by dholbach** [reply]
→ https://github.com/fluxcd/website/issues/1168

**Comment by cep21** [comment]
Is anyone using this integration successfully?  The example config (https://github.com/DataDog/integrations-extras/blob/master/fluxcd/datadog_checks/fluxcd/data/conf.yaml.example) is just a default template.

From the code, I think one needs to point the config to the flux metrics endpoints?

**Comment by cep21** [comment]
For people finding this ticket, if you're using helm you want to add values like this to your helm chart if using datadog (after also installing the fluxcd agent in your dockerfile): (Do the same for the other controllers (notificationController/kustomizeController/etc)
```yaml
      sourceController:
        annotations:
          prometheus.io/scrape: "false"
          ad.datadoghq.com/manager.checks: |
            {
              "fluxcd": {
                "instances": [ {
                    "openmetrics_endpoint": "http://%%host%%:8080/metrics"
                  } ]
              }
            }
        labels:
          tags.datadoghq.com/source: source-controller
          tags.datadoghq.com/service: source-controller
```


How to install the fluxcd agent in your dockerfile
```dockerfile
FROM datadog/agent:7.44.0
RUN agent integration install -r -t datadog-fluxcd==0.0.1
```
