### DISCUSSION TITLE
How to use valuesFrom, targetPath and configMapGenerator to merge large objects into HelmRelease values?

### DISCUSSION THREAD

**Discussion by airtonix** [fluxcd/flux2#3163] [Q&A] [answered]
I have these files: 

<details><summary>manifests/apps/hajimari/helm-release.yaml</summary>

```yml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: hajimari-app

spec:

  interval: 5m

  chart:
    spec:
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari-helm-repo
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      pullPolicy: IfNotPresent
      tag: v0.2.0

    resources:
      requests:
        cpu: 100m
        memory: 128M

  valuesFrom:
    - kind: ConfigMap
      name: hajimari-config
      valueskey: hajimari
      targetPath: hajimari
    - kind: ConfigMap
      name: hajimari-config
      valuesKey: ingress
      targetPath: ingress
```
</details>


<details><summary>manifests/apps/hajimari/namespace.yaml</summary>

```yml
---
apiVersion: v1
kind: Namespace
metadata:
  name: hajimari-app
```
</details>

<details><summary>manifests/apps/hajimari/Kustomization.yaml</summary>

```yml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hajimari-app
resources:
  - namespace.yaml
  - helm-release.yaml
```
</details>

and then in my cluster specific overlay: 


<details><summary>manifests/cluster-systems/default/apps/kustomization.yaml</summary>

```yml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/hajimari

configMapGenerator:
  - name: hajimari-config
    namespace: hajimari-config
    files:
      - hajimari=hajimari-app-config.yaml

  - name: hajimari-ingress-config
    namespace: hajimari-config
    files:
      - ingress=hajimari-ingress-config.yaml

configurations:
  - kustomizeconfig.yaml
```
</details>

<details><summary>manifests/cluster-systems/default/apps/kustomizeconfig.yaml</summary>

```yml
---
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/valuesFrom/name
    kind: HelmRelease
```
</details>

<details><summary>manifests/cluster-systems/default/apps/hajimari-ingress-config.yaml</summary>

```yml
main:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: cloudflare-certificate-issuer

  hosts:
    - host: hajimari.${CLUSTER_DOMAIN}
      paths:
        - path: /
          pathType: Prefix
```
</details>

<details><summary>manifests/cluster-systems/default/apps/hajimari-app-config.yaml</summary>

```yml
instanceName: hajimari-ui

defaultEnable: true

namespaceSelector:
  any: true

title: "${HAJIMARI_DASHBOARD_TITLE}"

name: "${HAJIMARI_DASHBOARD_NAME}"

customApps: []

groups:
  - name: Development
    links:
      - name: FluxCD
        url: https://fluxcd.io/flux/
```
</details>


hajimarji chart allows values that look like: 

```

values: 
  ingress:
    main:
      enabled: true
    
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: cloudflare-certificate-issuer
    
      hosts:
        - host: some.domain.com
          paths:
            - path: /
              pathType: Prefix

  hajimari:
    instanceName: hajimari-ui
    
    defaultEnable: true
    
    namespaceSelector:
      any: true
    
    title: "a browser page title i guess?"
    
    name: "Some greeting name used in the page"
    
    customApps: []
    
    groups:
      - name: Development
        links:
          - name: FluxCD
            url: https://fluxcd.io/flux/

```

If i run a local `kustomize build`:

<details><summary> $ kustomize build ./manifests/cluster-systems/default/apps                                                                                            
 </summary>

```yml
apiVersion: v1
kind: Namespace
metadata:
  name: hajimari-app
---
apiVersion: v1
data:
  hajimari: |
    instanceName: hajimari-ui

    defaultEnable: true

    namespaceSelector:
      any: true

    title: "${HAJIMARI_DASHBOARD_TITLE}"

    name: "${HAJIMARI_DASHBOARD_NAME}"

    customApps: []

    groups:
      - name: Development
        links:
          - name: FluxCD
            url: https://fluxcd.io/flux/
  ingress: |
    main:
      enabled: true

      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: cloudflare-certificate-issuer

      hosts:
        - host: hajimari.${CLUSTER_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
kind: ConfigMap
metadata:
  name: hajimari-config-7t6642h9gk
  namespace: hajimari-app
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: hajimari-app
spec:
  chart:
    spec:
      chart: hajimari
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: hajimari-helm-repo
        namespace: flux-system
      version: 1.2.0
  interval: 5m
  values:
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    resources:
      requests:
        cpu: 100m
        memory: 128M
  valuesFrom:
  - kind: ConfigMap
    name: hajimari-config-7t6642h9gk
    targetPath: hajimari
    valuesKey: hajimari
  - kind: ConfigMap
    name: hajimari-config-7t6642h9gk
    targetPath: ingress
    valuesKey: ingress
                                  
```
</details>

Except when the release deploys onto my cluster, the Hajimari template errors, because it expects `values.hajimari` and `values.ingress` to be an object instead of a string: 

<details><summmary> Error result </summary>

```shell
hajimari        1.2.0           False           False   Helm upgrade failed: template: hajimari/templates/common.yaml:14:3: executing "hajimari/templates/common.yaml" at <include "common.all" .>: error calli​‌​
ng include: template: hajimari/charts/common/templates/_all.tpl:51:5: executing "common.all" at <include "common.ingress" .>: error calling include: template: hajimari/charts/common/templates/_ingress.tpl:4:​‌​
38: executing "common.ingress" at <.Values.ingress>: range can't iterate over main:
                                                          enabled: true                                                                                                                                        ​‌​
                                                                                                                                                                                                               ​‌​
                                                                                   
                                                                                                                                                                                                               ​‌​
                                                                                                                                                                                                               ​‌​
                                                                                   
                                                          annotations:                                                                                                                                         ​‌​
                                                                                                                                                                                                               ​‌​
                                                                                   
                                                            kubernetes.io/ingress.class: traefik                                                                                                               ​‌​
                                                                                                                                                                                                               ​‌​
                                                                                   
                                                            cert-manager.io/cluster-issuer: cloudflare-certificate-issuer                                                                                      ​‌​
                                                                                                                                                                                                               ​‌​
                                                                                   
                                                                                                                                                                                                               ​‌​
                                                                                                                                                                                                               ​‌​
                                                                                   
                                                          hosts:                                                                                                                                               ​‌​
                                                                                                                                                                                                               ​‌​
                                                                                   
                                                            - host: hajimari.kube.lan                                                                                                                         ​‌​
                                                                                                                                                                                                               ​‌​
                                                                                   
                                                              paths:                                                                                                                                           ​‌​
                                                                                                                                                                                                               ​‌​
                                                                                   
                                                                - path: /                                                                                                                                      ​‌​
                                                                                                                                                                                                               ​‌​
                                                                                   
                                                                  pathType: Prefix    
```

</details>


1. Is the way the generated configmap is created (as two multiline strings) is probably the start of my issues?
2. Is there a way I can get it to merge as objects instead of a stringvalue when the `valuesFrom` and `targetPath` is executed?

**Comment by airtonix** [comment, marked as answer]
I looked for some other options and instead of generating a ConfigMap (which really seems to be for creating contents of files that would end up as volume mounts) used [patches](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches): 


<details><summary>manifests/apps/hajimari/helm-release.yaml</summary>

```yml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: hajimari-app

spec:

  interval: 5m

  chart:
    spec:
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari-helm-repo
        namespace: flux-system
      interval: 5m

  values:
    instanceName: hajimari-ui

    ingress:
      main:
        enabled: true

        annotations:
          kubernetes.io/ingress.class: traefik

        hosts:
          - paths:
              - path: /
                pathType: Prefix
```
</details>


<details><summary>manifests/apps/hajimari/namespace.yaml</summary>

```yml
---
apiVersion: v1
kind: Namespace
metadata:
  name: hajimari-app
```
</details>

<details><summary>manifests/apps/hajimari/Kustomization.yaml</summary>

```yml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hajimari-app
resources:
  - namespace.yaml
  - helm-release.yaml
```
</details>

and then in my cluster specific overlay: 


<details><summary>manifests/cluster-systems/default/apps/kustomization.yaml</summary>

```yml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/hajimari

patches:
  - path: hajimari-app-config-patch.yaml
  - path: hajimari-ingress-patch.yaml
    target:
        group: helm.toolkit.fluxcd.io
        version: v2beta1
        kind: HelmRelease
```
</details>

<details><summary>manifests/cluster-systems/default/apps/hajimari-ingress-patch.yaml</summary>

```yml
- op: add
  path: /spec/values/ingress/main/hosts/0/host
  value: hajimari.${CLUSTER_DOMAIN}
- op: add
  # ~1 here is a magical replacement for /
  path: /spec/values/ingress/main/annotations/cert-manager.io~1cluster-issuer
  value: cloudflare-certificate-issuer
```
</details>

<details><summary>manifests/cluster-systems/default/apps/hajimari-app-config-patch.yaml</summary>

```yml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: hajimari-app

spec:
  values:
    hajimari:
      defaultEnable: true

      namespaceSelector:
        any: true

      title: "${HAJIMARI_DASHBOARD_TITLE}"

      name: "${HAJIMARI_DASHBOARD_NAME}"

      customApps: []

      groups:
        - name: Development
          links:
            - name: FluxCD
              url: https://fluxcd.io/flux/
```
</details>

Running a local `kustomize build` now looks like:

<details><summary> $ kustomize build ./manifests/cluster-systems/default/apps                                                                                            
 </summary>

```yml
apiVersion: v1
kind: Namespace
metadata:
  name: hajimari-app
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: hajimari-app
spec:
  chart:
    spec:
      chart: hajimari
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: hajimari-helm-repo
        namespace: flux-system
      version: 1.2.0
  interval: 5m
  values:
    hajimari:
      customApps: []
      defaultEnable: true
      groups:
      - links:
        - name: FluxCD
          url: https://fluxcd.io/flux/
        name: Development
      name: ${HAJIMARI_DASHBOARD_NAME}
      namespaceSelector:
        any: true
      title: ${HAJIMARI_DASHBOARD_TITLE}
    ingress:
      main:
        annotations:
          cert-manager.io/cluster-issuer: cloudflare-certificate-issuer
          kubernetes.io/ingress.class: traefik
        enabled: true
        hosts:
        - host: hajimari.${CLUSTER_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
    instanceName: hajimari-ui
       
```
</details>

which is what I wanted.
