### DISCUSSION TITLE
Set context for gitlab commit status

### DISCUSSION THREAD

**Discussion by havard024** [fluxcd/flux2#3168] [Proposals] [answered]
We have a multi env setup using single branch model on gitlab.

We have configured git commit status ref https://fluxcd.io/flux/components/notification/provider/#git-commit-status
The problem we are facing is that each env will override each others commit status.

If we could set the `context` on the gitlab commit status API ref https://docs.github.com/en/rest/commits/statuses#create-a-commit-status 
We could differentiate the status of each env on the same commit

**Comment by kingdonb** [comment]
You should get multiple different checks, one for each Kustomization. If you have multiple different clusters that all have Kustomizations by the same name, you might see this issue. Is that the case for your configuration?

For alerts that surface through a notification provider like Slack, you get a "summary" field which is meant to let you specify which cluster is impacted by the change.

For commit status notifications, I don't think this field has any effect (but you can try it also!)

**Reply by kingdonb** [reply]
This may be a bug or missing feature, if I've understood the situation, please let me know and I'll give it a try to reproduce the issue. Could you put some more detail (screenshot of the message that gets overwritten for example)

**Comment by havard024** [comment]
Sorry for the late reply.

Yes, that's exactly the case, multiple different clusters that all have kustomizations by the same name and same branch (running single branch instead of multi branch)

We are unable to differentiate the commit status from our test cluster vs prod cluster since there is no difference in the names

screenshot of the commit history where the commit status passed
<img width="1284" alt="Screenshot 2022-11-13 at 23 07 20" src="https://user-images.githubusercontent.com/2212037/201546970-1f8f9d0f-6d8c-4022-9e53-4d0dbc22d01e.png">

screenshot after clicking on the commit status from the picture above
<img width="1306" alt="Screenshot 2022-11-13 at 23 07 41" src="https://user-images.githubusercontent.com/2212037/201546972-f8cbc3ba-941a-44e1-ad98-586547ef344d.png">

screenshot after clicking on the checkmark, shows the pipelines that run and the stage "external"
<img width="754" alt="Screenshot 2022-11-13 at 23 07 51" src="https://user-images.githubusercontent.com/2212037/201546977-12af9c4b-71b7-4066-9abe-966e9e06f292.png">

screenshot where I triggered a reconciliation error in our test cluster, both pipelines run, nothing is overwritten, but its not possible to differentiate which cluster failed in gitlab itself. It would be nice if we can get two different commit statuses or be able to name the pipeline / stage somehow
<img width="1296" alt="Screenshot 2022-11-13 at 23 17 10" src="https://user-images.githubusercontent.com/2212037/201547353-fea05a83-f4bf-4535-be83-78934387e529.png">

**Comment by havard024** [comment]
Not sure when it happened, but noticed that we are now getting a different id per commit status

<img width="338" alt="Screenshot 2023-12-22 at 21 49 20" src="https://github.com/fluxcd/flux2/assets/2212037/426b2af8-42d5-4744-a74c-f8c2154524eb">

Is it possible to configure the id to make it more human readable?

**Reply by marhbere-glb** [reply]
We are interested in this relations too

**Reply by Cenness** [reply]
Starting from notification v1.6.0 you can use cel expressions for that:

```
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: gitlab
  namespace: flux-system
spec:
  type: gitlab
  address: https://gitlab/group/repo
  commitStatusExpr: |
    '${CLUSTER_SLUG}'
    + '/' + event.involvedObject.namespace
    + '/' + event.involvedObject.kind.substring(0, 8)
    + '/' + event.involvedObject.name
  secretRef:
    name: gitlab-token
```

**Reply by libredeb** [reply]
> Starting from notification v1.6.0 you can use cel expressions for that:
> 
> ```
> apiVersion: notification.toolkit.fluxcd.io/v1beta3
> kind: Provider
> metadata:
>   name: gitlab
>   namespace: flux-system
> spec:
>   type: gitlab
>   address: https://gitlab/group/repo
>   commitStatusExpr: |
>     '${CLUSTER_SLUG}'
>     + '/' + event.involvedObject.namespace
>     + '/' + event.involvedObject.kind.substring(0, 8)
>     + '/' + event.involvedObject.name
>   secretRef:
>     name: gitlab-token
> ```

How you are used or builded that `CLUSTER_SLUG` environment variable? the [custom-commit-status-messages](https://fluxcd.io/flux/components/notification/providers/#custom-commit-status-messages) documentation says we only have access to flux event object, provider object and alert object but none of them has the cluster information. Is there any way to get that information?

**Reply by Cenness** [reply]
> How you are used or builded that `CLUSTER_SLUG` environment variable? 

It's sent via kustomize postBuild.substitute

Imagine that provider object in /app/flux-alerts/provider.yaml
And then you apply something like
```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-alerts
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./app/flux-alerts
  targetNamespace: flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-repo
    namespace: flux-system
  postBuild:
    substitute:
      CLUSTER_SLUG: "prod"
```
