### DISCUSSION TITLE
HelmRelease rollback query

### DISCUSSION THREAD

**Discussion by DevopsCareer** [fluxcd/flux2#3184] [Q&A] [answered]
Hi,

I have following spec in my HelmRelease
```
 install:
    remediation:
      retries: 1
  upgrade:
    remediation:
      retries: 0
      strategy: rollback
      remediateLastFailure: false
  rollback:
    force: true
    cleanupOnFail: true
    timeout: 15m`
```
The behavior I expect is that POD's try to roll forward but if it cant it should roll back, I do not see roll back keyword anywhere
my helm history shows 
`Upgrade "helm-release-abc" failed: timed out waiting for the condition` with a status as `failure ` as last line 
Pod which was not able to roll forward simply remained in failed state . 
What I am expecting and I do not see happening is :
1. I do not see rollback attempt as keyword in helm history, basically how do I know it tried to deploy but failed and hence it is rolling back
2. If it rolls back -  last line in helm history should be stating  `rolled back` not 
`Upgrade "helm-release-abc" failed: timed out waiting for the condition with a failure `
3. Failed POD's should have been cleaned up but they remain as failed in cluster

Am i missing something in config ? 

If we do this out side helm like rolling restart with a deployment it is same behavior we get , if say you have 2 running pods running on working version and you try to roll out newer version  -  a rolling restart try to bring the the 3rd pod with newer version if it cant it just do not touch existing 2. It keeps terminating and bringing up 3rd pod. 

What is helmrelease rollback function doing differently?
