### DISCUSSION TITLE
Encrypt standalone secrets using SOPs with Azure Key Vault

### DISCUSSION THREAD

**Discussion by benfoster** [fluxcd/flux2#3192] [Q&A]
I have SOPs configured using Azure Key Vault and aad-pod-identity. I am able to successfully decrypt secrets used by my pods.

I would like to follow the same approach to encrypt secrets that are used by other parts of Flux or in pods I do not control, for example, the Slack URL used for alerts.

It seems the only way to specify a decryption provider is via a GitRepository kustomization so I've moved the secret "slack-url.enc.yaml" to `/secrets` and have defined the following kustomization for my environment's cluster:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./secrets
  prune: true
  wait: true
  decryption:
    provider: sops
```

My pods are bound to an Azure identity via the `AzureIdentity` resource. How do I achieve the same thing for these secrets?

[The docs](https://fluxcd.io/flux/components/kustomize/kustomization/#azure-key-vault-secret-entry) suggest that I need to create a secret containing the Azure Service Principal secret and reference this in the decryption field. However, this is exactly what I'm trying to avoid - namely having any secrets manually created in the cluster. Can I not leverage a similar approach used by the Azure Identity binding?
