### DISCUSSION TITLE
kustomization after helmrelease

### DISCUSSION THREAD

**Discussion by chrislin22** [fluxcd/flux2#3196] [Q&A]
Trying find an example of kustomization after helm process. Only found them either before helm or directly applies on k8 manifest.
My guess it will be something like:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
....
spec:
  interval: 10m
  targetNamespace: XXX
  sourceRef:
    kind: HelmRelease
    name: xxx
  path: "./xxx"
  prune: true

```
