### DISCUSSION TITLE
Error creating rolebindings

### DISCUSSION THREAD

**Discussion by craigmunro** [fluxcd/flux2#3203] [Q&A]
We've been successfully using Flux in a multi-tenant cluster for a while now but have come across an issue we can't resolve.

We have the following in a Git repository:

```
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: ignite
  namespace: example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: example
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: example
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: ignite 
roleRef:
  kind: Role 
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
```

And a Kustomization in the namespace like:

```
spec:
  force: true
  interval: 1m0s
  path: example
  prune: true
  serviceAccountName: flux
  sourceRef:
    kind: GitRepository
    name: gke-iac
    namespace: example
  suspend: false
  targetNamespace: example
  validation: server
```

We then get the following:
```
kubectl get kustomizations.kustomize.toolkit.fluxcd.io gke-iac
NAME      AGE   READY   STATUS
gke-iac   44d   False   RoleBinding/example/read-pods namespace not specified, error: roles.rbac.authorization.k8s.io "pod-reader" not found...
```

Creating the same resources directly using the same service account works:
```
kubectl create -f role.yaml --as system:serviceaccount:example:flux
serviceaccount/ignite created
role.rbac.authorization.k8s.io/pod-reader created
rolebinding.rbac.authorization.k8s.io/read-pods created
```

If the Role is added to Git first and then the RoleBinding is added everything works too.

The kustomize controller has the following additional arguments:
```
        - --no-cross-namespace-refs=true
        - --default-service-account=flux
```

We're using Flux v0.35.0 and running on GKE v1.22.12-gke.1200

Are we missing something or is there an issue here?

**Comment by stefanprodan** [comment]
I've tested this on my cluster and works ok:

```yaml
$ flux tree ks apps-sync 
Kustomization/flux-system/apps-sync
├── Namespace/apps
├── ServiceAccount/apps/ignite
├── Role/apps/pod-reader
├── RoleBinding/apps/read-pods
```

My Flux Kustomization is v1beta2 without force nor validation, can you post here the full yaml.

**Comment by craigmunro** [comment]
Thanks for the prompt response.   Removing force and validation didn't make a difference.

Here's the full kustomization yaml:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: "2022-08-29T07:04:34Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 12
  name: gke-iac
  namespace: example
  resourceVersion: "209219971"
  uid: fa2d9580-dce2-4208-8eec-ba2fa791526e
spec:
  force: false
  interval: 1m0s
  path: example
  prune: true
  serviceAccountName: flux
  sourceRef:
    kind: GitRepository
    name: gke-iac
    namespace: example
  suspend: false
  targetNamespace: example
status:
  conditions:
  - lastTransitionTime: "2022-10-12T15:46:12Z"
    message: |
      RoleBinding/prv2-e2-prv-example/read-pods namespace not specified, error: roles.rbac.authorization.k8s.io "pod-reader" not found
    reason: ReconciliationFailed
    status: "False"
    type: Ready
  inventory:
    entries:
    - id: prv2-e2-prv-example_ignite__ServiceAccount
      v: v1
    - id: prv2-e2-prv-example_pod-reader_rbac.authorization.k8s.io_Role
      v: v1
    - id: prv2-e2-prv-example_read-pods_rbac.authorization.k8s.io_RoleBinding
      v: v1
  lastAppliedRevision: feature/test-role/8f27e5ca1d9d7cfcafa81e8b6cb74bcb6c499f75
  lastAttemptedRevision: feature/test-role/8f27e5ca1d9d7cfcafa81e8b6cb74bcb6c499f75
  observedGeneration: 1
```

**Reply by stefanprodan** [reply]
Can you please delete the Kustomization from the cluster then let Flux recreate it? IF it fails the same can you please post here the exact YAMLs from your repo. Given that i can't reproduce it, I suspect the actual YAMLs are different from what you've posted here.

**Reply by craigmunro** [reply]
Kustomization is deployed via Terraform.  I've deleted and re-deployed with no change and double checked the yaml I posted.

One observation - if I grant cluster-admin to the flux SA in this namespace it works.  Given I can manually create the roles with the SA is there something else that Flux requires?

**Reply by stefanprodan** [reply]
Ok so this is an RBAC issue. Flux needs to query all the objects it controls, so `roles.rbac.authorization.k8s.io "pod-reader" not foun` means that it can’t read Roles.

**Reply by craigmunro** [reply]
If I give the serviceaccount flux is using the following role it works:
```
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
```
If I give the serviceaccount flux is using this role it does not work:
```
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
```
In both cases I am able to create the resources manually using the service account directly.
