### DISCUSSION TITLE
Unable to use cron for ACR -  fs-security-constraint error

### DISCUSSION THREAD

**Discussion by joshuadmatthews** [fluxcd/flux2#3209] [General]
When I add a kustomization for registry-credentials-sync like 

```
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata: 
  name: kustomization-registry-credentials-sync
  namespace: flux-system
resources:
- https://github.com/fluxcd/flux2/manifests/integrations/registry-credentials-sync/azure?ref=main
patchesStrategicMerge:
- config-patches.yaml
```

I get the following error

` accumulating resources: accumulation err='accumulating resources from 'https://github.com/fluxcd/flux2/manifests/integrations/registry-credentials-sync/azure?ref=main': URL is a git repository': fs-security-constraint abs /tmp/kustomize-2657075801/manifests/integrations/registry-credentials-sync/azure: path '/tmp/kustomize-2657075801/manifests/integrations/registry-credentials-sync/azure' is not in or below '/tmp/kustomization-2461250258'`

I have multitenancy enforcement disabled, and I am also installing into the same namespace as my fluxConfiguration. Has anyone seen this error or may know what would cause it?
