### DISCUSSION TITLE
How to tackle: Helm upgrade failed: another operation (install/upgrade/rollback) is in progress

### DISCUSSION THREAD

**Discussion by angelbarrera92** [fluxcd/flux2#3238] [Q&A]
Hi team!

I am having random failures while initializing clusters using the same git repository/configuration.

One of the `HelmRelease`s fails almost immediately *(sometimes...)*:
```bash
Helm upgrade failed: another operation (install/upgrade/rollback) is in progress error.
```

**I'm using the latest 0.35.0 version.**

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  timeout: 30m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  interval: 1m
  chart:
    spec:
      chart: external-secrets-operator
      version: 0.5.1
      sourceRef:
        kind: HelmRepository
        name: public
        namespace: flux-system
      interval: 1m
  releaseName: external-secrets-operator
  targetNamespace: kube-system
  storageNamespace: kube-system
  valuesFrom: []
  values: {}
```

Reading: https://fluxcd.io/flux/components/helm/helmreleases/#configuring-failure-remediation ...
I understand that... On the first HelmRelease installation, the remediation method (by default) is uninstalling, right?
But what if it wasn't able to be installed? What does flux then?

What I use to do is access the cluster, then delete the `secret` generated by Helm that hosts the values/release information.
I really want to avoid doing manual operations :)

What is the correct/right way of configuring the `HelmRelease` object to perform the `delete` secret automatically so it could be re-tried for the installation?
