### DISCUSSION TITLE
OCIRepository in an airgap environment

### DISCUSSION THREAD

**Discussion by ntx-ben** [fluxcd/flux2#3239] [Q&A] [answered]
Can an OCI artifact be used with flux in an **airgap** environment? I'm trying it out in a KinD cluster and side-loading the OCI artifact in KinD, however I can see that flux is trying to reach out to the registry to fetch it instead, and fail since I didn't provide it with the registry credentials. 

```
kind load docker-image registry.gitlab.com/XXXXXX:latest

Image: "registry.gitlab.com/XXXXXXX:latest" with ID "sha256:2840428eadb4e56095f4ec8a766209a59a18e4f3efb7c0490d736fba95b92869" not yet present on node "kind-control-plane", loading...
```

My OCIRepository:
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: XXXXXXX
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: latest
  # secretRef:
  #   name: gitlab-registry
  url: oci://registry.gitlab.com/XXXXXXX
```

Result:
```
lastTransitionTime: "2022-10-21T13:35:29Z"
message: 'failed to determine artifact digest: GET https://gitlab.com/jwt/auth?scope=repository%!A(MISSING)XXXXXXX%!A(MISSING)pull&service=container_registry:
    DENIED: access forbidden' 
observedGeneration: 1
reason: OCIArtifactPullFailed    
status: "True"
type: FetchFailed
```

Any help and suggestions appreciated.
