### DISCUSSION TITLE
ImageDeploymentVerification CRD

### DISCUSSION THREAD

**Discussion by dudo** [fluxcd/flux2#3241] [Proposals] [answered]
While asking a question in [Slack](https://cloud-native.slack.com/archives/CLAJ40HV3/p1666297219118409), we realized that we can't really get a handle on an image change via the `Alert` mechanism. My understanding is that deployments follow a flow of 

ImageRepository -> ImagePolicy -> ImageUpdateAutomation -> GitRepository

I enabled info notifications for everything, and just watched... and I was never alerted of a change in image tag. The closest you get is GitRepository which shows the commit that triggers an image build, but then is quickly shadowed by the commit from ImageUpdateAutomation. ImagePolicy is the only thing that shows image tags, but it's kind of just noise since it alerts regardless of change - just most recent version detected.

I'd proposed that we create an *ImageDeploymentVerification* CRD that runs whenever the image of a Deployment changes. Having a handle on the *change* (and ultimately successful application) of a Deployment feels like the only useful thing to see info on (vs error for everything else).

**Comment by stefanprodan** [comment, marked as answer]
> I enabled info notifications for everything, and just watched... and I was never alerted of a change in image tag. 

Please see here how to configure the commit template to display all the image tags that were patched in Git: https://fluxcd.io/flux/components/image/imageupdateautomations/#commit-message-with-template-functions. Once you set the commit template and an alert for `ImageUpdateAutomation` you'll see in Slack what images are updated, in which files, etc.

**Reply by dudo** [reply]
I'll check that out, thank you. Do you think there's room for improvement to the default behavior?

**Reply by dudo** [reply]
So, I'm not using numeric image tags, not that it should matter. Just got this

![image](https://user-images.githubusercontent.com/2963800/197349017-b037f87c-c22e-4038-9e7b-a1eb6be1ee18.png)

Using 

```yaml
commit:
  messageTemplate: |
    Automated image update

    Images:
    {{ range $image, $_ := .Updated.Images -}}
     - {{ $image }}
    {{ end -}}
```

With ImagePolicy

```sh
k get imagepolicy -A                                            
NAMESPACE     NAME                        LATESTIMAGE
flux-system   graphql-federated-gateway   ghcr.io/compada/graphql-federated-gateway:main-8fa873f-1666406488
```

Is something misconfigured? Also, is there a variable for the previous git sha (that triggered the build)? Thanks!

**Reply by stefanprodan** [reply]
Can you please try:

```yaml
commit:
  messageTemplate: |
    Automated image update

    Images:
    {{ range $image, $url := .Updated.Images -}}
     - {{ $image }} {{ $url}}
    {{ end -}}
```
