### DISCUSSION TITLE
Timeout HelmRelease

### DISCUSSION THREAD

**Discussion by DevopsCareer** [fluxcd/flux2#3243] [Q&A]
My Helm Chart timeout, sometime wait as deployments are coming up and they take longer than x seconds to come up.
Is there a way I can increase the timeout so that my HelmRelease charts do not timeout while waiting for the deployments to come up?

essentially I have higher terminationGracePeriod and higher initial_delay_seconds on my HelmRelease ?

**Comment by pcharlan** [comment]
Perhaps add something like this to your Flux kustomization config?
```
spec:
  install:
    timeout: 20m
  upgrade:
    timeout: 20m
```
