### DISCUSSION TITLE
kustomize-controller: ignored health checks

### DISCUSSION THREAD

**Discussion by seaneagan** [fluxcd/flux2#325] [Proposals]
It may be the case sometimes that one of your health checks is failing, and you have identified that the issue is low impact, so you don't want the health check to stop the progress of the deployment, so you want the `Ready` condition to not be marked `False` because of the failure. However, rather than turning off the health check you may want to leave it for observability in order to debug the failure going forward. In this case it would be useful to mark the health check as ignored. This would be similar to the helm test ignore functionality in the helm-controller. It would be useful to separately configure whether to ignore [Failed vs InProgress](https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus#statuses) status.

API proposal:

```yaml
  healthChecks:
    - kind: Deployment
      name: healthy
    - kind: Deployment
      name: unhealthy
      ignoreFailed: true
    - kind: Deployment
      name: unhealthy
      ignoreInProgress: true
```

Then all health checks (including ignored ones) can be exposed via a new status condition e.g. `Healthy`, while the `Ready` condition will only be False upon non-ignored health check failures. The `Healthy` condition could potentially still be kept up to date even if the kustomization is `suspend`ed.

If #324 is implemented, there would need to be a way to specify the default health checks for resources not explicitly included in the list. For example:

Check all resources, ignore specific failure:

```yaml
  healthChecks:
    default:
      enable: true # default true as proposed in #324
    custom:
      - kind: Deployment
        name: unhealthy
        ignoreFailed: true
```

Wait for a single resource:

```yaml
  healthChecks:
    default:
      enable: false
    custom:
      - kind: Deployment
        name: healthy
```

Ignore all failed and in progress:

```yaml
  healthChecks:
    default:
      ignoreFailed: true
      ignoreInProgress: true
```
