### DISCUSSION TITLE
source-controller: define source dependencies

### DISCUSSION THREAD

**Discussion by seaneagan** [fluxcd/flux2#326] [Proposals] [answered]
Sometimes kustomizations need to combine manifests from multiple git repositories. For example one may keep most of their manifests for a given cluster type in one repo, while each cluster instance of this type contains parameters to patch into the cluster type manifests in its own repo. When using `kustomize` as a CLI this can be done by cloning the dependency repositories to predictable paths within the dependent repository checkout.

*Note:* while kustomizations can reference remote git refs in `resources`, this is highly repetitive and last time i checked i don't think caching was fully implemented. It also doesn't allow for automation of updates when the dependencies change.

This could be supported by allowing sources to specify dependencies including where to store them within the dependent source artifact. For example:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: type
# ...
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: instance
spec:
  dependsOn:
    - name: type
      targetPath: dependencies/type
  # ...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: deps
spec:
  sourceRef:
    kind: GitRepository
    name: instance
  path: . # < kustomization references `dependencies/type`
  # ...
```

This could also be used to potentially solve the following limitation ([mentioned here](https://toolkit.fluxcd.io/guides/helmreleases/#git-repository) with sourcing Helm charts from Git:

> Chart dependencies must be committed to Git, as the source-controller does not attempt to download them. This limitation may be removed in a future release.

# Alternatives

* Use [KPT subpackages](https://googlecontainertools.github.io/kpt/concepts/packaging/#subpackages). KPT in general requires one to commit changes (such as dependency updates) back to git in order to consume them from something like the GitOps Toolkit, unless the GitOps Toolkit added a kpt-controller which ran KPT commands on a source Kpt package and applied them. Automation of dependency updates could perhaps be implemented through something similar to the [image update automation](https://github.com/fluxcd/toolkit/discussions/107) except targeted at updating [Kptfile dependencies](https://github.com/GoogleContainerTools/kpt/blob/master/pkg/kptfile/pkgfile.go#L43).
* Use [git subtree](https://github.com/git/git/blob/master/contrib/subtree/git-subtree.txt) (see above KPT link for limitations) or [git submodules](https://www.git-scm.com/book/en/v2/Git-Tools-Submodules).

**Comment by stefanprodan** [comment, marked as answer]
When using remote bases, kustomize-controller does not support private repos, your proposal would solve this along with the caching problem.

I don't think `dependsOn ` is the right term to describe this features, my proposal is:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: app
# ...
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: infra
spec:
  include:
    - name: app
      namespace: gotk-system
      from: "./deploy"
      to: "./bases/apps/app"
# ...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infra
spec:
  sourceRef:
    kind: GitRepository
    name: infra
  path: ./clusters/prod # < kustomization.yaml references `../bases/apps/app`
  # ...
```

**Reply by autarchprinceps** [reply]
Joining together two gits on a subdirectory is nice, but what we typically use to modify a central template for each environment is yaml merging or JSON 6902 Patch files. This modifies a single Kubernetes resource from two source files.
In Fluxv1 it would look something like this:
base:
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
...
  values:
    dashboard:
      enabled: true
      ingress:
        annotations:
          kubernetes.io/ingress.class: traefik
          kubernetes.io/tls-acme: "true"
          traefik.ingress.kubernetes.io/frontend-entry-points: http,https
          traefik.ingress.kubernetes.io/redirect-entry-point: https
          ingress.kubernetes.io/auth-response-headers: X-Userinfo, X-Id-Token, X-Access-Token,Authorization
          ingress.kubernetes.io/auth-type: forward
```
preprod/patch:
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  values:
    dashboard:
      domain: "traefik.preprod.example.com"
      ingress:
        annotations:
          ingress.kubernetes.io/auth-url: https://eas.preprod.example.com/...
```
And the same in a prod patch, and we can use the same base yaml to create different environments. Yes, like this proposal suggests, it would naturally be nice to then put the base into its own "submodule" like source definition, but we still want to not just include it, but patch it. 

Ultimately, it would be nice to be able to give Kustomization resource some level of templating, parameterization or something like that, to enable variation on the same source. We are not opposed to changing how we do this, but I think the fundamental issue of having a generalised base and wanting to include, yes, but also perhaps extend, overwrite and modify it, would be a really great feature, and I would say it belongs in that CRD, if anywhere. It could be used on the same source, or even better on different ones, with this proposal.

**Reply by stefanprodan** [reply]
You would place the `kustomization.yaml` along with the patches in the main repo, then use the includes to populate the base dir.

**Reply by raffis** [reply]
I like the `include` proposal, in our case it would do it. Right now I have the problem that I have a base which I want in a separate git repository because only some people should have the permission to modify it. And as I see this there is currently no way doing it right? kustomize remote resources and git sub modules don't work. 
Having the include on the source spec is more flexible, also it's not required to update sub modules in git repos.

**Reply by springroll12** [reply]
The `include` proposal seems like it should account for most scenarios (excluding submodules). Is there any progress on implementation? This is the biggest blocker to adopting fluxv2 for organizations employing multiple repos with kustomize remote bases.

**Reply by raffis** [reply]
@stefanprodan Will this proposal by any chance be implemented? Or something which would be accepted as contribution?

**Reply by phillebaba** [reply]
We had a discussion about this at the community meeting two weeks ago and there seemed to be some differing opinions on this matter. @squaremo thought that this may be a complex solution for the problem it solved. I am a bit on the fence regarding this question. On the one hand it introduces a flux custom solution which will not work locally out of the box, on the other hand I currently do not have a better solution.

**Reply by stefanprodan** [reply]
> On the one hand it introduces a flux custom solution which will not work locally out of the box, on the other hand I currently do not have a better solution.

This solution works locally by using git submodules and in-cluster by replacing the submodules with `include`. I see the `include` feature as a drop-in replacement for submodules. You would still use submodules to test your kustomization locally and in CI, but in your production cluster you would use Flux's `include` to pull the manifests from different repos and avoid the Git SaaS limitation where a deploy key can't be used for more than one repo.

**Reply by nlamot** [reply]
Hi @stefanprodan , is there an update on this? This is a very important for our adoption of flux v2 and I would like to work on this feature if it would be (if implemented correctly of course) accepted as a contribution.

We currently use flux v1 and do use kustomize references to external private repositories that are very difficult to remove.

**Reply by stefanprodan** [reply]
I think @phillebaba is working on this? In the meantime you can use git submodules, see https://toolkit.fluxcd.io/components/source/gitrepositories/#git-submodules

**Comment by vladimirfx** [comment]
I think 2 options are needed:
1. Git submodules (https://github.com/fluxcd/source-controller/issues/169)
2. Authentication support for remote resources in kustomization. 

We use both but submodules more often. 

In our practice we compose fleet repository from cluster wide manifests and application/team manifests tracked in external repositories. In such scenario fleet repository contains main application kustomization in which external manifests is used as base or referenced somehow else.
As so we need flat file structure of fleet repository with all submodules inited and updated.
Submodules makes ops team work easier and more transparent because what is applied is visible and controlled in flat file structure.
Remote kustomize resources is useful for rarely changed external manifests (such case is often covered by Helm charts).

**Reply by stefanprodan** [reply]
@vladimirfx we have no plans on adding Git auth to kustomize-controller as the reconciler shouldn't deal with Git or any other type of source, that's source-controller responsibility.

Instead of Git modules, you would add each submodule repo to the cluster as `GitRepository` objects, then use `include` so that the main source will contain all the submodules manifests. Please see my proposal from above, will this work for you?

**Reply by vladimirfx** [reply]
> @vladimirfx we have no plans on adding Git auth to kustomize-controller as the reconciler shouldn't deal with Git or any other type of source, that's source-controller responsibility.

Yep, I agree - is conceptually clearer solution.
 
> Instead of Git modules, you would add each submodule repo to the cluster as `GitRepository` objects, then use `include` so that the main source will contain all the submodules manifests. Please see my proposal from above, will this work for you?

Solution above is more complex to maintain than submodules one. But it is definitely useful for advanced scenarios in which effective source should be composed from repositories with different update rules. For example, some subpath is tracking server tag but other is hardcoded revision.

I think submodules is useful because of simplicity and transparency for dev/op engineers - apply exactly what you see. It is sense of security especially for production environment. For prod I definitely want the commit that updates target revision. Yes, it is possible with your solution but it is way more indirect and complex for simple sub dir update.

**Reply by stefanprodan** [reply]
How would you set up authentication? GitHub doesn't allow the same deploy key to be reused, source-controller will use the main repo credentials to pull the submodules and those will fail.

**Reply by vladimirfx** [reply]
> How would you set up authentication? GitHub doesn't allow the same deploy key to be reused, source-controller will use the main repo credentials to pull the submodules and those will fail.

We use HTTPS/Basic - so simplest implementation can reuse credentials from root repo. 
For deployment keys lookup-table-like secret can be used (repo-to-key) which can be conveniently resumed in many source controllers (something similar to SOPS secrets).

**Reply by vladimirfx** [reply]
Additionally we implement another workaround - attach SSH keys to kustomize-controller that manage distinct namespace. So that controller can use `ssh:git@somhost` resources with SSH-based authorization.
But it is workaround... with all its drawbacks... So very waiting for solution.

**Reply by raffis** [reply]
> How would you set up authentication? GitHub doesn't allow the same deploy key to be reused, source-controller will use the main repo credentials to pull the submodules and those will fail.

If the credentials are from a user (for example dedicated gitops github user), not deploy keys it should work.

**Reply by bob-rohan** [reply]
> we have no plans on adding Git auth to kustomize-controller as the reconciler shouldn't deal with Git or any other type of source, that's source-controller responsibility.
> 

Kustomize-controller does currently deal with Git for kustomize remote bases on public repos. 

@stefanprodan Would it be acceptable to supply a credentials as a secret ref to the Kustomization CRD, which would be propagated to the file system pre buildKustomization along with supporting git/SSH config??

**Comment by vladimirfx** [comment]
We build workaround that uses kustomize (go-get) ability to fetch external resources. Of course it has drawbacks:
 - auth token to access external resources is stored in plain text
 - content of customized resources not transparent when working with fleet repo

**Comment by freefood89** [comment]
Hello-

I was wondering what the status of this discussion is.

I'm really looking forward to adopt flux v2 for multitenancy, but I depend on git submodules to manage shared kustomize bases for various teams. So far with flux v1 I've been using flux.yaml file to pull those submodules using ssh keys that are registered with my ci bot user (instead of repo deploy key).

Is there any way I can help?

**Comment by stefanprodan** [comment]
## Git submodules
 
Starting with flux2 v0.12 you can bootstrap with `--recurse-submodules` and create GitRepositories by enabling Git submodules:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: repo-with-submodules
  namespace: default
spec:
  interval: 1m
  url: https://github.com/<organization>/<repository>
  secretRef:
    name: https-credentials
  ref:
    branch: main
  recurseSubmodules: true
  gitImplementation: go-git
---
apiVersion: v1
kind: Secret
metadata:
  name: https-credentials
  namespace: default
type: Opaque
data:
  username: <Username>
  password: <Token or Password>
```

Note that deploy keys can't be used to pull submodules from private repositories as GitHub and GitLab doesn't allow a deploy key to be reused across repositories. You have to use either HTTPS token-based authentication, or an SSH key belonging to a user that has access to the main repository and all its submodules.

More info [here](https://toolkit.fluxcd.io/components/source/gitrepositories/#git-submodules).
