### DISCUSSION TITLE
Pick latest build image always

### DISCUSSION THREAD

**Discussion by marrip** [fluxcd/flux2#3265] [Q&A]
Hi,

I have a flux2 deployment running and want flux to automatically update the image I am running in the test environment. My images can be tagged with anything from `<branch>-<sha>` to semver tags. I created a `ImagePolicy` such as :

```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: test
  namespace: test
spec:
  imageRepositoryRef:
    name: test
    namespace: test
  policy:
   alphabetical:
      order: asc
```

which is clearly not what I want as commit shas are random and I always want to last image built not the first on the list deployed into the cluster. Any pointers or ideas?
