### DISCUSSION TITLE
How do intervals and timeouts work?

### DISCUSSION THREAD

**Discussion by FelipeEmerim** [fluxcd/flux2#3266] [Q&A] [answered]
Hi,

Thanks for the amazing tool.

Say we have the following manifest:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tooling
  namespace: flux-system
spec:
  interval: 60m0s
  wait: true
  timeout: 3m0s
  retryInterval: 2m0s
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
    namespace: flux-system
  dependsOn:
    - name: service-mesh
  path: "/tooling/lab/tooling"
```

What do the options interval, timeout and retryTimeout do? I read the docs but still cannot understand. If the timeout is reached, will flux stop applying the Kustomization? Will it retry?

Should the timeout be lower than the interval?

When does retryInterval take effect?

Is the timeout only considered for reconcilliations not triggered by git changes? (Manual changes).

Should the timeout be the longest it can possibily take to apply the changes?

There are intervals in some other manifests like Git and helm sources. Are those independent from the values in the Kustomization?
