### DISCUSSION TITLE
Support image automation marker annotations

### DISCUSSION THREAD

**Discussion by jacekn** [fluxcd/flux2#3272] [Proposals]
Currently image automation markers are configured as yaml comments, for example:
```
spec:
  containers:
  - name: podinfod
    image: ghcr.io/stefanprodan/podinfo:5.0.0 # {"$imagepolicy": "flux-system:podinfo"}
```
This method has some downsides:
1. It's harder to programmatically parse yaml documents and extract markers (libraries often ignore comments)
2. It's not possible to write policies using tools like Open Policy Agent that check automation markers
3. It's harder to programmatically generate manifests (see point 1 for explanation)
4. Automation marker info is lost when manifests are applied to k8s. In practice this means it's impossible to expose information about automation markers via prometheus metrics or using other methods

I'd like to propose that the automation markers can be set as annotations. That way they become first class citizens in the manifest documents. They will be easy to parse programmatically, validate and expose using observability tools.

For example the following should be very easy to understand and could achieve exactly the same results as comments:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  annotations:
    fluxcd.io/image-automation: '{"$imagepolicy": "flux-system:podinfo", "container": "podinfo"}'
spec:
  template:
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo:5.0.0
```
