### DISCUSSION TITLE
Using one Flux instance to deploy workloads on remote clusters with matching kubeconfig

### DISCUSSION THREAD

**Discussion by tuxicorn** [fluxcd/flux2#3280] [Q&A]
I am trying to configure multiple K8s clusters via a single Flux instance and a single repo with the following process. Please note cluster provisioning is handled outside of Flux and without using CAPI.  

The following example installs flux on the management cluster and sync with the repo.
Once Flux is setup, I clone the repo and add sync files for it to deploy workloads on the remote staging cluster using a kubeconfig secret.

When I omit the kubeconfig from the staging-sync.yaml, all get deployed on the management cluster (which is logic but not what I want to achieve), and as soon as i add the kubeconfig in spec, I get the following error: `Kustomization/flux-system/apps dry-run failed, error: no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1beta2"` and i can't get it work.

But in [this](https://github.com/fluxcd/flux2/discussions/2258) discussion from January, a member of the Flux project stated that targeting remote clusters using kubeconfig is fully supported.

```sh
# Store Gitlab known_hosts file in a variable
locals {
  known_hosts = "${file("${path.module}/known_hosts")}"
}

# Generate an SSH keypair
resource "tls_private_key" "main" {
  algorithm = "RSA"
  rsa_bits  = "4096"
}

# Generate manifests
data "flux_install" "main" {
  target_path = var.target_path
}

data "flux_sync" "main" {
  target_path = var.target_path
  url         = "ssh://git@${var.gitlab_base_url}:2222/${var.gitlab_owner}/${var.repository_name}.git"
  branch      = var.branch
}

# Create Namespace for Flux
resource "kubernetes_namespace" "flux_system" {
  metadata {
    name = "flux-system"
  }

  lifecycle {
    ignore_changes = [
      metadata[0].labels,
    ]
  }
}

# Split multi-doc YAML
data "kubectl_file_documents" "install" {
  content = data.flux_install.main.content
}

data "kubectl_file_documents" "sync" {
  content = data.flux_sync.main.content
}

# Convert documents list to include parsed yaml data
locals {
  install = [for v in data.kubectl_file_documents.install.documents : {
    data : yamldecode(v)
    content : v
    }
  ]
  sync = [for v in data.kubectl_file_documents.sync.documents : {
    data : yamldecode(v)
    content : v
    }
  ]
}

# Apply manifests on the cluster
resource "kubectl_manifest" "install" {
  for_each   = { for v in local.install : lower(join("/", compact([v.data.apiVersion, v.data.kind, lookup(v.data.metadata, "namespace", ""), v.data.metadata.name]))) => v.content }
  depends_on = [kubernetes_namespace.flux_system]
  yaml_body  = each.value
}

resource "kubectl_manifest" "sync" {
  for_each   = { for v in local.sync : lower(join("/", compact([v.data.apiVersion, v.data.kind, lookup(v.data.metadata, "namespace", ""), v.data.metadata.name]))) => v.content }
  depends_on = [kubernetes_namespace.flux_system]
  yaml_body  = each.value
}

# Generate a Kubernetes secret with the GitLab credentials
resource "kubernetes_secret" "main" {
  depends_on = [kubectl_manifest.install]

  metadata {
    name      = data.flux_sync.main.secret
    namespace = data.flux_sync.main.namespace
  }

  data = {
    identity       = tls_private_key.main.private_key_pem
    "identity.pub" = tls_private_key.main.public_key_pem
    known_hosts    = local.known_hosts
  }
}

# Create a repository
resource "gitlab_project" "main" {
  name                   = var.repository_name
  visibility_level       = var.repository_visibility
  initialize_with_readme = true
  default_branch         = var.branch
}

# Deploy generated SSH public key to Gitlab
resource "gitlab_deploy_key" "main" {
  title   = "flux"
  project = gitlab_project.main.id
  key     = tls_private_key.main.public_key_openssh

  depends_on = [gitlab_project.main]
}

# Deploy generated manifests to Gitlab project
resource "gitlab_repository_file" "install" {
  project        = gitlab_project.main.id
  branch         = gitlab_project.main.default_branch
  file_path      = data.flux_install.main.path
  content        = base64encode(data.flux_install.main.content)
  commit_message = "Add ${data.flux_install.main.path}"

  depends_on = [gitlab_project.main]
}

resource "gitlab_repository_file" "sync" {
  project        = gitlab_project.main.id
  branch         = gitlab_project.main.default_branch
  file_path      = data.flux_sync.main.path
  content        = base64encode(data.flux_sync.main.content)
  commit_message = "Add ${data.flux_sync.main.path}"

  depends_on = [gitlab_repository_file.install]
}

resource "gitlab_repository_file" "kustomize" {
  project        = gitlab_project.main.id
  branch         = gitlab_project.main.default_branch
  file_path      = data.flux_sync.main.kustomize_path
  content        = base64encode(data.flux_sync.main.kustomize_content)
  commit_message = "Add ${data.flux_sync.main.kustomize_path}"

  depends_on = [gitlab_repository_file.sync]
}

# Create the kubeconfig secret for the staging cluster
resource "kubernetes_secret" "kubeconfig_staging" {

  metadata {
    name      = "kubeconfig-staging"
    namespace = data.flux_sync.main.namespace
  }

  data = {
    "value.yaml" = base64decode(data.terraform_remote_state.downstream_cluster.outputs.kubeconfig)
  }
}
```

## Repository structure after pushing new files

```sh
.
├── apps # Added files after Flux is setup
│   ├── base
│   │   └── podinfo
│   │       ├── kustomization.yaml
│   │       ├── namespace.yaml
│   │       └── release.yaml
│   └── staging
│       ├── kustomization.yaml
│       └── podinfo-values.yaml
├── clusters
│   ├── management
│   │   ├── flux-system # Files generated by Terraform flux provider
│   │   │   ├── gotk-components.yaml
│   │   │   ├── gotk-sync.yaml
│   │   │   └── kustomization.yaml
│   │   ├── kustomization.yaml
│   │   └── staging-sync.yaml
│   └── staging # Added files after Flux is setup
│       ├── apps.yaml
│       └── infrastructure.yaml
├── infrastructure # Added files after Flux is setup
│   ├── kustomization.yaml
│   ├── nginx
│   │   ├── kustomization.yaml
│   │   ├── namespace.yaml
│   │   └── release.yaml
│   ├── redis
│   │   ├── kustomization.yaml
│   │   ├── kustomizeconfig.yaml
│   │   ├── namespace.yaml
│   │   ├── release.yaml
│   │   └── values.yaml
│   └── sources
│       ├── bitnami.yaml
│       ├── kustomization.yaml
│       └── podinfo.yaml
└── README.md
```

### clusters/management/flux-system

Note, I omitted the gotk-componenets.yaml intentionally because of it's length.

```sh
# clusters/management/flux-system/gotk-sync.yaml

# This manifest was generated by flux. DO NOT EDIT.
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: URL
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/management
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

```sh
# clusters/management/flux-system/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-sync.yaml
- gotk-components.yaml
```

### clusters/management
Those are the files that target the remote staging cluster using the kubeconfig for that cluster.

```sh
# clusters/management/staging-sync.yaml

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: URL
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  kubeConfig:
    secretRef:
      name: kubeconfig-staging
  timeout: 2m10s
  path: ./clusters/staging/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

```sh
# clusters/management/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- staging-sync.yaml
```

### apps, infrastructure and clusters/staging

Those folders are taken from https://github.com/fluxcd/flux2-kustomize-helm-example as a test to deploy workloads.

**Comment by stefanprodan** [comment]
The staging-sync.yaml overrides the root objects. Rename the GitRepository and Kustomization to `staging` from `flux-system`.

Also delete `clusters/management/kustomization.yaml` this makes Flux uninstall itself and nukes the whole cluster.

**Reply by tuxicorn** [reply]
I removed the `clusters/management/kustomization.yaml`, and changed the staging-sync.yaml to the following content and still get the same error. Any idea ?
![image](https://user-images.githubusercontent.com/66470559/199978708-354f810e-be6c-4efc-b01c-0f65c229143b.png)
![Untitled](https://user-images.githubusercontent.com/66470559/199979384-23e79b6b-c368-4d22-8684-68b3fad7ee3b.png)
```sh
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: URL
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 10m0s
  kubeConfig:
    secretRef:
      name: kubeconfig-staging
  timeout: 2m10s
  path: ./clusters/staging/
  prune: true
  sourceRef:
    kind: GitRepository
    name: staging
   ```

**Reply by stefanprodan** [reply]
All Flux objects which reconcile staging must have `kubeConfig`. You can't take a setup made for a cluster where Flux is suppose to run and move it to a cluster where Flux is not running.

**Reply by tuxicorn** [reply]
Thank you for your answers :) I am new to flux and I struggle a bit, so I'm sorry if my questions seem obvious.  Are you referencing `clusters/staging/infrastructure.yaml` ? I added the kubeconfig as well but still same error. 

```sh
# clusters/staging/infrastructure.yaml

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  kubeConfig:
    secretRef:
      name: kubeconfig-staging
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: staging
  path: ./infrastructure
  prune: true
  ```

**Reply by stefanprodan** [reply]
You need to remove the `kubeConfig` from the `Kustomization/staging`, as this applies Flux objects and the remote clusters don't have Flux installed on it. The [flux2-kustomize-helm-example](https://github.com/fluxcd/flux2-kustomize-helm-example) is not made for remote clusters you need to rethink the structure to fit your use case.

**Reply by tuxicorn** [reply]
I find it pretty hard to get documentation about remote cluster management without CAPI. could you send me a link about that? I've been trying to find information on how to do this for more time than I would like to admit.

**Reply by stefanprodan** [reply]
Here are the docs:
- https://fluxcd.io/flux/components/kustomize/kustomization/#remote-clusters--cluster-api
- https://fluxcd.io/flux/components/helm/helmreleases/#remote-clusters--cluster-api

Hopefully we'll get some time next year to create an example repo for remote clusters, to make things easier to follow.

**Reply by tuxicorn** [reply]
Thank you, I was already in that docs but wasn't very clear to me! Meaning that I can't use a single infrastructure and apps folder for both staging and prod because all Helm releases also need a kubeconfig in spec ?

**Reply by stefanprodan** [reply]
Yeap you need to patch the `kubeConfig` in each overlay and set the correct secret name

**Reply by tuxicorn** [reply]
Thank you very much!

**Reply by stefanprodan** [reply]
Can you please open an issue in https://github.com/fluxcd/flux2-kustomize-helm-example for us to create an example for remote clusters.

**Reply by tuxicorn** [reply]
Sorry to answer so late, I've been sick. And yes sure I'll open an issue now to request an example. I will try doing it myself this week and might come back to ask for some help in case I can't make it work.

**Comment by tuxicorn** [comment]
I tried the following as a test:
```sh
.
├── clusters
│   ├── management
│   │   ├── flux-system
│   │   │   ├── gotk-components.yaml
│   │   │   ├── gotk-sync.yaml
│   │   │   └── kustomization.yaml
│   │   └── staging-sync.yaml
│   └── staging
│       └── infrastructure.yaml
├── infrastructure
│   ├── kustomization.yaml
│   ├── redis
│   │   ├── kustomization.yaml
│   │   ├── kustomizeconfig.yaml
│   │   ├── namespace.yaml
│   │   ├── release.yaml
│   │   └── values.yaml
│   └── sources
│       ├── bitnami.yaml
│       ├── kustomization.yaml
│       └── podinfo.yaml
└── README.md
```
### clusters/management
```yaml
#clusters/management/staging-sync.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: <gitlab-url>
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 2m10s
  path: ./clusters/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: staging
```

### clusters/staging
```yaml
#clusters/staging/infrastructure.yaml

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./infrastructure/staging/
  prune: true
  sourceRef:
    kind: GitRepository
    name: staging
  kubeConfig:
    secretRef:
      name: kubeconfig-staging
```
     
### infrastructure/staging
    
```yaml
  #infrastructure/staging/redis/release.yaml

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
spec:
  kubeConfig:
    secretRef:
      name: kubeconfig-staging
  releaseName: redis
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "16.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: redis-values
```

```yaml
#infrastructure/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis
```

I'm keeping only the redis folder from https://github.com/fluxcd/flux2-kustomize-helm-example in `infrastructure/staging` as a test just to try to make it work for using the kubeconfig but i still get this error: 
```sh
HelmRelease/redis/redis dry-run failed, error: no matches for kind "HelmRelease" in version "helm.toolkit.fluxcd.io/v2beta1" Namespace/redis created
```
Could you point me out what I'm missing? Thank you very much in advance!
