### DISCUSSION TITLE
Image Automation doesn't work (no updates made)

### DISCUSSION THREAD

**Discussion by woj-tek** [fluxcd/flux2#3283] [Q&A]
I have quite simple use case - deploying self-contained in docker image static jekyll website. Basic setup works just fine. I wanted to update the process so I followed Automate image updates guide (https://fluxcd.io/flux/guides/image-update/#configure-image-update-for-custom-resources): created repository, created image policy and create imageautomation. Afterwards, Flux reconciled the changes pushed to the repository and I get all three items there:

```
$ flux get image all
NAME                     	LAST SCAN                	SUSPENDED	READY	MESSAGE
imagerepository/projectorg	2022-11-04T20:19:04+01:00	False    	True 	successful scan, found 3 tags

NAME                 	LATEST IMAGE                                      	READY	MESSAGE
imagepolicy/projectorg	project/project.org-jekyll-website:latest-1667587959	True 	Latest image tag for 'project/project.org-jekyll-website' resolved to: latest-1667587959

NAME                             	LAST RUN                 	SUSPENDED	READY	MESSAGE
imageupdateautomation/flux-system	2022-11-04T20:18:28+01:00	False    	True 	no updates made
```

As you can see, repository scan and image policy seems to work fine, but there are no changes made to the repository (and thus nothing is updated). I included "image policy marker" in image configuration in deployment file, and it matches the policy:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectorg-jekyll
  namespace: projectorg-jekyll
  labels:
    app: projectorg-jekyll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectorg-jekyll
  template:
    metadata:
      labels:
        app: projectorg-jekyll
    spec:
      containers:
      - name: projectorg-jekyll
        image: "project/project.org-jekyll-website:latest" # {"$imagepolicy": "flux-system:projectorg"}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
```

ImageUpdateAutomation is also straighforward:
```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./clusters/project-test-prod1
    strategy: Setters
```

Repo structure is rather straighforward:
```
├── clusters
│   └── project-test-prod1
│       ├── apps.yaml
│       ├── common.yaml
│       ├── flux-system
│       │   ├── gotk-components.yaml
│       │   ├── gotk-sync.yaml
│       │   └── kustomization.yaml
│       └── flux-system-automation.yaml
├── infra
│   ├── apps
│   │   ├── kustomization.yaml
│   │   ├── projectorg-jekyll
│   │   │   ├── deployment.yaml
│   │   │   ├── image-policy.yaml
│   │   │   ├── image-registry.yaml
│   │   │   ├── ingress.yaml
│   │   │   ├── kustomization.yaml
│   │   │   ├── namespace.yaml
│   │   │   └── service.yaml
```

Any hints what to check would be very appreciated :-)

(There is similar thread: https://github.com/fluxcd/flux2/discussions/2545 but there is no solution there)

**Comment by heyrun** [comment]
@Woj-tek can you check your path? I had a similar issue and it turns out that my path was wrong. Your path should point to where the manifests are located. Hope it helps

**Reply by woj-tek** [reply]
Hmm, I'm now looking at the ImageUpdateAutomation / (`clusters/project-test-prod1/flux-system-automation.yaml`) and it has `spec.update.path` set to `./clusters/project-test-prod1` but the Deployment with "image policy marker" is in `infra/apps/projectorg-jekyll`.

It would seem that ImageUpdateAutomation operating on own fluxcd repository (self) should be in `flux-system` repository and it covers complete repository though - how should we handle updates in different paths?

**Comment by leszczynskimikolaj** [comment]
@woj-tek can you show your ImagePolicy resource too?

**Reply by woj-tek** [reply]
```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: projectorg
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: ^latest-(?P<ts>[0-9]+)
  imageRepositoryRef:
    name: projectorg
  policy:
    numerical:
      order: asc
```

And ImageRepository for completnes:
```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: projectorg
  namespace: flux-system
spec:
  image: project/prject.org-jekyll-website
  interval: 5m0s
```

**Reply by leszczynskimikolaj** [reply]
Could you also link GitRepository flux-system ?

**Reply by woj-tek** [reply]
Hmm, there isn't such as the source is the repository itself?

**Reply by leszczynskimikolaj** [reply]
AFAIK you should have autogenerated file in gotk-sync.yaml with
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch:<your branch>
  secretRef:
    name: flux-system
  url: <your repo>
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: <path to your cluster folder>
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

**Reply by woj-tek** [reply]
I guess this would be this one then (`cluster/project-test-prod1/apps.yaml`):
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/apps
  prune: true
  validation: client
```

**Reply by woj-tek** [reply]
tl,dr;
1) is it possible to recreate deploy key and switch from read-only to read-write one without recreating whole cluster?
2) is it possible to have image-policy, image-repository in different kustomization than `flux-system`/main directory? It seems that namespace configuration is ignored here.


After enabling debugging for the controller from linked issue:
```
{"level":"error","ts":"2022-11-14T17:53:41.639Z","msg":"referenced git repository projectorg-jekyll/flux-system does not exist.","controller":"imageupdateautomation","controllerGroup":"image.toolkit.fluxcd.io","controllerKind":"ImageUpdateAutomation","ImageUpdateAutomation":{"name":"projectorg-jekyll","namespace":"projectorg-jekyll"},"namespace":"projectorg-jekyll","name":"projectorg-jekyll","reconcileID":"7655f78f-20e2-41af-9925-e405069226c8","error":"GitRepository.source.toolkit.fluxcd.io \"flux-system\" not found"}
```

I'm somewhat confused:
1) I try to self-update flux repository (I assume it's OK?)
2) GitRepository `flux-system` exists in the same namespace (`flux-system`) defined in `gotk-sync.yaml`
3) ImageUpdateAutomation is in the `flux-system` namespace and references GitRepository from such namespace:
```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: projectorg-jekyll
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./apps/projectorg-jekyll
    strategy: Setters
```

It's probably something trivial but why update controller looks for repository in `projectorg-jekyll/flux-system` instead of `flux-system/flux-system` even though namespace is defined as `flux-system` (probably different directory and thus different kustomization?

At any rate, I moved ImageRepository, Policy and ImageUpdateAutomation to `./clusters/project-test-prod1` and the scan works as before but still no update is made. And the error in the logs is gone (and now only says "no changes made in working directory"):
```
{"level":"info","ts":"2022-11-14T19:52:05.705Z","msg":"no changes made in working directory; no commit","controller":"imageupdateautomation","controllerGroup":"image.toolkit.fluxcd.io","controllerKind":"ImageUpdateAutomation","ImageUpdateAutomation":{"name":"projectorg-jekyll","namespace":"flux-system"},"namespace":"flux-system","name":"projectorg-jekyll","reconcileID":"47c7645a-18e3-4a48-bf60-a3e61de7d18f"}
```

EDIT: I rechecked update tag in deployment configuration at this point and the name wasn't correct, after updating it I finally got some progress:
```
{"level":"error","ts":"2022-11-14T19:59:20.205Z","msg":"Reconciler error","controller":"imageupdateautomation","controllerGroup":"image.toolkit.fluxcd.io","controllerKind":"ImageUpdateAutomation","ImageUpdateAutomation":{"name":"projectorg-jekyll","namespace":"flux-system"},"namespace":"flux-system","name":"projectorg-jekyll","reconcileID":"73546523-9be2-4f95-bd24-276b1a076c32","error":"early EOF (the SSH key may not have write access to the repository)"}
```

From what I see, Flux added it's key to the repository but it seems to be read-only:
```
flux-system-master-flux-system-./clusters/my-cluster
[…] Added on Nov 10, 2022 via personal access token owned by @woj-tek 
Last used within the last week — Read-only 
```

I tried re-running bootstrap with `--read-write-key` but it wasn't added so (for the test purposed) I recreated whole deployment and finally with it worked and the image is updated.

**Comment by woj-tek** [comment]
OK, the issue was caused by not explicitly defining `namespace` in `ImageUpdateAutomation`'s `sourceRef`, and as [documentation](https://fluxcd.io/flux/components/image/automation-api/#image.toolkit.fluxcd.io/v1beta1.CrossNamespaceSourceReference) states:

> `namespace` string	**(Optional)** -- Namespace of the referent, defaults to the namespace of the Kubernetes resource object that contains the reference.

I think there is some sort of a bug in FluxCD maybe as I had ImageUpdateAutomation in:
```yaml
metadata:
  name: projectorg-jekyll
  namespace: flux-system
```
yet it used different namespace ("referenced git repository projectorg-jekyll/flux-system does not exist.")
