### DISCUSSION TITLE
Generating HelmReleases in Helm

### DISCUSSION THREAD

**Discussion by rupelu** [fluxcd/flux2#3293] [Polls]
We provide apps to users in form of bundles. A bundle is grouping some apps together. The following tree should illustrate the structure:

```yaml
bundles:
  iam:
    - keycloak
    - postgres
  db:
    - elasticsearch
    - ...
```

Sometimes users do not want to include a specific application or make their own version for the app. Therefore we offer to not include it. We tried to do it in two different ways:

1. Offer the bundle as a Kustomization. The users can then decide via a substitution variable whether to include or exclude an app.

Here we have the variable `profile_keycloak` which can be set to `none` to exclude the app in total.
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-keycloak
spec:
  path: "./kustomization/keycloak/overlays/${profile_keycloak:=normal}"
  ...
```

This would then be the overlay file to include the keycloak bases - which basically does not include anything.
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases: []
```

2. Offer the bundle as a HelmRelease. The users can then provide a value for each app to be enabled or not.

```yaml
{{- if .Values.keycloak.enabled -}}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
spec:
  ...
{{- end }}
```

In the second approach we have one HelmRelease generating multiple HelmReleases. This makes things more flexible however we also saw that the behavior is a bit different in the following ways:

- There is no drift detection. If we delete a HelmRelease that was generated by a HelmRelease it is deleted until we do a suspend/resume cycle
- `flux tree` is only showing the resources till the first HelmRelease and not the Sub-HelmRelease Resources

We found also other use cases where it would be interesting to generate HelmReleases. For example to provide users a dynamic layering of value files like so:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
spec:
  valuesFrom:
    - kind: ConfigMap
      name: keycloak-bundle-values
    {{- range $k, $v := .Values.global.layers }}
    - kind: {{ $v.kind | default "ConfigMap" }}
      name: keycloak-{{ $v.name }}-values
      optional: {{ $v.optional | default true }}
    {{- end }}
```

All-in-all it felt a bit like HelmRelease were not intended to be dynamically generated. Also we didn't found examples of this structure used by others so far.
