### DISCUSSION TITLE
HelmReleases and following local charts by version

### DISCUSSION THREAD

**Discussion by leszczynskimikolaj** [fluxcd/flux2#3300] [Q&A]
Hey!

Wanted to ask if this is possible to treat my local Chart.yaml and its version as a source for the HelmRelease? I know I can have a GitRepository following the branch but what I actually need is to trigger HelmRelease reconciliation only when the version of my local chart has changed.

Thanks in advance!

**Comment by hiddeco** [comment]
By default, a new chart is only build if the version within the `Chart.yaml` file in the Git repository changes.

See: https://fluxcd.io/flux/components/source/helmcharts/#reconcile-strategy

**Comment by leszczynskimikolaj** [comment]
@hiddeco great, that is what I read too. Does it mean that in my case, if I want to reconcile HelmRelease based on the version bump of my chart in my private GitHub repo then I need a configuration like this?
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: my-repo
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: main
  url: <url to my repo>
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: my-helm-chart
  namespace: flux-system
spec:
  interval: 5m0s
  chart: path/to/my/helm/chart
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: GitRepository
    name: my-repo
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-release
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: path/to/my/helm/chart
      version: ">=1.0.0"
      sourceRef:
        kind: HelmChart
        name: my-helm-chart
        namespace: flux-system
      interval: 1m0s

```
