### DISCUSSION TITLE
Add OCI Artifact signature verification provider support for notaryproject/notation

### DISCUSSION THREAD

**Discussion by 0xjbushell** [fluxcd/flux2#3305] [Proposals]
As of today, Source Controller does not support notaryproject/notation as a verification provider for OCI Artifacts.

### Proposal
Add support to Source Controller to verify signatures signed by notaryproject/notation in `OCIRepository`. It looks like we can build on top of the OCI Repositories verification support introduced in:  https://github.com/fluxcd/source-controller/pull/876 and `0.30.0`. Notation verification can be configured by setting `OCIRepository.spec.verify` with provider as `notation`. Public key is retrieved via `secretRef ` pointing to a secret.

```---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: <repository-name>
spec:
  verify:
    provider: notation
    secretRef:
      name: notation-public-keys
```

```
---
apiVersion: v1
kind: Secret
metadata:
  name: notation-public-keys
type: Opaque
data:
  key1.pub: <BASE64>
  key2.pub: <BASE64>
```
