### DISCUSSION TITLE
Reconciliation happening nonstop even with no changes to manifests

### DISCUSSION THREAD

**Discussion by joshuadmatthews** [fluxcd/flux2#3308] [Q&A] [answered]
I recently hooked up the gitops connector https://github.com/Azure/gitops-connector so that I can see deployment status in github on the commits that contain manifest changes, and also so I can trigger the next step of my workflow once a deployment completes with the dispatch event that gitops connector sends out on successful deployment.

When I got everything setup, I noticed I was getting the dispatch event in github once per reconcilliation period, regardless of changes happening or not to the manifests. I checked the logs for gitops connector and have messages like this coming in 

`DEBUG:root:GitOps phase: {'involvedObject': {'kind': 'Kustomization', 'namespace': 'flux-system', 'name': 'kustomization-mymanifests', 'uid': 'f3de8ac7-e027-411c-a2e1-ffdf73cb35a4', 'apiVersion': 'kustomize.toolkit.fluxcd.io/v1beta2', 'resourceVersion': '13397523'}, 'severity': 'info', 'timestamp': '2022-11-10T14:24:20Z', 'message': 'Reconciliation finished in 843.869422ms, next run in 1m0s', 'reason': 'ReconciliationSucceeded', 'metadata': {'commit_status': 'update', 'revision': 'lab-talent-aks/efbe4dd15f723a82e90a122a508f092e7320d6af'}, 'reportingController': 'kustomize-controller', 'reportingInstance': 'kustomize-controller-6fc6744c6b-6dj68'}`

And every reconciliation period another one comes in with a unique resourceVersion number. I am thinking flux is sending the notification repeatedly to gitops connector, even though nothing has changed in the manifests. 

I am forwarding events with the following 

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: gitops-connector
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: myrepo
  - kind: Kustomization
    name: kustomization-mymanifests
  providerRef:
    name: gitops-connector
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: gitops-connector
  namespace: flux-system
spec:
  type: generic
  address: http://gitops-connector:8080/gitopsphase

```
How can I figure out what is going on here? Should I expect to only get events from flux when something actually changes in the manifests? Or does it alert on every reconciliation and it's the gitops connector job to know if something changed somehow?
