### DISCUSSION TITLE
HelmRelease upgrade and rollback

### DISCUSSION THREAD

**Discussion by leszczynskimikolaj** [fluxcd/flux2#3321] [Q&A]
Hey guys,

this is my configuration:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-hr
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: my-hr-name
  targetNamespace: my-ns
  install:
    createNamespace: true
    remediation:
      retries: 3
      ignoreTestFailures: false
      remediateLastFailure: false
  uninstall:
    keepHistory: true
  upgrade:
    force: true
    remediation:
      retries: 3
      ignoreTestFailures: false
      remediateLastFailure: false
  chart:
    spec:
      chart: path/to/my/chart
      sourceRef:
        kind: GitRepository
        name: my-git-repo
        namespace: flux-system
      interval: 1m0s
      reconcileStrategy: ChartVersion
```

and what I try to achieve is:
1. When doing the install/upgrade I want the same behaviour which is: retry 3 times and if the last retry also fails then do nothing and leave the not-deployed version on the cluster. Can I assume here that my working version of the HelmRelease, the one pre-failed-release, will still be running on the cluster in such case? Can I also assume that no rollback will happen here?
2. I think the `force: true` does not work as I assume it. My helm chart contains jobs and whenever there is the upgrade action happening I'm getting this long, obscure error about immutable field being changed. Am I missing something?
