### DISCUSSION TITLE
Confused between HelmChart vs HelmRelease

### DISCUSSION THREAD

**Discussion by sidd-harth** [fluxcd/flux2#3328] [Q&A] [answered]
Hi,

I have been exploring Flux2 and trying the example around Helm.

I use either a `GitRepository` or `HelmRepository` to define the source and then do a `HelmRelease`.

What is the use of `HelmChart` [API within the Source Controller](https://fluxcd.io/flux/components/source/helmcharts/#working-with-helmcharts)? Why is `HelmChart API` part of `Source Controller` and not part of `Helm Controller`?

As per my understanding, a Source Controller connects and fetches artifacts from different sources. But within the below HelmChart example, it is using a `sourceRef` which can be mapped to HelmRepository | GitRepository | Bucket. 

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m0s
  chart: podinfo
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: podinfo
  version: '5.*'
```
