### DISCUSSION TITLE
Unable to remove a previous helm repo definition

### DISCUSSION THREAD

**Discussion by mannp** [fluxcd/flux2#3331] [Q&A]
Hi all

I have an annoying issue where I have incorrectly defined a helm repo and tried to delete it and redefine.

`flux delete hr plausible  -n utilities --verbose`

Listing the HR gives me;

`flux get helmrelease -A`

```
NAMESPACE   	NAME                    	REVISION 	SUSPENDED	READY	MESSAGE
utilities   	plausible               	           	   False    	False	chart reconciliation failed: HelmChart.source.toolkit.fluxcd.io "utilities-plausible" is invalid: spec.sourceRef.kind: Unsupported value: "": supported values: "HelmRepository", "GitRepository", "Bucket"
```

This is the current definition for the HelmRepository;

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: plausible
  namespace: flux-system
spec:
  interval: 30m
  url: https://david-crty.github.io/plausible-helm-chart/
  timeout: 3m
```

How can i delete this spurious helm repo definition please?

Thanks
