### DISCUSSION TITLE
Image Update Automation, markers and filterTags

### DISCUSSION THREAD

**Discussion by tomstratton1** [fluxcd/flux2#3337] [Q&A]
Hello, many thanks for the hard work on this project, it is amazing. 

I noticed that the Image Update Automation does not seem to work unless the image you are targeting with the marker comment (in my case in a GitRepository source), already follows the filterTags pattern in the Image Policy. For example, the image policy I had was:

```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: <image-policy>
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: <name>
  filterTags:
    pattern: '^alpha-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts' 
  policy:
    numerical:
      order: asc
 ```     

And the deployment yaml it was targeting via a Image Update Automation was

```
php:
  replicaCount: 1
  image:
    repository: <repo>
    pullPolicy: Always
    tag: alpha # {"$imagepolicy": "flux-system:<image-policy>:tag"}
```
Note that the tag "alpha" does not obey the filterTags pattern (although there were images in the registry that do). 
Initially, the Image scanning and policy was working fine, but the Image Update Automation reported "no changes made".
After I changed the deployment yaml to something like below, it started working and the fluxcd bot started writing commits. 

```
php:
  replicaCount: 1
  image:
    repository: <repo>
    pullPolicy: Always
    tag: alpha-90d1234-1234567890 # {"$imagepolicy": "flux-system:<image-policy>:tag"}
```

Is this expected behaviour? Perhaps it is obvious to others but I thought I would share this in case anyone else had the same problem. I also searched through the discussions but could not find exactly the same issue.
