### DISCUSSION TITLE
Flux + Terraform Interpolation

### DISCUSSION THREAD

**Discussion by mattjamesaus** [fluxcd/flux2#3348] [Q&A]
Not sure if this is the right forum, but it seems that at least a lot in our Flux work we have a case of where we're using Terraform to bootstrap the EKS cluster and make things like OIDC roles for service accounts, Load Balancers etc and then we end up having to copy paste the ARNs into our kubernetes manifests like this:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-worker-role
  namespace: namespace
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxx:role/ops-app-worker-role
```
And it tends to lend itself to be a little brittle between these two great pieces of infra management tools, i'm wondering if there's a pattern or tool others use to bridge this gap? I've thought about trying to generate the yaml patches in terraform and then using github_repository_file to generate these dynamically using terraform. It seems like the only shortcoming to being able to generate a complete environment using TF and then have flux generate all the kube resources based on those outputs.

Perhaps this is more a TF question, but i feel there's a lot more folks here versed in both tools than folks in terraform communities familiar with flux.

Once again thanks for all the wonderful hard working people that make flux you're true legends.

Edit: I've just seen this link https://github.com/fluxcd/flux2/discussions/3130 which might solve the problem if i can get annotation values from other sources like configmaps
