### DISCUSSION TITLE
Multiple flux installations sync to single repo

### DISCUSSION THREAD

**Discussion by aerlaut** [fluxcd/flux2#3349] [Q&A] [answered]
Hi all,

I'd like to sync multiple clusters with separate Flux instances to one repository under the same path. Is it possible to do so?

I tried installing flux in different clusters pointing to the same repository, but found out that Flux ovewrites the deploy key. I tried changing the name of the deploy key using the `--secret-key` command, but it modifies the `secretRef` name in `gotk-sync.yaml`.

I have seen examples where 1 (management) cluster syncs to multiple clusters (push), but have not seen an example where multiple cluster syncs to a single repo (pull).

**Comment by aerlaut** [comment, marked as answer]
Oh I think I get it. Following this example: https://github.com/fluxcd/flux2-kustomize-helm-example, I can create a structure such as:

```
clusters/
  cluster-1/
    cluster.yaml
  cluster-2/
    cluster.yaml
app/
  deployment.yaml
```

And then what's needed inside `cluster.yaml` is

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-1
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./app
  prune: true
```

Then I just need to bootstrap the cluster, pointing to their respective directories.
