### DISCUSSION TITLE
Conditionally apply annotation

### DISCUSSION THREAD

**Discussion by rustygreen** [fluxcd/flux2#3357] [General]
I have an issue where I need to apply an annotation, that uses variable substitution, only if a variable exists. I have a helmrelease declaration that is re-used in multiple clusters. However, in one cluster I want to apply an annotation, but in another I do not want to apply the annotation. Using a default value of empty string does not work for this particular setting (`nginx.ingress.kubernetes.io/whitelist-source-range`).

**Desired Example for Cluster 1 (with annotation):**

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-release
  namespace: default
spec:
  values:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "100m"
        nginx.ingress.kubernetes.io/whitelist-source-range: "${SECURE_INGRESS_WHITELIST_RANGE}"
```

**Desired Example for Cluster 2 (without annotation):**

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-release
  namespace: default
spec:
  values:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "100m"
        # NOTE: "whitelist-source-range" annotation is not applied
```
 Is this possible? If not, will it ever be?
