### DISCUSSION TITLE
dry-run doesn't allow to install/apply dependencies

### DISCUSSION THREAD

**Discussion by mbaykara** [fluxcd/flux2#3374] [General] [answered]
I have following case:

flux repo structure:
```
.
├── apps
│   ├── base
          ├──  some-prometheus-rules.yaml
├── clusters
│   └── prod
          ├── kustomization-apps.yaml
          ├── kustomization-infrastructure.yaml
├── infrastructure
│   ├── apps
        ├── prometheus-helmrelease.yaml    

```
kustomization.yaml
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kustomization-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  dependsOn:
    - name: kustomization-infrastructure

```
And the kustomization-infrastructure.yaml

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kustomization-infrastructure
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
```
Expected: The apps unter ` path: ./infrastructure/apps` will be installed and then the following apps under ` path: ./apps/base` .
Result: It is failed. Because since flux run firstly a `dry-run`, it cannot find the `PrometheusRule` crd which will be installed once the Prometheus installed. In this case I have to install Prometheus then rerun or apply the PrometheusRule resources. I thought the `dependsOn` will solve this issue.
I am not sure where/what I am doing wrong?
