### DISCUSSION TITLE
OCI artifacts flux commands from a pod inside a KinD cluster is slow

### DISCUSSION THREAD

**Discussion by ntx-ben** [fluxcd/flux2#3375] [Q&A]
I'm running a small `KinD` v0.12.0 cluster based on v1.23.4 and basically deployed an empty docker registry (`registry:2`) as well as a k8s `Job` based on `fluxcd/flux-cli:v0.37.0`, trying to load OCI artifacts into the registry. I've noticed that each flux OCI commands (`flux push artifact` and `flux list artifacts` for ex.) running from inside the `Job` pod take approximately 90 seconds to complete, which is odd.

```
/ # time flux list artifacts oci://docker-registry.docker-registry.svc.cluster.local/test

ARTIFACT                                                        DIGEST                                                                  SOURCE                                                          REVISION
docker-registry.docker-registry.svc.cluster.local/test:latest   sha256:77f11fab624826cd57e558ec650d1bb0e2c3b264b9714b966d9de923c210b535 https://gitlab.com/bleh.git                   latest

real    1m 27.52s
user    0m 0.10s
sys     0m 0.03s
```

I've port-forwarded the registry pod to my machine and tried the same command locally, and it returns within 1-2 seconds.
The internal Kubernetes service is also working correctly (`nslookup` from the `Job` pod returns promptly).

Monitoring the registry logs, I see no errors whatsoever either.

What could be the reason for this? The only thing I can think of is that the `Job` is running with the default K8S user account, which has limited access to the cluster. Running `flux version` from within the `Job` pod shows this:

```
/ # flux version

✗ deployments.apps is forbidden: User "system:serviceaccount:docker-registry:default" cannot list resource "deployments" in API group "apps" in the namespace "flux-system"
```

Are flux OCI commands dependent on access to the cluster?

**Comment by stefanprodan** [comment]
> Are flux OCI commands dependent on access to the cluster?

No

> What could be the reason for this?

Can you post here the Job YAML with `kubectl get job -oyaml`? One reason could be that you've set some low CPU limits or you have some admission controller that does this.

**Comment by ntx-ben** [comment]
Hi @stefanprodan 

Thanks for the tip! I will edit my original post: I was using `KinD` v0.12.0 with k8s v1.23.4, which is exhibiting the issue. I tried again in a blank k3s cluster and now flux works as expected. So, it must be something in `KinD`... I'm not aware of any special controllers in `KinD` that would affect flux however.

For reference, my `Job`:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: test
  namespace: docker-registry
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: test
        image: fluxcd/flux-cli:v0.37.0
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          sleep 99999999
          # time flux pull artifact oci://docker-registry.docker-registry.svc.cluster.local/test:latest -o /tmp || 0
      restartPolicy: Never
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 0
```
