### DISCUSSION TITLE
Audit logs

### DISCUSSION THREAD

**Discussion by emilbillberg** [fluxcd/flux2#3376] [Q&A] [answered]
I am tailing the audit log file from Kubernetes API server and noticed that Flux creates about 50 % of the entries in the log file. I have a very naive audit policy at the moment that logs everything:

```
apiVersion: audit.k8s.io/v1
kind: Policy
  - level: Metadata
    omitStages:
      - "RequestReceived"
```

Since Flux creates such a big portion of the total audit logs file I wonder if you have a suggestion on an audit policy that filters out entries that would be consider low-risk and can be omitted?

**Comment by stefanprodan** [comment, marked as answer]
I guess a big percentage of these logs are generated by Flux drift detection, so you could drop all the server-side apply dry-run calls and keep only the actual apply ones.

**Reply by emilbillberg** [reply]
Yes, that would make sense. In my 15 minute time interval it seems like almost 40 % of the requests are dry-run calls. You don't happen to know how to set the log level to `None` for dry-run requests? The only way I can tell that a request is dry-run is on key `requestURI` contains `?dryRun=All`. I guess you need to find some glob pattern for that...

```
- level: None
   userGroups: ["system:serviceaccounts:flux-system"]
   nonResourceURLs:
    - ?? # some smart wildcard matching here for dryRun...
```
