### DISCUSSION TITLE
Use secret from Rook-Ceph-managed `ObjectBucketClaim` bucket in `ConfigMap` template.

### DISCUSSION THREAD

**Discussion by reitermarkus** [fluxcd/flux2#3392] [Q&A]
Hi, I am migrating from Ansible to Flux, and not sure how to proceed. With Ansible I had the following:

1. Apply 
   ```yaml
   apiVersion: objectbucket.io/v1alpha1
   kind: ObjectBucketClaim
   metadata:
     name: thanos-bucket
     namespace: monitoring
   spec:
     generateBucketName: thanos
     storageClassName: ceph-bucket
   ```

2. Wait for Rook-Ceph to create the bucket, then get the generated `configmap/thanos-bucket` and `secret/thanos-bucket`.

3. Create `values.yaml` for Helm release containing:
   ```yaml
   objstoreConfig: |-
     type: s3
     config:
       bucket: ${BUCKET_NAME}
       endpoint: ${BUCKET_HOST}:${BUCKET_PORT}
       access_key: ${AWS_ACCESS_KEY_ID}
       secret_key: ${AWS_SECRET_ACCESS_KEY}
       insecure: true
   ```
4. Deploy Helm release with the created `values.yaml`.

---

Now with Flux, how do I get the `ConfigMap` and `Secret` values into a `values.yaml` for a `HelmRelease`?
