### DISCUSSION TITLE
Inject secret from vault in helm values

### DISCUSSION THREAD

**Discussion by Crqck3d** [fluxcd/flux2#3400] [General]
Hello everyone, I've been looking for a long time and flux doesn't seem to provide the functionality I'm looking for.

Currently, if I understood correctly, the integration of the hashicorp vault by flux only allows it to decrypt SOPS secrets using a key (age or gpg) contained in the vault or in a k8s secret.

I want to be able to inject secrets contained in the vault into the values of a helm release without using SOPS.
ArgoCD allows to do that with the argocd-vault-plugin and it looks like:
```
envs:
  - name: PASS
    value: <path:kv-v2/data/argocd#password>
```

Expectation:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  values:
    grafana:
      adminPassword: <path:kv/data/grafana#adminPassword>
```

Does anyone have a solution ? Thanks
