### DISCUSSION TITLE
Cannot determine latest tag for policy: unable to determine latest version from provided list

### DISCUSSION THREAD

**Discussion by mhassaankhokhar** [fluxcd/flux2#3402] [Q&A]
Hello, I am facing the issue regarding tagging and I am using docker hub. 

Image registry code,
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: frontend
  namespace: flux-system
spec:
  image: mhassaankhokhar/lm-frontend
  interval: 1m0s
```
The image policy that I am using is, 
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: frontend-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frontend
  policy:
    semver:
      range: '>=0.x'
```
And the deployment that I am using, 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lm-frontend
  namespace: linkedmatrix
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.lm-frontend: glob:master-*
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: lm-frontend
  template:
    metadata:
      labels:
        app: lm-frontend
    spec:
      containers:
      - name: lm-frontend
        image: mhassaankhokhar/lm-frontend:master-0.1  # {"$imagepolicy": "default:frontend-policy"}
        ports:
        - containerPort: 80
```
