### DISCUSSION TITLE
install specific components with kustomize

### DISCUSSION THREAD

**Discussion by Raboo** [fluxcd/flux2#3412] [Q&A] [answered]
Hi

It's easy to install specific components with the flux cli tool like:
```
flux install --components="source-controller,helm-controller"
```

But does anyone know how to install specific components with kustomize? 

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/fluxcd/flux2/releases/download/v0.37.0/install.yaml
```

**Comment by stefanprodan** [comment, marked as answer]
You can use a patch to remove components like this:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/fluxcd/flux2/releases/download/v0.37.0/install.yaml
patches:
  - target:
      labelSelector: app.kubernetes.io/component in (image-reflector-controller, image-automation-controller)
    patch: |
      $patch: delete
      kind: ignored
      apiVersion: ignored
      metadata:
        name: ignored
```

**Comment by Raboo** [comment]
Thank you!
I have some follow up questions.

My kustomization.yaml:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/fluxcd/flux2/releases/download/v0.37.0/install.yaml

patches:
  - target:
      labelSelector: app.kubernetes.io/component in (image-reflector-controller, image-automation-controller, kustomize-controller, notification-controller)
    patch: |
      $patch: delete
      kind: ignored
      apiVersion: ignored
      metadata:
        name: ignored
```

Creating outputs from both commands:
```shell
$ kustomize build > kustomize-build.yaml
$ flux install --export --components="source-controller,helm-controller" > flux-install-cli.yaml
```

Comparing output (cleaned up a bit to reduce size):
```diff
--- kustomize-build.yaml	2022-12-16 10:52:49
+++ flux-install-cli.yaml	2022-12-16 10:52:30
@@ -3695,7 +3708,8 @@
   labels:
     app.kubernetes.io/instance: flux-system
     app.kubernetes.io/part-of: flux
-  name: crd-controller
+    app.kubernetes.io/version: v0.37.0
+  name: crd-controller-flux-system
 rules:
 - apiGroups:
   - source.toolkit.fluxcd.io
@@ -3784,7 +3798,8 @@
   labels:
     app.kubernetes.io/instance: flux-system
     app.kubernetes.io/part-of: flux
-  name: cluster-reconciler
+    app.kubernetes.io/version: v0.37.0
+  name: cluster-reconciler-flux-system
 roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
@@ -3803,11 +3818,12 @@
   labels:
     app.kubernetes.io/instance: flux-system
     app.kubernetes.io/part-of: flux
-  name: crd-controller
+    app.kubernetes.io/version: v0.37.0
+  name: crd-controller-flux-system
 roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
-  name: crd-controller
+  name: crd-controller-flux-system
 subjects:
 - kind: ServiceAccount
   name: kustomize-controller
@@ -3873,8 +3891,8 @@
     spec:
       containers:
       - args:
-        - --events-addr=http://notification-controller.flux-system.svc.cluster.local./
-        - --watch-all-namespaces
+        - --events-addr=
+        - --watch-all-namespaces=true
         - --log-level=info
         - --log-encoding=json
         - --enable-leader-election
@@ -3920,6 +3938,8 @@
         volumeMounts:
         - mountPath: /tmp
           name: temp
+      nodeSelector:
+        kubernetes.io/os: linux
       securityContext:
         fsGroup: 1337
       serviceAccountName: helm-controller
@@ -3955,8 +3976,8 @@
     spec:
       containers:
       - args:
-        - --events-addr=http://notification-controller.flux-system.svc.cluster.local./
-        - --watch-all-namespaces
+        - --events-addr=
+        - --watch-all-namespaces=true
         - --log-level=info
         - --log-encoding=json
         - --enable-leader-election
@@ -4011,6 +4032,8 @@
           name: data
         - mountPath: /tmp
           name: tmp
+      nodeSelector:
+        kubernetes.io/os: linux
       securityContext:
         fsGroup: 1337
       serviceAccountName: source-controller
```

I see that some objects have different names `crd-controller` vs `crd-controller-flux-system`.
If I am going from a previously "flux install" to a "kustomize build" would I need to uninstall and reinstall since some of the objects changed names?

Also and some arguments are different, like `--events-addr`. Will this cause a problem?
