### DISCUSSION TITLE
Issues when installing Linkerd with helm through flux

### DISCUSSION THREAD

**Discussion by ekke020** [fluxcd/flux2#3414] [Q&A]
Hello! 
I've been trying out flux in the recent days and have gotten a fairly good grasp of how stuff work but there is one thing that keep bugging me and I can't for the life of me figure out what I'm doing wrong.
The problem occurs when I try to install Linkerd. I manage to install the crds without a problem but when it comes to the control plane I get stuck. 
I have installed the same helm chart using the cli without a problem so it most definitely works but there must be something I am missing...
If I run `kubectl get helmrelease -n linkerd` the status says:

> Helm install failed: YAML parse error on linkerd-control-plane/templates/identity.yaml: error converting YAML to JSON: yaml: control characters are not allowed

Here are my HelmRelease & HelmRepository files.
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: control-plane
  namespace: linkerd
spec:
  interval: 5m
  chart:
    spec:
      chart: linkerd-control-plane
      version: "1.9.x"
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      interval: 1m
      valuesFiles:
        - values.yaml
        - values-ha.yaml
  upgrade:
    remediation:
      retries: -1
  values:
    identity.issuer.crtExpiry: 2023-12-16T23:03:32Z
    installNamespace: false
  valuesFrom:
    - kind: Secret
      name: linkerd-certs
      valuesKey: ca.crt
      targetPath: identityTrustAnchorsPEM
    - kind: Secret
      name: linkerd-certs
      valuesKey: issuer.crt
      targetPath: identity.issuer.tls.crtPEM
    - kind: Secret
      name: linkerd-certs
      valuesKey: issuer.key
      targetPath: identity.issuer.tls.keyPEM
```

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: linkerd
  namespace: linkerd
spec:
  interval: 2m
  url: https://helm.linkerd.io/stable
```
Appreciate any help!

**Comment by stefanprodan** [comment]
Please see here an example https://github.com/stefanprodan/gitops-linkerd/blob/main/infrastructure/linkerd/linkerd-release.yaml

You can’t use dots in the values keys.

**Reply by ekke020** [reply]
Ahh yes I changed that now but I still get the same error...
I've tried with and without passing `valuesFiles` as well but it does not seem to change anything.
I also tried reverting and using their old chart (the one in your example) that has since been depricated and I ended up with the same result.

**Reply by ekke020** [reply]
Oke so I seem to have boiled it down to the root cause, it has to do with the `identityTrustAnchorsPEM` for some reason whenever I remove this the install works great or at least starts, however the pods enter a crashloop because the value is missing.
So I'm guessing there must be something wrong with my ca.crt that I generated with step...
This is what the ca.crt looks like:
```
MIIBjjCCATSgAwIBAgIRAPmF58nUn620z3e6N4OBaWwwCgYIKoZIzj0EAwIwJTEjMCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjIxMjE2MjE1NjU3WhcNMzIxMjEzMjE1NjU3WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABLo3FQmcQeQGA1PjEI6/8GZ3sO9ET/tbL5DOu006AX6uhJz1od26y5dBn9K5bOeT1E6waHg10gRNPYLXe6pFEYyjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBT5lYvAeJrO+bslcUyAI93Oot37KjAKBggqhkjOPQQDAgNIADBFAiEAigyxy7VW6ErPe81oKDU8CQlrih5SWNkjPckKv+HKDa8CIF/vUDNcwXwPNH+yYCHMQHcBf2f5f1XtX7d+5kkWiNNs
```

Not sure if this is invalid format somehow.

**Reply by kingdonb** [reply]
So it sounds like you've fixed this! 🤞 hope it's resolved for you, let us know if there's more we can still do to help with this!

I'm not sure how you've included the ca.crt, we can look at it more if you provide more context in the example. (Are you using a SOPS Secret to add the ca.crt?)

**Reply by zsparal** [reply]
EDIT: I'll leave the comment here because the setup might be useful for other people. It was a dumb issue: I had "version: 2.x" for the linkerd Helm chart. Linkerd is on version 2 but the Helm chart is on version 1 

I'm actually running into similar issues. Installing `linkerd` manually with the generated certificate works fine, but when trying to do the same with `flux`, the installation just seems to hang (and `linkerd` never gets installed). Here's my setup:

**Generating the certificates:**

```yaml
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-selfsigned-issuer
  namespace: linkerd
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  isCA: true
  commonName: root.linkerd.cluster.local
  secretName: linkerd-trust-anchor
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: linkerd-selfsigned-issuer
  subject:
    organizations:
      - Loom
    organizationalUnits:
      - linkerd
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 48h
  renewBefore: 25h
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
    - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth
```

**Installing linkerd-control-plane:**

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  interval: 5m
  targetNamespace: linkerd
  releaseName: linkerd-crds
  chart:
    spec:
      chart: linkerd-crds
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: linkerd
      interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  interval: 5m
  targetNamespace: linkerd
  releaseName: linkerd-control-plane
  dependsOn:
    - name: linkerd-crds
  chart:
    spec:
      chart: linkerd-control-plane
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: linkerd
      interval: 1h
  values:
    identity:
      issuer:
        scheme: "kubernetes.io/tls"
  valuesFrom:
    - kind: Secret
      name: linkerd-trust-anchor
      valuesKey: ca.crt
      targetPath: identityTrustAnchorsPEM
```

What am I doing wrong?
