### DISCUSSION TITLE
Provider error after latest update

### DISCUSSION THREAD

**Discussion by budimanjojo** [fluxcd/flux2#3434] [General] [answered]
Hello, after updating to the latest version (`v0.38.1`) I keep getting this alert. 
```
kustomization/apps.flux-system
Provider/flux-system/discord dry-run failed, error: .spec.interval: field not declared in schema
```
I have checked that the `CRD` in the cluster is updated which include `spec.interval`, not sure what is causing this but this seems to be similar problem with this: https://github.com/fluxcd/flux2/issues/2501

**Comment by vomba** [comment]
I am having the exact same problem too.

**Reply by stefanprodan** [reply]
Can you please bump the API version in Git in your Providers YAMLs to `v1beta2` and see if it fixes it?

**Comment by stefanprodan** [comment]
Can you please say more about your clusters, which Kubernetes version do you use, is it a SaaS AKS/EKS/GKE?

Also can you post here the output of `kubectl get crd providers.notification.toolkit.fluxcd.io -oyaml| yq .status`, It should output only `v1beta2` as the stored version like so:

```yaml
acceptedNames:
  kind: Provider
  listKind: ProviderList
  plural: providers
  singular: provider
conditions:
  - lastTransitionTime: "2022-12-22T10:55:42Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2022-12-22T10:55:42Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
storedVersions:
  - v1beta2
```

**Reply by vomba** [reply]
I'm using EKS

```
acceptedNames:
  kind: Provider
  listKind: ProviderList
  plural: providers
  singular: provider
conditions:
  - lastTransitionTime: "2022-06-28T09:47:41Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2022-06-28T09:47:41Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
storedVersions:
  - v1beta1
  - v1beta2
```

It shows 2 versions
