### DISCUSSION TITLE
SOPS and Helm Values

### DISCUSSION THREAD

**Discussion by SrDayne** [fluxcd/flux2#3436] [Q&A] [answered]
Hello.

Is there a way do use SOPS for helm values? I mean, I have some secrets in values.yaml file and I need them to be encrypted. With sops cli it work perfect, but with kustomize controller it does not decrypt the values. Here is the example of encrypted values:

```
task:
    enabled: true
podSecurityContext:
    runAsUser: 33
    runAsNonRoot: true
volumes:
    - name: nginx-conf
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
    - name: vhost-conf
      mountPath: /etc/nginx/sites-enabled/vhost.conf
      subPath: vhost.conf
    - name: parameters-composer
      mountPath: /var/www/project/app/config/parameters.yml
      subPath: parameters.yml
resources:
    requests:
        cpu: 700m
        memory: 1200Mi
    limits:
        cpu: 900m
        memory: 1500Mi
autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
nodeSelector:
    eks.amazonaws.com/nodegroup: dev
tolerations:
    - effect: NoExecute
      key: node.alpha.kubernetes.io/notReady
      operator: Exists
      tolerationSeconds: 90
    - effect: NoExecute
      key: node.alpha.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 90
parameters: ENC[AES256_GCM,data:vYQmiRTmaeolMWIunfgJxd5uOG6j0mVUM1SeVVLFsqwBfZLIBbO2aj9ChNrpJz7ProvIrem98NTp80ACFlvsQUy1/AzIGRT26oFUcOgbkYoCbBzJxvuwaN0ux647UaHYZTAN87M/BiWTyCqbMcwA1Ico9yjp1WbDfeba6FTZTMeqBblD2mIWfE8ppTdPIG7Gw3akvFkpXrX5o7Hmho0q40qUdenTLjesE6tRaYYgMWC5stVeOGoGlBmSb3AsCEo=,iv:eK/9Fj9evMQtlmrMWFtPSomu/JkMq95xzO8DvC+YruQ=,tag:LJquw9sPE8jW4eSarHgh4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y69m0vp69wzensp8jgpgpf7ueqkmv9artwqmm9348cac02z0my5qp6nssd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc0xGT09HUzRNZnNJTnF2
            YmRwbUF0L0tOU0dnd3U5MHZpd1pLS21Ka2pNCngzWUpxNkx4RTdoazMzTlVXQ3l3
            Tzdqb202em9SMEVUQzdyQy9IVllHWmcKLS0tIHZqemRMclV1SFJHMDl5NER6bE83
            SzlETmNRRlVHUTZ0MVhRMXRNcDdmekkKys1MBAkkFJiSOPxxrZ2DPoGTk0kSQW/n
            fLgNAfHPolOeE4AU3mvd4qTPg15CCEKVj6woKVdV28HppVSeptA4PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T11:08:21Z"
    mac: ENC[AES256_GCM,data:Toq5sxUdseA/8K7Y5yTOFsIQU/LkwZgqpoGu9twEZ5xdTwAG/YvXNwg3gskUFt7SxSizxxg0VXELyRY+EoBYwapzGo1odecv9XJh8iJHAQ4MRDwdTORUx5eJdQ8ymD838BSKHiFH4ZCu+zvZkDgYpeqY2vYeec11yasPKNwSR5c=,iv:qfd0yA0tG4aqgQTeF7S+x67ILDEw5vR83r0S48WgnnA=,tag:PdBryac4qgbxCZLnuRT8jg==,type:str]
    pgp: []
    encrypted_regex: ^(parameters)$
    version: 3.7.3
```

So my question is: is it possible to use SOPS for values.yaml?

**Comment by stefanprodan** [comment, marked as answer]
> So my question is: is it possible to use SOPS for values.yaml?

No, but you can use `HelmRelease.spec.valuesFrom` and set those values in a Kubernetes secret encrypted with SOPS.

Docs here: https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-secret-generated-with-kustomize-and-sops

**Reply by SrDayne** [reply]
Thank you for the fast reply.

In my case valuesFrom doesn't fit me.

To be able to auto restart pod if configmap changes we can use `configMapGenerator`. So the name of the configmap changes each time when content of the file is changed. It is expected behavior. But I cannot use this dynamic name in helm template, because it does not support regex resource names.

So I need to use static name for volume, and to be able to auto restart pod when configmap's content changes. I found only one working solution for this:
**Helm part:**
1. Create `configmap-parameters-composer.yaml` by template which takes content from 'parameters' field of the values.yaml
2. Created file is using to generate annotation each time when configmap's content changes:
```
template:
    metadata:
      annotations:
        checksumComposer: {{ include (print $.Template.BasePath "/configmap-parameters-composer.yaml") . | sha256sum }}
```
**Flux part:**

3. Kustomization controller creates `dev-values.yaml`  using `configMapGenerator`. We use this configmap with values and dynamic name in `valuesFrom` field of the `HelmRelease`.

This workaround allows us to recreate pod in different ways:
1. Changed helm template - new helm release will deploy and recreate pods
2. Changed `parameters` - kuztomization controller creates new `dev-values.yaml` with new parameters and recreate pods
3. Changed `dev-values.yaml` - same as above - kuztomization controller creates new `dev-values.yaml` and recreate pods

So the only one problem left is secrets storage. And it does not work in my case.

But anyway, thanks for your answer it gives me confidence that I need to look for some workaround.
