### DISCUSSION TITLE
Kustomization postBuild substituteFrom

### DISCUSSION THREAD

**Discussion by TLDMain** [fluxcd/flux2#3451] [General]
Hi! Is it possible to allow reading substitute ConfigMap from generated resources?
eg:
```yaml
# flux-git-repo/sync-from-other-repo.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: default
  namespace: default
spec:
  path: ./production
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: substitute-config
```
and
```yaml
# other-repo/base/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
spec:
  rules:
  - host: ${host}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend: ...

# other-repo/production/substitute-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: substitute-config
data:
  host: example.com

# other-repo/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
```

Currently, kustomization-controller requires an already created ConfigMap to substituteFrom.

Or even allow referring a file in substituteFrom config:
```yaml
spec:
  postBuild:
    substituteFromFile:
      - path: vars.env
```
