### DISCUSSION TITLE
Image Update Automation

### DISCUSSION THREAD

**Discussion by ehudyonasi** [fluxcd/flux2#3464] [Q&A] [answered]
Hey,
Can flux update the image automation in a case I am setting it in the Kustomization file?
e.g:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./app.yaml
images:
- name: app-image
  newName: app-image-registry
  newTag: app-image-tag # {"$imagepolicy": "flux-system:app"}
```

**Comment by kingdonb** [comment, marked as answer]
Yes, indeed this is one of the examples in the Image Update Automation guide doc:

https://fluxcd.io/flux/guides/image-update/#configure-image-update-for-custom-resources

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: ghcr.io/stefanprodan/podinfo
  newName: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "flux-system:podinfo:name"}
  newTag: 5.0.0 # {"$imagepolicy": "flux-system:podinfo:tag"}
```
