### DISCUSSION TITLE
Unable to deploy plain YAMLs using Kustomization example

### DISCUSSION THREAD

**Discussion by cnukwas** [fluxcd/flux2#3475] [Q&A] [answered]
Hi,

I'm newbie to Flux and able to install/sync Helm releases but seeing an issue when I tried to sync plain YAMLs by following [plan yamls](https://fluxcd.io/flux/faq/#can-i-use-repositories-with-plain-yamls) example in the documentation. I see that GitRepository and Kustomization resources are created and seeing following error in kustomize controller logs and and when I describe the resource as well. Using Flux2 v0.38.2.

I am not sure why the error is referring to a different CRD from kustomize.config.k8s.io/v1beta1. I really appreciate any help to resolve this issue.

```
kubectl -n flux-system describe kustomizations.kustomize.toolkit.fluxcd.io testdeploy
Name:         testdeploy
Namespace:    flux-system
API Version:  kustomize.toolkit.fluxcd.io/v1beta2
Kind:         Kustomization
Metadata:
Spec:
  Force:     false
  Interval:  10m0s
  Path:      ./releases/testdeploy
  Prune:     true
  Source Ref:
    Kind:  GitRepository
    Name:  testdeploy
Status:
  Conditions:
    Message:               kustomize build failed: Failed to read kustomization file under /tmp/kustomization-2223444/releases/testdeploy:
apiVersion for Kustomization should be kustomize.config.k8s.io/v1beta1
    Reason:                 BuildFailed
    Status:                 False
    Type:                   Ready
  Last Attempted Revision:  xyzz/37036033e876f41ffdgdgdgdfg
  Observed Generation:      1
Events:
  Type     Reason       Age   From                  Message
  ----     ------       ----  ----                  -------
  Warning  BuildFailed  48m   kustomize-controller  kustomize build failed: Failed to read kustomization file under /tmp/kustomization-2223444/releases/testdeploy:
apiVersion for Kustomization should be kustomize.config.k8s.io/v1beta1
```

Kustomization YAML contents:

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: testdeploy
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  path: "./charts/testdeploy/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: testdeploy
    namespace: flux-system
```
