### DISCUSSION TITLE
Proper way to setup Helm values with SOPS.

### DISCUSSION THREAD

**Discussion by SrDayne** [fluxcd/flux2#3480] [Q&A]
Hello.

I tried to setup SOPS encryption for dynamically created values file, as described here:
https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-secret-generated-with-kustomize-and-sops

Seems like it is not possible to setup them even following the guide.

Let's try follow the steps. Assume that sops key already installed in `flux-system` namespace, repo prepared and we use `age` encryption tool.
Our `.sops.yaml` file looks like this:
```
creation_rules:
  - path_regex: .values.yaml
    age: age14a2r6hs58mywqgaezfrwwv7hvckjz4622ehwc5y26sgekspzd5eqc3uyp3
```

First of all we create` values.yaml` file with values, only 2 values for simplicity:
```
data1: value1
data2: value2
```
Now, let's encrypt it:
`sops --encrypt --input-type=yaml --output-type=yaml ./values.yaml > values.yaml.encrypted`

In output we receive:
```
data1: ENC[AES256_GCM,data:SRr6ynfj,iv:aA0kuVltd43izSZUflp/rfKOOOLdyfo9pPJTD/+mfhs=,tag:Jo4PmntVSTcLQI30mZYOQg==,type:str]
data2: ENC[AES256_GCM,data:Q3wW3gDV,iv:HIaLTZosVCEj80yXJC0903H4nQnD+OqtapsAsjKjUFI=,tag:OjtHTBhLQVrya4v/6xle1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14a2r6hs58mywqgaezfrwwv7hvckjz4622ehwc5y26sgekspzd5eqc3uyp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjK0svQ3hqNUpUNzhPWDFO
            WmVwd0JiN1FPb3hvYW5mdXNta2hqRGpRaUFnClM4MXliQzl3STBjMG1MZ0dCK2FT
            K3ZDWmJZSEVjRVBGZ051SnUzdHNIU0EKLS0tIDVWeW5kSGlFQzBaK2pHTHo4R1dW
            dVBUdzlHRFFwL3VvSWZORWJ5LzZENVkKzkBDaCH+crZCKbb2iSghAwH220IJyHgk
            B6A3mvyf5KIX1RW9AyoTnUaoVYOiKd6LW8M6LRUYsJggb+yRaLXMpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-11T15:32:11Z"
    mac: ENC[AES256_GCM,data:YWqHAhXLEaoTijXb6mvdadxhrJkMBck0Uk0yHm+XQum37ZPjbVHCtwdv+jdYZ8IP7NgtblQ34TdA+ph6euh6QLbZlVw8KEmPeZi3GXOj0r/6wH7c9l4J1cXWmShmk598ygvVfQrSFKwfGG5NOhfj/ASeAmbcfc36vyPVEPxrC6I=,iv:xZOLsOmSLheG9RAJoe8NOBxgyaFpOW5RmAgGTFfiHtQ=,tag:eRmnIoTpC/6gyeTzn1t/gQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
```
Everything is correct for now. Now, let's generate our ConfigMap from encrypted file `values.yaml.encrypted`. Our `kustomization.yaml` looks like this:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-dev
resources:
  - namespace.yaml
configMapGenerator:
  - name: project-dev-values
    files:
      - values.yaml.encrypted
configurations:
  - kustomizeconfig.yaml
```
And here is the main part. Now, when we run `kubectl kustomize` we get in the output next manifest. We save it to `test.yaml` file.:
```
apiVersion: v1
kind: Namespace
metadata:
  name: project-dev
---
apiVersion: v1
data:
  values.yaml: |-
    data1: ENC[AES256_GCM,data:SRr6ynfj,iv:aA0kuVltd43izSZUflp/rfKOOOLdyfo9pPJTD/+mfhs=,tag:Jo4PmntVSTcLQI30mZYOQg==,type:str]
    data2: ENC[AES256_GCM,data:Q3wW3gDV,iv:HIaLTZosVCEj80yXJC0903H4nQnD+OqtapsAsjKjUFI=,tag:OjtHTBhLQVrya4v/6xle1g==,type:str]
    sops:
        kms: []
        gcp_kms: []
        azure_kv: []
        hc_vault: []
        age:
            - recipient: age14a2r6hs58mywqgaezfrwwv7hvckjz4622ehwc5y26sgekspzd5eqc3uyp3
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjK0svQ3hqNUpUNzhPWDFO
                WmVwd0JiN1FPb3hvYW5mdXNta2hqRGpRaUFnClM4MXliQzl3STBjMG1MZ0dCK2FT
                K3ZDWmJZSEVjRVBGZ051SnUzdHNIU0EKLS0tIDVWeW5kSGlFQzBaK2pHTHo4R1dW
                dVBUdzlHRFFwL3VvSWZORWJ5LzZENVkKzkBDaCH+crZCKbb2iSghAwH220IJyHgk
                B6A3mvyf5KIX1RW9AyoTnUaoVYOiKd6LW8M6LRUYsJggb+yRaLXMpg==
                -----END AGE ENCRYPTED FILE-----
        lastmodified: "2023-01-11T15:32:11Z"
        mac: ENC[AES256_GCM,data:YWqHAhXLEaoTijXb6mvdadxhrJkMBck0Uk0yHm+XQum37ZPjbVHCtwdv+jdYZ8IP7NgtblQ34TdA+ph6euh6QLbZlVw8KEmPeZi3GXOj0r/6wH7c9l4J1cXWmShmk598ygvVfQrSFKwfGG5NOhfj/ASeAmbcfc36vyPVEPxrC6I=,iv:xZOLsOmSLheG9RAJoe8NOBxgyaFpOW5RmAgGTFfiHtQ=,tag:eRmnIoTpC/6gyeTzn1t/gQ==,type:str]
        pgp: []
        unencrypted_suffix: _unencrypted
        version: 3.7.3
kind: ConfigMap
metadata:
  name: project-dev-values-8g4b4684c9
  namespace: project-dev
```
As we can see, our necessary for decryption  `sops` field now located inside values.yaml and is not accessible by sops utility which is expected result. And when we try to decrypt our generated manifest:
`sops --decrypt --input-type=yaml ./test.yaml`
we get:
`sops metadata not found`
which is also the expected result. And I assume that is the reason why kustomization controller can't decrypt this ConfigMap.

From documentation it is not clear what I am doing wrong. looks like it should not work by default.
So, I have two questions:
1. What(if) am I doing wrong with SOPS and values?
2. How to setup SOPS for Flux and Helm in a proper way?

I already read everything regarding SOPS and Helm in docs: 
https://fluxcd.io/flux/components/kustomize/kustomization/#secrets-decryption
https://fluxcd.io/flux/guides/mozilla-sops/
https://fluxcd.io/flux/use-cases/helm/#managing-secrets-and-configmaps
https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-secret-generated-with-kustomize-and-sops

Thanks in advance.
