### DISCUSSION TITLE
Using HTTPS_PROXY with Flux in conjunction with substitution

### DISCUSSION THREAD

**Discussion by xunholy** [fluxcd/flux2#3496] [General]
Hi, I'm trying to confirm if there is a better approach to what we're trying to do with our Flux bootstrap process. We're currently using a HTTP_PROXY which is configured similar to what we see here https://fluxcd.io/flux/cheatsheets/bootstrap/#using-https-proxy-for-egress-traffic however, we're currently not setting the value in plaintext as it's containing sensitive information with the credentials of the proxy user, therefore we're using substitution to inject the value from a secret whilst server-side rendering. This posing a problem though because to have server-side substitution work the pods need to reach a Ready status, however, without the fields for the proxy the pods remain in a crashloop and therefore require a manual edit on first install.

Is there a better method to bootstrap the flux instance with a proxy and/or substitution or is there really no way around this due to its chicken/egg nature in which manually injecting those variables post bootstrap 1 time is the only other option?

Example:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gotk-components.yaml
- gotk-sync.yaml

patches:
  - patch: |
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        decryption:
          provider: sops
          secretRef:
            name: sops-gpg
        postBuild:
          substitute: {}
          substituteFrom:
            - kind: Secret
              name: cluster-secrets
    target:
      kind: Kustomization
      name: flux-system
      namespace: flux-system
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                env:
                  - name: "HTTPS_PROXY"
                    value: "${HTTPS_PROXY_SECRET}"
                  - name: "NO_PROXY"
                    value: ".cluster.local.,.cluster.local,.svc"      
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
```
Note: original question in slack https://cloud-native.slack.com/archives/CLAJ40HV3/p1674116494331699

**Comment by xunholy** [comment]
One possible solution I'd propose is providing a way to set either `--proxy` or `--set-env` flags to the `flux bootstrap <>` command whereby it would create the initial instance with those values to allow it to start in a state where it can become `Ready` and then commence managing correctly through reconciliation of what is stored in Git.

Then it's a matter of having a e2e bootstrap process whereby those secrets can be provided which is much more feasible. This would work similar to how we can set `--toleration-keys` to allow pods to be scheduled appropriately.

@kingdonb @stefanprodan I'm keen to get your thoughts here

**Reply by kingdonb** [reply]
We had a bit of discussion about this at Flux Bug Scrub today and didn't really come to any conclusions, but we're wondering about the environment where you run `bootstrap` in and whether it's amenable to simply running a patch there when it's done.

So we understood the issue is that at bootstrap time, these substitutions aren't possible because the secret isn't present on the cluster yet, so there's nothing for bootstrap to substitute from. Is that about correct?

We're discussing what might be possible in terms of, if you pass an environment variable to the Flux cli at bootstrap time, and having it injected. Would that be something you'd consider as a solution, (I guess I'd have some questions about where the secret comes from, is it decrypted in a separate Flux Kustomization, that won't be applied until after bootstrap succeeded... that's why this is a problem yes?)

**Reply by xunholy** [reply]
Just to clarify a few points;

> these substitutions aren't possible because the secret isn't present on the cluster yet, so there's nothing for bootstrap to substitute from. Is that about correct?

Not quite. The Kubernetes secret and configmap resources respectively do exist as this is part of our cluster creation automation, the issue is that the source controller and kustomize controller aren't able to reach Github and therefore the kustomization never allows itself to life-cycle its own patch that is stored in Git using the above kustomize rules.

Ideally, being able to run bootstrap whilst passing your own custom envs/labels/annotations/affinity etc should be possible.

**Reply by kingdonb** [reply]
Bootstrap uses the patch that is in kustomize, as far as I know, but there may be some order-of-apply issues to work out. This is a known issue with the terraform provider, on first boot kustomize patches are not applied, but I don't think this *should* be an issue if you are using the actual flux bootstrap command.

That being said, we usually don't advise people to put secrets in the root kustomization because bootstrap *cannot* decrypt secrets, even with KMS, but without KMS there is a chicken-and-the-egg problem if you don't have a way of loading your decryption secret into the cluster ahead of Flux.

```yaml
        name: flux-system
        namespace: flux-system
      spec:
        decryption:
          provider: sops
          secretRef:
            name: sops-gpg
```

I see that's what you're doing, so I guess you worked that out. However, bootstrap will not put the `decryption` here, and I'm sure you already understand it will overwrite that if you wrote it directly into `flux-system` in `gotk-sync.yaml` because bootstrap doesn't have any decryption options, and I guess Flux doesn't anticipate that you'll have another way of getting the secret in here. There may be other reasons I have not fully understood. This is the part of the config that I'd suggest you change.

There should be no reason that substitution does not work at bootstrap time, when it's not related to decryption. So I would call this a bug. But it's sorta unclear to me whether the substituted HTTPS_PROXY_SECRET variable is supposed to come from one of the encrypted secrets or not. (Flux bootstrap does not decrypt secrets.)

I would like to reproduce it before officially calling a bug, just so I can see the shape of it. What you're describing sounds like a bug to me. Anyway, please know that we generally do not recommend enabling decryption in the root kustomization at all, because this can fail, which severely complicates the bootstrap, and then Flux will not be able to recover itself here. Is this proxy secret coming from an encrypted secret that sops-gpg is used to decrypt? Maybe we can support this a different way, if you happen to have that key in your keyring and pass its fingerprint to the flux CLI, it could be provided in-line to bootstrap, in order to support that type of workflow? This is not currently possible without some changes.

I always recommend putting the decryption in other Kustomizations, either centralized or such that the secrets are in the tenant with the app and decrypted separably in their own contexts (understanding that this answer does not help if what you need is the secrets at bootstrap time.) If you need a secret to reach the git repo, I'm not sure how to resolve that.

We usually recommend ambient credentials everywhere they can be used, KMS or similar, but even that will not solve this issue for you and that certainly does not solve the bootstrap issue, as CLI users will rarely if ever have access to KMS to decrypt the secrets, that will never help this issue. I think you would need to perform the decryption locally, not sure how many rules that might break for you, but I'd guess that would also be a deal-breaker, (even if Flux was doing it, as the local CLI user should not have access to decrypt secrets at all.)

Not sure what else to recommend here. Maybe there is a bug that we can fix, if we can narrow down to the specific behavior and isolate it? I'm still not completely sure I understand where the problem is coming from, (a deep-dive into the code to grok it properly may be needed.)
