### DISCUSSION TITLE
Datadog Metric Collection v2

### DISCUSSION THREAD

**Discussion by alexandros-genies** [fluxcd/flux2#3500] [Q&A]
Hey all. 

I'm using the new community driven Datadog integration found here: https://github.com/DataDog/integrations-extras/tree/master/fluxcd 

Since we're running Datadog agents via Helm, I'm following the Datadog autodiscovery installation here: https://docs.datadoghq.com/containers/kubernetes/integrations/?tab=kubernetesadv2 

I'm testing out the current confd setting in my Datadog agents:
```yaml
    confd:
      fluxcd.yaml: |
        ad_identifiers: 
          - fluxcd 
        init_config:  
          - service: fluxcd
        instances: 
```
        
However I am not seeing any metrics being sent over to Datadog. According to https://docs.datadoghq.com/integrations/fluxcd/ I should be able to see the metrics listed on that page.

I'm probably doing something wrong but in good Datadog fashion, the docs are quite limiting. What do I put under "instances"?
