### DISCUSSION TITLE
Can anyone beside flux can see repository clearly?

### DISCUSSION THREAD

**Discussion by eugercek** [fluxcd/flux2#3510] [Q&A] [answered]
Hi, I couldn't find this on anywhere sorry if it's a silly question.

My concern is this, let's say I use `GitRepository` with a private repository. Clearly flux can clone the repository, because it needs to see new desired state (even push). Are there anything like an SLA to guarantee that no one can see the repositories itself beside flux.

To get further advice form  you my use case is installing application on a someones machine, and sync with flux. They shouldn't see the application code. Probably best approach is using config repository, but I'm curious about the answer.

For example:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: my-secret-repository
  namespace: default
spec:
  interval: 5m
  url: https://github.com/eugercek/my-secret-repository
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: my-secret-repository
  path: "./kustomize"
  prune: true
  ```

Paths like the github url (`https://github.com/eugercek/my-secret-repository`) and kustomize path (`./kustomize`) are OK to share.
