### DISCUSSION TITLE
SOPS and illegal base64 data

### DISCUSSION THREAD

**Discussion by karl-dpg** [fluxcd/flux2#3546] [Q&A] [answered]
I'm trying to setup Flux with SOPS and AWS KMS, and I'm having some trouble getting the `kustomize-controller` to decrypt the secret and applied to the cluster. Some details below:

Service account annotated:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::36xxxxxxxx14:role/EKSOIDCRole
  labels:
    app.kubernetes.io/component: kustomize-controller
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.38.3
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: kustomize-controller
  namespace: flux-system
secrets:
- name: kustomize-controller-token-zxzd2
```

IAM Role:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::36xxxxxxxx14:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/6C394CC27FBED3001xxxxxxxxxxx"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "oidc.eks.us-east-1.amazonaws.com/id/6C394CC27FBED3001xxxxxxxxxxx:sub": "system:serviceaccount:*:*",
                    "oidc.eks.us-east-1.amazonaws.com/id/6C394CC27FBED3001xxxxxxxxxxx:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```

Policy attached to role: `arn:aws:iam::aws:policy/AdministratorAccess`

Secret:

```
apiVersion: v1
kind: Secret
metadata:
  name: test-secrets
  namespace: jenkins
  labels:
    app.kubernetes.io/name: test-secrets
    app.kubernetes.io/part-of: test-automation
type: Opaque
data:
  test-data-username: ENC[AES256_GCM,data:6QzunNfJlJIFS+3z,iv:UbykNkzuNFe+kUC4wrkpWjW4JkRFSJJL/lPf6ANNlRc=,tag:tS0Gtvs9B3wGkxvqax8JHQ==,type:str]
  test-data-password: ENC[AES256_GCM,data:UJccrD1HPEiJepcZODhJGNPzcr3/hUZFwp4UozHlnnRP1H9Zdx9pROAm60I=,iv:0kqzEKY+sp/jyLRul3WRNvMlGHQVPWgZSR6diwJzKYg=,tag:LXBOniP744RtmIgt1NBdKQ==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:36xxxxxxxx14:key/efa527dd-64fc-451a-97a2-a5b02a907e5b
      created_at: "2023-01-31T08:15:03Z"
      enc: AQICAHiv5rlX1C2uLtDuHDwLLlliuGjAksdyvA5iB8AnPYeiAQEO5XUbXLVs1tiS4Cg/BRHOAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMb3yt27HSOglF4nuhAgEQgDuZ65wYm2eKc1+hY672DBJnVfFMCK3DyqAHaBy119mXbgxyTE8a4BXHXOfLHzJAimn2dv7m4IGs7qgPOQ==
      aws_profile: ""
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-01-31T08:15:06Z"
  mac: ENC[AES256_GCM,data:EuxBQS3wX4+guH+wdkl+BZnS5TPXNDZTeqULGm08aLkLa8FmUR000DC1iQB4BBFc1SeyGVIbspFUNGThQiA0hz2E091VYzxVw9PV43kouaVnMrW4I83aWIOxSX5y6Nao2nCUSVrKMrF0Y7VO7+fHBbpV9xHluWeuo95GtL1m8xM=,iv:aeDnFF8z96kqsad6smeVHwcSLeSp3KjF5xOKH52aXHM=,tag:laYo+T/g3AujVPn8o4xoGg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
```

Flux reconciliation error:

```
{
   "level":"error",
   "ts":"2023-01-31T16:42:35.573Z",
   "msg":"Reconciliation failed after 186.012676ms, next try in 10m0s",
   "controller":"kustomization",
   "controllerGroup":"kustomize.toolkit.fluxcd.io",
   "controllerKind":"Kustomization",
   "Kustomization":{
      "name":"tools",
      "namespace":"flux-system"
   },
   "namespace":"flux-system",
   "name":"tools",
   "reconcileID":"577ff31e-923e-4968-84ba-f648d49f3bec",
   "revision":"master/9a117188f103cd68ea4238f8291b92fec5ea9917",
   "error":"Secret/jenkins/test-secrets validation error: error decoding from json: illegal base64 data at input byte 3"
}
```

Been banging my head for a couple of days on this. Would appreciate if anyone could point me in the right direction. Thanks

**Comment by karl-dpg** [comment, marked as answer]
Found the problem. The documentation makes reference to add the `decryption.provider` in the `Kustomization` resources. The reference is always made in conjunction with the GPG keys. I thought this configuration was only needed when using local GPG keys and can be omitted when using cloud providers. That is not the case. The `Kustomization` must have the settings without the reference to the local secret:

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tools
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./services/bases/tools
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
```

Also, all the resource mentioned in the original post are necessary and correct.

Suggestion, maybe the documentation could be clearer for this scenario.

**Reply by mloskot** [reply]
Cross-referencing confirming solution https://github.com/fluxcd/kustomize-controller/issues/612#issuecomment-1445173370

**Comment by romankor** [comment]
I had the same issue i had to change `data` to `stringData` to make it work ...

**Reply by mariusrugan** [reply]
The whole ordeal comes from not specifying the sops secret in the Flux Kustomization. 

Declaring it in a top level Kustomization for example - "cluster" folder which includes several others "app-A" and "app-B", is not sufficient, it has to be declared with each Kustomization, if they exist.

```yaml
  ...
  decryption:
    provider: sops
    secretRef:
      name: sops-age
```
