### DISCUSSION TITLE
How to extract semver for tags that aren't quite semver?

### DISCUSSION THREAD

**Discussion by 2fst4u** [fluxcd/flux2#3574] [Q&A] [answered]
I'm using image policies to update my tags for a lot of my images, in particular ones that aren't under my control.

For may of them they don't follow proper semver. They might tag releases as "version-1.2.3" or "v.1.2.3" or something along those lines. So the semver is in there somewhere, but it's not correct enough to be parsed as is.

I can't get the hang of the regex filters to try and extract this. Does anyone have a regex filter or extract that would work for this? I've tried using "alphabetical" sort but for some images this ends up with a lot of Fudd included in the sort and can end up with undesired tags appearing at the bottom of the list.

**Comment by gionn** [comment]
at least the versioning scheme should be consistent, then you can use the appropriate regex to extract a semver from it.

**Reply by 2fst4u** [reply]
Yes but that's what I'm asking for help with.

**Reply by 2fst4u** [reply]
Any ideas?

**Comment by 2fst4u** [comment, marked as answer]
After much research I managed to find the answer. The flux docs don't explicitly mention this but one of the examples given shows a method of extracting relevant information.

https://fluxcd.io/flux/guides/image-update/#imagepolicy-examples

In the first example the filter `^main-[a-fA-F0-9]+-(?P<ts>.*)` is used. On the next line the information `$ts` is then extracted.

This led me to look into how it was extracted until I came across the regex concept of "named capturing groups", explained in further detail here https://www.regular-expressions.info/named.html

The key part of the regex filter is `(?P<ts>.*)` where `ts` is the arbitrary name of the capturing group which is called upon later and `.*` in this case represents a wildcard catchall of basically anything that is given after the rest of the full regex earlier is matched.

This means you can use that format, surrounded by the relevant regex to filter the tag you're looking at. One example I was trying to extract semver from is an image repository that has several versions of images, some with basic semver like `v[x.y.z]`, and some tags with `v[x.y.z]-vaapi`. I specifically want the "vaapi" ones. My regex starts like this: `^v(?P<semver>something needs to go here to catch valid semver)-vaapi$`.

Then I found that semver has an official regex to capture all valid versions, found here: https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string

Which gives us `^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`

If we ignore the `^` at the start and leave the one at the start of my own regex, and the `$` at the end in place of my own one at the end, we end up with this:

`^v(?P<semver>(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)-vaapi$`

Which will find anything starting with a "v", followed by a valid semver, followed by "-vaapi".

Put together with an `extract` line in my manifest, my flux ImagePolicy looks like this:

```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: myDocker
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: myDocker
  filterTags:
    pattern: '^v(?P<semver>(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)-vaapi$'
    extract: '$semver'
  policy:
    semver:
      range: '^1.x'
```
