### DISCUSSION TITLE
Using GitRepo for Helm Charts with many different git tags

### DISCUSSION THREAD

**Discussion by joncrlsn** [fluxcd/flux2#3596] [Q&A] [answered]
We are converting from flux1 to flux2.   Below is a typical flux1 HelmRelease file that loads Helm Charts from a git repo.  Notice the spec.chart.ref tag is specified in the HelmRelease file.

Every one of our 1800 HelmRelease files *could* have a different chart ref tag.  How would we replicate this in flux2 without creating 1800 GitRepository objects, all pointing the same repo, with different git tags?  Is there a way to do that? 

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: example-user-query
spec:
  releaseName: example-user-query
  chart:
    git: ssh://git@bitbucket.example.com/ccc/example-helm-charts.git
    path: example-user-query
    ref: 0.40.57
  values:
    image:
      repository: artifactory.example.com/docker/xyz/example-user-query
      tag: 2022-12-28T05-18-8c6174c-33
```
