### DISCUSSION TITLE
Deactivate flux-edit and flux-view ClusterRole

### DISCUSSION THREAD

**Discussion by siegenthalerroger** [fluxcd/flux2#3616] [Q&A] [answered]
In our current setup we'd like to be able to give edit permissions for the different parts of flux to different roles. With v0.40 this becomes impossible as according to the documentation the `flux-edit` role is aggregated to the `edit` role. Is there a way to deactivate the roles or deactivate the aggregation?

**Comment by stefanprodan** [comment, marked as answer]
>  Is there a way to deactivate the roles or deactivate the aggregation?

Sure, you can do a patch delete during bootstrap.

**Reply by stefanprodan** [reply]
Can you try this patch and let me know if it solves the issue for you?

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: flux
      $patch: delete
    target:
      kind: ClusterRole
      name: "(flux-view|flux-edit)"
```

**Reply by stefanprodan** [reply]
Docs: https://fluxcd.io/flux/cheatsheets/bootstrap/#disable-kubernetes-cluster-role-aggregations

**Reply by siegenthalerroger** [reply]
Hi stefan

That actually didn't work for me, I had to change the name as it wasn't as you had.

```
  - patch: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: flux
      $patch: delete
    target:
      kind: ClusterRole
      name: "(flux-view|flux-edit)-flux-system"
```
