### DISCUSSION TITLE
extra data or labels in alert

### DISCUSSION THREAD

**Discussion by Baitanik** [fluxcd/flux2#3621] [General]
Hello,
We have following Alert configuration for fluxCD 
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: flux-notification-alert
  namespace: flux-system
spec:
  summary: "flux cluster notification"
  providerRef:
    name: alertmanager
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmChart
      name: '*'
    - kind: HelmRelease
      name: '*'

```

which is working fine, but we need to add one label cluster_name , for monitoring purpose, as from different clusters alert will come to central place..
Please let us know how can we add one custom label(e.g cluster_name) in Alert
