### DISCUSSION TITLE
fluxcd sending status resolved notification although it is not resolved

### DISCUSSION THREAD

**Discussion by Baitanik** [fluxcd/flux2#3631] [General] [answered]
We have setup fluxcd alert notification to promethes alert manager. 
We have following configuration : 

```
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: flux-notification-alert
  namespace: flux-system
spec:
  summary: "flux cluster notification"
  providerRef:
    name: alertmanager
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'

```

Which is working , but flux is also sending clear alarm (status: resolve) after few minutes, although the issue is still here.

```
{'status': 'firing', 'labels': {'alertname': 'FluxGitRepositoryGitOperationFailed', 'kind': 'GitRepository', 'name': 'shell-repository', 'namespace': 'flux-system', 'reason': 'GitOperationFailed', 'reportingcontroller': 'source-controller', 'severity': 'error', 'timestamp': '2023-02-24 08:27:19 +0000 UTC'}, 'annotations': {'message': "failed to checkout and determine revision: unable to list remote for 'https://company.ccm.monitoring.test.com/gitea/ccm/shell.gt': repository not found", 'summary': 'accm18anbe101'}, 'startsAt': '2023-02-24T08:27:19.876957834Z', 'endsAt': '0001-01-01T00:00:00Z', 'generatorURL': '', 'fingerprint': 'ade764a44f990229'}
```

```
{'status': 'resolved', 'labels': {'alertname': 'FluxGitRepositoryGitOperationFailed', 'kind': 'GitRepository', 'name': 'shell-repository', 'namespace': 'flux-system', 'reason': 'GitOperationFailed', 'reportingcontroller': 'source-controller', 'severity': 'error', 'timestamp': '2023-02-24 08:27:19 +0000 UTC'}, 'annotations': {'message': "failed to checkout and determine revision: unable to list remote for 'https://company.ccm.monitoring.test.com/gitea/ccm/shell.gt': repository not found", 'summary': 'accm18anbe101'}, 'startsAt': '2023-02-24T08:27:19.876957834Z', 'endsAt': '2023-02-24T08:32:19.876957834Z', 'generatorURL': '', 'fingerprint': 'ade764a44f990229'}
```

Still persists , but flux sent an notification with status resolve.. any idea why flux is sending this resole status although issue is still there.
