### DISCUSSION TITLE
Make `spec.secretRef` in Flux's `Kustomization` namespaceable

### DISCUSSION THREAD

**Discussion by Goorzhel** [fluxcd/flux2#3639] [Proposals] [answered]
I wanted to do something like this:
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: top-level
  namespace: flux-system
spec:
<snip>
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        kind: Kustomization
        metadata:
          name: not-used
          namespace: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
              namespace: flux-system # <-------------
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1beta2
        kind: Kustomization
        labelSelector: substitution.flux.home.arpa/disabled notin (true)
        namespace: ".*"
```
so that I could keep `Kustomizations` in the namespaces where they deploy their apps (which'd make `k get ks` easier):
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: breezewiki
  namespace: default # <-------------
spec:
  sourceRef:
    kind: GitRepository
    name: kubernetes
    namespace: flux-system
<snip>
# automatically patched with spec.decryption
```

Instead, I must have _all_ `Kustomizations` in `ns/flux-system` because [`spec.decryption`](https://fluxcd.io/flux/components/kustomize/api/#kustomize.toolkit.fluxcd.io/v1beta2.Decryption) can [only reference same-namespace objects](https://pkg.go.dev/github.com/fluxcd/pkg/apis/meta#LocalObjectReference). If I try anyway:
> Kustomization/flux-system/top-level dry-run failed, error: failed to create typed patch object (flux-system/top-level; kustomize.toolkit.fluxcd.io/v1beta2, Kind=Kustomization): .spec.decryption.secretRef.namespace: field not declared in schema

I haven't thought through the security implications of this idea, hence this Discussion instead of a PR.
