### DISCUSSION TITLE
No kubernetes events during helmrelease uninstall?

### DISCUSSION THREAD

**Discussion by BobWorkGit** [fluxcd/flux2#3664] [Q&A]
Hello all. I am trying to move through my different Jenkins stages based on flux notifications (kubernetes events). With the simple install case helm release seems to return an event saying helm install started and succeeded, with the kustomization reconciliation successful coming in only after the helm release has been successfully installed. This allows me to base the install status from the successful reconciliation in the installation case. But during uninstall case when I remove helmrelease and kustomization from the repo, it seems like there are no helmrelease events generated to indicate the uninstall status on the cluster. HelmRelease eventually just disappears from the cluster once it is deleted successfully, the only mention of the uninstall I could find was in the helm controller logs. Not only that, the kustomization reconciliation status comes back successful almost instantly even though the uninstall takes several minutes. This means I can't really use the reconciliation status as my indicator anymore. 

-Why are there no events coming during uninstall, like it is for install? 
-Also why does it says reconciliation succeeded while the helm release is still present on the cluster? 
-Any suggestions on possible modifications of the helm release to start generating these events in the uninstall case?
-Any suggestions in general?
-Is this a missing feature? 

Things to note:
-I am using an older flux version: **flux version 0.39**
$ flux version -n ns
helm-controller: v0.29.0
kustomize-controller: v0.33.0
notification-controller: v0.31.0
source-controller: v0.34.0

My helmrelease and kustomization objects in a nutshell

- my-helmrelease.yaml
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-app-build-no
spec:
  interval: 1m
  timeout: 25m
  releaseName: my-app-build-no
  targetNamespace: ns
  storageNamespace: ns
  chart:
    spec:
      chart: my-chart
      version: 1.0.0
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
```

- my-kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  resources:
  - my-helmrelease.yaml
  namespace: ns
  files:
  - values.yaml=my-values.yaml
```

Thanks and any help is appreciated!
