### DISCUSSION TITLE
Customize Flux manifests and variable substitution

### DISCUSSION THREAD

**Discussion by mosman-lvmh** [fluxcd/flux2#3677] [Q&A] [answered]
Hello all,

We are using Flux to manage several clusters in several Google Cloud projects. We try also to make our gitops repository a base for other teams, so that they can fork our repo to create their own.

To ease the work for those teams, we extracted as much as we can all the values that are team-dependent. For example, we extracted the GC project ids, service account names, etc.

The only thing that remains is the service account name used by the image reflector automation controller.

We followed the documentation [Customize Flux manifests](https://fluxcd.io/flux/installation/#customize-flux-manifests), so we have this `kustomization.yaml` file under `clusters/mycluster/flux-system` folder

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - path: patches/image-reflector-controller-sa.yaml
    target:
      version: v1
      kind: ServiceAccount
      name: image-reflector-controller
      namespace: flux-system
  - path: patches/image-reflector-controller-deploy.yaml
    target:
      version: v1
      group: apps
      kind: Deployment
      name: image-reflector-controller
      namespace: flux-system
  - path: patches/safe-to-evict.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
```

The last two patches are ok because their content is not dependent on the cluster or the team, but the first one `patches/image-reflector-controller-sa.yaml` needs to be changed per team and cluster.

I tried to use interpolation, but as _kustomize_ doesn't support it, I am stuck here with this content for `patches/image-reflector-controller-sa.yaml`:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-reflector-controller
  namespace: flux-system
  annotations:
    # Next commented line doesn't work
    # iam.gke.io/gcp-service-account: ${flux_artifactregistry_service_account_email}
   iam.gke.io/gcp-service-account: flux-artifactregistry@myproject.iam.gserviceaccount.com
```

The vars are declared in a `.env` file used in a `configMapGenerator` definition declared in the kustomization file in the parent folder:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-ks.yaml
  - flux-system
configMapGenerator:
  - name: cluster-vars
    namespace: flux-system
    envs:
      - .env
    options:
      disableNameSuffixHash: true
```

Here is the `clusters/mycluster` subtree full content:

```
|____flux-system
| |____patches
| | |____safe-to-evict.yaml
| | |____image-reflector-controller-deploy.yaml
| | |____image-reflector-controller-sa.yaml
| |____kustomization.yaml
| |____gotk-sync.yaml
| |____gotk-components.yaml
|____cluster-ks.yaml
|____kustomization.yaml
|____.env
```

By the way, I am trying to avoid repeating these patches files in every cluster folder, so if I can move this patches in the `clusters/base` for example that would be great.

Any advise or guidance on how to handle better than with a _TODO_ comment in the `.env` explaining that the var is not used and must be replaced in the  `image-reflector-controller-sa.yaml` file.

**Comment by mosman-lvmh** [comment, marked as answer]
I will answer myself as I finally found a solution using [kustomize replacements mechanism](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/)

Here is the target file structure:

```
|____flux-system
| |____kustomization.yaml
| |____gotk-sync.yaml
| |____gotk-components.yaml
|____patches
| |____image-reflector-controller-sa.yaml
| |____image-reflector-controller-deploy.json
|____cluster-ks.yaml
|____kustomization.yaml
|____.env
```

First, I have moved the `patches` folder outside of the `flux-system` folder to let this directory fully managed by flux.

The `./flux-system/kustomization.yaml` is therefore as simple as this:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
```

The parent folder `./kustomization.yaml` now contains the patches definition and also the **replacements** that makes use of the **configMap**:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-ks.yaml
- flux-system
configMapGenerator:
- envs:
  - .env
  name: cluster-vars
  namespace: flux-system
  options:
    disableNameSuffixHash: true
replacements:
- source:
    fieldPath: data.flux_artifactregistry_service_account_email
    kind: ConfigMap
    name: cluster-vars
    version: v1
  targets:
  - fieldPaths:
    - metadata.annotations.[iam.gke.io/gcp-service-account]
    select:
      kind: ServiceAccount
      name: image-reflector-controller
      namespace: flux-system
      version: v1
patches:
- path: patches/image-reflector-controller-sa.yaml
  target:
    kind: ServiceAccount
    name: image-reflector-controller
    namespace: flux-system
    version: v1
# https://fluxcd.io/docs/guides/image-update/#using-native-gcp-gcr-auto-login
- path: patches/image-reflector-controller-deploy.json
  target:
    group: apps
    kind: Deployment
    name: image-reflector-controller
    namespace: flux-system
    version: v1
# https://fluxcd.io/docs/cheatsheets/bootstrap/#safe-to-evict
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
    spec:
      template:
        metadata:
          annotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=flux
```

This `.env` file is used to generate a **configMap** named `cluster-vars`, it contains several properties such the one that is interesting here `flux_artifactregistry_service_account_email`.
This **configMap** is used as the source of the kustomize **replacements** block, and the value of the previous key is referenced as `data.flux_artifactregistry_service_account_email`.
The **targets** block of the **replacements** describe where to use this value.
We tell `kustomize` to replace the content of the field `metadata.annotations.[iam.gke.io/gcp-service-account]` of the `ServiceAccount` named `image-reflector-controller` inside `flux-system`.

Finally, inside the `./patches/image-reflector-controller-sa.yaml` file, you can put whatever value you want for the `sa`annotation as it will be fully replaced by `kustomize` during build:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-reflector-controller
  namespace: flux-system
  annotations:
    iam.gke.io/gcp-service-account: PLACEHOLDER # replaced dynamically by kustomize
```
