### DISCUSSION TITLE
help installing OCI ack-s3-controller chart

### DISCUSSION THREAD

**Discussion by masterkain** [fluxcd/flux2#3690] [Q&A] [answered]
I'm following this guide: https://aws-controllers-k8s.github.io/community/docs/user-docs/install/#install-an-ack-service-controller-with-helm-recommended

this is what I have:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ack-s3-controller
spec:
  releaseName: ack-s3-controller
  reconcileStrategy: ChartVersion
  chart:
    spec:
      chart: ack-s3-controller
      version: "v1.0.2"
      sourceRef:
        kind: HelmRepository
        name: ack-s3-controller
        namespace: flux-system
  interval: 3m0s
  install:
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  values:
    aws:
      region: eu-west-1
```

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ack-s3-controller
spec:
  type: "oci"
  provider: aws
  interval: 30m
  url: oci://public.ecr.aws/aws-controllers-k8s/s3-chart
```

but I get

```
chart pull error: failed to download chart for remote reference: failed to get 'oci://public.ecr.aws/aws-controllers-k8s/s3-chart/ack-s3-controller:v1.0.2': public.ecr.aws/aws-controllers-k8s/s3-chart/ack-s3-controller:v1.0.2: not found
```

do I need to authenticate with ecr somehow? in the guide it mentions `aws ecr-public get-login-password --region us-east-1 | helm registry login --username AWS --password-stdin public.ecr.aws` before performing a manual install, can I do that with flux?

thanks
