### DISCUSSION TITLE
Variable substitution of lists

### DISCUSSION THREAD

**Discussion by gberche-orange** [fluxcd/flux2#3692] [Proposals] [answered]
I need to provision a set of users into a group.user.openshift.io CR, see https://docs.openshift.com/dedicated/3/rest_api/user_openshift_io/group-user-openshift-io-v1.html with a users array

```yaml
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: my-group
users:
  - "userId1"
  - "userId2"
...
```

In order to avoid leaking the user ids in the gitrepo, I'd like to use variable substitution to load the user names from a configmap/secret (which itself is managed in a vault)

I understand that currently the kustomize controller variable substitution is only supporting string https://fluxcd.io/flux/components/kustomize/kustomization/#variable-substitution

## Proposal

Use autoboxing from json or yaml syntax

Given a variable `users` with content 
```json
["user1","user2"]
```

Given a Kustomization with 

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
spec:
  interval: 5m
  path: "./apps/"
  postBuild:
    substitute:
      #users is holding a valid json array structure
      users: | 
         ["user1","user2"]
```

When the following resource gets rendered by kustomize controler

```
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: my-group
users: ${users[@]}
```

Syntax ${users[@]} is inspired from bash arrays: represents all the elements the users array. See https://opensource.com/article/18/5/you-dont-know-bash-intro-bash-arrays

then the rendered yaml is 

```
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: my-group
users: 
- user1
- user2
```

### Current workaround

Define an inline HelmChart within the git repo 

```
$ tree
.
├── kustomization.yaml
├── managed-services-operators-group-helm-release.yaml
└── openshift-group-helm-chart
    ├── Chart.yaml
    ├── templates
    │   └── group.yaml
    └── values.yaml
```

openshift-group-helm-chart/values.yaml:
```yaml
# Name of the group
name: "a-group"

# List of users in a valid YAML array format
users: |
  - user1
  - user2
  - user3
  - user4
```

openshift-group-helm-chart/templates/group.yaml:
```yaml
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: {{ .Values.name}}
users:
{{ .Values.users}}
```

managed-services-operators-group-helm-release.yaml:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: managed-services-operators-release
spec:
  chart:
    spec:
      chart: [...]/openshift-group-helm-chart
      sourceRef: ...
  values:
    # List of users in a valid YAML array format
    users: ${external_gcp_poc_managed_services_users_array_yaml}    # name of the group to provision
    name: managed-services-operators
  interval: 2m
```

**Comment by gberche-orange** [comment, marked as answer]
Actually, if a variable is formatted as a string holdin a json array (e.g. `["usera", "userb", "userc" ]`, then flux 0.40 interpolates it as an array within K8S resources. 

```yaml
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: managed-services-operators
# noinspection KubernetesUnknownValues
users: ${services_users_array_json}
```
Likely related improvement was brought through 

https://github.com/fluxcd/pkg/commits/main/kustomize
and possibly https://github.com/fluxcd/pkg/commit/00a9a2db7f5f9c81787565840f3e9c6de96bd44f


Additionally, my workaround using Helm release and interpolating plain yaml is not properly working, and results in yaml parsing errors. See https://github.com/fluxcd/kustomize-controller/issues/518
