### DISCUSSION TITLE
Option to fail reconciliation when substitution variable doesn't exist

### DISCUSSION THREAD

**Discussion by kaybinwang** [fluxcd/flux2#3712] [Proposals]
Today, I spent an hour debugging an online production issue only to realize that it was caused by a manifest that referenced `${1}` which unintentionally invoked Flux's variable substitution.

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-with-trailing-slash
spec:
  redirectRegex:
    permanent: true
    regex: (.*)
    replacement: ${1}/  # Flux substituted empty string for ${1}
```

It caught me off guard since our builds are so massive, it's sometimes hard to remember which deployments are using variable substitution. Anyways, this type of developer error should've ideally been caught at build time. A fail fast approach would've saved us a lot of time and would've prevented the issue from going into production. IMO this could be implemented as an opt-in setting in `spec.postBuild` to avoid breaking changes.

For example,
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
spec:
  postBuild:
    allVariablesRequired: false  # opt into failing when a variable is missing
    substituteFrom:
    - kind: ConfigMap
      name: cluster-vars  
```

I know the current recommendation is to simply use the `$$` notation or annotation, but this requires you to be aware of the problem in the first place. It's additional cognitive overhead, especially for new engineers. We all make mistakes at the end of the day, so it's helpful to hand guardrails like this in place that protect us.
