### DISCUSSION TITLE
after patched NO_PROXY HTPPS_PROXY and HTTP_PRPOXY to source controller, getting error message

### DISCUSSION THREAD

**Discussion by RaimundasR** [fluxcd/flux2#3723] [General] [answered]
after patched NO_PROXY HTPPS_PROXY and HTTP_PRPOXY to source controller, getting error message, can't find out what could be wron, trying to deploy podinfo to microk8s single node k8s cluster which running behind proxy... Any suggestion why it can't resolve and download  artifact ?

```
False   failed to download artifact, error: GET http://source-controller.$(RUNTIME_NAMESPACE).svc.cluster.local./helmc
hart/tools/tools-podinfo/podinfo-6.3.5.tgz giving up after 10 attempt(s): Get "http://source-controller.$(RUNTIME_NAMESPACE).svc.cluster.local./helmchar
t/tools/tools-podinfo/podinfo-6.3.5.tgz": dial tcp: lookup source-controller.$(RUNTIME_NAMESPACE).svc.cluster.local.: no such host
```

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: tools
spec:
  interval: 10s
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: tools
spec:
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: '>4.0.0'
  interval: 10s
  ```
  
  thank you very much in advance for your help!!!
