### DISCUSSION TITLE
Broken commits get stuck for a long time

### DISCUSSION THREAD

**Discussion by vytautaskubilius** [fluxcd/flux2#3725] [Q&A]
Whenever I commit something broken (e.g. a manifest with a syntax error), Flux takes a very long time (longer than the usual 1 minute git refresh window - it feels like it's 10 minutes or more) to try and apply any subsequent changes to that Kustomization. I can commit a fix within a minute or two, but then I see Flux doing nothing and just trying in vain to apply the broken commit until it eventually fixes itself. Trying to force things with a `flux reconcile` or `flux suspend/resume` doesn't seem to have any effect. It feels like it's happening only when I have the `wait` health check set up (but it might also be that that only highlights the underlying problem that I otherwise might not notice before it resolves itself). While it's not an issue most of the time, it's particularly annoying when I need to quickly fix something during an incident.

Here's and example config with various timeouts and intervals that reflects what I've set up:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: ssh://git@github.com/myorg/myrepo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/mycluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: myapp
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kustomize/apps/myapp/production
  prune: true
  wait: true
  timeout: 10m0s
  retryInterval: 2m0s
```

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: myrepository
spec:
  interval: 1m
  url: https://somerepo.github.io/charts
```

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mychart
spec:
  interval: 5m
  chart:
    spec:
      chart: mychart
      version: '1.2.3'
      sourceRef:
        kind: HelmRepository
        name: myrepository
        namespace: default
      interval: 1m
  values: {}
```

It feels like I might be missing something obvious (like a timeout or interval that I've misunderstood and should tune down, or something like that), so hopefully someone here can point out what it is :)

**Comment by netrusov** [comment]
I'm switching to Flux right now and I'm making a lot of stupid mistakes (haven't worked with k8s/kustomize before) which always results in stuck resources.

as OP said, reconciliation doesn't work if `wait: true` is used, nothing helps, actually. sometimes restarting kustomize-controller can release the lock, but this is not the right way, obviously, and I'm not sure what could go wrong.

**Reply by stefanprodan** [reply]
Lower the timeout on the Flux Kustomization while you work on building the cluster, so it will give up fast waiting for things that will never come up. Something like:

```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myapp
  namespace: flux-system
spec:
  interval: 60m
  timeout: 1m
  retryInterval: 5m
```

This gives you a window of 4 minutes to push new changes after each failure, and it will see new changes in max 1m.
