### DISCUSSION TITLE
Multiple instances of application within sub directories

### DISCUSSION THREAD

**Discussion by sbellan** [fluxcd/flux2#373] [Q&A]
If I have multiple applications under a sub-directory like this,

```
cluster1
   inst1
     kustomization.yaml
   inst2
     kustomization.yaml
   inst3
     kustomization.yaml
```

can I just have one kustomization resource like the following to get all the apps deployed, or should I be create separate Kustomization created for each of the subdirectories?

```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: apps
spec:
  interval: 10m0s
  path: ./cluster1
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-repo

```

Thank you.
