### DISCUSSION TITLE
Sorting image tags by date

### DISCUSSION THREAD

**Discussion by gionn** [fluxcd/flux2#3734] [Q&A] [answered]
Hello,

on flux1 when filtering image tags via regex there was no implicit sort and the most recent tag matching the regex was selected.

With flux2 it's possibile to have the same behaviour? From my test it looks like that sorting has become a mandatory parameter.

**Comment by tun0** [comment]
Those timestamps that were used in Flux1 were rather unreliable. They caused us pain more times than I could count. The decision to change the ordering logic in Flux2 is pretty much only for the better.

**Reply by gionn** [reply]
that's actually great for images that use semver properly or the ones with an incremental build number. However for more creative scenarios looks like we can't do anything else than ask to change the image versioning scheme, that may not be something that could always be solved on our side.

**Comment by makkes** [comment]
Please see https://fluxcd.io/flux/components/image/imagepolicies/#policy and https://fluxcd.io/flux/guides/sortable-image-tags/.

**Reply by gionn** [reply]
Thanks, at least now is clear that the intention here is to force to have support for a bunch of versioning scheme but again if the images are produced by third-parties and out of our control there is no much room for a proper solution other than asking to fix the image tags.

**Comment by wilmardo** [comment, marked as answer]
Since this is one of the few results to turn up when Googling this, here is a working solution:
```yaml
      spec:
        filterTags:
          # make it sortable as an absolute number otherwise month 9 will always be before 10/11/12 since they start with 1
          pattern: '^(?P<year>[0-9]*)\.(?P<month>[0-9]*)*\.(?P<day>[0-9]*)*$'
          extract: '$year$month$day'
        policy:
          numerical:
            order: asc
```
