### DISCUSSION TITLE
kustomize remote resources

### DISCUSSION THREAD

**Discussion by sbellan** [fluxcd/flux2#374] [Q&A]
If the kustomization.yaml file has references to remote git repositories like this,

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
namePrefix: test-
commonLabels:
  app: test
  fqdn: test.somedomain.com
resources:
- https://bitbucket.org/project1/repo1.git/example-base
```

Will this work and how to specify credentials for the remote resource?
