### DISCUSSION TITLE
Missing alerts about reconciliation failed: Helm upgrade failed

### DISCUSSION THREAD

**Discussion by mloskot** [fluxcd/flux2#3753] [Q&A] [answered]
I'm observing release failure in the Kubernetes events:

```
$ kubectl get -n test events
LAST SEEN   TYPE      REASON             OBJECT                         MESSAGE
4m4s        Normal    NotTriggerScaleUp  pod/myapp-6df44f5f8-9gnlp  pod didn't trigger scale-up: 5 persistentvolumeclaim "myapp-pvc-d" not found
12m         Warning   FailedScheduling   pod/myapp-6df44f5f8-9gnlp  0/5 nodes are available: 5 persistentvolumeclaim "myapp-pvc-d" not found. preemption: 0/5 nodes are available: 5 Preemption is not helpful for scheduling.
3m5s        Normal    info               helmrelease/myapp          Helm upgrade has started
18m         Warning   error              helmrelease/myapp          Helm upgrade failed: timed out waiting for the condition...
18m         Warning   error              helmrelease/myapp          reconciliation failed: Helm upgrade failed: timed out waiting for the condition
```

and Flux says this:

```
$ flux get -n test helmreleases
NAME    REVISION     SUSPENDED       READY   MESSAGE
myapp                False           Unknown Reconciliation in progress
```

I have configured Flux alerts posted to MS Teams for the `info` level, without any exclusions:

```yaml
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: msteams-alert-info
  namespace: flux-system
spec:
  providerRef:
    name: msteams
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: '*'
  - kind: HelmRelease
    name: '*'
  - kind: HelmChart
    name: '*'
  - kind: HelmRepository
    name: '*'
  - kind: Kustomization
    name: 'azure-hosting-gitops'
```

Why Flux is not dispatching any notifications about the `reconciliation failed`?

I noticed in the K8s events the `TYPE=Warning` and `REASON=error`, which seems to suggest the event is not considered of severity of error. Is that the reason of no alerts?

Am I missing any configuration that will allow to receive notifications about such `reconciliation failed` warnings-like-errors?
