### DISCUSSION TITLE
Helm Releases fail with  - HelmChart ' ' is not ready

### DISCUSSION THREAD

**Discussion by ghost** [fluxcd/flux2#3757] [Q&A] [answered]
When I apply helm releases to the cluster (10-15 of them), initial reconciliation for each of them fails with **HelmChart ' ' is not ready** message. After some time second reconciliation starts and all of them become successful and ready. 
Could you please advice how can I avoid failing on initial reconciliation ?

I tried `disableWait` for each section, but no result.

```
spec:
  chart:
    ....
  install:
    createNamespace: false
    disableHooks: true
    disableOpenAPIValidation: true
    disableWait: true
    disableWaitForJobs: true
  interval: 200m
  maxHistory: 2
  timeout: 2m
  uninstall:
    disableHooks: true
    disableWait: true
    keepHistory: false
  upgrade:
    disableHooks: true
    disableOpenAPIValidation: true
    disableWait: true
    disableWaitForJobs: true
    force: true
    preserveValues: false
```

```
kubectl get hr (initial reconciliation, when helm releases were just created)
lw-data-provider-http   41s   False     HelmChart 'service/th2-demo-books-lw-data-provider-http' is not ready
mstore                  41s   False     HelmChart 'service/th2-demo-books-mstore' is not ready
rpt-data-provider       42s   False     HelmChart 'service/th2-demo-books-rpt-data-provider' is not ready
rpt-data-viewer         41s   False     HelmChart 'service/th2-demo-books-rpt-data-viewer' is not ready
script                  40s   False     HelmChart 'service/th2-demo-books-script' is not ready
```
```
kubectl get hr (second reconciliation, happens automatically after 1-2 minutes)
message-producer        12m   True    Release reconciliation succeeded
mstore                  12m   True    Release reconciliation succeeded
rpt-data-provider       12m   True    Release reconciliation succeeded
rpt-data-viewer         12m   True    Release reconciliation succeeded
script                  12m   True    Release reconciliation succeeded
```
