### DISCUSSION TITLE
Flux Rocket Chat Notifications not functioning

### DISCUSSION THREAD

**Discussion by vsramalwan** [fluxcd/flux2#3807] [Q&A] [answered]
Hello,
I tried to setup Flux deployment notifications as mentioned [here](https://fluxcd.io/flux/guides/notifications/#git-commit-status) using Kustomization but it isn't triggering any updates in the Rocket Chat channel. All the steps mentioned in the link are followed. Following are the files:
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: flux-alerts
  namespace: flux-system
spec:
  summary: 'super cluster'
  providerRef:
    name: rocket
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'

```
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: rocket
  namespace: flux-system
spec:
  type: rocket
  channel: ssm-alerts
  username: rocket.bot
  secretRef:
    name: rocket-url

```
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - provider.yaml
  - alert.yaml

```
![image](https://user-images.githubusercontent.com/11861588/232393147-be92f616-3da8-4843-90fc-f2d37a1f287f.png)
![image](https://user-images.githubusercontent.com/11861588/232394103-f96645fb-36e2-46a9-8780-ed93c4d79dc9.png)
