### DISCUSSION TITLE
How to debug a HelmRelease that fails to install?

### DISCUSSION THREAD

**Discussion by jgz** [fluxcd/flux2#3809] [Q&A] [answered]
I'm trying to install aws-load-balancer-controller with the below HelmRelease.

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-lbc
  namespace: aws-lbc
spec:
  chart:
    spec:
      chart: aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: flux-system
      version: "1.5.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: -1
  values:
    clusterName: production
    serviceAccount:
      create: false
      name: aws-lbc
```
The install fails with:
```
Helm install failed: Internal error occurred: failed calling webhook "vingressclassparams.elbv2.k8s.aws": failed to call webhook: Post "https://aws-load-balancer-webhook-service.aws-lbc.svc:443/validate-elbv2-k8s-aws-v1beta1-ingressclassparams?timeout=10s": no endpoints available for service "aws-load-balancer-webhook-service
```
When I describe the failed pod it shows:
```
 Warning  FailedMount  53s (x8 over 116s)  kubelet            MountVolume.SetUp failed for volume "cert" : secret "aws-load-balancer-tls" not found
```

So I'm assuming the Secret record is not getting created by the helm chart before it tries to run the deployment manifests.  I've checked the chart with helm --dry-run and the secret record is the first resource that gets returned so I'm not really sure what the problem is here.  It seems like the Helm controller isn't processing the chart correctly?

How do I go about debugging this?  The helm release  is never created so I have no way to check what the generated yaml was.
