### DISCUSSION TITLE
"Manually" tell flux that a new image has been deployed

### DISCUSSION THREAD

**Discussion by mariusmitrofanbostontr** [fluxcd/flux2#3824] [General] [answered]
Background: We have a lot of ECR repositories that hold a lot of ECR images and scanning those images creates millions (literally) of AWS ECR API calls per day.

Is there a possibility that instead of using "Image Automation" to simply tell Flux that a new image was deployed and have it manually sync it to the git repo + deploy it in the cluster ?

Sample worfklow:

```
docker build -t asd:latest .

docker push asd:latest

flux deploy image asd:latest to deployment/whatever
```

I hope this makes sense.

Thanks!

**Comment by makkes** [comment]
One way to reduce the number of API calls against the registry is to increase the interval on the `ImageRepository` resources and create a [Flux Receiver](https://fluxcd.io/flux/components/notification/receiver/) that is triggered from your automation after updated images have been pushed.

**Reply by mariusmitrofanbostontr** [reply]
This will probably reduce API calls from millions to hundreds of thousands, which is a big step, but I would like it to be 0. No calls. At all.

Is that possible ?

**Reply by makkes** [reply]
Set the interval to "0s", then Flux will not reconcile the `ImageRepository` objects.

**Comment by SachithKasthuriarachchi** [comment]
Use `kustomize edit set image` to manually update the image tag in the git repository's `kustomization.yaml` file. Then `Kustomization` kind will sync your changes to the cluster

**Reply by mariusmitrofanbostontr** [reply]
Wait, how ?

So if my ImageRepository looks like this:

```
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: pliant-worker-nodejs-config
  namespace: flux-system
spec:
  image: 12345678.dkr.ecr.us-east-1.amazonaws.com/asd
  interval: 1m0s
  secretRef:
    name: ecr-credentials
```

then I just need to run:

```
kustomize edit set image 12345678.dkr.ecr.us-east-1.amazonaws.com/asd:mynewtag
```

Or how exactly.. ?
