### DISCUSSION TITLE
Github repository_dispatch can only trigger workflows on the default branch

### DISCUSSION THREAD

**Discussion by cer** [fluxcd/flux2#3878] [Q&A]
I've been playing with using a [Github Action to promote a HelmRelease from dev to production](https://fluxcd.io/flux/use-cases/gh-actions-helm-promotion/).

it seems that one limitation is that `repository_dispatch` can only trigger workflows on the default branch, eg. see this [discussion](https://github.com/orgs/community/discussions/24657)

Sadly, my example is on a non-default branch so this limitation is an obstacle.

Thoughts?

**Comment by stefanprodan** [comment]
Inside the workflow  pushed to main, you can clone any other branch e.g.

```
      # Checkout branch.
      - uses: actions/checkout@v3
        with:
          ref: my-branch
```
