### DISCUSSION TITLE
Mattermost/mattermost/mattermost configured spam

### DISCUSSION THREAD

**Discussion by cerebrate** [fluxcd/flux2#3888] [Q&A]
So, I'm having an issue that's related to the general resource-configured spam events [mentioned in the docs](https://fluxcd.io/flux/cheatsheets/troubleshooting/#how-do-i-resolve-someresource-configured-events-spam), except that instead of being an artifact of optional fields, etc., it appears to be a side-effect of how [mattermost-operator](https://github.com/mattermost/mattermost-operator) works by design.

Specifically, the Mattermost custom resource looks like this at configuration-time:

```
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
  namespace: mattermost
spec:
  version: 7.9.2
  size: 100users
  ingress:
    enabled: true
    host: mattermost.arkane-systems.net
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
      traefik.ingress.kubernetes.io/router.tls: 'true'
  database:
    external:
      secret: mattermost-db-credentials
  fileStore:
    external:
      url: minio-api.harmony.arkane-systems.lan
      bucket: mattermost-bucket
      secret: mattermost-file-store-credentials
```

*But* the operator, by design - [as stated here](https://github.com/mattermost/mattermost-operator#installation-size) - deletes the spec.size field and replaces it with resource requests and limits according to what was specified under spec.size, so at runtime, the object looks like this:

```
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
  namespace: mattermost
spec:
  database:
    external:
      secret: mattermost-db-credentials
  fileStore:
    external:
      bucket: mattermost-bucket
      secret: mattermost-file-store-credentials
      url: minio-api.harmony.arkane-systems.lan
  image: mattermost/mattermost-enterprise-edition
  imagePullPolicy: IfNotPresent
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: 'true'
    enabled: true
    host: mattermost.arkane-systems.net
  replicas: 1
  scheduling:
    resources:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 256Mi
  version: 7.9.2
```

And since the size is removed and replaced, off we go every ten minutes, configuring the Mattermost instance over again. By modifying the alert configuration I can at least avoid drowning in "Mattermost/mattermost/mattermost configured" messages, but is there a better way to prevent the actual cycle of reconfigurations?

Thanks muchly.
