### DISCUSSION TITLE
Flux / terraform object computed checksum error

### DISCUSSION THREAD

**Discussion by youcefguichi** [fluxcd/flux2#3890] [Q&A] [answered]
i'm trying to set up a terraform object within my gitrepo as follows:
```
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: helloworld
  namespace: flux-system
spec:
  approvePlan: "auto" # or you can omit this field
  interval: 1m
  path: ./terraform
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
```
and i'm facing the following error
```
➜ root git:(main) ✗ k get tf -n flux-system
 NAME         READY   STATUS                                                                                                                                        AGE
helloworld   False   failed to verify artifact: computed checksum '58ab539adaec0e0498d861b538ac8197757e423e1f94a90dae725b856e80cd32' doesn't match advertised ''   13m
```
any suggestions ?

**Comment by hiddeco** [comment]
Please update to `v2.0.0-rc.3` which was a fix for this issue.

**Reply by youcefguichi** [reply]
thanks for your reply, however i'm using the same version you proposed.
```
➜  root git:(main) ✗ flux version                                           
flux: v2.0.0-rc.3
helm-controller: v0.33.0
kustomize-controller: v1.0.0-rc.3
notification-controller: v1.0.0-rc.3
source-controller: v1.0.0-rc.3
```

**Reply by hiddeco** [reply]
Seems to be related to https://github.com/weaveworks/tf-controller/issues/567 in this case. @chanwit, can you please advise?

**Reply by youcefguichi** [reply]
I downgrade the version to `flux: v0.41.2` and it works fine now, the tf controller seems to have some issues with the latest versions of flux.

**Reply by chanwit** [reply, marked as answer]
@YoucefGuichi you're right.

For Flux v2.0.0-rc.x, you have to use Terraform controller v0.15.0-rc.x and later only.

**Reply by youcefguichi** [reply]
Hello @chanwit,  I upgraded again flux to `v2.0.0-rc.3` and tf-controller to `v0.15.0-rc.1` as you proposed:
```
image:
      tag: v0.15.0-rc.1
    runner:
      image:
        tag: v0.15.0-rc.1
```
 everything works smoothly now 🔥🚀
 Thanks!
