### DISCUSSION TITLE
HelmRelease with partial match semver expression based on prerelease string

### DISCUSSION THREAD

**Discussion by irishandyb** [fluxcd/flux2#3893] [Q&A]
I use semantic versioning for my Helm charts in the form of `x.y.z-<prerelease>+<build>`, for example `1.0.0-feature-foo+11`.

With this, at any one time there may be several features may be under development in separate feature branches. The development stream is identified in the semver prerelease string.
Each of these development streams may have multiple builds published, with each build incrementing a build number as denoted by the `+N` semver build metadata.

The following listing shows an example in which there are two feature branches: `feature-foo` and `feature-bar`, each with several builds.

```
$ helm search repo project-foobar --devel -l
NAME                            CHART VERSION           APP VERSION     DESCRIPTION
servicekit/project-foobar       1.0.0-feature-foo+12    1.0.0           Helm chart for project foobar
servicekit/project-foobar       1.0.0-feature-foo+11    1.0.0           Helm chart for project foobar
servicekit/project-foobar       1.0.0-feature-foo+10    1.0.0           Helm chart for project foobar
servicekit/project-foobar       1.0.0-feature-bar+22    1.0.0           Helm chart for project foobar
servicekit/project-foobar       1.0.0-feature-bar+21    1.0.0           Helm chart for project foobar
servicekit/project-foobar       1.0.0-feature-bar+20    1.0.0           Helm chart for project foobar
```

I would like to be able to deploy a `HelmRelease` with the `version` field set to match the latest build for a particular prerelease string.
For example, I deployed the following `HelmRelease` with version `^1.0.0-feature-bar+20` and I expect it to deploy the latest build matching the `feature-bar` prerelease string, in this case `1.0.0-feature-bar+22`.

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: project-foobar
  namespace: foobar
spec:
  chart:
    spec:
      chart: project-foobar
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: foobar
      version: "^1.0.0-feature-bar+20"
  interval: 1m0s
  values: {}
```

However, when I deploy the above `HelmRelease`, rather than deploying a `1.0.0-feature-bar+X` release, Flux deploys the `1.0.0-feature-foo+12` release. Note the 'Last Applied Version' in the output below.

```
$ kubectl -n foobar describe helmreleases.helm.toolkit.fluxcd.io project-foobar | grep "1.0.0"
      Version:  ^1.0.0-feature-bar.20
  Last Applied Revision:           1.0.0-feature-foo+12
  Last Attempted Revision:         1.0.0-feature-foo+12
```

I have also tried excluding the build number (semver build meta) from the semver expression i.e., `^1.0.0-feature-bar` but Flux still deploys `1.0.0-feature-foo+12`.
Flux deploys the correct version if I update the `HelmRelease` version to be an exact match string, such as `1.0.0-feature-bar+22`; however I would like to be able to use the `^` expression such that Flux deploys the latest build (+N).

Am I misunderstanding how the semver expressions should behave or is it a bug that Flux is deploying `feature-foo` when I have defined `feature-bar`?

Any input would be greatly appreciated.
