### DISCUSSION TITLE
Kustomization fails to reconcile

### DISCUSSION THREAD

**Discussion by munai-das** [fluxcd/flux2#3898] [Q&A]
Hi, 
```
➜  ~ flux version
flux: v0.41.2
flux-kustomize-controller: v0.34.0
flux-notification-controller: v0.32.0
flux-source-controller: v0.35.1
```

```
➜  ~ flux export kustomization ekipazh -n ekipazh
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2023-05-18T19:58:23.387933-07:00"
  name: ABC
  namespace: ABC
spec:
  interval: 1m0s
  path: ./platform-services/integration/spend/ABC/
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: Bucket
    name: ce-deploy-target
    namespace: flux-system
  targetNamespace: ABC
  timeout: 3m0s

```

I am getting the following error in my Kustomizations.

```
Deployment/XYZ/ABC dry-run failed, error: failed to create manager for existing fields: failed to convert new object (apps/v1, Kind=Deployment) to smd typed: .spec.template.spec.containers[name="ebs-container"].env: duplicate entries for key [name="LOCATION"]
```

We fixed the issue(simple duplicate removal) and deployed our changes . We use the Bucket Source for our setup. 
The error still remains in kustomization.

I checked the manifest by downloading the `latest.tar.gz` file from source-controller and running `kustomize build` on the manifest. It doesn't show any issue. 

```
➜  fluxcd git:(main) ✗ flux suspend kustomization -n ekipazh ekipazh
► suspending kustomization ekipazh in ekipazh namespace
✔ kustomization suspended
➜  ~ flux resume kustomization -n ABC ABC
► resuming kustomization ABC in ABC namespace
✔ kustomization resumed
◎ waiting for Kustomization reconciliation

```
It gets stuck indefinitely

What can be the issue here? I tried increasing the memory limits and replicas of kustomization to no avail.

Any help will be appreciated.
