### DISCUSSION TITLE
Rename resulting manifests of a HelmRelease

### DISCUSSION THREAD

**Discussion by Stupremee** [fluxcd/flux2#3908] [Q&A]
Hello people,

I'm currently in the process of migrating from one Helm chart to another, for a specific service I use.
Both helm charts create a Kubernetes `Service` object, that I need to use in my applications.
However, the new chart I'm gonna use, uses a different name that service.

So to save some work, I wanted to try to rename the `Service` that the new chart creates because then I don't need to change all URLs I use in my applications.

I tried using postrenderers, which are meant for this kind of use case, but they didn't work. So I'm gonna ask here for help.

This is what my HelmRelease looks like:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-release
spec:
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Service
              name: old-service
            patch:
              - op: replace
                path: /metadata/name
                value: "new-service"
  chart:
    # ...
```
