### DISCUSSION TITLE
HelmRelease: set helm values array using valuesFrom

### DISCUSSION THREAD

**Discussion by hoffimar** [fluxcd/flux2#3909] [Q&A]
I would like to use the values override feature of the helm-controller (https://fluxcd.io/flux/components/helm/helmreleases/#values-overrides) and set an array/list in the helm values of my helm release. But I am not clear about the syntax to use.

In the **helmrelease** I have this reference to a configmap:
```
    - kind: ConfigMap
      name: array-test
      optional: true
      targetPath: global.theList
      valuesKey: array-test.yaml

```

The **configmap** is defined like this:

```
apiVersion: v1
data:
  array-test.yaml: |-
    - type: apple
      count: 2
    - type: banana
      count: 3
kind: ConfigMap
metadata:
  name: array-test
```

Using `helm -n default my-release get values` I see that the values are updated, but are a **string instead of a list**. 
```
global:
  theList: |-
    - type: apple
      count: 2
    - type: banana
      count: 3
```

As I would like to iterate over the list/array with `range` in the helm chart implementation, is there any way to make the configmap entries available as list directly? Or would I need to use `fromYaml` (from https://helm.sh/docs/chart_template_guide/function_list/#type-conversion-functions) in the helm chart to convert the string to a list first?

**Comment by egorksv** [comment]
To all of you who ends up here:

targetPath is the equivalent of command line `helm .... -set name=value` and should be treated as such, as described here:
https://stackoverflow.com/questions/53846273/helm-passing-array-values-through-set

i.e. ConfigMap value syntax to set an array is:
`extdnscontroller.domain_filters: '{my.domain.com}'`

valuesFrom syntax to consume the value:
```
  valuesFrom:
    - kind: ConfigMap
      name: eks-extensions
      valuesKey: extdnscontroller.domain_filters
      targetPath: domainFilters

```
