### DISCUSSION TITLE
How to reference secrets from different namespace in Kustomization?

### DISCUSSION THREAD

**Discussion by iavkam** [fluxcd/flux2#391] [Q&A] [answered]
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gotk-system
  namespace: gotk-system
spec:
  interval: 1m0s
  url: my-cluster-config.git
...
```

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: workloads
  namespace: default
spec:
  interval: 2m0s
  path: ./path/to/sync
  prune: true
  sourceRef:
    kind: GitRepository
    name: gotk-system
    namespace: gotk-system
...
```
This don't work

**Comment by stefanprodan** [comment]
What version are you using? What's the logged error for the above config?

**Comment by vladimirfx** [comment, marked as answer]
There is no 'namespace' attribute in Kustomization.spec.sourceRef . In 'decryption' section namespace is absent too.

**Reply by stefanprodan** [reply]
We don't allow cross-namespace secrets ref in the toolkit APIs. As for the sourceRef it does have a namespace field.

**Reply by vladimirfx** [reply]
Ok, in case of same repository (GitRepository reference) users should provide copy of SOPS secret? Or there is another, idiomatic way?

**Comment by stefanprodan** [comment]
I've tested this with gotk v0.1.8 and works fine

```console
$ cat << EOF | kubectl apply -f -
> apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
> kind: Kustomization
> metadata:
>   name: workloads
>   namespace: default
> spec:
>   interval: 2m0s
>   path: ./path/to/sync
>   prune: true
>   sourceRef:
>     kind: GitRepository
>     name: gotk-system
>     namespace: gotk-system
> EOF
kustomization.kustomize.toolkit.fluxcd.io/workloads created
```

**Reply by iavkam** [reply]
Sorry, we were wrong. We meant in the section "decryption":
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: workloads
  namespace: default
spec:
  interval: 2m0s
  path: ./path/to/sync
  prune: true
  sourceRef:
    kind: GitRepository
    name: gotk-system
    namespace: gotk-system
  decryption:
    provider: sops
    secretRef:
      name: sops-pgp
      namespace: gotk-system
...
```
