### DISCUSSION TITLE
Problem with Kustomize an Sops

### DISCUSSION THREAD

**Discussion by Igorgro** [fluxcd/flux2#3951] [Q&A] [answered]
Hello. I'm trying to use Flux (2.0.0-rc5) with Kustomize and Sops, but something is going wrong. Steps to reproduce (according to https://fluxcd.io/flux/guides/mozilla-sops/):
1. Install Flux with Gitlab repository
2. Generate GPG key and add it to Kubernetes as secret (as said in manual)
3. Create new gitlab repository and add it to flux
4. Create directory with `kustomization.yaml` file with something like this:
    ```yaml
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    metadata:
      name: test-kust
    resources:
      - config-map.yaml
      - secret.yaml
    ```
    and ConfigMap (which is a plain manifest) and `secret.yaml` which is a Sops-gpg-encrypted Secret like this:
    ```yaml
    apiVersion: ENC[AES256_GCM,data:/68=,iv:SV...
    kind: ENC[AES256_GCM,data:17qKfK/4,iv:uRrD///
    metadata:
      name: ENC[AES256_GCM,data:942Jt...
    data:
      somevalue: ENC[AES256_GCM,data:1SD2Moh...
    ```
5. Create `.sops.yaml` file in that repository according to manual (not sure if it is required, because it presence does not affect this problem)
6. Push these files to repo
7. Create Flux Kustomization file like that:
    ```yaml
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: test
      namespace: flux-apps
    spec:
      interval: 10m
      targetNamespace: flux-apps
      sourceRef:
        kind: GitRepository
        name: flux-apps
        namespace: flux-apps
      path: prod/test-kust
      decryption:
        provider: sops
        secretRef:
          name: sops-gpg # this is a ref to secret created in 1.
      prune: true
      timeout: 1m
    ```
8. Apply this Kustomize manifest using `kubectl`
9. See the following status of that manifest:
    ```
    kubectl get -n flux-apps Kustomization
    NAME            AGE   READY   STATUS
    test            53m   False   kustomize build failed: recovered from kustomize build panic: number of previous names, number of previous namespaces, number of previous kinds not equal
    ```

If I remove encrypted secret reference from `kustomization.yaml` then everything works well. How to solve this problem? Searching through existing issues gave me nothing.
