### DISCUSSION TITLE
HelmChart being garbage collected with using GitRepo revision

### DISCUSSION THREAD

**Discussion by sancroth** [fluxcd/flux2#3984] [Q&A]
The goal:
Have a github repository that hosts multiple charts and their perspective values bundled under a directory called "/charts".
For example "/charts/redis" is going to contain the helm chart and values that we need to install.
I want to use revision as the reconciliation trigger to enable deploying new values on our custom charts when we decided to push said values on our master branch. Changed values don't always mean a new chart version and thus we decided this approach is fitting our setups. 

The setup:

helm release: 
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-nps-test-release-flux
  namespace: nps-test
spec:
  # The interval at which to reconcile the Helm release
  interval: 1m
  chart:
    spec:
      # The path of the chart relative to the repository root
      chart: ./bitnami/redis/
      # The reference to the GitRepository
      sourceRef:
        kind: GitRepository
        name: nps-test
        # Optional, defaults to the namespace of the HelmRelease
        namespace: nps-test
  values:
    filePath: values.yaml
```
---
helm chart: 
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: redis-flux-git-revision
  namespace: nps-test
spec:
  chart: ./bitnami/redis/
  sourceRef:
    name: nps-test
    kind: GitRepository
  interval: 1m
  reconcileStrategy: Revision
```
---
K8s running on rancher desktop:
```
Client Version: v1.25.10
Kustomize Version: v4.5.7
Server Version: v1.25.10+k3s1
```
Both of said resources have been installed using kubectl apply -f, after flux was installed using the official guide.

---
flux check:
```
► checking prerequisites
✗ flux 0.41.2 <2.0.0-rc.5 (new version is available, please upgrade)
✔ Kubernetes 1.25.10+k3s1 >=1.20.6-0
► checking controllers
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.35.1
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.31.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.33.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.36.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed
```
---
The problem:
When we first run kubectl apply -f {HelmRelease, HelmChart}.yaml the deployment is taking place as expected.
Any future updates leads to HelmChart creating a new package as seen from the source-controller logs:

`{"level":"info","ts":"2023-06-19T13:38:25.367Z","msg":"packaged 'redis' chart with version '17.11.5'","controller":"helmchart","controllerGroup":"source.toolkit.fluxcd.io","controllerKind":"HelmChart","HelmChart":{"name":"nps-test-redis-nps-test-release-flux","namespace":"nps-test"},"namespace":"nps-test","name":"nps-test-redis-nps-test-release-flux","reconcileID":"5247bd24-35cf-4a9b-97e5-310f315d502e"}`

But then the HelmRelease starts erroring out because it cannot fetch the chart version from the source-controller as seen below:

`  failed to download artifact, error: GET
  http://source-controller.nps-test.svc.cluster.local./helmchart/nps-test/nps-test-redis-nps-test-release-flux/redis-17.11.5.tgz
  giving up after 10 attempt(s): Get
  "http://source-controller.nps-test.svc.cluster.local./helmchart/nps-test/nps-test-redis-nps-test-release-flux/redis-17.11.5.tgz":
  dial tcp 10.43.105.100:80: connect: connection refused`

After looking into this a bit i found out that garbage collection is triggered right after the package mentioned above is complete:

`{"level":"info","ts":"2023-06-19T13:39:26.890Z","msg":"garbage collected 1 artifacts","controller":"helmchart","controllerGroup":"source.toolkit.fluxcd.io","controllerKind":"HelmChart","HelmChart":{"name":"redis-flux-git-revision","namespace":"nps-test"},"namespace":"nps-test","name":"redis-flux-git-revision","reconcileID":"bca1a004-23f0-41f7-91cc-cba8f919ee3b"}`

---
HelmRelease resource seems to exist just fine after the run:
```
$ kubectl get helmreleases --all-namespaces
NAMESPACE   NAME                          AGE   READY   STATUS
nps-test    redis-nps-test-release-flux   13h   True    Release reconciliation succeeded
```
While no HelmChart resource seems to exist other than the default traefik ones:
```
$ kubectl get helmcharts --all-namespaces
NAMESPACE     NAME          JOB                        CHART                                                                      TARGETNAMESPACE   VERSION   REPO   HELMVERSION   BOOTSTRAP
kube-system   traefik       helm-install-traefik       https://%{KUBERNETES_API}%/static/charts/traefik-21.2.1+up21.2.0.tgz
kube-system   traefik-crd   helm-install-traefik-crd   https://%{KUBERNETES_API}%/static/charts/traefik-crd-21.2.1+up21.2.0.tgz
```
---
If my understanding from this behavior is correct, then it means that the package is being successfully created and then deleted right after since the name of the package is based on the chart version(17.11.5) and not the hash of the commit.
Am i understanding something wrong or have maybe misconfigured something here?
