### DISCUSSION TITLE
error: the server could not find the requested resource

### DISCUSSION THREAD

**Discussion by Angel0r** [fluxcd/flux2#4034] [Q&A] [answered]
Hey,

I am getting the following error when I deployed my application.
`flux-system   flux-system   145d   False   Ingress/application/application-ingress namespace not specified, error: the server could not find the requested resource...
`
I cannot understand why this happened because the namespace exists in the manifest.
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: application-ingress
  namespace: application
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    ## Extend timeout to allow long running queries.
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  labels:
    app: superset
spec:
  ingressClassName: nginx
  rules:
    - host: domain.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: application
                port:
                  name: http
  tls:
    - hosts:
        - domain.com
```

/Angelos
