### DISCUSSION TITLE
How to config fluxcd on-premises use sops access AWS KMS

### DISCUSSION THREAD

**Discussion by TitanPocket** [fluxcd/flux2#4054] [Q&A] [answered]
How to config fluxcd on-premises use sops access AWS KMS

**Comment by kingdonb** [comment]
I think you are looking for "Roles Anywhere" https://docs.aws.amazon.com/rolesanywhere/latest/userguide/introduction.html

I have done AWS OIDC configuration using regular IAM and OIDC on EKS clusters that run on AWS cloud, but I haven't used this before, I don't know how it works. Can you say a bit more about your configuration? Are you using EKS Anywhere or AWS Identity "Roles Anywhere"?

There is an AWS-specific doc here, under the Flux SOPS guide, but it doesn't cover anything related to doing AWS IAM with off-cloud clusters or non-EKS clusters, I'm still looking for a better entrypoint in the AWS docs that covers "Roles Anywhere" wrt Kubernetes:

https://fluxcd.io/flux/guides/mozilla-sops/#encrypting-secrets-using-various-cloud-providers

**Comment by plaes** [comment, marked as answer]
You can manually provision a secret with AWS access keys in the cluster for sops and reference it from kustomization:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-repo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/on-prem-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-repo
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
```

And secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: sops-keys
  namespace: flux-system
stringData:
  sops.aws-kms: |
    aws_access_key_id: ...
    aws_secret_access_key: ...
```
