### DISCUSSION TITLE
HelmRelease with values.yaml from a git repository

### DISCUSSION THREAD

**Discussion by greenpasta** [fluxcd/flux2#407] [Q&A] [answered]
Very new to all this, still trying to wrap my head around it...

I bootstrapped with this:
`flux bootstrap gitlab --owner=me --repository=myrepo --branch=flux-test --path=dev --personal`

Then created a helm source for Redis with this:
`flux create source helm redis --url=https://charts.bitnami.com/bitnami --interval=10m`

The created a helm release with this:
`flux create helmrelease redis-myapp --source=HelmRepository/redis --chart=redis --values=/path/to/my-values.yaml`

My question: Can I get the helmrelease to use a values.yaml from a git repository? Ideally "myrepo", so I can keep everything together. If I'm pointing to a local values.yaml file I'm not sure how to keep that up to date in a Gitopsy way.

Thanks for any tips!

**Comment by stefanprodan** [comment, marked as answer]
The `flux create helmrelease` command embeds the values from your local `values.yaml` into the generated HelmRelease object under `spec.values`, so there is no need to keep the `values.yaml` in Git. When you want to modify the values, do it directly in the HelmRelease file.

The HelmRelease and HelmRepository manifests should be stored in Git, assuming you've used `flux bootstrap` you can export the objects to Git with:

```
git clone fleet-repo
cd fleet-repo

flux create source helm --export > my-cluster/bitnami.yaml
flux create helmrelease redis-myapp > my-cluster/redis-release.yaml

git add && git commit && git push
```

**Reply by greenpasta** [reply]
Ah ok, that makes sense now. Thanks!

**Reply by arbourd** [reply]
I feel like this isn't a great approach for everyone. We are currently migrating from Argo to Flux and this is a huge blocker.

We have three environments and 5 sets of values files. Moving this all to a Flux CRD is restrictive and doesn't provide much value for our use case. We are pulling the chart via Git and the values files are all there.

We run CI including KIND, template linting and `helm diff` long before a deploy. If we were to move to `HelmRelease.values` we'd lose all of that.

Are there any workarounds for teams like ours?

**Reply by stefanprodan** [reply]
@arbourd you can reference to values files located in Git like this:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
spec:
  chart:
    spec:
      chart: charts/my-app
      sourceRef:
        kind: GitRepository
        name: my-repo
      valuesFile: charts/my-app/values-production.yaml # <- path must be relative to the Git repo root
```

Docs here: https://toolkit.fluxcd.io/guides/helmreleases/#refer-to-values-inside-the-chart

**Reply by arbourd** [reply]
Well I feel silly. Missed that in the spec. Thank you so much @stefanprodan and team!

**Reply by Moskovych** [reply]
@stefanprodan , regarding: https://github.com/fluxcd/flux2/discussions/407#discussioncomment-355971
is it possible to specify multiple `valuesFiles` ?

**Reply by stefanprodan** [reply]
@Moskovych see https://github.com/fluxcd/source-controller/pull/305

**Reply by Moskovych** [reply]
@stefanprodan , nice. will watching for it.
But currently looks like it read's the file only if values file in the same folder as chart, like:
`chart: charts/my-app` and `valuesFile: charts/my-app/values.yaml`
but it doesn't work with (for example):
`chart: charts/my-app` and `valuesFile: helm/values/my-app.values.yaml`

UPD: looks like file should be always start with `values-`, like: `helm/path/values-dev.yaml`

**Reply by Zialus** [reply]
> @arbourd you can reference to values files located in Git like this:
> 
> ```yaml
> apiVersion: helm.toolkit.fluxcd.io/v2beta1
> kind: HelmRelease
> spec:
>   chart:
>     spec:
>       chart: charts/my-app
>       sourceRef:
>         kind: GitRepository
>         name: my-repo
>       valuesFile: charts/my-app/values-production.yaml # <- path must be relative to the Git repo root
> ```
> 
> Docs here: https://toolkit.fluxcd.io/guides/helmreleases/#refer-to-values-inside-the-chart

but let's say my use case is the same as the original poster where I currently have a manifest like the following

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: "1.16.0"
```

how would I be able to refer to a values file?
