### DISCUSSION TITLE
Variable substitution with hierarchical structure of flux kustomizations yielding strange results

### DISCUSSION THREAD

**Discussion by DaveMullin** [fluxcd/flux2#4087] [Q&A] [answered]
I am trying to understand why I am getting different behaviour between Scenario1 and 2. It seems if the parent does not have a     postBuild: substitute: section with a variable specified then the child variables are ignored. I must be doing something wrong here.

Flux version = v0.41.2

If I have 2 Flux Kustomization resources a parent and child like this:

**Scenario1 - parent DOES NOT HAVE variables of its own**

- https://github.com/Maersk-Global/k8s-somemodule/parent/k8s-gitresource.yaml

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
    name: k8s-somemodule
    namespace: flux-system
spec:
    interval: 1h
    ref:
        branch: master
    secretRef:
        name: github-secrets-ssh
    url: ssh://git@github.com/company/k8s-somemodule
```

- https://github.com/Maersk-Global/k8s-somemodule/parent/parent.yaml
- 
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    labels:
        kustomize.toolkit.fluxcd.io/prune: enabled
    name: k8s-parent
    namespace: flux-system
spec:
    interval: 1h
    path: ./config/
    prune: true                   ## <------- no postbuild or substitution is gone. 
    retryInterval: 10m
    sourceRef:
        kind: GitRepository
        name: k8s-somemodule
        namespace: flux-system
    suspend: false
```

- https://github.com/Maersk-Global/k8s-somerepo/config/child.yaml

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    labels:
        kustomize.toolkit.fluxcd.io/prune: enabled
    name: k8s-child
    namespace: flux-system
spec:
    interval: 1h
    path: ./manifests/
    postBuild:
        substitute:
            VERSION: 1.14.2
            CPU_LIMIT: ${CPU_LIMIT:=100m}  ## the aim here is that if the parent had of specified CPU_LIMIT we would use that else use 100m as default
    prune: true
    retryInterval: 10m
    sourceRef:
        kind: GitRepository
        name: k8s-somemodule
        namespace: flux-system
```

- https://github.com/Maersk-Global/k8s-somemodule/manifest/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - fluxcd-resources.yaml
    - hpa.yaml
    - namespace.yaml
    - values-configmap.yaml
```

- https://github.com/Maersk-Global/k8s-somerepo/manifest/values-configmap.yaml
```
apiVersion: v1
data:
  values.yaml:  "# Default values for somemodue.\n# This is a YAML-formatted
    file.\n# Declare variables to be passed into your templates.\n\nresources:\n  limits:\n    cpu: ${CPU_LIMIT}\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: helm-values
  namespace: flux-system
```

- https://github.com/Maersk-Global/k8s-somerepo/manifest/fluxcd-resources.yaml
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: somehelmchart
  namespace: flux-system
spec:
  interval: 2h0m0s
  url: http://kubernetes-charts.banzaicloud.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: somehelmchart
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vault-secrets-webhook
      sourceRef:
        kind: HelmRepository
        name: vault-secrets-webhook
      version: "${VERSION}"
  interval: 1h0m0s
  maxHistory: 3
  releaseName:  vault-secrets-webhook
  targetNamespace: vault-secrets-webhook
  install:
    remediation:
      retries: -1
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  test:
    enable: false
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values.yaml
```

- k get kustomization -n flux-system; k get gitrepository -n flux-system
```
NAME                                       AGE   READY   STATUS
k8s-parent   21s   True    Applied revision: develop@sha1:35ccca8ce365defa3f9215efb4cf0e89d54f891c
k8s-child   18s   False   var substitution failed for 'helm-values': YAMLToJSON: YAMLToJSON: yaml: line 4: did not find expected key

NAME                                URL                                                                    AGE   READY   STATUS
k8s-somemodule   ssh://git@github.com/company/k8s-somemodule   21s   True    stored artifact for revision 'develop@sha1:35ccca8ce365defa3f9215efb4cf0e89d54f891c'

```

------------------------

**Scenario2 - parent DOES HAVE variables of its own**

- https://github.com/Maersk-Global/k8s-somemodule/parent/k8s-gitresource.yaml

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
    name: k8s-somemodule
    namespace: flux-system
spec:
    interval: 1h
    ref:
        branch: master
    secretRef:
        name: github-secrets-ssh
    url: ssh://git@github.com/company/k8s-somemodule
```

- https://github.com/Maersk-Global/k8s-somemodule/parent/parent.yaml
- 
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    labels:
        kustomize.toolkit.fluxcd.io/prune: enabled
    name: k8s-parent
    namespace: flux-system
spec:
    interval: 1h
    path: ./config/
    postBuild:
        substitute:
            DUMMY: blah
    prune: true
    retryInterval: 10m
    sourceRef:
        kind: GitRepository
        name: k8s-somemodule
        namespace: flux-system
    suspend: false
```

- https://github.com/Maersk-Global/k8s-somerepo/config/child.yaml

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    labels:
        kustomize.toolkit.fluxcd.io/prune: enabled
    name: k8s-child
    namespace: flux-system
spec:
    interval: 1h
    path: ./manifests/
    postBuild:
        substitute:
            VERSION: 1.14.2
            CPU_LIMIT: ${CPU_LIMIT:=100m}      ## the aim here is that if the parent had of specified CPU_LIMIT we would use that else use 100m as default
    prune: true
    retryInterval: 10m
    sourceRef:
        kind: GitRepository
        name: k8s-somemodule
        namespace: flux-system
```

- https://github.com/Maersk-Global/k8s-somemodule/manifest/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - fluxcd-resources.yaml
    - hpa.yaml
    - namespace.yaml
    - values-configmap.yaml
```

- https://github.com/Maersk-Global/k8s-somerepo/manifest/values-configmap.yaml
```
apiVersion: v1
data:
  values.yaml:  "# Default values for somemodue.\n# This is a YAML-formatted
    file.\n# Declare variables to be passed into your templates.\n\nresources:\n  limits:\n    cpu: ${CPU_LIMIT}\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: helm-values
  namespace: flux-system
```

- https://github.com/Maersk-Global/k8s-somerepo/manifest/fluxcd-resources.yaml
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: somehelmchart
  namespace: flux-system
spec:
  interval: 2h0m0s
  url: http://kubernetes-charts.banzaicloud.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: somehelmchart
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vault-secrets-webhook
      sourceRef:
        kind: HelmRepository
        name: vault-secrets-webhook
      version: "${VERSION}"
  interval: 1h0m0s
  maxHistory: 3
  releaseName:  vault-secrets-webhook
  targetNamespace: vault-secrets-webhook
  install:
    remediation:
      retries: -1
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  test:
    enable: false
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values.yaml
```

- k get kustomization -n flux-system; k get gitrepository -n flux-system
```

NAME                                       AGE    READY   STATUS
k8s-parent     2m7s   True    Applied revision: develop@sha1:818e58978756daf2f2496bc4333ee92955e77cf6
k8s-child   2m4s   True    Applied revision: develop@sha1:818e58978756daf2f2496bc4333ee92955e77cf6

NAME                                URL                                                                    AGE    READY   STATUS
k8s-somemodule   ssh://git@github.com/company/k8s-somemodule   21s   True    stored artifact for revision 'develop@sha1:35ccca8ce365defa3f9215efb4cf0e89d54f891c'

```
