### DISCUSSION TITLE
Flux notifications on cluster

### DISCUSSION THREAD

**Discussion by Angel0r** [fluxcd/flux2#4095] [Q&A] [answered]
Hey!

Is there any way to have alerts from Flux notifications on Cluster or on all namespaces?

/Angelos

**Comment by kingdonb** [comment]
No, at present there is no wildcard namespace feature for alerting. Any namespace where you put Flux resources that you want to monitor with alerts, you will need to put Alerts there as well. (Edit: or at minimum, a named reference to the namespaces that you want each alert to cover. Sincd alerts can contain cross-namespace references if they are not [disabled system-wide](https://fluxcd.io/flux/components/notification/alert/#disable-cross-namespace-selectors), you can get away with one alert to cover many namespaces, but there is no wildcarding in the namespace field because there is no wildcard in the equivalent RBAC structures possible, without using a clusterrolebinding.)

The wildcard can only be used for name. In the design, this was intended to enable multi-tenancy, since an alert with a wildcard namespace would represent a cross-namespace reference of the highest order, and should be basically impossible in a multi-tenant system. We recommend disabling cross-namespace references in those configurations.

Maybe something can be done though, since it must be a common pattern to monitor all Flux resources on a cluster. My preferred approach would be to centralize all Flux resources in a given namespace, like you are encouraged or required to do with Image Update Automation, but if you look at my clusters I have rarely honored that, I have Flux resources scattered across many namespaces and the tenancy is not enforced, (I don't work on production systems).

It is not great working like this, I would recommend instead to do more intentional design about where Flux resources go and use `targetNamespace` to put the workloads in a separate namespace as appropriate, while the Flux resources remain centralized inside of a single namespace per team that manages. Flux resources that are all maintained by a single team should not be scattered across many namespaces IMO. If you divide them into namespaces on the cluster, then it's expected that you would want the Alert traffic to be divided into different channels that the namespace owners (teams) can all monitor separately without interfering with each other.

**Reply by Angel0r** [reply]
Hey kingdonb,
Thank you for your elaborate answer.
We have only one cluster and we use a monorepo structure meaning that we have a repo that contains all the resources:
```
flux-fleet
├── cluster-team)
│    ├── subteam1
│    │     ├── application1(ns)
│    │     ├── application2(ns)
│    │     │        .
│    │     │        .
│    │     │        .
│    │     └── application(ns)
│    ├── subteam2
│           │         .
│           │         .
│           │         .
│           └── application(ns)
|
├── flux-system(ns)
│    ├── gotk-components.yaml
│    ├── gotk-sync.yaml
│    └── kustomization.yaml
└── resources
       ├── notifications
              ├── alerts.yaml
              ├── provider.yaml
              ├── README.md       
              └── webhook.yaml      
```

All our applications run in their namespace so we have a cleaner structure. 
So you mean to have all of our application on flux-system namespace and add tagetNamespace: flux-system to our kustomization.yaml? 
Will it work if we just add multiple Alerts resources in the alerts.yaml with different namespaces?

For example something like the following:
```yaml
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: flux-notifications
  namespace: flux-system
spec:
  summary: Notifications for flux
  providerRef:
    name: msteams
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: HelmRelease
      name: "*"
    - kind: HelmRepository
      name: "*"
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: application1-notifications
  namespace: application1
spec:
  summary: Notifications for application1
  providerRef:
    name: msteams
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: HelmRelease
      name: "*"
    - kind: HelmRepository
      name: "*"
```

**Reply by kingdonb** [reply]
The `targetNamespace` is a feature in Flux's `Kustomization.spec` not in the `kustomization.yaml`

You can use `namespace` in `kustomization.yaml` or you can use `targetNamespace` in the Flux `Kustomization` but I would not use both, since one will override the other. I would assume that Flux's `spec.targetNamespace` will win.

That looks like pretty much exactly what I would do, yes. You can use a single `provider` and share it between multiple alerts, so that way at least you don't have as much config duplication. Another way, you can use the namespace in your `eventSources` so you don't have to have an Alert per namespace, but I'm not sure this is any better:

```
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: flux-notifications
  namespace: flux-system
spec:
  summary: Notifications for all namespaces
  providerRef:
    name: msteams
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: HelmRelease
      name: "*"
    - kind: HelmRepository
      name: "*"
    - kind: GitRepository
      name: "*"
      namespace: application1
    - kind: Kustomization
      name: "*"
      namespace: application1
    - kind: HelmRelease
      name: "*"
      namespace: application1
    - kind: HelmRepository
      name: "*"
      namespace: application1
```

Maybe also want to include OCIRepository!

This is possible to make better if you have a list of namespaces, and a manifest generator to run in CI with some looping constructs.
