### DISCUSSION TITLE
invalid Kustomization: json: unknown field "spec" with kustomize.toolkit.fluxcd.io/v1

### DISCUSSION THREAD

**Discussion by Eagleman7** [fluxcd/flux2#4141] [Q&A]
Hello! I'm trying to use the kustomize.toolkit.fluxcd.io/v1 Kustomization. However I have a feeling this is not available in my cluster because it keeps complaining about a spec not being found:

kustomize.exe build
```
Error: accumulating resources: accumulation err='accumulating resources from '../../base/metallb-system/metallb': '/gitrepo/kubernetes/infrastructure/base/metallb-system/metallb' must resolve to a file': couldn't make target for path '/gitrepo/kubernetes/infrastructure/base/metallb-system/metallb': invalid Kustomization: json: unknown field "spec"
```

File that gives the error:

/gitrepo/kubernetes/infrastructure/base/metallb-system/metallb/kustomization.yaml
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  path: "./infrastructure/base/metallb-system/metallb/app"
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
```

This is where it is being triggered from:

/gitrepo/kubernetes/infrastructure/overlays/staging/kustomization.yaml
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/metallb-system
  - ../../base/metallb-system/metallb
```

flux check
```
► checking prerequisites
✔ Kubernetes 1.27.4+k3s1 >=1.24.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.35.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed
```

**Comment by makkes** [comment]
Rename the file from `kustomization.yaml` to something else. That name is reserved for kustomize itself.

**Comment by Eagleman7** [comment]
Renamed it to ks.yaml and changed it to that here:

/gitrepo/kubernetes/infrastructure/overlays/staging/kustomization.yaml
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/metallb-system
  - ../../base/metallb-system/metallb/ks.yaml
```

Yields to another error:

```
Error: accumulating resources: accumulation err='accumulating resources from '../../base/metallb-system/metallb/ks.yaml': security; file /kubernetes/infrastructure/base/metallb-system/metallb/ks.yaml' is not in or below '/kubernetes/infrastructure/overlays/staging'': must build at directory: '/kubernetes/infrastructure/base/metallb-system/metallb/ks.yaml': file is not directory
```


So changed the file to:

/gitrepo/kubernetes/infrastructure/overlays/staging/metallb.yaml
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m0s
  path: "./infrastructure/base/metallb-system/metallb/app"
  sourceRef:
    kind: GitRepository
    name: flux-system
```

and changed

/gitrepo/kubernetes/infrastructure/overlays/staging/kustomization.yaml
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/metallb-system
  - ../staging/metallb.yaml # Yes this goes back a folder just to go back to the same folder, but it looks prettier next to all other resources.
```

This finally made it work, however it doesn't make the overlay folder prettier.

Can I only place the file with the kustomize.toolkit.fluxcd.io/v1 in the /gitrepo/kubernetes/infrastructure/overlays/staging/ folder?
