### DISCUSSION TITLE
How to use configMapGenerator and secretGenerator with FluxCD?

### DISCUSSION THREAD

**Discussion by aleksandaratanasov** [fluxcd/flux2#4148] [Q&A]
I have an Ubuntu Server 22.04 with microk8s as Kubernetes flavour. The repository that FluxCD is using to manage the cluster is on a company self-hosted GitLab instance (access is granted via project token).

I have noticed that my deployments (currently struggling with Cloudbeaver - a WebUI for database management, the desktop equivalent is DBeaver) fail due to configMap's and secrtes missing.

Due to write access requirements I switch from using a configMapGenerator to persistent volumes. So my `kustomization.yaml` looks like this:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudbeaver-vm

namespace: gin

resources:
  - dbeaver/pv.yaml
  - dbeaver/pvc.yaml
  - dbeaver/deployment.yaml
  - dbeaver/service.yaml

# Previously used. Now using persistent volume claim
#configMapGenerator:
#DBEAVER
#  - name: dbeaver-product-configmap-vm
#    files:
#      - dbeaver/configs/product.conf
#  - name: dbeaver-sources-user-configmap-vm
#    files:
#      - dbeaver/configs/user/data-sources.json
#  - name: dbeaver-sources-global-configmap-vm
#    files:
#      - dbeaver/configs/global/data-sources.json
#  - name: dbeaver-server-configmap-vm
#    files:
#      - dbeaver/configs/cloudbeaver.conf

secretGenerator:
#DBEAVER
- name: dbeaver-secret-vm
  literals:
    - CB_SERVER_NAME=CloudBeaver Test Server
    - CB_ADMIN_NAME=admin.dbeaver
    - CB_ADMIN_PASSWORD=Password123
```

I do need a secret. And while yes, I can create a separate YAML configuration file, where I would define a secret, I do wonder what I am doing wrong. The generator doesn't appear to get triggered at all so my deplöyment fails with a `CreateContainerConfigError`.

I decide to check if things are working without Flux so I simply ran `kubectl apply -k cloudbeaver` pointing at the directory where my `kustomization.yaml` as well as all other files are located. The secret was generated and (now gone) so were the configMaps. The app was deployed successfully and I was able to interact with it.

Is there something I am missing here? I looked around and people do seem to be using generators, so my guess is that it's me who doesn't get it (I'm new to Kubernetes and GitOps). If required I can provide the full set of files for my app in case someone want's to test things out.
