### DISCUSSION TITLE
Running Kubernetes Jobs on Reconciliation

### DISCUSSION THREAD

**Discussion by ocni-dtu** [fluxcd/flux2#4149] [Q&A] [answered]
I would like to run a Kubernetes Job every time an image in my cluster is updated.

Right now I'm trying to achieve that with Kustomizations as described here: https://fluxcd.io/flux/use-cases/running-jobs/
The problem is that jobs doesn't rerun after the reconciliation. According to the docs above it is because the image in my job doesn't update.

The specific use case I have is that I have several services that exposes a GraphQL api and I would like to have the Kubernetes Job to run Apollo Rover and create a federated supergraph from them.
Therefore I would like to recreate the supergraph every time a service image updates. 

Below you will find the YAML for my job and for the kustomization:

```yaml
# supergraph.job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: supergraph.job
  namespace: router
  labels:
    name: supergraph.job
spec:
  backoffLimit: 4
  template:
    spec:
      volumes:
      - name: blob-volume
        persistentVolumeClaim:
          claimName: lcarouter-pvc
      - name: supergraph-yaml
        configMap:
          name: supergraph-yaml
      restartPolicy: Never
      containers:
        - name: rover
          image: ghcr.io/arkitema/rover:v0.16.2
          command: ["rover", "supergraph", "compose", "--config", "/etc/config/supergraph-config.yaml", "--output", "/etc/graphql/main/lca.graphql"]
          env:
            - name: APOLLO_ELV2_LICENSE
              value: "accept"
          volumeMounts:
          - name: blob-volume
            mountPath: /etc/graphql
          - name: supergraph-yaml
            mountPath: "/etc/config/supergraph-config.yaml"
            subPath: supergraph-config.yaml
```

```yaml
# kustermization.yaml

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: backend-post-deploy
  namespace: flux-system
spec:
  dependsOn:
    - name: backend-controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./apps/production/jobs"
  interval: 60m
  timeout: 5m
  prune: true
  wait: true
  force: true
```

Any ideas how I can get the job to run on every image update?
