### DISCUSSION TITLE
How to use regex in path

### DISCUSSION THREAD

**Discussion by daniltreshchev** [fluxcd/flux2#4155] [General] [answered]
I want to use * to select all apps in apps dir

like
```

apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/*/dev
  prune: true
  validation: client

```
but no working

Is there a way how to do it?
