### DISCUSSION TITLE
imagepolicy not updating kustomize-applied yaml

### DISCUSSION THREAD

**Discussion by daveoy** [fluxcd/flux2#4161] [General] [answered]
hi there,

i have the following resources installed in production:

```
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: archiver
  namespace: flux-system
spec:
  image: registry.carbonvfx.com/engineering/archiver
  interval: 1m0s
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: archiver
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: archiver
  filterTags:
    pattern: '^(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
```

which is successfully pulling the latest version of my container image from the registry:

```
 ~ % kubectl get imagepolicies archiver -n flux-system
NAME       LATESTIMAGE
archiver   registry.carbonvfx.com/engineering/archiver:1692212908
```

however, this doesn't appear to update the anchor in my cronjob spec, which is applied via a kustomization:

```
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: archiver
  namespace: carbon-utils
spec:
  schedule: "0 0 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
          - name: weka-mount-name
            nfs:
              server: weka-servername
              path: /export-path
          - name: secrets-store-inline
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "regcred"
          imagePullSecrets:
          - name: regcred
          serviceAccountName: image-puller
          containers:
          - name: archiver
            image: registry.carbonvfx.com/engineering/archiver:1688763902 # {"$imagepolicy": "flux-system:archiver"}
            resources:
              limits:
                memory: "512Mi"
                cpu: "1"
            volumeMounts:
            - name: weka-mount-name
              mountPath: /mnt/mountpath/
              readOnly: false
            - name: secrets-store-inline
              mountPath: "/secrets-store"
              readOnly: true
```

imagepolicies are working just fine when applied against a helmrelease, just not here. is there something im missing?
