### DISCUSSION TITLE
How to add resources in remote cluster by flux

### DISCUSSION THREAD

**Discussion by SonalinP** [fluxcd/flux2#4174] [General]
Hi, 

I am able to create namespace, secret and deploy (helmrelease) in same cluster where flux is installed using flux kustomization and kustomization overlay. -- All are in same cluster
But I want to do the above in a remote cluster using the same flux .
There is an option to add [spec.kubeConfig] in helm release to deploy in different cluster .
But can anyone please help how to deploy other resource in remote cluster such as creation  of namespace and secret ?

**Comment by makkes** [comment]
There is documentation on this topic [here](https://fluxcd.io/flux/components/kustomize/kustomization/#kubeconfig-reference) and [here](https://fluxcd.io/flux/components/kustomize/kustomization/#kubeconfig-reference). What type of information do you think is missing from that page that would help you make progress?

**Comment by SonalinP** [comment]
I have  created secret for kubeconfig file for remote cluster. 
But how to use that for creation of namespace and any secret in remote cluster .
For resource kind like namespace and secrets , there is no option to add any spec where I can refer kubeconfig file to create in remote cluster 
unlike for helmrelease.

I don't see these information mentioned in the given links here .

**Reply by makkes** [reply]
How about using [a Kustomization](https://fluxcd.io/flux/components/kustomize/kustomization/#kubeconfig-reference)?

**Comment by SonalinP** [comment]
the documentation gives information only for helmrelease .
Will you be able to give some more information how to achieve this for other resource creation in remote cluster like namespace , secret etc ? 

I

**Reply by makkes** [reply]
This [documentation section](https://fluxcd.io/flux/components/kustomize/kustomization/#remote-clusterscluster-api) is completely generic and not specific to HelmReleases. Where do you see documentation that's specific to HelmReleases?

**Comment by SonalinP** [comment]
Documentation is not clear, how to work with remote cluster using one common flux .
I am giving more details to explain the issue .
What I want to achieve - Flux is bootstrapped in cluster1 and  all flux related resources should be in cluster1. I want to install the only env specific resources(namespace, secret, helmrelease defined under cluster/common_resources in this case) to install   in cluster2 .

I tried adding kubceonfig ref in TC1_kustomization.yaml but it didnt work . IF I add it to helmrelease file , question here is how to add for namespace and secrets ? 
If you could let me know how to achieve this would be great .

Below is the dir structure of the repo : 
```
|---clusters
|   |---mycluster
|   |   |---TC1_kustomization.yaml
|   |   |---TC2_kustomization.yaml
|   |---common_resources	
|   |   |---namespace.yaml
|   |   |---secret.yaml
|   |   |---helmrelease.yaml
|---testchannels
|   |---TC1
|   |   |---kustomization.yaml
|   |   |---kustomization-config.yaml
|   |   |---values.yaml
|   |---TC2
|   |   |---kustomization.yaml
|   |   |---kustomization-config.yaml
|   |   |---values.yaml	

```
The main flux kustomization is path is clusters/mycluster

clusters/mycluster/TC1_kustomization.yaml
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: TC1
  namespace: test-flux
spec:
  interval: 1m0s
  path: ./testchannels/TC1
  prune: true
  sourceRef:
    kind: GitRepository
    name: testapp-gitops
  patches:
    - target:
        kind: HelmRelease
      patch: |-
        - op: replace
          path: /spec/targetNamespace
          value: staging
    - target:
        kind: Namespace
      patch: |-
        - op: replace
          path: /metadata/name
          value: staging
    - target:
        kind: Secret
      patch: |-
        - op: replace
          path: /metadata/namespace
          value: staging

```
clusters/common_resources/helmrelease.yaml	
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cm
  namespace: test-flux
spec:
  chart:
    spec:
      chart: Charts/testapp-svc/charts/CmService
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: testapp
  interval: 5m0s
  valuesFrom:
    - kind: ConfigMap
      name: TC1-config

```

testchannels/TC1/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../clusters/common_resources/helmrelease.yaml
  - ../../clusters/common_resources/namespace.yaml
  - ../../clusters/common_resources/secret.yaml
configMapGenerator:
  - name: TC1-config
    namespace: test-flux
    files:
      - values.yaml=values.yaml
configurations:
  - kustomization-config.yaml

```
The above configuration is working fine in same cluster where flux is installed .. but I want to deploy the targets in another cluster without installing flux there . As we cant install in the cluster2.
