### DISCUSSION TITLE
Is there any way to use environment variables in kustomization patches?

### DISCUSSION THREAD

**Discussion by devantler** [fluxcd/flux2#4179] [Q&A] [answered]
> [!NOTE]
> I am sorry if I am asking something that has already been asked. I was not able to find the information. 

I am creating a homelab where I want some of the default values to be dynamic. Can environment variables be read in Kustomization patches? I am thinking something like this:

```yaml
# The Kustomization file
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - ../../base/gitops-dashboard

patches:
  - path: patches/gitops-dashboard-values.yaml
    target:
      kind: HelmRelease
      name: gitops-dashboard
```

```yaml
# The patch file
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops-dashboard
  namespace: flux-system
spec:
  values:
    adminUser:
      username: admin
      passwordHash: $2a$12$6twAYNqxU3Pz3PqVYTJN9uE5LaMDj3R1.TgLvalUoKeLnzKsFkK3i
    ingress:
      hosts:
        - host: gitops.${DOMAIN} # This where/how I would like to use an environment variable if at all possible.
          paths:
            - path: /
              pathType: ImplementationSpecific
```

If this is not possible in any way, what do you recommend as the best practice to accomplish this?
