### DISCUSSION TITLE
How to use different Azure Workload Identities for ACR auth?

### DISCUSSION THREAD

**Discussion by dschniepp** [fluxcd/flux2#4187] [Q&A] [answered]
From how I understand the [docs](https://fluxcd.io/flux/components/source/helmrepositories/#azure-workload-identity) it is only possible to have a single Workload Identity per Cluster. As we run a multi-tenant setup we wanted to have individual Workload Identities, which have permissions for dedicated container registries. Did I miss something or is this currently not possible? Thank you for your help.

**Comment by somtochiama** [comment, marked as answer]
Hello @dschniepp ,

This is currently not possible. We use the client ID of whichever identity you annotate the source-controller service account with. However, this is a great feature request and I will start looking into an implementation.

**Reply by dschniepp** [reply]
@somtochiama thank you, for the reply and for taking this requirement into consideration. Maybe [External Secrets](https://external-secrets.io/v0.5.7/provider-azure-key-vault/#workload-identity) can help as an inspiration. This is how we solve our multi tenant key vault requirement. If I can help you, please reach out.

**Reply by dschniepp** [reply]
Looks like, with https://github.com/fluxcd/source-controller/pull/1195 you are already on it.

**Reply by somtochiama** [reply]
@dschniepp do you have the workload identities bound to the same service account or different service accounts?

> Looks like, with https://github.com/fluxcd/source-controller/pull/1195 you are already on it.

Yes, it is adding `serviceAccountName` field (to use the image pull secrets) but we can add this functionality in as well.

**Reply by dschniepp** [reply]
They are bound to different service accounts and the `SecretStore` references the service account.

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa-1
  namespace: tenant-1
  annotations:
    azure.workload.identity/client-id: xxx
    azure.workload.identity/tenant-id: xxx
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store-1
  namespace: tenant-1
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "xxx"
      serviceAccountRef:
        name: workload-identity-sa-1
```
