### DISCUSSION TITLE
patching apiVersion of manifest from Helm chart possible?

### DISCUSSION THREAD

**Discussion by cbricart** [fluxcd/flux2#4239] [Q&A] [answered]
I (currently) have to use some (stale - sic!) external Helm Chart which is unconditionally also generating a PDB with the deprecated and eventually removed apiVersion "policy/v1beta1" - which of course causes helm/kustomization reconciles to fail due to `»Helm upgrade failed: unable to build kubernetes objects from current release manifest: resource mapping not found for name: … ": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1 - ensure CRDs are installed first«`

I think I have tried almost everything to patch or even just discard this helm-generated manifest before it is dry-run'ed to no avail…

currently:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
…
spec:
  …
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - kind: PodDisruptionBudget
        $patch: delete
    …
```
and I also tried using the un-deprecatad `patches[]` Syntax(es) and other than `$patch: delete` also trying to replace the apiVersion, like:
```
…
  postRenderers:
  - kustomize:
      patches:
        - target:
            kind: PodDisruptionBudget
          patch: |
            - op: replace
              path: /apiVersion
              value: policy/v1
…
```
Also anything with `patches[]` in the referencing same level `kustomization.yaml` has not worked out…

Would that be possible at all to achieve…? Or do I really have to clone this external chart source just to replace its `policy/v1beta1` with `policy/v1` in the templates…?

**Comment by cbricart** [comment]
…according to [this](https://github.com/kubernetes/kubernetes/issues/89558), it's isn't at least possible to *mutate* some fields : `name`, `namespace`, `uid`, `kind`, `apiVersion`.
However, I have been under the impression that in my case (judge from the name) `postRender`, the helm-contoller would do something like calling `helm` with the intended values and parameters to retrieve the rendered yaml manifests from chart's templates/ and postRender.patch[] would act as some `sed`-pipe before the server-site dry-run…

**Comment by hxalid** [comment]
You can do this in a HelmRelease post-renderer as follows:

```
postRenderers:
    - kustomize:
        patches:
          - patch: |-
              - op: replace
                path: "/apiVersion"
                value: policy/v1
            target:
              kind: PodDisruptionBudget
              name: your-pdb-name-1
          - patch: |-
              - op: replace
                path: "/apiVersion"
                value: policy/v1
            target:
              kind: PodDisruptionBudget
              name: your-pdb-name-2
```
