### DISCUSSION TITLE
Secrets to connect to private GitLab

### DISCUSSION THREAD

**Discussion by jmsariron** [fluxcd/flux2#4252] [Q&A]
Hi there!

I'm trying to bootstrap a Flux for a private GitLab. It's workign right now, I just created a secret with a user/token as `username/password` as use it as a SecretRef in the GitRepository object.

But I see that, for every `GitRepository` I add to Flux, it creates and secret for that repository with an empty token. I'm not sure if this is normal or if I have misconfigured something and instead of a general secret to auth against the gitlab, flux should create a token for each app.

**Comment by stefanprodan** [comment]
When creating the source use `flux create source git --secret-ref <NAME OF THE SECRET WITH THE GL TOKEN>`.

**Reply by jmsariron** [reply]
K8s obejcts are created automatically when I push to the flux config repo the `GitRepository` and `Kustomization` objects, I thought this was the way?

**Reply by stefanprodan** [reply]
You can't bootstrap Flux more than once on a cluster, so I'm really confused about who creates the empty secrets.

**Reply by jmsariron** [reply]
The empty secrets are created when I add a new `GitRepository` and `Kustomization` (Or let's just say a repo containing k8s yamls) to the flux confif repo so it starts watching them

**Reply by stefanprodan** [reply]
Who creates the empty secrets? Flux doesn't do that, it only applies the manifests from the bootstrap repo.

**Reply by jmsariron** [reply]
The YAML I'm adding to the flux-config is:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-example-app
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: gitlab-deploy-auth
  url: <<My GitLab Repo>>
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-example-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-example-app
```

Just by adding that to the flux system, once it reconciles, it creates this secret:

![imagen](https://github.com/fluxcd/flux2/assets/98026719/595cdae4-a8a4-4a0d-973f-0b1292ac6a71)
