### DISCUSSION TITLE
Flux fails to deploy valid resources

### DISCUSSION THREAD

**Discussion by glitchcrab** [fluxcd/flux2#4264] [Q&A] [answered]
I'm hitting a bit of a weird one and I'm running out of ideas as to what is going on. If I `kustomize build . | kubectl apply -f -` in the directory then everything is deployed successfully, however `kustomize-controller` is failing to deploy the deployment and not logging a clear reason why:

```
kustomize-controller-7b44d694bf-8nzbq manager {"level":"info","ts":"2023-09-19T21:06:26.618Z","msg":"All dependencies are ready, proceeding with reconciliation","controller":"kustomization","controllerGroup":"kustomize.toolkit.fluxcd.io","controllerKind":"Kustomization","Kustomization":{"name":"local-controllers-cluster-api-operator","namespace":"cluster-room101-a7d-mc"},"namespace":"cluster-room101-a7d-mc","name":"local-controllers-cluster-api-operator","reconcileID":"3b42ce08-ad24-4b09-920c-b73dc2ea0476"}
kustomize-controller-7b44d694bf-8nzbq manager {"level":"info","ts":"2023-09-19T21:06:28.683Z","msg":"server-side apply for cluster definitions completed","controller":"kustomization","controllerGroup":"kustomize.toolkit.fluxcd.io","controllerKind":"Kustomization","Kustomization":{"name":"local-controllers-cluster-api-operator","namespace":"cluster-room101-a7d-mc"},"namespace":"cluster-room101-a7d-mc","name":"local-controllers-cluster-api-operator","reconcileID":"3b42ce08-ad24-4b09-920c-b73dc2ea0476","output":{"CustomResourceDefinition/addonproviders.operator.cluster.x-k8s.io":"created","CustomResourceDefinition/bootstrapproviders.operator.cluster.x-k8s.io":"created","CustomResourceDefinition/controlplaneproviders.operator.cluster.x-k8s.io":"created","CustomResourceDefinition/coreproviders.operator.cluster.x-k8s.io":"created","CustomResourceDefinition/infrastructureproviders.operator.cluster.x-k8s.io":"created","Namespace/cabpt-system":"created","Namespace/cacppt-system":"created","Namespace/capi-operator-system":"created","Namespace/capi-system":"created","Namespace/sidero-system":"created"}}
kustomize-controller-7b44d694bf-8nzbq manager {"level":"info","ts":"2023-09-19T21:06:29.156Z","logger":"KubeAPIWarningLogger","msg":"would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"manager\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container \"manager\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or containers \"manager\", \"kube-rbac-proxy\" must set securityContext.runAsNonRoot=true), seccompProfile (pod or containers \"manager\", \"kube-rbac-proxy\" must set securityContext.seccompProfile.type to \"RuntimeDefault\" or \"Localhost\")"}
kustomize-controller-7b44d694bf-8nzbq manager {"level":"error","ts":"2023-09-19T21:06:29.205Z","msg":"Reconciliation failed after 2.587229388s, next try in 1m0s","controller":"kustomization","controllerGroup":"kustomize.toolkit.fluxcd.io","controllerKind":"Kustomization","Kustomization":{"name":"local-controllers-cluster-api-operator","namespace":"cluster-room101-a7d-mc"},"namespace":"cluster-room101-a7d-mc","name":"local-controllers-cluster-api-operator","reconcileID":"3b42ce08-ad24-4b09-920c-b73dc2ea0476","revision":"main@sha1:94e165bd0cbdc3f03941292a1f241b181be127ed","error":"BootstrapProvider/cabpt-system/talos dry-run failed, reason: InternalError: Internal error occurred: error resolving resource\nCustomResourceDefinition/addonproviders.operator.cluster.x-k8s.io created\nCustomResourceDefinition/bootstrapproviders.operator.cluster.x-k8s.io created\nCustomResourceDefinition/controlplaneproviders.operator.cluster.x-k8s.io created\nCustomResourceDefinition/coreproviders.operator.cluster.x-k8s.io created\nCustomResourceDefinition/infrastructureproviders.operator.cluster.x-k8s.io created\nNamespace/cabpt-system created\nNamespace/cacppt-system created\nNamespace/capi-operator-system created\nNamespace/capi-system created\nNamespace/sidero-system created\n"}
```

My first thought was the PSS policies were causing the deployment to be rejected, however that log line is informational - if I deploy the manifest manually then all is fine. 

The error on the 4th line is misleading - the BootstrapProvider cannot be deployed because the capi-operator pod never started. The (lack of) creation of the deployment seems to be the root cause.

Can anyone point me in the right direction to try and troubleshoot this? The specific manifests are [here](https://github.com/a7d-corp/homelab-clusters-fleet/tree/main/infrastructure/controllers/management/cluster-api-operator)

**Comment by hiddeco** [comment]
What happens when you apply them using SSA? As described in https://fluxcd.io/flux/faq/#what-is-the-behavior-of-kustomize-used-by-flux

**Comment by glitchcrab** [comment]
In theory, everything is deployed correctly:

```
✗  kustomize build --load-restrictor=LoadRestrictionsNone . | kubectl apply --server-side --dry-run=server -f-
namespace/cabpt-system serverside-applied (server dry run)
namespace/cacppt-system serverside-applied (server dry run)
namespace/capi-operator-system serverside-applied (server dry run)
namespace/capi-system serverside-applied (server dry run)
namespace/sidero-system serverside-applied (server dry run)
customresourcedefinition.apiextensions.k8s.io/addonproviders.operator.cluster.x-k8s.io serverside-applied (server dry run)
customresourcedefinition.apiextensions.k8s.io/bootstrapproviders.operator.cluster.x-k8s.io serverside-applied (server dry run)
customresourcedefinition.apiextensions.k8s.io/controlplaneproviders.operator.cluster.x-k8s.io serverside-applied (server dry run)
customresourcedefinition.apiextensions.k8s.io/coreproviders.operator.cluster.x-k8s.io serverside-applied (server dry run)
customresourcedefinition.apiextensions.k8s.io/infrastructureproviders.operator.cluster.x-k8s.io serverside-applied (server dry run)
role.rbac.authorization.k8s.io/capi-operator-leader-election-role serverside-applied (server dry run)
clusterrole.rbac.authorization.k8s.io/capi-operator-manager-role serverside-applied (server dry run)
clusterrole.rbac.authorization.k8s.io/capi-operator-metrics-reader serverside-applied (server dry run)
clusterrole.rbac.authorization.k8s.io/capi-operator-proxy-role serverside-applied (server dry run)
rolebinding.rbac.authorization.k8s.io/capi-operator-leader-election-rolebinding serverside-applied (server dry run)
clusterrolebinding.rbac.authorization.k8s.io/capi-operator-manager-rolebinding serverside-applied (server dry run)
clusterrolebinding.rbac.authorization.k8s.io/capi-operator-proxy-rolebinding serverside-applied (server dry run)
secret/sidero-config serverside-applied (server dry run)
service/capi-operator-controller-manager-metrics-service serverside-applied (server dry run)
service/capi-operator-webhook-service serverside-applied (server dry run)
Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "manager" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "manager" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or containers "manager", "kube-rbac-proxy" must set securityContext.runAsNonRoot=true), seccompProfile (pod or containers "manager", "kube-rbac-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/capi-operator-controller-manager serverside-applied (server dry run)
certificate.cert-manager.io/capi-operator-serving-cert serverside-applied (server dry run)
issuer.cert-manager.io/capi-operator-selfsigned-issuer serverside-applied (server dry run)
mutatingwebhookconfiguration.admissionregistration.k8s.io/capi-operator-mutating-webhook-configuration serverside-applied (server dry run)
validatingwebhookconfiguration.admissionregistration.k8s.io/capi-operator-validating-webhook-configuration serverside-applied (server dry run)
Error from server (NotFound): the server could not find the requested resource (patch bootstrapproviders.operator.cluster.x-k8s.io talos)
Error from server (NotFound): the server could not find the requested resource (patch controlplaneproviders.operator.cluster.x-k8s.io talos)
Error from server (NotFound): the server could not find the requested resource (patch coreproviders.operator.cluster.x-k8s.io cluster-api)
Error from server (NotFound): the server could not find the requested resource (patch infrastructureproviders.operator.cluster.x-k8s.io sidero)
```

The same warning from the API about the pod violating the restricted PSS is there, but that wouldn't stop it being deployed as the namespace is labelled to allow it to run.

**Comment by stefanprodan** [comment]
I think you need to split this into two Kustomizations with dependsOn and wait, so that Flux first installs the webhooks and CRDs, then it waits for the webhooks to become ready and only then it will apply the CRs.

@somtochiama if you have time, please try to replicate this.

**Comment by somtochiama** [comment]
@glitchcrab The error you are getting - `BootstrapProvider/cabpt-system/talos dry-run failed, reason: InternalError: Internal error occurred: error resolving resource` is from Kubernetes because the conversion webhook hasn't been deployed yet as it is created by the same Kustomization. (Not a great error msg but that's from Kubernetes, it might be worth opening an issue there for it)

I moved the line that [installs the cluster API operator](https://github.com/somtochiama/homelab-clusters-fleet/blob/22a93d6d89ada0c793a731d7144a870fa0b8fa5b/infrastructure/controllers/base/kustomization.yaml#L4) into the base folder that contains ingress-nginx and cert-manager and made the Kustomization that installs the bootstrap provider depend on it 

```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-cluster
  namespace: flux-system
spec:
  interval: 2m
  ref:
    branch: main
  url: https://github.com/somtochiama/homelab-clusters-fleet
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-cluster
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  dependsOn:
    - name: "homelab-cluster-controllers"
    - name: "homelab-cluster-certmanager"
  sourceRef:
    kind: GitRepository
    name: homelab-cluster
    namespace: flux-system
  path: ./infrastructure/controllers/management
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-cluster-controllers
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-cluster
    namespace: flux-system
  path: ./infrastructure/controllers/base
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-cluster-certmanager
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-cluster
    namespace: flux-system
  path: ./infrastructure/controllers/base/cert-manager
```
