### DISCUSSION TITLE
Kustomize decryption.secretRef doesn't have namespace property

### DISCUSSION THREAD

**Discussion by cer** [fluxcd/flux2#4286] [Q&A] [answered]
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
...
  decryption:
    provider: sops
    secretRef:
      name: sops-age
```

I had a Kustomization that was in a different namespace to the `sops-age` secret.
In order to enable decryption I had to change it's namespace to be the same as the secret's.

Is there any particular reason why [`decryption.secret`](https://fluxcd.io/flux/components/kustomize/api/v1/#kustomize.toolkit.fluxcd.io/v1.Decryption) doesn't have a `namespace` property?
