### DISCUSSION TITLE
HelmRelease configMap values are not updated when new change in in-line spec.values is pushed to github repo.

### DISCUSSION THREAD

**Discussion by ondrejFuchs** [fluxcd/flux2#4287] [Q&A] [answered]
Hi, 

I am trying to investigate, why my configMap (used under my HelmRelease) is not updated during flux reconciliation. 

My repo folder structure is:
```
charts/myChart
flux-system/ (generated files by flux bootstrap github command)
namespaces/
releases/myChartRelease/
```
In **releases/myChartRelease** folder I have `HelmRelease.yaml` and `GitRepository.yaml`: 

```
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: myChart-repository
  namespace: myChart
spec:
  interval: 1m
  url: <url> (github repo url)
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
```
```
and helmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myChart
  namespace: myChart
spec:
  interval: 1m
  chart:
    spec:
      chart: charts/myChart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: myChart-repository
        namespace: myChart
  values:
    config:
      TEST_VAR: "TEST"
```

When I change **TEST_VAR** to different value than `TEST` (for example `TEST_2`), reconciliation is triggered, new version is deployed to the cluster (new revision pod is deployed) but with the same configMap value for TEST_VAR (= `TEST`). When I describe configMap with command `kubectl describe configmap myChart-configmap -n myChart`, I can see that label has been changed: `helm.sh/chart=myChart-<version>_<sha>`, but **TEST_VAR** is still the same. 

Also I could share that configMap is combined with default values defined under `charts/myChart/values.yaml` and in-line defined values under HelmRelease.yaml (`TEST_VAR` variable is not defined in `charts/myChart/values.yaml`). 

When I deleted helmRelease with command `kubectl apply -f helmRelease.yaml` and applied again, configMap has been changed. 

Used versions:
  * fluxcd/source-controller:v1.1.1
  * fluxcd/kustomize-controller:v1.1.0
  * fluxcd/helm-controller:v0.36.1
  * fluxcd/notification-controller:v1.1.0
 
Also not sure if it's related, but under `kustomize-controller` logs I found error with Reconciliation failed: 
`{"level":"error","ts":"2023-09-28T11:12:24.904Z","msg":"Reconciliation failed after 121.245977ms, next try in 10m0s","controller":"kustomization","controllerGroup":"kustomize.toolkit.fluxcd.io","controllerKind":"Kustomization","Kustomization":{"name":"flux-system","namespace":"flux-system"},"namespace":"flux-system","name":"flux-system","reconcileID":"bc5832c7-495a-4720-a242-28916a43956b","revision":"master@sha1:f7dbeb771749c34e2a490c9bbf1a7306039da385","error":"failed to decode Kubernetes YAML from /tmp/kustomization-639678744/charts/myChart/Chart.yaml: missing kind in object {{v2 } {{ } map[] map[]}} <nil>"}`.

My only one Kustomization is general one created during `flux bootstrap github` command. I am not sure if I could have own helm chart with templates in the same repo as `flux-system` (path ./).

Thank you for advice.
