### DISCUSSION TITLE
Filter to specific kustomization in grafana annotations

### DISCUSSION THREAD

**Discussion by TheEdgeOfRage** [fluxcd/flux2#4288] [Q&A] [answered]
I've set up Grafana annotations to show deployments on our dashboards, but the dashboard shows all deployments, not just the ones relevant to the service that the dashboard is for. I want to only show annotations for a single flux kustomization for a given dashboard. The flux annotation event tags are just "flux", "kustomize-controller", "revision:deploy@sha1". none of which allow me to filter by kustomization. Any idea how to address this?

**Comment by TheEdgeOfRage** [comment, marked as answer]
I didn't realize that there's the eventMetadata key on the Alert rule. I was looking for "tags" on the docs and missed this one completely. For reference, you can specify custom tags using eventMetadata, like this:

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: app-grafana-annotations
  namespace: flux-system
spec:
  providerRef:
    name: grafana
  eventSeverity: info
  eventMetadata:
    team: frontend
    app: app
  eventSources:
    - kind: Kustomization
      name: app
      namespace: flux-system
  inclusionList:
    - "configured"
    - "created"
```
