### DISCUSSION TITLE
Run pre-deploy job every time

### DISCUSSION THREAD

**Discussion by davidgengenbach** [fluxcd/flux2#4302] [Q&A]
Is there a way to run a [pre-deploy job](https://fluxcd.io/flux/use-cases/running-jobs/) **every** time?
Currently, it seems like a job is only executed exactly once.
The only way I found to get FluxCD to run the job is to change some job field (e.g., the name, the image tag, ...) which is not feasible for an automated deployment.

Example job:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
spec:
  template:
    spec:
      restartPolicy: Always
      containers:
        - name: test-job
          image: ubuntu:23.04
          command:
            - date
```

Thanks a lot 🥳
