### DISCUSSION TITLE
Patching existing resource (ssa: merge) and append to list

### DISCUSSION THREAD

**Discussion by kaotika** [fluxcd/flux2#4312] [Q&A] [answered]
Hi,

I'am trying out capsule (provides multi-tennancy) with flux using this a bit outdated repo: https://github.com/clastix/flux2-capsule-multi-tenancy.

One step is to patch an existing CRD by adding a value to a list (append `system:serviceaccount:dev-team` to `.spec.userGroups`).

```yaml
apiVersion: capsule.clastix.io/v1beta2
kind: CapsuleConfiguration
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: enabled
    kustomize.toolkit.fluxcd.io/ssa: merge
    meta.helm.sh/release-name: capsule
    meta.helm.sh/release-namespace: capsule-system
  labels:
    app.kubernetes.io/instance: capsule
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: capsule
    app.kubernetes.io/version: 0.3.3
    helm.sh/chart: capsule-0.4.6
    helm.toolkit.fluxcd.io/name: capsule
    helm.toolkit.fluxcd.io/namespace: flux-system
    kustomize.toolkit.fluxcd.io/name: tenants
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: default
spec:
  enableTLSReconciler: true
  forceTenantPrefix: false
  nodeMetadata:
    forbiddenAnnotations:
      denied: []
      deniedRegex: ""
    forbiddenLabels:
      denied: []
      deniedRegex: ""
  overrides:
    TLSSecretName: capsule-tls
    mutatingWebhookConfigurationName: capsule-mutating-webhook-configuration
    validatingWebhookConfigurationName: capsule-validating-webhook-configuration
  protectedNamespaceRegex: ""
  userGroups:
  - capsule.clastix.io
```

Cause the solution in the repo does not work (anymore?!), I found the solution in the flux FAQ (How to patch CoreDNS and other pre-installed addons? ). My patch config looks:

```yaml
apiVersion: capsule.clastix.io/v1beta2
kind: CapsuleConfiguration
metadata:
  name: default
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
spec:
  userGroups:
    - system:serviceaccounts:dev-team
```

After reconciliation the userGroups is just replaced with my patch version not appended:

```yaml
spec:
  userGroups:
    - system:serviceaccounts:dev-team
```

what I expect is:

```yaml
spec:
  userGroups:
    - capsule.clastix.io
    - system:serviceaccounts:dev-team
```

Do I misunderstand the SSA feature or is there any (other) way to append the value?

**Comment by hiddeco** [comment, marked as answer]
As [merge behavior of lists is undefined by default](https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy), lists are replaced in patches and you would need to include the list in full.

**Reply by kaotika** [reply]
Thanks! That helped me to realize, that my way of solving wasn't the best approach ^^ it's possible but not really the GitOps way. Splitting the config into multiple files breaks with "single-source-of-truth".

By the way: if someone really needs in-cluster patching and SSA doesnt fit. Kyverno has mutate rules. Using this it's possible to add something to a list with patchesJson6902 patch.

**Reply by stefanprodan** [reply]
Flux Kustomization does support json patches for example:

```
patches:
  - patch: |
      - op: add
        path: '/spec/userGroups/-'
        value: 'system:serviceaccounts:dev-team'
    target:
      kind: CapsuleConfiguration
      name: default
```
