### DISCUSSION TITLE
How to delete helm realize from Kustomization. Please helm

### DISCUSSION THREAD

**Discussion by daniltreshchev** [fluxcd/flux2#4331] [Q&A]
I have infrastructure.yaml for my k8s.test-bm cluster

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: helmrepositories
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./helmrepositories
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps
  prune: true
  validation: client
  dependsOn:
    - name: helmrepositories
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-base-patches
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./patches/cluster-base/k8s.test-bm
  prune: true
  dependsOn:
    - name: infrastructure
  validation: client
```

I have ingress in ./apps/ingress folder with ingress-release.yaml
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress
  namespace: ingress
spec:
  releaseName: ingress-release
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress
        namespace: flux-system
      version: "4.8.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
```

and I would like to delete this ingress on the cluster k8s.test-bm

I write this in ./patches/cluster-base/k8s.test-bm

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/ingress/ingress-release.yaml
patchesStrategicMerge:
  - ./delete-ingress-helmrelease.yaml
```

delete-ingress-helmrelease
```
$patch: delete
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress
  namespace: ingress
```

but it is not working. 

How can I achieve what I want, please help
