### DISCUSSION TITLE
Automatic promotion from dev to production cluster (image tag)

### DISCUSSION THREAD

**Discussion by hrvatskibogmars** [fluxcd/flux2#4334] [Q&A]
How can I automate deployments across two Kubernetes clusters (dev and prod) using Flux from a single Git repository? Specifically, I'd like to trigger a deployment to the prod cluster automatically when a deployment is successful in the dev cluster

What are the recommended strategies and best practices for achieving this synchronization and promotion between clusters? 

I have seen this but this is for the entire new helm chart version
https://fluxcd.io/flux/use-cases/gh-actions-helm-promotion/

This is my setup (structure) of the flux repo
https://github.com/fluxcd/flux2-kustomize-helm-example

I guess I can modify this to basically change the image version instead of the helm chart version - and some bot that will auto approve it or directly push it to the main branch. Or maybe Alrert will trigger a GitHub action that will basically retag image version dev-SHA to prod-SHA. And then image automation can pick it up.

**Comment by hrvatskibogmars** [comment]
```
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: netshot-dispatch
  namespace: debug
spec:
  providerRef:
    name: github
  summary: "Trigger promotion"
  eventMetadata:
    env: dev
    cluster: dev-cluster
    **image: <GET_IMAGE_VERSION>**
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: netshot
  inclusionList:
    - ".*.upgrade.*succeeded.*"
```
Is it somehow possible to get this image version here?
