### DISCUSSION TITLE
Postbuild substition order

### DISCUSSION THREAD

**Discussion by cciobanu-aily** [fluxcd/flux2#4336] [Q&A]
I am using the postbuild substition feature from flux (https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-variable-substitution). 
I am using multiple config maps to do the substation, but I cannot find in the documentation if there it's any order. For example 
```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
spec:
  interval: 5m
  path: "./apps/"
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: config1
      - kind: ConfigMap
        name: config2
      - kind: ConfigMap
        name: config3
 ```
 
 If I have the same variable in all configs which one will be used?

**Comment by BertelBB** [comment]
From my personal tests it seems that variables are applied in the order they appear in the list of `.spec.postBuild.substituteFrom`. Meaning that if `config1`, `config2` and `config3` all define the same variable then the value defined in `config3` is used, unless the value is empty.

```yaml
kind: ConfigMap
metadata:
  name: config1
data:
  var: one
---
kind: ConfigMap
metadata:
  name: config2
data:
  var: two
---
kind: ConfigMap
metadata:
  name: config3
data:
  var: three
```

In this example `${var}` would output `three`. Setting `.data.var: ""` in `config3` would result in `${var}` outputting `two`.
