### DISCUSSION TITLE
How to reconcile a Kustomization if a value in resources: property changes?

### DISCUSSION THREAD

**Discussion by wibed** [fluxcd/flux2#4349] [Q&A]
i have a bootstrapped repo.
flux does log regularely
i can successfully run commands such as: `flux reconcile kustomization flux-system --with-source`

yet changes pushed to the repo are recognized, yet not acted upon.
***Z info GitRepository/flux-system.flux-system - garbage collected 1 artifacts 

as change i do include new lines with a path to deployments i would like to include to make an example:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  ...
  - ./docker-registry <--- this line is included
```

id expect some output but it is completely ignored. maybe i am missing something obvious
if someone could point that out for me would be great thank you.
