### DISCUSSION TITLE
Missing recommended label "app.kubernetes.io/name"

### DISCUSSION THREAD

**Discussion by langecode** [fluxcd/flux2#4378] [General]
There is a number of [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) for Kubernetes and it seems Flux manifests comes with most. However `app.kubernetes.io/name` is not part of the default labels. I was wondering if there is any reason for this label not being there?

![image](https://github.com/fluxcd/flux2/assets/5438266/65a213c7-29bf-4e88-bf60-8a8142aad0e2)

**Comment by akuzia** [comment]
Yes, having a `name` label will ease Flux integration into existing log/metric pipelines.
For now we've had to do add labels via patches for all the flux controller pods:
```yaml
patches:
  - target:
      kind: Deployment
      name: source-controller
    patch: |
      - op: add
        path: /spec/template/metadata/labels/app.kubernetes.io~1name
        value: source-controller
  - target:
      kind: Deployment
      name: kustomize-controller
    patch: |
      - op: add
        path: /spec/template/metadata/labels/app.kubernetes.io~1name
        value: kustomize-controller
  - target:
      kind: Deployment
      name: helm-controller
    patch: |
      - op: add
        path: /spec/template/metadata/labels/app.kubernetes.io~1name
        value: helm-controller
  - target:
      kind: Deployment
      name: notification-controller
    patch: |
      - op: add
        path: /spec/template/metadata/labels/app.kubernetes.io~1name
        value: notification-controller
  - target:
      kind: Deployment
      name: image-reflector-controller
    patch: |
      - op: add
        path: /spec/template/metadata/labels/app.kubernetes.io~1name
        value: image-reflector-controller
  - target:
      kind: Deployment
      name: image-automation-controller
    patch: |
      - op: add
        path: /spec/template/metadata/labels/app.kubernetes.io~1name
        value: image-automation-controller

```

I do not see how adding a label to manifests will be an issue. Maybe even migrating from generic `app` label to recommended in [some](https://github.com/fluxcd/flux2/blob/ccb9d129274d5fd7203625075253fef6b7df0c45/manifests/policies/allow-webhooks.yaml#L13) resources, but it may become a problem.

Is it worth bumping to an issue?
