### DISCUSSION TITLE
what would be the best strategy to change bootstrap github owner and repository

### DISCUSSION THREAD

**Discussion by zoezhangmattr** [fluxcd/flux2#4386] [Q&A]
we have already running flux2 , with bootstrap to owner github-org-1, repo name flux-repo
now we want to transfer the current flux-repo to another org github-org-2, 
just asking if anyone knows,
* is there any impact to current flux system, and the existent helmreleases.
* how do i change the owner , do i run bootstrap again. 
any help is appreciated, thanks

**Comment by stefanprodan** [comment]
GitHub should handle the redirect and Flux will follow it. If you don't actually transfer the repo but you make a copy, then, you need to do the following:
- delete the flux-system secret (contains the SSH private key, and Flux will no longer be able to access to old repo)
- rerun bootstrap for the new URL (the Flux CLI will generate a SSH private key and will add the deploy key to the new repo)

**Reply by zoezhangmattr** [reply]
hey @stefanprodan thanks for your reply, just wanna confirm, does it mean i can transfer the repo to new org, i know github redirect it when we do git clone without changing remote, is it the same that you mentioned?
in this case, do i need to worry about the git url in auto-generated file in gotk-sync.yaml , 
if i get what you said, the deploy key carried over when doing github transfer, so flux still has access, and no need to do bootstrap command again , below is the original command we set up in org1
```shell
flux  bootstrap github \
  --owner=org1 \
  --repository=flux-repo \
......
```


```yaml
# This manifest was generated by flux. DO NOT EDIT.
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: ssh://git@github.com/org1/flux-repo
```
