### DISCUSSION TITLE
Does helm-controller fetch chart dependencies, if they exist in charts/ subdirectory?

### DISCUSSION THREAD

**Discussion by baracoder** [fluxcd/flux2#4391] [Q&A]
We keep our helm-charts around in a git repository and pre-fetch them using `helm pull ... --untar`
E.g. jaeger:
```
helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
helm repo update
helm pull jaegertracing/jaeger --untar
```
This downloads the chart and all of the dependencies into a local directory. With all helm-dependencies in the  `charts/` subdirectory.
```
% ls charts/
cassandra/  common/  elasticsearch/  kafka/
```

The Chart.yaml has remote repositories defined:
```
% cat Chart.yaml 
apiVersion: v2
appVersion: 1.51.0
dependencies:
- condition: provisionDataStore.cassandra
  name: cassandra
  repository: https://charts.helm.sh/incubator
  version: 0.15.3
- condition: provisionDataStore.elasticsearch
  name: elasticsearch
  repository: https://helm.elastic.co
  version: ^7.11.1
- condition: provisionDataStore.kafka
  name: kafka
  repository: https://charts.bitnami.com/bitnami
  version: ^19.1.5
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 1.16.0
...
```
Does the helm-controller attempt to fetch new versions of the dependencies from the repositories or use the files from the `charts/` directory?
