### DISCUSSION TITLE
ImagePolicy: Regex don't match 2023.11.2 but match 2023.9.3

### DISCUSSION THREAD

**Discussion by RogerSik** [fluxcd/flux2#4401] [Q&A]
```
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: hass
  namespace: smart-home
spec:
  imageRepositoryRef:
    name: hass
  filterTags:
    pattern: ^\d{4}\.(0?[1-9]|1[012])\.(0?[1-9]|[12][0-9]|3[01])$
  policy:
    alphabetical:
      order: asc

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: hass
  namespace: smart-home
spec:
  image: ghcr.io/home-assistant/home-assistant
  interval: 24h
  exclusionList:
    - 'dev*'
    - '(?:(?:20)[0-22]{2})' # exclude releases from 2000 to 2022

```

```
 k describe ImagePolicy hass    
  Normal  Succeeded  5s    image-reflector-controller  Latest image tag for 'ghcr.io/home-assistant/home-assistant' resolved to 2023.9.3
```

But [regex101.com says that both tags should be accepted](https://regex101.com/r/AbxJSg/1)
<img width="312" alt="14_07-03-51" src="https://github.com/fluxcd/flux2/assets/165814/76cdc085-7a56-4417-b99d-e277d9994b58">

When searching for 
```
  filterTags:
    pattern: '2023.11.2'
```
it works

```
$ k describe ImagePolicy hass    
Latest image tag for 'ghcr.io/home-assistant/home-assistant' resolved to 2023.11.2
```
