### DISCUSSION TITLE
HelmRelease variable substitution and Kustomization Postbuild bevahiour

### DISCUSSION THREAD

**Discussion by lupindeterd** [fluxcd/flux2#4413] [Q&A] [answered]
hi, 

  Perhaps this quite a simple question but being new Flux  I'm a bit lost. Say I have following manifest:
a) HelmRelease with this spec.
```
spec:
  values:
    replicaCount: ${REPLICAS}
```
b) ConfigMap
```
data:
    REPLICAS: "2"
```
c) Flux KS
```
spec:
  interval: 5m
  path: "./apps/"
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
```

Q1: Which namespace shall I put the Flux KS?
Q2: In which namespace do I create the ConfigMap that contains the variables with values?  I want install the HelmRelease in namespace other than `flux-system`.
Q3. Who does Flux render and apply the HelmRelease in relation to substitution? Does it read what's in the ConfigMap first the pass it similar to `--set key=value` in helm cli?

Cheers
Lupin

**Comment by fossum** [comment, marked as answer]
I am by no means an expert and may have some of this wrong, but I see you have no answer and I just got mine working. Here is what I used and it maybe missing some of the answer as I just got it working.

1. Below I've listed my ks.yaml file which is in the flux-system namespace.
2. My configmap (named cluster-config) is also in the flux-system namespace. Likely has to be there as you cannot define any specific namespace.
3. I don't really know what you're asking here, but I think you want to know if the values come from the configmap. The answer to that is yes.

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr
  namespace: flux-system
spec:
  interval: 10m
  path: apps/torrents/sonarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
```
