### DISCUSSION TITLE
HelmRelease with subcharts/dependencies

### DISCUSSION THREAD

**Discussion by kgorskowski** [fluxcd/flux2#443] [Q&A] [answered]
Sorry if this has been solved somewhere before, I couldn't find it. I was trying to "migrate" a monitoring stack from a vanilla helm install to a flux workflow. Its based on this  [loki-stack grafana helm chart ](https://github.com/grafana/loki/tree/master/production/helm/loki-stack). The HelmRelease is picked up but it seems like the provided values are not processed correctly. When setting eg grafana and/or prometheus on "enabled" the values are picked up but its only ever the loki pod that is starting. So maybe its because they depend on subcharts definded in the requirements.yaml? Or am I missing something obvious? Where would be the best place to debug things like that?
Thanks for any input!
output from `helm get values`
```
grafana:
  enabled: true
prometheus:
  enabled: true
``` 
and my HelmRelease yaml:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      version: "2.0.x"
  values:
    prometheus:
      enabled: true
    grafana:
      enabled: true
```
- edit - I just tried a manual debug like stated [here in the docs](https://github.com/fluxcd/helm-operator/blob/0d0700bf0c3431b09700d0a50cc56ed7e0c48ab4/docs/helmrelease-guide/debugging.md) - when filtering out the existing `spec.values` a manual `helm upgrade` would spin up the missing deployments, volumes, service accounts and so on. So I guess the syntax is correct and the values are in the right place but somehow the whole subchart rollout is just not picking up
