### DISCUSSION TITLE
Passing Docker Pull Secret as a Value

### DISCUSSION THREAD

**Discussion by Snixells** [fluxcd/flux2#4434] [Q&A]
Hey there! 

I am using flux for a while now and I have a Problem i can't find a solution for:

I am trying to pass a docker pull secret to a HelmRelease. For that i have taken the following steps:

1. I've saved my docker credentials in a json file with the following format: 
```json
{
   "auths":{
      "url-1.com":{
         "username":"my_username",
         "password":"my_password",
         "auth":"my_auth"
      }
   }
}
```
This i then encrypted using age and sops but I'll keep that part out for simplicity reasons. 

2. I am then creating a secret from that using the Kustomize secretGenerator:
```yaml
secretGenerator:
  - name: docker-pull-secret
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=docker_creds.json
```

3. I use the generated secret in my HelmRelease to pass the docker config to my helm chart: 
```yaml
  valuesFrom:
    - kind: Secret
      name: docker-pull-secret
      valuesKey: .dockerconfigjson
      targetPath: artifactoryPullSecretDockerconfigjson
```

This way the Secret is properly created but passing the value to my HelmRelease raises an Error: 

```
Warning  error   1s (x4 over 6s)  helm-controller  unable to merge value from key '.dockerconfigjson' in Secret 'my-ns/docker-pull-secret-bkc489h47t' into target path 'artifactoryPullSecretDockerconfigjson': key "de\": {\n\t\t\t\"username\": \"my_username"" has no value (cannot end with ,)
```

I already tried a lot including 
- Converting the json to a string
- Trying yaml 
- Different ways of formatting the json 

But none of this works. I do really hope that there is a solution to the problem. Thanks a lot in advance!

**Comment by stefanprodan** [comment]
Instead of mapping the JSON to values, you can create the image pull secret on the cluster with a Flux Kustomization and refer its name in the values like so.

helmrelease.yaml:

```yaml
values:
  imagePullSecrets:
    - name: docker-pull-secret
```

kustomization.yaml

```yaml
secretGenerator:
  - name: docker-pull-secret
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=docker_creds.json
```

kustomizeconfig.yaml

```yaml
nameReference:
- kind: Secret
  version: v1
  fieldSpecs:
  - path: spec/values/imagePullSecrets/name
    kind: HelmRelease
```
