### DISCUSSION TITLE
Kustomization fails - due to post configuration of cert-manager

### DISCUSSION THREAD

**Discussion by pooranima-subramanian** [fluxcd/flux2#4440] [Q&A]
Hello everyone, 
Currently, we are working on a project that works only with flux to deploy all the components in the cluster. We want to deploy the cert-manager and PostgreSQL operator along with the post-configuration files in a single deployment. When trying to do this, flux is trying to deploy the post-config files even, before taking into account the helm release of the application. In this case, it's throwing the error
 ```
 Certificate/ingress/cert-ingress dry-run failed: failed to get API group resources: unable to retrieve the complete list
 of server APIs: cert-manager.io/v1: the server could not find the requested resource
 ```
 We searched for solutions in different forums, but we were not successful. We tried using `depends on`, `annotations`, and `kustomization.yaml` none of these worked. 

We are looking for suggestions and solutions that are applied using flux. 
 
 Failing Kustomization
 ```yaml
Name:         kustomize-applications
Namespace:    flux-main
Labels:       kustomize.toolkit.fluxcd.io/name=kustomize-main
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  <none>
API Version:  kustomize.toolkit.fluxcd.io/v1
Kind:         Kustomization
Metadata:
  Creation Timestamp:  2023-11-30T14:30:22Z
  Finalizers:
    finalizers.fluxcd.io
  Generation:  1
  Managed Fields:
    API Version:  kustomize.toolkit.fluxcd.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:kustomize.toolkit.fluxcd.io/name:
          f:kustomize.toolkit.fluxcd.io/namespace:
      f:spec:
        f:dependsOn:
        f:interval:
        f:path:
        f:prune:
        f:sourceRef:
          f:apiVersion:
          f:kind:
          f:name:
          f:namespace:
    Manager:      kustomize-controller
    Operation:    Apply
    Time:         2023-11-30T14:30:22Z
    API Version:  kustomize.toolkit.fluxcd.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizers.fluxcd.io":
    Manager:      gotk-kustomize-controller
    Operation:    Update
    Time:         2023-11-30T14:30:22Z
    API Version:  kustomize.toolkit.fluxcd.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
        f:lastAttemptedRevision:
    Manager:         gotk-kustomize-controller
    Operation:       Update
    Subresource:     status
    Time:            2023-11-30T14:40:53Z
  Resource Version:  4026
  UID:               0aa53478-cb58-4c04-b180-d0ff721ebb16
Spec:
  Depends On:
    Name:       kustomize-main
    Namespace:  flux-system
  Force:        false
  Interval:     10m0s
  Path:         ./
  Prune:        true
  Source Ref:
    API Version:  source.toolkit.fluxcd.io/v1
    Kind:         GitRepository
    Name:         git-applications
    Namespace:    flux-source
Status:
  Conditions:
    Last Transition Time:  2023-11-30T14:40:53Z
    Message:               Detecting drift for revision applications@sha1:58ca20ae08dfefefb701381f520362134b1442b7 with a timeout of 9m30s
    Observed Generation:   1
    Reason:                ProgressingWithRetry
    Status:                True
    Type:                  Reconciling
    Last Transition Time:  2023-11-30T14:40:53Z
    Message:               Certificate/ingress/cert-ingress dry-run failed: failed to get API group resources: unable to retrieve the complete list of server APIs: cert-manager.io/v1: the server could not find the requested resource

    Observed Generation:    1
    Reason:                 ReconciliationFailed
    Status:                 False
    Type:                   Ready
  Last Attempted Revision:  applications@sha1:58ca20ae08dfefefb701381f520362134b1442b7
  Observed Generation:      -1
Events:
  Type     Reason                Age                  From                  Message
  ----     ------                ----                 ----                  -------
  Warning  ReconciliationFailed  18m                  kustomize-controller  ClusterIssuer/ingress/letsencrypt dry-run failed: failed to get API group resources: unable to retrieve the complete list of server APIs: cert-manager.io/v1: the server could not find the requested resource
  Warning  ReconciliationFailed  8m26s (x2 over 18m)  kustomize-controller  Certificate/ingress/cert-ingress dry-run failed: failed to get API group resources: unable to retrieve the complete list of server APIs: cert-manager.io/v1: the server could not find the requested resource

```
