### DISCUSSION TITLE
Unable to deploy HelmRelease from OCIRegistry

### DISCUSSION THREAD

**Discussion by bogdancosmin** [fluxcd/flux2#4449] [Q&A]
Trying to deploy an HelmRelease from an OCIRepository I get an error when creating the HelmChart that there is no HelmRepository named `strimzi` (and fair enough, strimzi is an OCIRepository). 

So I tried changing the OCIRepository into and HelmRepository, but spec.secretRef isnt supported by HelmRepository 
`HelmRepository/kafka/strimzi dry-run failed: failed to create typed patch o ││ bject (kafka/strimzi; source.toolkit.fluxcd.io/v1beta2, Kind=HelmRepository): .spec.ref: field not declared in schema`

My last try was to define the OCI Repository in the Helm Release but then I ran into this error:

`HelmRelease/kafka/strimzi dry-run failed, reason: Invalid: HelmRelease.helm ││ .toolkit.fluxcd.io "strimzi" is invalid: spec.chart.spec.sourceRef.kind: Unsupported value: "OCIRegistry": supported values: "HelmRepository", "GitReposi ││ tory", "Bucket"`

Trying looking everywhere in the documentation but was unable to find something relevant or useful, is there no way to deploy a helm chart from an oci registry ?

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: strimzi
  namespace: kafka
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: 0.10.0
  url: oci://registry.harbor.io/harbor-charts/harbor-operator
  secretRef:
    name: harbordockercred
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi
  namespace: kafka
spec:
  interval: 1m
  targetNamespace: kafka
  chart:
    spec:
      chart: helm-operator
      version: '0.10.0'
      sourceRef:
        kind: HelmRepository
        name: strimzi
```
