### DISCUSSION TITLE
Is the kustomization force option only supposed to apply patches that fail due to immutable field changes?

### DISCUSSION THREAD

**Discussion by havard024** [fluxcd/flux2#4450] [Q&A] [answered]
We have enabled kustomization force option on all our kustomization manifests.
Last week we experienced an issue were our deployment suddenly disappeared from the cluster.

It happened when there was a syntax error in one of the k8s manifests together with the force option set to true.
We also experienced that flux was unable to recreate the service after fixing the syntax error, unfortunately we were unable to reproduce it.

When we set the force option to false and introduced the syntax error, the deployment / pod did not disappear.

The documentation for `force` option makes it seem likeit should only force apply related to immutable labels https://fluxcd.io/flux/components/kustomize/kustomizations/#force

Steps to reproduce:

1. Create deploy manifests for podinfo
2. Create flux kustomization to deploy manifests from 1 with `force: true`
4. Introduce syntax error, below is our syntax error

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  ... other options ...
  template:
    metadata: # This field was left empty
    spec:
      ... other options ...
```
4. reconcile the changes and the podinfo application gets removed + we receive the following error message

<img width="485" alt="Screenshot 2023-12-04 at 11 56 28" src="https://github.com/fluxcd/flux2/assets/2212037/c567f7fa-b55b-4db5-9595-244a4e0ea440">
