### DISCUSSION TITLE
How should I install a remote Kustomize from a static URL?

### DISCUSSION THREAD

**Discussion by akdor1154** [fluxcd/flux2#4457] [Q&A]
Heya,
I'm pretty new to Flux - I'm trying to install the k8s gateway API definitions. These are installed by a static yaml bundle:
`https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml`

I guess I can set such a bundle as an inline link in a `kustomization.yaml`, however I'd like to use a Flux source instead to take advantage of caching + decoupling from reconciliation interval, trying to follow the general direction to avoid inline remote sources.

Is there any way to do this if the yamls are published as a plain URL, and not in a Git or OCI repo?

Cheers
Jarrad

somewhat related:  #4359

**Comment by kingdonb** [comment]
Hi! plain URLs are not considered versioned sources, even if they are RESTful resources that may contain versioning in their schemes.

You can use inline URLs in kustomize but the use is heavily discouraged, and in the Flux docs we provide hardening instructions that will prevent users from doing this - it's recommended to prevent this because it can circumvent source provenance verification.

> I'd like to use a Flux source instead to take advantage of caching + decoupling from reconciliation interval

Those and the provenance verification are the main advantages of using Flux sources. The only Flux source kinds at present are GitRepository, OCIRepository, Bucket, and HelmRepository (and the associated HelmChart resources that come downstream of any Helm chart source)

I think there is some merit to the idea in #4359, github releases as a versioned source, because they do meet the criteria of a versioned source, but I don't know if it will be prioritized in the Flux roadmap. They do not have the advantages of OCI like cosign verification, keyless authentication workflows, but they could be a lightweight alternative.

Thank you for re-raising this with more detail.

Until the Flux media type is adopted by manifest publishers, there might not be any better option than to copy the manifests into your local repo and keep them versioned locally, either in your own OCI repos that you test and re-publish, or in the bootstrap/config repo copied from upstream (kept updated by a simple Makefile or script.)

The very last choice option is to use an external URL reference, it has numerous disadvantages and it is not recommended for all the reasons you cited. If the Gateway API `standard-install.yaml` is a part of the tree, then you could introduce the cluster-api git repository to the cluster and select the release by tag, and you'd get the caching and other advantages (but not cosign!)

You can select a tag using `spec.semver` with wildcard, if your goal is to get updates into the repo without copying and/or without manual steps. I'd recommend using wildcard patch or minor version only, since major updates will often come with breaking changes.

It's a middle of the road option because there is certainly a lot of other content in the Gateway API repo, and it might not always be part of the tree - it could be only stitched together at release time and only in the release archives.

Flux publishes its own manifests as OCI, signed with cosign keyless workflows (and projects like the Gateway API should too!)

https://github.com/fluxcd/flux2/pkgs/container/flux-manifests

This is the best option because release workflows that stitch things together can provide this as an additional output that can be verified with cosign; do you know if gateway-api git tree contains the standard-install.yaml anywhere, is it composed from here?

https://github.com/kubernetes-sigs/gateway-api/tree/main/config

**Reply by akdor1154** [reply]
Thanks for the detailed response!

Agree on the problems with inline URLs.

While OCI bundles of manifests is starting to see more widespread support, I think it's pushing it a bit to ask other projects to adopt it above and beyond already publishing helm + static yaml. I believe the MIME for a k8syaml bundle is still flux-specific `application/vnd.cncf.flux.content.v1.tar+gzip`, isn't it?

If there was a HTTPSource where I the devops guy could chuck in an optional hash along with a URL, that would get a fair few usecases across the line wouldn't it? While avoiding any github-specific stuff.

For example something like
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HTTP
name: gateway-crds
spec:
  interval: 24h
  url: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml
  # i can get with
  # curl https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml | sha1sum
  expectedSHA1s:
   - da39a3ee5e6b4b0d3255bfef95601890afd80709
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-crds
spec:
  interval: 50m0s
  sourceRef:
    kind: HTTP
    name: gateway-crds
```

this would let people use remote sources in a sane way, while still giving us a way to easily block against untrusted content if we wish, with no extra local tooling or scripting required.

> do you know if gateway-api git tree contains the standard-install.yaml anywhere, is it composed from here?


don't know off the top of my head, i know other k8s sig projects have a helm -> yaml bundle as part of their release workflow though so that's likely the case.

**Comment by stefanprodan** [comment]
For the Gateway API and almost all Kubernetes CRDs you can use the Git as the source. Controllers made with kubebuilder have a crd kustomize overlay.

Here is the Gateway API:

https://github.com/kubernetes-sigs/gateway-api/tree/main/config/crd/standard

**Reply by inistor** [reply]
For anyway interested, based on your advice, I've created and used (successfully):
```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    tag: v1.1.0
  url: https://github.com/kubernetes-sigs/gateway-api
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crd
  namespace: flux-system
spec:
  interval: 1m
  path: ./config/crd/standard
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-api-repo
```

Not sure if the `/config/crd/standard` is stable enough (I mean, they may change their mind at some point with regards to the path), and there's no guarantee that it's identical with the `https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml` URL provided in the standard docs. Nonetheless, it's working for now.

I'm havind a similar issue with [kube-virt](https://github.com/kubevirt/kubevirt) (they are not publishing a helm chart), I'm hoping the same solution will work.
