### DISCUSSION TITLE
Synchronous resource (pods/services) status from Flux

### DISCUSSION THREAD

**Discussion by yuanhe772** [fluxcd/flux2#4458] [Q&A] [answered]
Hi Flux community, 

This is Yuan and our team uses Helm Chart to manage k8s projects, hope you're doing good :) 

### My question:
Opening this Q&A to ask **if there's a way at all - to get to know the pod/service-level deployment status under a Helm Release via Flux**, or, if certain operations in Flux can summarize the completeness of all resources under a Helm Release.

### Local experiments:
I'm playing around with an experimental Traefik project to verify my ask above, by observing the resource status after uninstalling the Traefik helm release and waiting for Flux to automatically reconcile and reinstall the helm release.

The commands being used are `Flux get all -n <namespace>` and `kubectl get helmrelease -n <namespace> <releaseName> -o yaml`, each giving below status:
```
NAME                    REVISION        SUSPENDED       READY   MESSAGE
helmrepository/traefik  sha256:40123d61 False           True    stored artifact: revision 'sha256:40123d61'

NAME                            REVISION        SUSPENDED       READY   MESSAGE
helmchart/traefik-my-traefik    22.0.0          False           True    pulled 'traefik' chart with version '22.0.0'

NAME                    REVISION        SUSPENDED       READY   MESSAGE
helmrelease/my-traefik  22.0.0          False           True    Release reconciliation succeeded
```
```
status:
  conditions:
  - lastTransitionTime: "2023-12-08T06:24:20Z"
    message: Release reconciliation succeeded
    reason: ReconciliationSucceeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-12-08T06:24:20Z"
    message: Helm install succeeded
    reason: InstallSucceeded
    status: "True"
    type: Released
```
However, the `ReconciliationSucceeded` or `InstallSucceeded` didn't seem to match the timestamp when pods/services turned ready (given by a 3rd command `helm status <releaseName> --show-resources -n <namespace>`), I assume this is because reconciliation and installation are asynchronous operations, and thus they don't cover synchronous resource provisioning status.

Kindly lmk if from Flux there's a summarized/consolidated status indicating the synchronous resource creation completeness status, and lmk if needing more clarifications. Any inputs from the community are appreciated, thank you!

Yuan
