### DISCUSSION TITLE
Istio and Flux - observedGeneration

### DISCUSSION THREAD

**Discussion by hrvatskibogmars** [fluxcd/flux2#4508] [General] [answered]
Hello,

I'm currently encountering a type mismatch error when using **Istio** + **Flux**  and would appreciate any guidance or suggestions to resolve it. The issue arises with the status.observedGeneration field, which is expected to be an integer (int64), but it's being interpreted or provided as a string (string). Here's the specific error message I'm receiving:

`Warning  HealthCheckFailed  2m32s (x17 over 83m)  kustomize-controller  (combined from similar events): health check failed after 5m0.055393312s: timeout waiting for: [VirtualService/default/vs-front-imba status: 'Unknown': looking up status.observedGeneration from resource: .status.observedGeneration accessor error: 3 is of the type string, expected int64]`

virtual-service.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-api-imba
  namespace: default
spec:
  gateways:
  - gw-global-lb-portal-imba
  hosts:
  -imba.com
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: api
        port:
          number: 80
```
