### DISCUSSION TITLE
Azure blob storage as private helmrepository

### DISCUSSION THREAD

**Discussion by juhisxd** [fluxcd/flux2#4510] [Q&A]
Im using az storage account and blob inside as a private repo. I have generated SAS token for accessing. How its possible to use with flux?

I have created secret in k8s and secretref in helmrepo yaml

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: platform-helm-charts
  namespace: flux-system
spec:
  interval: 5m
  url: https://<storageaccount-name>.blob.core.windows.net/helm/
  secretRef:
    name: az-sas
```
Error:
403 This request is not authorized to perform this operation.

this is mine repo.yaml

Docs says username and password, but how about with sas token?
