### DISCUSSION TITLE
use a premade helm chart in helm release

### DISCUSSION THREAD

**Discussion by aji-suprana** [fluxcd/flux2#4539] [Q&A]
````
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentication-policy
  namespace: flux-system
  labels:
    releasetype: image-policy
spec:
  interval: 1m
  releaseName: authentication-policy
  chart:
    spec:
      sourceRef:
        kind: HelmChart
        name: vobis-image-policy
  values:
    name: authentication
    namespace: flux-system
    prefix: develop`
    
```
    

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: vobis-image-policy
  namespace: flux-system
spec:
  interval: 5m0s
  reconcileStrategy: Revision 
  chart: ../../_charts/image-policy
  sourceRef:
    kind: GitRepository
    name: flux-system
```

How can i make this work. to use a HelmChart in helm release's .spec.chart.spec
