### DISCUSSION TITLE
Can get fluxcd install podmonitor/serviceMonitor to get scraping from prometheus

### DISCUSSION THREAD

**Discussion by bmillemathias** [fluxcd/flux2#4543] [General]
Hi, 

I installed fluxcd into a brand new cluster using the `bootstrap gitlabl`, then with it I've installed [kube-prometheus-stack](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack) helm and loki. Now I'd like to get fluxcd servicemonitor deployed so I can monitor it.

Quite surprising because https://fluxcd.io/flux/monitoring/metrics/ deals with monitoring but does not mention the steps required to be able to monitor flux.

How can I do ? I did not see `flux install` was able to do that.

Best

**Comment by bmillemathias** [comment]
I eventually created podmonitor (see below) but I would expect fluxcd to be able to install this after prometheus-operator is installed.
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: helm-controller
  namespace: flux-system
  labels:
    app: helm-controller
spec:
  selector:
    matchLabels:
      app: helm-controller
  podMetricsEndpoints:
    - port: http-prom
```
