### DISCUSSION TITLE
How to manage remote GKE clusters using Workload Identity?

### DISCUSSION THREAD

**Discussion by 2hamed** [fluxcd/flux2#4548] [Q&A] [answered]
Hi,

What I want to do is, to use a single instance of FluxV2 to manage workloads on multiple remote clusters. We managed to do this before by manually creating user tokens on the remote clusters and putting them inside the `kubeconfig` manifest for those in the central Flux.

Now what I want to do is basically the same, but instead of static tokens I want to use [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity).

I have created the necessary SA bindings and have also added the necessary annotation on the `helm-controller` and `kustomize-controller` KSAs.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: kustomize-controller
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v2.2.2
  annotations:
    iam.gke.io/gcp-service-account: "my-sa@my-pj.iam.gserviceaccount.com"
  name: kustomize-controller
  namespace: flux-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: helm-controller
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v2.2.2
  annotations:
    iam.gke.io/gcp-service-account: "my-sa@my-pj.iam.gserviceaccount.com"
  name: helm-controller
  namespace: flux-system
```

Now this is how a kubeconfig manifest generally looks like:

```
apiVersion: v1
kind: Config
clusters:
- name: ${cluster_name}
  cluster:
    certificate-authority-data: ${ca}
    server: ${server}
contexts:
- name: default
  context:
    cluster: ${cluster_name}
    namespace: default
    user: flux
current-context: default
users:
- name: flux
  user:
    token: ${token}
```

I wonder if there is a way to make Flux controllers authenticate via the serviceAccount token instead of this `user` mentioned in the kubeconfig?
