### DISCUSSION TITLE
What does 'validation: client' in a kustomization mean?

### DISCUSSION THREAD

**Discussion by xeruf** [fluxcd/flux2#4572] [Q&A]
I see this property mentioned all over the place but could not find any explanation to it in the docs or anywhere else

**Comment by stefanprodan** [comment]
I doubt there is any mention of this field in latest docs, this opinion was removed some years ago from Flux APIs. Flux now uses Kubernetes server-side apply, which means manifests are always validated by the Kubernetes OpenAPI before being being persisted in etcd.

**Reply by mkadricogito** [reply]
@stefanprodan I recently encountered an issue when trying to update from 0.41.2 to v2.0.0-rc.1

```
Warning  ReconciliationFailed     5m5s (x2 over 5m15s)  kustomize-controller  Kustomization/flux-system/cert-manager dry-run failed, error: failed to p │
│ rune fields: failed add back owned items: failed to convert merged object at version kustomize.toolkit.fluxcd.io/v1: .spec.validation: field not declared │
│  in schema
```


it turns out that our existing kustomization has this flag set to 
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1m0s
  path: ./kustomize
  prune: false
  sourceRef:
    kind: GitRepository
    name: podinfo
    namespace: flux-system
  targetNamespace: default
  validation: client
```

i.e it breaks the flux-system kustomization, so its not reverse compatible I see, 
any way to overcome or get around it
