### DISCUSSION TITLE
Helm release error debugging

### DISCUSSION THREAD

**Discussion by SamarSidharth** [fluxcd/flux2#4581] [General]
I am trying to deploy [free5gc chart](https://github.com/Orange-OpenSource/towards5gs-helm/tree/main/charts/free5gc) which contains subcharts. It works fine when I deploy it manually using `helm install` but when I tried it with flux helm release I get below errors. I have attached my flux helm CR yamls below. I am not overriding any values with helmRelease so the valuesFrom field is marked optional.

```shell
Events:
  Type     Reason            Age                From             Message
  ----     ------            ----               ----             -------
  Normal   HelmChartCreated  42s                helm-controller  Created HelmChart/free5gc/free5gc-free5gc-demo with SourceRef 'HelmRepository/free5gc/free5gc-demo'
  Warning  InstallFailed     13s (x6 over 39s)  helm-controller  Helm install failed for release free5gc/free5gc-free5gc-demo with chart free5gc@1.1.7: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 63: mapping key "ports" already defined at line 61

{"level":"error","ts":"2024-01-31T10:33:58.770Z","msg":"Reconciler error","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":{"name":"free5gc-demo","namespace":"free5gc"},"namespace":"free5gc","name":"free5gc-demo","reconcileID":"78c50dea-a3da-4e9b-a1a8-d42c627d8b72","error":"error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:\n  line 63: mapping key \"ports\" already defined at line 61","errorVerbose":"map[string]interface {}(nil): yaml: unmarshal errors:\n  line 63: mapping key \"ports\" already defined at line 61\nerror while running post render on files\nhelm.sh/helm/v3/pkg/action.(*Configuration).renderResources\n\thelm.sh/helm/v3@v3.13.3/pkg/action/action.go:224\nhelm.sh/helm/v3/pkg/action.(*Install).RunWithContext\n\thelm.sh/helm/v3@v3.13.3/pkg/action/install.go:304\ngithub.com/fluxcd/helm-controller/internal/action.Install\n\tgithub.com/fluxcd/helm-controller/internal/action/install.go:62\ngithub.com/fluxcd/helm-controller/internal/reconcile.(*Install).Reconcile\n\tgithub.com/fluxcd/helm-controller/internal/reconcile/install.go:92\ngithub.com/fluxcd/helm-controller/internal/reconcile.(*AtomicRelease).Reconcile\n\tgithub.com/fluxcd/helm-controller/internal/reconcile/atomic_release.go:252\ngithub.com/fluxcd/helm-controller/internal/controller.(*HelmReleaseReconciler).reconcileRelease\n\tgithub.com/fluxcd/helm-controller/internal/controller/helmrelease_controller.go:359\ngithub.com/fluxcd/helm-controller/internal/controller.(*HelmReleaseReconciler).Reconcile\n\tgithub.com/fluxcd/helm-controller/internal/controller/helmrelease_controller.go:220\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227\nruntime.goexit\n\truntime/asm_amd64.s:1598"}
```

helmrepository yaml
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata: # kpt-merge: to-be-changed/to-be-changed
  name: free5gc-demo
  namespace: free5gc
  annotations:
    internal.kpt.dev/upstream-identifier: 'source.toolkit.fluxcd.io|HelmRepository|to-be-changed|to-be-changed'
spec:
  interval: 1m0s
  url: https://raw.githubusercontent.com/Orange-OpenSource/towards5gs-helm/main/repo/ #path-to-helm-repository
```

helmrelease yaml

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: # kpt-merge: to-be-changed/to-be-changed
  name: free5gc-demo
  namespace: free5gc
  annotations:
    internal.kpt.dev/upstream-identifier: 'helm.toolkit.fluxcd.io|HelmRelease|to-be-changed|to-be-changed'
spec:
  chart:
    spec:
      chart: free5gc
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: free5gc-demo
        namespace: free5gc
      version: 1.1.7 #0.2.6
  kubeConfig:
    secretRef:
      name: target-cluster #kubeconfig-of-target-cluster
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 1
  interval: 5m
  storageNamespace: free5gc
  targetNamespace: free5gc
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 1
  valuesFrom:
  - kind: ConfigMap
    name: values-overrides
    valuesKey: values.yaml
    optional: true
```
