### DISCUSSION TITLE
Bootstrap flux with ignore option

### DISCUSSION THREAD

**Discussion by Angel0r** [fluxcd/flux2#4590] [Q&A] [answered]
Hey!

We are using flux in production and I recently uninstalled flux accidentally. When I tried to bootstrap it again I couldn't, since flux was throwing an error of an incorrect YAML file in the repo. This YAML file is a pre-commit-config.yaml file which contains configuration. 

To solve this initially(before uninstall) I just ignored the file after the initial bootstrap and everything was fine.
The gotk looks like that:
```yaml
# This manifest was generated by flux. DO NOT EDIT.
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: ssh://user@git.com:/kubernetes/flux-fleet
  ignore: |
    # exclude pre-commit configuration
    .pre-commit-config.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  # Perform health checks, hence it will send notifications via the notification controller
  wait: true
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```
The problem is that after uninstalling and bootstrapping again, FLux is creating new manifests that don't have the **ignore** option.
It says "DO NOT EDIT" I know :) but what are the best practices for that?
Can I use the ignore option in the bootstrap command?
Or should just change the path so flux can check only the needed YAML?

/Angelos
