### DISCUSSION TITLE
alert-provider cannot receive notifications

### DISCUSSION THREAD

**Discussion by ForcemCS** [fluxcd/flux2#4624] [Q&A]
I am trying to use Notification Controller and I have created the following resource,But when I update the code in the deployment repository (e.g. change the image version), I don't get any message from my Wechat, how can I troubleshoot this issue
````yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: weixin-provider
  namespace: flux-system
spec:
  type: generic
  address: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=2028207c-300e-4154-bfacxxxxxxxxxxxxxxxxxxxxx
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: weixin-notification
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
  - kind: Kustomization
    name: '*'
  - kind: GitRepository
    name: '*'
  - kind: HelmRepository
    name: '*'
  providerRef:
    name: weixin-provider
````
