### DISCUSSION TITLE
How do I remove cpu limit from flux controllers?

### DISCUSSION THREAD

**Discussion by vbezhenar** [fluxcd/flux2#4644] [Q&A] [answered]
I want to adjust resources used by flux controllers and for cpu limit I want to remove it.

Here's approach I've taken:

`clusters/main/flux-system/kustomization.yaml`:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - ing-webhook-receiver.yaml
  - receiver-flux-system.yaml
patches:
  - path: helm-controller-patch.yaml
  - path: image-automation-controller-patch.yaml
  - path: image-reflector-controller-patch.yaml
  - path: kustomize-controller-patch.yaml
  - path: notification-controller-patch.yaml
  - path: source-controller-patch.yaml
```

`clusters/main/flux-system/helm-controller-patch.yaml`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          resources:
            limits:
              cpu: null
              memory: 176Mi
            requests:
              cpu: 66m
              memory: 117Mi
```

Other patches are similar.

With this setup, I'm getting this output from `kubectl kustomize .`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: helm-controller
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v2.2.3
    control-plane: controller
  name: helm-controller
  namespace: flux-system
spec:
...
        resources:
          limits:
            memory: 176Mi
          requests:
            cpu: 66m
            memory: 117Mi
...
```

So it seems that I did the right thing: kustomize produces manifest without CPU limit set.

However when applying this patch to the cluster (using flux, of course), the cpu limit stays here (other resources are adjusted):

`kubectl get deployments.apps helm-controller -o yaml`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2024-03-03T10:41:57Z"
  generation: 3
  labels:
    app.kubernetes.io/component: helm-controller
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v2.2.3
    control-plane: controller
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: helm-controller
  namespace: flux-system
...
spec:
...
        resources:
          limits:
            cpu: "1"
            memory: 176Mi
          requests:
            cpu: 66m
            memory: 117Mi
...
```

So it seems that flux does not remove field `resources.limits.cpu` despite the fact that it's not present in the patched manifest. This is surprising to me, as I thought that flux will replace deployment with the new manifest.

I tried to specify `cpu: ""`, but it didn't pass kubernetes validation.

Of course I could specify some huge value, but I'd prefer to keep consistent approach with all my deployments in the cluster.

**Comment by vbezhenar** [comment, marked as answer]
I fixed it using RFC6902 patch:

`kustomization.yaml`:

```yaml
...
patches:
  - path: helm-controller-patch6902.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: helm-controller
...
```

`helm-controller-patch6902.yaml`:

```
- op: test
  path: /metadata/name
  value: helm-controller
- op: test
  path: /spec/template/spec/containers/0/name
  value: manager
- op: replace
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      memory: 196Mi
    requests:
      cpu: 66m
      memory: 131Mi
```

I still don't understand why my original approach didn't work, because `kubectl kustomize` output was the same, feels like a bug somewhere...
