### DISCUSSION TITLE
Could not determine release state

### DISCUSSION THREAD

**Discussion by loxy** [fluxcd/flux2#4658] [Q&A]
Hi!

I'm mainly trying to run a Prometheus stack via the example from [here](https://github.com/fluxcd/flux2-monitoring-example/tree/main/monitoring) without any changes.

When I run it, the release is always not ready. It shows this error:

```sh
flux get helmreleases --all-namespaces

monitoring	kube-prometheus-stack	        	False    	False            Could not determine release state: unable to determine cluster state: [Prometheus/monitoring/kube-prometheus-stack-prometheus dry-run failed: failed to create typed patch object (monitoring/kube-prometheus-stack-prometheus; monitoring.coreos.com/v1, Kind=Prometheus): .spec.scrapeConfigNamespaceSelector: field not declared in schema, ServiceMonitor/monitoring/kube-prometheus-stack-prometheus-node-exporter dry-run failed: failed to create typed patch object (monitoring/kube-prometheus-stack-prometheus-node-exporter; monitoring.coreos.com/v1, Kind=ServiceMonitor): .spec.attachMetadata: field not declared in schema, ServiceMonitor/monitoring/kube-prometheus-stack-kubelet dry-run failed: failed to create typed patch object (monitoring/kube-prometheus-stack-kubelet; monitoring.coreos.com/v1, Kind=ServiceMonitor): .spec.attachMetadata: field not declared in schema]
```

When I look at the cluster it seams that all pods are created and running succesfully. I can for example log into Grafana.

Anyone a hint? I followed the debug steps here: https://fluxcd.io/flux/cheatsheets/troubleshooting/#how-to-debug-not-ready-errors, but all is OK. I'm running on K3s.

Can it be the case, that it has something to do with: https://github.com/fluxcd/flux2-monitoring-example/issues/29

Best regards,
Kersten

**Comment by gberche-orange** [comment]
We ran into a similar issue where the prometheus CRDs were invalid because of a race condition with loki helm chart also updating them with an older content, see https://github.com/grafana/loki/issues/7488

We yet have to test the following workaround: use Flux helm post rendered with kustomize special syntax to delete each *.monitoring.coreos.com CRD from loki rendered helm output

https://github.com/kubernetes-sigs/kustomize/issues/1593#issuecomment-1190801833
```yaml
patches:
  - target:
      kind: CustomResourceDefinition
      name: servicemonitors.monitoring.coreos.com
    patch: |
      $patch: delete
      apiVersion: route.openshift.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: DOES NOT MATTER
```
