### DISCUSSION TITLE
Failed to apply default image tag when trying to use kustomize image transformer and image policy

### DISCUSSION THREAD

**Discussion by mudux** [fluxcd/flux2#4661] [Q&A] [answered]
Hello everyone

I have a layered application and am using customize to apply different images per namespace

but when using kustomize image transformer as follows:

```
images:
  - name: image_placeholder
    newName: ########.dkr.ecr.us-west-1.amazonaws.com/image-testing
    newTag: 0.0.1 # { "$imagepolicy" : "flux-system:testing-image-policy"}
```
The entire line after # gets omitted.

I wasnt able to get any where with the current documentation.

How else can I incorporate usage of kustomize image transformer and also enable image policy per namespace?

Thank you.
