### DISCUSSION TITLE
Deploying HelmRelease with sourceRef of GitRepository (private) fails

### DISCUSSION THREAD

**Discussion by naegleria** [fluxcd/flux2#4665] [Q&A]
Hi,
I have a setup where each application has their own Git repo (app1, app2, etc.), their own custom Helm chart and their own HelmRelease plus any additional .yaml files (wrapped by a kustomization.yaml) for the app and infrastructure separately (similarly to [https://github.com/fluxcd/flux2-kustomize-helm-example/tree/main](url))
There is a separate repository called fluxcd, where I have bootstrapped K8s clusters, for example test cluster is bootstrapped to clusters/test and prod cluster to clusters/production. This is the general structure of the fluxcd repo:
```
.
├── clusters
│   ├── test
│   │   └── app1
│   │       ├── apps.yaml
│   │       ├── gitrepository.yaml
│   │       └── infrastructure.yaml
│   │   └── app2
│   │       ├── apps.yaml
│   │       ├── gitrepository.yaml
│   │       └── infrastructure.yaml
│   │   └── flux-system
│   │       ├── <files created during flux-bootstrap>
│   │   └── helm-repos
│   │       ├── bitnami-repo.yaml
│   │       ├── <some other repos>
│   └── production
│   │   └── app1
│   │       ├── apps.yaml
│   │       ├── gitrepository.yaml
│   │       └── infrastructure.yaml
│   │   └── flux-system
│   │       ├── <files created during flux-bootstrap>
│   │   └── <same thing as with test>
```

apps.yaml and infrastructure.yaml files are Kustomization files that reference their respective kustomization.yaml files inside the app repos. The HelmRelease yamls for infrastructure use the helm repositories defined in fluxcd project and as they are public repos, the infrastructure HelmRelease deployment works without issues, and the helm charts + other yamls get deployed as they should.

The setup for app deployment is as follows:
In app1 repo I have .helm/app1 directory containing Chart.yaml, values.yaml and templates, aka a normal helm chart structure.
In app1 repo I also have .kubernetes/apps/app1 directory containing a helmrelease.yaml and kustomization.yaml:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: app1
  namespace: app1
spec:
  interval: 8h
  releaseName: app1
  chart:
    spec:
      chart: ./helm/app1
      version: 0.*.*
      interval: 12h
      sourceRef:
        kind: GitRepository
        name: app1-repo
        namespace: flux-system
      valuesFiles:
        - ./helm/app1/values.yaml
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
```
(According to documentation, version: parameter is ignored for GitRepository sourceRef, but I added it anyway, hope that didn't cause the issue.)
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
```
The referenced git repo is the gitrepository.yaml file defined in fluxcd repo in .clusters/test/app1:
```
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app1-repo
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://gitlab.server.url/app1/app1
  secretRef:
    name: app1-repo-deploy-token
  ignore: |
    /*
    !/kubernetes/
    !/helm/
```
So the source-controller authenticates with the app1 repo using the deploy token with read repo and registry rights.
And finally the apps.yaml file in fluxcd repo that is supposed to actually deploy the HelmRelease to K8s:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app1
  namespace: flux-system
spec:
  dependsOn:
    - name: app1-mysql
  interval: 10m
  targetNamespace: app1
  sourceRef:
    kind: GitRepository
    name: app1-repo
  path: "./kubernetes/apps/app1"
  prune: true
  patches:
    - patch: | ...//...
```
The error message I am getting:
`2024-03-13T10:54:07.596Z error Kustomization/flux-system.flux-system - Reconciliation failed after 576.420153ms, next try in 10m0s HelmRelease/app1/app1 dry-run failed (Invalid): HelmRelease.helm.toolkit.fluxcd.io "app1" is invalid: [spec.chart: Required value, spec.interval: Required value]`

Now my assumption was that the app1 HelmRelease should be able to fetch the chart from the Git repo, as the reconciliation is done inside flux-system namespace, which can read app1 repo via the deploy token secret. Or is it necessary to define another gitrepository.yaml towards the same app1 repo just to be used for helm chart fetching, but with different parameters? Or maybe the issue is something else entirely, it's hard to tell as the error says it requires spec.chart and spec.interval values, which are defined.

Any help would be appreciated.
