### DISCUSSION TITLE
using a vendor helm chart with flux

### DISCUSSION THREAD

**Discussion by bashfulrobot** [fluxcd/flux2#4672] [General] [answered]
Hi there. In the sample docs, tutorials, etc, there are plenty of examples using a helm chart in a git repo. 

When using a vendor helm repo that is something like:

```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-nginx bitnami/nginx
```

which URL would I use in the below code?

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: my-nginx
  namespace: nginx
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami/???????
```

Would it literally be something like:

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: my-nginx
  namespace: nginx
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami/nginx
```

Or some other value I can grab from the `index.yaml` in the repo?

Thank you.

**Comment by stefanprodan** [comment, marked as answer]
Please note that Bitnami moved to Docker Hub and you should be using an `oci://` URL.

For an OCI repo it would be:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: nginx
spec:
  interval: 12h
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts # registry URL without the chart name
```

For a HTTP repo it would be:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: nginx
spec:
  interval: 50m
  url: https://charts.bitnami.com/bitnami # same URL as for "helm repo add"
```

The helm release:

`helm install my-nginx bitnami/nginx`

Translates to:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: my-nginx
  namespace: nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: nginx # no alias, just the chart name
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 12h
```

Docs:
- https://fluxcd.io/flux/components/source/helmrepositories/
- https://fluxcd.io/flux/components/helm/helmreleases/
