### DISCUSSION TITLE
How we can add metadata/finalizers field to the resource?

### DISCUSSION THREAD

**Discussion by prog76** [fluxcd/flux2#4683] [Q&A]
I want to do this as a protection from accidental delete of the resource or whole namespace with this resource no matter how. in the repo or with kubectl. 
So it will require manual action (remove finalizer) to really delete resources.
tried:
1 single **volume.yaml**:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-0
  namespace: test-volume
  finalizers:
  - kubernetes
...
```
**result**: volume-0 has only default finalizers value [kubernetes.io/pvc-protection]
2. **volume.yaml** + **kustomization.yaml**
**volume.yaml**:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-0
...
```
**kustomization.yaml**:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-volume
resources:
- volume.yaml
patches:
- patch: |
    - op: add
      path: /metadata/finalizers
      value:
      - kubernetes
  target:
    kind: PersistentVolumeClaim
    name: volume-0
    namespace: test-volume
```
**result**: works as expected and volume-0 has two finalizers: [kubernetes, kubernetes.io/pvc-protection]
But I already have resources that I want to change this way, so trying further steps.
3. first commit **volume.yaml**, second commit **kustomization.yaml**

**result**: doesn't work. volume-0 has only default finalizer.

also tried to change the patch to _replace_:
```
- patch: |
    - op: replace
      path: /metadata/finalizers
      value:
      - kubernetes
      - kubernetes.io/pvc-protection
```
doesn't help
