### DISCUSSION TITLE
How do I use helm charts in helm releases that don't follow best practices for helm chart naming conventions and contain dots

### DISCUSSION THREAD

**Discussion by gc-jro** [fluxcd/flux2#4684] [Q&A] [answered]
Hello,

I would like to deploy a helm chart with flux using attached helm repository and helm release custom resources.
Unfortunately, the vendor of the helm chart doesn't follow best practices regarding helm chart naming conventions. [1]
The helm chart provided contains a dot (`cognigy.ai`). [2]

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cognigy
  namespace: cognigy
spec:
  type: oci
  interval: 5m0s
  url: oci://cognigy.azurecr.io/helm
  secretRef:
    name: xxx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cognigy
  namespace: cognigy
spec:
  values:
    ...
  chart:
    spec:
      chart: cognigy.ai
      sourceRef:
        kind: HelmRepository
        name: cognigy
        namespace: cognigy
      version: "4.71.2"
  interval: 5m0s
  timeout: 15m0s
  releaseName: cognigy.ai
```

Once I deploy both helm release and helm repository crs, the flux helm controller is complaining that the helm chart must not contain said dot.
```
jens@[k8s-cluster]:~$ kubectl get helmrelease,helmchart
NAME                                         AGE   READY   STATUS
helmrelease.helm.toolkit.fluxcd.io/cognigy   63m   False   HelmChart 'cognigy/cognigy-cognigy' is not ready: invalid chart reference: invalid chart name 'cognigy.ai': a valid name must be lower case letters and numbers and MAY be separated with dashes (-) or slashes (/)

NAME                                                 CHART        VERSION   SOURCE KIND      SOURCE NAME   AGE   READY   STATUS
helmchart.source.toolkit.fluxcd.io/cognigy-cognigy   cognigy.ai   4.71.2    HelmRepository   cognigy       63m   False   invalid chart reference: invalid chart name 'cognigy.ai': a valid name must be lower case letters and numbers and MAY be separated with dashes (-) or slashes (/)
```

Is there a feature toggle or other workaround for the helm chart controller that allows me to deploy helm charts that don't follow the best practices regarding helm chart naming conventions?

If you need any further information, please do not hesitate to contact me.

Best regards

Jens.

[1] https://v2-14-0.helm.sh/docs/chart_best_practices/#:~:text=Dots%20should%20not%20be%20used,of%20the%20Helm%20Chart%20format.
[2] https://github.com/Cognigy/cognigy-ai-helm-chart
