### DISCUSSION TITLE
Helm drift detection on configmap patching '*** (after)' instead of the actual template from the helm chart

### DISCUSSION THREAD

**Discussion by soumyabk** [fluxcd/flux2#4693] [Q&A]
we're running helmcontroller version v0.37.2 and enabled drift detection. Noticing that if any manual change was added to one of the configmaps of our helm chart, the helm controller detects a drifts and patches with a string and not the actual config map from the helm template. 
```
{"level":"debug","ts":"2024-03-26T00:16:19.027Z","msg":"resource modified","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":{"name":"<resource_name>","namespace":"flux-system"},"namespace":"flux-system","name":"<servicename>","reconcileID":"94f4e548-7273-44b3-a316-859516ec5dbe","resource":"ConfigMap/flux-system/<service>-config","patch":[{"value":"*** (after)","op":"replace","path":"/data/config.yaml"}]}
```
Config map after reconcile:
```
apiVersion: v1
data:
  config.yaml: '*** (after)'
kind: ConfigMap
metadata:
********
``` 
configmap template sample:
```
apiVersion: v1
data:
  config.yaml: |
    slaPeriod: 12h   # if this is manually updated to 6h, then drift detection runs
metadata:
********
```
