### DISCUSSION TITLE
Use automated image updates to always run the very latest image available

### DISCUSSION THREAD

**Discussion by arkadyb** [fluxcd/flux2#4724] [General]
I am trying to follow https://fluxcd.io/flux/guides/image-update/ to keep the pod running the latest image available. 
The image policy file content i use is:
```
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: the-project
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: the-project
  policy:
    semver:
      range: '*'
```

Now, whenever i push a new image to the repo, i get the `image-reflector` to sync and find a new image is there:
```
  Normal   Succeeded            3m46s                image-reflector-controller  successful scan: found 30 tags
  Normal   Succeeded            2m46s                image-reflector-controller  successful scan: found 31 tags
```

however, the reflector can not find the right version to spin 
```
Warning  Failure  2m24s (x151 over 60m)  image-reflector-controller  unable to determine latest version from provided list
```
Is there some way to configure this? Or alternatively, is there a way to always pull the `latest` version instead?

P.S.: 
why would i need to configure the image updates as part of https://fluxcd.io/flux/guides/image-update/#configure-image-updates ?
