### DISCUSSION TITLE
Can't get Flux GitHub auth working with CDK EKS Blueprints

### DISCUSSION THREAD

**Discussion by JamesMcMahon** [fluxcd/flux2#4741] [Q&A] [answered]
Hey Folks,

Trying to get Flux working using [CDK and an add-on for the EKS blueprints](https://aws-quickstart.github.io/cdk-eks-blueprints/addons/fluxcd/). I can not get auth to work at all and keep getting:

> GitRepository/redacted	failed to checkout and determine revision: unable to clone 'https://github.com/redacted': authorization failed

A lot of the Flux docs are centered around `flux bootstrap` but I can't use that since I am using CDK to manage my cluster setup. The documentation for it the add-on suggests using a bearer token, but doing some [research it seems like you can't clone unless you basic access auth](https://github.com/fluxcd/flux2/issues/3668). So I switched over, but still no luck.

Secret resource for reference:

```yaml
apiVersion: v1
data:
  password: <redacted>
  username: <redacted>
immutable: false
kind: Secret
metadata:
  name: flux-github-credentials
  namespace: flux-system
  <trimming out runtime annotations etc>
type: Opaque
```

The repository and source controller hasn't given me more than the message above. Any suggestions for debugging further?
