### DISCUSSION TITLE
notification controller doesn't send alert when kustomize-controller meets reconciliation fail event of HelmRelease dry-run failed

### DISCUSSION THREAD

**Discussion by purehigh** [fluxcd/flux2#4776] [Q&A]
Hi, 
notification controller doesn't send alert when kustomize-controller meets reconciliation fail event of HelmRelease dry-run failed.

Is there a way to alert as well?
(other alerts are fine)

```
$ flux version
flux: v2.0.0
helm-controller: v0.37.2
image-automation-controller: v0.37.0
image-reflector-controller: v0.31.1
kustomize-controller: v1.2.1
notification-controller: v1.2.3
source-controller: v1.2.3
```
#### kustomize-controller's log
```json
{"level":"error","ts":"2024-05-10T02:04:17.796Z","msg":"Reconciliation failed after 119.212687ms, next try in 1m0s","controller":"kustomization","controllerGroup":"kustomize.toolkit.fluxcd.io","controllerKind":"Kustomization","Kustomization":{"name":"application-ocu-preview","namespace":"flux-system"},"namespace":"flux-system","name":"application-ocu-preview","reconcileID":"ddaeac73-8292-45f5-915e-4b03629eb1c1","revision":"main@sha1:5eecc3dbe67a7e1ef83878f029762f93a3a045e7","error":"HelmRelease/ocu/ocu-report-api-fix-Flux-Reconcilication-Alert2 dry-run failed (Invalid): HelmRelease.helm.toolkit.fluxcd.io \"ocu-report-api-fix-Flux-Reconcilication-Alert2\" is invalid: metadata.name: Invalid value: \"ocu-report-api-fix-Flux-Reconcilication-Alert2\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')\n"}
```
#### notification-controller's log
```json
{"level":"info","ts":"2024-05-10T02:10:18.680Z","logger":"event-server","msg":"discarding event, no alerts found for the involved object","eventInvolvedObject":{"kind":"Kustomization","namespace":"flux-system","name":"application-ocu-preview","uid":"7d2cc159-9809-4594-b4d6-4950ccca573a","apiVersion":"kustomize.toolkit.fluxcd.io/v1","resourceVersion":"156918550"}}
```
```
$ kubectl get kustomizations -n flux-system application-ocu-preview
NAME                      AGE    READY   STATUS
application-ocu-preview   245d   False   HelmRelease/ocu/ocu-report-api-fix-Flux-Reconcilication-Alert2 dry-run failed (Invalid): HelmRelease.helm.toolkit.fluxcd.io "ocu-report-api-fix-Flux-Reconcilication-Alert2" is invalid: metadata.name: Invalid value: "ocu-report-api-fix-Flux-Reconcilication-Alert2": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')...
```
#### crd
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  type: slack
  channel: grasse-fluxcd
  secretRef:
    name: slack-url
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: on-call-webapp
  namespace: flux-system
spec:
  summary: ''
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRepository
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: HelmChart
      name: '*'
  exclusionList:
    - "configured"
    - "test"
```
