### DISCUSSION TITLE
Is it possible to download a Github release using a flux kustomization?

### DISCUSSION THREAD

**Discussion by jcheroske** [fluxcd/flux2#4802] [Q&A]
I'd like to download an asset that's located at a Github release URL:
```
https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.crds.yaml
```
Is there a way to have this file processed using a Flux Kustomization? I've tried the following:
```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: master
  url: https://github.com/cert-manager/cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-crds
  namespace: cert-manager
spec:
  interval: 5m
  path: /releases/download/v1.14.5/cert-manager.crds.yaml
  prune: true
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: cert-manager
    namespace: flux-system
  timeout: 30s
```
This does not work. Is there a way to access manifests located under the `/releases` folder? Thanks.
