### DISCUSSION TITLE
struggles trying to switch helmRelease persistent storage

### DISCUSSION THREAD

**Discussion by dallinbeutler** [fluxcd/flux2#4803] [Q&A]
I'm using flux provisioned through eksctl. 
I can't seem to get HelmRelease to to provision PVCs based on my existing PVs that are in EBS specified in their own yamls:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: default-storage
    # annotations:
    #   storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nats
  namespace: nats
spec:
  storageClassName: default-storage
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-00ae68dc871722ca4
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.ebs.csi.aws.com/zone
              operator: In
              values:
                - us-west-2

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: nats
    namespace: nats
spec:
    spec:
      chart: nats
      version: 1.1.x
      sourceRef:
          kind: HelmRepository
          name: nats
          namespace: nats
      interval: 12h
    
  values:
    config:
      jetstream:
        enabled: true
        memoryStore:
          enabled: true
          pvc:
            enabled: true
            size: 256Mi
      nats:
        port: 4222
      websocket:
        enabled: true
        port: 9222
  postRenderers:
    # Instruct helm-controller to use built-in "kustomize" post renderer.
    - kustomize:
        # Array of inline strategic merge patch definitions as YAML object.
        # Note, this is a YAML object and not a string, to avoid syntax
        # indention errors.
        patchesStrategicMerge:
        - kind: PersistentVolumeClaim
          apiVersion: v1
          metadata:
            labels: 
              - app.kubernetes.io/name=nats
          spec:
            template:
              spec:
                - kind: PersistentVolumeClaim
                  storageClassName: default-storage
                  volumeName: nats


```
The patch doesn't seem to apply anything.

I tried a fuzzy regex of `.*nats.*` on the `metadata.name` patch instead of label but that didn't work either. am I missing something? 

I used advice in #2744 for reference

All I really want is to spin up a cluster using the volumes I already  dynamically created/modified last time i spun up flux.  Is there an easier way perhaps?

Really appreciate the help, I've been banging my head on this!

**Comment by dallinbeutler** [comment]
update: also tried version `v2beta2` and the following postRenderer:
```yaml
  postRenderers:
    # Instruct helm-controller to use built-in "kustomize" post renderer.
    - kustomize:
        # Array of inline strategic merge patch definitions as YAML object.
        # Note, this is a YAML object and not a string, to avoid syntax
        # indention errors.
        patches:
        - target:
            kind: PersistentVolumeClaim
            version: v1
            name: nats
          patch: |-
            - op: add
              path: "/storageClassName"
              value: default-storage
        - target:
            kind: PersistentVolumeClaim
            version: v1
            name: nats
          patch: |-
            - op: add
              path: "/volumeName"
              value: nats
```

**Reply by souleb** [reply]
The path is wrong. There is a nice example here on how to define it: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/jsonpatch.md

**Reply by dallinbeutler** [reply]
thank you, that is a good resource! 
```yaml
    - kustomize:
        patches:
        - target:
            kind: PersistentVolumeClaim
            version: v1
            name: nats.*
          patch: |-
            - op: add
              path: "/spec/storageClassName"
              value: default-storage
        - target:
            kind: PersistentVolumeClaim
            version: v1
            name: nats.*
          patch: |-
            - op: add
              path: "spec/volumeName"
              value: nats
```
although, based on the 
`helm install my-nats nats/nats --version 1.1.11 --dry-run` results, there's no outputted PVC to adjust.  but they get auto-generated from either a Deployment or a StatefulSet? 
Is there no simple place to insert extra info for the PVCs? 
Or am I looking at a bad reference for what kustomize is working on? 

Either way, I guess that puts it outside the scope of  flux and the  HelmRelease spec...
