### DISCUSSION TITLE
Add suspension status of resource to printed columns

### DISCUSSION THREAD

**Discussion by marevers** [fluxcd/flux2#4817] [Proposals]
Currently, when executing for instance a `kubectl get kustomizations.kustomize.toolkit.fluxcd.io` three additional printer columns are added. Age, Ready and Status.

I would propose to add a column 'Suspended' to any resource that can be suspended, like so (example is from Kustomization):

```yaml
...
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
        - name: Suspended
          type: boolean
          jsonPath: .spec.suspend
        - name: Status
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].message
...
```

Seeing as `spec.suspend` is not always present the column will show empty if it is not suspended but this is just for discussion purposes.

I mainly see three advantages:
1. kubectl output would be more helpful to determine the state
2. One could retrieve just suspended resources from the output of the command(s)
3. K8s IDEs like Lens will show the suspension status as it picks up these columns
