### DISCUSSION TITLE
Helm release retry without rollback/uninstall

### DISCUSSION THREAD

**Discussion by soumyabk** [fluxcd/flux2#4820] [Q&A]
Is it possible to have a retry configuration for the helmreleases to just query the status of the resources without performing a rollback/uninstall. It could be an additional parameter under the install configuration. 
```
  install:
    remediation:
      strategy: <maybe support None> # currently only rollback/uninstall
      retries: 3
```
We have use-cases where our service pods might take longer than the timeout duration, but we cannot afford a rollback and retry - have some control plane services deployed using flux. The helmreleases get stuck in "Helm install failed", and usually a `flux suspend hr <name>` and `flux resume hr <name>` gets the helm release to succeed.

**Comment by soumyabk** [comment]
@stefanprodan is this something that is on the roadmap or some way to do this currently?

**Reply by stefanprodan** [reply]
Setting `retries: -1` and `remediateLastFailure: false` will do just that.

**Reply by soumyabk** [reply]
@stefanprodan I tested this and that's not the case, it does try to rollback. This is the configuration I added to the helmrelease spec and I ensured it would fail by cordoning the nodes the pods would try to launch on.
```
 install:
    remediation:
      remediateLastFailure: false
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: false
      retries: -1
```
and here is my failing helmrelease(it was previously running version 0.0.13 and upgraded to 0.0.14 - it fails and tries to rollback)
```
kubectl -n flux-system get hr <service_name>
NAME                        AGE   READY   STATUS
<service_name>   69d   False   Helm rollback to previous release flux-system/<service_name>.v2 with chart <service_name>@0.0.13 succeeded
```
I was looking for an option where if it fails, it doesn't do anything(no revert/uninstall) and just retries the same during the next reconcile interval.
