### DISCUSSION TITLE
HelmChart generating differently than expected

### DISCUSSION THREAD

**Discussion by conorlawton** [fluxcd/flux2#4829] [Q&A]
Hi there, exploring flux, enjoying working with it thus far. I'm encountering an issue where the generated HelmChart resource is different than the values I provide to my HelmRelease via spec.chartRef and HelmChart resource.
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-helmrelease
spec:
  interval: {{ .Values.automation.interval }}
  chartRef:
    kind: HelmChart
    name: {{ .Release.Name }}-helmchart
```
```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: {{ .Release.Name }}-helmchart
spec:
  interval: {{ .Values.automation.interval }}
  chart: {{ .Chart.Name }}
  reconcileStrategy: Revision
  sourceRef:
    kind: HelmRepository
    name: {{ .Release.Name }}-helmrepo
  version: "*"
```
All the resources:
![image](https://github.com/fluxcd/flux2/assets/7032300/f50b5442-308b-4eb0-8768-560896cb1b6e)

a yaml export of the generated HelmChart resource
![image](https://github.com/fluxcd/flux2/assets/7032300/8feba356-7604-4656-9e66-edb8e2305876)

the reconciliation stratagey is different and the name doesn't follow the convention, given the HelmChart in chartRef, should this not be (where the release name is just "nekos-zip") nekos-zip-helmrepo? Is there something I've missed?
