### DISCUSSION TITLE
Image policy does not seem to work inside strings (using Kustomization patch)

### DISCUSSION THREAD

**Discussion by cep21** [fluxcd/flux2#4832] [Q&A]
I'm unable to see image policy work for content that is inside a strings.  Specifically I'm trying to patch a helm release object that has a values spec for an image inside it (the github actions controller).  My Kustomization looks like this and the imagepolicy does not seem to be picked up.  Is there a workaround?

```yaml
# Deploys node bootstrapping components
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-project
spec:
  # ...
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: ignored
        spec:
          values:
            template:
              spec:
                containers:
                  - name: runner
                    command: ["/home/runner/run.sh"]
                    image: "123123123.dkr.ecr.us-west-2.amazonaws.com/action-runner-image:v1.2.3" # {"$imagepolicy": "flux-system:action-runner-image"}
      target:
        kind: HelmRelease
        name: gha-runner-scale-set
```
