### DISCUSSION TITLE
Want to "integrate" an existing release into flux with no interruption of service

### DISCUSSION THREAD

**Discussion by sebabarre-evaneos** [fluxcd/flux2#4837] [Q&A]
Hello,

As testing purpose before deploy on our existing cluster, i have a release already deployed in a namespace, and i want to tell flux to handle this release now, but when i deploy an HelmRelease the deployment rollout, and i don't want that.

Is it possible ?

The release deployed : 
`helm install my-apache bitnami/apache -n sebarre-flux-test`

The HelmRelease deployed : 
```yaml
kind: HelmRepository
apiVersion: source.toolkit.fluxcd.io/v1
metadata:
    name: bitnami
    namespace: sebarre-flux-test
spec:
    interval: 1m
    url: https://charts.bitnami.com/bitnami
---
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2
metadata:
  name: apache
  namespace: sebarre-flux-test
spec:
  releaseName: my-apache
  interval: 1m
  chart:
    spec:
      chart: apache
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 1m
```
