### DISCUSSION TITLE
I don't want that a k8s job rerun every day

### DISCUSSION THREAD

**Discussion by jlozano-rh** [fluxcd/flux2#4839] [Q&A]
I have a k8s `Job` that should be run only once.

Example:
```yml
apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  backoffLimit: 0
  completions: 1
  completionMode: Indexed
  parallelism: 1
  # keep the log for 2 days
  ttlSecondsAfterFinished: 172800
  template:
    spec:
      containers:
      - name: example-job
        imagePullPolicy: IfNotPresent
        image: some/image:tag
        command: ["bash", "script.sh"]
        envFrom:
          - configMapRef:
              name: config-urls
        env:
          - secretKeyRef:
              name: config-credentials
        volumeMounts:
          - mountPath: /some/cache/dir
            name: cache-volume
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: 500Mi
      restartPolicy: Never
```

And this is my `Kustomization` object:
```yml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: example-job
  namespace: cicd
spec:
  interval: 5m0s
  path: ./kustomize/overlays/dev
  sourceRef:
    kind: GitRepository
    name: example-job
  healthChecks:
    - apiVersion: batch/v1
      kind: Job
      name: example-job
      namespace: cicd
  timeout: 10m
  prune: true
  force: true
``` 

But every one or two days, the `Job` run again (and is not the behavior that I need, because I'm running database migrations on it). What's wrong?
