### DISCUSSION TITLE
Bootstrap multiple clusters into one single shared directory

### DISCUSSION THREAD

**Discussion by HamzaZo** [fluxcd/flux2#4870] [Q&A]
Hello,

We have more than 200 clusters, and I wonder if Flux bootstrap supports bootstrapping multiple clusters into a single shared folder `flux-system`

For example, running the same command on multiple clusters: 
`flux bootstrap git --url=ssh://git@example.com/repository.git --path=clusters/flux-system`

**Comment by stefanprodan** [comment]
If the clusters run the same apps then Yes you can reuse the path, but it should be `clusters/shared`, bootstrap will create the `flux-system` dir first time you run it, inside `shared`.

To set different values per cluster, let's say ingress domains, you can use Flux [variable substitutions](https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-variable-substitution), even if in Git all are using the same manifests.

**Reply by HamzaZo** [reply]
the generated manifests won't be erased each time I run the bootstrap ? the folder name must be `clusters/shared` in path 
`flux bootstrap git --url=ssh://git@example.com/repository.git --path=clusters/shared` or I can choose whatever name I want ?

**Reply by stefanprodan** [reply]
The manifests inside flux-system will be overwritten each time but this will result in no changes. You can chose whatever name you want for the dir, but flux-system is confusing as it will result in `clusters/flux-system/flux-system`.

**Reply by HamzaZo** [reply]
The Git history will be a mess due to continually committing the overridden manifests. Is there any better approach ?

**Reply by stefanprodan** [reply]
Yes the Flux Operator or write your own thing.

**Reply by HamzaZo** [reply]
it seems that the Flux Operator will do the same thing `continually committing the overridden manifests` as mentioned in https://fluxcd.control-plane.io/operator/fluxinstance/#sync-from-git-over-ssh 
```
spec:
  sync:
    kind: GitRepository
    url: "ssh://git@github.com/my-org/my-fleet.git"
    ref: "refs/heads/main"
    path: "clusters/my-cluster"
    pullSecret: "git-ssh-auth"
```

**Reply by stefanprodan** [reply]
The Flux Operator doesn't write to Git...

**Reply by stefanprodan** [reply]
There are no manifests in Git at all, the Flux manifests are managed by the operator itself, directly in etcd, based on the version specified in the FluxInstance.

**Reply by HamzaZo** [reply]
I see, is there any way to add tolerations or podAntiAffinity to the generated manifests  by the operator. I tried to do something like this but it does not work: 
```
spec:
  kustomize:
    patches:
      - target:
          kind: Deployment
          name: "(kustomize-controller|helm-controller)"
        patch: |
          - op: add
            path: /spec/template/spec/tolerations/-1
            value: {"operator": "Exists"}
```
I'm getting `build failed: add operation does not apply: doc is missing path: "/spec/template/spec/tolerations/-1": missing value` 
any idea please @stefanprodan  ?
