### DISCUSSION TITLE
ImagePolicy in a Helm Deployment doesn't trigger Git change

### DISCUSSION THREAD

**Discussion by itai-spiritt** [fluxcd/flux2#4876] [Q&A]
Hey all
I have configured Flux in my EKS cluster using Helm for deployment.
I have successfully created the `ImagePolicy` (I can see the CR in my K8S cluster).
When I change the upstream image, I see that the policy has updated (using `kubectl`) but there is no commit to change the Deployment image.
My helm charts are in a different folder, and in the Flux folder I keep my services values files as HelmReleases

Flux version 2.3.0
k8s 1.30.0

Structure:
- charts
  - app-stack
    - Deployment.yaml
- flux
  - my-cluster
    - apps
      - app1.yaml
      - app2.yaml
    - flux-system
      - flux stuff

Flux path is `./flux/my-cluster`

```
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@acme.io
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: master
  update:
    path: ./flux/my-cluster
    strategy: Setters
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: my-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: my-service
  filterTags:
    pattern: '^master.*'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: my-service
  namespace: flux-system
spec:
  image: ecr.amazonaws.com/my-service
  interval: 1m
  secretRef:
    name: ecr-secret
---
apiVersion: apps/v1
kind: Deployment
...
        image: {{ .Values.my-service.image }} # {"$imagepolicy": "flux-system:my-service"}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
...
  values:
    my-service:
      image: ecr.eu-west-1.amazonaws.com/my-service:...
```
