### DISCUSSION TITLE
An ImagePolicy configuration for Calver format and an optional tag suffix

### DISCUSSION THREAD

**Discussion by 0xStarcat** [fluxcd/flux2#4881] [Show and tell]
👋🏼 felt like sharing an ImagePolicy configuration I figured out that works with Calver format + an optional tag suffix (ie: `-hotfix1`)
It uses the semver policy to extract and transform the components into semver format for internal comparison. It works only when your Calver format uses 0-padded dates like `YYYY-0M-0D.PATCH` (patch is optional too)

```
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: foo
  namespace: bar
spec:
  filterTags:
    pattern: ^v(?P<YEAR>\d+)\.(?P<MONTH>\d+)\.(?P<DAY>\d+)\.(?P<PATCH>\d+)(-hotfix(?P<QUANTIFIER>\d+))?$
    extract: $YEAR$MONTH$DAY.$PATCH.${QUANTIFIER}0
  policy:
    semver:
      range: ">=0.0.0"
```

tested with the following tags being detected earliest to latest:
1. `v2024.06.08.0`
2. `v2024.06.08.0-hotfix1`
3. ... `v2024.06.08.0-hotfix10`
4. `v2024.06.08.1`
5. `v2024.06.09.0`
6. ... `v2024.06.09.10`
7. ... `v2024.06.09.10-hotfix1`
8. `v2024.06.10.0`
