### DISCUSSION TITLE
Flux doesn't redeploy when local Helm charts changes

### DISCUSSION THREAD

**Discussion by itai-spiritt** [fluxcd/flux2#4882] [Q&A] [answered]
My project is built from multiple helm resources (charts) locally (git repo).
I have multiple HelmReleases that depend on these local charts.
I have configured Flux to listen to changes in the Kustomization path, and the charts are in a different path.

- charts
    - app-stack
      - deployment.yaml
      - ingress.yaml
      - ...
- clusters
  - test
    - apps
      - a.yaml
      - b.yaml
      - ...

a.yaml
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/app-stack
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
values:
  ...
```

gotk-sync.yaml
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/test
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

How can I trigger a redeploy when changing my charts (files in `charts/app-stack`)?
I am trying to force the update by adding an arbitrary value in the apps yaml (`a.yaml`) but nothing happens.
