### DISCUSSION TITLE
Kustomization stays in reconciliation until health check failure but HelmRelease artifacts are deployed and then unsynced

### DISCUSSION THREAD

**Discussion by LockeBirdsey** [fluxcd/flux2#4884] [Q&A]
I'm doing a very small test of Flux and I've run into a recurring issue:

1. Define and deploy a `HelmRepository` and `HelmRelease`
2. Define and deploy my `apps` directory with `apps.yaml` reference
3. `flux get kustomizations apps` is in `Ready=unknown` with message `Reconciliation in progress` until `health check failed after 5m...`
4. Pods and services are deployed and working
5. Remove `apps.yaml`, deploy and wait for reconciliation
6. `apps` kustomization is gone
7. Pods and services remain

The 2 main problems here:

1. Why is health check failing while the chart pods and services are deployed successfully?
2. When removing the 'parent' app, why do the pods and services remain? (If this is a misunderstanding I have with Flux then that's fine)

I've noticed several concerns about the `timeout` and `intervals` needing to be in a particular sequence, which I'm pretty sure I have correct, so this might be something else.

```bash
> flux version
flux: v2.3.0
distribution: flux-v2.3.0
helm-controller: v1.0.1
kustomize-controller: v1.3.0
notification-controller: v1.3.0
source-controller: v1.3.0
```

Cluster: k3s

<details><summary>Deployment YAMLs</summary>
<p>

`cluster/main/apps.yaml`
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/playground
  prune: true
  wait: true
  timeout: 5m0s
```
`clusters/main/helmrepos/bitnami.yaml`
```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: playground
spec:
  interval: 15m0s
  url: https://charts.bitnami.com/bitnami
```

`apps/playground/nginx-test.yaml`
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx-test
  namespace: playground
spec:
  chart:
    spec:
      chart: nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 18.1.4
  interval: 50m
  values:
    fullnameOverride: the-nginx-test
```

</p>
</details>
