### DISCUSSION TITLE
Dynamically Setting Timestamps in YAML Manifests with Flux Kustomize

### DISCUSSION THREAD

**Discussion by vijayansarathy** [fluxcd/flux2#4897] [Q&A]
Hi Everyone.

I am trying to come up with a solution for dynamically setting the value of a field in a Kubernetes manifest to the timestamp at which Flux Kustomize deploys that manifest. So, I was thinking of doing something like this.

First create a ConfigMap as follows:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-param
  namespace: test
data:
  deployTimestamp: 
```

Then, I can define the variable `${deployTimestamp}` in K8s manifests that are built by the Flux Kustomize pipeline. Kustomize can then reference this ConfigMap under `.spec.postBuild`, as shown below, to perform post-build variable substitution on such manifests.
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test
  namespace: flux-system
spec:
  path: ./manifests-to-inject-timestamp
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: test-param
        optional: false  
```

The ConfigMap itself is processed and deployed by the Flux Kustomize pipeline.
The question is how do I dynamically set the value of `deployTimestamp` field at build time?
Is there a better solution for doing what I am trying to do?
