### DISCUSSION TITLE
Patch HelmRelease behind fluxcd Kustomization

### DISCUSSION THREAD

**Discussion by everythings-gonna-be-alright** [fluxcd/flux2#4902] [Q&A]
https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize

I am trying to add some values overlays to my HelmRelease, but the configMapGenerator can't insert the correct configMap name because it is located behind flux Kustomization.
But I need flux Kustomization here for dependency reasons.
How can I overcome this? Any options?

Here is my overlay code example:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-app
resources:
  - ../../../infrastructure/base/my_app
configMapGenerator:
  - name: my-app-values-overlay
    files:
      - values.yaml=values.yaml
patches:
  - patch: |
      - op: add
        path: /spec/patches/-
        value:
            patch: |-
              - op: add
                path: /spec/valuesFrom/-
                value:
                  kind: ConfigMap
                  name: my-app-values-overlay
            target:
              kind: HelmRelease
              name: my-app
    target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: my-app-release
configurations:
  - ../../kustomizeconfig.yaml
```
 
 
 Here is a result:
 ```
 could not resolve ConfigMap chart values reference 'my-app/my-app-values-overlay' with key 'values.yaml': configmaps "my-app-values-overlay" not found
 ```

**Comment by praiaCristianMaluenda** [comment]
I am having the same issue. The problem is Kustomization creates the configmap with a random string and Flux can not find it. It is supposed to be transparent, but it doesn't work in Flux.
A possible solution is to set the property `disableNameSuffixHash` to `true`. 

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: customer

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: service-config-dev
    files:
      - dev.yaml
```
