### DISCUSSION TITLE
What to do for chart semver range when the tag starts with v

### DISCUSSION THREAD

**Discussion by Hazmi35** [fluxcd/flux2#4919] [Q&A]
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: staging
spec:
  chart:
    spec:
      chart: cert-manager
      version: "v1.*"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: dragonfly
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
   ```
   
   I'm trying to deploy dragonflydb but because of the tag has `v` (v1.21.0) prefix in it, source-controller failed to find the requested tag if I set the version with `v1.*`. `v1.21.0` works fine.
   
   Helm chart: https://github.com/dragonflydb/dragonfly/pkgs/container/dragonfly%2Fhelm%2Fdragonfly
