### DISCUSSION TITLE
FluxCD App deployment path not found issue

### DISCUSSION THREAD

**Discussion by harshit-paneri** [fluxcd/flux2#4920] [Q&A]
My repo structure : 

```
prod-common-teal/
├── flux-system/
│   ├── gotk-components.yaml
│   ├── gotk-sync.yaml
│   └── kustomization.yaml
└── whoami-cluster/
    ├── whoami-kustomization.yaml
    └── whoami-source.yaml

```
While doing : `flux get kustomizations --watch`

I am facing this issue:

```
NAME       	REVISION          	SUSPENDED	READY	MESSAGE                              
flux-system	main@sha1:708e5b46	False    	True 	Applied revision: main@sha1:708e5b46	
whoami		False	False	kustomization path not found: stat /tmp/kustomization-3634336803/kustomize: no such file or directory
```

Note: I am using GitRepository  ( `kind: GitRepository` ) 

Expected Output:

```
NAME       	REVISION          	SUSPENDED	READY	MESSAGE                              
flux-system	main@sha1:708e5b46	False    	True 	Applied revision: main@sha1:708e5b46	
whoami		<main@sha1:708e5b46>	False	        True    <main@sha1:.....>
```

That kind of response

In `watcher-kustomize.yaml` content is : 
```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: whoami
  namespace: flux-system
spec:
  interval: 30m0s
  path: "./kustomize" 
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: whoami
  targetNamespace: flux-system
  timeout: 3m0s
  wait: true
```
