### DISCUSSION TITLE
Flux Depends on With a wildcard pattern or namespace

### DISCUSSION THREAD

**Discussion by jeevanragula** [fluxcd/flux2#4975] [Proposals]
We have a use case one of the Helm Relase depends on Multiple Helm Releases which follow a pattern and they gets created dynamically in single namespace.

So we are looking for a feature where we either specify a pattern to match the helm release names or specify namespace and keep the name as optional so that if all the helm releases under that namespace or that pattern matches then the reconcile will happen.

Can some one tell if this is currently supported or Is this a new feature we can introduce in Flux?

```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: test-application
  namespace: test
spec:
  chart:
    spec:
      version: 1.0.0
  dependsOn:
    - name: *-another-application
      namespace: anothernamespace

```
