### DISCUSSION TITLE
configMapGenerator issues - flux looks for unhashed configmap name

### DISCUSSION THREAD

**Discussion by reallydontask** [fluxcd/flux2#4985] [Q&A] [answered]
I'm trying to follow this example: https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize to install cert-manager

I have created a kustomizeconfig.yaml

```
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: ./cluster-configuration/controllers/cert-manager/values.yml
    kind: HelmRelease
```

then a kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - cert-manager.yaml
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yml=values.yml
configurations:
  - kustomizeconfig.yaml
```

and this is the cert-manager.yaml

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager  
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
```

This fails with:

```
could not resolve ConfigMap chart values reference 'cert-manager/cert-manager-values' with key 'values.yaml': configmaps "cert-manager-values" not found
```

Not sure where I'm going wrong with this, as the kustomized helmrelease resource hasn't been updated with the hashed configmap name, so the error is consistent with the state of the system, but why isn't the helmrelease object being updated?

Any ideas?

TIA

**Comment by stefanprodan** [comment]
The path is wrong here:

```
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: ./cluster-configuration/controllers/cert-manager/values.yml
    kind: HelmRelease
```

This path refers to the spec of the HelmRelease, see the docs: https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize

**Reply by reallydontask** [reply]
Thanks for your reply

I guess it should be cert-manager then, like this or have I misunderstood what you mean?

```
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: cert-manager
    kind: HelmRelease
```
