### DISCUSSION TITLE
Helm overwrite values

### DISCUSSION THREAD

**Discussion by derritter88** [fluxcd/flux2#5026] [Q&A]
Hello there,

I recently started to play around with Flux and not sure how to poroperly use inline values.

Helm values are being recognized if I would use it that way
```
  values:
    image:
      tag: "latest"
      pullPolicy: Always
```

but if I would just use an ordinary key value pair it's somehow not working:

```
  values:
    domain: "https://foo.bar"
```

Any idea what I am doing wrong?
