### DISCUSSION TITLE
Slack notifications aren't being sent

### DISCUSSION THREAD

**Discussion by brianhicks-pnm** [fluxcd/flux2#5037] [General] [answered]
Hi! I'm having some trouble setting up notifications to go to a Slack channel. Following the guide, and creating+installing a Slack app in my workspace, I have these manifests:

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  channel: the-channel-i-care-about
  type: slack
  address: https://slack.com/api/chat.postMessage
  secretRef:
    name: slack-bot-token # not including, but this exists and has a key `token` as in the guide
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: alerts
  namespace: flux-system
spec:
  summary: flux-system components are being effected
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "*"
    - kind: GitRepository
      name: "*"
    - kind: HelmRelease
      name: "*"
    - kind: Bucket
      name: "*"
    - kind: HelmChart
      name: "*"
    - kind: OCIRepository
      name: "*"
    - kind: HelmRepository
      name: "*"
    - kind: ImageRepository
      name: "*"
    - kind: ImagePolicy
      name: "*"
    - kind: ImageUpdateAutomation
      name: "*"
  providerRef:
    name: slack

```

When these things are updated, I can see in the `notification-controller` logs that they're being dispatched, but nothing about actually sending the message. In addition, the `Provider` doesn't have any kind of status field, which makes me think that Flux is maybe not picking it up.

Where would I go to find out what's actually going wrong here? Does any of that look suspicious to folks?
