### DISCUSSION TITLE
Challenges with OCI URLs and Helm repositories: No automatic chart updates?

### DISCUSSION THREAD

**Discussion by carrodher** [fluxcd/flux2#5041] [General]
Hi all,

We’re currently testing Flux’s usability with an _index.yaml_ based on OCI URLs. Flux supports both traditional Helm repositories and OCI-based Helm repositories, as documented here:
 * [Flux & Helm HTTPS repos docs](https://fluxcd.io/flux/components/source/helmrepositories/#helm-https-repository).
 * [Flux & Helm OCI repos docs](https://fluxcd.io/flux/components/source/helmrepositories/#helm-oci-repository).

However, when using OCI repositories, there is no defined interval for the Flux Source Controller to check for updates in the Helm repo, meaning there’s no automatic reconciliation process. This differs from traditional Helm repos, which benefit from regular updates due to the presence of an index.

A HelmRelease in Flux defines an "interval" (see [HelmRelease docs](https://fluxcd.io/flux/components/helm/helmreleases/#interval)) which defines the interval at which the HelmRelease is reconciled. This reconciliation process includes upgrading a chart release if there's a new chart version published in the Helm repository. **However, when working with OCI Helm repositories, Flux cannot inherently detect new chart versions**.

This is the reason why a Helm repository index (regardless it uses OCI-based URLs or not) is key for automating upgrading to new chart versions with Flux.

### Testing Helm OCI-based URLs on Helm repo index
* I served through NGINX a very simple Helm repo index listing MariaDB:
```yaml
apiVersion: v1
entries:
  mariadb:
    - annotations:
      (...)
      appVersion: 11.4.3
      (...)
      name: mariadb
      (...)
      urls:
        - https://foo/bar/mariadb-19.0.6.tgz
      version: 19.0.6
generated: "2024-10-01T10:06:21.106464648Z"
```

 * Next, we created a HelmRepo and HelmRelease in Flux:

```console
$ kubectl get helmrepo
NAME        URL                                           AGE   READY   STATUS
podinfo     https://a00a-192-157-215-178.ngrok-free.app   2m    True    stored artifact: revision 'sha256:6fec7c7720d112184700a0d1280bae658bb44f17bf91a5c2318113e8780a1fe8'
$ kubectl get helmrelease
NAME        AGE     READY   STATUS
mariadb     4m29s   True    Helm install succeeded for release default/mariadb.v1 with chart mariadb@19.0.6
```
 * We then transformed the _index.yaml_ to use OCI URLs:

```diff
-         - https://foo/bar/mariadb-19.0.6.tgz
+         - oci://foo/bar/mariadb:19.0.6
```
 * And we added a new chart version:

```yaml
apiVersion: v1
entries:
  mariadb:
    - annotations:
      (...)
      appVersion: 11.4.3
      (...)
      name: mariadb
      (...)
      urls:
        - oci://foo/bar/mariadb:19.0.7
      version: 19.0.7
    - annotations:
      (...)
      appVersion: 11.4.3
      (...)
      name: mariadb
      (...)
      urls:
        - oci://foo/bar/mariadb:19.0.6
      version: 19.0.6
generated: "2024-10-01T10:06:21.106464648Z"
```
 * However, despite waiting for reconciliation, the new version failed to download:
```console
$ kg helmchart
NAME                CHART     VERSION   SOURCE KIND      SOURCE NAME   AGE   READY   STATUS
default-mariadb     mariadb   19.x      HelmRepository   podinfo       22m   False   chart pull error: failed to download chart for remote reference: Get "oci://foo/bar/mariadb:19.0.7": unsupported protocol scheme "oci"
```

It seems that Flux expects "classic" Helm repositories to use HTTP(S) URLs and doesn’t yet support OCI URLs for Helm repositories.

**Comment by stefanprodan** [comment]
This is how you should define the Helm OCI:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 10m
  url: oci://ghcr.io/stefanprodan/charts/podinfo
  ref:
    semver: ">6.0.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 10m
  releaseName: podinfo
  chartRef:
    kind: OCIRepository
    name: podinfo
```
