### DISCUSSION TITLE
How to solve the invalid chart reference error?

### DISCUSSION THREAD

**Discussion by ArKam** [fluxcd/flux2#5048] [Q&A] [answered]
Hi everyone,

just playing around with helm and flux (So far I was always using kustomize) but I get an issue where flux can't reconciliate as it can't build the helm chart because it can't find it on the source repository.

I'm using a GitRepository source for this helmRelease.

The upstream git repository is: [peertube-helm](https://git.lecygnenoir.info/LecygneNoir/peertube-helm.git)
set to use the tag version: 1.6.0 as this:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: peertube-helm
  namespace: peertube
spec:
  interval: 1m
  url: https://git.lecygnenoir.info/LecygneNoir/peertube-helm.git
  ref:
    tag: v1.6.0
```

Then I've got a helmRelease set as:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: v1.6.0
  namespace: peertube
spec:
  interval: 10m
  chart:
    spec:
      chart: Chart
      sourceRef:
        kind: GitRepository
        name: peertube-helm
        namespace: peertube
      interval: 5m
```

Flux correctly create the namespace and storage volume/claims and even correctly retrieve and create the peertube-helm gitRepository artifact.

However, it fail being able to locate the Chart.yaml file which is located at the root of the repository and end up with the following message:
> invalid chart reference: stat /tmp/helmchart-peertube-peertube-helm-v1.6.0-2459170356/source/Chart: no such file or directory
Everything is located onto the same namespace (peertube).

What did I missed?
