### DISCUSSION TITLE
Can helm release valuesFrom a configmap partly, thanks.

### DISCUSSION THREAD

**Discussion by johnzheng1975** [fluxcd/flux2#5078] [Q&A] [answered]
Can helm release valuesFrom a configmap partly, thanks.
For some reason (values.yaml is too long, some securer field do not want to expose), can I only get one filed from values.yaml and put it into helmrelease. 

Like below:
Here is configmap.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-values
  namespace: flux-system
data:
    values.yaml: |
      # Your values here
      replicaCount: 2
      image:
        repository: nginx
        tag: stable
```
        
        
Here is helmrelease, works well.
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-application
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: name-of-the-chart
      version: "1.2.3"
      sourceRef:
        kind: HelmRepository
        name: my-helm-chart-repo
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: my-values
    valuesKey: values.yaml
```

Can I only expose one key from values.yaml, like
```
  valuesFrom:
  - kind: ConfigMap
    name: my-values
    valuesKey: values.yaml
    subkey: replicaCount
```
