### DISCUSSION TITLE
Variable substitution and patches don't mix?

### DISCUSSION THREAD

**Discussion by bozho** [fluxcd/flux2#5082] [General]
Hi all,

I may be doing something wrong, but it looks like flux variable substitution and patching resources doesn't really work. Here's my example with a Gateway:

```yaml
# ./infrastructure/gateway/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${namespace_name}
resources:
  - gateway.yaml
```

```yaml
# ./infrastructure/gateway/gateway.yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ${gateway_name}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: nginx
  listeners:
    - name: dummy
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
```

```yaml
# ./clusters/_base/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  # ...
  - gateway.yaml
  # ...
```

```yaml
# ./clusters/_base/gateway.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: gateway-api
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/gateway
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      namespace_name: networking
      gateway_name: frontend
  patches:
    - target:
        kind: Gateway
        name: ${gateway_name}
      patch: |-
        kind: Gateway
        metadata:
          name: _
        spec:
          listeners:
            - name: http
              port: 80
              protocol: HTTP
              hostname: www.example.com
              allowedRoutes:
                namespaces:
                  from: All
            - name: https
              port: 443
              protocol: HTTPS
              hostname: www.example.com
              allowedRoutes:
                namespaces:
                  from: All
              tls:
                mode: Terminate
                certificateRefs:
                  - name: example-cert
```

The `_base` kustomization is then used by actual cluster kustomizations.

There seems to be a problem when `${gateway_name}` variable placeholder is used in the patch.

If my base `gateway.yaml` kustomization doesn't specify the patch, `${gateway_name}` in `Gateway`'s `metadata.name` is substituted properly, and `Gateway` with the name `frontend` and the `dummy` listener is created.

If I specify the patch as above (with `target.name` set to `${gateway_name}`), the patch silently doesn't get applied.

If I set patch `target.name` to `frontend` explicitly, the patch still doesn't get applied.

Only if I set both the patch `target.name` and `Gateway`'s `metadata.name` explicitly to `frontend` does the patch get applied. Is this a bug, or am I doing something wrong here?
