### DISCUSSION TITLE
How to use multiple namespace within base and child directory.

### DISCUSSION THREAD

**Discussion by tsiq-sanjanar** [fluxcd/flux2#5088] [Q&A] [answered]
Hi Below is the issue I am facing. Can anyone please help me?

We have flux v2.4.0

There are two env dev and prod. Below is the structure we have

```
apps/
  app-name
     base/
       kustomization.yaml
       release.yaml
     dev/
       kustomization.yaml
       app-name-values.yaml
     prod/
       kustomization.yaml
      app-name-values.yaml
      
```
base/release.yaml has below code 
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: account-service
  namespace: dev   #Notice the namespace
 ```
prod/app-name-values.yaml has below code
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: account-service
  namespace: prod   #Notice the namespace
```
My expectation was when the code is deployed in prod it would override base namespace with prod namespace but instead it fails with below error 
```
kustomize build failed: no resource matches strategic merge patch "HelmRelease.v2beta1.helm.toolkit.fluxcd.io/istio-gateway.prod": no matches for Id HelmRelease.v2beta1.helm.toolkit.fluxcd.io/istio-gateway.prod; failed to find unique target for patch HelmRelease.v2beta1.helm.toolkit.fluxcd.io/istio-gateway.prod   
```
In order to fix this I had to update the base.yaml with prod namespace.
