### DISCUSSION TITLE
how to configure Flux-cd to pick up the committed changes and re-apply the jobs.

### DISCUSSION THREAD

**Discussion by ayukukre** [fluxcd/flux2#5102] [Q&A]
Hi team, I have this below directory structure, in which I am bootstrapping the path /dev.
```
├── dev
    └──jobs
        └──job.yaml
    └──specs
        └──config.yaml
    └──kustomization.yaml
```
Using the kustomization.yaml I am creating a configMap which uses the data from the specs/config.yaml file and triggers the job.yaml, also I am using that configMap in the job.yaml.

---kustomization.yaml-----
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - jobs/job.yaml
configMapGenerator:
  - name: dev-config-map
    files:
      - config.yaml=specs/config.yaml
generatorOptions:
  disableNameSuffixHash: true
```
When I am bootstrapping it for the 1st time I am able to see the job is getting created and completed, now when I update/modify the config.yaml and commit the changes to git repository, the Flux-cd is not reapplying the job. 

Expectations: Is it possible to re-trigger(not manually) the job everytime I am making any change in the config.yaml or job.yaml and then committing it to the git repository.

Can you please provide any suggestions or configuration I am missing here ?

Thanks in advance!!
