### DISCUSSION TITLE
Using FluxCD with OCI Helm Charts: Handling Tags in HelmRelease

### DISCUSSION THREAD

**Discussion by hmoens** [fluxcd/flux2#5113] [Q&A] [answered]
Hi!

I'm working on using FluxCD to manage and deploy Helm charts from an OCI repository. My workflow doesn’t use Git directly. Instead, CI pipelines build and publish Helm charts to an OCI repository. A HelmRelease resource in the cluster monitors for changes and applies updates as necessary.

I want to use tags from the OCI repository (e.g., prod) to determine the appropriate version of the Helm chart, for example:

`flux tag artifact oci://my-registry/starter-app:1.2.3 --tag prod`

This command properly adds a 'prod' tag to the chart, which gave me hope that this approach would work.

Here’s my current YAML configuration:

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: starter-app-repo
  namespace: starter-app
spec:
  interval: 1m
  url: oci://my-registry/starter-app
  ref:
    tag: prod
  provider: aws
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: starter-app
  namespace: starter-app
spec:
  chartRef:
    kind: OCIRepository
    name: starter-app-repo
  interval: 1m
  values: {}
```

When I apply this configuration, it fails with the error:

`failed parsing artifact revision prod`

If I manually change the ref.tag value in the OCIRepository resource to a specific version (e.g., 1.2.3), it works as expected. The issue seems to be that the HelmRelease interprets the ref.tag value (e.g., prod) as the chart version, even though the version in the Chart.yaml from the OCI repository is correct.

**A possible workaround**

To bypass this issue, I started building separate -prod and -dev variants of the chart and updated the OCIRepository to filter using semver:

```
spec:
  ref:
    semver: ">=0.0.0-0"
    semverFilter: ".*-prod"
```

This works but comes with drawbacks:

-     It requires building additional chart variants for each environment.
-     It feels like a hacky workaround rather than a proper solution.

An alternative option would be to just do away with chart versioning overall and just build 0.0.0-prod and 0.0.0-dev instead but this also comes with obvious drawbacks.

**Question**

Is there a better approach within the FluxCD ecosystem to handle this scenario? Ideally, I’d like to use OCI tags (e.g., prod, dev) for dynamic Helm chart management without introducing additional complexity like environment-specific chart variants.

Any insights or suggestions would be greatly appreciated!

Edit: in the original version of this post there was an error in the yaml manifests.

**Comment by matheuscscp** [comment]
Change:

```
  chart:
    spec:
      sourceRef:
        kind: OCIRepository
        name: starter-app-repo
```

to:

```
  chartRef:
    kind: OCIRepository
    name: starter-app-repo
```

**Reply by hmoens** [reply]
I apologize: when anonymizing the yaml configuration (and converting from hcl) I somehow managed to get those two mixed up. The config as deployed is indeed

```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: starter-app
  namespace: starter-app
spec:
  chart:
  spec:
    chartRef:
      kind: OCIRepository
      name: starter-app-repo
    interval: 1m
    values: {}
```
