### DISCUSSION TITLE
How do I substitue version into url path for kustomization

### DISCUSSION THREAD

**Discussion by alita-moore** [fluxcd/flux2#5124] [Q&A]
Is it possible to use a variable for the version in a kustomization url string?

For example:
```yaml
resources:
  - https://download.elastic.co/downloads/eck/${version}/crds.yaml
```

If I use the `postBuild` option it gives me an error:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: elastic-crds
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infra/elastic/crds/overlays/local
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: monorepo
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: elastic-cloud-operator-version
```
outputs:
```
kustomize build failed: accumulating resources: accumulation err='accumulating resources from '../../base': read /tmp/kustomization-2571913250/infra/elastic/crds/base: is a directory': recursed accumulation of path '/tmp/kustomization-2571913250/infra/elastic/crds/base': accumulating resources: accumulation err='accumulating resources from 'https://download.elastic.co/downloads/eck/${version}/crds.yaml': URL is a git repository': failed to run '/usr/bin/git fetch --depth=1 https://download.elastic.co/downloads/eck HEAD': fatal: repository 'https://download.elastic.co/downloads/eck/
```
