### DISCUSSION TITLE
Certificate issue using using Github as helm repository

### DISCUSSION THREAD

**Discussion by Hexoplon** [fluxcd/flux2#5143] [Q&A]
Hi,

I'm having issues configuring HelmRepositories that are using Github to host the helm charts. The issue seems to be due to the redirects that these repos tend to do. For some reason, it seems that flux does not revalidate the certificate for other urls than what is first configured.

Do others have the same issue as well, or do you have any ideas how I can work around this? (other than using a chart syncer if possible)

Example error:

```
0s          Warning   ChartPullError               helmchart/flux-system-node-feature-discovery   chart pull error: failed to download chart for remote reference: Get "https://github.com/kubernetes-sigs/node-feature-discovery/releases/download/v0.17.0/node-feature-discovery-chart-0.17.0.tgz": tls: failed to verify certificate: x509: certificate is valid for github.com, www.github.com, not kubernetes-sigs.github.io
```

Example HelmRepository:

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: "nfd"
  namespace: flux-system
spec:
  interval: 30m
  url: "https://kubernetes-sigs.github.io/node-feature-discovery/charts"
  timeout: 3m
```
