### DISCUSSION TITLE
Is it safe to rename Git repository specified in GitRepository?

### DISCUSSION THREAD

**Discussion by mloskot** [fluxcd/flux2#5145] [Q&A] [answered]
I have a Git repository hosted on GitHub.
I would like to rename it within the same organization.

In theory, I should not need to change the `url` in the `GitRepository` spec, because [all existing information, with the exception of project site URLs, is automatically redirected to the new name](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository). Am I correct?

However, to keep things clean, I would like to update the `url` in the `GitRepository` manifest:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
spec:
  url: ssh://git@github.com/contoso/abc.git  # rename to github.com/contoso/xyz.git
  ...
```

Is this as trivial and Flux will simply re-fetch from the new URL and continue its business as nothing happened?

Or, should I prepare for anything unexpected like deleting deployments, re-fetching from Git, re-creating deployments?

The only discussion about renaming anything w.r.t. `GitRepository` that I found is this https://github.com/fluxcd/flux2/discussions/3230, but it asks about renaming a Kustomization too what is not my case, and remains unanswered.
