### DISCUSSION TITLE
"kustomize.toolkit.fluxcd.io/ssa: IfNotPresent" not working?

### DISCUSSION THREAD

**Discussion by ntx-ben** [fluxcd/flux2#5161] [General]
I'm running version `2.4.0` of flux and have 2 services that both define the same namespace in their definitions. I added the `kustomize.toolkit.fluxcd.io/ssa: IfNotPresent` annotation to both namespace resources, however I noticed that it seems to be ignored by flux when reconciling the services; the namespace keeps getting SSA'd in the cluster by its respective service at every reconciliation.

service1/namespace.yaml
```
apiVersion: v1
kind: Namespace
metadata:
  anotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
  name: my-ns
```

service2/namespace.yaml
```
apiVersion: v1
kind: Namespace
metadata:
  anotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
  name: my-ns
```

kustomize-controller logs:
```
{"level":"info","ts":"2025-01-27T15:54:50.192Z","msg":"server-side apply for cluster definitions completed","controller":"kustomization","controllerGroup":"kustomize.toolkit.fluxcd.io","controllerKind":"Kustomization","Kustomization":{"name":"service1","namespace":"flux-system"},"namespace":"flux-system","name":"service1","reconcileID":"69dfe54f-9d6e-44c9-bbf8-b2b2e29cb335","output":{"Namespace/my-ns":"configured"}}

(a few moments later)

{"level":"info","ts":"2025-01-27T15:56:41.576Z","msg":"server-side apply for cluster definitions completed","controller":"kustomization","controllerGroup":"kustomize.toolkit.fluxcd.io","controllerKind":"Kustomization","Kustomization":{"name":"service2","namespace":"flux-system"},"namespace":"flux-system","name":"service2","reconcileID":"e5125c92-88fa-437e-9857-170465b63ab9","output":{"Namespace/my-ns":"configured"}}
```

Could anyone tell me what I'm missing? Unless I got this wrong; my assumption is that if service1 first applies the namespace, then service2 should not apply it given the annotation to ignore it when it exists?
