### DISCUSSION TITLE
Best way to store & mount large configuration files

### DISCUSSION THREAD

**Discussion by day1118** [fluxcd/flux2#5173] [Q&A]
I have a number of services exist as helm charts which require a configuration file that I want to mount as a file inside a pod. I would like to keep the configuration file as a standalone file in my git repo for ease of version control and editing. I would rather not add the file contents to the HelmRelease.spec.values.

I'm sure this has been done many times, but cannot find many examples. I have found a way to make it work, but it looks more complex and requires more files than I expected.

I assume the best way is to create a configmap from the configuration file, then mount that as a volume in the pod. Below is my attempt at doing it using an nginx helm chart, though I am using this only as an example, which is why I am not using the `defaultBackend.serverBlockConfig` parameters.

<details>
  <summary>kustomization.yaml</summary>

```yaml
  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  namespace: nginx
  resources:
    - nginx.yaml
  configMapGenerator:
    - name: nginx-config
      files:
        - nginx.conf
  configurations:
    - kustomizeconfig.yaml
```

</details>

<details>
  <summary>kustomizeconfig.yaml</summary>

```yaml
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/values/extraVolumes/configMap/name
    kind: HelmRelease
```
</details> 

<details>
  <summary>nginx.yaml</summary>

```
apiVersion: v1
kind: Namespace
metadata:
  name: nginx

---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts/nginx-ingress-controller
  ref:
    tag: 11.6.7

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 10m
  releaseName: nginx
  chartRef:
    kind: OCIRepository
    name: nginx
  values:
    service:
      type: ClusterIP
    extraVolumes:
      - name: config
        configMap:
          name: nginx-config
    extraVolumeMounts:
      - name: config
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
```
</details>

<details>
  <summary>nginx.conf</summary>

```
# Shortened for sake of example
worker_processes  1;

events {
    worker_connections  1024;
}


http {
    server {
        listen 80;
        location / {
            return 200 "OK\n";
        }
    }
}
```
</details>

I want to keep all of the helm charts in individual repos (some are not my charts either), and have a single repo that Flux uses to deploy everything from.
1. Am I going about this in the right way? Is there a better strategy?
2. I am currently deploying this by running `kubectl apply -k .` - will this work the same way when I put it into a git repo and let flux manage it?
3. Is it possible to simplify the configuration or merge the kustomize files into the nginx.yaml file?
Thanks for your help!
