### DISCUSSION TITLE
Support for custom icons in Slack Provider spec

### DISCUSSION THREAD

**Discussion by deepakraajesh** [fluxcd/flux2#5194] [Q&A]
Currently, the Slack Provider in Flux's notification controller doesn't support setting custom icons (either icon_url or emoji) in the Provider spec. This limits branding and visual differentiation capabilities when using tokens, especially in environments with multiple clusters sending notifications

```
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack
spec:
  type: slack
  channel: your-channel
  username: "Flux Bot"
  icon: ":custom-emoji:"  # Support for custom Slack emoji
  # and/or
  icon_url: "https://example.com/icon.png"  # Support for custom icon URLs
```

Multiple apps are using the same bot token to post messages in different channels, including Grafana, Flux, CI alerts, and script alerts. While Slack allows adding an icon_url in the payload for most methods, this option isn’t available for Flux.

Using incoming webhooks is an alternative, but it applies a single icon to the entire channel. For example, if a channel receives all dev environment alerts from various applications, setting an icon via incoming webhooks means all alerts will share the same icon, making it less distinguishable and harder to read.
