### DISCUSSION TITLE
How to automate images from Helm charts to the latest version

### DISCUSSION THREAD

**Discussion by derritter88** [fluxcd/flux2#5206] [Q&A] [answered]
Hello there,

I am using Flux for some time now and in general this works great.
The only way I am having no success is how to keep images from Helm repositories up-to-date.

Currently a working release.yml would look like:

```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
  namespace: searxng
spec:
  interval: 60m0s
  upgrade:
    force: true
  chart:
    spec:
      chart: searxng
      sourceRef:
        kind: HelmRepository
        name: searxng
        namespace: searxng
      interval: 60m0s
  values:
    image:
      tag: latest
      pullPolicy: Always
      interval: 60m0s
    env:
.....
```

Can anyone shine a light on what I am doing wrong?

**Comment by matheuscscp** [comment]
> Can anyone shine a light on what I am doing wrong?

Definitely not without knowing what issues are you facing :sweat_smile: Do you have any specific error messages?

**Reply by derritter88** [reply]
There is no error message at all.
Flux just does not update the container image.

In my example from above it would be SearXNG which releases a new image once per day.
To currently get the newest image I need to manually redeploy it.

**Reply by matheuscscp** [reply, marked as answer]
Oh I understand your issue now. It has nothing to do with Flux. What HelmRelease will do here for you is deploying your app (Deployment, probably?) with the container image field `something:latest`. Flux has absolutely no knowledge that in your helm chart you have these values:

```yaml
    image:
      tag: latest
      pullPolicy: Always
      interval: 60m0s
```

So you are basically creating whatever this helm chart creates for you, specifying the values above on the chart.

---

What you can do, is use this: https://fluxcd.io/flux/guides/image-update/
