### DISCUSSION TITLE
Helm With OCI and digest version

### DISCUSSION THREAD

**Discussion by b4nst** [fluxcd/flux2#5207] [Q&A] [answered]
The default behavior of flux Helm release when using OCI repository as source is to add the digest to the version as described [here](https://fluxcd.io/flux/components/helm/helmreleases/#chart-reference). This is good, and I understand why.

However some charts can break with incorrect label due to lack of sanitization:

https://github.com/dagger/dagger/blob/cafeac4a8244ae9a407dbf6f5251acaa3cb1bc04/helm/dagger/templates/_helpers.tpl#L39

I know this is not a flux issue (I'm opening a PR to fix the mentioned example). However does somebody have a workaround (can be as dirty as you want, Helm is already 🤢 anyway, all hail [timoni](https://timoni.sh/)) in the meantime?

I tried overriding the label using values, but I get a marshal error. I also tried a dirty post patch:

```yaml
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: apps/v1
              kind: DaemonSet
              name: dagger-engine
            patch: |
              - op: replace
                path: /metadata/labels/app.kubernetes.io~1version
                value: "v0.16.1"
              - op: replace
                path: /spec/template/metadata/labels/app.kubernetes.io~1version
                value: "v0.16.1"
```

but still no luck:

```trace
Helm install failed for release dagger/dagger with chart dagger-helm@0.16.1+3ef98262e848:
      1 error occurred:\n\t* DaemonSet.apps \"dagger-engine\" is invalid: [metadata.labels:
      Invalid value: \"v0.16.1+3ef98262e848\": a valid label must be an empty string
      or consist of alphanumeric characters, '-', '_' or '.', and must start and end
      with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345',
      regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'),
      spec.template.labels: Invalid value: \"v0.16.1+3ef98262e848\": a valid label
      must be an empty string or consist of alphanumeric characters, '-', '_' or '.',
      and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',
      \ or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]
```

Thanks!

_P.S.: Did I mention I hate Helm?_
