### DISCUSSION TITLE
Troubleshooting flux kustomization dependency

### DISCUSSION THREAD

**Discussion by eb112** [fluxcd/flux2#5224] [Q&A]
I'm having trouble with a relatively common pattern:
- Deploy infrastructure
- Deploy an application that has a dependency on a component of the infrastructure.

I know that if I make two Flux Kustomizations (`apps` and `infrastructure`), I should be able to use `dependsOn` to force Flux to deploy infrastructure first, then apps. However, I can't get it to work as I expect it to. I suspect I have a fundamental misunderstanding of FluxCD (and perhaps Kubernetes!).

Requirements:
- Application is a plain Kubernetes deployment.
- Application requires an HTTPRoute
- HTTPRoute requires CRDs and Gateway managed by infrastructure 

Based on my understanding of how FluxCD handles [plain YAML files](https://fluxcd.io/flux/faq/#can-i-use-repositories-with-plain-yamls), flux will automatically process the manifests in my application. Following concepts in the  [Kustomize Helm example](https://github.com/fluxcd/flux2-kustomize-helm-example) I created two new Flux Kustomizations to gain control over the order in which infrastructure and apps and deployed.

However, when bootstrapping, FluxCD _always_ processes the apps first, which causes the reconciliation to fail immediately.

Here's a truncated version of my infra and apps kustomizations. I've gone through multiple iterations using various intervals, timings, healthchecks, and `wait` flags. At this point, I'm not sure if I just haven't hit the magic combination, or if I'm essentially working with an anti-pattern of my own doing.

Note that if I remove `./apps` from my repo, the infrastructure spins up fine. If I then add `.apps/,` the applications also work as expected. I just can't seem to do them all in a single bootstrap.

Here's a truncated version of my infra and apps kustomizations. 
```
# ./infrastructure.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/cluster/infrastructure
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: traefik
      namespace: networking

# ./apps.yaml 
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/apps # applications in this directory and regular kubernetes deployment files.
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure
```

Here's a truncated version of my repository structure:
```
cluster
├── apps
│   ├── my-application
│   │   ├── deployment.yaml # Plain YAML file
│   │   ├── kustomization.yaml
│   │   └── route.yaml #Plan YAML
│   └── kustomization.yaml
├── apps.yaml # kustomization of flux-system
├── flux-system
│   ├── gotk-components.yaml
│   ├── gotk-sync.yaml
│   └── kustomization.yaml
├── infrastructure
│   ├── kustomization.yaml
│   ├── networking
│   │   └── traefik
│   │       ├── kustomization.yaml
│   │       ├── release.yaml # HelmRelease
│   │       └── values.yaml
│   ├── sources
│   │   ├── gitrepositories.yaml
│   │   ├── helmrepositories.yaml
│   │   └── kustomization.yaml
└── infrastructure.yml #  kustomization of flux-system
```

Related error from `flux logs`:
> 2025-02-28T15:29:20.440Z error Kustomization/flux-system.flux-system - Reconciliation failed after 738.701414ms, next try in 10m0s HTTPRoute/my-application/my-application-route dry-run failed: no matches for kind "HTTPRoute" in version "gateway.networking.k8s.io/v1"

Possibly related issues / discussions:
- https://github.com/fluxcd/flux2/discussions/5177
- https://github.com/fluxcd/flux2/discussions/5172

Any hints pointing me in the right direction would be greatly appreciated.

(I do have a workaround where these resources are handled outside of flux, but I'm curious about what I'm missing).

eb
