### DISCUSSION TITLE
Semver act on all tags

### DISCUSSION THREAD

**Discussion by nicolas-goudry** [fluxcd/flux2#5231] [Q&A] [answered]
Hi,

I’m trying to make Flux work by monitoring all semver tags, whatever the version. Below is an example of what I’m trying rn:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: blog
  namespace: flux-system
spec:
  interval: 1m
  ref:
    semver: ">= 0.0.0-0"
  url: https://git.example.com/blog
  secretRef:
    name: blog-access-token
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blog
  namespace: flux-system
spec:
  interval: 1m
  path: ./kustomize/overlays/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: blog
```

As one can see, I read [this](https://github.com/Masterminds/semver#working-with-prerelease-versions) to end up with `semver: ">= 0.0.0-0"`. However, this doesn’t work and `blog`’s GitRepository is reporting the following status:

```
failed to checkout and determine revision: no match found for semver: >= 0.0.0-0
```

Btw, there is the following tag in the repository: `0.0.1-rc250305.095646`. Afaict, this tag is a valid semver tag but for some reason it doesn’t get picked up by Flux…

I tried to add a `0.0.1` tag on the same commit and I can see that Flux is happy and reporting: `stored artifact for revision '0.0.1@sha1:xxx'`.

What am I doing wrong? How to make flux monitor all semver tags, including (but not limited to) pre-release ones?
