### DISCUSSION TITLE
Support for dependsOn referencing a HelmRelease in Kustomization

### DISCUSSION THREAD

**Discussion by ootkin** [fluxcd/flux2#5233] [General]
Hi floks,

I was reviewing the [API reference](https://fluxcd.io/flux/components/kustomize/api/v1/) and noticed that the dependsOn field in a Kustomization appears to work only when referencing another Kustomization resource.

Is it possible to use dependsOn in a Kustomization while pointing to a HelmRelease instead?

For example:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  releaseName: external-secrets
  interval: 5m
  install:
    createNamespace: true
  targetNamespace: external-secrets
  chart:
    spec:
      interval: 1m
      chart: ./infrastructure/external-secrets
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: origin-ca-issuer
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets # This is a HelmRelease, and it does not seem to work
      namespace: external-secrets
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/origin-ca-issuer
  prune: true
  wait: true
```

When attempting this, I receive the following error:

dependency ''external-secrets/external-secrets'' not found: kustomizations.kustomize.toolkit.fluxcd.io "external-secrets" not found

Is there a way to declare a dependency on a HelmRelease, or is dependsOn strictly limited to Kustomization resources?

Thanks in advance for your help!
