### DISCUSSION TITLE
Image Update Automation Frequency

### DISCUSSION THREAD

**Discussion by sbquinlan** [fluxcd/flux2#5242] [Q&A]
I'm having trouble controlling the frequency of the image update. I've configured both the image repository and the image update automation to have an interval of 30m, but I still see the image update committing sometimes only with 10s between commits. Do I misunderstand the meaning of the interval settings? 

Ultimately the motivation here is the every new build of our app's image on the master branch is too frequent. The flagger canary doesn't have time to complete: the cluster is constantly pulling down images to start the canary only to restart second later.. Maybe there's a different approach here that we should be taking rather than just increasing the interval?

```
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: my-image-repo
spec:
  provider: "aws"
  image: "path.to.ecr.repo/image"
  interval: 30m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: my-image-policy
spec:
  imageRepositoryRef:
    name: my-image-repo
  filterTags:
    pattern: '^release-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: my-image-update
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: my-git-repo
  git:
    commit:
      author:
        email: service-account@users.noreply.github.com
        name: service-account
    push:
      branch: master
  update:
    path: ./path/to/flux/resources/
```
