### DISCUSSION TITLE
Post build substitutions with numeric

### DISCUSSION THREAD

**Discussion by kyklos** [fluxcd/flux2#5290] [Q&A]
When using post build substitutions in flux 2.4.0 or flux 2.5.1 with a var that is a numeric, the reconciliation fail with `expected numeric (int or float), got string`. 

The values are:

```
  postBuild:
    substitute:
      quote: '"' # double quote var
      replicas: "1"
```
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
....
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: worker
      spec:
        replicas: ${quote}${replicas}${quote}$
        ....

```
How can I reach the goal of applying type int to the StatefulSet?

[https://github.com/fluxcd/kustomize-controller/blob/main/docs/spec/v1/kustomizations.md#post-build-substitution-of-numbers-and-booleans](https://github.com/fluxcd/kustomize-controller/blob/main/docs/spec/v1/kustomizations.md#post-build-substitution-of-numbers-and-booleans) seems not work. Any comments, please?
