### DISCUSSION TITLE
New namespace for a new team is not created

### DISCUSSION THREAD

**Discussion by erwinntt** [fluxcd/flux2#5293] [Q&A]
Hi. I follow the guide for multi-tenant Flux. https://github.com/devent/audi-flux2-multi-tenancy
I try to add the monitoring-team in a new namespace monitoring. I added in `tenants/base/monitoring-team` the kustomization.zaml. Then I add `tenants/staging/` the kustomization.yaml:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - ../base/dev-team
patches:
  - path: dev-team-patch.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../base/monitoring-team
patches:
  - path: monitoring-team-patch.yaml
```

There are no errors in Flux or in the controllers. But there is no new namespace added. If I try to run `kubectl apply -k .` manually then the namespace is created. What do I miss?

**Comment by erwinntt** [comment]
It's not possible to add multiple Kustomization with different namespaces? How would I use a namespace per team? For example, team-1 would deploy in team-1 namespace, , team-2 would deploy in team-2 namespace, etc.

**Comment by stefanprodan** [comment]
You can't have mult-doc YAML in a kustomization.yaml. You need separate dirs with a single kustomization.yaml inside, each one is an overlay.

**Comment by erwinntt** [comment]
I actually just removed the namespace in the Kustomization. Now both teams are deployed in two namespaces.

Would there be any problems to do it this way?

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/monitoring-team
  - ../base/dev-team
patches:
  - path: monitoring-team-patch.yaml
  - path: dev-team-patch.yaml

```

```
flux -n monitoring get sources git
NAME            REVISION        SUSPENDED       READY   MESSAGE
monitoring-team                 False           False   git repository is empty
```
