### DISCUSSION TITLE
Kustomization reconcilation time - timeouts and 100+ nested kustomizations

### DISCUSSION THREAD

**Discussion by msisikPG** [fluxcd/flux2#5304] [Q&A]
Hello,

We are currently using Kustomization for each namespace/user in a multi-tenant environment within our main repository. To synchronize all of them at once, we have a single main Kustomization. However, this approach requires reconciling over 100 Kustomizations simultaneously, which causes the flux reconcile command to time out after 5 minutes.

The entire reconciliation process takes approximately 5 minutes and 30 seconds. I have attempted to implement Flux Sharding to reduce this time, but I have observed that when reconciling the main Kustomization, it consistently utilizes only one of the pods for the Kustomize controller. It does not appear to distribute the workload evenly among the Kustomizations labeled with shard1 or those without, which has been confirmed through my testing.

Is there an alternative solution to this issue, or would it be more effective to split the main Kustomization into, for example, five separate Kustomizations to decrease the reconciliation time to around one minute each?

Thanks

**Comment by stefanprodan** [comment]
What's the reason for the root Kustomization to have `wait: true`? If it only applies tenant Flux Kustomizations without any workloads, then you can just disable waiting and let the others run in parallel.

**Reply by msisikPG** [reply]
Hey, I don't see any wait: true on any my kustomizations, only flag set to true is prune. Most of the repos I'm working on are private, so I don't expect you can see them. Below an example of the main kustomization I'm using



```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: name
  namespace: ns
spec:
  interval: 30m
  serviceAccountName: sa
  path: apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitrepo
 timeout: 15m
```

**Reply by stefanprodan** [reply]
If this one applies 100 other Kustomizations, since there is no `wait: true` then it should reconcile in a couple of seconds.

**Reply by msisikPG** [reply]
This is what `kubectl describe` of main kustomization gives me as the `flux reconcile ks` command timeouts after 5 mins

`  Normal  ReconciliationSucceeded  2m20s  kustomize-controller  Reconciliation finished in 5m27.193137141s, next run in 30m0s`

kubectl logs of kustomize-controller pod are a mess but I don't see anything alarming, just every kustomization reconciling, unless I should be looking for something specific.

Just to be precise - 154 kustomizations are reconciling when I reconcile the main one

**Reply by stefanprodan** [reply]
Join CNCF Slack and message me there, I need to see the whole yaml including the status of that Kustomization to help you further.

**Reply by msisikPG** [reply]
sure, messaged you there

**Reply by matheuscscp** [reply]
What does the command `kubectl get ks <name> -n <namespace> -o jsonpath='{.spec.wait}'` show?

**Reply by msisikPG** [reply]
@matheuscscp  it returns nothing.

To sum up we spend some time to figure out what might be the issue and to see any drop we used patch with concurrent-ssa.
Due to very heavy workloads (over 6000 entries into inventory) we only managed to drop around 30 seconds/1 minute from reconcile time. It also might be an indication that AKS controlplane can be slower than GKE (@stefanprodan tested it on GKE and the time dropped from 4 mins to 2 mins with --concurrent-ssa=10 - not confirmed as we didn't have mirroring workloads/cluster setup)

In the end the solution to my problem might be to split the main kustomization into several smaller ones to make the time be much more acceptable, but I will be doing more testing.


```
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent=20
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent-ssa=20
      - op: replace
        path: /spec/template/spec/volumes/0
        value:
          name: temp
          emptyDir:
            medium: Memory
    target:
      kind: Deployment
      name: kustomize-controller
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  limits:
                    cpu: 4000m
                    memory: 4Gi
```
