### DISCUSSION TITLE
patchesStrategicMerge postRenderers configuration not accepted

### DISCUSSION THREAD

**Discussion by hhue13** [fluxcd/flux2#5306] [Q&A] [answered]
I have a 3rd party Helm chart with deploys the application via our Flux HelmRelease definition. Now we have the requirement that we need to inject a container into a StatefulSet rendered by the Helm chart. So my approach is to use Helm's postRederer hook to patch the generated yaml and inject the container.

However I'm having troubes enhancing an existing HelmRelease definition with a _postRenderers_ configuration using kustomize's  _patchesStrategicMerge_ patch strategy. Based on the example [here](https://github.com/kingdonb/bootstrap-repo/blob/da8d346bedeff887d9b5b429b166e51c5ae12531/apps/openvpn/helmrelease.yaml#L26-L46) I'm trying to add the following yaml snippet to the code: 

```
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: StatefulSet
            apiVersion: apps/v1
            metadata:
              name: dx-blue-core
            spec:
              template:
                spec:
                  containers:
                    - args:
                        - infinity
                      command:
                        - sleep
                      env:
                        - name: ENVIRONMENT
                          value: dev-2
                        - name: TESTER
                          value: hhue-2
                      image: 'nginx:latest'
                      imagePullPolicy: IfNotPresent
                      name: filebeat
```

However no matter if I do a _oc edit helmrelease dxb_ or do it via ArgoCD's edit function the the code is reverted back to:
```
  postRenderers:
    - kustomize: {}
```

and I can't find any hint on what's wrong. 

Running 2.3.0 on OpenShift using the Flux operator provided by the Flux project.

What am I doing wrong? Is it because of the [deprecation of the strategic merge](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesstrategicmerge/)?

**Comment by stefanprodan** [comment, marked as answer]
See the docs here: https://fluxcd.io/flux/components/helm/helmreleases/#post-renderers

**Reply by hhue13** [reply]
I was looking at that before but mislead by the (outdated) examples. Thanks!

**Comment by hhue13** [comment]
Just in case anyone has a similar use-case to inject a pod into a Deployment/StatefulSet rendered via a Helm Chart using the postrenderer here is the pod:

```
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: add
                path: /spec/template/spec/containers/-
                value:
                  args:
                    - infinity
                  command:
                    - sleep
                  env:
                    - name: ENVIRONMENT
                      value: dev-2
                    - name: TESTER
                      value: hhue-2
                  image: 'nginx:latest'
                  imagePullPolicy: IfNotPresent
                  name: filebeat
            target:
              group: apps
              kind: StatefulSet
              name: dx-green-core
              version: v1
```
