### DISCUSSION TITLE
Helmrelease: How to refers to valuesFiles (`spec.chart`) inside the chart with an Helm OCI repository (`spec.chartRef`) ?

### DISCUSSION THREAD

**Discussion by alphayax** [fluxcd/flux2#5315] [General] [answered]
Hello there !

I want to deploy a chart by referencing values inside the chart like specified here in the documentation : https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-inside-the-chart

However, I use an OCI Repository to hold my helm chart. And I have to use `chartRef` in my helm release ( https://fluxcd.io/flux/guides/helmreleases/#using-a-chart-reference ) and I didn't find a way to refer my values files inside my chart. 

To sum up I want to do something like this (but I can't cause `chartRef` and `chart` cannot be defined at the same time) :

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-wonderful-release

spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: my-oci-repo
  chart:
    spec:
      valuesFiles:
        - values.yaml
        - values-production.yaml
...
```

**Comment by darylgraham** [comment]
I believe you put the new values files under `.spec.valuesFrom` when using a `chartRef`:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-wonderful-release

spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: my-oci-repo
valuesFrom:
  - values.yaml
  - values-production.yaml
```

The HelmRelease spec might help you out: https://fluxcd.io/flux/components/helm/api/v2/#helm.toolkit.fluxcd.io/v2.HelmReleaseSpec
