### DISCUSSION TITLE
How to patch CoreDNS to use hostPort?

### DISCUSSION THREAD

**Discussion by damdinsharav** [fluxcd/flux2#5316] [Q&A]
I am trying to run CoreDNS on hostport 53.
I've looked at this but not sure if it's possible.
https://fluxcd.io/flux/faq/#how-to-patch-coredns-and-other-pre-installed-addons

Essentially
```
spec:
      containers:
      - name: coredns
        ports:
        - containerPort: 53
          hostPort: 53
          protocol: UDP
          name: dns
        - containerPort: 53
          hostPort: 53
          protocol: TCP
          name: dns-tcp
```
