### DISCUSSION TITLE
Nested Kustomizations with dependsOn failing dry-run

### DISCUSSION THREAD

**Discussion by darylgraham** [fluxcd/flux2#5362] [Q&A]
Hi all, 

I'm trying to install the Datadog Agent and Operator. The Operator provides the CRDs that are used in the Agent manifest, so I have a "Core" Kustomization that points to an OCI source. That source image has 2 folders, one for each component, and an `overlay.yaml` that sits at the root of the image and defines a Kustomization for each component. The Agent Kustomization depends on the Operator.

After applying that to the cluster, the Core Kustomization is failing with the error message: `DatadogAgent/datadog/datadog-agent dry-run failed: no matches for kind "DatadogAgent" in version "datadoghq.com/v2alpha1"`

The only hint I have that might be causing this is that the Operator installs via a HelmRelease. The `datadog-operator` chart does not contain the CRDs directly, but has a [dependency on a second helm chart](https://github.com/DataDog/helm-charts/blob/datadog-operator-2.9.2/charts/datadog-operator/Chart.yaml). Could this be causing the issue?

Files below:

```yaml
# core-datadog.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-datadog
  namespace: flux-system
spec:
  path: "./"
  interval: 60m
  prune: true
  wait: false
  sourceRef:
    kind: OCIRepository
    name: core-datadog
```

```
# overlay.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datadog-operator
spec:
  interval: 60m0s
  wait: true
  prune: true
  force: false
  sourceRef:
    kind: OCIRepository
    name: core-datadog
  path: "./datadog-operator"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datadog-agent
spec:
  dependsOn:
    - name: datadog-operator
  interval: 60m0s 
  wait: true 
  prune: true 
  force: false
  sourceRef:
    kind: OCIRepository
    name: core-datadog
  path: "./datadog-agent"
```

**Comment by rssnyder** [comment]
@darylgraham did you ever figure this out? Facing the same thing with [metallb which also keeps its CRDs in a subchart](https://github.com/metallb/metallb/blob/main/charts/metallb/charts/crds/templates/crds.yaml).

**Reply by darylgraham** [reply]
@rssnyder Sorry for the delayed response. I ended up using `.spec.dependsOn` to force the Agent to not start installing until the Operator was reconciled completely.

**Comment by SebTardif** [comment]
@darylgraham @rssnyder

> After applying that to the cluster, the Core Kustomization is failing with:
> `DatadogAgent/datadog/datadog-agent dry-run failed: no matches for kind "DatadogAgent" in version "datadoghq.com/v2alpha1"`

`dependsOn` on the nested Flux `Kustomization` objects is not what fails here. The object that is dry-running `DatadogAgent` is `core-datadog`. Server-side apply dry-run runs against the live API, and that CRD is not registered yet. Helm has not had a chance to install it.

This is the same chicken-and-egg as [fluxcd/flux2#2282](https://github.com/fluxcd/flux2/discussions/2282). The documented fix is two (or three) **separate** Flux Kustomizations, not one parent that also builds the child manifests.

### Why the overlay does not help

`core-datadog` has `path: "./"`. If the OCI root has a `kustomization.yaml` that lists both component folders (or Flux generates a kustomization that pulls in those YAMLs), Core's build output includes:

- the HelmRelease (and maybe the operator chart render)
- the `DatadogAgent` CR
- the two Flux `Kustomization` CRs from `overlay.yaml`

kustomize-controller then dry-runs **all of that in one pass**. `spec.dependsOn` on the child CRs is ignored for that pass. Those children only order *their own* later reconciles. They do not stop Core from validating `DatadogAgent` now.

The Datadog Operator chart putting CRDs in a [dependency subchart](https://github.com/DataDog/helm-charts/blob/datadog-operator-2.9.2/charts/datadog-operator/Chart.yaml) makes it worse: Helm installs those CRDs only when the HelmRelease actually runs. A sibling `DatadogAgent` in the same apply will always dry-run-fail. MetalLB's CRD subchart is the same pattern.

### Working shape

Keep `core-datadog` only if its path contains the Flux `Kustomization` CRs and **nothing else**. Better: drop the parent and apply the two children from `flux-system`.

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datadog-operator
  namespace: flux-system
spec:
  interval: 60m
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: OCIRepository
    name: core-datadog
  path: ./datadog-operator
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: datadog-operator
      namespace: datadog
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: datadogagents.datadoghq.com
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datadog-agent
  namespace: flux-system
spec:
  dependsOn:
    - name: datadog-operator
      namespace: flux-system
  interval: 60m
  prune: true
  wait: true
  sourceRef:
    kind: OCIRepository
    name: core-datadog
  path: ./datadog-agent
```

`./datadog-operator` should contain the HelmRelease only. `./datadog-agent` should contain the `DatadogAgent` CR only. Do not list those folders as `resources:` in a root `kustomization.yaml` that Core also builds.

On the HelmRelease, make CRD install explicit:

```yaml
spec:
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
```

`wait: true` plus a health check on the CRD matters. `dependsOn` waits for the operator Kustomization `Ready` condition. Without `wait` / health checks, Ready can flip true as soon as the HelmRelease **object** is applied, before helm-controller has created `datadogagents.datadoghq.com`.

### Quick check

```bash
kubectl describe kustomization core-datadog -n flux-system
kubectl get crd datadogagents.datadoghq.com
kubectl get helmrelease -A
```

If `describe` on **core-datadog** mentions `DatadogAgent`, Core is still flattening the children. Split the paths until that name disappears from Core's inventory.

@rssnyder same split for MetalLB: one Flux Kustomization for the chart (CRDs live in the subchart), a second one for `IPAddressPool` / `L2Advertisement` with `dependsOn` and a health check on `ipaddresspools.metallb.io`.
