### DISCUSSION TITLE
Flux doesn't always assign the sops-decoded secret to my HelmChart

### DISCUSSION THREAD

**Discussion by thibaultamartin** [fluxcd/flux2#5367] [Q&A]
I tried deploying a HelmRelease that reads values from a sops-encrypted values file. Flux does decrypt the secret in the cluster, but does not patch my HelmRelease to point to the decrypted secret.

## How I deployed flux

I have deployed a single node k3s cluster on a Raspberry Pi, and I have deployed flux using the flux bootstrap command. I omitted the `--path` argument because I will only manage this cluster from this repository.

```
flux bootstrap github \
  --token-auth \
  --owner=thibaultamartin \
  --repository=myrepo \
  --branch=main \
  --personal
```

I have deployed cert-manager and a ClusterIssuer by pushing the right manifests to my GitHub repo. I have deployed a test nginx HelmRelease that worked similarly well and was properly exposed to the Internet.

Then I tried to deploy a nextcloud from https://artifacthub.io/packages/helm/nextcloud/nextcloud

The deployment works well until I try to encrypt secrets with sops.

## How I set up secrets en/decryption on my cluster

I have created an agekey on my laptop with

```
age-keygen -o age.agekey
```

And I uploaded it to my cluster via 

```
cat age.agekey |
kubectl create secret generic sops-age \
--namespace=flux-system \
--from-file=age.agekey=/dev/stdin
```

I instructed the cluster to use that secret to decrypt files with

```
flux create kustomization apps-secrets --source=flux-system --prune=true --interval=10m --decryption-provider=sops --decryption-secret=sops-age --export > secrets.yaml
```

The secrets.yaml file looks like follows, and I pushed it to my git repo

```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

## How I encrypt values for my nextcloud deployment

My repo looks like the following

```
.
├── cert-manager
│   ├── manager.yaml
│   └── staging-clusterissuer.yaml
├── flux-system
│   ├── gotk-components.yaml
│   ├── gotk-sync.yaml
│   └── kustomization.yaml
├── nextcloud
│   ├── kustomization.yaml
│   ├── kustomizeconfig.yaml
│   ├── namespace.yaml
│   ├── release.yaml
│   ├── repository.yaml
│   └── values.yaml
└── secrets
    └── secrets.yaml
```

I created a `kustomization.yaml` to generate a secret called `prod-values` from the file `values.yaml`

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
secretGenerator:
  - name: prod-values
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
```

The release.yaml file specifies that the HelmRelease should read values from the secret `prod-values`

```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 1h
  chart:
    spec:
      chart: nextcloud
      version: "6.6.10"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
  valuesFrom:
    - kind: Secret
      name: prod-values
```

And the kustomizeconfig.yaml ensures that my HelmRelease will be patched every time the values.yaml file is changed

```
nameReference:
  - kind: Secret
    version: v1
    fieldSpecs:
      - path: spec/valuesFrom/name
        kind: HelmRelease
```

Running kustomize in the nextcloud folder on my laptop I see that the kustomization works, and that the secret indeed contains the sops-encrypted values

```
[...]
kind: Secret
metadata:
  name: prod-values-8c597g5kk2
  namespace: nextcloud
type: Opaque
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
      version: 6.6.10
  interval: 1h
  valuesFrom:
  - kind: Secret
    name: prod-values-8c597g5kk2
```

Pushing everything to my cluster, I see that the HelmRelease update fails. When I do a `kubectl describe HelmRelease -n nextcloud` I can see that the HelmChart tries to access encrypted values, because it tries to access the prod-values secret that is still encrypted

```
Name:         nextcloud
Namespace:    nextcloud
Labels:       kustomize.toolkit.fluxcd.io/name=flux-system
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  <none>
API Version:  helm.toolkit.fluxcd.io/v2
Kind:         HelmRelease
Metadata:
  Creation Timestamp:  2025-05-23T15:51:33Z
  Finalizers:
    finalizers.fluxcd.io
  Generation:        1078
  Resource Version:  634447
  UID:               f719f8b1-efdb-4fb2-9fca-fa2cad05b0da
Spec:
  Chart:
    Spec:
      Chart:               nextcloud
      Reconcile Strategy:  ChartVersion
      Source Ref:
        Kind:       HelmRepository
        Name:       nextcloud
        Namespace:  nextcloud
      Version:      6.6.10
  Interval:         1h
  Values From:
    Kind:  Secret
    Name:  prod-values-8c597g5kk2
Status:
  Conditions:
    Last Transition Time:  2025-05-27T10:59:32Z
    Message:               Failed to upgrade after 1 attempt(s)
    Observed Generation:   1078
    Reason:                RetriesExceeded
    Status:                True
    Type:                  Stalled
    Last Transition Time:  2025-05-27T10:59:32Z
    Message:               Helm upgrade failed for release nextcloud/nextcloud with chart nextcloud@6.6.10: failed to create resource: Ingress.networking.k8s.io "nextcloud" is invalid: [spec.rules[0].host: Invalid value: "ENC[AES256_GCM,data:kUCNz0TWAiLN8WxoqLaX+ZGE,iv:9WqCJnv70FUMhbL0oFXH66SAbgCwQxyRUl/cHCFw7y8=,tag:yNESh2g2hbvLYOPKGppirg==,type:str]": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.tls[0].hosts[0]: Invalid value: "ENC[AES256_GCM,data:sfwYJpoQ5E6rDa9vqShuSvxm,iv:iXjhL3EVVfLqZONulD0pucYBteU+UOjOdQcscnDx8/U=,tag:FyRGEXGkfgQ+uJf+UTtkqg==,type:str]": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.tls[0].secretName: Invalid value: "ENC[AES256_GCM,data:kSHebK7Bvw17tTp8iA==,iv:dAYbtQ3QrlRmzCumlrRQaLtg86IvRRzcdK+chECNfcQ=,tag:hy85d4iiRipyK/3Icaer2g==,type:str]": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```

Any guidance about where I got it wrong would be very helpful :)
