### DISCUSSION TITLE
How to trigger ImageRepository updates only with webhook

### DISCUSSION THREAD

**Discussion by mloskot** [fluxcd/flux2#5387] [Q&A] [answered]
I've just learned this technique of how to [Trigger image updates with webhooks](https://fluxcd.io/flux/guides/image-update/#trigger-image-updates-with-webhooks), but AFAIU this notification receiver

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: podinfo
  namespace: flux-system
spec:
  resources:
    - kind: ImageRepository
      name: podinfo
```

will act as an additional trigger and the referenced `ImageRepository` will continue its business as usual of watching its target registry at configured interval, correct?

Is there any way to ensure`ImageRepository` acts only on notification?
