### DISCUSSION TITLE
Reconciliation chain

### DISCUSSION THREAD

**Discussion by Stazis555** [fluxcd/flux2#5398] [Q&A]
Hello,

Loving the Flux2, but I have few questions:
I am curious what is the reconciliation chain for the resources - specifically for the ImageUpdateAutomation. 

Topology:
- We have 1 k8s cluster
- we have ~40 service and 4 environments. Each service producing 1 GitRepository, 1 ImageRepository, 4 ImagePolicy, 4 ImageUpdateAutomation.

File structure:
<img width="324" alt="image" src="https://github.com/user-attachments/assets/9453e979-3ecd-4edc-a41b-8a3a7fee54ba" />

Flux Kustomizations (adjsutment-report is separated for an experiment):
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: image-automation
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./image-automation/services # at this path there is a kustomization.yaml file that includes all services except for the adjustment-report, which is skipped and not present in the inventory 
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m0s
  retryInterval: 2m0s
  # wait: true
  wait: false
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: adjustment-report
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./image-automation/services/adjustment-report # single service
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m0s
  retryInterval: 2m0s
  # wait: true
  wait: false
  prune: true
```
ImageUpdateAutomation references ImagePolicy by labels:
```
...
  policySelector:                                                                                                                                                                            
    matchLabels:                                                                                                                                                                             
      env: ci                                                                                                                                                                                
      service: adjustment-report 
 ....
 ---
kind: ImagePolicy                                                                                                                                                                            
metadata:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  labels:                                                                                                                                                                                    
    env: ci                                                                                                                                                                                  
    kustomize.toolkit.fluxcd.io/name: adjustment-report                                                                                                                                      
    kustomize.toolkit.fluxcd.io/namespace: flux-system                                                                                                                                       
    service: adjustment-report
...
```

What Is the issue:

When I reconcile single ImageRepository (adjustment report) - it forces reconciliation of all ImageUpdateAutomation, regardless in what flux Kustomization they are located in or what ImagePolicies are referenced. At Github discussions I saw a comment saying that chain is based on the Kustomization. But after spliting one service out of the global Kustomization, other ImageUpdateAutomations are still triggered to reconcile. So what is the reconciliation chain, and is there a way to make it more precise (to reconcile only 1 service, and 4 ImageUpdateAutomations in my case)?

Off note:
I have found `--requeque-dependency` argument for some of the controllers, but not for the ImageReflector nor the ImageAutomation, is this expected?
