### DISCUSSION TITLE
How to Trigger `HelmRepository` Reconciliation in an Image Automation Workflow?

### DISCUSSION THREAD

**Discussion by xGerTowelie** [fluxcd/flux2#5425] [Q&A]
Hi Flux team,

I'm currently using Flux with the following workflow:

* **Image automation** fetches new image tags (e.g., patch releases), updates the appropriate files in the Git repo.
* **GitLab webhook** is triggered by the push, which reconciles the `GitRepository` and the top-level `Kustomization`.
* As a result, my kustomizations (namespaces, secrets, apps) are reconciled, and updated `HelmRelease` manifests are applied.

However, the issue I'm running into is:

> 🛑 The `HelmRelease` fails to install because the associated `HelmRepository` has not fetched the latest chart index (e.g., new builds/tags from the chart source are not visible yet).

### ❓ My Question

How can I make `HelmRepository` reconciliation part of this workflow so that new chart versions are picked up *at the same time* as image updates?

---

### 💡 Current workaround ideas

1. **Lower the `HelmRepository` interval** to something like `30s`, but this feels inefficient and doesn't guarantee alignment with webhook events.
2. **Manually reconcile all `HelmRepository` resources** via a webhook or script — but this requires maintaining a list of all `HelmRepository` resources in sync with my application setup.

---

### 🧩 Suggestion: Wildcard support for Receivers

It would be incredibly useful if `Receiver` resources could support wildcards for resource names and namespaces. For example:

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: gitlab-receiver
  namespace: flux-system
spec:
  type: gitlab
  events:
    - "Push Hook"
    - "Tag Push Hook"
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      name: "*"
      namespace: "*"
```

This would allow a single webhook to reconcile **all `HelmRepository` resources**, making it easy to keep them in sync with Git pushes and image automation flows.

---

### 🙏 I'd love input on:

* Best practice for keeping Helm repo metadata fresh in GitOps flows like this
* Whether wildcard support in `Receiver.spec.resources` is feasible or planned
* Any alternative patterns for reliably syncing Helm repo index updates with Git/image automation

Thanks for your work on Flux — it's a powerful tool and this is the last piece in making our setup fully automated!
