### DISCUSSION TITLE
S3 based helm repo with source-controller

### DISCUSSION THREAD

**Discussion by kantipov** [fluxcd/flux2#572] [Q&A] [answered]
Hello,

We are using S3 for helm charts repository with https://github.com/hypnoglow/helm-s3 plugin.
Now we are trying to implement gitops with the flux2.  
I successfully created Bucket resource, but when I'm trying to create HelmRelease with source from this bucket I get an error: 
```
chart location read error: stat /tmp/flux-system-flux-system-myapp-s3-414746166/my-helm-chart: no such file or directory
```
And this is correct, there are only my-helm-chart-x.x.x.tgz files it that tmp folder, as it should be in the helm repo.

So, is there is a way to somehow use Bucket as HelmRepository?

Thank you!

**Comment by hiddeco** [comment, marked as answer]
> So, is there is a way to somehow use Bucket as HelmRepository?

Using the `Bucket` as a `HelmRepository` is not possible at present, but it is possible to refer to the `.tgz` in the Bucket, e.g.

```yaml
...
kind: HelmRelease
...omitted for brevity
spec:
  chart:
    spec:
      chart: ./my-helm-chart-1.1.0.tgz
```
