### DISCUSSION TITLE
How can I redeploy a HelmRelease which failed?

### DISCUSSION THREAD

**Discussion by frank-bee** [fluxcd/flux2#743] [Q&A] [answered]
Is there a way to set a HelmRelease to "dirty" in order to trigger manually a redeployment? Via flux CLI or via code

**Comment by frank-bee** [comment]
one way seems to be to do a `helm uninstall`

**Comment by stefanprodan** [comment]
The helm chart failed or the chart got successfully downloaded but the release failed? If the chart failed, then fixing the repository URL/auth/etc would trigger a HelmRelease install.

**Reply by frank-bee** [reply]
sorry , the Release failed ( in my case because access to the container regestry was not properly set-up yet)

**Reply by stefanprodan** [reply]
I edited the title to reflect your question :)

**Comment by hiddeco** [comment, marked as answer]
You likely want to enable retries for Helm install actions, this can be configured in your `HelmRelease` as follows:

```yaml
spec:
  install:
    remediation:
      retries: 3 # NB: setting it to `-1` results in infinite retries
```
