### DISCUSSION TITLE
How to deploy a namespace together with HelmRepository + HelmRelease?

### DISCUSSION THREAD

**Discussion by frank-bee** [fluxcd/flux2#752] [Q&A] [answered]
If I put a namespace definition plus HelmRepository + HelmRelease in one Kustomization, I get this error:

```
➜  gitops git:(master) flux get kustomizations
NAME       	READY	MESSAGE                                                                                                                                         	REVISION                                       	SUSPENDED 
flux-system	False	apply failed: Error from server (NotFound): error when creating "3c180373-0d17-4039-b8f1-e6943d36d98c.yaml": namespaces "cert-manager" not found	master/cc33bbb399933ac47a785996fe577056b0219d86	False    	
           	     	Error from server (NotFound): error when creating "3c180373-0d17-4039-b8f1-e6943d36d98c.yaml": namespaces "cert-manager" not found      
```

Do I have to create 2 Kustomizations? With some kind of explicit dependency ?

**Comment by frank-bee** [comment, marked as answer]
ah ok , I found it in the docu
```
When applying a Kustomization, you may need to make sure other resources exist before the workloads defined in your Kustomization are deployed. For example, a namespace must exist before applying resources to it.
```
https://toolkit.fluxcd.io/components/kustomize/kustomization/#kustomization-dependencies

**Reply by frank-bee** [reply]
Would I work with a dependency here ? or just splitting the deployment into 2 Kustomzations (without dependency).
What would be the typical way?

**Reply by stefanprodan** [reply]
Create a directory with:
- namespace.yaml
- helm-repository.yaml
- helm-release.yaml
- kustomization.yaml (include all 3 manifests in resources)

**Reply by frank-bee** [reply]
this is what I did ( helmrepo and helmrel I have had in the same file)

**Reply by frank-bee** [reply]
but did not work

**Reply by frank-bee** [reply]
> include all 3 manifests in resources

or do you mean 3 Kustomization's instead of 1? This I did not try

**Reply by stefanprodan** [reply]
namespaces "cert-manager" not found mens that you didn't include the namespace.yaml  in your resources

**Reply by stefanprodan** [reply]
So one Flux Kustomization that syncs the dir `cert-manager`, in that dir add the namespace, CRDs, helm-repo and helm-release

**Reply by frank-bee** [reply]
the namespace yaml is there :
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns.yaml
- traefik.yaml
- certmanager.yaml
```

**Reply by frank-bee** [reply]
ns.yaml 

```
kind: Namespace
apiVersion: v1
metadata:
  name: traefik
  labels:
    name: traefik
---    
kind: Namespace
apiVersion: v1
metadata:
  name: cert-manager
  labels:
    name: cert-manager
```

**Reply by frank-bee** [reply]
certmanager.yaml 
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  interval: 1m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: 1.1.0
  interval: 1m
  values:
    installCRDs: true
    ```
