### DISCUSSION TITLE
Helm release not getting rolled back

### DISCUSSION THREAD

**Discussion by rajpopat27** [fluxcd/flux2#855] [Q&A]
I deployed the application v0.3 and it got deployed successfully as is shown below
```
`NAME    READY   MESSAGE                                 REVISION        SUSPENDED 
prod    True    Release reconciliation succeeded        0.3.0           False    
staging True    Release reconciliation succeeded        0.3.0           False
```
Now to check the rollback capabilities of flux I changed the helm chart and introduced an error intentionally
I changed the apiVersion of Kubernetes deployment to v1 from apps/v1
 And upgraded the chart version to 0.4.0 
Now the status of release is as below
```
NAME    READY   MESSAGE                                                                                                                      REVISION        SUSPENDED 
prod    False   Helm upgrade failed: unable to recognize "": no matches for kind "Deployment" in version "v1"   0.3.0           False    
staging False   Helm upgrade failed: unable to recognize "": no matches for kind "Deployment" in version "v1"   0.3.0           False    
```
My question is shouldn't helm rollback the release to the previous working version and the status should be ready with v 0.3.0 
As the spec.upgrade.remediation.strategy is rollback
This is the helm release CRD
```
spec:
  chart:
    spec:
      chart: ./
      version: '>=0.0.0 <2.0.0'
      sourceRef:
        kind: GitRepository
        name: demo-app
      valuesFile: values-prod.yaml
  interval: 30s
  releaseName: demo-app-prod
  targetNamespace: prod
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      strategy: rollback
      remediateLastFailure: false
```
