### DISCUSSION TITLE
Gate after commit and before deployment

### DISCUSSION THREAD

**Discussion by SnoopyCoder** [fluxcd/flux2#870] [Proposals] [answered]
I wanted to understand what would be the best way to extend the GitOps toolkit with a mechanism to allow configuration of a manual approval step (event-based) or a maintenance time window (e.g. only at night between 2-5 am) allowing to involve a cluster owner before deploying an update. 

My use case: a SaaS provider (vendor company) has a marketplace where clients (other companies) can buy apps/services which shall be operated by the vendor in a K8s cluster on client's premises. Once the client buys an offer from the marketplace, an automated agent in the cloud is updating the deployment spec in a client-specific Git repo. The GitOps system within the client's K8s cluster recognizes the changed spec, retrieves the necessary artifacts and applies/deploys the changes. In case the offer is addressing regulated domain (like a classified medical product), the update must not automatic. The client needs to know upfront and have control over what is changed and when it is changed in order to keep the system up and running during critical time periods and prevent unexpected disruptions.

The commit/merge is either done by a human or by an automated business process (e.g. after a client has selected a marketplace offer to be installed on his cluster).

Ideally it would also be configurable whether the approval is requested before pulling the image from the registry or after. The latter is useful in case the images are large and should not be downloaded until the approval has been given.

One idea of @stefanprodan was to extract Flagger's manual gating feature into a dedicated controller so that any toolkit component could be gated in such a fashion. For example, when source-controller detects a new commit, instead of creating an artifact, it will call the gate hook and wait until the gate is opened. Once the gate is opened, it will generate the artifact, then kustomize/helm controllers will reconcile it. Same with image automation, the controller will not push to upsteam until a human opens the gate.

I'm not deep into the inner workings of flux and cannot really judge (yet) whether this idea would be the right approach for my use case. I hope that this discussion arouses broad interest for such a capability (which would probably also be useful in many other scenarios) and a simple and easy to solution will be found.

**Comment by stefanprodan** [comment]
## [RFC] Manual Gating

### Motivation

Flux watches sources (e.g. GitRepositories, HelmRepositories, S3-compatible Buckets, ImageRepositories) and automatically reconciles the changes onto clusters as described with Flux Kustomizations and HelmReleases.
The teams involved in the delivery process (e.g. dev, qa, sre) can decide when changes are delivered to production by reviewing and approving the proposed changes in a collaborative manner with pull request.
Once a pull request is merged onto a branch that defines the desired state of the production system, Flux kicks off the reconciliation process.

There are situations when users want to have a gating mechanism after the cluster state changes are merged in Git:

- Manual approval of container image updates (e.g. classified medical products)
- Manual approval of infrastructure upgrades (e.g. https://github.com/fluxcd/flux2/issues/959)
- Maintenance window (e.g. https://github.com/fluxcd/flux2/discussions/1004)
- Planned releases 
- No Deploy Friday

### Proposed solution

In order to support manual gating, the GitOps Toolkit could be extended with a dedicated API and controller that would allow users to define `Gate` objects and perform operations like `open` and `close`.

A `Gate` object could be referenced in sources (Buckets, Git, Helm, Image Repositories) and syncs (Kustomizations, HelmReleases, ImageUpdateAutomation) to block the reconciliation until the gate is opened.

A `Gate` can be be opened or closed by annotating the object with a timestamp or by calling a specific webhook receiver exposed by notification-controller. 

A `Gate` can be configured to automatically close or open based on a time window defined in the `Gate` spec.

The `Gate` API would replace Flagger's current [manual gating mechanism](https://docs.flagger.app/usage/webhooks#manual-gating).

### Example

Define a gate that automatically closes after 1h from the time it has been opened:

```yaml
apiVersion: gating.toolkit.fluxcd.io/v1alpha1
kind: Gate
metadata:
  name: sre-approval
  namespace: flux-system
spec:
  interval: 30s
  default: closed
  window: 1h
```

When the gate is created in-cluster, the `gating-controller` uses `spec.default` to set the `Opened` condition:

```yaml
apiVersion: gating.toolkit.fluxcd.io/v1alpha1
kind: Gate
metadata:
  name: sre-approval
  namespace: flux-system
status:
  conditions:
    - lastTransitionTime: "2021-03-26T10:09:26Z"
      message: "Gate closed by default"
      reason: ReconciliationSucceeded
      status: "False"
      type: Opened
```

While the gate is closed, all the objects that reference it will wait for an approval:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system
spec:
  gates:
    - name: sre-approval
    - name: qa-approval
status:
  conditions:
    - lastTransitionTime: "2021-03-26T10:09:26Z"
      message: "Reconciliation is waiting approval, gate 'flux-system/sre-approval' is closed."
      reason: GateClosed
      status: "False"
      type: Approved
```

The SRE team can open the gate either by annotating the gate or by calling the notification-controller webhook:

```sh
kubectl -n flux-system annotate --overwrite gate/sre-approval \
open.gate.fluxcd.io/requestedAt="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
```

The `gating-controller` extracts the ISO8601 date from the `open.gate` annotation value, sets the `requestedAt` & `resetToDefaultAt`, and opens the gate for the specified window:

```yaml
apiVersion: gating.toolkit.fluxcd.io/v1alpha1
kind: Gate
metadata:
  name: sre-approval
  namespace: flux-system
status:
  requestedAt: "2021-03-26T10:00:00Z"
  resetToDefaultAt: "2021-03-26T11:00:00Z"
  conditions:
    - lastTransitionTime: "2021-03-26T10:00:00Z"
      message: "Gate scheduled for closing at 2021-03-26T11:00:00Z"
      reason: ReconciliationSucceeded
      status: "True"
      type: Opened
```

While the gate is opened, all the objects that reference it are approved to reconcile at their configured interval.

The SRE can decide to close the gate ahead of its schedule with:

```sh
kubectl -n flux-system annotate --overwrite gate/sre-approval \
close.gate.fluxcd.io/requestedAt="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
```

The `gating-controller` extracts the ISO8601 date from the `close.gate` annotation value, compares it with the `open.gate` & `requestedAt` date and closes the gate:

```yaml
apiVersion: gating.toolkit.fluxcd.io/v1alpha1
kind: Gate
metadata:
  name: sre-approval
  namespace: flux-system
status:
  requestedAt: "2021-03-26T10:10:00Z"
  resetToDefaultAt: "2021-03-26T10:10:00Z"
  conditions:
    - lastTransitionTime: "2021-03-26T10:10:00Z"
      message: "Gate close requested"
      reason: ReconciliationSucceeded
      status: "False"
      type: Opened
```

The objects that are referencing this gate, will finish their ongoing reconciliation (if any) then pause.

To enforce a maintenance window of 24 hours, you can define a `Gate` that's opened by default:

```yaml
apiVersion: gating.toolkit.fluxcd.io/v1alpha1
kind: Gate
metadata:
  name: maintenance
  namespace: flux-system
spec:
  interval: 30s
  default: opened
  window: 24h
```

To start the maintenance window you can annotate the gate with:

```sh
kubectl -n flux-system annotate --overwrite gate/maintenance \
close.gate.fluxcd.io/requestedAt="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
```

The `gating-controller` extracts the ISO8601 date from the `close.gate` annotation value and closes the gate for the specified window:

```yaml
apiVersion: gating.toolkit.fluxcd.io/v1alpha1
kind: Gate
metadata:
  name: maintenance
  namespace: flux-system
status:
  requestedAt: "2021-03-26T10:00:00Z"
  resetToDefaultAt: "2021-03-27T10:00:00Z"
  conditions:
    - lastTransitionTime: "2021-03-26T10:00:00Z"
      message: "Gate scheduled for opening at 2021-03-27T11:00:00Z"
      reason: ReconciliationSucceeded
      status: "False"
      type: Opened
```

You could also schedule "No Deploy Fridays" with a CronJob that closes the `maintenance` gate at `0 0 * * FRI`.
