### DISCUSSION TITLE
How to generate secrets into multiple namespaces? (without .flux.yaml)

### DISCUSSION THREAD

**Discussion by IsNull** [fluxcd/flux2#872] [Q&A] [answered]
**Problem**
I'am evaluating flux v2 and planning the migration to it for a large deployment. 
We need to provide docker-registry and tls secrets into a lot of namespaces. 

While flux v2 mostly brought improvements, it discarded the ability to run arbitrary shell commands as generators via flux.yaml.

**Current solution (Flux 1)**

**.flux.yaml**
```yaml
version: 1
commandUpdated:
  generators:
    - command: bash certificates/emit-tls-certs.sh
    - command: bash registries/emit-registries.sh
```
The bash scripts read a list of target namespaces and generate secretes into all of them.

**Solution for Flux 2?**

The question is how to solve this with flux v2 / kustomize? What is the kustomize way to do this?

I'd like to avoid bringing in yet another tool such as [kubed](https://github.com/appscode/kubed) for such a basic task.

**Comment by stefanprodan** [comment, marked as answer]
Place your secret in a base dir, then include it in the overlays that contain a namespace.

**Reply by IsNull** [reply]
Alright, it works with this kustomization.yaml and repeat this for each namespace:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-namspace
resources:
- ns.yaml
- ../../../base/registries
- ../../base/certificates
```

Its a lot more boilerplate (we have a lot of namespaces) but yeah it works.
