### DISCUSSION TITLE
Full toleration objects support

### DISCUSSION THREAD

**Discussion by trillejs** [fluxcd/flux2#921] [Proposals]
Hi,

Last week tolerations keys were added:
https://github.com/fluxcd/flux2/pull/899/files#diff-c5538abd82ea734d20ae2773b15cb061ee18a5c5badc699fbe48a5a5287626baR142

However, this only allows to set tolerations by the key:
```yaml
 tolerations:
- key: yourKey
  operator: Exists
```
instead of the full toleration object as specified in the [Kubernetes documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/). Such as:
```yaml
 tolerations:
- key: yourKey
  value: your Value
  effect: yourEffect
  operator: Equal
```
