### DISCUSSION TITLE
Deploy to specific namespaces

### DISCUSSION THREAD

**Discussion by bitva77** [fluxcd/flux2#939] [Q&A] [answered]
Hi!  Using Flux2 0.7.7.

I've got Flux pointing at a repo with my apps in it and it's deploying them all into the `default` namespace.  I'd like to have a different namespace used if nothing is specific in the manifests.

Documentation isn't entirely clear but I just want to verify that I need to overwrite the `/home/controller/.kube` with a ConfigMap that specifies which namespace to use instead.  Is this correct?

```
clusters: []
contexts:
- context:
    cluster: ""
    namespace: my-cool-namespace
    user: ""
  name: default
current-context: default
kind: Config
preferences: {}
users: []
```
