### DISCUSSION TITLE
Creating Pull/Merge requests from automated updates

### DISCUSSION THREAD

**Discussion by squaremo** [fluxcd/flux2#952] [Proposals]
In the image automation design, there was a [short discussion](https://github.com/fluxcd/flux2/discussions/107#discussioncomment-96937) about creating pull/merge requests/changesets (I'll abbreviate as "PR"). This is a pretty natural extension to any kind of update automation, as noted there.

There's several ways this could work -- this discussion can serve as a venue for bashing ideas around, perhaps.

The base use case is this:

 1. I have a particular automation that I want to run
 2. When it makes a change to the git repo, I want a pull request to be opened, when can then be reviewed and merged

Within that there are variations and design questions:

 - should there be a new PR whenever there's an update?
   - you might want this if you want to step through things in order, e.g., if there's a new image a few times in short succession
   - on the other hand, these PRs will have an ordering to them, and you'd have to be careful to not just make the same change in successive PRs
   - using only one branch means you'll either stack commits in the branch, or have to force-push over the top
 - what creates the PR?
    - if the automation controller can do the basics of upserting a branch and pushing to it, other automation can take over (e.g., GitHub Actions)

**Comment by hiddeco** [comment]
From a chat with @squaremo

---

Custom resource that keeps the upstream state of a PR, and an additional (almost static) one to configure behavior.

`PullRequest`: represents the state of a pull request, as reflected from a git provider
`PullRequestPolicy`: specifies how to create, add, or queue changes
`ImageUpdateAutomation`: can refer to a `PullRequestPolicy` for where it puts commits

Reconciliation loops take care of scheduling, tracking and reacting to changes.

Reacting to webhooks (with an annotation on the `PullRequest`) could be an additional configuration option to speed things up.

We both like the idea of having configuration flavors / modes in the pull request policy, so that common sets of configuration options can be defined (e.g. waiting for the pull request to be merged before making additional changes, force overwriting, etc.).

**Reply by stefanprodan** [reply]
I would avoid dealing with Git providers APIs in the first iteration of this feature. I think we could create the branch if it doesn't exists or push to it if it does, all the PR/MR logic could be handled on the provider side.

**Reply by squaremo** [reply]
> I would avoid dealing with Git providers APIs in the first iteration

:+1:

And in support of this: a good design will work with git providers that don't have pull/merge request APIs, e.g., self-hosted git (maybe with some CI on the other side).

**Reply by stefanprodan** [reply]
This is how I see the v1alpha2 API:

```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: GitRepository
    name: flux-system
  checkout:
    branch: main
  commit:
    branch: flux-image-updates # optional (defaults to checkout.branch)
    authorEmail: bot@fluxcd.io
    authorName: flux
    messageTemplate: 'update image'
```

**Reply by hiddeco** [reply]
Two minor tweaks on top of your example @stefanprodan:

```yaml
...
  commit:
    branch: flux-image-updates # optional (defaults to checkout.branch)
    author: # optional (defaults to Flux / <some email>)
      name: Flux
      email: bot@fluxcd.io
    template: | # optional? We could at least provide some sane default
      Update images

      Images:
      {{ range .Updated.Images -}}
      - {{.}}
      {{ end -}}
```

**Reply by stefanprodan** [reply]
@hiddeco looks great, thank you!

**Comment by stefanprodan** [comment]
Combining the above ideas into a proposal for `image.toolkit.fluxcd.io/v1alpha2` or maybe `v1beta1` if we feel this is the right approach.

```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: GitRepository
    name: flux-system
  checkout:
    branch: main
  update: # optional (defaults to {strategy: Setters})
    strategy: Setters
  commit:
    author:
      name: Flux  # optional (defaults to Flux)
      email: bot@fluxcd.io
    template: | # optional (defaults to the below template)
      Update images
      {{ range .Updated.Images -}}
      - {{.}}
      {{ end -}}
  push:  # optional (defaults to {branch: checkout.branch})
    branch: flux-image-updates
``` 

Updated according to https://github.com/fluxcd/flux2/discussions/952#discussioncomment-429155
Updated again per https://github.com/fluxcd/flux2/discussions/952#discussioncomment-429848

**Reply by squaremo** [reply]
Putting the branch as a field right there could hinder broadening this out later (per https://github.com/fluxcd/flux2/discussions/952#discussioncomment-386254 or other approaches yet to come). Can you give an example of how it might be adapted to support e.g., referring to a `PullRequestPolicy`?

**Reply by stefanprodan** [reply]
If `commit.pullRequestRef` is specified then it takes precedence over `commit.branch`, similar to what we do in `GitRepositry.spec.ref`.

**Reply by squaremo** [reply]
When there's a union type I tend to put it in a field of its own. In this case, it might also make the meaning of the field within a bit more explicit.

```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1beta1
    name: flux-system
  checkout:
    branch: main
  commit:
    push:  # optional (defaults to {branch: checkout.branch})
      branch: flux-image-updates
      # or
      pullRequestPolicyRef:
        name: pileup
    # ...
```

There's a few things that aren't to do with pull requests that snuck into the examples given -- I'm not endorsing those nor rebutting them here, except to say this: I don't mind putting the commit author in its own field, but I don't like having a default for it, especially the email address. People should be obliged to supply a value for their own environment.

**Reply by stefanprodan** [reply]
Super valid points 💯 I've updated the proposal, thanks Michael.

**Reply by squaremo** [reply]
🙇 I'm happy with this as a first iteration, and as a design we can build on later.

The `push:` field is additive so can be done in v1alpha1.

The `author:` change is not backward-compatible, but is a mechanical translation away, so might have to wait for a new version. What are the consequences of making a v1alpha2 -- is it worth it for a mostly cosmetic change like that?

**Reply by stefanprodan** [reply]
Should we place `push` under spec?

```yaml
spec:
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: GitRepository
    name: flux-system
  checkout:
    branch: main
  update: 
    strategy: Setters
  commit:
    author:
      name: Flux 
      email: bot@fluxcd.io
    template: |
      Update images
      {{ range .Updated.Images -}}
      - {{.}}
      {{ end -}}
  push:
    branch: flux-image-updates
```
