### DISCUSSION TITLE
Show an example of Notification providers of Microsoft Teams

### DISCUSSION THREAD

**Discussion by hatzhang** [fluxcd/flux2#957] [Q&A]
There is only an example of Slack in the manual,  can the team give an example of Microsoft Teams as providers ?

**Comment by daveoy** [comment]
did you happen to get this to work? i have prometheus alerts hitting this webhook so i know the webhook is working, but nothing from flux.

**Comment by kingdonb** [comment]
Thanks for filing this issue. It has a lot of thumbs, and while I don't have an MS Teams account to diagnose this myself on, I guess it's probably possible to sign up for a free trial?

I opened this issue so it gets more likely follow-up: https://github.com/fluxcd/website/issues/738

**Reply by kingdonb** [reply]
There is a PR to address this now: https://github.com/fluxcd/notification-controller/pull/370

It will likely get merged soon!

**Comment by Thaval** [comment]
Still no example? I've set up a provider and alert, but see nothing in my channel and in the notification controller logs

**Reply by somtochiama** [reply]
How did you set it up?  I am working on the documentation for ms teams.
But I am curious as to what might be the difficulty in getting it set up so I can add it in. It is the same process as the slack one.
Create an incoming webhook in Ms Teams - reference the webhook in the provider resource (or in the secret ref) 
e.g 
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: msteams
  namespace: flux-system
spec:
  type: msteams
  address: <webhook-url>
```

**Reply by Thaval** [reply]
It's funny. When first trying it out, I couldn't see any messages in my channel. However, now I'm able to see the messages in the channels, hours later....
I've set it up as follows:
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: msteams
  namespace: flux-system
spec:
  type: msteams
  address: <MS_TEAM_CHANNEL_ADDRESS>
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: msteams
  namespace: flux-system
spec:
  providerRef:
    name: msteams
  eventSeverity: info
  eventSources:
  - kind: Bucket
    name: '*'
  - kind: GitRepository
    name: '*'
  - kind: Kustomization
    name: '*'
  - kind: HelmRelease
    name: '*'
  - kind: HelmChart
    name: '*'
  - kind: HelmRepository
    name: '*'
  - kind: ImageRepository
    name: '*'
  - kind: ImagePolicy
    name: '*'
  - kind: ImageUpdateAutomation
    name: '*'
```
