### DISCUSSION TITLE
notification alert - generic rule to be informed of change for all helmrelease

### DISCUSSION THREAD

**Discussion by fgrelaud** [fluxcd/flux2#958] [Q&A]
Hi, about setup notification.
I would like to create two rules for my ops team.
One is for error on gitrepository (name: flux-system) and kustomization (name: ‘*’). That’s ok.
The second for info on all HelmRepository, HelmChart and HelmRelease. For the first two, no problem because both are in the namespace flux-system. While HelmRelease depends on the namespace where it is deployed.

I would like to create one generic alert for the three. I want my ops to be informed of change for all helm releases too.
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
 name: dia-alert-info
 namespace: flux-system
spec:
 providerRef:
  name: rocket-allflux
 eventSeverity: info
 eventSources:
  - kind: HelmRepository
   name: ‘*’
  - kind: HelmChart
   name: ‘*’
  - kind: HelmRelease
   name: ‘*’
   namespace: ‘rocketchat’
  - kind: HelmRelease
   name: ‘metrics-server’
   namespace: ‘kube-system’
```
This (example) is functional but i need to register every helmrelease for every namespace.
I would like to know if like name, we can use * wildcard for namespace (a priori no :clin_d'œil: ) ?
```
  - kind: HelmRelease
   name: ‘*’
   namespace: ‘*’
```

Otherwise how can i answer to this use case ? 
Cordially,
Fabrice
