### DISCUSSION TITLE
HelmRelease and multiline values

### DISCUSSION THREAD

**Discussion by bitva77** [fluxcd/flux2#961] [Q&A]
Hi!  Does HelmRelease `spec.values` support multiline YAML?  Like

```
  values:
    service:
      port: 80
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
    environment: stage
    replicaCount: 1
    settings: | 
      {
        "Application": {
          "ApiKey": "12345",
          "ApiURL": "http://blah.com"
          }
      }
```

My tests show that it's not working but I wonder if I'm missing something.

**Comment by kingdonb** [comment]
I'll need more information about what's not working to help with this.

I just did a test of similar helmrelease with embedded multiline values, and it succeeded. I was able to get the multi-line string back out from Helm values without a problem.

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: terminal
  namespace: default
spec:
  interval: 15m
  targetNamespace: default
  storageNamespace: default
  timeout: 10m
  chart:
    spec:
      chart: terminal
      version: '0.3'
      sourceRef:
        kind: GitRepository
        name: okteto-charts
        namespace: default
      interval: 15m
  values:
    noop:
      example: |
        {
          "multiline": "string",
          "example": "json"
        }
    resources:
      requests:
        memory: "50Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "2"
    ingress:
      enabled: false
```

```
$ helm get values default-terminal
USER-SUPPLIED VALUES:
ingress:
  enabled: false
noop:
  example: |
    {
      "multiline": "string",
      "example": "json"
    }
resources:
  limits:
    cpu: "2"
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 50Mi
```

What tests did you try exactly? It is very difficult to help someone debug a reported issue without complete information, like all the versions used, what error exactly was received, and the complete steps to reproduce the described scenario. We do the best we can to make sure everyone gets helped, but it is not uncommon for reports like this one without much information to go un-responded.

(Found this thread through #1343 which is a duplicate of this one.)
