### ISSUE TITLE
Changing targetNamespace causes orphaned HelmRelease

### ISSUE THREAD

**Issue by mbrancato** [fluxcd/flux2#1005]
### Describe the bug

If after deploying a `HelmRelease` object the `spec.targetNamespace` is later changed, the flux controller will create a new deployment, etc in the newly specified namespace. However, it fails to delete the old components. If the `HelmRelease` is later deleted, Flux orphans the original deployment and does not delete it.

### To Reproduce

Steps to reproduce the behaviour:

Install a `HelmRelease`:

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myapp
  namespace: flux-system
spec:
  chart:
    spec:
      chart: myapp
      sourceRef:
        kind: HelmRepository
        name: myrepo
      version: 0.1.0
  interval: 1m0s
  targetNamespace: mynamespace
```

Commit the config to git and let Flux deploy.

Later, change the `spec.targetNamespace` value:

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myapp
  namespace: flux-system
spec:
  chart:
    spec:
      chart: myapp
      sourceRef:
        kind: HelmRepository
        name: myrepo
      version: 0.1.0
  interval: 1m0s
  targetNamespace: mynewnamespace
```

Commit to git or apply ad-hoc to the cluster.

### Expected behavior

Flux should create the deployment components in the new namespace, but it should also delete the components from the old namespace.

### Additional context

I first hit this with v0.6.1, but I upgraded to v0.9.0 and the issue still exists.

- Kubernetes version: 1.17.15
- Git provider: Github
- Container registry provider: GCR

Below please provide the output of the following commands:

```cli
flux --version
flux check
kubectl -n <namespace> get all
kubectl -n <namespace> logs deploy/source-controller
kubectl -n <namespace> logs deploy/kustomize-controller
```

```
% flux --version
flux version 0.9.0
% flux check
► checking prerequisites
✔ kubectl 1.19.3 >=1.18.0-0
✔ Kubernetes 1.17.15-gke.800 >=1.16.0-0
► checking controllers
✔ helm-controller: healthy
► ghcr.io/fluxcd/helm-controller:v0.8.0
✔ kustomize-controller: healthy
► ghcr.io/fluxcd/kustomize-controller:v0.9.1
✔ notification-controller: healthy
► ghcr.io/fluxcd/notification-controller:v0.9.0
✔ source-controller: healthy
► ghcr.io/fluxcd/source-controller:v0.9.0
✔ all checks passed
```
