### ISSUE TITLE
blank lines removed from kustomization.yaml after image update

### ISSUE THREAD

**Issue by dan-slinky-ckpd** [fluxcd/flux2#1007]
### Describe the bug

Blank lines are removed from my kustomization.yaml after an image update. In large kustomizations it useful to seperate sections for readability. 

### To Reproduce

Start with a kustomization.yaml like so:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production-my-app

namePrefix: production-

commonLabels:
  overlay: production

resources:
- namespace.yaml
- ../base

images:
- name: ghcr.io/stefanprodan/podinfo
  newTag: 5.0.0 # {"$imagepolicy": "flux-system:my-app-production:tag"}
```

After an image update, the blank lines are removed :(

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production-my-app
namePrefix: production-
commonLabels:
  overlay: production
resources:
- namespace.yaml
- ../base
images:
- name: ghcr.io/stefanprodan/podinfo
  newTag: 5.1.4 # {"$imagepolicy": "flux-system:my-app-production:tag"}
```

### Expected behavior

Maintain the blank lines.

### Additional context

flux version 0.9.0
