### ISSUE TITLE
Feature Request: Allow Alerts to specify namespace in providerRef.

### ISSUE THREAD

**Issue by MattMencel** [fluxcd/flux2#1074]
### Describe the bug

I just tried to do something like this and it's not supported at the moment.

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  summary: "cert-manager affected in (${CLUSTERNAME})"
  providerRef:
    name: slack
    namespace: flux-system ### <<--- cannot specify namespace for the providerRef
  eventSeverity: error
  eventSources:
    - kind: HelmRelease
      name: cert-manager
```

For all my system components, I'd like to create one Provider and be able to use that from Alerts created in each of the individual namespaces.

This is not a huge issue. I can create all the Alerts in the flux-system namespace where the Provider is located. It might be a nice feature to have though if it's possible. That way a Provider could be shared across multiple alerts in multiple namespaces.
