### ISSUE TITLE
Webhook receivers can't trigger resource reconciliations in other namespaces

### ISSUE THREAD

**Issue by hendrikhalkow** [fluxcd/flux2#1115]
### Describe the bug

While a GitHub or Harbor webhook receiver can trigger resource reconciliations in it's own namespace, the same doesn't work when the targeted resource is in another namespace.

### To Reproduce

Steps to reproduce the behaviour:

Works

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: github-core
spec:
  type: github
  events:
  - ping
  - push
  secretRef:
    name: github-receiver-token
  resources:
  - kind: GitRepository
    name: flux-system
```

Does not work:

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: github-core
spec:
  type: github
  events:
  - ping
  - push
  secretRef:
    name: github-receiver-token
  resources:
  - kind: GitRepository
    name: core
    namespace: foo
  - kind: GitRepository
    name: core
    namespace: bar
```

 The webhook is received, which can be indicated by a log message in the notification controller pod:

```json
{"level":"info","ts":"2021-03-18T00:17:18.392Z","logger":"event-server","msg":"Discarding event, no alerts found for the involved object","object":"/","kind":""} 
```

Unfortunately, there is no log message in no pod that can help debugging.

### Expected behavior

The webhook triggers a reconciliation for the targeted GitRepository resources in other namespaces. The same applies to Harbor, too.

### Additional context

- Kubernetes version: 1.19.6 (EKS)
- Git provider: GitHub
- Container registry provider: Harbor
