### ISSUE TITLE
helmcontroller pod can't be moved by GKE autoscaler

### ISSUE THREAD

**Issue by williambrode** [fluxcd/flux2#1166]
### Describe the bug

After load testing my GKE (Google Kubernetes Engine) cluster I noticed some nodes hadn't been deleted by the autoscaler.  Looking at the autoscaler logs I found this:

```
reason": {
            "parameters": [
              "helm-controller-xxxxxxxx-xxxxx"
            ],
            "messageId": "no.scale.down.node.pod.has.local.storage"
          },
```

Which makes sense because the GKE autoscaler won't mess with a pod with local storage unless it has the annotation that says its safe to evict:

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node

So I would like to add the annotation to the helm-controller pod so it won't interfere with the autoscaler being able to move the pod and delete an under-used node.

```
annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
```

### To Reproduce

Steps to reproduce the behaviour:

1. Create a GKE cluster and install Flux2.
2. Scale up pods to cause the autoscaler to add nodes
3. Scale down the pods and notice the node with helm-controller won't be removed. (this could happen but depends where things are scheduled)

### Expected behavior

helm-controller will not interfere with the GKE autoscaler's ability to delete a node.

### Additional context

K8s Rev: v1.18.12-gke.1210
Flux2 version: v0.8.2

**Comment by stefanprodan** [comment]
All Flux controllers map an EmptyDir to /tmp. I don’t see why would this block the eviction, do you get this message for source-controller and all the others?

**Comment by williambrode** [comment]
In the docs I linked it mentions pods with local storage as a reason why a node won't be removed.  The autoscaler logs told me why a specific node with helm-controller on it wasn't being removed - but if all of them have EmptyDir then we should add the annotation to all of them.  I'm happy to provide a PR for this if an approver agrees it would be good to add.

**Comment by nomeelnoj** [comment]
Yes, cluster autoscaler will not evict anything with an EmptyDir.  Our solution is [this](https://kyverno.io/policies/best-practices/add_safe_to_evict/) kyverno policy, though I do agree that a native flag or default within flux would be ideal.

**Comment by williambrode** [comment]
@stefanprodan if I add a PR for this would it be accepted?

**Comment by williambrode** [comment]
#1300 is a good work-around and a nice enhancement in general.  I think its still worth considering adding this by default if enough people use the autoscaler (I don't think it would hurt aside from adding unnecessary annotation for people who don't).  Looks like you would use this patch to fix it:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
```

**Comment by stefanprodan** [comment]
@williambrode a better way of doing this for all controllers is:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-flux-components
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
```

And in `kustomization.yaml`:

```yaml
patches:
- path: safe-to-evict-patch.yaml
  target:
    kind: Deployment
```
