### ISSUE TITLE
kustomize build failed: filter cannot create or delete objects

### ISSUE THREAD

**Issue by autarchprinceps** [fluxcd/flux2#1185]
### Describe the bug

Using a strategic merge yaml patch in kustomize build with delete option `$patch: delete` now causes a `kustomize build failed: filter cannot create or delete objects` exception in flux. Locally this still works with kustomize build, and it did work in older versions of flux onmodified.

### To Reproduce

Create a base folder with some kubernetes resources, reference it in a kustomization.yaml, alongside a strategic merge patch containing one resource to be omitted:

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../../products/base/prometheus/custom-resources
patchesStrategicMerge:
- patch.yaml
```
patch.yaml
```yaml
---
$patch: delete  
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube2iam.rules
  namespace: monitoring
```
And point to the folder containing the kustomization.yaml in a Kustomization Resource looking something like this:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus-custom-resources
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./patches/preprod/prometheus/custom-resources
  dependsOn:
  - name: prometheus-release
  - name: traefik-release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
```
### Expected behavior

kustomize build doesn't contain the element, even though it is present in the bases.

### Additional context

- Kubernetes version: 1.18
- Git provider: GitHub
- kustomization controller image version (broken): 0.6 - 0.10
- kustomization controller image version (definitively still working): 0.5.3
