### ISSUE TITLE
Helm tpl override issue in Flux

### ISSUE THREAD

**Issue by anthony-pastor** [fluxcd/flux2#1197]
We are using FluxCD v0.11.0.

We are trying to deploy a Helm Chart using tpl overrides with Flux:
- This version is working: https://github.com/JordanGoasdoue/golang-demo-app-reproduce-flux-error
- This one is not: https://github.com/JordanGoasdoue/golang-demo-app-reproduce-flux-error/tree/non-working-version
The error reported by Flux is:

```
flux -n jordan-golang-demo-app get hr
NAME                  	READY	MESSAGE                                                                                                                                                                                                                                          	REVISION	SUSPENDED 
jordan-golang-demo-app	False	Helm install failed: error while running post render on files: missing metadata.name in object {map[apiVersion:v1 kind:Service metadata:<nil> spec:map[ports:[map[port:80 protocol:TCP targetPort:8080]] selector:map[service:golang-demo-app]]]}
```


PS: **Both** charts are working with a _manual_ Helm install/upgrade command:

```
helm upgrade --wait --install test-golang-demo-app -n reproduce-golang-demo-app charts/golang-demo-app/ --create-namespace
Release "test-golang-demo-app" does not exist. Installing it now.
NAME: test-golang-demo-app
LAST DEPLOYED: Fri Apr  2 17:46:11 2021
NAMESPACE: reproduce-golang-demo-app
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Comment by hiddeco** [comment]
Would be very useful to also have a copy of the `HelmRelease` at hand before debugging this any further.

**Comment by anthony-pastor** [comment]
@hiddeco This was the latest test of our helmrelease definition:
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jordan-golang-demo-app
  namespace: jordan-golang-demo-app
spec:
  chart:
    spec:
      chart: charts/golang-demo-app
      sourceRef:
        namespace: flux-system
        kind: GitRepository
        name: jordan-golang-demo-app
  interval: 30s
  targetNamespace: jordan-golang-demo-app
  releaseName: jordan-golang-demo-app

```
