### ISSUE TITLE
images are not fetched

### ISSUE THREAD

**Issue by kadzielawa** [fluxcd/flux2#1248]
Hello,
thank you for your powerful tool, I really like it! great job ! it's big milestone to gitops :) 
I have problem with fluxcd2 because during creating processes which would be automatically after pushing images to ECR repository, HelmRelease is not upgrading containers however ImageUpdateAutomation works great and helm values file is updated on git repository very well.

not upgrading containers - I mean that even in repository the image is in the newest version eg.(sdd9) container is still in wrong version...
do you have any ideas what it's wrong with those files?

flux logs doesn't return nothing special... I see only that every one minute updating working.

something like values.yaml are not valid recognize by kubernetes   


```
Every 2.0s: flux get images all                                                                                                                                                                                                                                                                                            iMac-Jakub.local: Sun Apr 11 09:45:36 2021

NAME                    READY   MESSAGE                         LAST SCAN                       SUSPENDED
imagerepository/podinfo True    successful scan, found 34 tags  2021-04-11T09:44:46+02:00       False

NAME                    READY   MESSAGE                                                                                                 LATEST IMAGE
imagepolicy/podinfo     True    Latest image tag for '247635813899.dkr.ecr.eu-central-1.amazonaws.com/hey-flux' resolved to: sdd9      247635813899.dkr.ecr.eu-central-1.amazonaws.com/hey-flux:sdd9

NAME                                    READY   MESSAGE                                                         LAST RUN                        SUSPENDED
imageupdateautomation/flux-system       True    no updates made; last commit 58dd783 at 2021-04-11T07:35:46Z    2021-04-11T09:44:53+02:00       False


``` 





structure (my-private-repo)
-file1.yml
-file2.yml
-file3.yml
---eks(directory)
-------heyflux(directory)
----------values.yaml
----------Chart.yaml
----------rest chart files

file1.yml
```
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  checkout:
    branch: master
    gitRepositoryRef:
      name: podinfo
  commit:
    authorEmail: fluxcdbot@users.noreply.github.com
    authorName: fluxcdbot
    messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
  interval: 1m0s
  push:
    branch: master
  update:
    path: ./eks/heyflux
    strategy: Setters
```
file2.yml
```
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  image: 247635813899.dkr.ecr.eu-central-1.amazonaws.com/hey-flux
  interval: 1m0s
  secretRef:
    name: aws-ecr
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: podinfo
  filterTags:
    pattern: '^sdd[a-fA-F0-9]+'
  policy:
    alphabetical:
      order: asc
```

file3.yml:
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@bitbucket.org/muumerepos/my-private-repo.git
  secretRef:
    name: ssh-credentials
  ref:
    branch: master
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heyflux
  namespace: flux-system
spec:
  interval: 1m
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      chart: ./eks/heyflux
      valuesFile: ./eks/heyflux/values.yaml
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
```

eks/heyflux/values.yaml
```
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
envName: "default"
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
muumeerp:
  image:
    repository: 247635813899.dkr.ecr.eu-central-1.amazonaws.com/hey-flux
    tag: sdd9 # {"$imagepolicy": "flux-system:podinfo:tag"}
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
```

**Comment by martijnjanssen** [comment]
I'm having the same issue, but with a deployment. My ImagePolicy is able to retrieve the correct image and tag, but the image itself is not updated for some reason. The ImageUpdateAutomation doesn't see any updates and constantly has the `no updates made` message. My Deployment also has a `strategy` which is set to `Recreate`, but the `RollingUpdate` gives the same result. Something is wrong, but I'm unsure what. If needed I can attach my files here too. Otherwise I'll just see what the response to kadzielawa is.

**Comment by kadzielawa** [comment]
@martijnjanssen please take a look on the discussion which we have here:
https://github.com/fluxcd/flux2/discussions/1249

**Comment by squaremo** [comment]
@martijnjanssen It sounds like you have a different problem. As I parse the discussion here, the automated updates are working (writing to git) but do not have an effect when synced to the cluster. I think your problem is that the automation does not make a commit, is that right?

**Comment by martijnjanssen** [comment]
Yes, I will take a look at it again later, maybe I can spot the issue. If not I can file an issue or start a discussion.

It does indeed not make a commit, however, it does detect the newer image. Anyway, I'll stop bumping this issue :wink:

**Comment by sanjvij** [comment]
@squaremo Did you managed to fix your problem? I am having the same issue whereby the containers are not getting updated with new image. In my case the flux is not even updating the deployment yaml with newer version. However when I run get image policy, I can see that flux is able to identify that a newer version is available. I have logged my issue here . Will appreciate any help or pointers [https://github.com/fluxcd/flux2/issues/1274]

**Comment by nomeelnoj** [comment]
I *think* i might know what is going on here, if I understand the issue correctly. 

You are having Flux update the `values.yaml` file in your helm chart when a new image is pushed to ECR, which is working properly, but then you are expecting flux to redeploy your helm chart into the cluster.  From what I understand, this is not going to work.  In order for flux to see changes in a helm chart that is hosted in a git repository, the version of that chart in `Chart.yaml` needs to change. This is happening because fluxv2 pulls helm charts from git as versioned artifacts based on the version you have defined in `Chart.yaml`, versus using git metadata as it did in fluxv1.


Suggest a slightly different approach:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heyflux
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./eks/heyflux
      valuesFile: ./eks/heyflux/values.yaml
      values: # Not sure if you can provide both valuesFile and values...haven't tested this
        muumeerp:
          image:
            tag: sdd9 # {"$imagepolicy": "flux-system:podinfo:tag"}
# ... removed for brevity
```
As I understand it, Flux will commit back to your repo into `file3.yaml` due to the marker above whenever you push an image to ECR that matches your `ImagePolicy` definition.  When the git repository is updated with the new image tag, the `source-controller` will pick up the changes and sync them into your cluster, passing off to the `kustomize-controller` which will update the `HelmRelease` object with the new tag from your `file3.yaml`, and then the `helm-controller` will run the equivalent of a `helm upgrade`.  That may not be 100% correct, but I believe this is all due to the version in your `Chart.yaml` not getting updated, per the docs here: https://toolkit.fluxcd.io/guides/faq-migration/#helm-integration (see the bottom row in the table).
