### ISSUE TITLE
--with-souce not work if kustomization and source in diffrent namespace.

### ISSUE THREAD

**Issue by eisig** [fluxcd/flux2#1283]
--with-souce  not work if kustomization and source in diffrent namespace.

reconcile with command: 
`flux reconcile ks test-apps  -n  test --with-source`
output:
`gitrepositories.source.toolkit.fluxcd.io "apps" not found`

here is my config:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: test-apps
  namespace: test
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: flux-system
  path: ./apps/test/
  prune: true
  validation: client
```

## version info
flux version 0.12.1
k8s version: v1.19.9
