### ISSUE TITLE
Cannot create configmaps greather than 262144

### ISSUE THREAD

**Issue by kubealex** [fluxcd/flux2#1301]
I've seen a similar issue, linked to another one but still no real answer to the problem.

The case is creating a configmap with grafana dashboards in it, ending with:
The ConfigMap "istio-dashboards" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

Is there a way to overcome this issue?

Thank you

**Comment by kubealex** [comment]
as far as I see, I guess this kind of resources should be just kept out of gitops, period,

**Comment by stefanprodan** [comment]
Istio should bundle the dashboards inside the Grafana image like Linkerd does https://github.com/linkerd/linkerd2/blob/main/grafana/Dockerfile

There is no thing we can do in Flux.

**Comment by kubealex** [comment]
> Istio should bundle the dashboards inside the Grafana image like Linkerd does https://github.com/linkerd/linkerd2/blob/main/grafana/Dockerfile
> 
> There is nothing we can do in Flux.

My bad, forgot about the limit. 
The resource was a custom one, nothing to do with 'stock' istio dashboard. Thank you!

**Comment by ViBiOh** [comment]
I have same issue but for the `VirtualService` configuration. We have many redirection rules (10k) and we end up having the same message about length.

We tried the `force` option in Kustomization but with no success.

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-manifests-large
  namespace: flux-system
spec:
  interval: 10m
  path: ./staging-1
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: kube-manifests-large
  validation: client
```

It works when running locally `kubectl create/replace -f my-file.yaml` so it's not a Kubernetes limitations but an `apply` limitations. Is it possible to allow choosing the "apply" mode for a given resource (at the Kustomization level or on the ressource with annotations) ?
