### ISSUE TITLE
Reconciler error failed to download repository index: 401 Unauthorized

### ISSUE THREAD

**Issue by eddie1030** [fluxcd/flux2#1317]
### Describe the bug

I followed the Getting started guide and tried to configure a private HelmRepository using Harbor v1.10. I paid special attetion to docs about the toolkit [components](https://toolkit.fluxcd.io/components/source/helmrepositories/#condition-reasons) and create a secret per the example.  

However, when I push the resources to the flux repository, I get the Unauthorized error.

### To Reproduce

I tested 2 types of Harbor accounts ("robot" account and standard user account) with a secret like this:
```
apiVersion: v1
kind: Secret
metadata:
  name: harbor
  namespace: flux-system
type: Opaque
data:
  username: <base64 username>
  password:  <base64 password>
```
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: example.com
  namespace: flux-system
spec:
  interval: 1m
  url: https://harbor.example.com/chartrepo/example
  secretRef:
    name: harbor
    namespace: flux-system
```
I tried to login to the chart repo with the same accounts from my cli, which worked, and should rule out faulty credentials.

### Expected behavior

I expected flux to deploy charts from my private repo.
