### ISSUE TITLE
Kustomization generator is not generating individual kustomizations

### ISSUE THREAD

**Issue by rverma-nsl** [fluxcd/flux2#1368]
### Describe the bug

With kustomization controllers flux can generate kustomization(k8s) files. It would be nice flux can also generate kustomizations(flux-crd) too(along with sourceignore)

This would be helpful in multi-cluster scenario like 

<img width="377" alt="Screenshot 2021-04-24 at 9 45 00 AM" src="https://user-images.githubusercontent.com/80032502/115946884-caaf1200-a4e1-11eb-92e8-85973040c0ca.png">

If we want to sync all the infrastructure components to a specific tenant we have two options of creating kustomizations.

1. Create a single kustomization which syncs all the components in 1 shot. The disadvantage of this is that its not an itemwise sync and is all/none strategy. We should be okay to sync 9 components if one of 10 is incorrect. I understand that behind the scene if there is no formatting error it will work same, but issue comes when there is a single formatting error in any one single file.

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: platform
  namespace: platform
spec:
  interval: 10m0s
  path: ./infrastructure/k8
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
```

2. Create list of kustomizations for each component in each tenant. The primary issue is its not following DRY and we need to copy paste this in all the tenants. If we push them in base, then the issue comes is what if in a cluster I don't need some of them, and then we started putting patch: delete, which is again not a clear way.
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: platform
  namespace: platform
spec:
  interval: 10m0s
  path: ./infrastructure/k8/cluster-autoscaler
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: platform
  namespace: platform
spec:
  interval: 10m0s
  path: ./infrastructure/k8/external-dns
....
```

To take advantage of 2nd approach we propose to  have kustomization as generation strategy as 
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: platform
  namespace: platform
spec:
  interval: 10m0s
  generator: recursive
  path: ./infrastructure/k8/external-dns
  sourceignore: |
         kyverno
```
Once this is done we can have the simplicity of 1st approach and flexibility of 2nd approach and still follow DRY.

### Expected behavior

Flux should be able to generate multiple kustomizations

**Comment by stefanprodan** [comment]
> We should be okay to sync 9 components if one of 10 is incorrect. I understand that behind the scene if there is no formatting error it will work same, but issue comes when there is a single formatting error in any one single file.

Malformed manifests shouldn’t make it onto the branch that’s synced by Flux. We offer OpenAPI schemas so you can validate all your YAMLs locally and in CI with kubeval or similar tools.

Static validation scripts:
- Single tenant repo: https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/scripts/validate.sh
- Multi tenant repo: https://github.com/fluxcd/flux2-multi-tenancy/blob/main/scripts/validate.sh

**Comment by rverma-nsl** [comment]
PR validation is based on the fact that we are only talking about environments > dev. What if we want to use flux for dev/feature environment. I can see that flux has preview environments on the roadmap, which is supposed to be sync within preview clusters.
What I understand that validation scripts are just to validate things but those can still be merged and if merged flux sync would still broke.

Also this would give some parity to Argo's App of Apps schematics, since argo define every kustomize/helmrelease as an app.
Users can then provide dependencies too define the order of bootstrapping the apps. 

Anyways the point is that how can we provide a better experience and more visibility, how can this be integrated with upcoming flux ui better.

**Comment by kingdonb** [comment]
> What I understand that validation scripts are just to validate things but those can still be merged and if merged flux sync would still broke.

You can add protected branches and merge checks, which we do recommend. The guiding principle here is that, contributors to your cluster should be verifying changes before applying them to the cluster, and if the commit contains something wrong in it, then it should not be applied at all.

The same principle applies here; if a merge check that completes quickly can tell you in advance that the commit will break the environment, don't merge it. Either prevent this condition through policy or through careful attention to the merge checks, which again do not take long to complete. If you don't want to put your own separate pre-merge checks there, you leave it up to Flux's own validation routines, (and that's where the deploy will stop then, because Kustomize controller also validates.)

I understand what you're saying, you don't want to bother with merge checks if it's only dev; that's a compromise you can accept, and the result is that things will sometimes break.

If you really don't want validation failures to break anything in a particular environment, you can also set `validate: none` in the spec. But be prepared to struggle with failures that could have been identified and prevented early. Silent failures are much harder to diagnose than straightforward validation failures that come with an error about what went wrong.

Dependency ordering is provided in Kustomization and HelmRelease as `dependsOn` in the spec.

**Comment by rverma-nsl** [comment]
Still it lacks the fact that there is no clear visibility on the sync schematics of individual apps. Take a look at argo schematics

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      items:
      - path: nginx
      - path: external-dns
      - path: falco
  template:
    metadata:
      name: '{{path}}'
    spec:
      project: kube-system
      source:
        repoURL: https://github.com/argoproj-labs/applicationset.git
        targetRevision: HEAD
        path: {{cluster}}
      destination:
        namespace: kube-system
```
Here it generate the argo resource Application which argo uses to track its gitops deployment (a combination of GitRepository+Kustomization). 

The item object here is an object which can be modelled in different way. This can be used to even replace overlays with postbuild hook. 

Infact I would even recommend to have dependsOn substituted by annotation based on the resource. The equivalent of argo is the sync-wave https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/

The idea is not to make flux as argo but I believe the builtin simplicity of flux can always be feature rich.
