### ISSUE TITLE
Git submodules fetch from public repo fails if SSH key is used for private repo

### ISSUE THREAD

**Issue by gaima8** [fluxcd/flux2#1417]
### Describe the bug

I appear to be affected by exactly this issue reported to ArgoCD; https://github.com/argoproj/argo-workflows/issues/1498

Git submodules fetch from public repo fails if SSH key is used for private repo

### To Reproduce

Exactly as in the above issue, but in Flux2 syntax.

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: whatever
  namespace: whereever
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: gitrepository-secret
  url: ssh://user@someserver/auser/arepo.git
  recurseSubmodules: true
```

Where auser/arepo.git contains a submodule from a public github repo, and `gitrepository-secret` contains an SSH keypair & known_hosts for user@someserver.

If the submodule is https://github.com the GitRepository fails with
>unable to clone 'ssh://user@someserver/auser/arepo.git', error: invalid auth method

If the submodule is ssh://git@github.com/ then the GitRepository fails with
>unable to clone 'ssh://user@someserver/auser/arepo.git', error: ssh: handshake failed: knownhosts: key is unknown

### Additional context

Below please provide the output of the following commands:

```cli
mike@lena ~ $ flux --version
flux version 0.13.4
mike@lena ~ $ flux check
► checking prerequisites
✔ kubectl 1.20.2 >=1.18.0-0
✔ Kubernetes 1.20.6 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.10.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.9.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.9.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.12.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.13.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.12.2
✔ all checks passed
mike@lena ~ $ 
```

This was the same in 0.11.0, I upgraded to 0.13.4 this evening to confirm the issue was still there.
