### ISSUE TITLE
HelmChart is not reconciled when updating GitRepository

### ISSUE THREAD

**Issue by ViBiOh** [fluxcd/flux2#1427]
### Describe the bug

We have a `GitRepository` that stores our Helm Chart, we use this chart in a `HelmRelease`. When updating the chart, the `GitRepository` is correctly fetched/reconciled, the HelmRelease is reconciled too, but the `HelmChart` is not updated.

Don't know if it's related, but the chart modifications are in a `files/` folder (not the `templates`). 

```
kubectl describe gitrepository --namespace=infra app
> Last Update Time      2021-05-19T08:11:37Z

kubectl describe helmchart --namespace=infra infra-app
> Last Update Time      2021-05-18T15:00:55Z

kubectl describe helmrelease --namespace=infra app
> Last Update Time        2021-05-19T07:30:06Z
```

### To Reproduce

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: app
  namespace: infra
spec:
  url: ssh://git@github.com/org/repo
  interval: 10m
  ref:
    branch: mybranch
  secretRef:
    name: github

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app
  namespace: infra
spec:
  interval: 60m
  chart:
    spec:
      chart: infra/app
      sourceRef:
        kind: GitRepository
        name: app
```

Here the structure of the folder in the GitRepository

```
> tree
.
├── Chart.yaml
├── README.md
├── files
│   ├── custom-httpd.conf.tpl
│   └── vhosts.conf.tpl
├── release-notes.md
├── templates
│   ├── configmap.yaml
```

### Expected behavior

HelmChart is reconciliated before HelmRelease and/or a CLI option for reconciliating HelmChart manually.

### Additional context

```cli
flux version 0.13.4
```
