### ISSUE TITLE
KUBECONFIG env-var does not respect config merging when using multiple files

### ISSUE THREAD

**Issue by OneCricketeer** [fluxcd/flux2#1434]
### Describe the bug

Looked at #472 and #637 , but those don't address the issue I'm seeing

### To Reproduce

Started some k3d clusters - [steps here](https://github.com/kubernetes-sigs/kubefed/issues/1412)

Define a minimal kubeconfig with only the values I want to override

<details><summary>Minimal kubeconfig (click to expand)</summary>
<p>

```yml
apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://k3d-ctrl-server-0:6443
  name: k3d-ctrl
- cluster:
    server: https://k3d-worker-server-0:6443
  name: k3d-worker
current-context: k3d-ctrl
```

</p>
</details>

And mount the kubeconfig I use on the host, which looks like this 

<details><summary>Host kubeconfig (click to expand)</summary>
<p>

```yml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://0.0.0.0:60507
  name: k3d-ctrl
contexts:
- context:
    cluster: k3d-ctrl
    user: admin@k3d-ctrl
  name: k3d-ctrl
current-context: k3d-ctrl
kind: Config
preferences: {}
users:
- name: admin@k3d-ctrl
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

</p>
(there is also a `k3d-worker` context and user, but can be ignored for this issue, IMO)
</details>

I start the `flux-cli` image on the network of my cluster(s)

```sh
$ docker run --rm -ti --network=k3d-bridge --entrypoint=ash \
    -v $HOME/.kube/config:/root/.kube/config \
    -v $PWD/kubectl-e2e-docker.yml:/tmp/kubeconfig.yml \
    -e KUBECONFIG='/tmp/kubeconfig.yml:/root/.kube/config' \
    fluxcd/flux-cli:v0.13.4
```

Here's what kubectl says the api server should be (kubectl commands work as expected), minus [one issue](https://github.com/kubernetes/kubectl/issues/1054) (I have CA data that isn't passed though)

```
/ # kubectl config view --minify
apiVersion: v1
clusters:
- cluster:
    server: https://k3d-ctrl-server-0:6443
  name: k3d-ctrl
contexts:
- context:
    cluster: k3d-ctrl
    user: admin@k3d-ctrl
  name: k3d-ctrl
current-context: k3d-ctrl
kind: Config
preferences: {}
users:
- name: admin@k3d-ctrl
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

Here's the error from flux

```
/ # flux --kubeconfig /root/.kube/config check --pre
► checking prerequisites
✔ kubectl 1.20.4 >=1.18.0-0
✗ Kubernetes API call failed: Get "https://0.0.0.0:60507/version?timeout=32s": dial tcp 0.0.0.0:60507: connect: connection refused
```

And the variable is set to use multiple files

```
# env
HOME=/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBECONFIG=/tmp/kubeconfig.yml:/root/.kube/config
```

### Expected behavior

`flux` should respect the config merging logic as described [in the documentation](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#merging-kubeconfig-files)

Secondly, does `flux` offer `--insecure-skip-tls-verify` equivalent?

### Additional context

- Kubernetes version: 1.19
- Git provider: N/A
- Container registry provider: N/A

Below please provide the output of the following commands:

```cli
/ # flux --version
flux version 0.13.4
/ # flux check
► checking prerequisites
✔ kubectl 1.20.4 >=1.18.0-0
✗ Kubernetes API call failed: Get "https://0.0.0.0:60507/version?timeout=32s": dial tcp 0.0.0.0:60507: connect: connection refused
► checking controllers
```
