### ISSUE TITLE
Flux2 kustomization reconcile failing when it has to pull base from another repository

### ISSUE THREAD

**Issue by sujithvs74** [fluxcd/flux2#1445]
### Describe the bug

I am trying to setup multi-tenancy for my development team. I have three repository setup cluster-level repo, dev-team-repo and component-base-repo. 

In cluster level repo I have setup dev-team-repo as source and configured path for application kustomization like below. 

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
      name: dev-team-repo
       namespace: dev-ns
spec:
    interval: 1m0s
    url: ssh://git@gitlab.com/svs/dev-deployments.git
    ref:
        branch: main
    secretRef:
        name: flux-secret
```

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
      name: go-hellow-world
       namespace: dev-ns
spec:
     interval: 10m0s
     path: "./clusters/dev-cluster/go-hellow-world" 
     prune: true
     sourceRef:
          kind: GitRepository
           name: dev-team-repo
      validation: none
```

I have another kustomization.yaml file inside _/clusters/dev-cluster/go-hellow-world_ to pull base from component-base-repo.

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ssh://git@gitlab.com/svs/hellow-world-base.git/base/go-hellow-world?ref=v3.15.6

patchesStrategicMerge:
- service.yaml
```
When flux2 runs kustomize reconcile, it is failing with below error. 

```
* accumulateFile error: "accumulating resources from 'ssh://git@gitlab.com/svs/hellow-world-base.git/base/go-hellow-world?ref=v3.15.6': open /tmp/node-exporter455681601/clusters/dev-cluster/go-hellow-world/ssh://git@gitlab.com/svs/hellow-world-base.git/base/go-hellow-world?ref=v3.15.6: no such file or directory"
* loader.New error: "hit 27s timeout running '/usr/bin/git fetch --depth=1 origin v3.15.6'"
```

### Additional context

- Kubernetes version: 1.20.2
- Git provider: gitlab

Below please provide the output of the following commands:

```cli
flux --version - 0.13.4

flux check
► checking prerequisites
✔ kubectl 1.18.0 >=1.18.0-0
✔ Kubernetes 1.20.2 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.9.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.10.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.11.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.10.0
✔ all checks passed

```

**Comment by stefanprodan** [comment]
Move the service patch inside the Flux Kustomization https://fluxcd.io/docs/components/kustomize/kustomization/#strategic-merge-patches, there is no need to use kustomize remote bases over ssh.

**Comment by sujithvs74** [comment]
@stefanprodan You are right, I can move patch inside Flux Kustomization. Still for applying patch I need to to pull remote base over SSH.

**Comment by stefanprodan** [comment]
> Still for applying patch I need to pull remote base over SSH.

Create a GitRepository for it.

**Comment by sujithvs74** [comment]
I already have repository for that, `ssh://git@gitlab.com/svs/hellow-world-base.git/base/go-hellow-world?ref=v3.15.6`. But with some reason flux not able to pull repo contents. Is this an expected behavior?

**Comment by stefanprodan** [comment]
I mean Flux GitRepository.

**Comment by sujithvs74** [comment]
As mentioned in the description, I am trying to implement multi-tenancy for my cluster as described in https://github.com/fluxcd/flux2-multi-tenancy/. Only difference is tenant application base is on another repository which is this https://github.com/fluxcd/flux2-multi-tenancy/blob/dev-team/production/kustomization.yaml.

**Comment by stefanprodan** [comment]
In the multi-tenancy example there is no ssh remote base, you need to use Flux GitRepository as kustomize-controller doesn't know how to handle SSH auth.

**Comment by stefanprodan** [comment]
Something like this:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
      name: hellow-world
       namespace: dev-ns
spec:
    interval: 1m0s
    url: ssh://git@gitlab.com/svs/hellow-world-base.git
    ref:
        tag: v3.15.6
    secretRef:
        name: hellow-world-secret
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
      name: hellow-world
       namespace: dev-ns
spec:
  interval: 10m0s
  path: "./base/go-hellow-world" 
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-team-repo
  validation: client
  patchesStrategicMerge:
  - apiVersion: v1
    kind: Service
    metadata:
      name: go-hellow-world
    spec:
      type: ClusterIP
```

You should also set `Kustomization.spec.serviceAccountName`, other patch options here: https://fluxcd.io/docs/components/kustomize/kustomization/#override-kustomize-config
