### ISSUE TITLE
Update documentation about exposing notification-controller webhook receiver port

### ISSUE THREAD

**Issue by br0ziliy** [fluxcd/flux2#1448]
This is not a bug, but rather a documentation issue.

Both `flux install` and `flux bootstrap` create couple of NetworkPolicy objects in the Flux namespace (this behaviour is controlled with `--network-policy` which defaults to `true`), which deny incoming network access to the toolkit controllers from other namespaces, as well as outside worlds, and only allow incoming connections from other namespaces to the `notification-controller` Pod.
Here are the policies being created:

```
$ kubectl -n flux-system get networkpolicy
NAME                          POD-SELECTOR                  AGE
allow-egress                  <none>                        19d
allow-scraping                <none>                        19d
allow-webhooks                app=notification-controller   19d
```

The documentation in https://fluxcd.io/docs/guides/webhook-receivers/#expose-the-webhook-receiver recommends creating `LoadBalancer` Service to expose `notification-controller` webhook receiver port, but does not mention that cluster operator should also add a NetworkPolicy that allows access to `notification-controller` from the outside networks (if Flux was installed with `--network-policy=true`, which is the default), something along these lines:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-webhooks-from-outside
  namespace: flux-system
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.0/8 # CHANGE THIS DEPENDING ON YOUR NETWORK LAYOUT
  podSelector:
    matchLabels:
      app: notification-controller
  policyTypes:
  - Ingress
```  

If cluster operator decides to use `Ingress` instead of `LoadBalancer` to expose `notification-controller` webhook port, and Ingress Controller is hosted within the same cluster - no additional NetworkPolicies needed, existing `allow-webhooks` policy allows cross-namespace communication already.

I suggest the "Expose the webhook receiver" paragraph is updated with Ingress example, and a note on `LoadBalancer` example with the sample NetworkPolicy. Also "receiver" in the title is a bit ambiguous with the `Receiver` Custom Resource name, would "Expose the notification-controller webhook port" be more clear? 

Also, "Public ingress considerations" in https://fluxcd.io/docs/components/notification/receiver/#public-ingress-considerations can be linked back to the "Expose the webhook receiver" paragraph, for clarity.

### Additional context

- Kubernetes version: v1.19.9

```cli
$ flux --version
flux version 0.13.3
$ flux check
► checking prerequisites
✗ flux 0.13.3 <0.13.4 (new version is available, please upgrade)
✔ kubectl 1.18.3 >=1.18.0-0
✔ Kubernetes 1.19.9 >=1.16.0-0
► checking controllers
✗ helm-controller: deployment not ready
► ghcr.io/fluxcd/helm-controller:v0.10.0
✗ image-automation-controller: deployment not ready
► ghcr.io/fluxcd/image-automation-controller:v0.9.1
✗ image-reflector-controller: deployment not ready
► ghcr.io/fluxcd/image-reflector-controller:v0.9.1
✗ kustomize-controller: deployment not ready
► ghcr.io/fluxcd/kustomize-controller:v0.12.0
✗ notification-controller: deployment not ready
► ghcr.io/fluxcd/notification-controller:v0.13.0
✗ source-controller: deployment not ready
► ghcr.io/fluxcd/source-controller:v0.12.1
✔ all checks passed
```

**Comment by stefanprodan** [comment]
@br0ziliy our default network policies do allow traffic from ingress controllers, check out [allow-webhooks.yaml](https://github.com/fluxcd/flux2/blob/main/manifests/policies/allow-webhooks.yaml).

**Comment by br0ziliy** [comment]
> @br0ziliy our default network policies do allow traffic from ingress controllers, check out [allow-webhooks.yaml](https://github.com/fluxcd/flux2/blob/main/manifests/policies/allow-webhooks.yaml).

For ingress controllers - yes, but if cluster operator wants to make notification-controller webhook port accessible with `Service` of type `LoadBalancer` (as suggested in Flux documentation) - this won't work as policies do not allow outside networks access to that port, and documentation does not cover this; this is what this report is about, as stated in the issue description.

**Comment by kingdonb** [comment]
If this is truly just a documentation issue, I suggest letting fluxcd/website#359 supersede this issue since that is where docs live now.

I opened fluxcd/website#358 to start to address this, but it doesn't tackle the problem that LoadBalancer as described doesn't seem to work out of the box with network policies enabled.

We should either describe the adjustments required to make the NetworkPolicy work with LoadBalancer, or point at resources (a visual editor for NetworkPolicy resources? something else?) to get users up to speed about how to modify these objects appropriately.

**Comment by stefanprodan** [comment]
@kingdonb I would inverse the order, Ingress first, then a 2nd sub-section with the LB service and the a network policy example provided by br0ziliy

**Comment by kingdonb** [comment]
We've had feedback from someone in a slack thread:
https://cloud-native.slack.com/archives/CLAJ40HV3/p1631809511167300

that there is more needed to know than what we have documented, especially if you are on a VPC-networked CNI

For example, from the thread:
```
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    - ipBlock:
        cidr: 172.44.0.0/16 # VPC CIDR
```

I owe this issue a follow-up with some further clarification in the notification controller guide. I'd like to make sure this is covered as well. (Assigned to myself so this does not get left behind again.)

**Comment by stefanprodan** [comment]
@kingdonb what's the status with this issue?

**Comment by kingdonb** [comment]
It looks like the main bit that's outstanding is some guidance about how to handle cert-manager for the webhook receiver.

I see that, at a high level, my own test cluster doesn't have the networkpolicy enabled at all, and this might have been a reason why. The telltale sign is `504 Gateway Time-out` and users reported back here, that it can be worked around through an additional policy that selects the http-01 solver ingress by label, to allow:

https://github.com/fluxcd/flux2/issues/2240#issuecomment-1527996010

I think this only affects users who have their Receivers in the `flux-system` namespace. I will have a review of the docs, and get back to this thread (flagging it for today's Bug Scrub) – if there's a feature we should add in response to the docs issue, maybe we can avoid another weird knob in the docs.

We could add a note right after: https://fluxcd.io/flux/guides/webhook-receivers/#expose-the-webhook-receiver

and suggest the networkpolicy for users there? I have to go enable networkpolicy on my own clusters first so I can test it.

**Comment by kingdonb** [comment]
Haven't lost track of this. It should get attention next week.

**Comment by JVMartin** [comment]
All of our teams struggle with this when setting up webhook receivers for real-time updates.

The cert-manager acme http DNS verifying pod that spins up to broker the SSL certificate in the `flux-system` namespace is unable to communicate with the ingress controller in order to receive the LetsEncrypt requests.

I believe @kingdonb advised us a couple years ago to do this, not sure if this is still the best solution, but if anyone else needs to get around this issue this is how we do it:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- patch: |-
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: flux-system
      namespace: flux-system
    spec:
      interval: 2m0s
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-egress
      namespace: flux-system
    $patch: delete
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-scraping
      namespace: flux-system
    $patch: delete
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-webhooks
      namespace: flux-system
    $patch: delete
```
