### ISSUE TITLE
Kustomize: Inline cloud provider decryption configuration

### ISSUE THREAD

**Issue by travisgroth** [fluxcd/flux2#1478]
Currently users can specify arbitrary PGP or age decryption secrets for any given `kustomize` resource.   However, when using sops with cloud providers, the KMS credentials are tied to the kustomize-controller itself by using ENV vars, service accounts, etc.  

It think it would be useful to allow any secret provider and credentials to be specified within a `kustomize` resource, so that various cloud kms key usage schemes can be supported without requiring additional kustomize-controllers being deployed for each key.  Mock example:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-secrets
  namespace: default
spec:
  interval: 5m
  path: "./"
  sourceRef:
    kind: GitRepository
    name: team-1-repo
  decryption:
    provider: gcpkms
    secretRef:
      name: gcp-kms-sa
```

Is the strict 1:1 nature of cloud kms credentials<->kustomize-controller intentional or is there opportunity for a feature here?
