### ISSUE TITLE
[Enhancement] Implement explicit security contexts for pods and containers

### ISSUE THREAD

**Issue by Cellebyte** [fluxcd/flux2#1500]
# Examples containerSecurity which could be implemented.

Should that be a standard implementation in the release manifests from fluxctl?

```yaml
...
      containers:
      - name: <name>
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
...
```

# Examples podSecurity

```yaml
...
 securityContext:
    runAsUser: <uid>
    fsGroup: <gid>
...
```

Currently is uses the standard allow everything policy which is not great and also breaks the securityPolicies of our cluster.
The best way would be to have it upstream to ensure that it is correctly implemented. We can patch it on our own but if greater changes happen to how flux gets deployed it will brick.

_Originally posted by @Cellebyte in https://github.com/fluxcd/flux2/discussions/1483_
