### ISSUE TITLE
Breaking changes in Flux due to Kustomize v4

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#1522]
Starting with version 0.15.0, Flux and its controllers have been upgraded to Kustomize v4. While Kustomize v4 comes with many improvements and bug fixes, it introduces a couple of breaking changes.

### Remote archives 

Due to the removal of `hashicorp/go-getter` from Kustomize v4, the set of URLs accepted by Kustomize in the `resources` filed is reduced to file system paths, URLs to plain YAMLs and values compatible with `git clone`.

This means you can no longer use resources from archives (zip, tgz, etc).

No longer works:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/rook/rook/archive/refs/heads/master.zip//rook-master/cluster/examples/kubernetes/ceph/crds.yaml
```

Works:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/rook/rook/v1.6.0/cluster/examples/kubernetes/ceph/crds.yaml
```

### Non-string YAML keys

Due to a [bug](https://github.com/kubernetes-sigs/kustomize/issues/3446) in Kustomize v4, if you have **non-string keys** in your manifests, the controller will fail to build the final manifest.

The non-string keys bug affects Helm release like the nginx-ingress one, for example:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
spec:
  values:
    tcp:
      2222: "app/server:2222"
```

The above will fail with `{}{2222:"app/server:2222:2222"}}}}: json: unsupported type: map[interface {}]interface {}`.

To fix this issue, you have to make the YAML keys into strings, e.g.:

```yaml
  values:
    tcp:
      "2222": "app/server:2222"
```

### Duplicate YAML keys

Unlike Helm, the Kustomize yaml parser (kyaml) does not accept duplicate keys, while Helm drops the duplicates, Kustomize errors out. This impacts helm-controller as it uses `kustomize/kyaml` to label objects reconciled by a `HelmRelease`.

For example, a chart that adds the `app.kubernetes.io/name` more than once, will result in a HelmRelease install failure:

```
map[string]interface {}(nil): yaml: unmarshal errors:
line 21: mapping key "app.kubernetes.io/name" already defined at line 20
```

### YAML formatting

Due to a [bug](https://github.com/kubernetes-sigs/kustomize/issues/3605) in Kustomize v4 that makes the [image-automation-controller](https://github.com/fluxcd/image-automation-controller) crash when YAMLs contain non-ASCII characters, we had to update the underlying go-yaml package to fix the panics. 

The `gopkg.in/yaml.v3` update means that the indentation style changed:

From:

```yaml
spec:
  containers:
  - name: one
    image: image1:v1.0.0 # {"$imagepolicy": "automation-ns:policy1"}
  - name: two
    image: image2:v1.0.0 # {"$imagepolicy": "automation-ns:policy2"}
```

To:

```yaml
spec:
  containers:
    - name: one
      image: image1:v1.0.0 # {"$imagepolicy": "automation-ns:policy1"}
    - name: two
      image: image2:v1.0.0 # {"$imagepolicy": "automation-ns:policy2"}
```

**Comment by onedr0p** [comment]
> Due to the removal of hashicorp/go-getter from Kustomize v4, the set of URLs accepted by Kustomize in the resources filed is reduced to only file system paths or values compatible with git clone. This means you can no longer use resources from archives (zip, tgz, etc).

Does this mean standard URLs do not work anymore? e.g.

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  grafana_dashboard: "1"
resources:
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.8.0/manifests/grafana-dashboardDefinitions.yaml
```

**Comment by stefanprodan** [comment]
@onedr0p I've update the issue with examples, let me know if it answerers your question.

**Comment by metasim** [comment]
> Due to the removal of hashicorp/go-getter from Kustomize v4...

🤦‍♂️

**Comment by IsNull** [comment]
I am pretty shocked how easily the kustomize crowd breaks established standards, given how dogmatic they are about their templating philosophy.  On that note, maybe flux should not include such massive breaking changes in _minor_ releases. 

From an operational perspective, this is a nightmare. I guess we will stay on flux 0.14.0 for some time until this has settled.

@stefanprodan Thank you for pushing back on this and clearly documenting the impacts. 👍

**Comment by stefanprodan** [comment]
> maybe flux should not include such massive breaking changes in minor releases.

You may not be aware, but flux2 has no GA release so we can't bump the major version before going GA aka 2.0.0. Every minor release of flux2 could come with breaking changes, we try to communicate those ahead of time, in this case with Kustomize v4, I documented the whole thing months ago here: https://github.com/fluxcd/flux2/issues/918

**Comment by BertelBB** [comment]
I have a question about an issue I am having with Kustomize and I don't know if it is related to these changes or not. I have never used Kustomize until I migrated over to Flux v2.

I am refactoring the `bootstrap` repo to make use of Kustomize's `overlay` and `dependsOn` features. One Kustomization is failing and I get this error.
```
kustomize build failed: accumulating resources: accumulation err='accumulating resources from './notifications/dev': read /tmp/flux191219993/flux/notifications/dev: is a directory': recursed merging from path '/tmp/flux191219993/flux/notifications/dev': may not add resource with an already registered id: notification.toolkit.fluxcd.io_v1beta1_Provider|flux-system|slack
```

Running kustomize build on the directory in question yields no errors, so I'm a bit confused why it's failing when Flux does it... But like I say, I am very new to Kustomize and might be missing something trivial. I've tried to search for similar issues but haven't found anything of use.

I can go into further details here or create a separate issue for this. One thing I haven't tried is downgrading Flux to 0.14, will try that next and see if the issue persists.

**Comment by stefanprodan** [comment]
@BertelBB that error tells you that you’ve got a duplicate provider definition called slack.

**Comment by BertelBB** [comment]
I tried bootstrapping with Flux@0.14.2 and the issue still persists.

@stefanprodan yes, that is what I suspected. But AFAICT, I don't have two provider definitions. I have one definition and another one which is the overlay for the `dev` cluster...

A little more info on what I am trying to achieve. I am following this guide: <https://github.com/fluxcd/flux2-kustomize-helm-example>

I have this file structure, with two Kustomizations; `flux` and `infrastructure`. `flux` depends on `infrastructure`.
 
![image](https://user-images.githubusercontent.com/5678412/123429501-8eb62d00-d5b6-11eb-8958-967b5dde9508.png)

The idea is to define the Slack notification provider in the base, but have each cluster inject which Slack channel to use.

`flux/notifications/dev/kustomization` 
```yaml
namespace: flux-system
resources:
- ../base/slack
patchesStrategicMerge:
- slack.provider.yaml
```

`flux/notifications/base/slack/slack.provider.yaml`
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
spec:
  secretRef:
    name: slack-url
  type: slack

```
`flux/notifications/dev/slack.provider.yaml`
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
spec:
  channel: dev-channel

```

**Comment by stefanprodan** [comment]
@BertelBB add the namespace to the patch

**Comment by BertelBB** [comment]
@stefanprodan then I get a new error...
```
no matches for Id notification.toolkit.fluxcd.io_v1beta1_Provider|flux-system|slack; failed to find unique target for patch notification.toolkit.fluxcd.io_v1beta1_Provider|slack
```

I also get this error if I run `kustomize build flux/notifications/dev`.

If I remove `namespace: flux-system` from `flux/notifications/dev/kustomization.yaml` and instead add it to all the resources explicitly, then I get the previous error message again...

```
may not add resource with an already registered id: notification.toolkit.fluxcd.io_v1beta1_Provider|flux-system|slack
```

The weird thing is that when I run `kustomize build dev/notifications/dev` on this configuration, it succeeds.

**Comment by stefanprodan** [comment]
@BertelBB make sure to use kustomize v4.1.3, your `base/slack/kustomization.yaml` should also set the namespace like you did in `dev/kustomization.yaml`

**Comment by BertelBB** [comment]
```bash
$ kustomize version
{Version:4.1.3 GitCommit:$Format:%H$ BuildDate:2021-06-02T11:13:36Z GoOs:linux GoArch:amd64}
```

I've tried setting the namespace in both `kustomization.yaml`, as well as in all resources defined in `flux/notifications` and the issue still persists.

My thinking is, if `kustomize build` succeeds locally for all of my kustomize overlays, then the issue is probably not with the individual overlays but perhaps with the combination of kustomizations in my repo? Does that make sense?

**Comment by BertelBB** [comment]
If I change the file structure such that `slack.provider.yaml` is only defined in the `dev` overlay, i.e. the only thing coming from `base/slack` is the Alert resource.
![image](https://user-images.githubusercontent.com/5678412/123442153-1eaea380-d5c4-11eb-9c48-444c9632d1c9.png)

Then I get this error
```
may not add resource with an already registered id: notification.toolkit.fluxcd.io_v1beta1_Alert|flux-system|flux-errors
```

### base/slack/flux-errors.alert.yaml
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: flux-errors
  namespace: flux-system
spec:
  eventSeverity: error
  eventSources:
  - kind: GitRepository
    name: '*'
  - kind: HelmRepository
    name: '*'
  - kind: Kustomization
    name: '*'
  - kind: ImageUpdateAutomation
    name: '*'
  - kind: ImageRepository
    name: '*'
  - kind: ImagePolicy
    name: '*'
  providerRef:
    name: slack
```

### base/slack/kustomization.yaml
```yaml
namespace: flux-system
resources:
- flux-errors.alert.yaml
```

### dev/kustomization.yaml
```yaml
namespace: flux-system
resources:
- slack-url.secret.yaml
- slack.provider.yaml
- ../base/slack
```

### dev/slack-url.secret.yaml
```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: ...
  template:
    data: null
    metadata:
      name: slack-url
      namespace: flux-system
```

### dev/slack.provider.yaml
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  channel: dev-channel
  secretRef:
    name: slack-url
  type: slack
```

**Comment by BertelBB** [comment]
So I figured it out. It's just my lack of understanding of how Kustomize works...
My `flux` Kustomization resource for the `dev` cluster was reconciling the whole `./flux` directory. When I think about it, it's quite obvious that won't work :sweat_smile:
Thank you though and sorry for the interruption.

Should I just delete my comments since this has nothing to do with the upgrade and is quite a lot of clutter?

**Comment by stefanprodan** [comment]
@BertelBB yes let’s clean this up please

**Comment by messiahUA** [comment]
I've faced with "Non-string YAML keys" problem, but in the context of helm itself, more specifically a helm template has integer key. As far as I understand this is because of post-rendering kustomization, so basically helm-controller renders helm templates and then runs kustomization - am I correct?

**Comment by hiddeco** [comment]
The helm-controller does run a default Kustomize plugin to be able to trace resources that originate from a `HelmRelease` by adding labels.

The impact of this may however been underestimated with the recent changes to Kustomize v4, and we may want to provide some sort of configuration flag to disable this default behavior for charts it does not cope with.

**Comment by or-shachar** [comment]
I stumbled upon the "Duplicate YAML keys" problem in one of my releases. Fixing it is rather easy. 

I'm a little concerned about how to avoid this kind of failure in the future. 
What is the test that needs to be added to CI so it would break before merge to master/develop

I found a very awkward way to do it, but I wonder if someone found something more sustainable...

**Comment by akselleirv** [comment]
@or-shachar I also have the same issue. How did you workaround this?
I need to update `serviceMonitor` key in the the values for the HelmRelease. Orginally I did it this way:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: log
spec:
  interval: 1h
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    serviceMonitor:
      enabled: true
      labels:
        release: mon

```
But now I get the "Duplicate YAML keys" error...

**Comment by masterkain** [comment]
I have two initContainers in my deployment and I cannot proceed, is this bug related?

```
 {"level":"error","ts":"2021-09-09T22:35:34.794Z","logger":"controller.helmrelease","msg":"Reconciler error","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"sendy","namespace":"sendy","error":"Helm upgrade failed: error while running post render on
│  files: map[string]interface {}(nil): yaml: unmarshal errors:\n  line 93: mapping key \"name\" already defined at line 91\n  line 107: mapping key \"name\" already defined at line 105"}
```

```yaml
      initContainers:
        - name: create-csvs
          image: "{{ .Values.image }}"
          command:
          - mkdir
          - -p
          - /var/www/html/sendy/uploads/csvs
          volumeMounts:
          - name: data
            mountPath: /var/www/html/sendy/uploads
            name: sendy-data
        - name: take-data-dir-ownership
          image: "{{ .Values.image }}"
          command:
          - chown
          - -R
          - www-data:www-data
          - /var/www/html/sendy/uploads
          volumeMounts:
          - name: data
            mountPath: /var/www/html/sendy/uploads
            name: sendy-data
```

**Comment by endrec** [comment]
@masterkain:
> is this bug related?

No.
That is an issue with your yaml, you are defining `volumeMounts` names twice for both initcontainers.
```
          volumeMounts:
          - name: data #### Here...
            mountPath: /var/www/html/sendy/uploads
            name: sendy-data #### ... and here.
```

**Comment by masterkain** [comment]
thanks @endrec, that definitely slipped under my tired eyes 👍

**Comment by jeinwag** [comment]
Looks like this is fixed in upstream now: kubernetes-sigs/kustomize#3675

**Comment by onedr0p** [comment]
Can't wait for the update to this newer version of kustomize in Flux, anchor support is amazing.

**Comment by jeinwag** [comment]
And there's alreay a new kustomize release which includes the fix: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.4.0

**Comment by davisford** [comment]
@stefanprodan if i use this version of kustomize:

```sh
➜ kustomize version
{Version:kustomize/v4.4.0 GitCommit:63ec6bdb3d737a7c66901828c5743656c49b60e1 BuildDate:2021-09-27T16:13:36Z GoOs:darwin GoArch:amd64}
```

I do _not_ get the dupe key error.  But with current flux v0.20.1, I am seeing the dupe key error on an ingress-nginx spec.

```
➜ flux get kustomization ingress-nginx
NAME         	READY	MESSAGE                                                                                                                                                                                                                                                                                                          	REVISION                                     	SUSPENDED
ingress-nginx	False	Deployment/ingress-nginx/ingress-nginx-controller dry-run failed, error: failed to create manager for existing fields: failed to convert new object (apps/v1, Kind=Deployment) to smd typed: .spec.template.spec.containers[name="controller"].ports: duplicate entries for key [containerPort=80,protocol="TCP"]	main/5f7e56ed5328481798d7feff415036e220d32178	False
```

However, the section of the spec it is complaining about does not have a dupe entry:

```yaml
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: tohttps
              containerPort: 2443
              protocol: TCP
            - name: webhook
              containerPort: 8443
              protocol: TCP
```

It _used_ to.  Before it was specified like this:

```yaml
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort:  80
              protocol: TCP
            - name: tohttps
              containerPort: 2443
              protocol: TCP
            - name: webhook
              containerPort: 8443
              protocol: TCP
```

...but I pushed a commit to change the port for `https` from `80` to `443`, then did `flux get kustomization ingress-nginx --with-source`, but it is still complaining about the same dupe key entry.  Could it be cached?

We're getting umpteen million alerts in a slack chan on this, so I'm trying to make it go away.

**Comment by jerem0808** [comment]
Hi @stefanprodan,
We are affected with the duplicate keys issue. We are actually using Helm charts from another company we work with. Would there be a way maybe to to ignore those errors?

**Comment by stefanprodan** [comment]
> Would there be a way maybe to to ignore those errors?

No there is no workaround, I think soon Helm itself will error out the same as Flux once they update their yaml processor package.

**Comment by marianobilli** [comment]
> I stumbled upon the "Duplicate YAML keys" problem in one of my releases. Fixing it is rather easy.
> 
> I'm a little concerned about how to avoid this kind of failure in the future. What is the test that needs to be added to CI so it would break before merge to master/develop
> 
> I found a very awkward way to do it, but I wonder if someone found something more sustainable...

and what is your way?

**Comment by JVMartin** [comment]
I really need a workaround for charts that have lots of duplicate keys in them, like GitLab.

@or-shachar can you share your method please? @marianobilli have you found a workaround?

I guess one option might be to do a Kustomize PostRenderer to patch all of the effected yamls, but that would take AGES.

**Comment by marianobilli** [comment]
> I really need a workaround for charts that have lots of duplicate keys in them, like GitLab.
> 
> @or-shachar can you share your method please? @marianobilli have you found a workaround?
> 
> I guess one option might be to do a Kustomize PostRenderer to patch all of the effected yamls, but that would take AGES.
> 
> EDIT: Tried fixing with Kustomize PostRenderer and it doesn't seem to work, it errors out before even attempting the patch.

I had to fix the helm template with the duplicate keys.

**Comment by onedr0p** [comment]
I just upgraded to v0.29.0 and noticed that a ksutomization like this is no longer supported, is this safe to assume now?

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/rancher/system-upgrade-controller?ref=v0.9.1
```

I looked into it a bit more and discvoered this PR https://github.com/kubernetes-sigs/kustomize/pull/4453 which makes it seem like the below would work

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - git::https://github.com/rancher/system-upgrade-controller?ref=v0.9.1
```

But I am getting an error:

```
kustomize build failed: accumulating resources: accumulation err='accumulating resources from 'system-upgrade': read /tmp/apps2651878754/cluster/apps/system-upgrade: is a directory': recursed accumulation of path '/tmp/apps2651878754/cluster/apps/system-upgrade': accumulating resources: accumulation err='accumulating resources from 'system-upgrade-controller': read /tmp/apps2651878754/cluster/apps/system-upgrade/system-upgrade-controller: is a directory': recursed accumulation of path '/tmp/apps2651878754/cluster/apps/system-upgrade/system-upgrade-controller': accumulating resources: accumulation err='accumulating resources from 'git::https://github.com/rancher/system-upgrade-controller?ref=v0.9.1': open /tmp/apps2651878754/cluster/apps/system-upgrade/system-upgrade-controller/git::https:/github.com/rancher/system-upgrade-controller?ref=v0.9.1: no such file or directory': fs-security-constraint abs /tmp/kustomize-356128291: path '/tmp/kustomize-356128291' is not in or below '/tmp/apps2651878754'
```
