### ISSUE TITLE
Migration from Flux V1 to V2 with minimal kubeconfig does not work

### ISSUE THREAD

**Issue by stylius** [fluxcd/flux2#1527]
### Describe the bug

Flux V1 installation with helm like that:
```
helm3 upgrade --install paas-infrastructure fluxcd/flux \\
--version 1.4.1 \\
--namespace paas-infrastructure \\
--set git.url=REPO.git \\
--set git.secretName=flux-git-deploy \\
--set git.user=flux \\
--set git.branch=lab-gke \\
--set syncGarbageCollection.enabled=true \\
--set clusterRole.create=true \\
--set kube.config='\\{apiVersion: v1\\, clusters: \\[\\]\\, contexts: \\[\\{context: \\{cluster: ""\\, namespace: "paas-infrastructure"\\, user: ""\\}\\, name: ""\\}\\]\\, current-context: ""\\, kind: Config\\, preferences: \\{\\}\\, users: \\[\\]\\}' \\
--debug
```
This allows Flux to synchronise manifests without "metadata.namespace" set to the `paas-infrastructure` namespace and to any other namespace if metadata.namespace is set. 

We can't do the same using Flux V2. Here's the kustomization used:
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: paas-infrastructure
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: lab-gke
  secretRef:
    name: flux-system
  url: ssh://REPO.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: paas-infrastructure
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: paas-infrastructure
  kubeConfig:
    secretRef:
      name: fluxv2-paas-infrastructure-kubeconfig
  validation: none
```
fluxv2-paas-infrastructure-kubeconfig secret contains the same kubeconfig as in Flux V1.
We intentionally skipped the `targetNamespace` parameter as it forcefully overrides any manifest, instead of acting as just default. Such configuration expects self-contained (complete) kubeconfig file and not minimal set that just overrides a specific parameter (e.g. namespace). Moreover it is either kubeConfig that is used or ServiceAccount and not both, unlike Flux V1.

Using self-contained kubeconfigs causes huge overhead to maintain kubeconfig files up to date in multiple clusters.

How can use a default namespace for specific repo, without enforcing it using `targetNamespace` parameter to override all?
