### ISSUE TITLE
Helm Chart installation failed due to post renderer yaml unmarshal error

### ISSUE THREAD

**Issue by Jimmy-Newtron** [fluxcd/flux2#1556]
### Describe the bug

We were used to deploy the [ErpNext Helm Chart](https://github.com/frappe/helm/tree/master/erpnext) using Flux.

Since the Flux upgrade to version 0.15.3 we are facing the following error message:

```
Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 12: mapping key "app.kubernetes.io/name" already defined at line 8
```

PS: we are able to deploy the chart with a manual Helm install/upgrade command

### Root cause

The helm chart is generating the follow yaml resource:

```yaml
# Source: erpnext/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-erpnext-redis
  labels:
    helm.sh/chart: erpnext-3.2.8
    app.kubernetes.io/name: erpnext
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "v13.5.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: erpnext-redis
```

source code: https://github.com/frappe/helm/blob/c27ba7d38687a9a67331ab555e369b16c79685b5/erpnext/templates/serviceaccount.yaml#L15

The double presence of the label `app.kubernetes.io/name` is the most likely root cause

### Reproduce the issue

Simply follow the ErpNext guide

https://helm.erpnext.com/

### Expected behavior

As we are able to deploy the chart with a manual Helm install/upgrade command, we expect that Flux can deploy the chart without the mentioned issue

### Additional context

- Kubernetes version: 1.19
- Git provider: Gitlab private repo
- Container registry provider: docker hub

Below please provide the output of the following commands:

```cli
$ flux --version
flux version 0.15.3
$ flux check
► checking prerequisites
✔ kubectl 1.19.0 >=1.18.0-0
✔ Kubernetes 1.19.7 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.13.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.15.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.2
✔ all checks passed
```
