### ISSUE TITLE
Loki pod fails to start if installed using HelmRelease: Secret modified by Flux

### ISSUE THREAD

**Issue by fl42** [fluxcd/flux2#1592]
### Describe the bug

Flux modifies Secret on helm release install

### To Reproduce

Install Loki using Helm chart:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
```

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "2.5.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
```

From [values file](https://github.com/grafana/helm-charts/blob/main/charts/loki/values.yaml#L74):
```yaml
...
schema_config:
  configs:
  - from: 2020-10-24
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h
...
```

But looking in loki config using `kubectl -n loki get secrets loki -o yaml`
```yaml
...
schema_config:
  configs:
  - from: "2020-10-24T00:00:00Z"
    index:
      period: 24h
      prefix: index_
    object_store: filesystem
    schema: v11
    store: boltdb-shipper
...
```

Then loki pod fails to start with:
```
failed parsing config: /etc/loki/loki.yaml: parsing time "2020-10-24T00:00:00Z": extra text: "T00:00:00Z"
```

Manually updating `from` key to `2020-10-24` in the Secret solves the issue.

The problem occurred after updating Flux to version 0.16.0

### Expected behavior

Date format in `from` key should not be modified by Flux.

### Additional context

- Kubernetes version: 1.20.6
- Git provider: Gitlab
- Container registry provider: N/A

Below please provide the output of the following commands:

```cli
$ flux --version
flux version 0.16.0
```

```cli
$ flux check
► checking prerequisites
✔ kubectl 1.20.4 >=1.18.0-0
✔ Kubernetes 1.20.6 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.14.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.11.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.13.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.15.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.3
✔ all checks passed
```
