### ISSUE TITLE
flux bootstrap disables GPG commit verification

### ISSUE THREAD

**Issue by fl42** [fluxcd/flux2#1615]
### Describe the bug

I enabled GPG commit verification by adding `verify` to the default `GitRepository` in `gotk-sync.yaml`:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1h0m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: ssh://xxx
  verify:
    mode: head
    secretRef:
      name: flux-gpg-pubkeys
```

It works as expected.

However running `flux bootstrap` again ([should be idempotent](https://fluxcd.io/docs/installation/#bootstrap)) removes the `verify` part.

:warning: That may be considered as a security risk as users may not be aware that GPG commit verification is disabled when running `flux bootstrap` (e.g., on upgrade)

### To Reproduce

1. Run `flux bootstrap`
2. Add `flux-gpg-pubkeys` Secret (if needed)
3. Add `verify` key to `GitRepository` object in `gotk-sync.yaml`

```yaml
verify:
  mode: head
  secretRef:
    name: flux-gpg-pubkeys
```

4.  Run

```cli
kubectl -n flux-system get gitrepositories.source.toolkit.fluxcd.io flux-system -o yaml
```
:heavy_check_mark: `verify` key is present
5. Run `flux bootstrap` again
6. Run
```cli
kubectl -n flux-system get gitrepositories.source.toolkit.fluxcd.io flux-system -o yaml
```
:warning: `verify` key is not present anymore (you may also check commit issued by flux)

### Expected behavior

GPG commit verification should not be disabled on `flux bootstrap`.
At least a strong warning message should be raised.
Ideally a --verify parameter to configure GPG commit verification should be added to flux CLI.

### Additional context

- Kubernetes version: 1.21.1
- Git provider: 0.16.1
- Container registry provider: N/A

Below please provide the output of the following commands:

```cli
flux --version
flux version 0.16.1
```

```cli
flux check
► checking prerequisites
✔ kubectl 1.20.4 >=1.18.0-0
✔ Kubernetes 1.21.1 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.14.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.11.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.13.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.15.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.3
✔ all checks passed
```
