### ISSUE TITLE
Support encrypted envs files in secretGenerator 

### ISSUE THREAD

**Issue by aivanov-citc** [fluxcd/flux2#1646]
Thanks for the ability to decrypt files!
According to the article https://fluxcd.io/docs/components/kustomize/kustomization/#kustomize-secretgenerator, decryption works only with regular files.
```yaml
secretGenerator:
 - name: token
   files:
   - token=token.encrypted
```
In our work, we also use ENV files in addition to regular files. Please add this functionality
```yaml
secretGenerator:
 - name: list-parameters
   envs:
   - list-parameters.env=list-parameters.encrypted
```
