### ISSUE TITLE
Feature request: `flux render {kustomization|helmrelease}`

### ISSUE THREAD

**Issue by metasim** [fluxcd/flux2#1652]
Debugging configuration examples would benefit with a new `render` subcommand to `flux` whereby the fully rendered manifests defined by a `Kustomization` or `HelmRelease` object are output. You'd run 

    flux render kustomization my-app

and get the streamed manifests as they were (our would have been except for an error) applied to K8S.

**Comment by stefanprodan** [comment]
The CLI can’t decrypt secrets so it can’t render the manifests the same way kustomize-controller does it. Also due to security reasons, the controller doesn’t stores the multi-doc YAML nor does it expose an HTTP API as it would bypass Kubernetes RBAC. While I agree that a render command would be useful for debugging, the security implications are quite serious.

**Comment by xeor** [comment]
I am testing flux2 these days as well, and I actually got here now just to make an issue just like this.
Flux just works it seams, but there is a lack of local tooling to render and maybe even apply what flux would have done.

Is the only option now to do a git add, commit and push?

There should be a way to apply your cluster without git, or at least render it as @metasim suggest..
Maybe the flux cli can offload some of the work to the kustomize-controller? Or maybe there already is a way using kubectl cp and exec?

**Comment by anthr76** [comment]
Secrets aside this can still useful. Chewing on ideas.... Can't we just leverage the RBAC provided by the kubeconfig?

**Comment by metasim** [comment]
@stefanprodan 

> The CLI can’t decrypt secrets so it can’t render the manifests the same way kustomize-controller does it. Also due to security reasons, the controller doesn’t stores the multi-doc YAML nor does it expose an HTTP API as it would bypass Kubernetes RBAC. While I agree that a render command would be useful for debugging, the security implications are quite serious.


I was thinking about this as more of a server-side rendering operation. I hadn't considered that the person invoking `flux render` might not have the same permissions as the `kustomize-controller` (still not sure how that chain of authz would play out), but could imagine the secrets being easily redacted.

**Comment by hiddeco** [comment]
Server-side rendering would mean that both the helm-controller and kustomize-controller would have to expose some endpoint to be able to receive and respond to requests, which is not a light introduction from an architectural point of view.

In my opinion, it would be better if we sometime in the future factor out the bits and pieces that deal with the collection and composition of the dependencies that are required to e.g. run the Kustomization build, or a Helm release dry-run. The CLI can then use these bits to run the same actions with the user's local credentials to provide the rendered YAMLs.

**Comment by arash-bizcover** [comment]
I also thought about how to do **local development** with FluxCD GitOps model. But for me even the helm kustomize render wouldn't be enough, as there are other things which might go wrong.

Then I realized the best way I'd do local development is by using a local k3s cluster with the same structure on non-prod and prod clusters. 
📖 I do this:

- Create a local K3S cluster 
- Create a new branch `dev` on the same repository I want to have my clusters
- Flux bootstrap the local cluster with the `dev` branch
- Make the `dev` structure exactly the same as the `master` 

With this approach my changes to `dev` will get deployed to my local k3s cluster by FluxDB and because I'm using the exact same folder/base structure I can trust it a lot more. 
➕  when I'm happy with my change I just PR from `dev` to `master`

**dev** branch:
![image](https://user-images.githubusercontent.com/62287461/130390574-40d9d9d4-fa19-4757-add3-c72577ede320.png)

**master** branch: 
![image](https://user-images.githubusercontent.com/62287461/130390656-56e08c30-7c12-416f-b638-151d957fb9be.png)

**Comment by jbilliau-rcd** [comment]
@stefanprodan  Can we not provide for this with an override argument or something? And what does secrets have to do with this? In our environment, we are using the GOTK to distribute changes to nonprod and prod environments, over 150+ clusters. While I can use `kustomize build` to see my kustomize files, I have no idea if the "final output yaml" is at all correct, which is what is most important. Seeing the kustomize files is pointless, I can see them already in my git repo. 

If it's at all possible, even if that means some sort of argument or flag to "accept security implications", this functionality would be huge for validating and trusting the final config being pushed to countless servers.

**Comment by kingdonb** [comment]
@jbilliau-rcd The `flux build` and `flux diff` subcommands are new since this issue was filed. I think they already address the feature request.

Have you seen both of these features? I agree that `kustomize build` output is a bit too far away from the live production cluster, but `flux build` is different:

https://fluxcd.io/docs/cmd/flux_build/

```
flux build kustomization ks --path=./target-path
```

This will get you the "final output YAML" including any modifications made by Flux resources that might patch or envsubst from configmap or secret sources. Please check these features out and let us know if they solve your use cases.

The `flux diff` command in particular is really useful, because it allows you to see just what Flux will change, and also has some provisions for masking secrets so they would not be shown in the output if a secret is what will be changing.

https://fluxcd.io/docs/cmd/flux_diff/

**Comment by kingdonb** [comment]
I think this issue is mostly closed by `flux diff` and `flux build`, which was released in January:

https://fluxcd.io/blog/2022/01/january-update/

The one remaining feature I see which is not already implemented by this is to diff a HelmRelease.

**Comment by dfallert-rcd** [comment]
> I think this issue is mostly closed by `flux diff` and `flux build`, which was released in January:

both `diff` and `build` do not render the full manifest. For instance, if you create a `Kustomization` object part of the `kustomize.toolkit.fluxcd.io` API, then perform a `flux diff` or `flux build`, it does not output the fully rendered manifest, but instead outputs the `Kustomization` object as is. For instance, the example below is the result of a `flux build`.

I want to see the rendered and outputted result, so in this case the `IstioOperator` object.

Being unable to render the end result objects, makes it more difficult to develop, troubleshoot, and verify changes when utilizing the flux `Kustomization` objects.



```YAML
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: ""
    kustomize.toolkit.fluxcd.io/namespace: ""
  name: istio-install
  namespace: flux
spec:
  dependsOn:
  - name: istio-operator
  interval: 10m
  patches:
  - patch: |-
      apiVersion: install.istio.io/v1alpha1
      kind: IstioOperator
      metadata:
        namespace: istio-system
        name: istio-controlplane
<ommitted for brevity>
```

**Comment by stefanprodan** [comment]
@dfallert-rcd You need to upgrade all your Flux Kustomizations to the v1beta2 API released many months ago.

**Comment by dfallert-rcd** [comment]
> @dfallert-rcd You need to upgrade all your Flux Kustomizations to the v1beta2 API released many months ago.

I was hoping this would do it, but I just upgraded everything, and tried again, and got the same output. It just outputs the `Kustomization` object, rather then the final, post-patch result

```YAML
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: ""
    kustomize.toolkit.fluxcd.io/namespace: ""
  name: istio-install
  namespace: flux
spec:
  dependsOn:
  - name: istio-operator
  interval: 10m
  patches:
  - patch: |-
      apiVersion: install.istio.io/v1alpha1
      kind: IstioOperator
      metadata:
        namespace: istio-system
        name: istio-controlplane
      spec:
        components:
          pilot:
<ommitted for brevity>
```

**Comment by dfallert-rcd** [comment]
To help better explain what I would like to see, vs what's available:

Currently:
- When doing a flux build, or a flux diff, the output **WILL** render the post patch results of patches applied via Kustomize objects from the **kustomize.config.k8s.io** group.
     
- When doing a flux build, or a flux diff, the output **will NOT** render the post patch results of patches applied via Kustomize objects from the **kustomize.toolkit.fluxcd.io** group. Instead, it will just output the object itself, like the example I gave earlier.
     
What I would like to see:
- When doing a flux \<new command name here\> ( or just use build/diff ) the output **WILL** render the post patch results of patches applied via Kustomize objects from the **kustomize.config.k8s.io** group, and the output **WILL** render the post patch results of patches applied via Kustomize objects from the **kustomize.toolkit.fluxcd.io** group.

**Comment by souleb** [comment]
This is implemented in `flux build`.  The code is here: https://github.com/fluxcd/flux2/blob/main/internal/build/build.go#L291

**Comment by dfallert-rcd** [comment]
My current experience tells me otherwise.

To be clear, you're stating that if I have this object:

```YAML
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-install
  namespace: flux
spec:
  interval: 10m
  path: "./base/istio/istiod"
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-cluster-gitops-v2
  patches:
    - target:
        kind: IstioOperator
        name: istio-controlplane
        namespace: istio-system
        group: install.istio.io
      patch: |-
        apiVersion: install.istio.io/v1alpha1
        kind: IstioOperator
        metadata:
          namespace: istio-system
          name: istio-controlplane
        spec:
          components:
            pilot:
              enabled: true
              k8s:
                podAnnotations:
                  metrics.dynatrace.com/scrape: "true"
                  metrics.dynatrace.com/port: "15014"
                  metrics.dynatrace.com/filter: '{"mode": "include","names": ["istio_build"]}'
                affinity:
                  podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                    - podAffinityTerm:
                        labelSelector:
                          matchExpressions:
                          - key: app
                            operator: In
                            values:
                            - istiod
                        topologyKey: kubernetes.io/hostname
                      weight: 100
```

Then I run `flux build kustomization <parameters>`

I should be getting a fully rendered, post-patch output like below?

```YAML
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  creationTimestamp: <ommitted>
  finalizers: <ommitted>
  labels: <ommitted>
  name: istio-controlplane
  namespace: istio-system
  resourceVersion: "58108260"
  uid: 0a86b9f2-6cbd-4f26-87c7-d75e7b592e7f
spec:
  components:
    base: <ommitted>
    cni: <ommitted>
    ingressGateways: <ommitted>
    pilot:
      enabled: true
      k8s:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istiod
                topologyKey: kubernetes.io/hostname
              weight: 100
        hpaSpec: <ommitted>
        podAnnotations:
          metrics.dynatrace.com/filter: '{"mode": "include","names": ["istio_build"]}'
          metrics.dynatrace.com/port: "15014"
          metrics.dynatrace.com/scrape: "true"
```
Because if that's the intended result, then I am not seeing this behavior.

Instead, the only thing related to istio-controlplane I see outputted, is the Kustomize object itself. 

Same story with flux diff
