### ISSUE TITLE
ImageUpdateAutomation not respecting Path

### ISSUE THREAD

**Issue by smarsh-tim** [fluxcd/flux2#1657]
### Describe the bug

The image tag updates are being updated outside of the path defined in ImageUpdateAutomation.

I am using a single GitOps repository, for two different Kubernetes clusters.

- Kubernetes cluster 1: apps/dev
- Kubernetes cluster 2: apps/qa

The specific portion that goes and updates the GitOps repository seems to update all deployment images tags for `# {"$imagepolicy": "flux-system:foo-service"}`, NOT just the specific Path defined in ImageUpdateAutomation. Otherwise values are set correctly. 

The result is that the image switches in GitOps from the `dev-` tagged one to the `qa-` tagged one every cycle. Resulting in thousands of extra commits to the GitOps repository, since it's flapping.

As defined in https://fluxcd.io/docs/components/image/imageupdateautomations/#update-strategy:
```go
        // Path to the directory containing the manifests to be updated.
	// Defaults to 'None', which translates to the root path
	// of the GitRepositoryRef.
	// +optional
	Path string `json:"path,omitempty"`
```

I have a directory structure such like:
```
apps/base
apps/base/service/image_update.yaml
apps/dev
apps/dev/service
apps/dev/service/image_update.yaml
apps/dev/service/deployment.yaml
apps/qa
apps/qa/service
apps/qa/service/image_update.yaml
apps/qa/service/deployment.yaml
```
^ I have `kustomization.yaml` files in each directory which combines (patches) the dev/qa objects into the base objects.

Such that  `apps/base` include common values, and `apps/dev` or `apps/qa` include values specific to Dev or QA environments.  Here are the contents of pertinent files:

`apps/base/service/image_update.yaml`
```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: foo-service
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: foo-fluxcd@users.noreply.foo.com
        name: foo-fluxcd
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  interval: 5m00s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    strategy: Setters

---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: foo-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: foo-service
  filterTags:
    extract: '$timestamp'
  policy:
    numerical:
      order: asc   # See examples: https://fluxcd.io/docs/components/image/imagepolicies/#examples
```

`apps/dev/service/image_update.yaml`
```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: foo-service
  namespace: flux-system
spec:
  update:
    path: ./apps/dev/service

---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: foo-service
  namespace: flux-system
spec:
  filterTags:
    pattern: '^dev-[a-fA-F0-9]+-(?P<timestamp>.*)'
```

`apps/qa/service/image_update.yaml`
```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: foo-service
  namespace: flux-system
spec:
  update:
    path: ./apps/qa/foo-service

---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: foo-service
  namespace: flux-system
spec:
  filterTags:
    pattern: '^qa-[a-fA-F0-9]+-(?P<timestamp>.*)'
```

`apps/dev/service/deployment.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-service
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: worker
        image: private-docker-registry.io/foo-service:dev-a4c50b9-1620688887 # {"$imagepolicy": "flux-system:foo-service"}
```

`apps/qa/service/deployment.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-service
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: worker
        image: private-docker-registry.io/foo-service:qa-472afda-1624643590 # {"$imagepolicy": "flux-system:foo-service"}
```

---

You can see that the imagepolicy tag in the `deployment.yaml` is for `flux-system:foo-service` on each. This is intended, and those ImagePolicy objects are different in each Kubernetes cluster. When I check the ImagePolicy object within Kubernetes, I can see that it is _not_ flopping between `dev-` and `qa-` tagged images.

I have commits every minute or so that go from:
- `qa-472afda-1624643590`
- `dev-a4c50b9-1620688887`
- `qa-472afda-1624643590`
- `dev-a4c50b9-1620688887`
- etc

This leads me to believe that the error is in the ImageUpdateAutomation process that updates the GitOps repository, and is just updating the wrong files - leading to the flap.

---

### Potential Workaround

The only thing I can think of doing to work-around this is drop the `kustomize` patching functionality and create different named ImagePolicy objects in `dev` and `qa`, such that the imagepolicy tag in each deployment.yaml is actually different.  While it should work, it's not a very DRY (don't repeat yourself) solution.

### Steps to reproduce

1. Install Flux with the Image Automation Controllers
2. Create two Kubernetes clusters, both managed by a singular GitOps repository
3. Leverage `kustomize` to match the directory structure described above
4. Set the ImagePolicy tag for a deployment that exists in both Dev and QA, but use the same ImagePolicy object name
5. Observe ImageUpdateAutomation will update both images even though the ImageUpdateAutomation is set to only look at one environment path.

### Expected behavior

ImageUpdateAutomation to _only_ update the path and sub-paths defined in the ImageUpdateAutomation object - not everywhere in the GitOps repository that has the comment used to update the image.

### OS / Distro

Fedora CoreOS

### Flux version

0.13.1

### Flux check

```sh
flux check
► checking prerequisites
✗ flux 0.13.1 <0.16.1 (new version is available, please upgrade)
✔ kubectl 1.19.7 >=1.18.0-0
✔ Kubernetes 1.19.8-eks-96780e >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.10.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.9.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.9.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.11.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.13.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.12.1
✔ all checks passed
```

### Git provider

GitHub

### Container Registry provider

JFrog Artifactory

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
