### ISSUE TITLE
Helm release listed in the wrong namespace

### ISSUE THREAD

**Issue by davivcgarcia** [fluxcd/flux2#1674]
### Describe the bug

When creating a `HelmRelease` in a custom namespace, the `helm` CLI detects it on `flux-system` instead.

### Steps to reproduce

1. Creates the `HelmSource`:

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kube-autoscaler
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://kubernetes.github.io/autoscaler
```

2. Create the `HelmRelease`:

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  releaseName: cluster-autoscaler
  chart:
    spec:
      chart: cluster-autoscaler
      sourceRef:
        kind: HelmRepository
        name: kube-autoscaler
  values:
    autoDiscovery:
      clusterName: sandbox
    rbac:
      serviceAccount:
        create: false
        name: cluster-autoscaler
  install: {}
  interval: 1m0s
  targetNamespace: kube-system
```

### Expected behavior

When running `helm ls -n kube-system` is shows empty:

```
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
```

But checking the with `helm ls -n flux-system` we see:

```
NAME              	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART                    	APP VERSION
cluster-autoscaler	kube-system	1       	2021-08-03 02:17:24.622728998 +0000 UTC	deployed	cluster-autoscaler-9.10.3	1.21.0
```

### OS / Distro

macOS 15

### Flux version

0.16.1

### Flux check

► checking prerequisites
✔ kubectl 1.21.3 >=1.18.0-0
✔ Kubernetes 1.21.2-13+d2965f0db10712 >=1.16.0-0
► checking controllers
✗ helm-controller: deployment not ready
► ghcr.io/fluxcd/helm-controller:v0.11.1
✗ kustomize-controller: deployment not ready
► ghcr.io/fluxcd/kustomize-controller:v0.13.2
✗ notification-controller: deployment not ready
► ghcr.io/fluxcd/notification-controller:v0.15.0
✗ source-controller: deployment not ready
► ghcr.io/fluxcd/source-controller:v0.15.3
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
