### ISSUE TITLE
Unwanted automatic deployments because of missing kustomization.yaml in the bootstrap root

### ISSUE THREAD

**Issue by pgillich** [fluxcd/flux2#1678]
### Describe the bug

Here is the bootstrap command:
```
flux bootstrap gitlab \
  --hostname=gitlab.lan \
  --owner=xxx \
  --repository=fluxcd \
  --branch=master \
  --path=clusters/hu2-k8s \
  --token-auth \
  --personal \
  --log-level=debug
```
It creates a boostrap deployment here:
`gitlab.lan/xxx/fluxcd/clusters/hu2-k8s/flux-system/`
A Kustomization is created with below config:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/hu2-k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
```
Since there is no any `kustomization.yaml` in the root of `./clusters/hu2-k8s`, all `kustomization.yaml` are collected and processed, too (including the `./clusters/hu2-k8s/flux-system/kustomization.yaml`).

Result: all Kustomizations under the `./clusters/hu2-k8s` (`kustomizations/flux-system:spec.path`) are deployed and kept running automatically.

### Steps to reproduce

1. Install Flux, described above.
2. Create new directories with Flux Kustomization configs under the root of bootstrap config (under `kustomizations/flux-system:spec.path`).
3. All new Flux Kustomizations are deployed automatically.

### Expected behavior

Better documentation (note), for example creating a simple `kustomization.yaml` in `kustomizations/flux-system:spec.path` with below content:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - flux-system
```

Set the `kustomizations/flux-system:spec.path` to `./clusters/hu2-k8s/flux-system`

### OS / Distro

Ubuntu 20.04

### Flux version

0.16.1

### Flux check

► checking prerequisites
✔ kubectl 1.21.3 >=1.18.0-0
✔ Kubernetes 1.21.0 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.13.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.15.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.3
✔ all checks passed

### Git provider

GitLab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
