### ISSUE TITLE
HelmRelease does not update when migrating from helm-operator to helm-controller

### ISSUE THREAD

**Issue by jbilliau-rcd** [fluxcd/flux2#1708]
### Describe the bug

Hi, we currently run FluxV1 and the helm-operator on over 100+ clusters. We are now looking into migrating to Fluxv2 and the whole Gitops Toolkit. I followed the migration guide here:

https://fluxcd.io/docs/migration/helm-operator-migration/#steps

I had this:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: flux
spec:
  releaseName: cluster-autoscaler
  targetNamespace: kube-system
  chart:
    repository: https://kubernetes.github.io/autoscaler
    name: cluster-autoscaler
    version: 9.9.2
  values:
    fullnameOverride: cluster-autoscaler
    extraArgs:
      balance-similar-node-groups: true
      skip-nodes-with-local-storage: false
    image:
      tag: "v1.20.0"
    resources:
      limits:
        cpu: 150m
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 50Mi
  valuesFrom:
    - configMapKeyRef:
        name: cluster-info
        key: cluster-autoscaler.yaml
```

and am migrating to this:

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cluster-autoscaler
  namespace: flux
spec:
  interval: 1m
  url: https://kubernetes.github.io/autoscaler
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: flux
spec:
  interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
  releaseName: cluster-autoscaler
  targetNamespace: kube-system
  chart:
    spec:
      chart: cluster-autoscaler
      version: 9.9.2
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
      interval: 1m
  values:
    fullnameOverride: cluster-autoscaler
    extraArgs:
      balance-similar-node-groups: true
      skip-nodes-with-local-storage: false
    image:
      tag: "v1.20.0"
    resources:
      limits:
        cpu: 150m
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 50Mi
  valuesFrom:
    - kind: ConfigMap
      name: cluster-info
      valuesKey: cluster-autoscaler.yaml
```

I scale down the helm-operator to 0, then commit my flux changes on the Fluxv2 side:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
resources:
- controllers/cluster-autoscaler.yaml
- controllers/external-dns.yaml
```

According to the guide, the helm-controller should *upgrade* the existing `HelmReleases` and basically "take them over". Instead, I get errors about resources already existing, basically the same type of stuff you get when trying to install new resources over existing resources with a different helm release.

```
  status:
    conditions:
    - lastTransitionTime: "2021-08-10T00:44:14Z"
      message: install retries exhausted
      reason: InstallFailed
      status: "False"
      type: Ready
    - lastTransitionTime: "2021-08-10T00:44:14Z"
      message: |+
        Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "external-dns" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "external-dns"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
```

What am I doing wrong here?

### Steps to reproduce

1. Deploy source-controller, kustomize-controller, helm-controller to cluster.
2. Point controllers at a "gitops-v2" repo. Fluxv1 pointed at "gitops-v1".
3. Turn off helm-operator
4. Git push my changes to gitops-v2 repo which the new Fluxv2 is monitoring.
5. Source-controller and kustomize-controller are fine, but helm-controller blows up with errors when it tries to deploy.

### Expected behavior

According to the migration guide, helm-controller should commandeer any HelmReleases that were installed via the helm-operator. 

### OS / Distro

Amazon Linux

### Flux version

0.15.3 (source-controller) 0.11.1 (helm-controller)

### Flux check

N/A

### Git provider

Github

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
