### ISSUE TITLE
Orphan objects after failed reconciliation with validation: none and prune: true

### ISSUE THREAD

**Issue by murillodigital** [fluxcd/flux2#1723]
### Describe the bug

- Given a  `GitRepository` holding multiple individual manifests inside a path without a wrapping kustomization.yaml

![image](https://user-images.githubusercontent.com/1219288/129756049-37b87eab-a197-4533-9feb-bddf3c79d8e6.png)

- A `Kustomization` object pointing to that repo and path, with `prune: true` and `validation: none`

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-kustomization
  namespace: default
spec:
  interval: 1m
  prune: true
  validation: none
  path: "./manifests"
  sourceRef:
    kind: GitRepository
    name: flux
```
- And a malformed manifest inside that path (`replicaset.yaml` in the example above)

The `Kustomization` will reach the following state:

```yaml
status:
  conditions:
  - lastTransitionTime: "2021-08-17T15:25:10Z"
    message: |
      apply failed: error: error validating "e893bb8d-57f3-40ac-bcfa-67b0ba809a7e.yaml": error validating data: ValidationError(ReplicaSet.spec): missing required field "selector" in io.k8s.api.apps.v1.ReplicaSetSpec; if you choose to ignore these errors, turn validation off with --validate=false
    reason: ReconciliationFailed
    status: "False"
    type: Ready
```

And the objects declared in correct manifests will have been created:

```
❯ kubectl get ns
NAME              STATUS   AGE
default           Active   3d19h
kube-system       Active   3d19h
kube-public       Active   3d19h
kube-node-lease   Active   3d19h
flux-system       Active   30m
ns0               Active   86s
ns1               Active   86s
ns2               Active   86s
ns3               Active   86s
ns4               Active   86s
ns5               Active   86s
ns6               Active   86s
ns7               Active   86s
ns8               Active   86s
ns9               Active   86s
```

However, deleting the `Kustomization`, although is `prune: true`, will not delete the created objects, leaving them orphan:

```shell
kubectl delete kustomization flux-kustomization
kustomization.kustomize.toolkit.fluxcd.io "flux-kustomization" deleted
❯ kubectl get ns
NAME              STATUS   AGE
default           Active   3d19h
kube-system       Active   3d19h
kube-public       Active   3d19h
kube-node-lease   Active   3d19h
flux-system       Active   30m
ns0               Active   105s
ns1               Active   105s
ns2               Active   105s
ns3               Active   105s
ns4               Active   105s
ns5               Active   105s
ns6               Active   105s
ns7               Active   105s
ns8               Active   105s
ns9               Active   105s
```

### Steps to reproduce

Apply the following manifest to your cluster:

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux
  namespace: default
spec:
  interval: 1m
  url: https://github.com/jonathan-innis/flux2-validation-test.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-kustomization
  namespace: default
spec:
  interval: 1m
  prune: true
  validation: none
  path: "./manifests"
  sourceRef:
    kind: GitRepository
    name: flux
...
```

Confirm `Namespaces` have been created. Then proceed to delete the `Kustomization`, you will find that the namespaces did not get pruned.

### Expected behavior

Any object created by a `Kustomization` should be removed when it is deleted.

### OS / Distro

Ubuntu

### Flux version

0.13.3

### Flux check

❯ flux check
► checking prerequisites
✗ flux 0.13.3 <0.16.2 (new version is available, please upgrade)
✔ kubectl 1.22.0 >=1.18.0-0
✔ Kubernetes 1.21.3+k3s1 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.10.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.12.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.13.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.12.1
✔ all checks passed

### Git provider

GitHub

### Container Registry provider

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
