### ISSUE TITLE
flux bootstrap fails with accumulating resources: accumulation err='accumulating resources from 'gotk-sync.yaml'

### ISSUE THREAD

**Issue by jack-evans** [fluxcd/flux2#1741]
### Describe the bug

hitting the following error with v0.16.2:

```bash
flux bootstrap --verbose github --owner xxx --repository cluster-policies --interval 5m --branch test --components source-controller,kustomize-controller,helm-controller --components-extra image-reflector-controller,image-automation-controller --hostname xxxx --ssh-hostname xxxx --path policies/my-cluster --commit-message-appendix "[ci skip]" --registry xxxx --image-pull-secret xxxx --verbose
► connecting to github.ibm.com
► cloning branch "test-again" from Git repository "https://xxxx/xxxx/cluster-policies.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ committed sync manifests to "test" ("5623fc213fae764b5ddebcf6a85d68580fb2398d")
► pushing component manifests to "https://xxxx/xxxx/cluster-policies.git"
► installing toolkit.fluxcd.io CRDs
◎ waiting for CRDs to be reconciled
✔ CRDs reconciled successfully
► installing components in "flux-system" namespace
error: accumulating resources: accumulation err='accumulating resources from 'gotk-sync.yaml': evalsymlink failure on '/private/var/folders/ql/j2nnpjkx40x6mb1jnmtjmkz00000gn/T/flux-bootstrap-1991140482/policies/my-cluster/flux-system/gotk-sync.yaml' : lstat /private/var/folders/ql/j2nnpjkx40x6mb1jnmtjmkz00000gn/T/flux-bootstrap-1991140482/policies/my-cluster/flux-system/gotk-sync.yaml: no such file or directory': evalsymlink failure on '/private/var/folders/ql/j2nnpjkx40x6mb1jnmtjmkz00000gn/T/flux-bootstrap-1991140482/policies/my-cluster/flux-system/gotk-sync.yaml' : lstat /private/var/folders/ql/j2nnpjkx40x6mb1jnmtjmkz00000gn/T/flux-bootstrap-1991140482/policies/my-cluster/flux-system/gotk-sync.yaml: no such file or directory
✗ exit status 1
```

prior to the flux bootstrap we generate a `gotk-patches.yaml` like the following:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  ignore: |
    # exclude all files
    /*
    # include relevant cluster
    !/policies/my-cluster
    # ignore old flux policies
    /policies/my-cluster/100-flux.yaml
    /policies/my-cluster/200-flux-helm-operator.yaml
# The following are used to override the imagePullPolicy and resource limits for the components.
# For now, helm-controller is the only one we should override for replicas as that is the main one we use.
# source-controller should always run as a single replica due to its stateful nature. See https://github.com/fluxcd/flux2/issues/836#issuecomment-770751139
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: manager
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: manager
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: manager
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-reflector-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: manager
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-automation-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: manager
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
```

and a kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patchesStrategicMerge:
- gotk-patches.yaml
```

seems to be a bug around [here](https://github.com/fluxcd/flux2/blob/72294b2a56fd8e75370878d1e143636657e4a5f5/internal/bootstrap/bootstrap_plain_git.go#L187)

### Steps to reproduce

1. Install flux2
2. use the above patches and flux bootstrap command to bootstrap a cluster
3. see error

### Expected behavior

successful install

### OS / Distro

macOS

### Flux version

0.16.2

### Flux check

flux check --pre
► checking prerequisites
✔ kubectl 1.21.4 >=1.18.0-0
✔ Kubernetes 1.19.13+IKS >=1.16.0-0
✔ prerequisites checks passed

### Additional context

originally used kubectl at version 1.19 and got:
```
► installing components in "flux-system" namespace
error: rawResources failed to read Resources: Load from path gotk-sync.yaml failed: evalsymlink failure on '/private/var/folders/ql/j2nnpjkx40x6mb1jnmtjmkz00000gn/T/flux-bootstrap-2092984589/policies/de-nikjackmzr-hub0/flux-system/gotk-sync.yaml' : lstat /private/var/folders/ql/j2nnpjkx40x6mb1jnmtjmkz00000gn/T/flux-bootstrap-2092984589/policies/de-nikjackmzr-hub0/flux-system/gotk-sync.yaml: no such file or directory
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Please see the docs here, you need to create the file structure required by bootstrap https://fluxcd.io/docs/installation/#customize-flux-manifests

**Comment by jack-evans** [comment]
ahh yes, right so if I do that I now get the error:

```
► installing components in "flux-system" namespace
error: no matches for IdId source.toolkit.fluxcd.io_v1beta1_GitRepository|flux-system|flux-system; failed to find unique target for patch source.toolkit.fluxcd.io_v1beta1_GitRepository|flux-system
```

which I am guessing is because we're trying to patch something that flux bootstrap wants to create?

**Comment by jack-evans** [comment]
right think I've fixed it - if I add a basic:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  url: ssh://git@xxxx/xxxx/cluster-policies
```

to gotk-sync.yaml then it all works out okay. Thanks for the help @stefanprodan
