### ISSUE TITLE
HelmRelease DependsOn is Not Considered for Delete Operations

### ISSUE THREAD

**Issue by danehans** [fluxcd/flux2#1744]
### Describe the bug

The HelmRelease dependency graph is not being respected for delete operations.

### Steps to reproduce

1. Create 2 hr's, foo and bar.
2. Have bar dependOn foo.
3. Delete hr/foo.

### Expected behavior

The hr/foo does not get deleted and surfaces status condition message: `Failed to delete hr/foo: hr/bar depends on hr/foo.`

### OS / Distro

1.20.8-gke.2100

### Flux version

v0.11.0

### Flux check

$ flux check
► checking prerequisites
✗ flux 0.16.1 <0.16.2 (new version is available, please upgrade)
✔ kubectl 1.19.11 >=1.18.0-0
✔ Kubernetes 1.20.8-gke.2100 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► <SNIP>/fluxcd/helm-controller:v0.11.0
✔ kustomize-controller: deployment ready
► <SNIP>/fluxcd/kustomize-controller:v0.13.0
✔ notification-controller: deployment ready
► <SNIP>/fluxcd/notification-controller:v0.15.0
✔ source-controller: deployment ready
► <SNIP>/fluxcd/source-controller:v0.14.0
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danehans** [comment]
> Please let us know if this is something you already understood, or if not it would be good to better understand how we could make this clearer in the docs. I'd like to clarify also whether, with this information, is your report only now a misunderstanding about how Flux works, or if it is a feature request even knowing how it was intended to work.

@kingdonb Yes, I understand the current state and this is a feature request. For my use case, I have a primary HelmRelease that represents my app:
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-repo
spec:
  url: https://github.com/my/repo.git
  ...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app-foo
spec:
  sourceRef:
    kind: GitRepository
    name: my-repo
...
```

Values, such as what services to enable/disable are passed in as values:
```
hostname: foo.com

svcA:
  enabled: true

svcB:
  enabled: false
...
```

Each service is managed by a HelmRelease and `dependsOn` is used for dependency management of the services. When the app is removed, some resources get stuck in "Terminating" since the managed services were not deleted in reverse order.

> (I am not sure whether this can be implemented, but it seems like something that could be technically possible to implement as part of the finalizer checks that occur on receiving a delete event.)

This was my thinking as well. If svcB dependsOn svcA, a controller adds a finalizer to svcA and removes this finalizer when svcB is deleted.
