### ISSUE TITLE
kustomize build failed: accumulating resources is a directory

### ISSUE THREAD

**Issue by Kashalls** [fluxcd/flux2#1749]
### Describe the bug

Unable to use kustomization on github resource

We've tried using different styles of URLs:
- github.com/rancher/system-upgrade-controller
- https://github.com/rancher/system-upgrade-controller
- git@github.com:rancher/system-upgrade-controller.git
- github.com/rancher/system-upgrade-controller?ref=v0.7.1

It seems to happen in some environments, perhaps I am missing a dependency? I am not sure as I am quite new to this.

### Steps to reproduce

1. Install flux and run repo
2. Run: ` flux --kubeconfig=./kubeconfig get sources git` 
3. `kubectl --kubeconfig=./kubeconfig get kustomization -A` reports that flux-system core could not build from github

`cluster/core/system-upgrade/kustomization.yaml`:
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/rancher/system-upgrade-controller
images:
  - name: rancher/system-upgrade-controller
    newName: docker.io/rancher/system-upgrade-controller
    newTag: v0.7.4
```

flux log error:
```
2021-08-24T17:54:02.983Z error Kustomization/core.flux-system - Reconciliation failed after 283.070822ms, next try in 10m0s kustomize build failed: accumulating resources: accumulation err=&#39;accumulating resources from &#39;system-upgrade&#39;: read /tmp/core047006118/cluster/core/system-upgrade: is a directory&#39;: recursed accumulation of path &#39;/tmp/core047006118/cluster/core/system-upgrade&#39;: accumulating resources: accumulation err=&#39;accumulating resources from &#39;github.com/rancher/system-upgrade-controller?ref=v0.7.4&#39;: open /tmp/core047006118/cluster/core/system-upgrade/github.com/rancher/system-upgrade-controller?ref=v0.7.4: no such file or directory&#39;: git cmd = &#39;/usr/bin/git fetch --depth=1 origin v0.7.4&#39;: exit status 128
```

### Expected behavior

It should just work, as other people have done this on other systems and have had no problems. 

Non-working: https://github.com/Kashalls/home-cluster/blob/main/cluster/core/system-upgrade/kustomization.yaml
Working: https://github.com/onedr0p/home-cluster/blob/main/cluster/core/system-upgrade/kustomization.yaml

### OS / Distro

Ubuntu 20.04.2 LTS

### Flux version

flux version 0.16.2

### Flux check

► checking prerequisites
✔ kubectl 1.22.1 >=1.18.0-0
✔ Kubernetes 1.20.5+k3s1 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.13.3
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.15.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.4
✔ all checks passed

### Git provider

Github

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
I'm guessing you want to apply the `manifests` dir from Git. Register the repository as a Flux source and create a Flux Kustomization that overrides the image tag like so:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: system-upgrade-controller
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/rancher/system-upgrade-controller
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: system-upgrade-controller
  namespace: flux-system
spec:
  interval: 5m
  path: "./manifests/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: system-upgrade-controller
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: system-upgrade-controller
      namespace: system-upgrade
  timeout: 2m
  images:
  - name: rancher/system-upgrade-controller
    newName: docker.io/rancher/system-upgrade-controller
    newTag: v0.7.5
```

**Comment by onedr0p** [comment]
Using a kustomization to pull this in works fine on my end, I'm really curious why it doesn't for some people. 

Sure you can use a git repository and a flux kustomize but it should also work with a kustomization? I've seen other people also run into this when deploying metrics-server with a kustomization thru flux where for me it worked fine.

I'm really confused on this behaviour.

**Comment by stefanprodan** [comment]
> I'm really confused on this behaviour. It seems like a flux issue because @Kashalls was able to run kustomize build locally and it rendered out.

Well `resources` expect a YAML file not a a whole repo, have you tried `kustomize build` locally?

**Comment by Kashalls** [comment]
> > I'm really confused on this behaviour. It seems like a flux issue because @Kashalls was able to run kustomize build locally and it rendered out.
> 
> Well `resources` expect a YAML file not a a whole repo, have you tried `kustomize build` locally?

It rendered out completely with no issues. Syntax was fine and nothing out of the ordinary.

**Comment by stefanprodan** [comment]
Ah ok there is kustomization.yaml in the repo root, haven't seen that.

**Comment by onedr0p** [comment]
I was thinking it could be DNS but his source controller, helm controller are able to do DNS lookups.

**Comment by stefanprodan** [comment]
If don't want to use the Flux objects then switching to https in the config should work:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml
images:
  - name: rancher/system-upgrade-controller
    newName: docker.io/rancher/system-upgrade-controller
    newTag: v0.7.4
```
