### ISSUE TITLE
metadata.resourceVersion must be specified

### ISSUE THREAD

**Issue by sbeck14** [fluxcd/flux2#1765]
### Describe the bug

I'm having an issue with using Flux to sync certificates.

I updated from Flux v1 to v2 (installed v2 with bootstrap, scaled down v1, copied manifests over) and am getting the following error:

```
The certificates "[certificate-name]" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```

I believe this is the same issue that was referenced here: https://github.com/fluxcd/flux/issues/2938 except I'm using v2. This issue might have been present in our installation of v1 as well and I just didn't notice the error.

My certificate manifest looks similar to this:

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  annotations:
  name: certificate-name
  namespace: akkeris-system
spec:
  acme:
    config:
    - dns01:
        provider: aws
      domains:
      - certificate-name.domain.io
  commonName: certificate-name.domain.io
  dnsNames:
  - certificate-name.domain.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: certificate-name
  ```

AFAIK I shouldn't need to provide a resourceVersion in the metadata of the certificate manifest.

### Steps to reproduce

1. Install flux v2 and cert-manager
2. Add a certificate manifest to the gitops repo
3. Profit

### Expected behavior

The manifest is created and synced in the target cluster

### OS / Distro

macOS 11.2.2

### Flux version

0.17.0

### Flux check

► checking prerequisites
✔ kubectl 1.20.4-dirty >=1.18.0-0
✔ Kubernetes 1.19.8 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.14.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.16.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.4
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
