### ISSUE TITLE
Flux bootstrap ignores the username specified when using git with SSH

### ISSUE THREAD

**Issue by fbonin** [fluxcd/flux2#1771]
### Describe the bug

When creating a new project with bootstrap, if a username is specified in the git URL it will be ignored when creating the file gotk-sync.yaml. As a result, Flux won't be able to complete the installation in this scenario because it won't be able to connect to the git repo.

The bug can be bypassed by adding a gotk-patches file that patch the git URL.

### Steps to reproduce

1 : Use this command to create a new flux project (make sure to use a custom username for the ssh link) : 

flux bootstrap git \
  --url=ssh://<CUSTOM_USERNAME>@<host>/<org>/<repository> \
  --branch=main \
  --path=clusters/my-cluster

2 The file gotk-sync.yaml will not have the CUSTOM_USERNAME specified :  : 
---
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@<host>/<org>/<repository>
```

It will have a username harcoded to git@<host>/<org>/<repository> instead

### Expected behavior

The file gotk-sync.yaml should have the username included like this : 

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://<CUSTOM_USERNAME>@<host>/<org>/<repository>
```

### OS / Distro

N/A

### Flux version

0.17.0

### Flux check

N/A

### Git provider

CodeCommit

### Container Registry provider

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
