### ISSUE TITLE
Flux incorrectly parses support strategic merge patches under kustomization overlay patches key

### ISSUE THREAD

**Issue by apeschel** [fluxcd/flux2#1778]
### Describe the bug

The `patches` key in a kustomization.yaml allows the use of either JSON6902 or strategicmerge patches, as documented here:

<https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/>

However, attempting to use an overlay with a stategic merge patch under the `patches` key will result in this error:

```
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Kustomization.patches of type types.Patch
```

### Steps to reproduce

Using this documentation as a reference:

https://github.com/kubernetes-sigs/kustomize/blob/master/examples/inlinePatch.md

Create a base

```
DEMO_HOME=$(mktemp -d)

BASE=$DEMO_HOME/base
mkdir $BASE

cat <<EOF >$BASE/kustomization.yaml
resources:
- deployments.yaml
EOF

cat <<EOF >$BASE/deployments.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  template:
    metadata:
      labels:
        foo: bar
    spec:
      containers:
        - name: nginx
          image: nginx
          args:
          - one
          - two
EOF
```

Define an overlay with a strategic merge patch under the patches key.

```
SMP_OVERLAY=$DEMO_HOME/smp
mkdir $SMP_OVERLAY
cat <<EOF >$SMP_OVERLAY/kustomization.yaml
resources:
- ../base

patches:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: deploy
  spec:
    template:
      spec:
        containers:
        - name: nginx
          image: nginx:latest
          
EOF
```

It will render with kustomize

```
kubectl kustomize $SMP_OVERLAY
```

However, if you attempt to use this with flux, it will fail with the above error.

### Expected behavior

flux should be able to render and apply kustomization overlays with strategic merge patches under the patches key, as per the kustomize spec.

### OS / Distro

macOS 11.5.2

### Flux version

flux version 0.17.0

### Flux check

► checking prerequisites
✔ kubectl 1.22.1 >=1.18.0-0
✔ Kubernetes 1.19.11 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.14.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.16.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.4
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seh** [comment]
I see that your "patches" entry is missing [the "target" field](https://sourcegraph.com/github.com/kubernetes-sigs/kustomize@634464353ff38b93e45f06f77832f24ee2921f64/-/blob/api/types/patch.go?L19-20). Does it help if you include it?

**Comment by seh** [comment]
Oh, I see the problem: your "patches" entry is just a string. It needs a "patch" field:
```yaml
patches:
- patch: |-
  ...
```

**Comment by stefanprodan** [comment]
As @seh said, the patch field is missing. Please see the docs: https://fluxcd.io/docs/components/kustomize/kustomization/#patches

**Comment by apeschel** [comment]
@seh @stefanprodan It's very strange, because this works in kustomize, but not in flux:

```
patches:
- foo.yaml
```
However, you're right that this behavior doesn't seem to be documented.

This seems to work in both, however

```
patches:
- path: foo.yaml
```

**Comment by seh** [comment]
In which version of _kustomize_ did you find that that works?

**Comment by apeschel** [comment]
@seh Using the kustomize integrated with kubectl 1.22 exhibits this behavior:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
```

Also happens with the standalone kustomize, version 4.3.0

```
kustomize version

{Version:kustomize/v4.3.0 GitCommit:cd17338759ef64c14307991fd25d52259697f1fb BuildDate:2021-08-24T19:04:58Z GoOs:darwin GoArch:amd64}
```

**Comment by apeschel** [comment]
I'll give a full practical example here, rather than continue trying to simplify:


```
.
├── helm-release.yaml
├── kustomization.yaml
└── patch.yaml

0 directories, 3 files.
├── helm-release.yaml
├── kustomization.yaml
└── patch.yaml

0 directories, 3 files
```

helm-release.yaml

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  chart:
    spec:
      chart: ./charts/postgres-operator/
      sourceRef:
        kind: GitRepository
        name: postgres-operator
        namespace: postgres-operator
  interval: 1m0s
```

patch.yaml

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  values:
    configAwsOrGcp:
      aws_region: us-east-1
```

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helm-release.yaml

patches:
- patch.yaml
```

`kustomize build .`

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  chart:
    spec:
      chart: ./charts/postgres-operator/
      sourceRef:
        kind: GitRepository
        name: postgres-operator
        namespace: postgres-operator
  interval: 1m0s
  values:
    configAwsOrGcp:
      aws_region: us-east-1
      wal_s3_bucket: auth-project-postgres-backups
```
