### ISSUE TITLE
Upgrade of flux components fails with: error: json: cannot unmarshal object into Go

### ISSUE THREAD

**Issue by chuegel** [fluxcd/flux2#1812]
### Describe the bug

Flux fails to upgrade its components when sops is added via patch to `flux-system -> kustomization.yaml`

kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

patches:
  - path: sops-patch.yaml
    target:
      kind: Kustomization
      name: flux-system
      namespace: flux-system
```
sops-patch.yaml:

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/lab
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
```

```
► connecting to https://scm.example.com
► cloning branch "master" from Git repository "https://scm.example.com/networking/k8s-gitops.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ committed sync manifests to "master" ("c7de5581564869124bd7048d0de0e8fc8837cfca")
► pushing component manifests to "https://scm.example.com/networking/k8s-gitops.git"
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
► generating source secret
► applying source secret "flux-system/flux-system"
✔ reconciled source secret
► generating sync manifests
✔ generated sync manifests
✔ sync manifests are up to date
► applying sync manifests
error: json: cannot unmarshal object into Go struct field Kustomization.patchesStrategicMerge of type patch.StrategicMerge
✗ exit status 1
```

### Steps to reproduce

1. Deploy flux and wait to reconcile componentes.
2. add patch to kustomization.yaml (see above)
3. Cluster reconciles successful
4. Upgrade flux components with `flux bootstrap ....`
5. Watch error 

### Expected behavior

Upgrade should not fail 

### OS / Distro

CentOS 7.8

### Flux version

0.17

### Flux check

► checking prerequisites
✔ kubectl 1.19.4 >=1.18.0-0
✔ Kubernetes 1.19.4 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.14.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.11.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.14.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.16.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/sou

### Git provider

gitlab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Please try this:

sops-patch.yaml:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
```

kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patchesStrategicMerge:
  - sops-patch.yaml
```
