### ISSUE TITLE
Helmchart states: "no chart name found"

### ISSUE THREAD

**Issue by dakky** [fluxcd/flux2#1813]
### Describe the bug

After deploying a helm release, the corresponding chartrelease fails with `no chart name found`

Some infos about the setup:

* Helm registry is a mirror of `https://repo.chartcenter.io`
* other helmreleases are working
* i want to install the nginx-ingress-1.9.0

I did some debugging already:

inside of the `source-controller` i examined the following directories:
* `/data/helmchart/flux-system`: 
  there no folder for the chart gets created and therefore no `.tgz` of the chart is found
* `/data/helmrepository/flux-system/helm-chartcenter`:
  There an index.yaml (and a symlink is located).
  The index.yaml includes the relevant chart (twice! maybe the problem?):
  ```
    - name: nginx/nginx-ingress
      version: "1.9.0"
      description: "NGINX Ingress Controller"
      appVersion: "1.9.0"
      digest: 757a19d2b2bbe8db8377d541bfc47c5fac0555803ed9929b62b68cef9e90cd99
      urls: 
      - https://<private-registry>/nginx/nginx-ingress-1.9.0.tgz
    - name: stable/nginx-ingress
      version: "1.9.0"
      description: "An nginx Ingress controller that uses ConfigMap to store the nginx configuration."
      appVersion: "0.25.0"
      digest: 5a88201f0e52e5ad7c70bd5774e2fb8a4c1c5b172a4a638950d80ef981e6c1b6
      urls: 
      - https://<private-registry>/stable/nginx-ingress-1.9.0.tgz
  ```
  Downloading these URLs is successful when made manually.

So basically the issue seems to be: 
Why is the source controller not able to download and extract the chart itself, although he succeedes to download the index .yaml with the (imho) correct content from the same host?

### Steps to reproduce

Hard, because private registry is involved and i don't have direct access to validate it against chartcenter.io

But basically:
1. add chartcenter.io as helmrepository
2. add helmrelease for nginx-ingress-1.9.0:
  ```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  suspend: false
  releaseName: nginx-ingress
  targetNamespace: nginx-ingress
  storageNamespace: nginx-ingress
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress
      version: '1.9.0'
      sourceRef:
        kind: HelmRepository
        name: helm-chartcenter
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: nginx-ingress-values
      valuesKey: dev-nginx-ingress-values.yaml
      optional: false
  install:
    createNamespace: true
```

### Expected behavior

helm charts gets deployed

### Screenshots and recordings

unfortunetly there a no hints in the logs (`flux log` nor `kubectl logs` of the source container) ot the k8s events 

### OS / Distro

ubuntu 20.04

### Flux version

0.16.1

### Flux check

$ flux check
► checking prerequisites
✔ kubectl 1.18.8 >=1.18.0-0
✔ Kubernetes 1.19.13+vmware.1 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► <private-registry>/fluxcd/helm-controller:v0.11.1
✔ kustomize-controller: deployment ready
► <private-registry>/fluxcd/kustomize-controller:v0.13.2
✔ notification-controller: deployment ready
► <private-registry>/fluxcd/notification-controller:v0.15.0
✔ source-controller: deployment ready
► <private-registry>/fluxcd/source-controller:v0.15.3
✔ all checks passed

### Git provider

gitlab

### Container Registry provider

jfrog artifactory mirroring https://repo.chartcenter.io

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
