### ISSUE TITLE
NetworkPolicy implementation does not allow cert-manager to run HTTP-01 challenge

### ISSUE THREAD

**Issue by febus982** [fluxcd/flux2#1863]
### Describe the bug

The existing NetworkPolicy implementation applies to all pods in the namespace. 

`cert-manager` runs a temporary pod listening on port 8089 to answer HTTP-01 challenges from letsencrypt provider and generate TLS certificates for the ingress for the webhook controller.

Calls received from letsencrypt to verify the certificate do fail because connection to the pod is refused.

### Steps to reproduce

1. Install `flux`, `cert-manager`, `nginx-ingress` ingress controller (any ingress controller should do).
2. Create an Ingress resource as per documentation to expose the `webhook-receiver` services
3. Add the necessary annotations and spec for `cert-manager` to generate certificates.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-receiver
  namespace: flux-system
  annotations:
    "cert-manager.io/cluster-issuer": letsencrypt-staging
spec:
  tls:
    - hosts:
        - webhook.example.com
      secretName: flux-webhook-tls-cert-staging
  rules:
  - host: webhook.example.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: webhook-receiver
            port:
              number: 80
```

4. A pod named `cm-acme-http-solver-XXXXX` is running in the namespace
5. Logs are visible in the ingress controller pod showing "connection refused" errors
6. Allowing traffic with an additional NetworkPolicy for the `cert-manager` pod fixes the issue :

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cert-manager
  namespace: flux-system
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      acme.cert-manager.io/http01-solver: "true"
  policyTypes:
  - Ingress
```

### Expected behavior

The Network Policies should target only the flux application pods (e.g. by using a pod label) so that connections to pods not owned by flux are accepted.

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by febus982** [comment]
Correct, this wouldn't apply if network policies were disabled.

For context, these are the related resources in ` v0.17.2`:

The policy blocking traffic:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.17.2
  name: allow-egress
  namespace: flux-system
spec:
  egress:
  - {}
  ingress:
  - from:
    - podSelector: {} # This allows connections only from other pods, but blocks other ingress traffic
  podSelector: {} # This targets all pods in namespace (also pods not part flux application)
  policyTypes:
  - Ingress
  - Egress
```

The policy allowing ingress, specifically on webhook pod:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.17.2
  name: allow-webhooks
  namespace: flux-system
spec:
  ingress:
  - from:
    - namespaceSelector: {}
  podSelector:
    matchLabels:
      app: notification-controller
  policyTypes:
  - Ingress
```
