### ISSUE TITLE
Implement flux version command

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#1892]
Implement `flux version` commands for both client and server-side components with the following specs.

Example output of `flux version -h`:

```
Print the client and server-side components version information for the current context.

Flags:
      --client             if true, shows client version only (no server required)
  -o, --output string      one of 'yaml' or 'json'  (default "yaml")

Global Flags:
      --context string      kubernetes context to use
      --kubeconfig string   absolute path to the kubeconfig file
  -n, --namespace string    the namespace scope for this operation (default "flux-system")
      --timeout duration    timeout for this operation (default 5m0s)
```

Example output of `flux version --client -o yaml`:

```yaml
flux: v0.17.0
```

Example output of `flux version -o yaml`:

```yaml
flux: v0.17.0
source-controller: v0.15.4
kustomize-controller: v0.14.0
helm-controller: v0.11.2
notification-controller: v0.16.0
image-reflector-controller: v0.11.1
image-automation-controller: v0.14.1
```

The components listing could use the same code as `flux check`. The component name and version should be extracted from the container image. Given that the Flux components except for source-controller are optional, we should error out only when the server is not accessible or when no components are found in the specified namespace.
