### ISSUE TITLE
[0.18.1] no matches for Id kustomize.toolkit.fluxcd.io_v1beta1

### ISSUE THREAD

**Issue by untcha** [fluxcd/flux2#1924]
### Describe the bug

I just updated flux from v0.16.1 to v0.18.1
The flux bootstrap command shows the following error:

`no matches for Id kustomize.toolkit.fluxcd.io_v1beta1_Kustomization|flux-system|flux-system; failed to find unique target for patch kustomize.toolkit.fluxcd.io_v1beta1_Kustomization|flux-system`

and the reconcilation for flux-system does not work anymore.

### Steps to reproduce

Upgrade flux with the following command:

```bash
flux bootstrap github \
  --owner=$GITHUB_USER \
  --repository=$GITHUB_REPOSITORY \
  --branch=main \
  --path=./cluster/base \
  --version="v0.18.1" \
  --network-policy=false \
  --personal
```

After running into the error I just reverted the changes in `gotk-sync.yaml`
`gotk-sync.yaml` after installing 0.18.1:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

I changed it back to the following:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
```

### Expected behavior

The flux bootstrap command should run without errors

### OS / Distro

macOS 11.6

### Flux version

0.18.1

### Flux check

flux check
► checking prerequisites
✔ Kubernetes 1.21.2+k3s1 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.15.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.17.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.16.0
✔ all checks passed

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
