### ISSUE TITLE
A problem with spec.dependsOn in flux2.

### ISSUE THREAD

**Issue by AndreyMaslovN** [fluxcd/flux2#1928]
### Describe the bug

We tried to install cert-manager and cert according to the instructions https://fluxcd.io/docs/components/kustomize/kustomization/

### Kustomization
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  path: "./cert-manager/controller"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: certs
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 5m
  path: "./cert-manager/certs"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

### Cert-manager
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  interval: 1m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    installCRDs: true
```

### Certificate
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flux-test
  namespace: default
spec:
  secretName: cert-mos
  issuerRef:
    name: cluster-issuer
  commonName: flux-test.mos.corp
  dnsNames:
  - flux-test.mos.corp
```

We got the following error: ``` ✗ Certificate/default/flux-test dry-run failed, error: no matches for kind "Certificate" in version "cert-manager.io/v1" ```
It looks like a broken ``` spec.dependsOn  ```

### Steps to reproduce

-  Use the official instructions (example) for spec.dependsOn

https://fluxcd.io/docs/components/kustomize/kustomization/

-  Deploy cert-manager and certificate 

### Expected behavior

We expected the spec.dependsOn to work as follows:
The cert-manager  will be installed and then installed certificate and we will not receive errors such as ``` ✗ Certificate/default/flux-test dry-run failed, error: no matches for kind "Certificate" in version "cert-manager.io/v1" ```

### OS / Distro

Ubuntu 20.04

### Flux version

0.18.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.20.6 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.15.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.17.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.16.0
✔ all checks passed

### Git provider

gitlab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AndreyMaslovN** [comment]
@stefanprodan I tell Flux to install the CRDs.
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  interval: 1m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    installCRDs: true
```

**Comment by AndreyMaslovN** [comment]
@stefanprodan 
I added  CRD health check. Its not work.
Strange that the official example doesn't work.
```
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: certificates.cert-manager.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: certificaterequests.cert-manager.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusterissuers.cert-manager.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: issuers.cert-manager.io
```
