### ISSUE TITLE
Unsupported Media Type error

### ISSUE THREAD

**Issue by ywyt738** [fluxcd/flux2#1940]
### Describe the bug

I use **Kustomizations** sync from git.
I have met the error since v0.18.0. It's work on 0.17.2.

error message:
Account/e-chop-account dry-run failed, reason: UnsupportedMediaType, error: 415: Unsupported Media Type

manifest:
```yaml
apiVersion: tenancy.kiosk.sh/v1alpha1
kind: Account
metadata:
  name: e-chop-account
spec:
  subjects:
    - kind: User
      name: e-chop
      apiGroup: rbac.authorization.k8s.io
```

### Steps to reproduce

upgrade from 0.17.2 to 0.18.x

### Expected behavior

apply successful

### OS / Distro

macOS

### Flux version

0.18.x

### Flux check

kubectl 1.22.2
kubenetes 1.21.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
