### ISSUE TITLE
[0.18+] Random Helm reconciliation issuess

### ISSUE THREAD

**Issue by artyom-p** [fluxcd/flux2#1957]
### Describe the bug

After upgrading to 0.18 (now 0.18.3 is installed) HelmReleases start to fail randomly on different charts.

Example with Cert-Manager chart:

Helm controller logs:

```
{"level":"info","ts":"2021-10-18T09:21:31.846Z","logger":"controller.helmrelease","msg":"skipping remediation, no new release revision created","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"cert-manager","namespace":"cert-manager"}
```
```
{"level":"info","ts":"2021-10-18T09:21:32.293Z","logger":"controller.helmrelease","msg":"reconcilation finished in 1.861515913s, next run in 3h0m0s","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"cert-manager","namespace":"cert-manager"}
```
```
{"level":"error","ts":"2021-10-18T09:21:32.293Z","logger":"controller.helmrelease","msg":"Reconciler error","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"cert-manager","namespace":"cert-manager","error":"Helm upgrade failed: another operation (install/upgrade/rollback) is in progress"}
```

HelmRelease:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      version: v1.5.4
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  values:
    installCRDs: true
    serviceAccount:
      create: true
      name: cert-manager
      annotations:
        eks.amazonaws.com/role-arn: "****"
    securityContext:
      enabled: true
      fsGroup: 1001
  suspend: false
  interval: 3h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
```

Kustomization:

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-kustomization
  namespace: flux-system
spec:
  suspend: false
  interval: 1m
  prune: true
  wait: true
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/test
```

Idk if thats related but also noticed that there are some errors in SourceController, and at the moment of writing, i see that SourceController was already restarted 15 times.

```
{"level":"error","ts":"2021-10-18T09:19:34.700Z","logger":"controller.helmchart","msg":"Reconciler error","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmChart","name":"cert-manager-cert-manager","namespace":"cert-manager","error":"no artifact found for source `jetstack` kind 'HelmRepository'"}
```

UPDATE:
Noticed that it happens when new HelmRepositories are added, source controller keeps restarting because of readiness probe:

```
Readiness probe failed: Get "http://192.168.57.14:9090/": dial tcp 192.168.57.14:9090: connect: connection refused
```

![image](https://user-images.githubusercontent.com/3993463/137723595-39d05ee5-f34a-4ba7-97df-2cce310f0e0e.png)

```
containerStatuses:
    - name: manager
      state:
        running:
          startedAt: '2021-10-18T12:14:05Z'
      lastState:
        terminated:
          exitCode: 137
          reason: OOMKilled
          startedAt: '2021-10-18T12:12:13Z'
          finishedAt: '2021-10-18T12:13:22Z'
```

HelmRepository:

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  interval: 5m
  url: https://charts.jetstack.io
```

### Steps to reproduce

Still not sure how to reproduce it, as i mentioned it happens randomly.

1. Install latest flux
2. Create kustomization with multiple helmreleases in it

### Expected behavior

Helm releases should be reconciled

### OS / Distro

Windows 11

### Flux version

0.18.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.2-eks-0389ca3 >=1.19.0-0
► checking controllers
✗ helm-controller: deployment not ready
► ghcr.io/fluxcd/helm-controller:v0.12.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.15.5
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.17.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.16.0
✔ all checks passed

### Git provider

Github

### Container Registry provider

Harbor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
