### ISSUE TITLE
Finish Fuzzer integration

### ISSUE THREAD

**Issue by dholbach** [fluxcd/flux2#2002]
- [x] Review and merge fuzzing PRs from https://github.com/orgs/fluxcd/projects/5
- [x] Work with Ada Logics on switching 
      > the git source in Flux’s OSS-fuzz integration from our forks to Flux’s own git
      > repositories ([here](https://github.com/google/oss-fuzz/pull/6539/files)). 
      They
      > will furthermore complete the [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) set up which is supported by OSS-fuzz.
- [x] Enable static linking of C dependencies (missing source-controller and image-automation-controller)
      According to @hiddeco this is done, but 
      > first needs to confirm it solves https://github.com/fluxcd/source-controller/pull/445
     there is now
      > prepared work in https://github.com/fluxcd/golang-with-libgit2/pull/6
- [x] Once all of the above is complete add the following manifest to `.github/workflows` in all repositories with fuzzers

```yaml
name: CIFuzz
on: [pull_request]
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'fluxcd'
        language: go
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'fluxcd'
        language: go
       fuzz-seconds: 60
    - name: Upload Crash
      uses: actions/upload-artifact@v1
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
```
