### ISSUE TITLE
Kustomization reconciliation failed: ImagePolicy :: Invalid value: "null": spec.policy.semver in body must be of type object: "null"

### ISSUE THREAD

**Issue by pnlarsson** [fluxcd/flux2#2010]
### Describe the bug

Using this:
```
 apiVersion: image.toolkit.fluxcd.io/v1beta1
 kind: ImagePolicy 
 metadata:
   name: policy-www
   namespace: flux-system
 spec:
   imageRepositoryRef:
     name: www-image
   filterTags:
     pattern: '^master-(?P<ts>[0-9]+)'
     extract: '$ts'
   policy:
     numerical:
       order: asc
```
Fails with:

► annotating Kustomization flux-system in flux-system namespace
✔ Kustomization annotated
◎ waiting for Kustomization reconciliation
✗ Kustomization reconciliation failed: ImagePolicy/flux-system/www dry-run failed, reason: Invalid, error: ImagePolicy.image.toolkit.fluxcd.io "www" is invalid: spec.policy.semver: Invalid value: "null": spec.policy.semver in body must be of type object: "null"

Using semver works fine

### Steps to reproduce

use yaml above

### Expected behavior

► annotating GitRepository flux-system in flux-system namespace
✔ GitRepository annotated
◎ waiting for GitRepository reconciliation
✔ fetched revision master/2b2ed72d298bda258fc6f4071ce99d1dedf7e02f
► annotating Kustomization flux-system in flux-system namespace
✔ Kustomization annotated
◎ waiting for Kustomization reconciliation
✔ applied revision master/2b2ed72d298bda258fc6f4071ce99d1dedf7e02f

### OS / Distro

Arch

### Flux version

flux version 0.19.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.20.4 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.15.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.13.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.16.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.16.1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
