### ISSUE TITLE
Spark Operator can not be installed using Flux 2

### ISSUE THREAD

**Issue by zzvara** [fluxcd/flux2#2030]
### Describe the bug

The Google Spark Operator can not be installed, because:
- Flux fails to install necessary roles and role-bindings _before_ the webhook job starts. The webhook job then fails because of missing roles and role-bindings.
- Above problem can be mitigated, by disabling the webhook during installation. It then allows an upgrade with the webhook enabled, because by then, roles and role-bindings are created.
- However, `HelmRelease` goes into a state of `
Helm upgrade failed: "spark-operator-development" has no deployed releases`.the 

### Steps to reproduce

1. Install flux:

`flux bootstrap git
    --namespace flux-system
    --author-name ##redacted##
    --branch flux-2
    --cluster-domain sigma
    --commit-message-appendix [Flux]
    --image-pull-secret ##redacted##
    --url ##redacted##
    --branch flux-2
    --username ##redacted##
    --private-key-file ../.ssh/id_rsa-flux
    --log-level debug
    --network-policy true
    --components-extra=image-reflector-controller,image-automation-controller`

2. Add `HelmRelease`:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spark-operator-development
  namespace: development
spec:
  chart:
    spec:
      chart: spark-operator
      sourceRef:
        kind: HelmRepository
        name: spark-operator
        namespace: kube-system
      version: 1.1.8
  interval: 30m0s
  install:
    crds: CreateReplace
    replace: true
    remediation:
      retries: -1
    disableWaitForJobs: true
    disableWait: true
    timeout: "2m"
  upgrade:
    crds: CreateReplace
    force: true
    remediation:
      retries: -1
    disableWaitForJobs: true
  uninstall:
    timeout: "1m"
  values:
    image:
      tag: v1beta2-1.2.3-3.1.1
      pullPolicy: Always
    webhook:
      enable: true
      namespaceSelector: "name=development"
    sparkJobNamespace: development
    resyncInterval: 10
    metrics:
      enable: false
    controllerThreads: 1
    batchScheduler:
      enable: true
    resourceQuotaEnforcement:
      enable: true
    rbac:
      createClusterRole: true
      createRole: true
    resources:
      requests:
        memory: 250Mi
        cpu: 100m
      limits:
        memory: 250Mi
        cpu: 500m
```

### Expected behavior

Spark Operator should be installed on the first try. Then stay stable.

### OS / Distro

Flatcar 2905.2.6

### Flux version

flux version 0.19.0

### Flux check

► checking prerequisites
✗ flux 0.19.0 <0.20.1 (new version is available, please upgrade)
✔ Kubernetes 1.21.5 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.15.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.13.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.16.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.16.0
✔ all checks passed

### Git provider

BitBucket

### Container Registry provider

DockerHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
