### ISSUE TITLE
Inconsistency in manifests generated by install vs bootstrap commands

### ISSUE THREAD

**Issue by aliusmiles** [fluxcd/flux2#2056]
### Describe the bug

Manifests generated by `flux install --export` have extra lines compared to those from `flux bootstrap`:

```sh
--- a/clusters/dev/flux-system/gotk-components.yaml
+++ b/clusters/dev/flux-system/gotk-components.yaml
@@ -1,3 +1,6 @@
+---
+# Flux version: v0.21.1
+# Components: source-controller,kustomize-controller,helm-controller,notification-controller,image-reflector-controller,image-automation-controller
 apiVersion: v1
 kind: Namespace
 metadata:
@@ -6228,3 +6231,4 @@ spec:
       app: notification-controller
   policyTypes:
   - Ingress
+---
```

It's nothing critical but rather annoying when cluster update is always done by `flux install --export` (I like this way since I can preview changes plus it can be automated) and then for some reason, like key recreation in v0.21.0, `flux bootstrap` must be executed.

### Steps to reproduce

1. bootstrap using `flux bootstrap ...` command
2. go to repo/clusters/name/flux-system and run `flux install --export ... > gotk-components.yaml`
3. run `git diff`

### Expected behavior

No differences in manifests.

### OS / Distro

N/A

### Flux version

v0.21.1

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jack-evans** [comment]
Agreed, I think if there was a consistent message at the top for both the install and the bootstrap then that would be a lot better....

maybe something like this in both cases:
```yaml
# This manifest was generated by flux. DO NOT EDIT.
# Flux version: v0.21.1
# Components: source-controller,kustomize-controller,helm-controller,notification-controller,image-reflector-controller,image-automation-controller
```

**Comment by jack-evans** [comment]
happy to put in a PR for this if we think the above is an improvement?

**Comment by stefanprodan** [comment]
@jack-evans your proposal looks good to me, I'm not sure how would this would work with Flux Terraform provider as the version is a property of the binary.

**Comment by jack-evans** [comment]
so my thoughts were it would live in the flux2 command itself, on install (with `--export`) and bootstrap (when pushing to git/vcs) we could have something that prepends:
```yaml
# This manifest was generated by flux. DO NOT EDIT.
# Flux version: v0.21.1
# Components: source-controller,kustomize-controller,helm-controller,notification-controller,image-reflector-controller,image-automation-controller
```
before the contents of either the gotk-components.yaml or the gotk-sync.yaml.

Having a brief look at the code potentially could be added in [install.Generate()](https://github.com/fluxcd/flux2/blob/main/pkg/manifestgen/install/install.go#L39)?  I guess I could take a stab and see what happens 🙂 

Not sure on the terraform case either. As that is Go, I'm guessing that uses the go packages rather than the CLI directly?

**Comment by jack-evans** [comment]
@stefanprodan just realised that a change I made locally to remove the fmt.Println("---") from the flux install --export (cmd/install.go) never made it in my PR which would make install and bootstrap generate exactly the same thing. Feels like a very small change to add as a Pr so wondering what you want to do here?

**Comment by stefanprodan** [comment]
I have tested this on my cluster, here is the header created bootstrap:

```yaml
---
# This manifest was generated by flux. DO NOT EDIT.
# Flux Version: v0.22.0
# Components: source-controller,kustomize-controller,helm-controller,notification-controller
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.22.0
  name: flux-system
---
```

And here is the install --export output:

```yaml
---
# This manifest was generated by flux. DO NOT EDIT.
# Flux Version: v0.22.0
# Components: source-controller,kustomize-controller,helm-controller,notification-controller
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.22.0
  name: flux-system
---
```

@jack-evans they look identical to me.
