### ISSUE TITLE
Helm install failed: rendered manifests contain a resource that already exists

### ISSUE THREAD

**Issue by chuegel** [fluxcd/flux2#2059]
### Describe the bug

We bootstrapped our cluster with ansible and terraform prior to install the flux components. During this operation, calico CNI was installed with the according manifests ( see https://docs.projectcalico.org/getting-started/kubernetes/quickstart#install-calico)
Now we would like to manage calico with flux via a helmrelease:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: projectcalico
  namespace: calico-system
spec:
  chart:
    spec:
      chart: tigera-operator
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: projectcalico
        namespace: flux-system
      version: 3.x
  interval: 5m
```
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: projectcalico
  namespace: flux-system
spec:
  interval: 5m
  url: https://docs.projectcalico.org/charts
```
But the deployment of the helmrelease fails with `✗ HelmRelease reconciliation failed: install retries exhausted`
Looking at the helm-controller logs, I get following errors:
```
{"level":"error","ts":"2021-11-07T18:07:45.252Z","logger":"controller.helmrelease","msg":"Reconciler error","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"projectcalico","namespace":"calico-system","error":"Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole \"tigera-operator\" in namespace \"\" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key \"app.kubernetes.io/managed-by\": must be set to \"Helm\"; annotation validation error: missing key \"meta.helm.sh/release-name\": must be set to \"projectcalico\"; annotation validation error: missing key \"meta.helm.sh/release-namespace\": must be set to \"calico-system\""}
```
at a bunch of other resources like namespace etc.

### Steps to reproduce

1. bootstrap a cluster and install calico according to the official documentation
2. bootstrap flux and create calico helmrepo/helmrelease
3. try to reconcile helmrelease

### Expected behavior

Helm should apply the chart even if the CRDs are present in the cluster

### OS / Distro

CentOS 8

### Flux version

flux: v0.21.0

### Flux check

► checking prerequisites
✗ flux 0.21.0 <0.21.1 (new version is available, please upgrade)
✔ Kubernetes 1.21.5+k3s2 >=1.19.0-0
► checking controllers
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.16.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.17.1
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.1
✔ all checks passed

### Git provider

gitlab

### Container Registry provider

DockerHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
