### ISSUE TITLE
substitution feature to create a secret from an already existing secret

### ISSUE THREAD

**Issue by rakeshreddyrg09** [fluxcd/flux2#2139]
### Describe the bug

Hi All,
can I use the substitution feature to create a secret from an already existing secret?

Hi All,
can I use the substitution feature to create a secret from an already existing secret?
There is already a secret that exists in Kubernetes with data
data:
```
{
name:postgresdb
user:postgres_user
password:postgres_password
}
```
and we want to create one more secret out of it with i.e.
data
```
{
db_name: $name
db_user: $user
db_password: $password
}
```
but, when I am using the substitution feature to put value in the new secret it gives me an error
**error: data values must be of type string**
code:
below is the new secret which I am trying to create
```
apiVersion: v1
kind: Secret
metadata:
  name: my-secret-test
type: Opaque
stringData:
  #myDbname: ${dbname:=NA}
  #myUserName: ${username:=NA}
  myPassword: ${password:=NA}
```
below is the Kustomization for the same
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: my-namespace
spec:
  interval: 5m
  path: "./core/keycloak/apps/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ######-git
  postBuild:
    substituteFrom:
      - kind: Secret
        name: my-secret
```
The secret is getting created, but with the input string it self(refer below)

```
apiVersion: v1
data:
  myPassword: JHtkYm5hbWU6PU5BfQ== (to base64 of this is ${dbname:=NA})
kind: Secret
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: my-secret-test
  namespace: my-namespace
type: Opaque
```

### Steps to reproduce

1. Please refer to the description 
2. I am trying to create a secret from an already existing secret using a substitute feature, this only works if I use the flux-system secret which is automatically created when I use the flux bootstrap command. But when i tried to import secret from another secret it giving me the above error.

### Expected behavior

This should be generated 
```
apiVersion: v1
data:
  myPassword: a2V5Y2xvYWs= (to base64 of this is keycloak)
kind: Secret
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: my-secret-test
  namespace: my-namespace
type: Opaque
```

### OS / Distro

Ubuntu (wsl), k8s cluster is created using k3d

### Flux version

flux version 0.22.0 I am using

### Flux check

► checking prerequisites
✗ flux 0.22.0 <0.24.0 (new version is available, please upgrade)
✔ Kubernetes 1.21.5+k3s2 >=1.19.0-0
► checking controllers
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.17.0
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.17.2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
