### ISSUE TITLE
Flux SOPS integration breaks in the presence of the Kustomize object

### ISSUE THREAD

**Issue by andrey-dubnik** [fluxcd/flux2#2145]
### Describe the bug

Hi, I'm not sure if this is a bug or expected behaviour but I can't use Flux Kustomize with SOPS when resources are being Kustomized...

### Steps to reproduce

Create Kust resource

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: deploy-observability
  namespace: kuma-system 
spec:
  targetNamespace: kuma-watch
  interval: 3m
  sourceRef:
    kind: GitRepository
    name: kuma-system
    namespace: flux-system
  path: ./observability/base
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
```

observability/base content:

.sops.yaml - SOPS meta
dd-api-key.yaml - k8s secret
kustomization.yaml

kustomization.yaml content:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dd-api-key.yaml
```

If there is a kustomization.yaml present then I'm getting an error

> decryption failed for 'metrics-collector-config': LoadEncryptedFile: sops metadata not found

If I remove the kustomization.yaml file and leave only the base then Flux Kustomize succeeds 

### Expected behavior

should be possible to use SOPS with kustomize.yaml present

### OS / Distro

Linux

### Flux version

v0.23

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Have you configured SOPS to encrypt only `data` and `stringData`? Docs here: https://fluxcd.io/docs/components/kustomize/kustomization/#secrets-decryption

**Comment by andrey-dubnik** [comment]
I have just found some piece of code in the recursive folders which was causing a failure in recursive folders

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dd-api-key.yaml
  - ../prometheus
  - ../otel

otel folder contains another set of SOPS rules

.sops.yaml
collector.yaml - this is a configmap encrypted with SOPS

I'm getting this if I don't get rid of encryption in the subfolder

> decryption failed for 'metrics-collector-config': LoadEncryptedFile: sops metadata not found

**Comment by andrey-dubnik** [comment]
Does Flux only support k8s secrets? Or it can also decrypt other objects (in this case I may have to debug further)?

**Comment by stefanprodan** [comment]
Flux can decrypt only Kubernetes objects with `metadata` in clear. Also `. sops.yaml` is not a Kubernetes object, make sure you don't include it in `kustomization.yaml` resources.

**Comment by andrey-dubnik** [comment]
I'm not including the .sops.yaml in the kustomization.yaml but indeed the collector.yaml is not a plain k8s object, we are using it to generate the configmap and I guess the issue is occurring because of that so the sequencing of events makes a difference...

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kuma-watch
resources:
  - deployment.yaml
configMapGenerator:
- name: metrics-collector-config
  files:
  - collector.yaml
  options:
    disableNameSuffixHash: true
```

Thanks for the help!
