### ISSUE TITLE
postBuild substitute is setting the template variables to the empty values

### ISSUE THREAD

**Issue by andrey-dubnik** [fluxcd/flux2#2148]
### Describe the bug

Hi, I have a kustomization

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: deploy-observability
  namespace: kuma-system # TODO kuma-system should be excluded from the OPA policy which manages the FluxCD tenants
spec:
  targetNamespace: kuma-watch
  interval: 3m
  sourceRef:
    kind: GitRepository
    name: kuma-system # TODO register this repo in FluxCD
    namespace: flux-system
  path: ./observability/base
  prune: true
  validation: client
  postBuild:
    substitute:
      CLUSTER_NAME: cluster-a
      ENVIRONMENT_NAME: dev
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
```

And the template like this

```
exporters:
    datadog:
        api:
            key: "${DD_API_KEY}"
            site: datadoghq.eu
        tags:
            - app:servicemesh
            - env:${ENVIRONMENT_NAME}
            - zone:${CLUSTER_NAME}
            - service:kuma
            - business_platform:servicemesh
            - brand:maersk
            - team:purplesea
```

If I use substitute Flux also replaces the ${DD_API_KEY} with the empty value which breaks the template... Is this a normal behaviour?

### Steps to reproduce

Apply postBuild in a kustomization 

postBuild:
    substitute:
      CLUSTER_NAME: cluster-a
      ENVIRONMENT_NAME: dev

To the template folder where with the files having ${SOMETHING_ELSE} additionally to the postBuild scope

### Expected behavior

only substitute what's been asked for

### OS / Distro

Linux

### Flux version

v0.17

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
