### ISSUE TITLE
patchesJson6902 doesn't work when using kustomize variables

### ISSUE THREAD

**Issue by mikalai-t** [fluxcd/flux2#2151]
### Describe the bug

It seems `Kustomization` controller, if there is a kustomize variable in the `metadata`, uses another technique when building final manifest in such a way so the _base_ resource remains untouched and not patched!

### Steps to reproduce

1. create a git repo and configure appropriate `GitRepository` and `Kustomization` objects:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 3m
  timeout: 60s
  url: ssh://git@bitbucket.org/...
  ref:
    branch: master
  secretRef:
    name: flux-git-deploy
```
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: test
  namespace: flux-system
spec:
  force: false
  interval: 1m0s
  path: .
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
```
2. In that repo create following structure
```
.
|
├ base
|  |
|  └ cm.yaml
|
├ overlays
|  |
|  └ cm-overlay.yaml
|
├ apps.env
├ kustomization.yaml
└ kustomizeconfig.yaml
```
3. Configs
```yaml
# base/cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: $(env)-test
  namespace: default
data:
  var1: value1
```
```yaml
# overlays/cm-overlay.yaml
- op: replace
  path: /data
  value:
    var2: value2
```
```ini
# apps.env
env=dev
```
```yaml
# kustomization.yaml
configurations:
- kustomizeconfig.yaml

resources:
  - base/cm.yaml

patchesJson6902:
- target:
    group: ""
    version: v1
    kind: ConfigMap
    name: $(env)-test
    namespace: default
  path: overlays/cm-overlay.yaml

generatorOptions:
  labels:
    "kustomize.generated": "true"
  disableNameSuffixHash: true

configMapGenerator:
- name: test-kustomization-config
  namespace: default
  behavior: create
  envs:
    - apps.env

vars:
- name: env
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: test-kustomization-config
  fieldref:
    fieldpath: data.env
```
```yaml
varReference:
- kind: ConfigMap
  path: metadata/name
```
4. Sync changes with the remote and wait for reconcilation, the result in the Kubernetes cluster will be:
```shell
kubectl get cm -n default dev-test -o yaml
```
```yaml
apiVersion: v1
data:
  var1: value1
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-29T10:05:26Z"
  labels:
    kustomize.toolkit.fluxcd.io/name: test
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:var1: {}
      f:metadata:
        f:labels:
          f:kustomize.toolkit.fluxcd.io/name: {}
          f:kustomize.toolkit.fluxcd.io/namespace: {}
    manager: kustomize-controller
    operation: Apply
    time: "2021-11-29T10:05:26Z"
  name: dev-test
  namespace: default
  resourceVersion: "159991199"
  selfLink: /api/v1/namespaces/default/configmaps/dev-test
  uid: 3e998751-280d-4820-adc3-b88f80700a16
```

### Expected behavior

Result must be the same as the local `kustomize build .` run:
```yaml
apiVersion: v1
data:
  var2: value2
kind: ConfigMap
metadata:
  name: dev-test
  namespace: default
---
apiVersion: v1
data:
  env: dev
kind: ConfigMap
metadata:
  labels:
    kustomize.generated: "true"
  name: test-kustomization-config
  namespace: default
```

### OS / Distro

Debian 10.11

### Flux version

v0.23.0

### Flux check

► checking prerequisites
✗ flux 0.23.0 <0.24.0 (new version is available, please upgrade)
✗ Kubernetes version v1.18.20-eks-8c579e does not match >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.13.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.17.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.13.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.18.0

### Git provider

Bitbucket

### Container Registry provider

N/A

### Additional context

1. Version of `kustomize` installed locally:
```
kustomize version
{Version:kustomize/v3.8.4 GitCommit:8285af8cf11c0b202be533e02b88e114ad61c1a9 BuildDate:2020-09-19T15:39:21Z GoOs:linux GoArch:amd64}
```

2. Upgraded Flux to `v0.23.0` after facing this issue on Flux `v0.16.2`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
