### ISSUE TITLE
Helm chart latest version not picked up

### ISSUE THREAD

**Issue by mariusrugan** [fluxcd/flux2#2185]
### Describe the bug

hi,

Flux helm-controller cannot find & pull Traefik latest chart and pulls 2 versions ago if left to decide.
Please advise, thanks!

### Steps to reproduce

using as per below HelmRelease,HelmRepository combo,
flux 0.24.0,

```
flux: v0.24.0
helm-controller: v0.14.0
kustomize-controller: v0.18.1
notification-controller: v0.19.0
source-controller: v0.19.0
```

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 10.7.1
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 10m
``` 
with

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik-charts
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.traefik.io/traefik
  timeout: 3m
```

cannot find latest chart, although helm CLI can,

```
chart pull error: failed to get chart version for remote reference: no 'traefik' chart with version matching '10.7.1' found
```

```
helm show all traefik/traefik | more
```

```
apiVersion: v2
appVersion: 2.5.4
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
keywords:
- traefik
- ingress
maintainers:
- email: emile@vauge.com
  name: emilevauge
- email: daniel.tomcej@gmail.com
  name: dtomcej
- email: ldez@traefik.io
  name: ldez
name: traefik
sources:
- https://github.com/traefik/traefik
- https://github.com/traefik/traefik-helm-chart
type: application
version: 10.7.1
```

if version is omitted in HelmRelease to leave it up to flux, pull 2 versions ago, 10.6.2
```
NAME   	READY	MESSAGE                         	REVISION	SUSPENDED
traefik	True 	Release reconciliation succeeded	10.6.2  	False
```

### Expected behavior

Flux should pull latest specified in index.yaml

### OS / Distro

MacOS 

### Flux version

v0.24.0

### Flux check

```
► checking prerequisites
✔ Kubernetes 1.21.5-gke.1302 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.14.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.19.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.19.0
✔ all checks passed


### Git provider

_No response_

### Container Registry provider

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
