### ISSUE TITLE
Reconciliation succeeds when using SOPS decryption, but CLI is reporting it failed

### ISSUE THREAD

**Issue by gowthamgts** [fluxcd/flux2#2206]
### Describe the bug

My goal is to deploy a helm chart from a repo with secrets encrypted with SOPS. I tried the `podinfo` repo and I was able to deploy it and see flux reconciling it properly and all worked good. Then, I proceeded to test out `HelmRelease` with encrypted secrets, but for some reason I was getting the following error:

```
✗ Kustomization reconciliation failed: Secret/default/basic-auth is SOPS encryted, configuring decryption is required for this secret to be reconciled
```

upon digging deep and many retries later, I found out that the secrets are properly decrypted by SOPS pgp, but the CLI was the only one throwing the above problem. I'm not sure whether I'm doing something wrong or it's a bug.

### Steps to reproduce

1. create a kind cluster and load the pgp key into the `flux-system` namespace as per documentation: https://fluxcd.io/docs/guides/mozilla-sops/#generate-a-gpg-key
2. create a kustomize file for having sops decryptor:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secrets-decryptor
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
```
3. load the encrypted secret to the repo under `clusters/kind`:
```
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: default
stringData:
  values.yaml: ENC[AES256_GCM,data:R50Uk8YQEi4PkH8Pg0K8gYJglY5j8XxMVw==,iv:mwH4xzRsU1fnD+QfKwmuUfe9GCTllaqGuGEu7JNVgLk=,tag:nYTUsi05laY3Ejt+ti581g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2021-12-11T07:47:11Z"
  mac: ENC[AES256_GCM,data:ozO2Sj/e6yI1K3mlFcOqOfMTXwN5TrTI4OBiV4nFLURV8iiaOHF9eVnPH1MvOoMde0WJ8tFBxZWjxurXkxA2hUmqenGFWiCUuGH+lQWhgmNVxppUriuJVubzmODjhX3F9ZkkZEbaEhYrWWLvPrkyYUCcxTrni/3IxLoiv6dIrUo=,iv:TxBEbhY7MYV7PvIzYJgoMNoNM0ydeTplfydvbA3h6vk=,tag:jxCBYI4KSWXjPuADpFa0rQ==,type:str]
  pgp:
    - created_at: "2021-12-11T07:47:10Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMAz+ZodgEye+kARAAm8KVeOG6UdflHKSlvSdm6wRBR1kIUATFCGFx4igPHJl5
        EywDZmN/fKWgaWCJF5ouQr7102Jkpa1TDyJvMeLcoAOPmY9SGBBFLSBcrATtyXEM
        lD17so6LMCMtVReGjTGtR9MfR5GGR/gqQ6ocQhyzISdU6hFeNOB6YjKNLUU55i+J
        ZUHNCqxlV0Y4c0j8BlyDzp4UgLetUL+LTlU9EIii2Cft7L16LTpeEJrwh0/tG29i
        o7GPhHRwI9dQFlyZsAYJKAgmBCASxAZ0+z+COCssm270Arv71nkhgbgrJVv9THer
        9vTXpURny+x59IlU+J6SwIY425/D8UlBW0OLnWkwrH5QInFDDGibMzYfkdaYOzNu
        8TQc0gdwVLyLJxv+DB1lNXO6qBR2MLq9paJGBDdvRx1NzzpfrP4xvxnGbRRfY7q+
        KaPsb/gJWvYgiZRrA8BpgYGuWJJHtPRbQT8iYD0cxeZ8Fb031QEJv0UJOWsyWkx2
        5/jv6XDUMgo/LWj4t4+SawvXih7Z6Ze2Ylb1dKXArrPLhkvJbndCzj+UAtgdE4t9
        USQStc+ib8U8veBashEDL+Br4bY7t9rn7Yk7NQaD14rkwWnVq7yyfVNR91+9JdBP
        6Gz7T/9u5BGwYb5QnmLp4DU5zx/Li4tmtkRy7yJnajAVb4ei+mZhk9ag6yKI09fU
        ZgEJAhDUvTHYgqNp+ugIQ7k0PoVOl/f50k/DYsyd1QhkKBo1RvROXnHFM33zvPW3
        0IAsSQlNLWfTU/YCtnyERbS2Fks6cFvc9Z2RQrvaEdW9yuZ8vP7Y2f4ZjF6LXoDy
        aj34bM7p1w==
        =hOdo
        -----END PGP MESSAGE-----
      fp: 76ADA0B8EE4F8883B65AF7B92EA5CCADB6D2D911
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
```
4. commit the changes and reconcile.

### Expected behavior

reconcile should succeed without any problems. Right now, i'm able to see the secret loaded properly, but the `flux get all -A` tells me otherwise:
```
NAMESPACE  	NAME                     	READY	MESSAGE                                                          	REVISION                                       	SUSPENDED 
flux-system	gitrepository/flux-system	True 	Fetched revision: master/c9ad370a957c049b33127810df8196582805c3c6	master/c9ad370a957c049b33127810df8196582805c3c6	False    	

NAMESPACE  	NAME                           	READY	MESSAGE                                                                                                        	REVISION                                       	SUSPENDED 
flux-system	kustomization/flux-system      	False	Secret/default/basic-auth is SOPS encryted, configuring decryption is required for this secret to be reconciled	master/26facfe9554fae4e1cc627022aead0470893fbae	False    	
flux-system	kustomization/secrets-decryptor	True 	Applied revision: master/c9ad370a957c049b33127810df8196582805c3c6                                              	master/c9ad370a957c049b33127810df8196582805c3c6	False    	
```

### OS / Distro

macOS with kind default cluster

### Flux version

flux: v0.24.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.1 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.14.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.18.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.14.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.19.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.19.2
✔ all checks passed

### Git provider

github

### Container Registry provider

both ghcr and docker.io

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Place the secret YAML outside the clusters dir, for example in the Git root under the `secrets` dir. Then place the `secrets-decryptor` Kustomization inside the `clusters/kind`, then set the the path to secrets with:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secrets-decryptor
  namespace: flux-system
spec:
  path: "./secrets" 
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
```
