### ISSUE TITLE
HelmRelease wrong HelmChart selection

### ISSUE THREAD

**Issue by AzSiAz** [fluxcd/flux2#2236]
### Describe the bug

`HelmCharts` name always get prefixed with `HelmRelease` namespace before chart name, so `HelmChart` not ready and chart is never deployed

### Steps to reproduce

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: sealed-secrets
      version: v0.17.1
  interval: 2h
  values:
    nodeSelector: 
      kubernetes.io/hostname: k3s-master-1
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 24h
  url: https://bitnami-labs.github.io/sealed-secrets
```

### Expected behavior

Use HelmChart `flux-system/sealed-secrets`

### OS / Distro

MacOS

### Flux version

v0.24.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.5+k3s2 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.14.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.19.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.19.2
✔ all checks passed

### Git provider

Gitlab

### Additional context

HelmChart 'flux-system/kube-system-sealed-secrets' is not ready

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gecube** [comment]
I workaorund this issue by 
1. ```yaml
metadata:
  name: sealed-secrets
  namespace: kube-system```
changing to 
```yaml
metadata:
  name: sealed-secrets
  namespace: flux-system
```
2. Adding target namespace in `HelmRelease`
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  chart:
...
  install:
    createNamespace: true
  targetNamespace: kube-system
```

**Comment by stefanprodan** [comment]
> version: v0.17.1

Helm uses strict semver, remove the `v` prefix.

**Comment by AzSiAz** [comment]
> Helm uses strict semver, remove the `v` prefix.

Sorry but this does not solve my issue, but thanks for pointing it out

HelmRelease still use wrong HelmChart/HelmRepository as you can see here
<img width="1387" alt="Capture d’écran 2022-01-03 à 15 11 44" src="https://user-images.githubusercontent.com/7109680/147940489-294e5263-301d-43bb-b611-430e505877ef.png">

**Comment by gecube** [comment]
I think that I was able to reproduce the bug. Let's make the next setup:

```
kubectl get helmrepository -A
NAMESPACE     NAME            URL                                          READY   STATUS                                                                               AGE
flux-system   centrigufal     https://centrifugal.github.io/helm-charts    True    Fetched revision: 5d266c28111c1b9fada891c3a60edbff392f4050fa78c6835c120f48efa57e23   9m10s
flux-system   ingress-nginx   https://kubernetes.github.io/ingress-nginx   True    Fetched revision: b67e10d002be11c3bd121f8f5fe2d1d50213460f70fc708c11247cd995a818d6   3d10h
flux-system   jetstack        https://charts.jetstack.io                   True    Fetched revision: a9e13d130da94b2a1f4bd9eb4e07dfa1b83257eff8d64e58b19bb41fad9d3340   3d10h
```
Firstly, we create a helmrepository in `flux-system` called `centrifugal`.
Then we'd like to install helm chart centrifugo from `centrifugal` repo in particular namespace like test.
So I created corresponding HelmRelease:
```
kubectl get helmrelease -A
NAMESPACE     NAME            READY   STATUS                                                 AGE
flux-system   cert-manager    True    Release reconciliation succeeded                       3d10h
flux-system   ingress-nginx   True    Release reconciliation succeeded                       3d10h
test          centrifugo      False   HelmChart 'flux-system/test-centrifugo' is not ready   8m
```
with the such manifest:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: centrifugo
  namespace: test
spec:
  chart:
    spec:
      chart: centrifugo
      sourceRef:
        kind: HelmRepository
        name: centrifugal
        namespace: flux-system
      version: '*'
  interval: 1m0s
  values:
```
Everything looks reasonable, yes?
But in fact I see the next errors:

```
flux get all -A
...
NAMESPACE  	NAME                               	READY	MESSAGE                                                                                   	REVISION	SUSPENDED 
...
flux-system	helmchart/test-centrifugo          	False	failed to retrieve source: HelmRepository.source.toolkit.fluxcd.io "centrifugal" not found	        	False    	
```
and from logs of source-controller:
```
{"level":"error","ts":"2022-01-07T17:27:18.909Z","logger":"controller.helmchart","msg":"Reconciler error","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmChart","name":"test-centrifugo","namespace":"flux-system","error":"failed to retrieve source: HelmRepository.source.toolkit.fluxcd.io \"centrifugal\" not found"}
```

```
kubectl describe -n flux-system helmchart test-centrifugo 
Name:         test-centrifugo
Namespace:    flux-system
Labels:       <none>
Annotations:  <none>
API Version:  source.toolkit.fluxcd.io/v1beta1
Kind:         HelmChart
Metadata:
  Creation Timestamp:  2022-01-07T17:21:50Z
  Finalizers:
    finalizers.fluxcd.io
  Generation:  1
...
    Manager:         source-controller
    Operation:       Update
    Time:            2022-01-07T17:21:50Z
  Resource Version:  5944222
  UID:               b2032223-003f-49de-8af6-d41e111035b9
Spec:
  Chart:               centrifugo
  Interval:            1m0s
  Reconcile Strategy:  ChartVersion
  Source Ref:
    Kind:   HelmRepository
    Name:   centrifugal
  Version:  *
Status:
  Conditions:
    Last Transition Time:  2022-01-07T17:27:18Z
    Message:               failed to retrieve source: HelmRepository.source.toolkit.fluxcd.io "centrifugal" not found
    Reason:                ChartPullFailed
    Status:                False
    Type:                  Ready
  Observed Generation:     1
Events:                    <none>
```
and SourceRef in HelmChart does not contain namespace filed.

The only option was to use the next HelmRelease and HelmChart

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: centrifugo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: centrifugo
      sourceRef:
        kind: HelmRepository
        name: centrigufal
      version: '*'
  install:
    createNamespace: true
  targetNamespace: centrifugo
  interval: 1m0s
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: centrigufal
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://centrifugal.github.io/helm-charts
```

I really feel that I miss something.

### Expected behaviour:

I can create HelmRepository in one random choosen namespace and reference it in HelmRelease from any other namespace.

**Comment by javiermarasco** [comment]
I am facing the same issue using AKS and an Azure container registry (oci). Here is my config.


```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helmrepo1
  namespace: flux-system
spec:
  type: oci
  interval: 5m0s
  url: oci://xxxxxxxxxxxxx.azurecr.io/helm
  secretRef:
    name: acr-user-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-user-secret
  namespace: flux-system
stringData:
  username: xxxxxxxxxxxx
  password: xxxxxxxxxxxxxx
```
```
NAME        URL                                         AGE     READY   STATUS
helmrepo1   oci://xxxxxxx.azurecr.io/helm   3h25m   True    Helm repository is ready
```

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: default-app
  namespace: app1
spec:
  interval: 5m
  chart:
    spec:
      chart: helm/default_app
      version: '0.1.1'
      sourceRef:
        kind: HelmRepository
        name: helmrepo1
        namespace: flux-system
      interval: 1m
  targetNamespace: app1
  values:
    deployment.replicas: 2
```

```
NAME          AGE     READY   STATUS
default-app   3h28m   False   HelmChart 'flux-system/app1-default-app' is not ready
```

I don't get why it is trying to make the name of the helm chart like `flux-system/app1-default-app`.

Does anyone have this same problem? am I doing something wrong in my manifests?
