### ISSUE TITLE
Flux reconciliation fails due to cert-manager ClusterIssuer resource

### ISSUE THREAD

**Issue by tyzbit** [fluxcd/flux2#2243]
### Describe the bug

Adding a ClusterIssuer to a Kustomization repository throws this error very often:

```
flux reconcile source git flux-system; flux reconcile kustomization flux-system
► annotating GitRepository flux-system in flux-system namespace
✔ GitRepository annotated
◎ waiting for GitRepository reconciliation
✔ fetched revision main/5f3811da381d53211478ec72d777e336d9ea2ea8
► annotating Kustomization flux-system in flux-system namespace
✔ Kustomization annotated
◎ waiting for Kustomization reconciliation
✗ Kustomization reconciliation failed: ClusterIssuer/letsencrypt dry-run failed, error: failed to prune fields: failed add back owned items: failed to convert pruned object at version cert-manager.io/v1alpha2: conversion webhook for cert-manager.io/v1, Kind=ClusterIssuer returned invalid metadata: invalid metadata of type <nil> in input object
```

Adding the `fluxcd.io/ignore: "true"` annotation doesn't seem to stop this resource from trying to be pruned either.

### Steps to reproduce

cert-manager:
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 10m
  timeout: 1m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: "v1.2.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 1m0s
  values:
    installCRDs: true
```

ClusterIssuer:
```
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: redacted@example.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - http01:
        ingress:
          class: nginx
    - dns01:
        cloudflare:
          email: redacted@example.com
          apiKeySecretRef:
            name: cloudflare-global-apikey
            key: apikey
```

### Expected behavior

1. Flux reconciles with ClusterIssuers without error
2. Flux does not throw an error and correctly ignores a ClusterIssuer with the `fluxcd.io/ignore: "true"` annotation.

### OS / Distro

Darwin computer.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64

### Flux version

flux: v0.24.1

### Flux check

```
► checking prerequisites
✔ Kubernetes 1.20.10 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.16.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.13.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.16.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.17.2
✔ all checks passed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
