### ISSUE TITLE
Source Controller Bucket resource returning unspecified 400 error

### ISSUE THREAD

**Issue by Tzrlk** [fluxcd/flux2#2244]
### Describe the bug

A Bucket resource I've defined refuses to reconcile, but the only error message is literally "400 ". I have no idea what I need to fix, as the only provided stack-trace points to a generic controller workload processor loop.

### Steps to reproduce

1. Create an IRSA role for use with the source-controller.
2. Install flux with at least the source-controller using IRSA auth and debug logging enabled.
3. Create an S3 bucket.
4. Grant the IRSA role access to the s3 bucket.
5. Create a bucket resource.
6. Observe the error presented.

### Expected behavior

* When presented with the correct configuration, the Bucket resource should reconcile successfully and allow other controllers to access the configuration.
* If there are any issues with the configuration, or unforseen errors are thrown by the AWS API, the debug logs should contain an error message that identifies what went wrong with enough detail to assist with remediation. Details such as:
** The API method that failed.
** Full response information (headers + body).

### OS / Distro

EKS v1.21.2-eks-06eac09

### Flux version

flux: v0.24.0, source-controller: v0.19.0

### Flux check

flux check
► checking prerequisites
✗ flux 0.24.0 <0.24.1 (new version is available, please upgrade)
✔ Kubernetes 1.21.2-eks-06eac09 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► [redacted].dkr.ecr.ap-southeast-2.amazonaws.com/fluxcd/helm-controller:v0.14.0
✔ image-automation-controller: deployment ready
► [redacted].dkr.ecr.ap-southeast-2.amazonaws.com/fluxcd/image-automation-controller:v0.18.0
✔ image-reflector-controller: deployment ready
► [redacted].dkr.ecr.ap-southeast-2.amazonaws.com/fluxcd/image-reflector-controller:v0.14.0
✔ kustomize-controller: deployment ready
► [redacted].dkr.ecr.ap-southeast-2.amazonaws.com/fluxcd/kustomize-controller:v0.18.1
✔ notification-controller: deployment ready
► [redacted].dkr.ecr.ap-southeast-2.amazonaws.com/fluxcd/notification-controller:v0.19.0
✔ source-controller: deployment ready
► [redacted].dkr.ecr.ap-southeast-2.amazonaws.com/fluxcd/source-controller:v0.19.0
✔ all checks passed

### Git provider

N/A

### Container Registry provider

N/A

### Additional context

`flux logs`:
```
2021-12-23T23:44:52.257Z error Bucket/flux-master-config.flux-system - Reconciler error 400
```
`kubectl logs | jq`:
```json
{
  "level": "error",
  "ts": "2021-12-24T01:13:25.731Z",
  "logger": "controller.bucket",
  "msg": "Reconciler error",
  "reconciler group": "source.toolkit.fluxcd.io",
  "reconciler kind": "Bucket",
  "name": "flux-master-config",
  "namespace": "flux-system",
  "error": "400 ",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:227"
}
{
  "level": "debug",
  "ts": "2021-12-24T01:13:25.731Z",
  "logger": "events",
  "msg": "Normal",
  "object": {
    "kind": "Bucket",
    "namespace": "flux-system",
    "name": "flux-master-config",
    "uid": "e5387b55-7900-45cb-87cd-42a9de7ccda6",
    "apiVersion": "source.toolkit.fluxcd.io/v1beta1",
    "resourceVersion": "18564668"
  },
  "reason": "error",
  "message": "400 "
}
```
`kubectl describe`:
```yaml
Name:         flux-master-config
Namespace:    flux-system
Labels:       app.kubernetes.io/component=overlay
              app.kubernetes.io/instance=flux-master
              app.kubernetes.io/managed-by=terraform
              app.kubernetes.io/name=control
              app.kubernetes.io/part-of=flux
Annotations:  reconcile.fluxcd.io/requestedAt: 2021-12-24T13:43:17.1218197+13:00
API Version:  source.toolkit.fluxcd.io/v1beta1
Kind:         Bucket
Metadata:
  Creation Timestamp:  2021-12-07T00:05:30Z
  Finalizers:
    finalizers.fluxcd.io
  Generation:  2
  Managed Fields:
    [ omitted for brevity ]
  Resource Version:  18579606
  UID:               e5387b55-7900-45cb-87cd-42a9de7ccda6
Spec:
  Bucket Name:  [redacted]
  Endpoint:     s3.amazonaws.com
  Interval:     5s
  Provider:     aws
  Region:       ap-southeast-2
  Timeout:      30s
Status:
  Conditions:
    Last Transition Time:     2021-12-24T01:30:05Z
    Message:                  400 
    Reason:                   BucketOperationFailed
    Status:                   False
    Type:                     Ready
  Last Handled Reconcile At:  2021-12-24T13:43:17.1218197+13:00
  Observed Generation:        2
Events:
  Type    Reason  Age                  From               Message
  ----    ------  ----                 ----               -------
  Normal  error   49s (x25 over 106m)  source-controller  400
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
