### ISSUE TITLE
Permanent 'no such file or directory' on kustomization resource

### ISSUE THREAD

**Issue by gecube** [fluxcd/flux2#2245]
### Describe the bug

Hello!

If I make an erroneous kustomization resource which points to non-existing path, kustomization resource stuck in failed state.

### Steps to reproduce

1. Install flux
2. create gitops repo
3. add ./components/elastic-cloud/v1.9.1 catalogue with manifests
4. create kustomization in main catalogue: 
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: elastic-cloud
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./components/elastic-cloud/v.1.9.1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
```
5. make sync:
```bash
$ flux reconcile source git flux-system
$ flux get all -A
...
NAMESPACE  	NAME                     	READY	MESSAGE                                                        	REVISION                                     	SUSPENDED 
flux-system	gitrepository/flux-system	True 	Fetched revision: main/c562865e0748a10f1798d2e4e804032e5648997a	main/c562865e0748a10f1798d2e4e804032e5648997a	False    
...
flux-system	kustomization/elastic-cloud      	False	kustomization path not found: stat /tmp/elastic-cloud2228703098/components/elastic-cloud/v.1.9.1: no such file or directory
```
6. We found that we created bad file. Let's fix it:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: elastic-cloud
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./components/elastic-cloud/v1.9.1 # this path exists
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
```
7. make the sync again:
```bash
$ flux reconcile source git flux-system
$ flux get all -A
...
NAMESPACE  	NAME                     	READY	MESSAGE                                                        	REVISION                                     	SUSPENDED 
flux-system	gitrepository/flux-system	True 	Fetched revision: main/f47a5043ad2b2019de5dd27b653c8500bf8ccd96	main/f47a5043ad2b2019de5dd27b653c8500bf8ccd96	False    
...
flux-system	kustomization/elastic-cloud      	False	kustomization path not found: stat /tmp/elastic-cloud2228703098/components/elastic-cloud/v.1.9.1: no such file or directory
$ flux reconcile kustomization elastic-cloud
► annotating Kustomization elastic-cloud in flux-system namespace
✔ Kustomization annotated
◎ waiting for Kustomization reconciliation
✗ Kustomization reconciliation failed: kustomization path not found: stat /tmp/elastic-cloud3455281738/components/elastic-cloud/v.1.9.1: no such file or directory
$ flux get all -A
...
NAMESPACE  	NAME                     	READY	MESSAGE                                                        	REVISION                                     	SUSPENDED 
flux-system	gitrepository/flux-system	True 	Fetched revision: main/f47a5043ad2b2019de5dd27b653c8500bf8ccd96	main/f47a5043ad2b2019de5dd27b653c8500bf8ccd96	False    
...
flux-system	kustomization/elastic-cloud      	False	kustomization path not found: stat /tmp/elastic-cloud2228703098/components/elastic-cloud/v.1.9.1: no such file or directory
```
No further actions helps.

### Expected behavior

The kustomization resource will be updated according to new Kustomization manifest and successfully synced.

### OS / Distro

mac os x

### Flux version

flux: v0.24.0

### Flux check

```
flux check
► checking prerequisites
✗ flux 0.24.0 <0.24.1 (new version is available, please upgrade)
✔ Kubernetes 1.20.2 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.14.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.19.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.19.0
✔ all checks passed
```

### Git provider

gitlab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
