### ISSUE TITLE
Unable to validate or deploy Kustomizations due to 'Error: json: unknown field "spec"'

### ISSUE THREAD

**Issue by alanjjenkins** [fluxcd/flux2#2251]
### Describe the bug

When trying to validate Kustomizations using Kubeval using the [validate.sh](https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/scripts/validate.sh) script or deploy Kustomizations generated via the flux2 CLI I am getting the error: 
```
Error: json: unknown field "spec"
```
I did believe for a while it was something to do with some of the yaml I had written, that my CRDs were out of date or that there was something wrong with my flux2 install on my cluster however after examining the validate.sh script it is not using the Kubernetes cluster which rules out my cluster and it's flux2 install and it is using the latest flux crd schemas downloaded from https://github.com/fluxcd/flux2/releases/latest/download/crd-schemas.tar.gz and it is failing to validate yaml that is generated by...
```
flux create ks karpenter --source=GitRepository/flux-system --path="./infrastructure/karpenter/helmrelease/" --prune=true --interval=10m --export > kustomization.yaml
```

### Steps to reproduce

Ensure running the following versions of tools:
* flux2-cli: 0.24.1
* helm: version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
* kubeval --version
Version: 0.15.0
Commit: df50ea7fd4fd202458002a40a6a39ffbb3125bad
Date: 2020-04-14T09:32:50Z
* yq --version
yq version 4.9.8
```
flux create ks karpenter --source=GitRepository/flux-system --path="./infrastructure/karpenter/helmrelease/" --prune=true --interval=10m --export > kustomization.yaml
```
The contents of my ```./infrastructure/karpenter/helmrelease/``` directory is:
helmrelease.yaml:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  releaseName: karpenter
  targetNamespace: karpenter
  chart:
    spec:
      chart: karpenter
      version: "0.5.3"
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # defaults:
  # https://github.com/aws/karpenter/blob/main/charts/karpenter/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: karpenter-helm-values
      optional: false
```
kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease.yaml
```

### Expected behavior

Kubeval not to throw errors and the Kustomization to be able to apply without error.

### OS / Distro

N/A

### Flux version

flux: v0.24.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.2-eks-06eac09 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.14.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.19.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.19.2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
