### ISSUE TITLE
HelmRelease upgrade "uninstall" remediation strategy does not remove actual resources

### ISSUE THREAD

**Issue by artem-nefedov** [fluxcd/flux2#2299]
### Describe the bug

We have a case with helm chart that is guaranteed to fail on upgrade, so the only valid upgrade procedure is to uninstall the old version and install the new one. So, we set upgrade remediation strategy in HelmRelease to uninstall:

```yaml
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 1
      strategy: uninstall
```

After applying new version, HelmRelease status shows that it did perform uninstall, but the subsequent installation still failed:

```yaml
status:
  conditions:
  - lastTransitionTime: "2022-01-14T17:04:57Z"
    message: 'Helm install failed: admission webhook "vtargetgroupbinding.elbv2.k8s.aws"
      denied the request: TargetGroup <redacted>
      is already bound to TargetGroupBinding <redacted>'
    reason: InstallFailed
    status: "False"
    type: Ready
  - lastTransitionTime: "2022-01-14T17:04:57Z"
    message: |-
      Helm install failed: admission webhook "vtargetgroupbinding.elbv2.k8s.aws" denied the request: TargetGroup <redacted> is already bound to TargetGroupBinding <redacted>

      Last Helm logs:

      creating 1 resource(s)
    reason: InstallFailed
    status: "False"
    type: Released
  - lastTransitionTime: "2022-01-14T17:05:01Z"
    message: Helm uninstall succeeded
    reason: UninstallSucceeded
    status: "True"
    type: Remediated
  failures: 8
  helmChart: <redacted>
  installFailures: 7
  lastAppliedRevision: 1.1.0
  lastAttemptedRevision: 1.2.0
  lastAttemptedValuesChecksum: 12c48b01b3ac1007209f0cde21a813092c12b58d
  observedGeneration: 2
  upgradeFailures: 1
```

The problem caused by the fact that actual resources that are created by previous version of helm chart were not removed. This is despite the fact that chart itself appears to be removed (it no longer shows in the output of "helm list" command).

Even worse, if you delete HelmRelease while it's in this state, those resources will be left in the cluster, and will remain there permanently! This is despite the fact that all resources still have annotations indicating they are managed by helm.

If you just delete successfully reconciled HelmRelease normally, all resources are removed correctly. The problem only seem to occur with "uninstall" remediation strategy.

### Steps to reproduce

1. apply HelmRelease with "uninstall" remediation strategy
2. upgrade to chart version that:
  a) is guaranteed to fail on direct upgrade
  b) changes the names of some resources (compared to previous version)
3. confirm that HelmRelease is failed to reconcile
4. check that resource names created by previous version still exist
5. (optionally) delete HelmRelease and confirm that resources are still there

### Expected behavior

Previous chart version is fully uninstalled (including resouces), then new version is installed from scratch

### OS / Distro

N/A

### Flux version

N/A

### Flux check

fluxcd/helm-controller:v0.15.0
fluxcd/kustomize-controller:v0.19.1
fluxcd/source-controller:v0.20.1

### Additional context

In our case, resources that helm chart installs are [TargetGroupBindings](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/targetgroupbinding/targetgroupbinding/) used by AWS Load Balancer Controller to connect to externally created target groups. The way names of the objects are generated was changed in the newer helm chart version, but the controller does not allow more than one TargetGroupBinding to reference the same target group, so we need to uninstall previous version first.

Note that these resources do have custom finalizers that are handled by AWS LB Controller.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
