### ISSUE TITLE
Force equal true. Replaces for StatefulSets.

### ISSUE THREAD

**Issue by KrisJohnstone** [fluxcd/flux2#2328]
### Describe the bug

So the doco around force, [says](https://fluxcd.io/docs/components/kustomize/kustomization/):

> "// Force instructs the controller to recreate resources
> // when patching fails due to an immutable field change.
> // +kubebuilder:default:=false
> // +optional
> Force bool `json:"force,omitempty"

This works for Deployments in my tests so far, but doesn't for statefulsets. Based on the above I would have expected statefulsets to be deleted and reapplied. Except that I'm receiving the following error:

> "StatefulSet/mbr-rabbitmq-ptg/rabbitmq dry-run failed, reason: Invalid,
>  error: StatefulSet.apps "rabbitmq" is invalid: spec: Forbidden: updates
>  to statefulset spec for fields other than 'replicas', 'template', and
>  'updateStrategy' are forbidden"

There is a workaround of sorts which is to set prune: false, delete the SS, add back the overlays (note nice but it works). Alternatively you can simply delete the kustomize object and recreate it but that means you lose *all* your objects and creates more risk in terms of what items are ephemeral or don't like being wiped and recreated (i.e. ops-manager) etc.

Using the recommended kube labels means you need to update the version resource each deployment meaning the above becomes a every deployment exercise.

### Steps to reproduce

1. Setup an overlays containing a statefulset, for example:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    application: rabbitmq
    environment: ${environment}
    project: def
  name: rabbitmq
  namespace: def-rabbitmq-${environment}
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      application: rabbitmq
  serviceName: rabbitmq
  template:
    metadata:
      labels:
        application: rabbitmq
    spec:
      containers:
      - env:
```

2. Add new labels or use a label transformer to add new labels e.g.:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: rabbit
    app.kubernetes.io/created-by: kustomization-controller
    app.kubernetes.io/instance: rabbitmq-${environment}
    app.kubernetes.io/managed-by: fluxcd
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: abc
    app.kubernetes.io/version: 3.8.17
    application: rabbitmq
    environment: ${environment}
    project: def
  name: rabbitmq
  namespace: def-rabbitmq-${environment}
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbit
      app.kubernetes.io/created-by: kustomization-controller
      app.kubernetes.io/instance: rabbitmq-${environment}
      app.kubernetes.io/managed-by: fluxcd
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/part-of: abc
      app.kubernetes.io/version: 3.8.17
      application: rabbitmq
  serviceName: rabbitmq
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rabbit
        app.kubernetes.io/created-by: kustomization-controller
        app.kubernetes.io/instance: rabbitmq-${environment}
        app.kubernetes.io/managed-by: fluxcd
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/part-of: abc
        app.kubernetes.io/version: 3.8.17
        application: rabbitmq
    spec:
      containers:
      - env:
```
3. Commit changes. When kustomize reconciles it'll have an issue.
4. Set force to true and there will still be issues.
5. If I delete the SS manually, kustomize still wont place it back sadly.

### Expected behavior

Given force should delete and replace items that fail a merge, would expect overlays with the value set to true to replace the items. 

### OS / Distro

OpenShift 4.7

### Flux version

v0.20.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.20.11+c343126 >=1.19.0-0
► checking controllers
✔ all checks passed

### Git provider

TFS :(

### Container Registry provider

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
