### ISSUE TITLE
${VARIABLES} fail substitution in manifests and will not apply to cluster through Flux.

### ISSUE THREAD

**Issue by TheNakedZealot** [fluxcd/flux2#2360]
### Describe the bug

Using ${VARIABLES} in my manifests and attempting to `substitute` with Kustomize fails with the following error...

`"error":"Cluster/default/${CLUSTER_NAME} dry-run failed, reason: Invalid, error: Cluster.cluster.x-k8s.io \"${CLUSTER_NAME}\" is invalid: metadata.name: Invalid value: \"${CLUSTER_NAME}\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')\n"}`

The same manifest when using `kustomize build ./manifests/ | $GOPATH/bin/envsubst ` shows the correct variables replaced by envsubst.

### Steps to reproduce

1. Install Flux via Terraform Operator to brand-new 1.22.4 Kubernetes Cluster.
2. Write a cluster deployment manifest using ${VARIBLES} (our manifest is meant to bring up a managed AKS cluster using the Cluster API/CAPZ, latest versions)
3. Write a Kustomize manifest to substitute the variables with values.
4. Flux attempts to reconcile cluster from repository with an error.

### Expected behavior

Expect the variables in the manifest to be substituted for the values in the Kustomization manifest.

### OS / Distro

macOS 12.1

### Flux version

v0.26.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.4 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.15.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.19.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.20.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.20.1
✔ all checks passed

### Git provider

Azure DevOps (libgit2)

### Container Registry provider

Azure Container Registry

### Additional context

"error":"Cluster/default/${CLUSTER_NAME} dry-run failed, reason: Invalid, error: Cluster.cluster.x-k8s.io \"${CLUSTER_NAME}\" is invalid: metadata.name: Invalid value: \"${CLUSTER_NAME}\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')\n"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Post here the Flux Kustomization manifest please.

**Comment by TheNakedZealot** [comment]
> apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: developer-enablement
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: dreamcast
    namespace: flux-system
  path: ./mgmt/clusters/developer-enablement
  prune: true
  targetNamespace: default
  validation: client
  postBuild:
    substitute:
      var_substitution_enabled: "true"
      CLUSTER_NAME: "developer-enablement"
      CLUSTER_IDENTITY_NAME: ""
      AZURE_CLUSTER_IDENTITY_SECRET_NAME: "cluster-identity-secret"
      CLUSTER_IDENTITY_NAMESPACE: "default"
      KUBERNETES_VERSION: v1.22.4
      AZURE_CLIENT_ID: ""
      AZURE_TENANT_ID: ""
    substituteFrom:
      - kind: Secret
        name: developer-enablement-secret

**Comment by SomtochiAma** [comment]
Can you post the cluster yaml?

**Comment by TheNakedZealot** [comment]
Absolutely, thank you for the assistance.

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - 10.12.0.0/16
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: ${CLUSTER_NAME}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: ${CLUSTER_NAME}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
spec:
  additionalTags:
    jobName: ${JOB_NAME:=""}
    creationTimestamp: ${TIMESTAMP:=""}
    buildProvenance: ${BUILD_PROVENANCE:=""}
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: ${CLUSTER_IDENTITY_NAME}
    namespace: ${CLUSTER_IDENTITY_NAMESPACE}
  location: eastus
  resourceGroupName: ${CLUSTER_NAME}
  sshPublicKey: ${AZURE_SSH_PUBLIC_KEY_B64:=""}
  subscriptionID: ${AZURE_SUBSCRIPTION_ID}
  version: ${KUBERNETES_VERSION}
  networkPolicy: azure
  networkPlugin: azure
  sku: Paid
  loadBalancerProfile:
    managedOutboundIPs: 6
    idleTimeoutInMinutes: 9
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: agentpool0
  namespace: default
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: 1
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: ${CLUSTER_NAME}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: agentpool0
      version: ${KUBERNETES_VERSION}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: agentpool0
  namespace: default
spec:
  maxPods: 40
  mode: System
  osDiskSizeGB: 60
  osDiskType: Managed
  sku: Standard_D16_v4
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: agentpool1
  namespace: default
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: 1
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: ${CLUSTER_NAME}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: agentpool1
      version: ${KUBERNETES_VERSION}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: agentpool1
  namespace: default
spec:
  maxPods: 250
  mode: User
  osDiskSizeGB: 512
  osDiskType: Ephemeral
  sku: Standard_F64s_v2
  scaling:
    minSize: 2
    maxSize: 24
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  name: ${CLUSTER_IDENTITY_NAME}
  namespace: default
spec:
  allowedNamespaces: {}
  clientID: ${AZURE_CLIENT_ID}
  clientSecret:
    name: ${AZURE_CLUSTER_IDENTITY_SECRET_NAME}
    namespace: ${AZURE_CLUSTER_IDENTITY_SECRET_NAMESPACE}
  tenantID: ${AZURE_TENANT_ID}
  type: ServicePrincipal
```

**Comment by SomtochiAma** [comment]
I am unable to replicate this.
```
$ k get cluster -n default 
NAME                   PHASE          AGE   VERSION
developer-enablement   Provisioning   42s 
```

My kustomization.yaml
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  force: true
  interval: 1m0s
  path: ./clusters/another-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
    namespace: flux-system
  postBuild:
    substitute:
      CLUSTER_NAME: "developer-enablement"
```

My Cluster yaml
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - 10.12.0.0/16
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: ${CLUSTER_NAME}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: ${CLUSTER_NAME}
```

I am also on flux version `0.26.0`.  The only difference is I don't have a `substituteFrom` secret. 
What fields are in your secret so I can try creating one too.

**Comment by stefanprodan** [comment]
The error log was stripped of metadata like the Kustomization name and namespace. My guess is that the `developer-enablement` Kustomization is not the one applying these manifests or these manifests are applied by conflicting Kustomizations.

**Comment by TheNakedZealot** [comment]
Here's the entire error log line from the Kustomize Controller logs. I bolded the important bits.

```
{"level":"error","ts":"2022-02-01T16:18:24.031Z","logger":"controller.kustomization","msg":"Reconciliation failed after 127.100335ms, next try in 10m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","revision":"main/9c81fd4cbd28aac0f56508e4da9347dd9af0344f","error":"Cluster/default/${CLUSTER_NAME} dry-run failed, reason: Invalid, error: Cluster.cluster.x-k8s.io \"${CLUSTER_NAME}\" is invalid: metadata.name: Invalid value: \"${CLUSTER_NAME}\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')\n"}
```

and the Secret yaml...

```
apiVersion: v1
kind: Secret
metadata:
  name: developer-enablement-secret
  namespace: default
type: Opaque
data:
  AZURE_SUBSCRIPTION_ID: <base64 encoded value>
  ```
