### ISSUE TITLE
flux build|diff kustomization fails: ✗ failed to decode secret data: illegal base64 data at input byte 3

### ISSUE THREAD

**Issue by rombert** [fluxcd/flux2#2363]
### Describe the bug

When using `flux build` or `flux diff` a kustomization that includes a SOPS-managed secret the command errors out with 

> ✗ failed to decode secret data: illegal base64 data at input byte 3

### Steps to reproduce

I have the following kustomization structure:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-namespace
resources:
  - namespace.yaml
  - ../shared/
  - helm-release.yaml
  - endpoint-monitor.yaml
```

The kustomization that points to ../shared/ is the following

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - docker.io-secret.yaml⏎
```

The referenced `docker.io-secret.yaml` is a plain secret of type `kubernetes.io/dockerconfigjson` which is encrypted by Mozilla SOPS via AGE.

If I remove the `../shared/` kustomization from the resources list, then `flux build` works as expected.

### Expected behavior

`flux build kustomization` should not error out.

### OS / Distro

openSUSE Tumbleweed

### Flux version

v0.26.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.5 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.20.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.21.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by souleb** [comment]
Hi there,

I tried to reproduce the error like this

```yaml
$ cat podinfo/kustomize/kustomization.yaml                                                                                                                                                  09:29:04
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hpa.yaml
- deployment.yaml
- ../shared/
- service.yaml
- secret.yaml
```

```yaml
⋊> ~/flux cat podinfo/shared/kustomization.yaml                                                                                                                                                     09:37:43
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-secret.yaml

````

my age encrypted secret: 

```yaml
⋊> ~/flux cat podinfo/shared/config-secret.yaml                                                                                                                                                     09:37:35
apiVersion: v1
data:
  config.yaml: ZW52OgogICAgbm9kZV9lbnY6IEVOQ1tBRVMyNTZfR0NNLGRhdGE6VWlxMSxpdjpuSHJtQXFMMkp2OHl1ekliZzdWZjZ4bE5uTnRDWlBHUVVQRXRnRkdrQ1RBPSx0YWc6VlRYbVM0VDZiYWFBMkhMMXFvT2pSQT09LHR5cGU6c3RyXQpzb3BzOgogICAga21zOiBbXQogICAgZ2NwX2ttczogW10KICAgIGF6dXJlX2t2OiBbXQogICAgaGNfdmF1bHQ6IFtdCiAgICBhZ2U6CiAgICAgICAgLSByZWNpcGllbnQ6IGFnZTEwbGEyZ2Uwd3R2eDNxcjdkYXRxZjdyczR5bmd4c3pkYWw5MjdmczlydWthbXI4dTJwc2hzdnR6N2NlCiAgICAgICAgICBlbmM6IHwKICAgICAgICAgICAgLS0tLS1CRUdJTiBBR0UgRU5DUllQVEVEIEZJTEUtLS0tLQogICAgICAgICAgICBZV2RsTFdWdVkzSjVjSFJwYjI0dWIzSm5MM1l4Q2kwK0lGZ3lOVFV4T1NCc1FtVjBOMXBLZGpSeE9FeENkaTl6CiAgICAgICAgICAgIE1URjBNMW81VTBOWllYQmpPSEZ3VUN0RVdtWjRTak5xZGxWdkNuaFpWek5FVlZKb2NGZEtVMHBRVG5RcmNWbHYKICAgICAgICAgICAgU1d0d1VtMW5USGN5WkRWaVdVaFlTbU5OYTNaUUt6Z0tMUzB0SUZGSFVXRkpNV0prVFVZd2FtSnlhMFZqY1hveQogICAgICAgICAgICBNbU5wT1hWNU1FSjRNVmcyYVM5dVJrUlJNM2MwYWswS3hPQVB4YWdmSG9qQm9OVi9QY05CK2d1OW9IQ01XZHhrCiAgICAgICAgICAgIGhuOXJVZ2RtUDVzQzVHWGtMKzdjVC9EbUJkanJrRTM0RHJzK01yVUlZc01FSjZvaENDa1BXQT09CiAgICAgICAgICAgIC0tLS0tRU5EIEFHRSBFTkNSWVBURUQgRklMRS0tLS0tCiAgICBsYXN0bW9kaWZpZWQ6ICIyMDIyLTAxLTMxVDA4OjU5OjEwWiIKICAgIG1hYzogRU5DW0FFUzI1Nl9HQ00sZGF0YToxbURXUVVsTVMrWVA0VktmSHVsUVUzL2RWWXhoQnkwNmJ2U3EyODUxSllxRzd6WFZJOEMwdHdVbVpmU2x1MjIybklLNTRBbmMyanJGZXRNQ3FGdFl3Tlk0Ym12cGpMUlNKdW5oVXk2Nm5nSUt0SFZTMERWakN6OWNDL1h0WEJUM2RLWmdpci9kSWVrUnVJL0VZcVY4QUVDaWdhSURHbER0RzUzdjdZTzI3Ujg9LGl2OkVsU2VWeXk5VkluYmJBNHlSVjF3a3VLT2VvWEx6MWpiVjZKV2JyZ3hBNnM9LHRhZzphdDRUYW1FdVU4Ym9CdGF6U0lQOW13PT0sdHlwZTpzdHJdCiAgICBwZ3A6IFtdCiAgICB1bmVuY3J5cHRlZF9zdWZmaXg6IF91bmVuY3J5cHRlZAogICAgdmVyc2lvbjogMy43LjEK
kind: Secret
metadata:
  name: config-secret
  namespace: flux-system
type: Opaque
```

I get the expected result

```yaml
⋊> ~/flux flux build kustomization podinfo --path ./podinfo/kustomize/                                                                                                                              09:37:05
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: podinfo
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: podinfo
  namespace: flux-system
spec:
  maxReplicas: 4
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 99
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: podinfo
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: podinfo
  namespace: flux-system
spec:
  minReadySeconds: 3
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: podinfo
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9797"
        prometheus.io/scrape: "true"
      labels:
        app: podinfo
    spec:
      containers:
      - command:
        - ./podinfo
        - --port=9898
        - --port-metrics=9797
        - --grpc-port=9999
        - --grpc-service-name=podinfo
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_COLOR
          value: '#34577c'
        image: ghcr.io/stefanprodan/podinfo:6.0.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/healthz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        name: podinfod
        ports:
        - containerPort: 9899
          name: http
          protocol: TCP
        - containerPort: 9797
          name: http-metrics
          protocol: TCP
        - containerPort: 9999
          name: grpc
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
data:
  config.yaml: KipTT1BTKio=
kind: Secret
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: podinfo
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: config-secret
  namespace: flux-system
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: podinfo
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: podinfo
  namespace: flux-system
spec:
  ports:
  - name: http
    port: 9899
    protocol: TCP
    targetPort: http
  - name: grpc
    port: 9999
    protocol: TCP
    targetPort: grpc
  selector:
    app: podinfo
  type: ClusterIP

```

can you check your kustomization and secret file? Make sure you have a new line at the end.

**Comment by rombert** [comment]
Hi @souleb and thanks for looking into this! I looked at your example, and it seems the way the SOPS-encrypted secrets are stored differ.  My secret is of the following form:

```yaml
apiVersion: v1
kind: Secret
metadata:
    name: docker.io
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:REMOVED,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: ageREMOVED
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            REMOVED
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-25T13:28:57Z"
    mac: ENC[AES256_GCM,data:REMOVED,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1

```

Does that point to a potential problem? I also wanted to note that this worked just fine when applied by the kustomize controller; it's just the flux CLi that errors out.
