### ISSUE TITLE
[flux v0.26.0-2] Kustomization tries to modify immutable fields

### ISSUE THREAD

**Issue by Legion2** [fluxcd/flux2#2386]
### Describe the bug

I updated to flux 0.26.1 and then observed an reconciliation error in a deployment. I deleted the deployment and now there is a problem with the pvc of that deployment.
```
PersistentVolumeClaim/monitoring/influxdb-volume dry-run failed, reason: Invalid, error: PersistentVolumeClaim "influxdb-volume" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
        AccessModes:      {"ReadWriteOnce"},
        Selector:         nil,
        Resources:        {Requests: {s"storage": {i: {...}, s: "10Gi", Format: "BinarySI"}}},
-       VolumeName:       "",
+       VolumeName:       "pvc-c7f9929e-2741-43ce-b690-ed00816092ad",
        StorageClassName: &"aws-gp2-dynamic",
        VolumeMode:       &"Filesystem",
        DataSource:       nil,
  }
```

I tried to downgrade the kustomization controller, but that did not resolve the issue.

### Steps to reproduce

1. Install flux 0.25.3
2. create a PVC
  ```yaml
  apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-volume
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: aws-gp2-dynamic
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
```
3. Update flux to 0.26.1

### Expected behavior

Should work after the update

### OS / Distro

Ubuntu 21

### Flux version

flux: v0.26.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.20.11-eks-f17b81 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.16.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.20.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.19.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.21.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.1
✔ all checks passed

### Git provider

Gitlab

### Container Registry provider

Gitlab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
