### ISSUE TITLE
Unable to customize bootstrapped controllers

### ISSUE THREAD

**Issue by eloo** [fluxcd/flux2#2408]
### Describe the bug

Hi, 

i'm currently facing issues with the helm-controller related to OOM because of many changes on our helm releases.
There is already a bug which recommends to adjust the memory limit and concurrent setting for the controllers.

But it seems that its not possible to customize bootstrapped controller fully. 
In the docs there is an example of how a kustomization (gotk-patches.yaml) can be created to adjust the manifest. 
This is working for at least some settings but it seems that this is not the best way to adjust the controller fully. 

For example if you want to set the concurrent setting which is an cmdline arg its not that easy to change and also its not documented.
The result when i patch the args is that i loose all default set arguments. 

So the question is what is a real way to customize the controller settings? 

### Steps to reproduce

gotk-patches.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
          - concurrent 3
        resources:
            limits:
              memory: 3Gi
            requests:
              memory: 256Mi
```
kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

patchesStrategicMerge:
  - gotk-patches.yaml
```

results in the following controller
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.25.3
    control-plane: controller
  name: helm-controller
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-controller
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: helm-controller
    spec:
      containers:
      - args:
        - concurrent 3
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/fluxcd/helm-controller:v0.15.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 8080
          name: http-prom
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        resources:
          limits:
            cpu: 1000m
            memory: 3Gi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: temp
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: helm-controller
      terminationGracePeriodSeconds: 600
      volumes:
      - emptyDir: {}
        name: temp
```

You can see in this deployment that the patch is working as expect. 
But i loose all default args.
This does not look like a proper solution to me to adjust the controller deployments.

### Expected behavior

I want an adjustment of my controller additional to the default in an expected behaviour. 
Further this should be documented so we can really rely on the docs of how a controller can be adjusted.

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
