### ISSUE TITLE
Grafana dashboards should support the `cluster` variable

### ISSUE THREAD

**Issue by anthr76** [fluxcd/flux2#2453]
### Describe the bug

The grafana dashboard's don't work for prometheus's/grafana's setup for multi-cluster.

### Steps to reproduce

```yaml
    grafana:
      enabled: false
      forceDeployDashboards: true
      sidecar:
        dashboards:
          multicluster:
            global:
              enabled: true
            etcd:
              enabled: true
```

### Expected behavior

A cluster selector for dashboards

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/25143877/154815472-6c626b66-47ab-46af-8f86-1e60ddcf40c7.png)

![image](https://user-images.githubusercontent.com/25143877/154815564-365808b1-ab90-4d83-9193-564a7bea970d.png)

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
