### ISSUE TITLE
Image scanner for private repository returns 400 bad request on DigitalOcean

### ISSUE THREAD

**Issue by waltdizzy** [fluxcd/flux2#2454]
### Describe the bug

Hello. I am following the guide [Automate image updates to Git](https://fluxcd.io/docs/guides/image-update/). I receive 400 Bad Request whenever trying to image scan my private DigitalOcean container registry. 

> GET https://api.digitalocean.com/v2/registry/auth?scope=repository%3Awalts-fav-registry%3Apull&service=registry.digitalocean.com: unexpected status code 400 Bad Request

### Steps to reproduce

Follow the guides and setup the following YAML:

```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: walts-fav-registry
  namespace: flux-system
spec:
  image: registry.digitalocean.com/walts-fav-registry
  interval: 1m0s
  secretRef:
    name: walts-fav-registry-secret
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: walts-fav-registry
  namespace: flux-system
spec:
  imageRepositoryRef:  
    name: walts-fav-registry
    namespace: flux-system
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
     numerical:
      order: asc
```
Download a docker-config.json from Digital Ocean and run

```
kubectl create secret --namespace=flux-system generic walts-fav-registry-secret \
  --from-file=.dockerconfigjson=docker-config.json \
  --type=kubernetes.io/dockerconfigjson
```
Verify the secret is there
```
kubectl get secret -n flux-system
```
> walts-fav-registry-secret                 kubernetes.io/dockerconfigjson        1      14m
Get. the image repository
```
flux get image repository walts-fav-registry
```
> GET https://api.digitalocean.com/v2/registry/auth?scope=repository%3Awalts-fav-registry%3Apull&service=registry.digitalocean.com: unexpected status code 400 Bad Request

Also, describing the image repository shows a weird result

>Normal  error   16m (x19 over 54m)  image-reflector-controller  GET https://api.digitalocean.com/v2/registry/auth?scope=repository%!A(MISSING)walts-fav-registry%!A(MISSING)pull&service=registry.digitalocean.com: unexpected status code 400 Bad Request

### Expected behavior

Image repository should receive with a successful 200 like the tutorial shows.

### OS / Distro

Mac OS 12.2.1

### Flux version

v0.27.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.9 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.17.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.20.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.21.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.22.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

### Container Registry provider

DigitalOcean

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
