### ISSUE TITLE
Flux diff not working for roles with aggregationRule

### ISSUE THREAD

**Issue by eloo** [fluxcd/flux2#2472]
### Describe the bug

It seems that flux diff is not working properly when a (cluster)role has an aggregationRule.

It seems that the aggregation is ignored and thus the diff shows a lot removed rules which should be applied by the aggregations.

### Steps to reproduce

Create role like this:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-public-viewer
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-to-kube-public-viewer: "true"
rules: []

---
# Cluster role for Read-only access to default K8S resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-public-secret-reader
  labels:
      rbac.authorization.k8s.io/aggregate-to-kube-public-viewer: "true"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
  resourceNames:
    - "infrastructure"
    - "cluster"
```

Run flux diff afterwards

Output of diff:
```
► ClusterRole/kube-public-viewer drifted

rules
  ± type change from list to <nil>
    - - apiGroups:
        -
        resourceNames:
        - infrastructure
        - cluster
        resources:
        - secrets
        verbs:
        - get
        - watch
        - list
    + <nil>
    ```

### Expected behavior

I would expected that the aggregation is detected as it is the case in the kubernetes cluster and i get no diff.

### OS / Distro

macos 11.6

### Flux version

flux: v0.27.2

### Flux check

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Can you please try this with `kubectl diff --server-side`? I suspect this is a bug in Kubernetes server-side apply dry-run, we don't do anything special with RBAC, we send it to the API and show the diff output.

**Comment by eloo** [comment]
@stefanprodan 
I'm not familiar with the kubectl diff and which options to use but here is some input:

 kubectl diff --server-side -k . --force-conflicts=true
 -> i see the same deletes of rules like i do for flux diff
 
  kubectl diff --server-side -k . 
  ```
  Error from server (Conflict): Apply failed with 1 conflict: conflict with "clusterrole-aggregation-controller": .rules
  ```
  
  kubectl diff -k .
   -> i see the same deletes of rules like i do for flux diff

i hope that helps?

kubectl version --client=true
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by nickspizzas** [comment]
I just stumbled across this and was able to resolve it by removing the empty "rules" key.

Flux will reconcile it every time when defined like that:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-view
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-view: "true"
rules: []
```

Works:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-view
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-view: "true"
```

**Comment by gecube** [comment]
Revisited this in 2026: still reproducible byte-for-byte with flux v2.9.2 against Kubernetes v1.36.1 (kind), using the manifests from the original report. But having traced the full mechanics, I don't think there is anything left to wait for upstream — details below.

**What actually happens.** For an aggregated ClusterRole, `.rules` is populated by the control plane — since Kubernetes v1.21 the `clusterrole-aggregation-controller` writes it via **server-side apply with force** (kubernetes/kubernetes#99462), and the RBAC docs state: *"The control plane overwrites any values that you manually specify in the rules field of an aggregate ClusterRole."* So `.rules` is effectively a controller-owned output field, like `status` — except the schema treats it as a regular field.

A manifest containing `rules: []` **claims that field** under SSA semantics: an empty list doesn't mean "leave it alone", it means "I want this field empty". From there everything follows:

- flux's server-side dry-run (which is what `flux diff` shows) correctly returns the object with `rules` cleared → perpetual "drifted" output;
- on every real reconcile, kustomize-controller's apply (SSA with force ownership) **actually wipes the live rules** — I verified the API response to the apply contains `rules: null` — and the aggregation controller force-applies them back moments later. So beyond the cosmetic diff, every reconcile interval briefly drops all permissions granted through the aggregated role, plus endless `configured` events;
- kubectl behaves identically on the same cluster: `kubectl apply --server-side` without `--force-conflicts` fails with `conflict with "clusterrole-aggregation-controller": .rules`, and with it, the same wipe happens. Not flux-specific, exactly as @stefanprodan concluded back then.

**On the `blocked/upstream` label**: the Kubernetes issue this was waiting for was never filed (I couldn't find any), and there is nothing actionable upstream anyway — dry-run by design does not run controllers, so the API server cannot "fill in" aggregated rules in a dry-run response. SSA is working as specified here. The real trap is that the official RBAC docs example for aggregated ClusterRoles ships `rules: [] # The control plane automatically fills in the rules` — everyone copies that line, and under SSA it claims the field. I've sent kubernetes/website#56495 to drop it from the example and document the pitfall.

**The fix that works today** (already hinted by @nickspizzas above, verified on v2.9.2): remove the `rules: []` key from aggregated ClusterRole manifests entirely. The field is then not claimed, `flux diff` is clean (exit 0), and there is no ownership fight:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-public-viewer
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-to-kube-public-viewer: "true"
# no `rules:` key — the control plane owns it
```

**A possible flux-side hardening**, since users will keep copying the docs example: `fluxcd/pkg/ssa`'s normalize package already special-cases `rbac.authorization.k8s.io/v1` objects (for fluxcd/kustomize-controller#1041), so it would be natural to also drop `.rules` from the desired object when `.aggregationRule` is set. That is semantically faithful — the control plane overwrites manual rules anyway per the docs — and it would fix both the false drift and the transient permission wipe for existing manifests, in kustomize-controller and `flux diff` alike. Happy to send a PR if you'd take it; otherwise this issue could be closed with the workaround above as the answer (and maybe an FAQ entry), since there is no upstream fix to wait for.
