### ISSUE TITLE
Implement Patches update strategy for ImageUpdateAutomation resource

### ISSUE THREAD

**Issue by Tzrlk** [fluxcd/flux2#2474]
Since comments may not necessarily be preserved in some image pipelines, and keeping necessary configuration in comments is generally considered to be a bad code smell, `Patches` should be added to the list of available options when setting `spec.update.strategy` on ` ImageUpdateAutomation` resources, and a field added to contain the list of parameterised patches needed to update the relevant fields.

e.g.

```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind:       ImageUpdateAutomation
spec:
  update:
    strategy: JSONPatches
    path:     /apps/nginx/_base
    patches:
      - target:
          kind: Deployment
        patches:
          - path: /spec/containers/*/image
            replace: 'nginx:$1' # implied filter of '^.+$'
          - path: /metadata/labels/app.kubernetes.io~1version
            select: '^v([\\d\\.]+)' # implied termplate of '$1'
```

These patches would work exactly like Kustomize patches, except that the value can be run through a regex beforehand, and the operation is assumed to be "replace".
