### ISSUE TITLE
HelmRelease failing with "Service does not have load balancer ingress IP address"

### ISSUE THREAD

**Issue by waltdizzy** [fluxcd/flux2#2476]
### Describe the bug

HelmRelease fails to deploy when using DigitalOcean.

### Steps to reproduce

1. Setup a managed Kubernetes cluster on DigitalOcean
2. Utilize the following YAML:

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx2
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.0.17'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
    controller: 
      publishService:
        enabled: true
```

3. `kubectl describe helmrelease ingress-nginx2 -n flux-system`

> Events:
>   Type    Reason  Age                 From             Message
>   ----    ------  ----                ----             -------
>   Normal  info    18m (x13 over 29m)  helm-controller  HelmChart 'flux-system/flux-system-ingress-nginx2' is not ready
>   Normal  info    18m                 helm-controller  Helm install has started
>   Normal  error   12m                 helm-controller  Helm install failed: timed out waiting for the condition
> 
> Last Helm logs:
> 
> Starting delete for "ingress-nginx2-admission" RoleBinding
> Starting delete for "ingress-nginx2-admission-create" Job
> creating 11 resource(s)
> beginning wait for 11 resources with timeout of 5m0s
> Service does not have load balancer ingress IP address: flux-system/ingress-nginx2-controller
>   Normal  error  12m                helm-controller  reconciliation failed: Helm install failed: timed out waiting for the condition
>   Normal  error  2m (x17 over 12m)  helm-controller  reconciliation failed: install retries exhausted

### Expected behavior

The values.controller.publishService.enabled should publish the IP address and the load balancer should be deployed. 

### OS / Distro

Mac OS 12.2.1

### Flux version

v0.27.0

### Flux check

► checking prerequisites
✗ flux 0.27.0 <0.27.2 (new version is available, please upgrade)
✔ Kubernetes 1.21.9 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.17.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.20.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.21.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.22.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
