### ISSUE TITLE
ImageRepository producing 400 bad request with A(MISSING) when using a private registry

### ISSUE THREAD

**Issue by waltdizzy** [fluxcd/flux2#2477]
Hello, I created an issue for this last week but felt I could do a better job explaining why I think this is a bug. I closed that issue and I am trying again.

### Describe the bug

A verified secret that works against a private registry with deployments does not work with ImageRepository and ImagePolicy. Describing the ImageRepository shows a 400 bad request with MISSING tokens (see last line). I believe this may be a bug in flux because the MISSING tokens are strange and the secret is verified OK by ensuring deployments can pull from the private registry. 
```
kubectl describe imagerepository wdr-web -n flux-system
...
Spec:
  Image:     registry.digitalocean.com/walts-fav-registry
  Interval:  1m0s
  Secret Ref:
    Name:  regcred
Status:
  Canonical Image Name:  registry.digitalocean.com/walts-fav-registry
  Conditions:
    Last Transition Time:  2022-02-27T12:09:00Z
    Message:               GET https://api.digitalocean.com/v2/registry/auth?scope=repository%3Awalts-fav-registry%3Apull&service=registry.digitalocean.com: unexpected status code 400 Bad Request
    Reason:                ReconciliationFailed
    Status:                False
    Type:                  Ready
  Observed Generation:     1
Events:
  Type    Reason  Age                 From                        Message
  ----    ------  ----                ----                        -------
  Normal  error   46s (x19 over 22m)  image-reflector-controller  GET https://api.digitalocean.com/v2/registry/auth?scope=repository%!A(MISSING)walts-fav-registry%!A(MISSING)pull&service=registry.digitalocean.com: unexpected status code 400 Bad Request
```

### Steps to reproduce

1. Create a local kind kubernetes cluster
`kind create cluster --name local`
2. Run `flux create` according to getting started guide
3. Add a deployment.yaml with a private registry using `imagePullSecrets`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wdr-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wdr-web
  template:
    metadata:
      labels:
        app: wdr-web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: wdr-web
        image: registry.digitalocean.com/walts-fav-registry/wdr-web:main-fb558721-1645395731
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
```
4. Add a secret named `regcred`
```
kubectl create secret generic regcred \
    --from-file=.dockerconfigjson=/Users/myuser/.docker/.wfr \
    --type=kubernetes.io/dockerconfigjson
```
5. Reconcile flux
6. Verify registry secret is correct and image was pulled successfully
```
kubectl get all
pod/wdr-web-7c5bbbb9bb-n9rcd   1/1     Running   0          62m
```
7. Create an image repository
```
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: wdr-web
  namespace: flux-system
spec:
  image: registry.digitalocean.com/walts-fav-registry
  interval: 1m0s
  secretRef: 
    name: regcred
```
8. Add the same secret to the flux-system namespace
```
kubectl -n flux-system create secret generic regcred \
    --from-file=.dockerconfigjson=/Users/myuser/.docker/.wfr \
    --type=kubernetes.io/dockerconfigjson
```
9. Add an ImagePolicy
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: wdr-web
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: wdr-web
    namespace: flux-system
  policy:
    semver:
      range: 5.0.x
```

### Expected behavior

image-reflector-controller should have a successful scan by utilizing the stored secret for the private registry. The secret is verified working against deployments and should also work for ImageRepository.

### OS / Distro

Mac OS 12.2.1

### Flux version

v0.27.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.1 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.17.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.20.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.21.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.22.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

### Git provider

GitHub

### Container Registry provider

DigitalOcean

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
I got the same errors when I tried testing this, I think we both held it wrong:

```
spec:
  image: registry.digitalocean.com/walts-fav-registry
```

I have a registry created called `testrepo-podinfo` important to note here that this is a registry, which is the parent container for repositories. It is **not** a repository, which you can push image tags directly on. You must push tags to repositories underneath it.

```
# ... (docker tag then)
$ docker push registry.digitalocean.com/testrepo-podinfo:6.0.3
The push refers to repository [registry.digitalocean.com/testrepo-podinfo]
5ca8d37d3170: Preparing
89a73a7096ab: Preparing
f362ee1023d3: Preparing
618a79d2aa92: Preparing
931b628fbf37: Preparing
ee420dfed78a: Waiting
error parsing HTTP 400 response body: unexpected end of JSON input: ""
```

but then:

```
$ docker tag docker.io/stefanprodan/podinfo:6.0.3 registry.digitalocean.com/testrepo-podinfo/podinfo:6.0.3

$ docker push registry.digitalocean.com/testrepo-podinfo/podinfo:6.0.3
The push refers to repository [registry.digitalocean.com/testrepo-podinfo/podinfo]
5ca8d37d3170: Pushed
89a73a7096ab: Pushed
f362ee1023d3: Pushed
618a79d2aa92: Pushed
931b628fbf37: Pushed
ee420dfed78a: Pushed
6.0.3: digest: sha256:bd7199573096805472acd40a8c1ed8eebdba2e5e9fc2f10c558d77bcbd6f13ea size: 1580
```

Make sure you have images in the target repository, and that you approach creating a flux `ImageRepository` with the right depth. The tags are pushed into repositories only, not registries. You can index a repository with one `ImageRepository`, but you cannot index a registry with many repositories and tags.

I tested this against DO registry and found that it works. You might also investigate the feature provided by DO for automatically propagating a read-only Image Pull Secret to every namespace on your cluster:

https://docs.digitalocean.com/products/container-registry/how-to/use-registry-docker-kubernetes/

That will save a lot of boilerplate!

**Comment by waltdizzy** [comment]
This was the problem! Here is my updated manifest if anybody should find this later by searching:

```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: walts-fav-registry
  namespace: flux-system
spec:
  image: registry.digitalocean.com/walts-fav-registry/wdr-web
  interval: 1m0s
  secretRef:
    name: walts-fav-registry
```
Notice that spec.image now has three layers of depth. wdr-web was the repository, walts-fav-registry was the registry. Thank you so much, I'll star this project on GH!
