### ISSUE TITLE
ImageUpdateAutomation dry-run failed, error: failed to create typed pa tch object: .spec.sourceRef.namespace: field not declared in schema

### ISSUE THREAD

**Issue by theartusz** [fluxcd/flux2#2501]
### Describe the bug

After updating flux from v0.17.1 to v0.27.3 we experience error during reconciliation. 
The error message states `ImageUpdateAutomation/sre-selfservice-prod/sre-aks-gitops-prod dry-run failed, error: failed to create typed patch object: .spec.sourceRef.namespace: field not declared in schema`. 
However if I run `kubectl apply -f imageupdateautomation.yaml` manually the manifest is created in kubernetes without problem.

### Steps to reproduce

1. spinup new aks cluster on version 1.21.9
2. install fluxcd with terraform provider v0.11.2
3. deploy gitrepository
4. point with Kustomization to imageUpdateAutomation.yaml 
5. run flux reconcile

### Expected behavior

flux should deploy imageUpdateAutomation through kustomization (kustomize.toolkit.fluxcd.io/v1beta2) and kustomization should have `True` status

### OS / Distro

N/A

### Flux version

v0.27.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.9 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.17.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.20.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.21.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.22.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
Hi! Thanks for the report and sorry for the trouble.

Can you provide more detail including the manifests that errored out, in the form of an example that has as much detail as possible to make sure that we can run it, and try to use to reproduce your issue?

**Comment by AndersRunningen** [comment]
Hi, 
For reference, I am working on the same project as @theartusz :)

The manifest we are trying to apply with flux is:
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: sre-aks-gitops
  namespace: sre-selfservice-prod
spec:
  sourceRef:
    kind: GitRepository
    name: sre-aks-gitops
    namespace: flux-system
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        Automated image update
        [ci skip]
        Automation name: {{ .AutomationObject }}
        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}
        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}
        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}
  interval: 1m0s
  update:
    strategy: Setters
```
For **GitProvider**, we are using GitHub. 
For **Container registry provider**, we are using Azure Container Registry.
