### ISSUE TITLE
Flux Kustomization reconciliation causes deployment rollout

### ISSUE THREAD

**Issue by PierreBart** [fluxcd/flux2#2514]
### Describe the bug

I recently migrated my K8S manifests from Flux v1 to v2 and stumbled across an issue with my deployments rolling out completely during the Flux v2 first Kustomization reconciliation.

There are no diffs between the manifests of Flux v1 and v2 except:
- Flux v1 annotations and labels: `fluxcd.io/sync-checksum` and `fluxcd.io/sync-gc-mark`
- `managedFields` to be taken over by Flux v2
- Flux v2 new labels: `kustomize.toolkit.fluxcd.io/name` and `kustomize.toolkit.fluxcd.io/namespace`

When I activated the Flux v2 reconciliation for the first time, my pods replicas went down to 1, and then back to the previous number of replicas.

I did not expect my pods to downscale to 1 replicas when activating Flux v2 reconciliation because:
- The `flux diff` command outputs only `kustomize.toolkit.fluxcd.io/name` and `kustomize.toolkit.fluxcd.io/namespace` labels addition
- The deployment's rolling update strategy is configured with `maxSurge: 25%` and  `maxUnavailable: 0`
- The HPA `spec.minReplicas` is set to 3

### Steps to reproduce

Below are the minimal steps to reproduce the issue:
1. Apply the following manifests to create a Deployment and HPA with 3 replicas and the Flux v1 annotations and labels:
```yaml
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      fluxcd.io/sync-checksum: a434c2d6d3ee133d5759b172d5b9afaac0c20f8b
    labels:
      app: podinfo
      fluxcd.io/sync-gc-mark: sha256.etLmwGPQWoJH4Qw83eFGigGqAiZUwsd0x1V7rMo3Zgs
    name: staging-podinfo
    namespace: staging
  spec:
    progressDeadlineSeconds: 600
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: podinfo
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: podinfo
      spec:
        containers:
        - command:
          - ./podinfo
          - --port=9898
          - --level=info
          - --random-delay=false
          - --random-error=false
          env:
          - name: PODINFO_UI_COLOR
            value: green
          image: stefanprodan/podinfo:1.3.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 9898
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: podinfod
          ports:
          - containerPort: 9898
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 9898
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: autoscaling/v2beta2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      fluxcd.io/sync-checksum: ef3462645a7b66984b5776a1e0f19a3abe1f6162
    labels:
      app: podinfo
      fluxcd.io/sync-gc-mark: sha256.hPn6xJ9FQZgCqy-Y1vG1YVozrbnrs-vPiE3XWrzfUY8
    name: staging-podinfo
    namespace: staging
  spec:
    maxReplicas: 3
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
    minReplicas: 3
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: staging-podinfo
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
You should have the following objects configured:
```bash
kubectl get all -l app=podinfo
NAME                                   READY   STATUS    RESTARTS   AGE
pod/staging-podinfo-5d6d556894-8s4jb   1/1     Running   0          50s
pod/staging-podinfo-5d6d556894-jw5kk   1/1     Running   0          50s
pod/staging-podinfo-5d6d556894-z994m   1/1     Running   0          50s

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/staging-podinfo   3/3     3            3           51s

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/staging-podinfo-5d6d556894   3         3         3       50s

NAME                                                  REFERENCE                    TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/staging-podinfo   Deployment/staging-podinfo   10%/80%   3         3         3          50s
```
2. Bootstrap Flux 2 with the following options:
```bash
# Replace options with your git config
$ flux bootstrap git
    --branch=master
    --components-extra=image-reflector-controller,image-automation-controller
    --namespace='flux2'
    --path='clusters/test'
    --private-key-file='{{ flux2_ssh_key_path }}'
    --secret-name='{{ flux2_git_ssh_keys_secret_name }}'
    --version='v0.27.3'
```
2. Store the following manifests under the `apps/staging/podinfo` path in Git:
 a. In file `manifests.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: podinfo
  name: staging-podinfo
  namespace: staging
spec:
  selector:
    matchLabels:
      app: podinfo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - command:
        - ./podinfo
        - --port=9898
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_COLOR
          value: green
        image: stefanprodan/podinfo:1.3.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
        name: podinfod
        ports:
        - containerPort: 9898
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: podinfo
  name: staging-podinfo
  namespace: staging
spec:
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: staging-podinfo
```
  b. In file `kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests.yaml
namespace: staging
namePrefix: staging-
```
3. Let Flux 2 apply the following Kustomization with `suspend: true` attribute: 
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: staging-podinfo
  namespace: staging
spec:
  interval: 1m0s
  path: apps/staging/podinfo
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux2
    namespace: flux2
  suspend: true
```
4. Run the following command under your git root directory:
```bash
$ flux diff kustomization staging-podinfo -n staging --path ./apps/staging/podinfo
✓  Kustomization diffing...
► Deployment/staging/staging-podinfo drifted

metadata.labels
  + two map entries added:
    kustomize.toolkit.fluxcd.io/name: staging-podinfo
    kustomize.toolkit.fluxcd.io/namespace: staging

► HorizontalPodAutoscaler/staging/staging-podinfo drifted

metadata.labels
  + two map entries added:
    kustomize.toolkit.fluxcd.io/name: staging-podinfo
    kustomize.toolkit.fluxcd.io/namespace: staging

⚠️ identified at least one change, exiting with non-zero exit code
```
5. Start the Flux v2 reconciliation:
```bash
$ flux resume kustomization -n staging staging-podinfo
```
6. You can assert that 2 out 3 pods got restarted unexpectedly:
```bash
$ kubectl get pods
staging-podinfo-5d6d556894-2llr5   1/1     Running   0          16s
staging-podinfo-5d6d556894-4d9xq   1/1     Running   0          16s
staging-podinfo-5d6d556894-6spcl   1/1     Running   0          3m11s
```

### Expected behavior

I expected the pods not to be restarted after the Flux v2 first reconciliation.

### OS / Distro

Google managed Container-Optimized OS in GKE

### Flux version

flux: v0.27.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.5-gke.1302 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.17.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.20.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.21.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.22.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
You need to remove `replicas: 3` from your Deployment as it conflicts with HPA, every time Flux does a reconciliation overrides it.

**Comment by PierreBart** [comment]
The YAMLs to apply from the first step are not reconciled by anything, they are here to simulate a Flux v1 situation of reconciliation. I have tried the procedure removing the `replicas` attribute from the Deployment of the first step and the behavior is the same. 

Also the Deployment in step 2, which is reconciled by Flux v2, does not contain the `replicas` attribute.

Here is the output of the command `kubectl get deployment/staging-podinfo --show-managed-fields -oyaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-03-08T15:22:51Z"
  generation: 4
  labels:
    app: podinfo
    kustomize.toolkit.fluxcd.io/name: staging-podinfo
    kustomize.toolkit.fluxcd.io/namespace: staging
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:app: {}
          f:kustomize.toolkit.fluxcd.io/name: {}
          f:kustomize.toolkit.fluxcd.io/namespace: {}
      f:spec:
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:creationTimestamp: {}
            f:labels:
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"podinfod"}:
                .: {}
                f:command: {}
                f:env:
                  k:{"name":"PODINFO_UI_COLOR"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:livenessProbe:
                  f:httpGet:
                    f:path: {}
                    f:port: {}
                f:name: {}
                f:ports:
                  k:{"containerPort":9898,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:readinessProbe:
                  f:httpGet:
                    f:path: {}
                    f:port: {}
                f:resources:
                  f:limits:
                    f:cpu: {}
                    f:memory: {}
                  f:requests:
                    f:cpu: {}
                    f:memory: {}
    manager: kustomize-controller
    operation: Apply
    time: "2022-03-08T15:25:11Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-03-08T15:25:29Z"
  name: staging-podinfo
  namespace: staging
  resourceVersion: "74541654"
  uid: d2d822d8-4c51-4459-9194-609f38fcc65c
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: podinfo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: podinfo
    spec:
      containers:
      - command:
        - ./podinfo
        - --port=9898
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_COLOR
          value: green
        image: stefanprodan/podinfo:1.3.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9898
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: podinfod
        ports:
        - containerPort: 9898
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 9898
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2022-03-08T15:22:52Z"
    lastUpdateTime: "2022-03-08T15:22:57Z"
    message: ReplicaSet "staging-podinfo-5d6d556894" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-03-08T15:25:29Z"
    lastUpdateTime: "2022-03-08T15:25:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3

**Comment by stefanprodan** [comment]
I see `deployment.kubernetes.io/revision: "1"` so Flux does not change the deployment. After the replicas set reaches the desired state, if you run `flux reconcile` does the deployment keeps restarting? I'm also running dozen of podinfo deployment in my test cluster and I don't see this behaviour. Maybe look at the HPA events and replicaset ones.

**Comment by stefanprodan** [comment]
Ah `creationTimestamp: null`, readonly fields shouldn't be set in Git, this may be the issue https://fluxcd.io/docs/faq/#how-do-i-resolve-someresource-configured-events-spam

**Comment by PierreBart** [comment]
I tried the procedure removing the `creationTimestamp: null` from the first step and I still see the same behavior.

The attribute `creationTimestamp: null` is not present in Git either. 
 
After the replicas set reaches the desired state, and I run `flux resume` the deployment's pods scaledown to 1 and then scale up to 3 in a matter of seconds.
 
 Here are some events after running the `flux resume` command:
 ```bash
45s         Normal    info               kustomization/staging-podinfo           Deployment/staging/staging-podinfo configured
HorizontalPodAutoscaler/staging/staging-podinfo configured
45s         Normal    info                kustomization/staging-podinfo             Reconciliation finished in 109.779427ms, next run in 2m0s
45s         Normal    ScalingReplicaSet   deployment/staging-podinfo                Scaled down replica set staging-podinfo-5d6d556894 to 1
38s         Normal    SuccessfulRescale   horizontalpodautoscaler/staging-podinfo   New size: 3; reason: cpu resource utilization (percentage of request) above target
38s         Normal    ScalingReplicaSet   deployment/staging-podinfo                Scaled up replica set staging-podinfo-5d6d556894 to 3
 ```

**Comment by PierreBart** [comment]
So it seems that the issue is related to how the ownership of the `spec.replica` field of the deployment is transferred when Flux starts reconciling.

I have managed to avoid the situations of the deployment replicas going down to 1 by pre-patching the manager of the `spec.replicas` field before letting Flux reconcile.

First I create a manifest containing only the replicas field of the deployment:
```yaml
kind: Deployment
metadata:
  name: staging-podinfo
  namespace: staging
spec:
  replicas: 3
```

Then I apply this manifest with the following command to set the ownership over the `spec.replicas` field:
```bash
kubectl apply -f manifest.yaml --server-side --field-manager=handover-to-hpa --validate=false
```

Finally, I let Flux apply the manifests and the deployment `replicas` field doesn't reset to 1.
