### ISSUE TITLE
can not get helmrelease reconcile failure notification

### ISSUE THREAD

**Issue by zxkane** [fluxcd/flux2#2519]
### Describe the bug

Create a alert object using slack like below,

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: on-call-webapp
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
```

I can receive the notification for resource configured like below,
```
kustomization/infrastructure.flux-system
SealedSecret/app1/mariadb configured
revision
master/8b21d57c4d323cb1b6aec01f8e0c1c0ca16467db
```

However there is no notification for failing installing/upgrading helm release,
```
kubectl get helmreleases.helm.toolkit.fluxcd.io -A
NAMESPACE     NAME                           READY   STATUS                                                                                    AGE
app1          prestashop                     False   Helm uninstall failed: uninstall: Release not loaded: prestashop: release: not found...   4m49s
flux-system   sealed-secrets                 True    Release reconciliation succeeded                                                          19h
```

### Steps to reproduce

deploy `bitnami/prestashop` via HelmRelease,

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prestashop
  namespace: app1
spec:
  releaseName: prestashop
  chart:
    spec:
      chart: prestashop
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 14.0.10
  values:
    existingSecret: prestashop
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: external
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    persistence:
      storageClass: standard
    # for mariadb
    mariadb:
      enabled: false
    externalDatabase:
      host: mariadb.mariadb.svc.cluster.local
      user: root
      database: my_database
      existingSecret: mariadb
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
```

### Expected behavior

The failure status of helm release is notified via alert system.

### OS / Distro

ubuntu 18.04

### Flux version

flux: v0.27.3 helm-controller: v0.16.0 kustomize-controller: v0.20.1 notification-controller: v0.21.0 source-controller: v0.21.2

### Flux check

$ flux check
► checking prerequisites
✔ Kubernetes 1.21.5-eks-bc4871b >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.20.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.21.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
You need yo add a new entry to `eventSources` for that namespace:

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: on-call-webapp
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: HelmRelease
      name: '*'
      namespace: 'app1'
```
