### ISSUE TITLE
Webhook receivers don't allow granular event selection on github

### ISSUE THREAD

**Issue by fishman** [fluxcd/flux2#2525]
### Describe the bug

if I create a github receiver, I can for example listen for the release events. However the release event on github triggers for `Release created, edited, published, unpublished, or deleted`.

Similarly it's impossible to trigger anything at the end of a github workflow. Since there is no way to limit the event on a completed workflow.

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: github-receiver
  namespace: default
spec:
  type: github
  events:
    - "release"
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1beta1
      kind: GitRepository

```

### Steps to reproduce

1. Create a github-receiver as defined above
2. add github webhook
3. create a workflow which deletes a tag first and then does a release
4. the reconcile happens before the release is create since the tag delete already triggers a reconcile

### Expected behavior

Trigger the reconcile after successful release publish.

### OS / Distro

N/A

### Flux version

flux: v0.27.3

### Flux check

N/A

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
