### ISSUE TITLE
Flux reconcile kustomization causes redeploy after kubectl rollout restart deploy

### ISSUE THREAD

**Issue by pusherman** [fluxcd/flux2#2526]
### Describe the bug

When you issue a `kubectl rollout restart deploy` to redeploy a pod-- that pod is then killed and recreated the next time a reconciliation is performed.

From describing the deployment after a restart, it looks like the only difference is a `Pod Template`, annotations for `kubectl.kubernetes.io/restartedAt`.  After flux reconciles and kills the pod and deploys a new one that `kubectl.kubernetes.io/restartedAt` annotation is removed and subsequent reconciliations do **not** kill and restart the pod.

Describe Deployment Snippet (after rollout restart)
```
Pod Template:
  Labels:           app=debugger
                    tier=backend
  Annotations:      kubectl.kubernetes.io/restartedAt: 2022-03-10T09:57:06-05:00
```

Describe Deployment Snippet (after reconciliation)
```
Pod Template:
  Labels:       app=debugger
                tier=backend
  Containers:
   debugger:
    Image:        294686472773.dkr.ecr.us-east-1.amazonaws.com/common/pod-debugger:latest
```

Logs from flux
```
{
  "level":"info",
  "ts":"2022-03-10T15:00:28.170Z",
  "logger":"controller.kustomization",
  "msg":"server-side apply completed",
  "reconciler group":"kustomize.toolkit.fluxcd.io",
  "reconciler kind":"Kustomization",
  "name":"debugger-sync",
  "namespace":"flux-system",
  "output":{
    "Deployment/app/debugger":"configured",
  }
}


{
  "level":"info",
  "ts":"2022-03-10T15:00:28.227Z",
  "logger":"controller.kustomization",
  "msg":"Reconciliation finished in 698.046485ms, next run in 10m0s",
  "reconciler group":"kustomize.toolkit.fluxcd.io",
  "reconciler kind":"Kustomization",
  "name":"debugger-sync",
  "namespace":"flux-system",
  "revision":"main/d71ece3a566e1519be1ecd23680de2ef5925f104"
}
```

### Steps to reproduce

Sample Flux Kustomzation
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: debugger-sync
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/debugger/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

Sample Kustomization (./apps/debugger/overlays/dev/kustomization.yaml)
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testing

configMapGenerator:
- name: aws
  literals:
  - region=us-east-1

resources:
- debugger.yaml
```

Sample Deployment (./apps/debugger/overlays/dev/debugger.yaml)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugger
  template:
    metadata:
      labels:
        app: debugger
        tier: backend
    spec:
      containers:
      - name: debugger
        image: 494686412343.dkr.ecr.us-east-1.amazonaws.com/debugger:latest
        imagePullPolicy: Always
```

1. Using the above files, when flux is enabled for the debugger deployment, issue a `kubectl rollout restart deploy debugger` command.
2. Watch the pods and notice a new pod is deployed and the previous pod was terminated
3. Issue a `flux reconcile kustomization debugger-sync` command
4. Watch the pods and notice a new pod is deployed and the previously deployed pod will be terminted
5. Issue another `flux reconcile kustomization debugger-sync` command
6. Watch no further re-deployments are done

### Expected behavior

A simple `kubectl rollout restart deploy` should not trigger a reconciliation redeploy.  This was not the case in version `0.25.3` at least.

### OS / Distro

macOS 12.2.1

### Flux version

v0.27.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.5-eks-bc4871b >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.17.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.21.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.22.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

### Container Registry provider

AWS ECR

### Additional context

It sounds like the issue could possibly be related to https://github.com/fluxcd/flux2/issues/2514 but I'm not 100% sure.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
