### ISSUE TITLE
flux diff - failed to mask secret <name> sops data: no field named 'type'

### ISSUE THREAD

**Issue by nickperkins** [fluxcd/flux2#2535]
### Describe the bug

I would like to run a `flux diff` to view the changes to be applied to our production cluster. We use SOPS secrets.

When I run `flux diff` I get the following error:

```
flux --context production diff kustomization infrastructure --path /path/to/kustomization 
✗ failed to mask secret <secret-name> sops data: no field named 'type'
```

### Steps to reproduce

1. Create a secret encrypted with SOPS.
2. Attempt to run a `flux diff` against the kustomization which has the secret encrypted with SOPS.

### Expected behavior

The flux diff should succeed.

### OS / Distro

macOS 12.2.1

### Flux version

v0.27.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.5-eks-bc4871b >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.17.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.20.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.21.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.22.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by souleb** [comment]
Hi,

Can you give more information on how you generate and encrypt your secrets? Only the `data` or `stringdata`fields must be encrypted.

**Comment by nickperkins** [comment]
I'm only encrypting `data` or `stringData`. 
```
creation_rules:
- path_regex: infrastructure/global/.*.yaml
  encrypted_regex: ^(data|stringData)$
```
Here's an example secret:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-operations
  namespace: flux-system
type: Opaque
stringData:
  address: ENC[AES256_GCM,data:<data>,type:str]
sops:
  kms:
  - arn: arn:aws:kms:<region>:<account>:key/<keyid>
    created_at: '2022-02-24T05:33:07Z'
    enc: <removed>
    aws_profile: ''
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2022-02-24T05:33:07Z'
  mac: ENC[AES256_GCM,data:<data>,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
  ```
