### ISSUE TITLE
HelmRelease notifications are not sent when install/dry-run fails

### ISSUE THREAD

**Issue by jprecuch** [fluxcd/flux2#2551]
### Describe the bug

I've tried to install helmchart but it failed because of existing resource in my cluster
```
{"level":"error","ts":"2022-03-18T12:44:22.115Z","logger":"controller.helmrelease","msg":"Reconciler error","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"sde-deployment","namespace":"sde","error":"Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install: StorageClass \"faster\" in namespace \"\" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key \"app.kubernetes.io/managed-by\": must be set to \"Helm\"; annotation validation error: missing key \"meta.helm.sh/release-name\": must be set to \"sde-deployment\"; annotation validation error: missing key \"meta.helm.sh/release-namespace\": must be set to \"sde\""}
```
This was properly reported in helm-controller logs. However when I checked Slack where my notifications are being sent, there is nothing like this reported
Configuration:
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: error-notifications
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: '*'
    - kind: HelmRepository
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: HelmChart
      name: '*'
 ```
 I have same set for info notifications but nothing. The only issue I get is after timeout
 ```
Health check failed after 5m0.016616752s, timeout waiting for: [HelmRelease/sde/sde-deployment status: 'InProgress']
revision
main/cb345745c3494c52a8f34530baccea3373afdd99

Health check failed after 5m0.050700875s, timeout waiting for: [Namespace/sde status: 'Unknown': rate: Wait(n=1) would exceed context deadline, ConfigMap/sde/sde-manifest-6g7fcbfgtb status: 'Unknown': rate: Wait(n=1) would exceed context deadline, Secret/sde/gcp-main-secret status: 'Unknown': rate: Wait(n=1) would exceed context deadline, HelmRelease/sde/sde-deployment status: 'Unknown': rate: Wait(n=1) would exceed context deadline]
revision
main/6668389de970ff1d96b2000bd238344f77c50051
```

Is is somehow possible to include also those install/dry-run errors to the notifications?

### Steps to reproduce

1. Configure notifications based on above
2. Try to deploy chart which you know will fail
3. Monitor notifications and see that the install/dry-run error is not parsed to notifications

### Expected behavior

All install/dry-run errors should be sent

### OS / Distro

Ubuntu 18.04.5 LTS

### Flux version

v0.27.4

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.6-gke.1503 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.17.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.21.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.22.3
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
The Alert that you've defined only captures events from the `flux-system` namespace. You need to add all namespaces to it, e.g:

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: error-notifications
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: '*'
    - kind: HelmRepository
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: HelmRelease
      name: '*'
      name: 'sde'
```
