### ISSUE TITLE
GitRepository: caFile not respected x509: certificate signed by unknown authority': git cmd = '/usr/bin/git 

### ISSUE THREAD

**Issue by rlaflamme** [fluxcd/flux2#2568]
### Describe the bug

I have a private gitlab repository secured by  a self-signed certificate (pfsense certificate authority).
The bootstrap process is working fine. However when I try to add another git repository ( app-config) I have a X509 issue.

```
 flux get kustomizations --watch
NAME            READY   MESSAGE                                 REVISION        SUSPENDED
flux-system     True    Applied revision: master/1ce3c3d        master/1ce3c3d  False
code-to-prod-blog       False   kustomize build failed: accumulating resources: accumulation err='accumulating resources from 'https://gitlab.lab.okd.local/from-code-to-production-with-gitops/code-to-prod-blog?ref=config': Get "https://gitlab.lab.okd.local/from-code-to-production-with-gitops/code-to-prod-blog?ref=config": x509: certificate signed by unknown authority': git cmd = '/usr/bin/git fetch --depth=1 origin config': exit status 128   master/79279ccb31ee61dd3ed47c13aca336fafdae8e2f False
```

Here is manifest:
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: code-to-prod-blog
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: prod
  url: ssh://git@gitlab.lab.okd.local:22/from-code-to-production-with-gitops/code-to-prod-blog.git
  secretRef:
    name: ssh-gitlab-creds
```
And the secret:
```
---
apiVersion: v1
data:
  caFile: LS0tLS1CRU...
  identity: LS0tLS1...
  identity.pub: c3NoLXJzY...
  known_hosts: fDF8Nm...
kind: Secret
metadata:
  name: ssh-gitlab-creds
  namespace: flux-system
type: Opaque
```
I tried different solutions but none of them worked
1- bundle the root+intermediate CA certs together
2- bundle the intermediate CA cert only 
3- Replace the gitImplementation by libgit2
https://fluxcd.io/docs/components/source/gitrepositories/#git-implementation
4- I even tried this one
https://github.com/fluxcd/source-controller/issues/510#issuecomment-985512998
I'm out of options

### Steps to reproduce

Follow the get-stated doc
https://fluxcd.io/docs/get-started/#customize-podinfo-deployment
https://fluxcd.io/docs/components/source/gitrepositories/#ssh-authentication

### Expected behavior

The caFile parameter is handled for https certificate authority
https://fluxcd.io/docs/components/source/gitrepositories/#https-certificate-authority

However it should be handled also by the git command for ssh authentication.
https://fluxcd.io/docs/components/source/gitrepositories/#ssh-authentication

### OS / Distro

buntu 20.04.3 LTS

### Flux version

flux: v0.28.0

### Flux check
```
# flux check --pre
► checking prerequisites
✔ Kubernetes 1.23.4 >=1.20.6-0
✔ prerequisites checks passed
```

### Git provider

gitlab

### Container Registry provider

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
I do not think the issue you are experiencing has to do with the setup of the `GitRepository` object, but rather with something in the `Kustomization` containing a reference to a remote resource. For which the kustomize-controller does not have any credentials.

**Comment by rlaflamme** [comment]
@hiddeco You're right! I have an issue in the kustomization.yaml.  It's a link to a resource that is on my internal gitlab and 

```
bases:
- https://gitlab.lab.okd.local/from-code-to-production-with-gitops/code-to-prod-blog?ref=config
- namespace.yaml
patchesStrategicMerge:
- deployment.yaml
```
The exact error message:
```
 kustomize build failed: accumulating resources: accumulation err='accumulating resources from 'https://gitlab.lab.okd.local/from-code-to-production-with-gitops/code-to-prod-blog?ref=config': Get "https://gitlab.lab.okd.local/from-code-to-production-with-gitops/code-to-prod-blog?ref=config": x509: certificate signed by unknown authority': git cmd = '/usr/bin/git fetch --depth=1 origin config': exit status 128
```

But I have X509 Issues with the GitRepository artifact.  Here's the use case:

- Internal/Company Git -- public reposities (no authentication) -- using self signed certificate (internal CA signer)
The following manifest doesn't work (X509 issue)
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: master
  url: https://gitlab.lab.okd.local/rlaflamme/podinfo
```
But this one works:

- Internal/Company Git -- private or internal reposities -- using self signed certificate (internal CA signer) with ssh-authentication 

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: master
  url: ssh://git@gitlab.lab.okd.local/rlaflamme/podinfo
  secretRef:
    name: ssh-gitlab-creds
```

Curiously, pulling images from my internal nexus3 registry works successfully without any X509 issues
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  ...
  template:
    spec:
      containers:
      - name: podinfod
        image: hub-registry.lab.okd.local/podinfo/podinfo:6.1.0
        imagePullPolicy: IfNotPresent
        ...
```

I didn't test the Helm controller but I suppose it will behave the same.
We need a way tot support internal CA Certs inside the controller managers. 
Maybe I am missing something (an option or an attribute or an annotation, or a way to mount in a volume custom CA certs)

In my case these test are done in my lab.
My client is currently using Flux v1 and they are planning to migrate to V2 this year and they will face the same issues.
In my lab I have provisioned a subset of my client's ecosystem. We both use custom CA cert signer, Nexus3 Container registry, Gitlab, Openshift and others.

Thank you for enlightening me

Regards

Robert

**Comment by stefanprodan** [comment]
@rlaflamme remote bases that point to Git are not supported.

So instead of this `kustomization.yaml`:

```yaml
bases:
- https://gitlab.lab.okd.local/from-code-to-production-with-gitops/code-to-prod-blog?ref=config
- namespace.yaml
patchesStrategicMerge:
- deployment.yaml
```

Firt you need to create a GitRepository under `clusters/your-cluster` for the base with:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: code-to-prod-blog
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: config
  url: ssh://git@gitlab.lab.okd.local/from-code-to-production-with-gitops/code-to-prod-blog
  secretRef:
    name: ssh-gitlab-creds
```

Then add the namespace and the deployment patch to the main repo in a dir e.g. `code-to-prod-blog`. Inside the `code-to-prod-blog` create a `kustomization.yaml` like so:

```
resources:
- base
- namespace.yaml
patchesStrategicMerge:
- deployment.yaml
```

Next create a GitRepository under `clusters/your-cluster` that includes the base one:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: code-to-prod-blog-deploy
  namespace: flux-system
spec:
  include:
    - repository:
        name: code-to-prod-blog
      toPath: code-to-prod-blog/base
  interval: 1m
  ref:
    branch: <SAME AS FLUX-SYSTEM>
  url: ssh://git@gitlab.lab.okd.local:22/<SAME AS FLUX-SYSTEM>
  secretRef:
    name: <SAME AS FLUX-SYSTEM>
```

And finally create a Kustomization under `clusters/your-cluster` that applies the `code-to-prod-blog` dir:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: code-to-prod-blog
  namespace: flux-system
spec:
  interval: 15m
  path: "./code-to-prod-blog"
  sourceRef:
    kind: GitRepository
    name: code-to-prod-blog-deploy
  prune: true
  timeout: 5m
```

**Comment by rlaflamme** [comment]
Thank you @stefanprodan !
It almost works,
I am facing an ordering issue. 
code-to-prod-blog-config  repo should be deployed before code-to-prod-blog. Otherwise I have the message ' no artifact available for include 'code-to-prod-blog-config''
Is there a way to specify a order or a codition before/after antother git repo?

```
flux get sources git --watch

NAME            REVISION        SUSPENDED       READY   MESSAGE
flux-system     master/54f8c09  False           True    stored artifact for revision 'master/54f8c099419edd1e23814a683c3d35b2a387a783'
code-to-prod-blog               False   False   no artifact available for include 'code-to-prod-blog-config'
podinfo master/9f196bf  False   True    stored artifact for revision 'master/9f196bfb59a3b0332a48d69591047af937d8929e'
code-to-prod-blog-config        config/67feba2  False   True    stored artifact for revision 'config/67feba278e9f1860a665ec82c39a181492cf22a9'
```
```
flux get kustomizations --watch
NAME            REVISION        SUSPENDED       READY   MESSAGE
flux-system     master/54f8c09  False           True    Applied revision: master/54f8c09
code-to-prod-blog               False   False   Source is not ready, artifact not found
podinfo master/9f196bf  False   True    Applied revision: master/9f196bf

```

Thank you!
Robert

**Comment by stefanprodan** [comment]
@rlaflamme if you do `flux reconcile source git code-to-prod-blog` does it recover?

**Comment by rlaflamme** [comment]
Thank's a lot @stefanprodan  It's working now with your solution and the 'flux reconcile' command
Do you know is there any plan to support internal CA certs  like this ?
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: master
  url: https://gitlab.lab.okd.local/rlaflamme/podinfo
```
