### ISSUE TITLE
Public GitRepository using GitLab Requiring Credentials

### ISSUE THREAD

**Issue by ground7** [fluxcd/flux2#2596]
### Describe the bug

Previously I was able to use a gitlab public repository like so:
```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitlab-repo
  namespace: flux-system
spec:
  interval: 1h
  url: https://gitlab.com/gitlab-org/gitlab-runner.git
```
This no longer works, I now get:
```
$ flux reconcile source git gitlab-repo
► annotating GitRepository gitlab-repo in flux-system namespace
✔ GitRepository annotated
◎ waiting for GitRepository reconciliation
✗ GitRepository reconciliation failed: 'failed to checkout and determine revision: unable to clone 'https://gitlab.com/gitlab-org/gitlab-runner.git': authentication required'
```
This still works fine for my github sources.

### Steps to reproduce

1. Install flux
2. Add a public GitRepository source with a public gitlab url
3. Try to reconcile

### Expected behavior

Public gitlab repos would work as sources without needing credentials

### OS / Distro

Ubuntu 20.04

### Flux version

v0.28.4

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.7+rke2r2 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.18.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.22.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.22.4
✔ all checks passed

### Git provider

GitLab

### Container Registry provider

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
