### ISSUE TITLE
Diff command should ignore substitute label/annotation on configMapGenerator

### ISSUE THREAD

**Issue by clementblaise** [fluxcd/flux2#2598]
### Describe the bug

When using substitute on a Kustomization that contains a configMapGenerator diff is templating the content even though `kustomize.toolkit.fluxcd.io/substitute: disabled` was set.

The diff command should not template resource when the annotation is present.

This is a bit problematic since at runtime the substitution will not template the resource, which means diff will  always return templated resource that will not match the state in the cluster.

I have seen the problem on Grafana dashboard json file that contain `"$$hashKey"` , diff will template it to `"$hashKey"`

### Steps to reproduce

1. Create a Kustomization that has postBuild, example :

```yaml
...
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
```

2. Create a configMapGenerator, for example :

```yaml
...
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
generatorOptions:
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
configMapGenerator:
  - name: flux-grafana-dashboards
    files:
      - ./dashboards/flux-cluster.json
```

`./dashboards/flux-cluster.json` should be the official fluxcd dashboard (will contain `"$$hashKey"` )

3. Sync flux

4. Run `flux diff` on the Kustomization from step 1

### Expected behavior

Diff should not template resources that have label/annotation `kustomize.toolkit.fluxcd.io/substitute: disabled`

### OS / Distro

macOs 12.3

### Flux version

v0.28.3

### Flux check

► checking prerequisites
✗ flux 0.28.2 <0.28.4 (new version is available, please upgrade)
✔ Kubernetes 1.22.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.18.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.21.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.17.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.22.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.22.3
✔ all checks passe

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
