### ISSUE TITLE
HelmRelease valuesFrom kind secret with comma separated values (cannot end with ,)

### ISSUE THREAD

**Issue by tomasfabian** [fluxcd/flux2#2625]
### Describe the bug

Hi,
in case that the secret value contains a comma character we receive the following error message:

```
Type    Reason  Age                 From             Message                                                                                                                                                ││   ----    ------  ----                ----             -------                                                                                                                                                                                                                            ││   Normal  error   14m (x7 over 51m)   helm-controller  unable to merge value from key 'brokers' in Secret 'default/kafka' into target path 'kafka.Brokers': key "net:9092" has no value (cannot end with ,)    │
```

### Steps to reproduce

Secret with a comma separated list of brokers:
```
kafka01.net:9092,kafka02.net:9092,kafka03.net:9092
```

Example HelmRelease yaml:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-app
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: my-chart
      version: "0.1.0-alpha"
      sourceRef:
        kind: HelmRepository
        name: harbor-chart-repo
        namespace: default
  valuesFrom:
    - kind: Secret
      targetPath: kafka.brokers
      name: kafka
      valuesKey: brokers
      optional: false
```

### Expected behavior

The secret value shouldn't be "parsed" with an error outcome.

### Screenshots and recordings

_No response_

### OS / Distro

N/A

### Flux version

v0.17.1

### Flux check

N/A

### Git provider

_No response_

### Container Registry provider

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
You need to escape the comma, as otherwise the parsing logic (which equals `--set` as `helm` itself has when `targetPath` is used) will trip over the value. See also: https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set

The correct value would be: `kafka01.net:9092\,kafka02.net:9092\,kafka03.net:9092`

**Comment by tomasfabian** [comment]
Hi thanks for you reply @hiddeco. 

The creation of the secret is not under our control. We are using the following [kafka-topic-operator](https://github.com/btrace-baader/kafka-topic-operator). 

Thx

**Comment by wuhuizuo** [comment]
> You need to escape the comma, as otherwise the parsing logic (which equals `--set` as `helm` itself has when `targetPath` is used) will trip over the value. See also: https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set
> 
> The correct value would be: `kafka01.net:9092\,kafka02.net:9092\,kafka03.net:9092`

may be it can e solved if flux2 can using `--set-file` instead of `--set`

I occued the issue also, but my content is a json.

**Comment by nourspace** [comment]
I was also hoping that `valuesFrom` could allow using a ConfigMap whose content is a regular `values.yaml` with comments etc.

---
Edit 2025: don't use the `valuesFrom.targetPath` and provide the full yaml values.



```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-app
spec:
  ...
  valuesFrom:
    - kind: Secret
      name: kafka
      optional: false

```
```yaml
kind: Secret
metadata:
  name: kafka
type: Opaque
stringData:  # or data with base64 encoded values.yaml
  values.yaml: |
    kafka:
      brokers: kafka01.net:9092,kafka02.net:9092,kafka03.net:9092
```
