### ISSUE TITLE
Helm deployment not working -- based on docs example

### ISSUE THREAD

**Issue by AnaisUrlichs** [fluxcd/flux2#2629]
### Describe the bug

I tried to install a Helm Chart with Flux:
```
flux create source helm starboard-operator --url https://aquasecurity.github.io/helm-charts --namespace starboard-system
flux create helmrelease starboard-operator --chart aqua/starboard-operator \
  --source HelmRepository/starboard-operator \
  --chart-version 0.10.3 \
  --namespace starboard-system
```
However, that 
![Screenshot 2022-04-08 at 17 20 04](https://user-images.githubusercontent.com/33576047/162482488-0c559753-fec5-435e-8f55-57561831d6b8.png)
did not work:

So I tried the example in the docs: https://fluxcd.io/docs/use-cases/helm/#getting-started
But that did not work either:
![Screenshot 2022-04-08 at 17 20 42](https://user-images.githubusercontent.com/33576047/162482481-d9d421c5-125b-4fdc-8d2c-da6b7956ed74.png)

And I cannot find a better example.

Here is my Kuberentes manifest with which I tried instead:
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: starboard-operator
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://aquasecurity.github.io/helm-charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-operator
  namespace: starboard-system
spec:
  chart:
    spec:
      chart: aqua/starboard-operator
      sourceRef:
        kind: HelmRepository
        name: starboard-operator
        namespace: flux-system
      version: 0.10.3
  interval: 1m0s
```

The HelmRepositories are created as source in the flux-system namespace:
![Screenshot 2022-04-08 at 17 23 01](https://user-images.githubusercontent.com/33576047/162482879-b875f7eb-9f29-42f2-9ee0-211c3da9d33c.png)

Any help would be highly appreciated. 

### Steps to reproduce

Using the above commands to install the helm charts

### Expected behavior

That the Helm chart would get installed?

### OS / Distro

macOS 12.3.1

### Flux version

 v0.28.5

### Flux check

❯ flux check
]► checking prerequisites
✔ Kubernetes 1.21.1 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.18.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.22.3
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.22.5
✔ all checks passed

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
