### ISSUE TITLE
Kustomize rips ImagePolicy comment from image definition

### ISSUE THREAD

**Issue by alec-eu** [fluxcd/flux2#2633]
### Describe the bug

base/podinfo/deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  template:
    spec:
      containers:
        - name: account-web
          image: XXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/podinfo:754754b # {"$imagepolicy": "flux-system:podinfo"}
```

demo/podinfo/kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/podinfo
- podinfo-config.yaml

namespace: demo
```

I am aware of https://github.com/fluxcd/flux2/issues/1522, however I properly indented the spec and it is still removing the comment.

### Steps to reproduce

1. Install flux with image controllers
2. Create a base deployment.yaml that includes an image policy reference
3. Reference that base in a different location, and run kustomize

### Expected behavior

The image policy comment should be appended to the image definition

### OS / Distro

N/A

### Flux version

v0.28.4

### Flux check

N/A

### Git provider

GitHub

### Container Registry provider

ECR

### Additional context

The one thought I had is the line length - since it is using an image from ECR, the line is fairly long with the comment included. So far I have not found any damning evidence that this is the cause, however

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
kustomize the CLI, removes all comments on build. You need to set the image policy comment in the Flux Kustomization object that reconciles the app on the cluster, like so:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  images:
    - name: ghcr.io/stefanprodan/podinfo
      newName: ghcr.io/stefanprodan/podinfo
      newTag: 5.0.0 # {"$imagepolicy": "flux-system:podinfo:tag"}
```

Docs here: https://fluxcd.io/docs/guides/image-update/#configure-image-update-for-custom-resources
