### ISSUE TITLE
HTTPS Authorization Required Error

### ISSUE THREAD

**Issue by texasbobs** [fluxcd/flux2#2642]
### Describe the bug

We have a GitRepository that uses https to access github.com.  We have a secret defined with that GitRepository.  In the secret, we have a
```
data:
  password: base64-Personal-Access-Token
  username: base64-user-name
```
We get the following error from the source controller.
```
{"level":"error","ts":"2022-04-14T20:51:37.566Z","logger":"controller.gitrepository","msg":"Reconciler error","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"GitRepository","name":"edge","namespace":"flux-system","error":"failed to checkout and determine revision: unable to clone 'https://github.com<repo>: authentication required"}
```

We saw a similar [bug](https://github.com/fluxcd/flux2/issues/2596) for GitLabs when accessing a public repo so we upgraded from v0.26.0 to v0.28.5 and got the same error.

### Steps to reproduce

Attempt to use HTTPS to access github.com

### Expected behavior

We expect the credentials provided to be used.

### OS / Distro

k3s v1.21.2+k3s1

### Flux version

v0.26.0 and v0.28.5

### Flux check

n/a

### Git provider

github.com

### Additional context

Using the same credentials, we can clone and push from/to the repository.

We gave the user admin on the repo but that had no effect.

Secret
```
apiVersion: v1
data:
  password: base64-Personal-Access-Token
  username: base64-user-name
kind: Secret
metadata:
  name: flux-secret-https
  namespace: flux-system
type: Opaque
```

GitRepository
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: edge
  namespace: flux-system
spec:
  interval: 15m0s
  ref:
    branch: main
  secretRef:
    name: flux-secret-https
  url: https://github.com/<repo>.git
```  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
