### ISSUE TITLE
postBuild string is sent to boolean entries like string failing kustomize build

### ISSUE THREAD

**Issue by jprecuch** [fluxcd/flux2#2656]
### Describe the bug

I'm not sure how to explain this but when we are trying to adjust "suspend" which is boolean on helmrelease using postBuild varaibles, kustomize validation (kustomize build) always complains about string being used instead of boolean.
We tested this with validate.sh script from https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/scripts/validate.sh
I'm reporting it like issue to confirm it here if it's expected or if there is some normal way to overcome this
```
INFO - Validating kustomization ./infrastructure/applications/sde/
stdin - HelmRelease sde is invalid: For field spec.suspend: Invalid type. Expected: boolean, given: string
``` 
Details:
deploy-charts.yaml
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 3-deploy-helmcharts
  namespace: flux-system
spec:
  path: ./infrastructure/types/dev-hw
  postBuild:
    substitute:
      sde_suspend_release: "false"
```
types:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: deploy-charts-dev-hw
  
resources:
  - ../../applications/sde
```
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sde
  namespace: sde
spec:
   suspend: ${sde_suspend_release}
...
```

### Steps to reproduce

1. Add postBuild string for suspend to "false" or "true"
2. Let it replace spec.suspend in separate helmrelease file
3. Run kustomize build (validate.sh) script and see it ends with
```
stdin - HelmRelease sde is invalid: For field spec.suspend: Invalid type. Expected: boolean, given: string
```

### Expected behavior

spec.suspend (boolean) should be configurable by postBuild somehow and pass validation in kustomize

### OS / Distro

GKE

### Flux version

0.28.5

### Flux check

► checking prerequisites
✗ flux 0.28.5 <0.29.0 (new version is available, please upgrade)
✔ Kubernetes 1.21.6-gke.1503 >=1.20.6-0
► checking controllers
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
