### ISSUE TITLE
Kustomization Path Deleted Causing Controller Error

### ISSUE THREAD

**Issue by stevewallone** [fluxcd/flux2#2660]
### Describe the bug

The below kustomization contains a `path`. If the contents of the path are deleted, that is, all files in the directory are removed, the kustomization controller throws a `no such file or directory` error (see below). 

```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test-crd
  namespace: flux-system
spec:
  interval: 1m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-test-repo
  path: ./crd
  ```
  
  ```
  {"level":"error","ts":"2022-04-20T18:52:32.670Z","logger":"controller.kustomization","msg":"Reconciliation failed after 20.789552ms, next try in 1m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"test-crd","namespace":"flux-system","revision":"master/ad51df9b9d15cf7f7ba3bd275cc3cec395e0f7f0","error":"kustomization path not found: stat /tmp/test-crd55678433/crd: no such file or directory"}
  ```

### Steps to reproduce

For example:
1. Create a directory
2. Add the directory to a Kustomization as the `path:`
3. Add a CRD manifest to the directory.
4. Flux creates the CRD.
5. Remove the CRD file.
6. Flux throws an error

### Expected behavior

I would have expected the controller to realize the directory has been deleted and should in turn delete the resources that were previously deployed. In this example, the directory only contained one CRD manifest. The CRD manifest was deleted, leaving an empty directory. I would have expected the CRD to have been deleted from the cluster. Instead, the CRD remained and the kustomize controller logged an error.

### OS / Distro

Linux

### Flux version

v0.24.1

### Flux check

> flux check 
► checking prerequisites
✗ flux 0.24.1 <0.29.1 (new version is available, please upgrade)
✔ Kubernetes 1.19.10-gke.1602 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.13.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.18.0
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
