### ISSUE TITLE
SOPS secrets generated from ENV files are not getting decrypted 

### ISSUE THREAD

**Issue by networkhell** [fluxcd/flux2#2671]
**Describe the bug**
we are using the flux2 kustomize-controller with in-cluster decryption of sops secrets. I guess we hit an edge case where secrets are not getting decrypted. This problem only affects secrets generated from .env files with the kustomize SecretGenerator. When secrets of this kind are created from the base of the kustomization, these secrets are not decrypted by flux.   

**Steps to reproduce**
- Encrypt .env file with sops
- Reference the .env file in the kustomize SecretGenerator from the base of a kustomization
- Let flux reconcile the kustomization
- Notice that this secret is not decrypted by flux

**Expected behavior**

The secret should be decrypted by flux.

**OS / Distro**
CentOS 7.9

**Flux version**
0.28.5

**Flux check**
✗ flux 0.28.5 <0.29.3 (new version is available, please upgrade)
✔ Kubernetes 1.22.8 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► my-private-registry/hub.docker.com-proxy/fluxcd/helm-controller:v0.18.2
✔ image-automation-controller: deployment ready
► my-private-registry/hub.docker.com-proxy/fluxcd/image-automation-controller:v0.21.3
✔ image-reflector-controller: deployment ready
►my-private-registry/hub.docker.com-proxy/fluxcd/image-reflector-controller:v0.17.1
✔ kustomize-controller: deployment ready
► my-private-registry/hub.docker.com-proxy/fluxcd/kustomize-controller:v0.22.2
✔ notification-controller: deployment ready
► my-private-registry/hub.docker.com-proxy/fluxcd/notification-controller:v0.23.2
✔ source-controller: deployment ready
► my-private-registry/hub.docker.com-proxy/fluxcd/source-controller:v0.22.4
✔ all checks passed

**Git provider**
git 

**Container Registry provider**
Harbor

**Additional context**
Secrets generated like this are not decrypted, when generated in the kustomize "base"
```
secretGenerator:
  - name: my-sops-encrypted-secret
    envs:
    - 'common_secrets/shared-secret.sops.env'
```
whereas secrets get decrypted when generated in the overlay - even from the same file...
```
secretGenerator:
  - name: my-sops-encrypted-secret
    envs:
    - '../../../base/common_secrets/shared-secret.sops.env'
```

**Code of Conduct**
✔ I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
Decryption of files referenced in Kustomization files was refactored in the [kustomize-controller v0.24.0 release](https://github.com/fluxcd/kustomize-controller/blob/main/CHANGELOG.md#0240). Given this (and the extensive test coverage it now has), I expected your issue to be resolved by updating to latest Flux.

**Comment by stefanprodan** [comment]
Kustomize `bases` have been deprecated in favor of `resources` since 2 years now. Flux does not look at bases when scanning the file system for encrypted files.

**Comment by networkhell** [comment]
@stefanprodan thanks for that hint. I replaced all bases directives with resources and it seems to work as intended.
The only strange thing is that it seemed to work with all secrets but env files... 
I will close this one anyways.

**Comment by stefanprodan** [comment]
> The only strange thing is that it seemed to work with all secrets but env files...

That's because we decrypt the env files before the build process, all the other secret file types are decrypted during the build. Anyway we should add to the docs a note on bases being deprecated and not used by Flux, why kutomize keeps them around after 2+ years I can't say.

**Comment by bernardgut** [comment]
I just spent hours banging my head on the same issue so for anyone that ends up here because for some reason their dotenv file does not get encrypted :

**Your file path must end with the characters ".env" for the decryption to work.** 
eg:
```
 secretGenerator:
  - name: my-sops-encrypted-secret
    envs:
    - 'common_secrets/shared-secret.sops.env'
```
will work but 
```
secretGenerator:
  - name: my-sops-encrypted-secret
    envs:
    - 'common_secrets/shared-secret.sops.env.enc'
```
will **not** work

hope this helps someone avoid the waste of time I had.
