### ISSUE TITLE
Updating the `spec.ignore` field of a `GitRepository` has no effect

### ISSUE THREAD

**Issue by angelokurtis** [fluxcd/flux2#2693]
### Describe the bug

When editing a `GitRepository` resource whose the `spec.ignore` field is already set the new ignored paths are not updated and the configuration has no effect.

### Steps to reproduce

1. Install Flux
2. Create a `GitRepository` setting the `spec.ignore` field. eg:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: istio
spec:
  interval: 10s
  url: https://github.com/istio/istio
  ref:
    semver: ~1.13.3
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/manifests
```
3. Check if the created resource is ready. eg:
```
❯ kubectl get gitrepository.source.toolkit.fluxcd.io/istio
NAME    URL                              AGE   READY   STATUS
istio   https://github.com/istio/istio   29m   True    stored artifact for revision '1.13.3/b28579cb30c12c428ea58279b7c06f3302abe924'
```
4. Then, remove the  `spec.ignore` field. eg:
```
❯ kubectl patch gitrepository.source.toolkit.fluxcd.io/istio --type='json' -p='[{"op":"remove","path":"/spec/ignore"}]'
```

### Expected behavior

The generated artifact should be updated and the new `tar.gz` must contain all expected paths that were previously ignored.

### OS / Distro

Ubuntu 20.04

### Flux version

v0.29.5

### Flux check

► checking prerequisites
✔ Kubernetes 1.23.5 >=1.20.6-0
► checking controllers
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
