### ISSUE TITLE
Kustomizations without a base do not apply

### ISSUE THREAD

**Issue by daveoy** [fluxcd/flux2#2704]
### Describe the bug

according to [the FAQ](https://fluxcd.io/docs/faq/#how-to-patch-coredns-and-other-pre-installed-addons) we should be able to patch arbitrary pre-installed resources using kustomize objects.

I have not been able to patch any using the (limited) instructions in the FAQ. 

### Steps to reproduce

1. install flux
2. create kustomization with patchesStrategicMerge
3. reconcile kustomization

### Expected behavior

resource patched with provided patch

### Screenshots and recordings

kustomization:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: weave-liveness.yaml
  target:
    kind: DaemonSet
    name: weave-net
    namespace: kube-system
```

weave-liveness.yaml:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kustomize.fluxcd.toolkit.io/ssa: merge
  name: weave-net
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: weave
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /home/weave/weave --local status connections | grep fastdp
          initialDelaySeconds: 20
          periodSeconds: 5
```

no errors, but also no change / no output.
```
# kubectl get kustomizations.kustomize.toolkit.fluxcd.io -n flux-system weave-net
NAME        AGE   READY   STATUS
weave-net   22h   True    Applied revision: main/ca160ca0ec5d1ef98cb6fc368d09e6e09195f1ab
```

### OS / Distro

centos 7.7

### Flux version

v0.28.4

### Flux check

# flux check
► checking prerequisites
✔ Kubernetes 1.23.3 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► car:5000/helm-controller:v0.18.2
✔ image-automation-controller: deployment ready
► car:5000/image-automation-controller:v0.21.2
✔ image-reflector-controller: deployment ready
► car:5000/image-reflector-controller:v0.17.1
✔ kustomize-controller: deployment ready
► car:5000/kustomize-controller:v0.22.2
✔ notification-controller: deployment ready
► car:5000/notification-controller:v0.23.1
✔ source-controller: deployment ready
► car:5000/source-controller:v0.22.4
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Delete the `kustomization.yaml`, and let Flux sync the `weave-liveness.yaml`. 

Patching in-cluster objects is not a Kustomize feature but a Flux one. Kustomize is all about files on disk, you can't patch something that's not on the file system with it.

**Comment by stefanprodan** [comment]
`flux tree ks flux-system` should tell if it manages the weave-net daemonset. Can post `tree ./clusters`? I suspect you placed the file in a dir that's not actually synced. The file should be on the same level with the `flux-system` dir, for example in here: https://github.com/fluxcd/flux2-multi-tenancy/tree/main/clusters/production

**Comment by daveoy** [comment]
source and kustomize object is here:
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@<githubserver:org/repo.git>
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./<clustername>/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```


tree of this cluster (there are many in the repo):
```
├── <clustername>
│   ├── flux-system
│   │   ├── gotk-components.yaml
│   │   ├── gotk-sync.yaml
│   │   ├── kustomization.yaml
│   │   ├── kustomize-controller-resources.yaml
│   │   ├── source-controller-resources.yaml
│   │   └── third-party-repos.yaml
│   ├── releases
│   │   ├── grafana.yaml
│   │   ├── istio-base.yaml
│   │   ├── istiod.yaml
│   │   ├── istio-ingressgateway.yaml
│   │   ├── kiali-operator.yaml
│   │   ├── kube-prometheus-stack.yaml
│   │   ├── kube-state-metrics.yaml
│   │   ├── kustomization.yaml
│   │   ├── loki.yaml
│   │   └── node-exporter.yaml
│   └── weave-liveness.yaml
```
have also had no success with the weave-liveness.yaml inside the flux-system directory.

`flux tree ks flux-system` does not list the weave-net daemonset

**Comment by lunderhage** [comment]
I have this exact problem trying to patch a deployment which ofc is a result of applying a helmrelease.

**Comment by daveoy** [comment]
> I have this exact problem trying to patch a deployment which ofc is a result of applying a helmrelease.

So yes this is actually my next question. I figured the answer to this issue would illuminate that.

**Comment by stefanprodan** [comment]
@lunderhage @daveoy to patch any resource in a HelmRelease you can use postRenderers, docs here:  https://fluxcd.io/docs/components/helm/helmreleases/#post-renderers

**Comment by stefanprodan** [comment]
@daveoy this path is wrong `path: ./<clustername>/flux-system` It should point to the cluster dir. You may want to start fresh with `flux bootstrap` and check out the example repos e.g. https://github.com/fluxcd/flux2-kustomize-helm-example

**Comment by daveoy** [comment]
> @daveoy this path is wrong `path: ./<clustername>/flux-system` It should point to the cluster dir. You may want to start fresh with `flux bootstrap` and check out the example repos e.g. https://github.com/fluxcd/flux2-kustomize-helm-example 

I have arranged my git repo and modified my kustomize objects to solve a teardown / first-run dependency cycle situation. I have added kustomize objects to point at the rest of the folders in my repo with dependsOn attributes as required. 

I will attempt to reset the flux-system kustomize object as best I can to accomplish this patching by following the example you posted, however shouldn't I be able to do this patching with any kustomize object? Not just flux-system?

**Comment by stefanprodan** [comment]
> houldn't I be able to do this patching with any kustomize object? Not just flux-system?

Yes for sure, also adding that file to `flux-system` dir and including it the `resources` array will have the same effect.

**Comment by lunderhage** [comment]
Adding the patch in the helmrelease under postRenderers sorted my problem. Thank you for your help!

**Comment by daveoy** [comment]
> https://fluxcd.io/docs/components/helm/helmreleases/#post-renderers

trying this out, i had the same thing happen -- my patch is not applied and there are no errors:

helmrelease:
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: flux-system
spec:
  interval: 1m
  dependsOn: 
  - name: istiod
  targetNamespace: istio-system
  chart:
    spec:
      chart: ./manifests/charts/gateways/istio-ingress/
      sourceRef:
        kind: GitRepository
        name: istio
        namespace: flux-system
      interval: 1m
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Service
            apiVersion: v1
            metadata:
              name: istio-ingressgateway
              namespace: istio-system
            spec:
              externalIPs:
              - <ip address>
  values:
    name: istio-ingressgateway
    global:
      hub: car:5000/istio-release
      tag: 1.13.2
    gateways:
      istio-ingressgateway:
        type: ClusterIP
```
is there a kustomize setting im missing here?

**Comment by daveoy** [comment]
> > houldn't I be able to do this patching with any kustomize object? Not just flux-system?
> 
> Yes for sure, also adding that file to `flux-system` dir and including it the `resources` array will have the same effect.

@stefanprodan are you suggesting i add the strategic merge formatted patch under 'resources'?

**Comment by stefanprodan** [comment]
> are you suggesting i add the strategic merge formatted patch under 'resources'?

Yes, you may need to add the pod label selectors too, like in the CoreDNS example.

> is there a kustomize setting I'm missing here?

I think the namespace is injected at apply time. You can use a patch and target the service by name only. On my Istio cluster this works fine:


```yaml
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              kind: Service
              apiVersion: v1
              metadata:
                name: istio-gateway
              spec:
                externalIPs:
                  - 10.124.14.56
            target:
              kind: Service
              name: istio-gateway
```

Note that I'm using a different chart called gateway, so you need to map the name to your service.
