### ISSUE TITLE
Container image update for custom resources

### ISSUE THREAD

**Issue by Morriz** [fluxcd/flux2#272]
Are you guys open to try to make this engine work with CRs? There are quite some people out there that would love to see gotk reconcile CRs such like a knative service. It would be awesome to let gotk scan any resource with a label such as:
```
...
    labels:
        app.kubernetes.io/managed-by: gotk
```
and then allow it to update the resource's container image tag using annotations like:
```
...
    annotations:
        fluxcd.io/automated: 'true'
        fluxcd.io/tag.somecontainername: "semver:~1.1"
        # and maybe allow a pointer to the place of the container spec in the resource for other scenarios:
        # fluxcd.io/spec.location: "spec.template.spec" (default)
```
I believe all the parts are already in place, right?

A similar request like this was long outstanding in the old flux repo, but I thought I would start it afresh here.
