### ISSUE TITLE
Kustomization path fails with a set

### ISSUE THREAD

**Issue by M-Gregoire** [fluxcd/flux2#2735]
### Context

I'm trying to run only a specific YAML from a folder, inside a Git Repository

### Documentation

The documentation of the [Kustomize](https://fluxcd.io/docs/components/kustomize/api/#kustomize.toolkit.fluxcd.io/v1beta2) API specifies the following:

path (string) | (Optional)Path to the directory containing the kustomization.yaml file, or the set of plain YAMLs a kustomization.yaml should be generated for. Defaults to ‘None’, which translates to the root path of the SourceRef.
-- | --

### Using a Set

Passing only the wanted YAML fails with:
```
"error":"open /tmp/kustomization-1740197060/deploy/examples/toolbox.yaml/kustomization.yaml: not a directory
```
This is kinda expected since a directory is wanted.

However, according to the documentation, I can provide `the set of plain YAMLs a kustomization.yaml should be generated for`, but this also fails:
```
error: failed to create typed patch object: .spec.path: expected string, got &value.valueUnstructured{Value:map[string]interface {}{\"./deploy/examples/toolbox.yaml\":\"\"}  
```

### Steps to reproduce

1. Add the Git Repository:
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: rook-git
  namespace: rook-ceph
spec:
  interval: 5m
  url: https://github.com/rook/rook.git
  ref:
    branch: master
```

2. Try to load only one YAML:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rook-ceph-toolbox
  namespace: rook-ceph
spec:
  interval: 10m0s
  path: {./deploy/examples/toolbox.yaml}
  prune: true
  sourceRef:
    kind: GitRepository
    name: rook-git
  timeout: 2m
```

### Expected behavior

I expected `toolbox.yaml` to deploy.

### OS / Distro

NixOS

### Flux version

v0.30.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.3+k3s1 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.21.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.5
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.4
✔ all checks passed

### Additional context

I'm sorry if this is a wrong understanding of the documentation on my part.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
