### ISSUE TITLE
Flux crd dryrun error on version upgrade

### ISSUE THREAD

**Issue by jambu** [fluxcd/flux2#2743]
### Describe the bug

I have full cluster definitions which was previously running on flux 0.17.2. I used the latest flux version and tried to bring up the same cluster.
I use flux install command to get the components file and then kubectl apply them.
flux install --export > gotk-components.yaml

```
$ flux30 get kustomizations
NAME            REVISION        SUSPENDED       READY   MESSAGE
flux-system                     False           False   CustomResourceDefinition/buckets.source.toolkit.fluxcd.io dry-run failed, reason: Invalid, error: CustomResourceDefinition.apiextensions.k8s.io "buckets.source.toolkit.fluxcd.io" is invalid: status.storedVersions[0]: Invalid value: "v1beta2": must appear in spec.versions
```
I keep getting this error, I am not sure if I have to migrate apiVersion in my gitrepository objects. I tried that too and it didnt work. 

I did go through these steps
https://github.com/fluxcd/flux2/discussions/2567

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: <sshurl>
  ```

### Steps to reproduce

Install latest flux using flux 0.17.2 definitions.

### Expected behavior

Kustomiation should reconcile

### OS / Distro

ubuntu

### Flux version

v0.30.2

### Flux check

ubuntu@ip-172-16-3-97:~$ flux30 check
► checking prerequisites
✔ Kubernetes 1.21.7 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.21.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.5
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.4
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
