### ISSUE TITLE
GitRepository support for fallback url

### ISSUE THREAD

**Issue by Daklon** [fluxcd/flux2#2761]
### Describe the bug

On my current company we are using flux on all of our clusters. We started to move all of our services from ec2 instances to k8s. The latest thing that we moved was our self hosted Gitlab. 

The problem was when we moved gitlab to k8s, flux deleted everything that it manages. We had to disable flux on our infrastructure cluster and deploy everything manually until we address this problem. I had the oportunity to talk about it with Scott Rigby during the Europe Kubecon 2022 and he explained to me why it happened and that flux expect to have git source somewhere else. Since Flux needs Gitlab to deploy Gitlab, is a chicken egg problem.

I have a proposal to addres this problem, since we need flux to deploy and use our Gitlab I have been thinking on having a fall back url.

The following is a very quick (and probably could be improved proposal):
```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/stefanprodan/podinfo
  fallbackUrl: https://gitlab.com/stefanprodan/podinfo
  ref:
    branch: master
```

The idea is to have flux using the normal url as it's currently doing. But if for some reason the main url fails, it will try with the fallbackUrl which should be a mirror of the main url. Also this parameter could be optional so it will not break the current usage.

I'm also willing to try to implement this but wanted to know what do you think first.

### Steps to reproduce

N/A

### Expected behavior

N/A

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by achetronic** [comment]
@stefanprodan @hiddeco 
Hello there,
Think that this would be a good solution for the use case. This will allow Gitlab to create mirrors outside, for example in GitHub. What is your opinion about it?

**Comment by stefanprodan** [comment]
I'm not in favour if this, you can't have a backup by just providing a different URL, for SSH the deploy keys are unique per repo so the auth will fail, same with HTTPS access, a GitHub token will not work on GitLab.

**Comment by Daklon** [comment]
Yes, you are right, I didn't thought about the different ssh keys and https tokens. I have a second proposal that could fit here.
Instead of having a fallback url defined on the gitrepository, what about having two different gitrepositories, each one configured to his own git server. But allowing to have the fallback logic at kustomization level, let me add an example of how it could be:

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo-github
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo-gitlab
  namespace: default
spec:
  interval: 5m0s
  url: https://gitlab.com/stefanprodan/podinfo
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo-gitlab
  fallbackSourceRef:
    kind: GitRepository
    name: podinfo-github
```

The fallbackSourceRef is the first name that came to my mind but could be changed, I'm open to ideas about this :smiley:
