### ISSUE TITLE
Add `--ignore-path` to `flux create source`

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#2763]
We need to add a new arg (string array) to `flux create source git` and `flux create source bucket` that populates the `ignore` spec filed, each arg would add a new line to the ignore value e.g.:

```sh
flux create source git podinfo \
--url=https://github.com/stefanprodan/podinfo \
--branch=master \
--ignore-path=".git/" \
--ignore-path=".github/" \
--export
```

The above command will generate:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
  ignore: |
    .git/
    .github/
```
