### ISSUE TITLE
Error looking up service account XXX because it is not found, although it's in the manifest

### ISSUE THREAD

**Issue by doctorpangloss** [fluxcd/flux2#2772]
### Describe the bug

When I define a ServiceAccount and a Pod that uses it in the same file in an empty (implicit Kustomize) directory in my flux managed git repo, Flux fails to reconcile. I expect it to work, because it is super routine.

### Steps to reproduce

 1. Create an 1.22 EKS cluster with flux installed via eksctl.
 2. Write the calicoctl.yaml to an empty kube-system directory in your repo:
     ```
     mkdir -pv kube-system
     curl -L https://projectcalico.docs.tigera.io/manifests/calicoctl.yaml > ./kube-system/calicoctl.yaml
     ```
  3. Observe the following failure:
```sh
flux-system     kustomization/flux-system       False   Pod/kube-system/calicoctl dry-run failed, reason: Forbidden, error: pods "calicoctl" is forbidden: error looking up service account kube-system/calicoctl: serviceaccount "calicoctl" not found       main/d53c4c388b4fac63493368e5794b4cdb21604809   False
```
 4. Observe `kubectl apply -f calicoctl.yaml` works just fine.

### Expected behavior

It should reconcile.

### Kubernetes version / Distro / Cloud provider

EKS v1.22.6

### Flux version

flux manifests :v0.24.1
flux cli: v0.24.1

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by makkes** [comment]
kustomize-controller applies resources in two stages:
1. Namespaces and CRDs
2. all other resources
Since the ServiceAccount is part of stage two, the dry-run will fail. In your case I would employ two Kustomzations, one that creates the ServiceAccount and another one that creates the Pod and then let the latter depend on the former: https://fluxcd.io/docs/components/kustomize/kustomization/#kustomization-dependencies

**Comment by makkes** [comment]
Another option would be to use a Deployment instead of a Pod directly.

**Comment by stefanprodan** [comment]
> Another option would be to use a Deployment instead of a Pod directly.

Yes that's the best option, Flux is not meant to manage pods directly, using a Deployment or Job is what we expect.

**Comment by doctorpangloss** [comment]
Should Flux2 work with Calico's real manifest? It would be painful to patch this. They may have set the manifest up exactly the way it is in response to other bugs.

**Comment by stefanprodan** [comment]
@doctorpangloss that pod does do much, it just prints the version inside the container:

```
apiVersion: v1
kind: Pod
metadata:
  name: calicoctl
  namespace: kube-system
spec:
  nodeSelector:
    kubernetes.io/os: linux
  hostNetwork: true
  serviceAccountName: calicoctl
  containers:
  - name: calicoctl
    image: calico/ctl:v3.23.1
    command:
      - /calicoctl
    args:
      - version
      - --poll=1m
    env:
    - name: DATASTORE_TYPE
      value: kubernetes
```

We have no plans on supporting managing pods with Flux, the above could be a Deployment with a single replica.
