### ISSUE TITLE
Handle multi-doc `kustomize.toolkit.fluxcd.io/v1beta2` YAML within flux build

### ISSUE THREAD

**Issue by anthr76** [fluxcd/flux2#2780]
### Describe the bug

When using on-disk local flux Kustomization file that is a multi-doc yaml patches within it aren't "built" on `flux build`

### Steps to reproduce

1. Consider a `flux-kustomize.yaml` like:

```yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-namespace
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/infra"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kps
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/infra/kps"
  prune: true
  patches:
    - patch: |
        - op: add
          path: /spec/values/kubeEtcd/endpoints
          value:
            - 192.168.8.40
            - 192.168.8.47
            - 192.168.8.51
      target:
        kind: HelmRelease
        name: kube-prometheus-stack
        namespace: monitoring
```
2. `flux build kustomization kps --path ./k8s/base/infra/kps --kustomization-file ./k8s/clusters/cluster-0/definitions/infra.yaml`

The kustomization will build successfully outputting the multi-doc yaml of `./k8s/base/infra/kps` but **not** include the patches in the `kps` `kustomize.toolkit.fluxcd.io/v1beta2` flux kustomize file.

If you were to take the above example and make it:

`flux-test.yaml`

```yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kps
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/infra/kps"
  prune: true
  patches:
    - patch: |
        - op: add
          path: /spec/values/kubeEtcd/endpoints
          value:
            - 192.168.8.40
            - 192.168.8.47
            - 192.168.8.51
      target:
        kind: HelmRelease
        name: kube-prometheus-stack
        namespace: monitoring
```

and do `flux build kustomization kps --path ./k8s/base/infra/kps --kustomization-file ./flux-test.yaml` it would build correctly with it's patches.

### Expected behavior

Correct output when using flux build when your `--kustomization-file` containers multi-doc yaml of `kustomize.toolkit.fluxcd.io/v1beta2`s

### OS / Distro

N/A

### Flux version

flux: v0.30.2

### Flux check

```
► checking prerequisites
✔ Kubernetes 1.23.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► fluxcd/helm-controller:v0.21.0
✔ image-automation-controller: deployment ready
► fluxcd/image-automation-controller:v0.22.1
✔ image-reflector-controller: deployment ready
► fluxcd/image-reflector-controller:v0.18.0
✔ kustomize-controller: deployment ready
► fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► fluxcd/notification-controller:v0.23.5
✔ source-controller: deployment ready
► fluxcd/source-controller:v0.24.4
✔ all checks passed
```

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
