### ISSUE TITLE
Kustomize deployment patch with updated image does not get updated by automation

### ISSUE THREAD

**Issue by marvin-w** [fluxcd/flux2#2826]
### Describe the bug

Image Automation Updates do not seem to work with kustomize patches.

Is this supported or am I missing something here?

### Steps to reproduce

1. Install flux with the additional image automation controllers
2. Create a test deployment with Kustomize with two overlays (dev and prod)
3. Define a ImagePolicy and an ImageRepository in the base
4. Define an ImageUpdateAutomation in the namespace (dev and prod)
5. Make sure the GitRepository exists in the namespaces (dev and prod)
6. Patch the deployment image in the overlay and attach the policy to the patch

Path in Git Repo: `./apps/data-receiver/overlay/dev/deployment-patch.yaml`

```yaml
- op: replace
  path: /spec/template/spec/containers/0/image
  value: registry.gitlab.com/group/repo:develop-0f33caff-60 # {"$imagepolicy": "dev:data-receiver-policy"}
```

7. Verify that the policy works:

```
NAME                        LATESTIMAGE
data-receiver-policy   registry.gitlab.com/group/repo:develop-8485bcbc-62
```

8. Check the status of the ImageUpdateAutomation

```
Status:
  Conditions:
    Last Transition Time:    2022-06-08T23:40:08Z
    Message:                 no updates made
    Reason:                  ReconciliationSucceeded
    Status:                  True
    Type:                    Ready
  Last Automation Run Time:  2022-06-09T00:21:32Z
  Observed Generation:       1
```

```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: update-automation
  namespace: dev
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./apps
    strategy: Setters
```

From the documentation I got that the ImageUpdateAutomation has to be in the same namespace then the Policy. This is the case here. Both reside in the dev namespace.

Result: The image does not get updated.

### Expected behavior

I expect the image to get updated and the deployment patch to be updated with the new image tag when running the above steps

### OS / Distro

Ubuntu 20.04

### Flux version

v0.31.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.9-eks-a64ea69 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.22.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.23.2
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.19.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.26.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.24.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.25.5
✔ all checks passed

### Git provider

GitLab

### Container Registry provider

GitLab Container Registry

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
As described here https://fluxcd.io/docs/guides/image-update/#configure-image-update-for-custom-resources Flux can only patch Kubernetes manifests. This means the YAML manifest must have `apiVersion` and `kind` fields. Instead of using that JSON patch, you can use the `images` directive like so:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: registry.gitlab.com/group/repo
  newTag: develop-0f33caff-60 # {"$imagepolicy": "dev:data-receiver-policy:tag"}
```
