### ISSUE TITLE
Kustomize intermittent errors with KNative PingSource

### ISSUE THREAD

**Issue by GJKrupa** [fluxcd/flux2#2833]
### Describe the bug

I've created an installation on Raspberry Pi with KNative (with some creative patching to get the Kourier ingress working) and a Service that has a PingSource triggering a weekly job. I've found that the Kustomization that contains this PingSource frequently errors with the following:

```
apps   106d   False   PingSource/my-app/my-app-notify dry-run failed, error: failed to prune fields: failed add back owned items: failed to convert pruned object at version sources.knative.dev/v1beta2: conversion webhook for sources.knative.dev/v1, Kind=PingSource returned invalid metadata: invalid metadata of type <nil> in input object
```

### Steps to reproduce

1. Install flux with the image automation controllers
2. Install KNative operator `kubectl apply -f https://github.com/knative/operator/releases/latest/download/operator.yaml`
3. Install KNative serving and eventing in their own Kustomization using the appropriate resources:
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: "1.4"
  ingress:
    kourier:
      enabled: true
  config:
    network:
      domain-template: "{{.Name}}.{{.Domain}}"
      ingress-class: "kourier.ingress.networking.knative.dev"
    domain:
      my-domain.com: ""
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  version: "1.4"
```
4. (optional, for ARM only) patch the 3scale-kourier-gateway-xxx pod to run Envoy version v1.16-latest
5. Deploy an apps Kustomization that looks similar to the following:
```
kind: ImageRepository
metadata:
  name: my-app
  namespace: my-app
spec:
  image: my-registry/my-app
  interval: 5m
  secretRef:
    name: gitlab
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: my-app
  namespace: my-app
spec:
  filterTags:
    pattern: '.*'
  imageRepositoryRef:
    name: my-app
  policy:
    semver:
      range: ">=0.0.1"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-app
  namespace: my-app
  annotations:
    custom-hostname: my-app
spec:
  template:
    spec:
      imagePullSecrets:
      - name: my-secret
      containers:
      - name: app
        image: my-registry/my-app:2.0.0 # {"$imagepolicy": "my-app:my-app"}
        ports:
        - containerPort: 8080
          name: http1
        resources:
          requests:
            memory: "8Mi"
            cpu: "1m"
          limits:
            memory: "32Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
        livenessProbe:
          httpGet:
            path: /health
---
kind: PingSource
apiVersion: sources.knative.dev/v1beta2
metadata:
  namespace: my-app
  name: my-app
spec:
  schedule: "30 17 * * WED"
  timezone: "Europe/London"
  contentType: application/json
  data: '{"ping": "yes"}'
  sink:
    uri: "/notify"
    ref:
      namespace: my-app
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: my-app
```

### Expected behavior

The kustomization deploys without error and updates when a new image is pushed.

### Screenshots and recordings

![CleanShot 2022-06-12 at 21 07 25@2x](https://user-images.githubusercontent.com/5756726/173251433-45967ae6-18ae-4739-bff8-034114e699d6.png)

### OS / Distro

Raspberry Pi 4B (8GB) running Debian GNU/Linux 11 (bullseye) 64-bit

### Flux version

v0.30.2

### Flux check

► checking prerequisites
✗ flux 0.30.2 <0.31.1 (new version is available, please upgrade)
✔ Kubernetes 1.23.6+k3s1 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.21.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.22.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.18.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.5
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.4
✔ all checks passed

### Git provider

gitlab.com

### Container Registry provider

gitlab.com

### Additional context

The error occurs intermittently with every apply of the apps kustomization even if the resource in question wasn't updated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
