### ISSUE TITLE
Image automation controlling in not committing new versions in source

### ISSUE THREAD

**Issue by pratikbin** [fluxcd/flux2#2853]
### Describe the bug

I'm seeing container images new versions are not getting committed to git for some reason. I can see image reflector controller can identify new versions of images from our docker hub registry, so looks like something with the image automation controller. Weird thing is, I can't see anything in image automation controller logs. It's just workers starting logs. BTW, I'm using plain manifest files.

### Steps to reproduce

Putting necessary manifest below with repo structure. I don't think it's reproducible but we can

```log
/cluster-1/flux-system/imageUpdateAutomation.yaml
/cluster-1/prod/imageRepo.yaml
/cluster-1/prod/deployment.yaml
/cluster-1/prod/imagePolicy.yaml
/cluster-1/dev/imagePolicy.yaml
/cluster-1/dev/deployment.yaml
```

```yaml
# /cluster-1/flux-system/imageUpdateAutomation.yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: k8s-infra
  namespace: flux-system
spec:
  interval: 3m0s
  sourceRef:
    kind: GitRepository
    name: k8s-infra
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: me@users.noreply.github.com
        name: me
      messageTemplate: |
        Automated image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}
    push:
      branch: main
  update:
    path: "./cluster-1"
    strategy: Setters
```

```yaml
# /cluster-1/prod/imageRepo.yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: service
  namespace: prod
spec:
  image: docker.io/me/...
  interval: 5m0s
  secretRef:
    name: dockerhub-registry-creds
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: prod
```

```yaml
# /cluster-1/prod/imagePolicyAndRepo.yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: prod-policy
  namespace: prod
spec:
  imageRepositoryRef:
    name: service
    namespace: prod
  filterTags:
    pattern: '^prod-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
```

```yaml
# /cluster-1/dev/imagePolicy.yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: dev-policy
  namespace: dev
spec:
  imageRepositoryRef:
    name: service
    namespace: dev
  filterTags:
    pattern: '^edge-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
```

### Expected behavior

It should commit.

### Screenshots and recordings

```log
NAMESPACE          NAME                                                   LATESTIMAGE
dev                imagepolicy.image.toolkit.fluxcd.io/dev                 docker.io/../..:edge-639c03e-1654079997
prod               imagepolicy.image.toolkit.fluxcd.io/prod                docker.io/../..:latest-38e05a5-1653930561

NAMESPACE          NAME                                                  LAST SCAN              TAGS
dev                imagerepository.image.toolkit.fluxcd.io/service        2022-06-19T19:39:05Z   26

NAMESPACE     NAME                                                      LAST RUN
flux-system    imageupdateautomation.image.toolkit.fluxcd.io/k8s-infra    2022-06-19T19:43:00Z
```

### OS / Distro

N/A

### Flux version

v0.31.0

### controller versions

* source-controller [v0.25.3](https://github.com/fluxcd/source-controller/blob/v0.25.3/CHANGELOG.md)
* kustomize-controller [v0.26.0](https://github.com/fluxcd/kustomize-controller/blob/v0.26.0/CHANGELOG.md)
* helm-controller [v0.22.0](https://github.com/fluxcd/helm-controller/blob/v0.22.0/CHANGELOG.md)
* notification-controller [v0.24.0](https://github.com/fluxcd/notification-controller/blob/v0.24.0/CHANGELOG.md)
* image-reflector-controller [v0.19.0](https://github.com/fluxcd/image-reflector-controller/blob/v0.19.0/CHANGELOG.md)
* image-automation-controller [v0.23.0](https://github.com/fluxcd/image-automation-controller/blob/v0.23.0/CHANGELOG.md)

### Flux check

$ flux check
► checking prerequisites
✔ Kubernetes 1.21.12-eks-a64ea69 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► fluxcd/helm-controller:v0.22.0
✔ image-automation-controller: deployment ready
► fluxcd/image-automation-controller:v0.23.0
✔ image-reflector-controller: deployment ready
► fluxcd/image-reflector-controller:v0.19.0
✔ kustomize-controller: deployment ready
► fluxcd/kustomize-controller:v0.26.0
✔ notification-controller: deployment ready
► fluxcd/notification-controller:v0.24.0
✔ source-controller: deployment ready
► fluxcd/source-controller:v0.25.3
✔ all checks passed

### Git provider

github

### Container Registry provider

docker

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aryan9600** [comment]
Could you make sure that your Deployment or Kustomization config yaml has the required kyaml setters?

**Comment by pratikbin** [comment]
I'm using plain deployment manifest. Let me edit the issue as well.

```yaml
...
    spec:
      containers:
      - name: mantleplace
        image: docker.io/../..:edge-639c03e-1654079996 # {"$imagepolicy": "dev:dev"}
...
```
