### ISSUE TITLE
Can't create HelmChart using OCI HelmRepository from Azure Container Registry

### ISSUE THREAD

**Issue by marvin-garcia** [fluxcd/flux2#2900]
### Describe the bug

I packaged a Helm chart and pushed it to an Azure Container Registry. My chart address is oci://marvacr.azurecr.io/helm/carapi.

I am able to install the chart using `helm install  myrelease --repo oci://marvacr.azurecr.io/helm/carapi` and can see my chart's information using `helm show all oci://marvacr.azurecr.io/helm/carapi`.

- My **HelmRepository** object: 
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: carapi
  namespace: cluster-config
spec:
  type: "oci"
  interval: 5m
  secretRef:
    name: acr
  url: oci://marvacr.azurecr.io/helm/carapi
```

- My **HelmRelease** object:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carapi
  namespace: cluster-config
spec:
  targetNamespace: carapi
  releaseName: carapi
  chart:
    spec:
      chart: carapi
      version: "1.0.0"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: carapi
        namespace: cluster-config
  interval: 5m
  install:
    remediation:
      retries: 3
```

- Error message from **HelmChart**:
```
chart pull error: chart pull error: failed to get chart version for remote reference: GET "https://
marvacr.azurecr.io/v2/helm/carapi/carapi/tags/list": unexpected status code 404: name unknown: repository "helm/carapi/carapi" is not found
```

I am not aware of the conversion from the HelmChart definition to helm commands, but Flux is appending the chart name to the repository URL and using the wrong URL to retrieve repository tags, therefore causing a 404 error.

### Steps to reproduce

1. Create objects mentioned earlier and attempt to deploy the configuration.

### Expected behavior

The correct endpoint to retrieve Helm chart tags from Azure Container Registry is `https://marvacr.azurecr.io/acr/v1/helm/carapi/_tags`. 

Instead, Flux is using `https://marvacr.azurecr.io/v2/helm/carapi/carapi/tags/list`.

### OS / Distro

Ubuntu 20.04

### Flux version

v0.31.2

### Flux check

N/A (Using Flux through `Microsoft.flux` extension for Azure Arc for Kubernetes).

### Container Registry provider

Azure Container Registry

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
You should omit `/carapi` in the HelmRepository object, this part of the URL is defined as the chart name.

**Comment by mitrx** [comment]
I think I am having the same issue. I am trying to deploy an ACK controller for AWS S3 https://aws-controllers-k8s.github.io/community/docs/user-docs/install/. I can deploy it successfully executing a helm command according to the instructions
```
helm install --create-namespace -n ack-system ack-s3-controller oci://public.ecr.aws/aws-controllers-k8s/s3-chart --version=v0.1.3 --set=aws.region=eu-west-2
```
but when I apply the following manifests
### ack.yaml
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ack-s3-source
  namespace: ack-system
spec:
  interval: 1m0s
  type: "oci"
  url: oci://public.ecr.aws/aws-controllers-k8s
```
### release.yaml
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ack-s3-controller
  namespace: ack-system
spec:
  chart:
    spec:
      chart: s3-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ack-s3-source
        namespace: ack-system
      version: v0.1.3
  interval: 1m0s
```
I get
```
chart pull error: chart pull error: failed to get chart version for remote reference: GET "https://public.ecr.aws/v2/aws-controllers-k8s/s3-chart/tags/list": unexpected status code 404: Not Found
```
I tried both URLs `oci://public.ecr.aws/aws-controllers-k8s` and `oci://public.ecr.aws/aws-controllers-k8s/s3-chart` but the error stays the same.
I would assume helm controller treats URL as a Helm HTTP/S repository for some reason.
### `flux version` output
```
flux: v0.31.3
helm-controller: v0.22.1
kustomize-controller: v0.26.2
notification-controller: v0.24.0
source-controller: v0.25.9
```
