### ISSUE TITLE
ImageUpdate reconciliation complains about missing python

### ISSUE THREAD

**Issue by fuero** [fluxcd/flux2#2908]
### Describe the bug

Reconciling an image update automation results in this output:

```bash
$ flux reconcile -n limesurvey image update limesurvey
► annotating ImageUpdateAutomation limesurvey in limesurvey namespace
✔ ImageUpdateAutomation annotated
◎ waiting for ImageUpdateAutomation reconciliation
✗ ImageUpdateAutomation reconciliation failed: 'stat /tmp/flux-system-flux-system524747141/k3s/test-env/bin/python: no such file or directory'
```

The controller doesn't apply the commit with the updated image tag.

### Steps to reproduce

1. Install flux with image* controllers
2. Create imagerepository, imagepolicy, imageautomation.
3. Verify that the former 2 are working fine with `flux reconcile`
4. Call `flux reconcile -n limesurvey image update limesurvey --verbose`

### Expected behavior

Deployment being updated as documented.

### OS / Distro

Rocky 8 (k8s host), Arch (client)

### Flux version

0.31.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.2+k3s2 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.22.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.24.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.23.4
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.19.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.25.9
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.26.2
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

Generic git

### Container Registry provider

Artifactory

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuero** [comment]
So here's what it looks like - I've only included the parts that seem relevant, there's more in the repo.

```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: limesurvey
  namespace: limesurvey
spec:
  image: path/to/my/image:tag
  interval: 10m0s
  secretRef:
    name: pull-secret
```

```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: limesurvey
  namespace: limesurvey
spec:
  imageRepositoryRef:
    name: limesurvey
  policy:
    numerical:
      order: asc
```

imageautomation.yaml
```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: limesurvey
  namespace: limesurvey
spec:
  git:
    checkout:
      ref:
        branch: fuero
    commit:
      author:
        email: foo@bar.com
        name: fluxcdbot
      messageTemplate: "{{range .Updated.Images}}{{println .}}{{end}}"
    push:
      branch: fuero
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  update:
    path: ./limesurvey
    strategy: Setters
```

Relevant directory:

```
limesurvey
├── configmap-limesurvey.yaml
├── deployment.yaml
├── imageautomation.yaml
├── imagepolicy.yaml
├── imagerepository.yaml
├── ingress.yaml
├── kustomization.yaml
├── namespace.yaml
├── postgres.yaml
├── pvc.yaml
├── secret.yaml
└── service.yaml
```
kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- imageautomation.yaml
- imagepolicy.yaml
- imagerepository.yaml
- namespace.yaml
- postgres.yaml
- pvc.yaml
- secret-xxx.yaml
- service.yaml
```
