### ISSUE TITLE
Getting 401 using OCI HelmRepository with Azure Container Registry

### ISSUE THREAD

**Issue by ahsanemon** [fluxcd/flux2#2915]
### Describe the bug

I have a MongoDB helm chart on Azure container registry as OCI artifacts. 
I can log in to the repository using 
```
helm registry login my_domain.azurecr.io --username <my-username> --password <my-password>
```
and install the chart using 
```
helm upgrade --install --namespace mongodb mongodb oci://my_domain.azurecr.io/helm/mongodb --version 10.30.3 --values my_values.yaml
```
But with the same credentials, I am getting 401 unauthorized while installing the chart with FluxCD OCI HelmRepository.

My `HelmRepository` and `HelmRelease` Object definition

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mongodb-helm
  namespace: mongodb
spec:
  interval: 2m0s
  url: oci://my_domain.azurecr.io/helm
  type: "oci"
  secretRef:
    name: registry-token
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  targetNamespace: mongodb
  releaseName: mongodb
  interval: 2m
  valuesFrom:
    - kind: ConfigMap
      name: mongodb-values
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: mongodb-helm
      version: '10.30.3'

```

Error message
```
{"level":"error","ts":"2022-07-11T08:50:41.748Z","logger":"controller.helmchart","msg":"Reconciler error","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmChart","name":"mongodb","namespace":"mongodb","error":"chart pull error: chart pull error: failed to get chart version for remote reference: GET \"https://my_domain.azurecr.io/v2/helm/mongodb/tags/list\": unexpected status code 401: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information."}
```

### Steps to reproduce

Try to deploy using the objects mentioned in the description. 

### Expected behavior

Able to log in to Azure container registry and deploy an OCI helm chart.

### OS / Distro

Ubuntu 20.04

### Flux version

flux: v0.31.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.10-eks-84b4fe6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.22.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.26.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.24.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.25.9
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

Azure DevOps

### Container Registry provider

Azure DevOps

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
