### ISSUE TITLE
[build] Multiple patches are ignored in a multi-doc `kustomize.toolkit.fluxcd.io/v1beta2` YAML

### ISSUE THREAD

**Issue by anthr76** [fluxcd/flux2#2938]
### Describe the bug

Similar to https://github.com/fluxcd/flux2/issues/2780 this time with multiple patches with different Kustomizations in a single yaml.

`flux build` in this instance doesn't error but instead ignore the patches when there's more then one in different kustomizations. A single patch set in one kustomization will build correctly otherwise it's ignored.

### Steps to reproduce

This will work:

```yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-namespace
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  patches:
    - patch: |
        - op: add
          path: /spec/values/kubeEtcd/endpoints
          value:
            - 192.168.8.40
      target:
        kind: HelmRelease
        name: kube-prometheus-stack
        namespace: monitoring
  path: "./k8s/base/infra"
  prune: true
---
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  path: "./clusters/test-build"
---
```

This will not work:

```yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-namespace
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  patches:
    - patch: |
        - op: add
          path: /spec/values/kubeEtcd/endpoints
          value:
            - 192.168.8.40
      target:
        kind: HelmRelease
        name: kube-prometheus-stack
        namespace: monitoring
  path: "./k8s/base/infra"
  prune: true
---
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  path: "./clusters/test-build"
  patches:
    - patch: |
        - op: add
          path: /spec/values/kubeEtcd/endpoints
          value: foo
---
````

### Expected behavior

Flux to build different patches of kustomizations in a multi-doc yaml

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
