### ISSUE TITLE
events-addr url in container args generated by the cli has malformed url

### ISSUE THREAD

**Issue by abhilashjoseph** [fluxcd/flux2#2946]
### Describe the bug

Using flux cli to generate and export the manifest for newer versions, has malformed event-addr argument passed onto the containers.

```
apiVersion: apps/v1
kind: Deployment
....
    spec:
      containers:
      - args:
        - --events-addr=http://notification-controller.flux-system.svc.cluster.local./
        - --watch-all-namespaces=true
        - --log-level=info
```
There is a period at the end of the cluster.local url that causes failures to initialize the service.

### Steps to reproduce

1. Install specific flux version `curl -s https://fluxcd.io/install.sh | env FLUX_VERSION=0.31.4 bash`
2. Generate manifests `flux install --version=0.31.4 --export > template-0.31.4.yaml`
3. The generated manifests contains the incorrect event-addr args for all deployments.

### Expected behavior

Url generated for event-addr should not have the period at the end.

### OS / Distro

Ubuntu 20.04

### Flux version

v0.31.4

### Flux check

N/A

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
