### ISSUE TITLE
HelmCharts resources stuck in READY state false after 0.28.0 upgrade

### ISSUE THREAD

**Issue by jhaumont** [fluxcd/flux2#3026]
### Describe the bug

Hello

### Context
After a long migration from `Flux v1` to `Flux v2`, we are currently catching up Flux version from `0.27.1` to `0.32.0` (to be up to date 🚀 ).
And we have to manage the **_source controller api version change_** in `0.28.0` version.

A small disclaimer about our setup: for source controller, we use a PVC to save the resources cache when the pod restart.
Why ? Because in production, we have more than 300 gitrepositories + helmrepositories + 300 helmcharts. Because of this, pod takes a long time to fetch all the artifacts (more than 5 minutes) and finally, this triggers alerts because HelmRelease are in bad status.

### What happened
We have an issue with HelmChart k8s resources when we deploy this specific version: they switch from `READY` state `True` to `False`, and never come back to a stable state. The only solution we have is to delete the HelmChart and do a reconcile on the parent HelmRelease. But, with other resources (gitrepo, helmrepo), we have no issues.

During our investigation, we have decided to destroy the PVC to start source-controller on a fresh one. And the magic happened: `READY` state of HelmCharts switched back to `True`!

So we suspect an issue with the data stored on the PVC for HelmCharts when CRD version changed.

### Steps to reproduce

1. Install flux version 0.27.1 (on kubernetes 1.22.6 for example)
2. Setup a PVC to cache source controller resources data
PVC yaml definition
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flux-source-controller-cache
  namespace: flux-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: pd-ssd-retain
```
Kustomization patch to add the pvc to source controller
```yaml
- op: replace
  path: /spec/template/spec/volumes/0
  value:
    name: data
    persistentVolumeClaim:
      claimName: flux-source-controller-cache
```
3. Create an helmRelease for podinfo app
4. Migrate Flux to 0.28.0 version

### Expected behavior

HelmChart objects on kubernetes should have a READY state to True after 0.28.0 migration.

### OS / Distro

N/A

### Flux version

0.28.0

### Flux check

► checking prerequisites
✗ flux 0.29.0 <0.32.0 (new version is available, please upgrade)
✔ Kubernetes 1.22.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.18.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.21.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.17.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.22.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.22.1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jhaumont** [comment]
Hello @stefanprodan 
Thx for your answer 😃 

We test your solution:

- Upgrade to 0.28
- Upgrade all CRD to v1beta2
- Upgrade to 0.32.0

Sadly, no improvements on helmChart status: they still be in `READY=false` status.

But now, we have error in `source-controller` logs!

Example:
```json
{"level":"info","ts":"2022-08-30T08:29:54.335Z","logger":"controller.helmchart","msg":"artifact up-to-date with remote revision: '2.1.7'","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmChart","name":"ep-sealed-secrets","namespace":"ep","reconcileID":"70415523-9018-4fec-88c2-f99c76281348"}
{"level":"error","ts":"2022-08-30T08:29:54.336Z","logger":"controller.helmchart","msg":"Reconciler error","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmChart","name":"ep-sealed-secrets","namespace":"ep","error":"pulled 'sealed-secrets' chart with version '2.1.7'"}
```

So, like the 1st time, to fix it, we have to delete pvc & pv (to erase cache).

**Comment by darkowlzz** [comment]
Hi, can you share the full status of the HelmChart object? The status should have more information about why it's not ready. You can redact any sensitive information in there before sharing. Ready status will also have reasons for why it's not ready and must be accompanied by some other status conditions that are the actual reasons for the failure, like Reconciling, FetchFailed, Stalled, etc.

**Comment by darkowlzz** [comment]
I tried this myself.

Created a new cluster (K8s v1.24.0) and installed flux v0.28.0 with the PVC patch.
SC deployment event that shows the version (v0.22.1):
```console
[event: pod flux-system/source-controller-5d895589f7-bg8zw] Pulling image "fluxcd/source-controller:v0.22.1"
```
PVC:
```console
$ kubectl get pvc -A
NAMESPACE     NAME                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
flux-system   flux-source-controller-cache   Bound    pvc-a0856a3a-0b50-490f-9ee2-71202ecde400   10Gi       RWO            standard       7m7s
```

Pod description with PVC attached:
```yaml
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  flux-source-controller-cache
    ReadOnly:   false
```
Created HelmRepository and HelmRelease for podinfo.

HelmChart status before upgrade:
```yaml
  conditions:
  - lastTransitionTime: "2022-08-30T22:48:06Z"
    message: pulled 'podinfo' chart with version '4.0.6'
    observedGeneration: 1
    reason: ChartPullSucceeded
    status: "True"
    type: Ready
  observedChartName: podinfo
  observedGeneration: 1
  observedSourceArtifactRevision: 1df61314875caa093830692c7b4f8c6d10cd5f9f5fafa46e926144e5d55ebac2
  url: http://source-controller.flux-system.svc.cluster.local./helmchart/default/default-podinfo/latest.tar.gz
```

Upgraded to flux 0.32.0 (SC 0.26.1) by applying the new install manifest from github release artifacts.

HelmChart status after upgrade:
```yaml
  conditions:
  - lastTransitionTime: "2022-08-30T22:48:06Z"
    message: pulled 'podinfo' chart with version '4.0.6'
    observedGeneration: 1
    reason: ChartPullSucceeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-08-30T22:50:01Z"
    message: pulled 'podinfo' chart with version '4.0.6'
    observedGeneration: 1
    reason: ChartPullSucceeded
    status: "True"
    type: ArtifactInStorage
  observedChartName: podinfo
  observedGeneration: 1
  observedSourceArtifactRevision: 1df61314875caa093830692c7b4f8c6d10cd5f9f5fafa46e926144e5d55ebac2
  url: http://source-controller.flux-system.svc.cluster.local./helmchart/default/default-podinfo/latest.tar.gz
```

Since we added new conditions after SC 0.22.1, there's new condition in the status but everything seems to be fine.

Flux 0.28.0 had the new source-controller which would contain helpful information about the reasons for failure. If the HelmChart isn't ready, the status will have more information about why it's not ready.

Maybe something is missing in the steps to reproduce other than the k8s version.
