### ISSUE TITLE
AKS Fluxv2 - Can't download helmchart from private HelmRepository

### ISSUE THREAD

**Issue by p9139010** [fluxcd/flux2#3031]
### Describe the bug

Hi,

we are testing GitOps on AKS through Flux-V2 & facing issue while downloading the helmchart into Source controller of Flux. 

### Environment:
AKS cluster 1.23
Flux azure-k8s-flux-1.5.1 

Have configured **HELMREPOSITORY** in GitHub based on [https://harness.io/blog/helm-chart-repo] documentation. We are able to install the package through normal helm commands but not through Flux-V2.

Have configured kustomization for Helmrepository & Helmrelease as well. And used basic authentication for HelmRepository.

HelmRepository is able to download the index.yaml file but not the actual package from HelmRelease operation. Getting page 404 not found. Authentication is not referred/honoured by HelmRelease.

Requesting assistance.

---
Secret.yaml:
apiVersion: v1
kind: Secret
metadata:
  name: helmrepo-secret-xxxx
  namespace: xxxx
type: kubernetes.io/basic-auth
stringData:
  username: 
  password: 

----
HelmRepository:
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: xxxx-helmrepo
  namespace: xxxx
spec:
  interval: 1m0s
  url: https://<org>.github.io/helmchart-gitops/
  secretRef:
    name: helmrepo-secret-xxxx

----
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: xxxx-aks
  namespace: xxxx
spec:
  releaseName: xxxx-aks
  serviceAccountName: flux-applier
  interval: 1m
  install:
    remediation:
     retries: 3
  chart:
    spec:
      chart: xxxx-aks
      sourceRef:
        kind: HelmRepository
        name: xxxx-helmrepo
        namespace: xxxx
      interval: 1m
      version: "0.1.0"
  values:
    image:
      registry: testacrxxxx.azurecr.io
      pullPolicy: Always
    imagePullSecrets:
      name: xxxxcred-test

### Steps to reproduce

As per the above manifest file configured the GitOps for AKS. Not able to authenticate to HelmRepository using the provided secrets file (basic/auth).

### Expected behavior

1. Uploaded public charts into Private HelmRepository (of Github)
2. Referred secrets as basic auth for https connection to repository
3. Able to download the index.yaml (for HelmRepository - Kustomization)
4. Not able to download the actual package from HelmRepository through HelmRelease action of kustomization.

### OS / Distro

Ubuntu 18.04.6 LTS / AKS - 1.23.5

### Flux version

azure-k8s-flux-1.5.1

### Flux check

CONTAINER                     IMAGE
fluxconfig-agent,fluent-bit   mcr.microsoft.com/azurek8sflux/fluxconfig-agent:1.5.1,mcr.microsoft.com/azurek8sflux/fluent-bit:1.5.1
manager,fluent-bit            mcr.microsoft.com/azurek8sflux/fluxconfig-controller:1.5.1,mcr.microsoft.com/azurek8sflux/fluent-bit:1.5.1
manager                       mcr.microsoft.com/oss/fluxcd/helm-controller:v0.22.1
manager                       mcr.microsoft.com/oss/fluxcd/kustomize-controller:v0.26.1
manager                       mcr.microsoft.com/oss/fluxcd/notification-controller:v0.24.0
manager                       mcr.microsoft.com/oss/fluxcd/source-controller:v0.25.8

### Git provider

Github (Enterprise)

### Container Registry provider

Github HelmRepository Package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
I'm not familiar to Github Enterprise, my guess is that the domain for the chart file is different to the index one and Flux rejects it. I highly recommend using GitHub container registry to store the charts instead of GitHub Pages. Once you have the charts published to GHCR, you can setup Flux to download them using a GH PAT.

Helm OCI Example:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ghcr-charts
  namespace: test
spec:
  interval: 10m
  type: oci
  url: oci://ghcr.io/org/charts
  secretRef:
    name: ghcr-auth
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-app
  namespace: test
spec:
  interval: 10m
  chart:
    spec:
      chart: my-app
      sourceRef:
        kind: HelmRepository
        name: ghcr-charts
```

The secret can be generated with:
```sh
flux -n test create secret oci ghcr-auth \
  --url=ghcr.io \
  --username=flux \
  --password=${GITHUB_PAT}
```
