### ISSUE TITLE
Git implementation changes from libgit2 to go-git and source is not ready

### ISSUE THREAD

**Issue by oeffel** [fluxcd/flux2#3062]
### Describe the bug

I have the following resource:

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: fleet-infra
  namespace: flux-system
spec:
  gitImplementation: libgit2
  interval: 0m30s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@ssh.dev.azure.com/v3/...
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: secrets
  namespace: flux-system
spec:
  gitImplementation: libgit2
  interval: 0m30s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@ssh.dev.azure.com/v3/...
```

And when I apply them to the cluster, it successfully clones the repository, but then I get the following logs:

```
2022-08-31T10:59:07.953Z info GitRepository/fleet-infra.flux-system - stored artifact for commit 'asdf'
2022-08-31T10:59:08.043Z info GitRepository/secrets.flux-system - stored artifact for commit 'Rotating credentials: machine user'
2022-08-31T10:59:08.404Z error GitRepository/fleet-infra.flux-system - failed to configure auth strategy for Git implementation 'go-git': invalid 'ssh' auth option: 'identity' is required
 failed to configure auth strategy for Git implementation 'go-git': invalid 'ssh' auth option: 'identity' is required
2022-08-31T10:59:08.408Z error GitRepository/secrets.flux-system - failed to configure auth strategy for Git implementation 'go-git': invalid 'ssh' auth option: 'identity' is required fai
led to configure auth strategy for Git implementation 'go-git': invalid 'ssh' auth option: 'identity' is required
```

And I get the following:

```
oeffel/flux-system [main●] » flux get source all
NAME                            REVISION                                        SUSPENDED       READY   MESSAGE

gitrepository/fleet-infra       main/0b97fbeb253aa0550c85e401a0f8cbad2621141d   False           False   failed to configure auth strategy for Git implementation 'go-git': invalid 'ssh' auth option: 'identity' is required
gitrepository/secrets           main/157e1b4e69c7e4f28261f8c56cd16849cd6b9894   False           False   failed to configure auth strategy for Git implementation 'go-git': invalid 'ssh' auth option: 'identity' is required
```

The git implementation seems to have changed on its own from libgit2 to go-git, and my sources are not ready -- they appear to be in an error state.

### Steps to reproduce

Install flux, apply the secret that is needed for the machine user to read from the Azure Repos, and then apply the GitRepository resources.

### Expected behavior

The sources are ready and able to pull from the repository without error.

### OS / Distro

N/A

### Flux version

0.33.0

### Flux check

```
oeffel/flux-system [main●] » flux check
► checking prerequisites
✔ Kubernetes 1.24.1 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.22.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.27.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.25.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.26.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
