### ISSUE TITLE
Duplicate slack error notifications being fired

### ISSUE THREAD

**Issue by jprecuch** [fluxcd/flux2#3072]
### Describe the bug

We've noticed on our Slack channel that each error notification is doubled. Everything works properly for info notifications (no doubles). However when there is an error we can see the error notification is fired twice for the same namespace.
For example:
```
helmrelease/kube-prometheus.monitoring
reconciliation failed: Operation cannot be fulfilled on [helmreleases.helm.toolkit.fluxcd.io](http://helmreleases.helm.toolkit.fluxcd.io/) "kube-prometheus": the object has been modified; please apply your changes to the latest version and try again
revision
2022.9.0-DEV16
[14:16]
helmrelease/kube-prometheus.monitoring
reconciliation failed: Operation cannot be fulfilled on [helmreleases.helm.toolkit.fluxcd.io](http://helmreleases.helm.toolkit.fluxcd.io/) "kube-prometheus": the object has been modified; please apply your changes to the latest version and try again
revision
2022.9.0-DEV16
```
Are we doing something wrong?
Our notification configuration is as following:

monitoring namespace:
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: monitoring-error
  namespace: flux-system
spec:
  providerRef:
    name: slack-provider
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: 'monitoring'   
    - kind: HelmRepository
      name: '*'
      namespace: 'monitoring'
    - kind: HelmRelease
      name: '*'
      namespace: 'monitoring'
    - kind: HelmChart
      name: '*'
      namespace: 'monitoring'
```
flux-system
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: flux-system-error
  namespace: flux-system
spec:
  providerRef:
    name: slack-provider
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: 'flux-system'   
    - kind: HelmRepository
      name: '*'
      namespace: 'flux-system'
    - kind: HelmRelease
      name: '*'
      namespace: 'flux-system'
    - kind: HelmChart
      name: '*'
      namespace: 'flux-system'
```
sde namespace
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: sde-error
  namespace: flux-system
spec:
  providerRef:
    name: slack-provider
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: 'sde'
    - kind: HelmRepository
      name: '*'
      namespace: 'sde'
    - kind: HelmRelease
      name: '*'
      namespace: 'sde'
    - kind: HelmChart
      name: '*'
      namespace: 'sde'
```
### Steps to reproduce

1. Install latest Flux
2. Configure notifications to be based on description
3. Fail some helmrelease

### Expected behavior

Notification should fire just once

### Screenshots and recordings
Failed release error:
![Slack_2022-09-05](https://user-images.githubusercontent.com/16647499/188398851-b9fda699-8577-40c3-aa0a-23a6497547f9.jpg)
Missing chart error:
![Slack_2022-09-05_09-53-27](https://user-images.githubusercontent.com/16647499/188397624-983a0288-d49f-4b3a-9940-cdf432cd7fa5.jpg)

### OS / Distro

GKE

### Flux version

v0.32.0

### Flux check

► checking prerequisites
✗ flux 0.32.0 <0.33.0 (new version is available, please upgrade)
✔ Kubernetes 1.24.2-gke.1900 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.22.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.27.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.25.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.26.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by snebel29** [comment]
I think this issue belong to https://github.com/fluxcd/notification-controller, I wouldn't mind taking a look if this is ok for maintainers of this organisation...

**Comment by somtochiama** [comment]
@jprecuch This might be due to the helm/source controller requeuing immediately on an error, hitting the error again and firing the same event off to the notification-controller

**Comment by stefanprodan** [comment]
@somtochiama this should happen unless rate limiting is broken in NC

**Comment by somtochiama** [comment]
I will look into it

**Comment by somtochiama** [comment]
@jprecuch Can you crosscheck that you don't have more than one alert defined for the same provider and event sources?
The event is sent to each alert, so if you have two alerts referencing the same provider, it would be sent twice.

**Comment by stefanprodan** [comment]
I've tested this on my cluster and I'm not getting any duplicates. My guess is that multiple Alerts have the same `eventSources`. One way to find out, would be to add a  unique `summary` to each Alert, then in Slack you'll see where the duplicates come from.

**Comment by jprecuch** [comment]
Thanks @somtochiama @stefanprodan .
For each namespace we deploy we have following eventSources and provider:
```
  providerRef:
    name: slack-provider
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: 'monitoring'
    - kind: HelmRepository
      name: '*'
      namespace: 'monitoring'
    - kind: HelmRelease
      name: '*'
      namespace: 'monitoring'
    - kind: HelmChart
      name: '*'
      namespace: 'monitoring'
```
We have same for flux-system namespace. Would that duplicate alerts somehow? The info alerts are not duplicated, only error ones.

**Comment by stefanprodan** [comment]
@jprecuch see my last comment https://github.com/fluxcd/flux2/issues/3072#issuecomment-1239301117 on how to debug this

**Comment by jprecuch** [comment]
Thanks @stefanprodan.
Ive did add this today and can see that info alerts fire also error alerts in our case. Any ideas why?
![alerts1](https://user-images.githubusercontent.com/16647499/189607735-2e8a3896-97b5-4f7a-9d76-b5b3bdf15418.jpg)

Configuration of info+error alerts are following:
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: cbs-error
  namespace: flux-system
spec:
  summary: "CBS namespace error alerts"
  providerRef:
    name: slack-provider
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: 'cbs'   
    - kind: HelmRepository
      name: '*'
      namespace: 'cbs'
    - kind: HelmRelease
      name: '*'
      namespace: 'cbs'
    - kind: HelmChart
      name: '*'
      namespace: 'cbs'
```
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: cbs-info
  namespace: flux-system
spec:
  summary: "CBS namespace info alerts"
  providerRef:
    name: slack-provider
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: 'cbs'
    - kind: HelmRelease
      name: '*'
      namespace: 'cbs'
    - kind: HelmChart
      name: '*'
      namespace: 'cbs'
  exclusionList:
    - "HelmChart.*is not ready"
    - "dependency.*is not ready"
```
