### ISSUE TITLE
Error: failed to decode Kubernetes YAML did not find expected key

### ISSUE THREAD

**Issue by Dotisandhyarani** [fluxcd/flux2#3094]
How do we deploy the helm templates ( yaml file with `{{ }}` ) values in EKS with flux
I have tried with hardcoded values instead of `{{ }}` and can deploy successfully.

**Example: ConfigMap.yaml**
```

apiVersion: v1
kind: ConfigMap
metadata:
name: {{ include “sample-api.fullname” . | indent 2 }}-env
{{- with .Values.envVariables }}
data:
{{- toYaml . | nindent 2 }}
{{- end }}
```

my sample-api/templates folder has **Kustomization.yaml**
```

apiVersion: [kustomize.config.k8s.io/v1beta1](http://kustomize.config.k8s.io/v1beta1)
kind: Kustomization
resources:
-configmap.yml
```

I have my helm repository added to flux , here is the configuration file
```

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fleet-helm
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./charts/src/analytics/sample-api/templates
  prune: true
  sourceRef:
    kind: GitRepository
    name: fleet-helm
```
I set `path: ./charts/src/analytics/sample-api/templates` to templates dir where I have yaml files with {{ }}. Throws below error when I check with `flux get all`

```
False False failed to decode Kubernetes YAML from /tmp/kustomization-2772309989/charts/src/analytics/analytics-api/templates/sample-api.yaml: MalformedYAMLError: yaml: line 3: did not find expected key.
```

Any help please?
