### ISSUE TITLE
Kustomize intermittent errors with ExternalSecret

### ISSUE THREAD

**Issue by midestefanis** [fluxcd/flux2#3099]
### Describe the bug

ESO version: 0.5.9

Error:

```
ExternalSecret/monitoring/.. dry-run failed, error: failed to prune fields: failed add back owned items: failed to convert pruned object at version external-secrets.io/v1alpha1: conversion webhook for external-secrets.io/v1beta1, Kind=ExternalSecret returned invalid metadata: invalid metadata of type <nil> in input object Namespace/monitoring configured
```

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: ...
  namespace: monitoring
spec:
  data:
    - remoteRef:
        key: ...
      secretKey: license
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore-secrets-manager
  target:
    name: ...
```

### Steps to reproduce

1. Install flux with
2. Install External Secrtet Operator with components
3. Install ExternalSecret
4. The Kustomization that syncs the secrets starts throwing that error
5. After a few minutes, it reconciles well and the error does not appear, then when it reconciles again it fails and so on...

### Expected behavior

That reconciles always well

### OS / Distro

macOS Monterrey 12.4

### Flux version

v0.33.0

### Flux check

```
► checking prerequisites
✗ flux 0.33.0 <0.34.0 (new version is available, please upgrade)
✔ Kubernetes 1.21.14-eks-18ef993 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.23.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.27.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.25.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.28.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed
```

### Git provider

GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
