### ISSUE TITLE
EKS Fargate - Flux Controllers Can't Boot

### ISSUE THREAD

**Issue by pusherman** [fluxcd/flux2#3138]
### Describe the bug

**This is not a bug in Flux**-- this is a recent "bug" (or change) in EKS Fargate.  Let me know if this should be moved to the discussion thread and I will happily do so.  I'm putting it here because I almost submitted a bug in Flux.. so hopefully this will help someone else.

We run Flux in EKS Fargate.  We just recently I noticed our flux controllers were in a CrashLoopBackoff state.  Describing the crashed pod would give the error 

> OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: failed to write "100000": write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod1c7b880e-6be8-48d3-9565 f7378d3c391e/04389a3f1e9bb589e8a4c2e8783df9646fe7273ab6972478364516774ae6190b/cpu.cfs_quota_us: invalid argument: unknown

After working with AWS support, they said there was an open issue with Fargate that would cause pods to not be able to start if their resource requests and limits were not the same value.  They did not give an ETA on when the fix would be deployed or if it would be.

I was able to work around the issue with the following modification to the `kustomization.yaml` that the `gotk-components.yaml` was deployed from.

```
patches:
  - target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "0.25"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "0.25"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256M
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256M
```

### Steps to reproduce

1. Use AWS EKS Fargate for your flux controllers
2. Deploy Flux
3. See pods in `flux-system` in a CrashLoopBackoff

### Expected behavior

Pods to deploy fine in EKS Fargate

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
