### ISSUE TITLE
Using secretKeyRef in HelmRelease dosent working

### ISSUE THREAD

**Issue by guyalo** [fluxcd/flux2#3151]
### Describe the bug

Hi, trying to use secretKeyRef in the HelmRelease values section but doesn't evaluate the secretKeyRef but uses the literal object.

flux2 version: flux version 0.31.1
environment:: GKE

yaml:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
spec:
  releaseName: rabbitmq
  chart:
    spec:
      chart: rabbitmq
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    service:
      type: LoadBalancer
    auth:
      password:
        valueFrom:
          secretKeyRef:
            name: rabbitmq-password
            key: value
```

For checking the secret that created by the rabbitmq chart running :

    `kubectl get secret rabbitmq -n stage -o go-template='{{range $k,$v := .data}}{{printf "%s: " $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{"\n"}}{{end}}'`

result is:

    `rabbitmq-password: map[valueFrom:map[secretKeyRef:map[key:value name:rabbitmq-password]]]`

the secret was not evaluated

### Steps to reproduce

1. add any helm-chart source.
2. add a secret to the Kubernetes cluster.
3. reference the secret from the HelmRelease YAML.
4. check the secret created by the helm.was 

### Expected behavior

The secret should evaluated by the HelmRelease 

### OS / Distro

Ubuntu 20.4

### Flux version

v0.31.1

### Flux check

✔ Kubernetes 1.22.12-gke.500 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.22.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.19.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.26.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.24.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.25.8
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
