### ISSUE TITLE
Migrating Ingress apiVersion results in 

### ISSUE THREAD

**Issue by jpiper** [fluxcd/flux2#3202]
### Describe the bug

We have a manifest in git that is using the legacy ingress kind in`apiVersion: extensions/v1beta1` on a k8s cluster running 1.20

When we committed a change to upgrade this to the new ingress kind in`networking.k8s.io/v1` the old ingress was garbage collected, and the new ingress was never created, resulting is no ingress in the cluster. The deployment timed out

```
12m         Warning   HealthCheckFailed         kustomization/test      Health check failed after 5m0.005924542s, timeout waiting for: [Ingress/test/test status: 'NotFound'
```

I assume what's happening is that as the apiVersion is upgraded automatically by the APIserver is that flux is applying the new manifest and then garbage collecting it straight away.

The fix was to revert, and then set `prune: disabled` on the ingress before upgrading.

### Steps to reproduce

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  namespace: test
spec:
  rules:
  - host: test.example.com
    http:
      paths:
      - backend:
          serviceName: test
          servicePort: 6776
```
now check in
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  namespace: test
spec:
  rules:
  - host: test.example.com
    http:
      paths:
      - backend:
          service:
            name: test
            port:
              number: 6776
        pathType: ImplementationSpecific
```

### Expected behavior

the new ingress resources to be created

### OS / Distro

N/A

### Flux version

flux: v0.35.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.20.11 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► docker-upstream.apple.com/fluxcd/helm-controller:v0.25.0
✔ kustomize-controller: deployment ready
► docker-upstream.apple.com/fluxcd/kustomize-controller:v0.29.0
✔ notification-controller: deployment ready
► docker-upstream.apple.com/fluxcd/notification-controller:v0.27.0
✔ source-controller: deployment ready
► docker-upstream.apple.com/fluxcd/source-controller:v0.30.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
