### ISSUE TITLE
Cannot overwrite pruning

### ISSUE THREAD

**Issue by ldimitrov** [fluxcd/flux2#3226]
### Describe the bug

I have a setup where I want to have prune set to `false` by default and then overwrite the value and set it for a particular Kustomization to `true`. In other words, I want Flux to perform pruning on one namespace only, but have it false on all other namespaces. But somehow that does not seem to work.

I have the following structure:
```
.
|-- clusters
|   `-- test-cluster
|       `-- flux-system
|           |-- base.yaml
|           |-- gotk-components.yaml
|           |-- gotk-sync.yaml
|           |-- kustomization.yaml
|           |-- overlays
|           |   |-- gotk-patches.yaml
|           |   `-- helm-controller-patches.yaml
|           |-- rbac.yaml
|           `-- tenants.yaml
|-- tenants
|   `-- test
|       |-- feature-namespace
|       |   |-- ..
|       |   |-- sync-apps.yaml
|       |   `-- ..
```
So, my `./clusters/test-cluster/tenants.yaml` looks like this: 

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/test
  prune: false

```

As you can see, I have here `prune: false` as I'd like this to be the default behaviour (and this is at my highest level)

Then in my `./tenants/test/feature-namespace/sync-apps.yaml` Kustomization:

```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: feature-apps
  namespace: feature-namespace
spec:
  interval: 1m0s
  path: ./apps
  prune: true
  serviceAccountName: feature-namespace-tenant
  sourceRef:
    kind: GitRepository
    name: git-repo
    namespace: shared
  targetNamespace: feature-namespace

```
And now here in this Kustomization, I have `prune: true`. 

But when I delete an app from my repo, the HelmRelease does not get removed.

### Steps to reproduce

1. set `prune: false` in top Kustomization
2. set `prune: true` to a lower level Kustomization
3. Delete app from git repo
4. App is still there and does not get removed.

### Expected behavior

1. set `prune: false` in top Kustomization
2. set `prune: true` to a lower level Kustomization
3. Delete app from git repo
4. App is removed from cluster.

### OS / Distro

macOS

### Flux version

flux: v0.34.0

### Flux check

► checking prerequisites
✗ flux 0.30.2 <0.35.0 (new version is available, please upgrade)
✔ Kubernetes 1.23.10-eks-15b7512 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.21.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.5
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.4
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta1
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta1
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

BitBucket

### Container Registry provider

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
