### ISSUE TITLE
Image Policy Cannot determine the latest tag

### ISSUE THREAD

**Issue by AVASamsundar** [fluxcd/flux2#3244]
### Describe the bug

I am trying to reconcile the latest image from the ecr repository which is private. I can able to create image repository and it provides a image tags that are available.

PS C:\xx\xxx\xxxx\xxxx> flux get image repository
NAME                            LAST SCAN               SUSPENDED       READY   MESSAGE
xxxx                                2022-10-22T18:13:06Z    False           True    successful scan, found 3 tags

But when I add a ImagePolicy which is bounded to the image repository object. I am getting the following Issue.

PS C:\xx\xxx\xxxx\xxxx> flux get image policy
NAME  LATEST IMAGE    READY   MESSAGE
xxxx                                 False   Cannot determine latest tag for policy: unable to determine latest version from provided list.

### Steps to reproduce

Install Flux version 2.

> curl -s https://fluxcd.io/install.sh | sudo bash

Flux Bootstrap a github repository. which contains the kubernetes manifest, Image-repository with Secret of the Image registry, Image-policy by using following commands.

> flux create image repository abc --image=xxxx.dkr.ecr.us-east-1.amazonaws.com/abc --interval=1m --export > xxx-image-repository.yaml

> flux create image policy abcd --image-ref=abc --select-semver=1.0.x --export >  xxx-image-policy.yaml

flux get image repository - To validate is the image repository can be accessed.
flux get image policy - Flux cannot able to determine the latest image in the registry.

### Expected behavior

The Image Policy should provide the latest image that is present in the docker image registry.

$ flux get image policy flux-system
NAME            READY   MESSAGE                                                                 LATEST IMAGE
my-app-policy   True    Latest image tag for 'ghcr.io/stefanprodan/podinfo' resolved to: 5.1.4  ghcr.io/stefanprodan/podinfo:5.1.4

### OS / Distro

Linux

### Flux version

flux: v0.35.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.23.10-eks-15b7512 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.25.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.26.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.22.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.29.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.27.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.30.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

Github

### Container Registry provider

ecr

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by AVASamsundar** [comment]
Please find the Image repository yaml below.

> ---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: abc
  namespace: flux-system
spec:
  image: xxxx.dkr.ecr.us-east-1.amazonaws.com/abc
  interval: 1m0s
  secretRef:
    name: image-registry-secret

Please find the Image Policy yaml below.

> ---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: abcd
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: abc
  policy:
    semver:
      range: '1.0.x'

**Comment by chrisjohnson00** [comment]
Docs don't include `1.0.x` as an example, here's what I use for my image policy

```
  policy:
    semver:
      range: '>1.0.0-rc <2.0.0-rc'
```
You could adjust it to match just patch versions `>1.0.0 < 1.1.0`

**Comment by AVASamsundar** [comment]
> Docs don't include `1.0.x` as an example, here's what I use for my image policy
> 
> ```
>   policy:
>     semver:
>       range: '>1.0.0-rc <2.0.0-rc'
> ```
> 
> You could adjust it to match just patch versions `>1.0.0 <1.1.0`

Thanks Chris. Let me check.

**Comment by AVASamsundar** [comment]
FYI!
My Image tagging is $ECR_REGISTRY/$ECR_REPOSITORY:${{env.BRANCH_NAME}}-${{ app.version }}-${GITHUB_RUN_NUMBER}-${{env.COMMIT_ID}}

How should my policy be for this tagging

**Comment by AVASamsundar** [comment]
No @chrisjohnson00 I am still getting the same issue

**Comment by chrisjohnson00** [comment]
I wish there was a way to list the 3 found images

**Comment by chrisjohnson00** [comment]
> FYI!
> My Image tagging is $ECR_REGISTRY/$ECR_REPOSITORY:${{env.BRANCH_NAME}}-${{ app.version }}-${GITHUB_RUN_NUMBER}-${{env.COMMIT_ID}}
> 
> How should my policy be for this tagging

I'm on my phone, but I do this pattern also. It's alpha with regex you want.

Something like

'branch\-v\d{1,}\.\d{1,}\.\d{1,}\-\d{1,}\-.'

I would remove the commit ID from it because the GitHub Runner numbers are unique.

Are you using a unique ID for the GitHub Runner or is that the workflow id?

**Comment by AVASamsundar** [comment]
It is the workflow ID Chris.

**Comment by AVASamsundar** [comment]
> > FYI!
> > My Image tagging is ECRREGISTRY/{{env.BRANCH_NAME}}-${{ app.version }}-${GITHUB_RUN_NUMBER}-${{env.COMMIT_ID}}
> > How should my policy be for this tagging
> 
> I'm on my phone, but I do a similar pattern also. It's alpha with regex you want.
> 
> Something like
> 
> 'branch-v\d{1,}.\d{1,}.\d{1,}-\d{1,}-.'
> 
> I would remove the commit ID from it because the GitHub Runner numbers are unique.
> 
> Are you using a unique ID for the GitHub Runner or is that the workflow id?
> 
> I'd remove the commit Id, since the github workflow id is enough to keep it unique and makes the regex simpler

Will it work with this policy if I remove my Commit ID

**Comment by AVASamsundar** [comment]
Team I've used the filter tags with the branching strategy at the end. It works Perfectly Now.

**Comment by mhassaankhokhar** [comment]
Hello, I am facing the same issue but in my case I am using docker hub. Further, There is an issue with tagging the image.  
Image registry code,
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: frontend
  namespace: flux-system
spec:
  image: mhassaankhokhar/lm-frontend
  interval: 1m0s
```
The image policy that I am using is, 
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: frontend-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frontend
  policy:
    semver:
      range: '>=0.x'
```
And the deployment that I am using, 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lm-frontend
  namespace: linkedmatrix
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.lm-frontend: glob:master-*
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: lm-frontend
  template:
    metadata:
      labels:
        app: lm-frontend
    spec:
      containers:
      - name: lm-frontend
        image: mhassaankhokhar/lm-frontend:master-0.1  # {"$imagepolicy": "default:frontend-policy"}
        ports:
        - containerPort: 80
```
