### ISSUE TITLE
Add TimeZone support in flux controllers 

### ISSUE THREAD

**Issue by mfilotto** [fluxcd/flux2#3263]
### Describe the bug

I tried to set TZ var env with my timezone (Pacific/Noumea) in all flux controllers with no luck  

### Steps to reproduce

1. Modify flux kustomization file to inject TZ var env

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  # target all controllers to add TZ var env
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: TZ
          value: "Pacific/Noumea"
    target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/part-of=flux"
```
2. Then read the logs of the new pods to see if timezone has changed

### Expected behavior

Flux controllers should log with the expected timezone

### OS / Distro

CentOS 7.9

### Flux version

v0.36.0

### Flux check

flux check
► checking prerequisites
✔ Kubernetes 1.24.7 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.26.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.30.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.28.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.31.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
