### ISSUE TITLE
flux diff fails if the namespace does not exist

### ISSUE THREAD

**Issue by ilijamt** [fluxcd/flux2#3270]
### Describe the bug

If a namespace does not exist the diff fails with the resources complaining that the namespace does not exist.

I've tried this on k8s 1.22, and 1.24 with same result.

### Steps to reproduce

Create the following files 

```
efs-csi-driver
├── helmrelease-efs-csi-driver.yaml
├── helmrepository-efs-csi-driver.yaml
├── kustomization.yaml
└── namespace.yaml
```

```yaml
# helmrelease-efs-csi-driver.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-efs-csi-driver
  namespace: efs-csi-driver
spec:
  releaseName: aws-efs-csi-driver
  interval: 1m
  chart:
    spec:
      chart: aws-efs-csi-driver
      version: 2.2.9
      sourceRef:
        kind: HelmRepository
        name: aws-efs-csi-driver
# helmrepository-efs-csi-driver.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aws-efs-csi-driver
  namespace: efs-csi-driver
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/aws-efs-csi-driver/
# kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository-efs-csi-driver.yaml
  - helmrelease-efs-csi-driver.yaml
# namespace.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: efs-csi-driver
```

Then running 

```shell
$ flux diff kustomization flux-system --path efs-csi-driver
✓  Kustomization diffing...
► Namespace/efs-csi-driver created
✗ 2 errors occurred:
	* HelmRepository/efs-csi-driver/aws-efs-csi-driver namespace not specified, error: namespaces "efs-csi-driver" not found
	* HelmRelease/efs-csi-driver/aws-efs-csi-driver namespace not specified, error: namespaces "efs-csi-driver" not found
```

### Expected behavior

I expected to show the resources that would be created 

```shell
$ flux diff kustomization flux-system --path efs-csi-driver
✓  Kustomization diffing...
► Namespace/efs-csi-driver created
► HelmRepository/efs-csi-driver/aws-efs-csi-driver created
► HelmRelease/efs-csi-driver/aws-efs-csi-driver created
```

### OS / Distro

Linux x1c 5.19.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1 (2022-09-24) x86_64 GNU/Linux

### Flux version

0.35.0 and 0.36.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.2 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.26.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.30.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.28.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.31.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
