### ISSUE TITLE
provider a aliyun bucket provider

### ISSUE THREAD

**Issue by 13567436138** [fluxcd/flux2#3287]
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: Bucket
metadata:
  name: aliyun
spec:
  interval: 1m
  bucketName: fluxcd
  endpoint: oss-cn-hangzhou.aliyuncs.com
  secretRef:
    name: aliyun-bucket
  region: 华东1
```

this config got error:
![lQLPJxbY167bUqnNAZ7NBlWwBIKDrhPQSAcDZFdQ8MBLAA_1621_414 png_720x720q90g](https://user-images.githubusercontent.com/31508490/200152143-d3e967b2-6588-4e92-8f28-6076effa6519.jpg)
