### ISSUE TITLE
patchesStrategicMerge error ,file can not found

### ISSUE THREAD

**Issue by 13567436138** [fluxcd/flux2#3290]
### Describe the bug

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: GitRepository
        name: mygit
        namespace: flux-system
  interval: 1m
  values:
    image:
      registry: registry.cn-hangzhou.aliyuncs.com
      repository: hxpapp/nginx
      tag: 1.23.2-debian-11-r2
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - ./increase_replicas.yaml
```

```
Events:
  Type     Reason  Age              From             Message
  ----     ------  ----             ----             -------
  Normal   info    10s              helm-controller  HelmChart 'flux-system/helm-nginx' is not ready
  Normal   info    3s (x4 over 9s)  helm-controller  Helm install has started
  Warning  error   3s (x4 over 9s)  helm-controller  Helm install failed: error while running post render on files: trouble configuring builtin PatchStrategicMergeTransformer with config: `
paths:
- '"./increase_replicas.yaml"'
`: '/"./increase_replicas.yaml"' doesn't exist

Last Helm logs:
  Warning  error  3s (x4 over 9s)  helm-controller  reconciliation failed: Helm install failed: error while running post render on files: trouble configuring builtin PatchStrategicMergeTransformer with config: `
paths:
- '"./increase_replicas.yaml"'
`: '/"./increase_replicas.yaml"' doesn't exist
```

### Steps to reproduce

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: GitRepository
        name: mygit
        namespace: flux-system
  interval: 1m
  values:
    image:
      registry: registry.cn-hangzhou.aliyuncs.com
      repository: hxpapp/nginx
      tag: 1.23.2-debian-11-r2
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - ./increase_replicas.yaml
```

```
Events:
  Type     Reason  Age              From             Message
  ----     ------  ----             ----             -------
  Normal   info    10s              helm-controller  HelmChart 'flux-system/helm-nginx' is not ready
  Normal   info    3s (x4 over 9s)  helm-controller  Helm install has started
  Warning  error   3s (x4 over 9s)  helm-controller  Helm install failed: error while running post render on files: trouble configuring builtin PatchStrategicMergeTransformer with config: `
paths:
- '"./increase_replicas.yaml"'
`: '/"./increase_replicas.yaml"' doesn't exist

Last Helm logs:
  Warning  error  3s (x4 over 9s)  helm-controller  reconciliation failed: Helm install failed: error while running post render on files: trouble configuring builtin PatchStrategicMergeTransformer with config: `
paths:
- '"./increase_replicas.yaml"'
`: '/"./increase_replicas.yaml"' doesn't exist
```

### Expected behavior

no error

### OS / Distro

centos 8

### Flux version

v0.22.0

### Flux check

[root@node01 fluxcd]# flux check
► checking prerequisites
✔ Kubernetes 1.21.0 >=1.20.6-0
► checking controllers
✗ no controllers found in the 'flux-system' namespace with the label selector 'app.kubernetes.io/part-of=flux'
► checking crds
✗ no crds found with the label selector 'app.kubernetes.io/part-of=flux'
✗ check failed

my flux was installed by kubevela

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Only in-line patches are supported, here is an examaple https://fluxcd.io/flux/components/helm/helmreleases/#post-renderers

**Comment by 13567436138** [comment]
```
Events:
  Type     Reason  Age               From             Message
  ----     ------  ----              ----             -------
  Normal   info    13s               helm-controller  HelmChart 'flux-system/helm-nginx' is not ready
  Normal   info    0s (x5 over 12s)  helm-controller  Helm install has started
  Warning  error   0s (x5 over 12s)  helm-controller  Helm install failed: error while running post render on files: no matches for Id Deployment.v1.apps/nginx.[noNs]; failed to find unique target for patch Deployment.v1.apps/nginx.[noNs]

Last Helm logs:
  Warning  error  0s (x5 over 12s)  helm-controller  reconciliation failed: Helm install failed: error while running post render on files: no matches for Id Deployment.v1.apps/nginx.[noNs]; failed to find unique target for patch Deployment.v1.apps/nginx.[noNs]
```

**Comment by 13567436138** [comment]
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: GitRepository
        name: mygit
        namespace: flux-system
  interval: 1m
  values:
    image:
      registry: registry.cn-hangzhou.aliyuncs.com
      repository: hxpapp/nginx
      tag: 1.23.2-debian-11-r2
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx
        spec:
          replicas: 3
```

**Comment by stefanprodan** [comment]
> failed to find unique target for patch Deployment.v1.apps/nginx

Do `helm template` to see the actual deployment name, it's not nginx.

**Comment by 13567436138** [comment]
it is niginx
```
[root@node01 helmRelease]# kubectl apply -f helmRelease-rollback-disableHooks.yaml -n helm
helmrelease.helm.toolkit.fluxcd.io/nginx configured
[root@node01 helmRelease]# kubectl get deploy -n helm
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   0/1     1            0           9s
```
use flowing yaml
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: GitRepository
        name: mygit
        namespace: flux-system
  interval: 1m
  rollback:
    disableHooks: true
```
