### ISSUE TITLE
Kustomization images newName is not effective

### ISSUE THREAD

**Issue by 13567436138** [fluxcd/flux2#3295]
### Describe the bug

Kustomization images newName is not effective

```
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  12s   default-scheduler  Successfully assigned podinfo/podinfo-5c55d695d7-vx8jp to 192.168.229.133
  Normal  Pulled     11s   kubelet            Container image "registry.cn-hangzhou.aliyuncs.com/hxpdocker/podinfo:6.2.2" already present on machine
  Normal  Created    11s   kubelet            Created container podinfo
  Normal  Started    11s   kubelet            Started container podinfo
```

the image name is not mypodinfo

### Steps to reproduce

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: mygit3
    apiVersion: source.toolkit.fluxcd.io/v1beta2
    namespace: flux-system
  path: ./apps/staging
  prune: true
  images:
  - newName: registry.cn-hangzhou.aliyuncs.com/hxpdocker/mypodinfo
    name: registry.cn-hangzhou.aliyuncs.com/hxpdocker/podinfo
```

### Expected behavior

image name is mypodinfo

### OS / Distro

centos 8

### Flux version

v0.22.0

### Flux check

[root@node01 kustomization]# flux check
► checking prerequisites
✔ Kubernetes 1.21.0 >=1.20.6-0
► checking controllers
✗ no controllers found in the 'flux-system' namespace with the label selector 'app.kubernetes.io/part-of=flux'
► checking crds
✗ no crds found with the label selector 'app.kubernetes.io/part-of=flux'
✗ check failed

installed with kubevela

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
