### ISSUE TITLE
Flux unable to deploy charts after v0.36.0 update due to dependencies

### ISSUE THREAD

**Issue by jprecuch** [fluxcd/flux2#3302]
### Describe the bug

After we updated all our dev clusters to v0.36.0 FluxCD is unable to deploy new version of charts before it complains dependency are not Ready. However all the charts are deployed just fine. Any ideas why/how to resolve this?

```
{"level":"info","ts":"2022-11-09T07:59:50.351Z","msg":"reconcilation finished in 25.73442ms, next run in 30s","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":{"name":"rabbitmq","namespace":"rabbitmq"},"namespace":"rabbitmq","name":"rabbitmq","reconcileID":"f1310668-a905-4a97-bdd1-8dc6f3f2821b"}
{"level":"info","ts":"2022-11-09T08:00:20.357Z","msg":"dependencies do not meet ready condition (dependency 'velero/velero' is not ready), retrying in 30s","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":{"name":"rabbitmq","namespace":"rabbitmq"},"namespace":"rabbitmq","name":"rabbitmq","reconcileID":"c9f95db2-a1b7-40ef-8d02-935f92e8a64d"}
```

```
flux get all -n rabbitmq
NAME                	REVISION	SUSPENDED	READY	MESSAGE
helmrelease/rabbitmq	v1.2.44 	False    	False	dependency 'velero/velero' is not ready

flux get all -n velero
NAME              	REVISION	SUSPENDED	READY	MESSAGE
helmrelease/velero	2.32.1  	True     	True 	Release reconciliation succeeded

flux get all -n flux-system
NAME                     	REVISION    	SUSPENDED	READY	MESSAGE
gitrepository/flux-system	main/b15fe70	False    	True 	stored artifact for revision 'main/b15fe70688d0890a882150466e551db9a177b787'

NAME                               	REVISION                                                        	SUSPENDED	READY	MESSAGE
helmrepository/testing-repo 	de7ec1fde16b71658ea72abb835e396f1344df5ed086f817057ea1251af70c8a	False    	True 	stored artifact for revision 'de7ec1fde16b71658ea72abb835e396f1344df5ed086f817057ea1251af70c8a'


NAME                                       	REVISION        	SUSPENDED	READY	MESSAGE
helmchart/rabbitmq-rabbitmq                	v1.2.44         	False    	True 	pulled 'rabbitmq' chart with version 'v1.2.44'
helmchart/velero-velero                    	2.32.1          	False    	True 	pulled 'velero' chart with version '2.32.1'

NAME                                         	REVISION    	SUSPENDED	READY	MESSAGE
kustomization/flux-system                    	main/b15fe70	False    	True 	Applied revision: main/b15fe70
kustomization/region-deployment-us-east4-test	main/b15fe70	False    	True 	Applied revision: main/b15fe70

```

```
NAME            	NAMESPACE       	REVISION	UPDATED                                	STATUS  	CHART                             	APP VERSION
rabbitmq        	rabbitmq        	10      	2022-11-03 11:02:03.547462674 +0000 UTC	deployed	rabbitmq-v1.2.44                  	3.9.8
velero          	velero          	10      	2022-11-03 11:01:33.681602748 +0000 UTC	deployed	velero-2.32.1                     	1.9.2
```

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  releaseName: rabbitmq
  targetNamespace: rabbitmq
  chart:
    spec:
      chart: rabbitmq
      sourceRef:
        kind: HelmRepository
        name: testing-repo
        namespace: flux-system
  interval: 10m
  timeout: 30m
  dependsOn:
    - name: velero
      namespace: velero
  install:
    disableWait: false
    remediation:
      retries: 0
  upgrade:
    disableWait: false
    preserveValues: false
    remediation:
      retries: 0
```

This worked fine on previous version. I don't see any issue with deployments. All 3 regions which got latest versions are now affected by this.

Can you please debug this somehow to confirm why it says some dependency is not ready when all of them seem to be alive and kicking (deployed state).

### Steps to reproduce

Not sure. In our case was
1. Have all deployed charts before upgrading to latest v0.36.0 version..
2. Try to upgrade chart again.

### Expected behavior

When all deployments in helm are in deployed state, FluxCD should not complain about dependencies.

### OS / Distro

GKE

### Flux version

flux: v0.36.0

### Flux check

► checking prerequisites
W1109 08:14:10.919632    3183 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
✔ Kubernetes 1.24.4-gke.800 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.26.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.30.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.28.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.31.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
