### ISSUE TITLE
Flug purge bug

### ISSUE THREAD

**Issue by vinkiel** [fluxcd/flux2#3334]
### Describe the bug

I've tried to do a running jobs via Flux tutorial (https://fluxcd.io/flux/use-cases/running-jobs/) and there is a bug i think. Each
`Job/default/db-migration immutable field detected, failed to delete object, error: jobs.batch "db-migration" not found...`
Seems like some race condition - `force: true`, item is deleted in real, but Flux try to do load / delete it second time. 

### Steps to reproduce

Software Installed:

Flux:
```
% flux -v
flux version 0.36.0
```
K8S (Docker Desktop for Mac):
```
% kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.2
```

Please clone my error proof repo: https://github.com/vinkiel/flux-prune-bug.git 
(or fork it, change repo address in `flux/gotk-sync.yaml` to your)

and go to the repo folder:

`kubectl apply -k flux`

Results:
```    
namespace/flux-system created
customresourcedefinition.apiextensions.k8s.io/alerts.notification.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/buckets.source.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/gitrepositories.source.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/helmcharts.source.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/helmreleases.helm.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/helmrepositories.source.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/kustomizations.kustomize.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/ocirepositories.source.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/providers.notification.toolkit.fluxcd.io created
customresourcedefinition.apiextensions.k8s.io/receivers.notification.toolkit.fluxcd.io created
serviceaccount/helm-controller created
serviceaccount/kustomize-controller created
serviceaccount/notification-controller created
serviceaccount/source-controller created
clusterrole.rbac.authorization.k8s.io/crd-controller-flux-system created
clusterrolebinding.rbac.authorization.k8s.io/cluster-reconciler-flux-system created
clusterrolebinding.rbac.authorization.k8s.io/crd-controller-flux-system created
service/notification-controller created
service/source-controller created
service/webhook-receiver created
deployment.apps/helm-controller created
deployment.apps/kustomize-controller created
deployment.apps/notification-controller created
deployment.apps/source-controller created
kustomization.kustomize.toolkit.fluxcd.io/app-deploy created
kustomization.kustomize.toolkit.fluxcd.io/app-pre-deploy created
kustomization.kustomize.toolkit.fluxcd.io/flux-system created
networkpolicy.networking.k8s.io/allow-egress created
networkpolicy.networking.k8s.io/allow-scraping created
networkpolicy.networking.k8s.io/allow-webhooks created
gitrepository.source.toolkit.fluxcd.io/flux-system created
```

`kubectl get gitrepository -n flux-system`

```
NAME          URL                                             AGE   READY   STATUS
flux-system   https://github.com/vinkiel/flux-prune-bug.git   90s   True    stored artifact for revision 'main/037f48ace8b2dd2381c4fa652317e237268fae6f'
```

`kubectl get kustomization -n flux-system`

```
NAME             AGE     READY   STATUS
app-deploy       2m55s   True    Applied revision: main/037f48ace8b2dd2381c4fa652317e237268fae6f
app-pre-deploy   2m55s   True    Applied revision: main/037f48ace8b2dd2381c4fa652317e237268fae6f
flux-system      2m55s   True    Applied revision: main/037f48ace8b2dd2381c4fa652317e237268fae6f
```

`kubectl get pod`

```
NAME                 READY   STATUS      RESTARTS   AGE
db-migration-8lmwz   0/1     Completed   0          5m22s
webserver            1/1     Running     0          4m57s
```

`kubectl logs db-migration-8lmwz`

```
starting db migration
```

Looks good till now.

Now change tag of busybox in `pre-deploy/migration.job.yaml` to 1.34 , commit and push to main branch.  Wait for sync (you can use `kubectl get kustomization -n flux-system -w` to observe)

`kubectl get kustomization -n flux-system `

```
NAME             AGE   READY   STATUS
app-deploy       11m   False   dependency 'flux-system/app-pre-deploy' revision is not up to date
app-pre-deploy   11m   False   Job/default/db-migration immutable field detected, failed to delete object, error: jobs.batch "db-migration" not found...
flux-system      11m   True    Applied revision: main/c90a7a1657c2bde80a2e61081f0147c766550392
```

`Job/default/db-migration immutable field detected, failed to delete object, error: jobs.batch "db-migration" not found...` is the error that blocks deployment.

However Job was removed due `force: true`: 

`kubectl get jobs`

```
No resources found in default namespace.
```

Note: issue is not repeatable every time, so seems like a race condition. Please change version of busybox few time more if first try pass with no errors.

### Expected behavior

There should be no error `Job/default/db-migration immutable field detected, failed to delete object, error: jobs.batch "db-migration" not found...` and jobs should be recreated smooth way

In my o

### OS / Distro

Mac OS 12.1 (21C52)

### Flux version

flux: v0.36.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.25.2 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.26.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.30.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.28.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.31.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinkiel** [comment]
Update:

when i add .spec.ttlSecondsAfterFinished=60 in my job it works fine (Job is removed after 60s, and next sync can just create is instead of delete and create).... this can be workaround, but `force: true`, should works better.

**Comment by SrDayne** [comment]
Confirm same issue on 0.37.0

**Comment by stefanprodan** [comment]
The error message is very strange ` jobs.batch "hello-migrations" not found` as if the job was already deleted. Can you replicate this with Kubernetes Kind?

**Comment by sylvainOL** [comment]
I'm facing same issue
it's seems on my side that some jobs are present and other are not so maybe flux is puzzled because of that

**Comment by sylvainOL** [comment]
when I remove all jobs, reconciliation is passing

**Comment by somtochiama** [comment]
@sylvainOL what version of flux are you using? and what do you get if you try to dry-run apply the job with server-side apply
```
kubectl apply --server-side --dry-run=server -f job.yaml
```

**Comment by sylvainOL** [comment]
Hi @somtochiama, I've just tested it:

```shell
$ kubeclt get kustomization -n flux-system xtesting-postinstallation
NAME                        AGE   READY   STATUS
xtesting-postinstallation   82d   False   Job/xtesting/xtesting-provisioning immutable field detected, failed to delete object, error: jobs.batch "xtesting-provisioning" not found...
$ kubectl apply --server-side --dry-run=server -f base/postinstallation/job.yaml
job.batch/xtesting-provisioning serverside-applied (server dry run)
```

the job in question:

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
  labels:
    app.kubernetes.io/name: xtesting-provisioning
    kustomize.toolkit.fluxcd.io/force: enabled
    kustomize.toolkit.fluxcd.io/substitute: disabled
  name: xtesting-provisioning
  namespace: xtesting
spec:
  backoffLimit: 10
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app.kubernetes.io/name: xtesting-provisioning
        job-name: xtesting-provisioning
    spec:
      containers:
      - command:
        - /scripts/populate_xtesting_db.sh
        envFrom:
        - configMapRef:
            name: postconfigure-env-configuration
        # yamllint disable-line rule:line-length
        image: xxx/xtesting-configuration:1.2.4
        imagePullPolicy: Always
        name: xtesting-provisioning
        resources:
          limits:
            ephemeral-storage: 100Mi
            memory: 100Mi
          requests:
            cpu: 200m
            ephemeral-storage: 100Mi
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /app/pods.yaml
          name: config-pods
          subPath: pods.yaml
        - mountPath: /app/testcases.yaml
          name: config-testcases
          subPath: testcases.yaml
        - mountPath: /scripts
          name: scripts
      imagePullSecrets:
      - name: gitlab-docker-auth
      restartPolicy: Never
      securityContext:
        runAsGroup: 10001
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: xtesting-jobservice
      volumes:
      - configMap:
          defaultMode: 0440
          name: postconfigure-pods-configuration
        name: config-pods
      - configMap:
          defaultMode: 0440
          name: postconfigure-testcases-configuration
        name: config-testcases
      - configMap:
          defaultMode: 0550
          name: populate-db-script
        name: scripts
```
