### ISSUE TITLE
flux reconcile kustomization fails on encrypted objects with ".sops: field not declared in schema"

### ISSUE THREAD

**Issue by marccarre** [fluxcd/flux2#3367]
### Describe the bug

When running:

```console
flux reconcile kustomization flux-system --with-source
```

if the repository contains SOPS-encrypted objects, then the command fails with:

```console
► annotating GitRepository flux-system in flux-system namespace
✔ GitRepository annotated
◎ waiting for GitRepository reconciliation
✔ fetched revision main/${GIT_COMMIT_HASH}
► annotating Kustomization flux-system in flux-system namespace
✔ Kustomization annotated
◎ waiting for Kustomization reconciliation
✗ Kustomization reconciliation failed: ConfigMap/${NAMESPACE}/${NAME} dry-run failed, error: failed to create typed patch object (${NAMESPACE}/${NAME}; /v1, Kind=ConfigMap): .sops: field not declared in schema
```

This happens with:

```console
$ flux -v
flux version 0.37.0
```
and
```console
$ sops -v
sops 3.7.3 (latest)
```

### Steps to reproduce

1. [Install Flux](https://fluxcd.io/flux/installation/)
2. [Configure SOPS](https://fluxcd.io/flux/guides/mozilla-sops/)
3. Encrypt a `ConfigMap` with SOPS, to have something like the following in Git:
    ```yaml
    apiVersion: v1
    kind: ConfigMap
    metadata:
        name: ${NAME}
        namespace: ${NAMESPACE}
    data:
        [...]
    sops:
        kms: []
        gcp_kms: []
        azure_kv: []
        hc_vault: []
        age: []
        lastmodified: "2022-12-03T06:32:42Z"
        mac: [...]
        pgp:
            - created_at: "2022-12-03T06:32:42Z"
              enc: [...]
              fp: [...]
        encrypted_regex: ^(data|stringData|[Pp]ass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|.*[Tt]oken)$
        version: 3.7.3
    ```
4. Run:
    ```console
    $ flux reconcile kustomization flux-system --with-source
    ► annotating GitRepository flux-system in flux-system namespace
    ✔ GitRepository annotated
    ◎ waiting for GitRepository reconciliation
    ✔ fetched revision main/${GIT_COMMIT_HASH}
    ► annotating Kustomization flux-system in flux-system namespace
    ✔ Kustomization annotated
    ◎ waiting for Kustomization reconciliation
    ✗ Kustomization reconciliation failed: ConfigMap/${NAMESPACE}/${NAME} dry-run failed, error: failed to create typed patch object (${NAMESPACE}/${NAME}; /v1, Kind=ConfigMap): .sops: field not declared in schema
    ```

### Expected behavior

Reconciliation should be updated to either:

- tolerate this `sops` field, or
- if there is a way to alter the schema to make the `sops` field legit, then we should aim to either:
  - do so automatically as part of Flux/SOPS' bootstrap, or
  - document how to do so manually in https://fluxcd.io/flux/guides/mozilla-sops/

### OS / Distro

macOS Monterey Version 12.6

### Flux version

v0.37.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.25.2+k0s >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.27.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.27.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.23.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.31.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.29.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.32.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

GitHub

### Container Registry provider

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marccarre** [comment]
Somehow, adding:

```yaml
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
```

to `flux-system/gotk-sync.yaml`'s `Kustomization` via a pull request didn't get picked up by Flux.
Re-applying it manually seems to have fixed it:

```console
$ kubectl apply -f flux-system/gotk-sync.yaml 
```

```console
$ flux reconcile kustomization flux-system --with-source   
► annotating GitRepository flux-system in flux-system namespace
✔ GitRepository annotated
◎ waiting for GitRepository reconciliation
✔ fetched revision main/${GIT_COMMIT_HASH}
► annotating Kustomization flux-system in flux-system namespace
✔ Kustomization annotated
◎ waiting for Kustomization reconciliation
✔ applied revision main/${GIT_COMMIT_HASH}
```

The `kustomize-controller`'s logs also now look healthier.

Closing this issue for now. 
(Not 100% sure if I did something wrong, or if the documentation could be improved, though.)
