### ISSUE TITLE
postRenderers has no effect

### ISSUE THREAD

**Issue by ar-qun** [fluxcd/flux2#3388]
### Describe the bug

postRenderers field seems to have no effect. It is displayed by describe but nothing happens. Same patches work against a raw yaml with Kustomization.kustomize.config.k8s.io/v1beta1.

### Steps to reproduce

Apply a helm release with a patch. For example and 

```
postRenderes:
  patchesJson6902:
    - patch: |-
        - op: remove
          path: /spec/tls
      target:
        group: networking.k8s.io
        version: v1
        kind: Ingress
        namespace: test
        name: test
```

### Expected behavior

tls field should be removed

### OS / Distro

Ubuntu 20.04 WSL

### Flux version

v0.37.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.23.12-gke.100 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.27.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.27.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.23.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.31.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.29.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.32.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
