### ISSUE TITLE
Notification Controller sending Slack Notifications twice 

### ISSUE THREAD

**Issue by alexandros-genies** [fluxcd/flux2#3406]
### Describe the bug

Slack notifications/alerts using the standard Provider, is sending info level events twice to Slack. 

This is clogging up the channel, as any change to a manifest results in 4 messages being sent.

2 for the deployment manifest change, and 2 for the health check passing.

### Steps to reproduce

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  type: slack
  channel: flux_dev_feed
  secretRef:
    name: slack
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack-monitoring
  namespace: flux-system
spec:
  type: slack
  channel: flux_dev_monitoring_feed
  secretRef:
    name: slack-monitoring
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: dev-kustomization-feed
  namespace: flux-system
spec:
  summary: "general app updates"
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'apps'
--- 
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: dev-monitoring-feed
  namespace: flux-system
spec:
  summary: "general cluster updates"
  providerRef:
    name: slack-monitoring
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: HelmRepository
      name: '*'
    - kind: Kustomization
      name: '*'

```

### Expected behavior

Only one message per event should be sent.

### OS / Distro

AWS EKS standard AWS Linux 2 image for EKS

### Flux version

flux: v0.36.0

### Flux check

► checking prerequisites
✗ flux 0.36.0 <0.37.0 (new version is available, please upgrade)
✔ Kubernetes 1.22.15-eks-fb459a0 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.26.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.30.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.28.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.31.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
