### ISSUE TITLE
Unable to install chart from OCI helm repository

### ISSUE THREAD

**Issue by ecoupal-believe** [fluxcd/flux2#3438]
### Describe the bug

I can't install a chart using `HelmRelease `and `HelmRepository ` crds but it's working when I'm using the helm cli.

The repo seems ok
![image](https://user-images.githubusercontent.com/103646557/209171638-4d377de8-15fd-4c5b-83ca-d2dbde6dd0b0.png)

But the release is not ready
![image](https://user-images.githubusercontent.com/103646557/209171736-6a40b940-e918-413b-baa2-53a692071250.png)

I keep getting this error:

`chart pull error: failed to download chart for remote reference: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden`

### Steps to reproduce

Here are the manifests:

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: apollo-router
spec:
  type: "oci"
  interval: 1h
  url: oci://ghcr.io/apollographql/helm-charts/router
```
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apollo-router
spec:
  releaseName: apollo-router
  chart:
    spec:
      chart: router
      sourceRef:
        kind: HelmRepository
        name: apollo-router
        namespace: apps
      version: "1.0.0-rc.10"
  interval: 1h
```

### Expected behavior

I have expect the release to be installed as any other release.

### OS / Distro

N/A

### Flux version

flux: v0.35.0

### Flux check

► checking prerequisites
✗ flux 0.35.0 <0.38.2 (new version is available, please upgrade)
✔ Kubernetes 1.23.13-eks-fb459a0 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.27.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.27.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.23.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.31.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.32.1
► checking crds
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Additional context

Everything is working when i'm using helm cli:

`helm install router oci://ghcr.io/apollographql/helm-charts/router`

```
helm version
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
