### ISSUE TITLE
Configure image scanning faild 

### ISSUE THREAD

**Issue by jiangguoqing** [fluxcd/flux2#3442]
Create an ImageRepository to tell Flux which container registry to scan for new tags,but give  error":"Get \"https://167.71.195.24:30002/v2/":server gave HTTP response to HTTPS client.how to configue image scanner scan an insecure-registries?

**Comment by gecube** [comment]
Hi @jiangguoqing,

This is supported now: `ImageRepository` has a `.spec.insecure` field for scanning plain-HTTP registries. It was added in Flux v2.2.0 (image-reflector-controller v0.31.0), so it did not exist yet on the version you were running when you opened this issue — hence the `server gave HTTP response to HTTPS client` error with no way to opt out.

I just verified this on Flux v2.9.2 against a plain-HTTP `registry:2`:

```yaml
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: app
  namespace: default
spec:
  image: 192.168.215.4:5000/app
  interval: 1m
  insecure: true
```

The scan succeeds: `successful scan: found 2 tags` (`v1.1.0`, `v1.0.0` in `.status.lastScanResult`). Note that a cluster admin can forbid HTTP registries fleet-wide by running the controller with `--insecure-allow-http=false`, in which case objects with `insecure: true` are stalled.

If you are still hitting this on a current Flux version, could you please share the exact `ImageRepository` manifest and the `flux version` output? Otherwise I believe this can be closed as resolved by `.spec.insecure`.
