### ISSUE TITLE
The same helm chart can be installed successfully by command line , but not by fluxcd.

### ISSUE THREAD

**Issue by xiemeilong** [fluxcd/flux2#3446]
### Describe the bug

The same helm chart can be installed successfully by command line , but not by fluxcd.

This works.
```
helm install skywalking \
  oci://registry-1.docker.io/apache/skywalking-helm \
  --version 4.4.0  \
  -n istio-system \
  --set oap.image.tag=9.3.0 \
  --set oap.replicas=1 \
  --set oap.storageType=elasticsearch \
  --set elasticsearch.replicas=1 \
  --set ui.image.tag=9.3.0
```

This not works.   It seems the Job resource is not installed. so the service can not start. 
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: skywalking
spec:
  chart:
    spec:
      chart: skywalking-helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: apache
        namespace: flux-system
      version: 4.4.*
      interval: 168h
  interval: 10m
  values:
    oap:
      image:
        tag: 9.3.0
      storageType: elasticsearch
      replicas: 1
    ui:
      image:
        tag: 9.3.0
    elasticsearch:
      replicas: 1
```

error message: 
`install retries exhausted`

### Steps to reproduce

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: apache
spec:
  type: "oci"
  interval: 168h
  url: oci://registry-1.docker.io/apache
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: skywalking
spec:
  chart:
    spec:
      chart: skywalking-helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: apache
        namespace: flux-system
      version: 4.4.*
      interval: 168h
  interval: 10m
  values:
    oap:
      image:
        tag: 9.3.0
      storageType: elasticsearch
      replicas: 1
    ui:
      image:
        tag: 9.3.0
    elasticsearch:
      replicas: 1
```

### Expected behavior

The skywalking started successfully.

### OS / Distro

Debian 11

### Flux version

v0.38.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► harbor.xxxxxx.com:10000/ghcr/fluxcd/helm-controller:v0.28.1
✔ image-automation-controller: deployment ready
► harbor.xxxxxx.com:10000/ghcr/fluxcd/image-automation-controller:v0.28.0
✔ image-reflector-controller: deployment ready
► harbor.xxxxxx.com:10000/ghcr/fluxcd/image-reflector-controller:v0.23.1
✔ kustomize-controller: deployment ready
► harbor.xxxxxx.com:10000/ghcr/fluxcd/kustomize-controller:v0.32.0
✔ notification-controller: deployment ready
► harbor.xxxxxx.com:10000/ghcr/fluxcd/notification-controller:v0.30.2
✔ source-controller: deployment ready
► harbor.xxxxxx.com:10000/ghcr/fluxcd/source-controller:v0.33.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

gitea

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
