### ISSUE TITLE
Setting optional in substituteFrom does not work

### ISSUE THREAD

**Issue by pjastrzabek-roche** [fluxcd/flux2#3448]
### Describe the bug

I'm trying to configure multiple substitution config maps and some of them I want to make optional. Whole kustomization object looks like this:
```
           apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
            kind: Kustomization
            metadata:
              name: main
              namespace: flux-system
            spec:
              interval: 10m
              path: ./kubernetes/gitops/control-plane/base
              postBuild:
                substituteFrom:
                - kind: ConfigMap
                  name: kustomize-variables
                - kind: ConfigMap
                  name: kustomize-variables-aws
                  optional: true
              prune: true
              sourceRef:
                kind: GitRepository
                name: main
              suspend: false
              validation: none
```

This yaml is being configured via kubectl provider via terraform and in terraform logs I see optional value as "true"

But when I check the value of this resource
```
k get kustomization -n flux-system main -o yaml
```

optional is set to false

### Steps to reproduce

1. Try to create Kustomization with optional substitution from configmap set to true
2. Inspect value of optional field
```
k get kustomization -n flux-system main -o jsonpath='{.spec.postBuild}' | jq .
```

### Expected behavior

Optional field should be set to proper value

### OS / Distro

N/A

### Flux version

v0.36.0

### Flux check

► checking prerequisites
✗ flux 0.36.0 <0.38.2 (new version is available, please upgrade)
✔ Kubernetes 1.24.7-eks-fb459a0 >=1.20.6-0
► checking controllers
✗ no controllers found in the 'flux-system' namespace with the label selector 'app.kubernetes.io/part-of=flux'
► checking crds
✗ no crds found with the label selector 'app.kubernetes.io/part-of=flux'
✗ check failed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
