### ISSUE TITLE
Pick latest build image always if no policy but filter tag given

### ISSUE THREAD

**Issue by abhijit838** [fluxcd/flux2#3449]
### Discussed in https://github.com/fluxcd/flux2/discussions/3265

<div type='discussions-op-text'>

<sup>Originally posted by **marrip** October 28, 2022</sup>
Hi,

I have a flux2 deployment running and want flux to automatically update the image I am running in the test environment. My images can be tagged with anything from `<branch>-<sha>` to semver tags. I created a `ImagePolicy` such as :

```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: test
  namespace: test
spec:
  imageRepositoryRef:
    name: test
    namespace: test
  policy:
   alphabetical:
      order: asc
```

which is clearly not what I want as commit shas are random and I always want to last image built not the first on the list deployed into the cluster. Any pointers or ideas?</div>
