### ISSUE TITLE
Flux CLI tool doesn't respect context namespace

### ISSUE THREAD

**Issue by sharkymcdongles** [fluxcd/flux2#3453]
### Describe the bug

Say a Kubeconfig has the following block:

```
contexts:
- context:
    cluster: cluster
    namespace: services
    user: user
  name: cluster
current-context: cluster
```

When you run flux commands it will not target the namespace your context is currently using. It always targets flux-system unless the namespace flag is specified. For continuity sake between all kubernetes cli tools e.g. kubectl and helm the cli should use namespace context for CLI calls.

### Steps to reproduce

1. Set your kubecontext to a namespace containing a helmrelease e.g.

```
namespace: services
helmrelease: service
```

2. Run 
`flux reconcile hr service`

3. See this error
`✗ helmreleases.helm.toolkit.fluxcd.io "service" not found`

4. Run
`flux reconcile hr service --namespace service`

It works

### Expected behavior

1. Set your kubecontext to a namespace containing a helmrelease e.g.

```
namespace: services
helmrelease: service
```

2. Run 
`flux reconcile hr service`
it works

### OS / Distro

Fedora

### Flux version

v0.38.2

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
