### ISSUE TITLE
Kustomize key `specs.suspend` does not get removed by flux on a flux-created kustomization resource after being manually added on the cluster. 

### ISSUE THREAD

**Issue by MahrRah** [fluxcd/flux2#3462]
### Describe the bug

Flux does not properly revert a manually changed kustomization resource back to what was defined in the GitOps repository. 
If one uses a bootstrap approach to create multiple kustomization resources from their definitions in the GitOps repository, flux will not remove a manually added `specs.suspend` key. This is the case even if the bootstrap resource has `spec.prune=true`.

### Steps to reproduce

1. Create bootstrap kustomization resources with `spec.prune=true`, which creates a set of kustomization resources defined in the GitOps repository
    ```sh
      flux create kustomization bootstrap \
        --path="./clusters/<device-ID>/flux" \
        --source=gitops-source \
        --prune=true \
        --interval=1m
    
    ```
    Simplified GitOps repository folder structure:
    ```text
    .
    ├── apps
    └── clusters
          └── <device-ID>
              ├── flux
              │     ├── sets-1.yaml
              │     └── sets-2.yaml
              └── sets
                    └── sets-1
                    └── sets-2
    
    ```
    
    eg. Kustomization resource definition pointing to `clusters/<device-ID>/sets/sets-1` defined in the manifest file `clusters/<device-ID>/flux/sets-1.yaml`
    
    ```yaml
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    kind: Kustomization
    metadata:
      name: <device-ID>-sets-1
      namespace: flux-system
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: gitops-repo
        namespace: flux-system
      path: ./clusters/<device-ID>/sets/sets-1
      prune: true
      wait: true
      timeout: 10m
    ```
    
    The key  `spec.suspend` is not specified in any of the resource definitions of the kustomization resources in the GitOps repo.
    As expected neither is the `spec.suspend` key set for the created kustomization resources on the cluster, when checking with `kubectl`.
   
3. Manually suspend the kustomization resource with `flux suspend` on the cluster. This will add the `spec.suspend=true` to the kustomization resource.
    ```bash
    flux suspend kustomization <device-ID>-sets-1
    ```
4.  After reconciliation the suspend key does not get removed from the kustomization resource. The resource's state on the cluster is therefore different from what is defined in the GitOps repository.

### Expected behavior

Flux would revert the kustomization resource to how it was defined in the GitOps repository. Which would mean in this case removing the added `spec.suspend=true` from the resource. 

The change only gets reverted back, if the kustomization resource definition in `clusters/flux/` has a reference to `spec.suspend`.

### Screenshots and recordings

Flux would revert the kustomization resource to how it was defined in the GitOps repository. Which would mean in this case removing the added `spec.suspend=true` from the resource. 

The change only gets reverted back, if the kustomization resource definition in `clusters/flux/` has a reference to `spec.suspend`.

### OS / Distro

Ubuntu 20.04

### Flux version

v0.37.0

### Flux check

► checking prerequisites
✗ flux 0.37.0 <0.38.2 (new version is available, please upgrade)
✔ Kubernetes 1.25.4+k3s1 >=1.20.6-0
► checking controllers
✔ kustomize-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/kustomize-controller:v0.31.0
✔ notification-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/notification-controller:v0.29.0
✔ helm-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/helm-controller:v0.27.0
✔ source-controller: deployment ready
► mcr.microsoft.com/oss/fluxcd/source-controller:v0.32.1
✔ fluxconfig-controller: deployment ready
► mcr.microsoft.com/azurek8sflux/fluxconfig-controller:1.6.3
► mcr.microsoft.com/azurek8sflux/fluent-bit:1.6.3
✔ fluxconfig-agent: deployment ready
► mcr.microsoft.com/azurek8sflux/fluxconfig-agent:1.6.3
► mcr.microsoft.com/azurek8sflux/fluent-bit:1.6.3
► checking crds
✔ fluxconfigs.clusterconfig.azure.com/v1alpha1
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by souleb** [comment]
I think that is the expected behaviour. When running `flux suspend kustomization`, `spec.suspend` is set to `true` in the live `kustomize` object. The consequence of this is that the `kustomize-controller` will not attempt the object reconciliation. See: https://github.com/fluxcd/kustomize-controller/blob/803349d1c25b2d3aa8b5aac36054d7357dccd529/controllers/kustomization_controller.go#L215.

Yes there is a drift, but again that is what expected. You don't want the drift detection to kick in during an investigation for example. That when you rely on `suspend`.

You have to manually use `flux resume kustomization` for the reconciliation to be performed again.

**Comment by MahrRah** [comment]
I see what you mean, but could this behavior not be achieved by adding the annotation `kustomize.toolkit.fluxcd.io/reconcile=disabled` to the `kustomization` resource and then suspending it?


Also, what I then would not expect is the suspended `kustomization` resource to be reverted in case the kustomization manifest explicitly contains `suspend: false`. 
Eg. If I define the following in my GitOps repo:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: <device-ID>-sets-1
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: gitops-repo
    namespace: flux-system
  path: ./clusters/<device-ID>/sets/sets-1
  prune: true
  wait: true
  suspend: false
  timeout: 10m
```
Even if I suspend the `<device-ID>-sets-1` `kustomization` the `spec.suspend` will be reverted back within minutes to `false`.

Maybe to give some context on why I found this issue.  We are suspending certain `kustomization` resources till a defined time window arrives and then resuming them. The goal is to enable a type of reconciliation/maintenance window for the resources managed by that kustomizaton.
