### ISSUE TITLE
Newline in generated secrets

### ISSUE THREAD

**Issue by mjroeleveld** [fluxcd/flux2#3463]
### Describe the bug

Kubernetes secrets generated by secretGenerator contain newlines.

### Steps to reproduce

```
sops secrets/test
```
Save it without any newline.

Add a kustomization with the following:
```
secretGenerator:
  - files:
      - secrets/test
    name: test-secret
```

The secret in k8s contains a newline.

### Expected behavior

The secret should not contain a newline.

### OS / Distro

Amazon EKS optimized Amazon Linux AMIs

### Flux version

0.38.2

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
