### ISSUE TITLE
Flux doesn't do deployment rolling updates on chart version update

### ISSUE THREAD

**Issue by absnmohammed** [fluxcd/flux2#3466]
Hi, 

We have a scenario where we are making change to values in Helm charts and updating the chart version. Flux doing all at once deployment instead of rolling update which is a default deployment strategy. 

This is resulting in the downtime, it works fine if the values change via Flux repository instead of helm chart repo. 

helm-controller:v0.22.1

Please let me know if this is a bug or if am doing something wrong here.

**Comment by kingdonb** [comment]
Flux doesn't make any controlling changes to the manifests that it applies, it is unlikely that the issue is in Flux but more likely that it is an issue in your chart. You are several minor releases behind in Helm Controller, the latest is v0.28.x, and while I think this is not likely to make any difference in this issue, it's always my first advice to try this again on the latest version.

The only major way that Flux's `helm upgrade` differs from Helm upstream (the CLI) is that it enables resource waiting by default. So if your HelmRelease has some resource that does not become ready, it will hold up the whole release and Helm will eventually report the release as failed.

https://fluxcd.io/flux/components/helm/helmreleases/#disabling-resource-waiting

This is configurable, you can enable or disable resource waiting to get more similar behavior to the default of Helm. This is not likely to be related to the issue reported, but just to highlight there is very little difference between Helm as Flux does vs Helm as the Helm CLI does.

You will likely find there is similar behavior if you try upgrading the Helm chart by hand in your cluster, (this is one way you could attempt to confirm or refute that there is any behavior difference between Helm vs Flux's Helm Controller)

If you can share the chart and HelmRelease, we can possibly shed some additional light on how this happens!

**Comment by absnmohammed** [comment]
Can someone please looks into this and shed some light?

**Comment by gladiatr72** [comment]
@absnmohammed can you show the full HelmRelease manifest?

**Comment by absnmohammed** [comment]
@gladiatr72, thanks for picking this up. I forgot to update the thread, this has been fixed after an upgrade to latest `helm_controller`.

FYI, deployment.yaml is using default rolling updates strategy, 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
  annotations:
    {{- include "reloader_anotation" . | indent 4 }}
    {{- toYaml .Values.deploymentAnnotations | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: RollingUpdate
```
