### ISSUE TITLE
Issues reconciling kustomizations containing statefulsets

### ISSUE THREAD

**Issue by yoan-myparcel** [fluxcd/flux2#3573]
### Describe the bug

The following statefulset is included in a kustomization and the dry-run is complaining that we are trying to update forbidden fields.

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sandbox
  labels:
    app: sandbox
spec:
  minReadySeconds: 10
  serviceName: sandbox
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
        - name: sandbox
          image: sandbox
          args:
            - sleep
            - infinity
          imagePullPolicy: IfNotPresent
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
```
The initial reconciliation succeeds. However, if I change the template, the number of replicas or minReadySeconds I get the following error while reconciling:

```
✗ Kustomization reconciliation failed: StatefulSet/develop/sandbox dry-run failed, reason: Invalid, error: StatefulSet.apps "sandbox" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy' and 'minReadySeconds' are forbidden
```

I haven't tried to update the values of any of the forbidden fields. Is it possible that flux/kustomize is modifying something?

I am using version 0.35.0. However, I tracked the changelogs in each new version after 0.35 and I did not see anything related to statefulsets being changed. 

### Steps to reproduce

1. Use flux 0.35.0
2. Reconcile a kustomization with the following statefulset
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sandbox
  labels:
    app: sandbox
spec:
  minReadySeconds: 10
  serviceName: sandbox
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
        - name: sandbox
          image: sandbox
          args:
            - sleep
            - infinity
          imagePullPolicy: IfNotPresent
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
```
3. Change one of the allowed fields, such as replicas or minReadySeconds
4. Reconcile the kustomization again

### Expected behavior

Statefulsets get applied without issues when no forbidden fields are modified.

### OS / Distro

Ubuntu 22.04

### Flux version

0.35.0

### Flux check

► checking prerequisites
✗ flux 0.35.0 <0.39.0 (new version is available, please upgrade)
✔ Kubernetes 1.22.16-eks-ffeb93d >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.25.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.26.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.22.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.29.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.27.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.30.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta1
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta1
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
