### ISSUE TITLE
gotk create source git does not create secret for ssh

### ISSUE THREAD

**Issue by vchrisb** [fluxcd/flux2#360]
I'm using following gotk (version 0.1.8, macos) command to create a git source with ssh for a private github repo;
```
gotk create source git reponame \
  --url="ssh://git@github.com/vchrisb/<repo>" \
  --branch=master \
  --interval=30s \
  --export
```

But it somehow gotk does not recognise, that the scheme is `ssh` and hence doesn't trigger the creation of a deploy key.

The output is:
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: k8s-home
  namespace: gotk-system
spec:
  interval: 30s
  ref:
    branch: master
  url: ssh://git@github.com/vchrisb/<repo-name>
```

I looked at the sources, but can't figure out why it isn't triggered https://github.com/fluxcd/toolkit/blob/main/cmd/gotk/create_source_git.go#L188
