### ISSUE TITLE
Kustomization controller does not follow symlinks in GitRepos

### ISSUE THREAD

**Issue by clux** [fluxcd/flux2#3619]
### Describe the bug

GitOps repositories that re-use common files in different environment folders currently have to duplicate the yaml even though parts of the yaml is designed to be the same across all environments.

Create a symlink in a gitops repo pointing to another folder that is part of the same `GitRepo` (and not ignored).

The GitRepo gets updated, but the KS seemingly does not follow symlinks when applying and fails with:

```sh
 kustomization path not found: stat /tmp/kustomization-1896818420/development/dashboards: no such file or directory
```

### Steps to reproduce

Enter a gitops repository and link a thing from one folder to another:
```
cd development
ln -sn ../common/dashboards .
git add dashboards && git commit -am "a" && git push
```

GitRepo has all successful conditions, updated to latest revision and using the following spec:
```yaml
spec:
  gitImplementation: go-git
  interval: 1m
  ref:
    branch: master
  secretRef:
    name: gitops-YYY
  timeout: 60s
  url: ssh://git@github.com/XXX/gitops-YYY
```

KS has:

```yaml
spec:
  force: false
  interval: 1m
  path: development/dashboards
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-YYY
  targetNamespace: monitoring
status:
  conditions:
  - lastTransitionTime: "2023-02-21T13:46:19Z"
    message: 'kustomization path not found: stat /tmp/kustomization-1003430881/development/dashboards:
      no such file or directory'
    reason: ArtifactFailed
    status: "False"
    type: Ready
```

### Expected behavior

Flux should follow the symlink provided the place the link is pointing to is not deliberately ignored by the GitRepo.
NB: fluxv1 followed symlinks.

### OS / Distro

N/A

### Flux version

N/A

### Flux check

```
$ flux check -n flux2
► checking prerequisites
✗ flux 0.39.0 <0.40.0 (new version is available, please upgrade)
✔ Kubernetes 1.24.8-eks-ffeb93d >=1.20.6-0
► checking controllers
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.28.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.29.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed
```

### Git provider

GH

### Additional context

Nothing else in the kustomization-controller logs. Just `kustomization path not found: stat /tmp/kustomization-3028922926/development/dashboards: no such file or directory`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
