### ISSUE TITLE
Enable SOPS decryption kustomization patch blocked by sops-encryped files

### ISSUE THREAD

**Issue by cwi-tyrone** [fluxcd/flux2#3629]
### Describe the bug

We deploy Flux using the Terraform provider and we make use of kustomization patches to enable sops decryption.
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-apps
  namespace: flux
spec:
  decryption:
    provider: sops
```

The issue is that when we try to create a new cluster with an existing Git repo with sops-encrypted files, Flux will try parsing a sops-encrypted file *before* it applies this patch to enable sops-decryption. Flux fails to parse the encrypted file and blocks all other changes (including the patch to enable sops decryption).

### Steps to reproduce

To emulate what the Terraform code is doing:
1. Create a repository with multiple sops-encrypted files
2. Generate Flux manifests and create patch files to enable sops decryption and add to git repo
```
flux/
├── gotk-components.yaml
├── gotk-sync.yaml
├── kustomization.yaml
├── patch-enable-sops.yaml
└── patch-irsa.yaml
```
```yaml
# patch-enable-sops.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kustomize-controller
  namespace: flux
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/kms-sops
```
```yaml
# patch-irsa.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-install
  namespace: flux
spec:
  decryption:
    provider: sops
```
3. Apply Flux manifests (i.e. `gotk-components.yaml` and `gotk-sync.yaml`) to the cluster

### Expected behavior

Flux should patch itself to enable sops decryption and then apply sops-encrypted manifest files.

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
