### ISSUE TITLE
Strange behavior with variable substitution depending of the folder

### ISSUE THREAD

**Issue by QuentinBtd** [fluxcd/flux2#3632]
### Describe the bug

I have trouble with variable substitution depending of the folder.

I have this structure in my git fluxcd repo:

```
.
└── flux-cd/
    ├── apps/base/k8s-apps/
    │   ├── k8s-app-aws-ebs-csi-driver.yaml
    │   ├── k8s-app-cluster-autoscaler.yaml
    │   └── k8s-app-metrics-server.yaml
    └── clusters/
        └── my-cluster-1/
            ├── flux-system/
            ├── apps/
            │   ├── kustomization.yaml
            │   └── nexus.yaml
            ├── apps.yaml
            └── k8s-apps.yaml
```

In `./flux-cd/apps/base/k8s-apps/k8s-app-aws-ebs-csi-driver.yaml`

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: k8s-app-aws-ebs-csi-driver
  namespace: flux-system
spec:
  url: ssh://fluxcd@gerrit.example.com:29418/k8s-app-aws-ebs-csi-driver
  ref:
    branch: ${git_branch}
  secretRef:
    name: flux-system
  interval: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: k8s-app-aws-ebs-csi-driver
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: k8s-app-aws-ebs-csi-driver
  path: .infra/flux/${cluster_name}/
  interval: 5m
  prune: true
  postBuild:
    substitute:
      cluster_name: ${cluster_name}
      aws_account_id: "${aws_account_id}"

```

In `./flux-cd/apps/base/k8s-apps/kustomization.yaml`

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k8s-app-aws-ebs-csi-driver.yaml
```

In `./flux-cd/clusters/my-cluster-1/apps/nexus.yaml`

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: nexus
  namespace: flux-system
spec:
  url: ssh://fluxcd@gerrit.example.com:29418/nexus
  ref:
    branch: master
  secretRef:
    name: flux-system
  interval: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nexus
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: nexus
  dependsOn:
    - name: k8s-app-aws-ebs-csi-driver
  path: .infra/flux/${cluster_name}/
  interval: 5m
  prune: true
  postBuild:
    substitute:
      cluster_name: ${cluster_name}
      aws_account_id: "${aws_account_id}"

```

In `./flux-cd/clusters/my-cluster-1/apps/kustomization.yaml`

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nexus.yaml
```

In `./flux-cd/clusters/my-cluster-1/apps.yaml`

```yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  path: ./clusters/my-cluster-1/apps/
  prune: true
  postBuild:
    substitute:
      cluster_name: my-cluster-1
      aws_account_id: "'0123456789000'"
      git_branch: master

```

In `./flux-cd/clusters/my-cluster-1/k8s-apps.yaml`

```yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: k8s-apps
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  path: ./apps/base/k8s-apps
  prune: true
  postBuild:
    substitute:
      cluster_name: my-cluster-1
      aws_account_id: "'0123456789000'"
      git_branch: master

```
---

### Steps to reproduce

See above

### Expected behavior

The variables are well substituted in the file `./flux-cd/apps/base/k8s-apps/k8s-app-aws-ebs-csi-driver.yaml`
But not in `./flux-cd/clusters/my-cluster-1/apps/nexus.yaml`

I don't understand why. The only difference between the two file are their location.

I have the same comportment for all files in `./flux-cd/clusters/my-cluster-1/apps/`.

All variables in files located in `./flux-cd/apps/base/k8s-apps/` are  well substituted.

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/21245565/221157621-f5ebade0-1558-48d6-9ad9-a3a1bf17e58a.png)

### OS / Distro

MacOS Darwin

### Flux version

0.40.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.25.6-eks-48e63af >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.30.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.30.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.25.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.34.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.32.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.35.2
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Git provider

Gerrit

### Container Registry provider

DockerHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by QuentinBtd** [comment]
> Have you found a solution to this? I have a similar problem but for me the variable substitution works like 1 out of 10 times. I literally just delete the file, reconcile the kustomisation and see if the variable was replaced or not and it works every now and then.

Hello,

I changed my way of doing things, I no longer do cascading substitutions like in the example. Now I  only substitute on one level. Where I have to substitute a variable in some kustomizations,  I use `substituteFrom` with values in a configMap (or a secret).


```yaml
   postBuild:
     substituteFrom:
       - kind: ConfigMap
         name: cluster-vars
```

**Comment by TheKangaroo** [comment]
Thanks for the quick reply.
Actually, I've just figured out what's wrong with my deployment when I read this issue https://github.com/fluxcd/flux2/issues/2360, and I think it might be your problem here too.
I completely missed the part about "Please note that Flux applies yaml recursively, so it will apply those in sub-directories" (https://github.com/fluxcd/flux2/issues/2360#issuecomment-1027036159).

As in your example above, I placed the kustomization in a subfolder of the cluster, and since kustomize does not include subfolders by default, I assumed that flux kustomization would ignore subfolders as well.

I can see from the annotations on my kustomization that every time the substitution works it is being applied by the correct flux kustomization, but every time it does not work it is being reconciled by the flux-system kustomization which does not have the substitution block.

**Comment by mgugino-pdig** [comment]
What I have found is if a Flux Kustomization points at a folder containing a k8s kustomization.yaml, you will not get the recursion problem.  This is confirmed by the source: https://github.com/fluxcd/pkg/blob/ef0f9554ec737f364132fdb2d06bc2293e630624/kustomize/kustomize_generator.go#L433-L449

**Comment by gecube** [comment]
**Triage summary (reproduced on Flux v2.8.8 / kustomize-controller v1.8.5):** there is no substitution bug here — the manifests under `./flux-cd/clusters/my-cluster-1/apps/` are applied by **two** Flux Kustomizations at once, and only one of them carries your `postBuild.substitute`. The cluster shows whichever parent reconciled last, which is why it looks random (and why @TheKangaroo saw it "work 1 out of 10 times").

### Root cause

The bootstrap `flux-system` Kustomization points at `./clusters/my-cluster-1`, which has **no `kustomization.yaml`**, so kustomize-controller generates one — the equivalent of `kustomize create --autodetect --recursive` ([FAQ](https://fluxcd.io/flux/faq/#can-i-use-repositories-with-plain-yamls)). While scanning, a subdirectory that has its own `kustomization.yaml` is added **as a resource** — it is *not* skipped: [`scanManifests`](https://github.com/fluxcd/pkg/blob/kustomize/v1.9.0/kustomize/kustomize_generator.go#L499-L519) (same logic in pkg/kustomize v0.13.1 used by kustomize-controller v0.34.0 from the report, and already noted by @provMichaelGugino above).

So the generated root build includes `clusters/my-cluster-1/apps/` → `nexus.yaml`, and `flux-system` — which has no `postBuild` — applies the `nexus` GitRepository/Kustomization with a literal `${cluster_name}`. Your `apps` Kustomization then applies the same two objects *with* substitution, and the two parents keep overwriting each other via server-side apply on every reconcile. Both stay `Ready=True` and no warning event is emitted, so the fight is invisible unless you inspect the `kustomize.toolkit.fluxcd.io/name` label.

`./flux-cd/apps/base/k8s-apps/` is *outside* the root Kustomization's path, so those objects have a single owner (`k8s-apps`) and substitution always works there — exactly matching the report.

### Repro

Same tree as in the report (OCI source instead of git, v1 APIs), watching the `nexus` Kustomization object:

```console
$ flux reconcile kustomization flux-system --with-source=false
$ kubectl get kustomization nexus -n flux-system \
    -o jsonpath='owner={.metadata.labels.kustomize\.toolkit\.fluxcd\.io/name}{"\n"}path={.spec.path}{"\n"}'
owner=flux-system
path=.infra/flux/${cluster_name}/     # ← literal, not substituted

$ flux reconcile kustomization apps --with-source=false
owner=apps
path=.infra/flux/my-cluster-1/        # ← substituted
```

…and back again, on every reconcile of either parent. @TheKangaroo's annotation observation is precisely this ownership flip.

### Fix (validated)

Commit an explicit `kustomization.yaml` at `clusters/my-cluster-1/` so the root Kustomization stops auto-descending — confirming what @provMichaelGugino wrote:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - apps.yaml
  - k8s-apps.yaml
```

With this in place, repeated reconciles of `flux-system` no longer touch `nexus`; it stays owned by `apps` with substituted values. One switchover caveat: if at that moment the objects happen to be labeled as owned by `flux-system`, its prune will delete them once and `apps` will recreate them on its next reconcile.

Equivalent alternative: keep the cluster directory free of nested manifest dirs, as in [flux2-kustomize-helm-example](https://github.com/fluxcd/flux2-kustomize-helm-example) (`clusters/<name>/` contains only the Flux Kustomization files; apps/infrastructure live outside).

### Suggestion

This can probably be closed as working-as-designed — same class as #2360. The recurring pain point is that the overlap is **silent**: both Kustomizations report Ready, and nothing is logged when a server-side apply takes over an object and flips its `kustomize.toolkit.fluxcd.io/name` label. If that sounds useful to maintainers, I can open a separate feature request (warning event on ownership-label takeover during apply) against kustomize-controller.

cc @matheuscscp
