### ISSUE TITLE
flux bootstrap git not completing on large repositories

### ISSUE THREAD

**Issue by gpl** [fluxcd/flux2#3661]
### Describe the bug

When attempting to use the following bootstrap command in a large repo, the command seems to never complete.  We think it's crashing internally; because it seems to be consistently pulling data from Git - but never completing.  

 flux bootstrap git --url=ssh://git@github.com/our/repo--branch=trunk --path=clusters/test --private-key-file=/path/to/our/deploy/key --context our-cluster --interval 20m --verbose

### Steps to reproduce

-

### Expected behavior

-

### OS / Distro

Ubuntu 22.04

### Flux version

v0.40.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.25.3 >=1.20.6-0
► checking controllers
✗ no controllers found in the 'flux-system' namespace with the label selector 'app.kubernetes.io/part-of=flux'
► checking crds
✗ no crds found with the label selector 'app.kubernetes.io/part-of=flux'
✗ check failed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
Flux is made for one specific purpose, to apply YAML to Kubernetes clusters, and YAML files are small. Typically we recommend bootstrapping Flux into a new repository, rather than into your app repo, and moving configs into the new repo (rather than dragging along all of your legacy commits and non-YAML content with you into the place where you're applying config to the cluster from.) This is my first advice, to get that out of the way. You will have a much better experience with Flux if you use it with smaller Git repos, or with a specific "config repo" that is just for YAML.

That being said, there are several `timeout` parameters that you can tune to see if it helps. The one thing that will probably not help, is passing `--timeout` directly to bootstrap git. This is the global context timeout parameter, it does not affect the definition of the `GitRepository` that Bootstrap produces in any way.

To accomplish this, you would need to "customize Flux resources" as explained here in the FAQ:
https://fluxcd.io/flux/installation/#customize-flux-manifests

The patch you need to apply to Flux is going to look like this one:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: # manifests generated during bootstrap
  - gotk-components.yaml
  - gotk-sync.yaml

patches: # customize the manifests during bootstrap
  - target:
      kind: GitRepository
      name: flux-system
    patch: |
      apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        timeout: 10m0s
```

and the idea is just to give this clone a little longer, because it is large and expectedly takes so long. The default is 5m.

I do not recommend you move ahead with this configuration, but if you have some operational requirement that the changes must come from this git repo, there are some other options to discuss. (You could pack the important parts for Flux in an OCI repo, and then pull them as an artifact which will again be much more efficient, because only YAML files and some metadata are downloaded.)
