### ISSUE TITLE
Helm hook resources with keep policy missing

### ISSUE THREAD

**Issue by tarioch** [fluxcd/flux2#3691]
### Describe the bug

While trying to upgrade the helm chart https://gitlab.com/ananace/charts/-/tree/master/charts/matrix-synapse I'm running into the issue as one of the configmaps in there which is used by a pre-install is missing afterwards (it's also needed afterwards). The resource looks like this

```yaml

# Source: matrix-synapse/templates/configuration-scripts.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-synapse-scripts
  labels:
    helm.sh/chart: matrix-synapse-3.2.1
    app.kubernetes.io/name: matrix-synapse
    app.kubernetes.io/instance: matrix-synapse
    app.kubernetes.io/version: "1.79.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
data:
  signing-key.sh: |
...

```

### Steps to reproduce

Try to upgrade the matrix-synapse helm chart from version 3.1.0 to 3.2.1 (maybe even a fresh installation might have this problem)

### Expected behavior

matrix-synapse-scripts configmap is still present while the chart runs

### OS / Distro

K3S v1.25.7+k3s1

### Flux version

flux: v0.41.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.25.7+k3s1 >=1.20.6-0
► checking controllers
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.30.2
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.23.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.33.0
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.28.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.28.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.32.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
