### ISSUE TITLE
Issue fetching HelmChart from Helm OCI ECR repository

### ISSUE THREAD

**Issue by heretogo** [fluxcd/flux2#3766]
### Describe the bug

I'm having issues matching a HelmChart to my semver expression and then fetching the resource from ECR.

### Steps to reproduce

I have the following resource objects in my fluxcd GitOps source repo:

### Helm OCI repository CRD
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: application-charts
  namespace: company
spec:
  type: oci
  provider: aws
  interval: 5m0s
  url: oci://account.dkr.ecr.region.amazonaws.com
```

### Helm chart CRD
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: application-charts
  namespace: company
spec:
  interval: 5m0s
  chart: application-charts
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: application-charts
  version: 'v4.*'
```

If I specify a range (version: v4.x ) I get the error below
```
chart pull error: failed to get chart version for remote reference: could not get tags for "application-charts": unable to locate any tags in provided repository: oci://account.dkr.ecr.us-region.amazonaws.com/application-charts
```

I have tried variants with the same result:
- `v4.*`
- `v4.0.*`
- `>= 4`
- `>= 4.*`

`flux get sources chart -A` gives the following output
```
company    	application-charts	v4.3.34 	False    	False	no artifact available for HelmRepository source 'application-charts'
```

If I specify the exact version it pulls correctly. I need to specify a range to automate deployments to a staging environment. Eventually I want flux to deploy according to a pre-release tagging convention; i.e. `v4.3.34-helm`.

### Expected behavior

Expected output is
```
pulled 'application-charts' chart with version '4.3.14'
```

### OS / Distro

macOS 12.6

### Flux version

v2.0.0-rc.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.23.16-eks-48e63af >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.31.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.35.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.33.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.36.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Git provider

GitHub

### Container Registry provider

ECR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Please try `version: 4.x`, using the `v` prefix is not a valid semver range.

**Comment by heretogo** [comment]
> Please try `version: 4.x`, using the `v` prefix is not a valid semver range.

Same issue:

```
{"level":"error","ts":"2023-04-19T18:22:36.606Z","msg":"Reconciler error","controller":"helmchart","controllerGroup":"source.toolkit.fluxcd.io","controllerKind":"HelmChart","HelmChart":{"name":"redacted","namespace":"redacted"},"namespace":"redacted","name":"redacted","reconcileID":"f1f2278e-4acf-4d5c-9eea-72b802404a0c","error":"chart pull error: failed to get chart version for remote reference: could not get tags for \"redacted\": unable to locate any tags in provided repository: oci://redacted.dkr.ecr.us-east-1.amazonaws.com/redacted"}
```

Is there anything that needs to be configured on ECR's end?

**Comment by stefanprodan** [comment]
I think you’ve used the v prefix when pushing the charts to ECR, which is not supported by Helm nor Flux.

**Comment by heretogo** [comment]
I just want to acknowledge that @stefanprodan's helped.

In ECR helm charts need to be tagged without the `v`.

**Comment by inistor** [comment]
Just to point out, for others in the same situation. It appears many are pushing tags with a `v` prefix (e.g. [Envoy Gateway](https://github.com/envoyproxy/gateway/issues/2940)), and this approach doesn't work with Flux. In Helm, though, they do (in spite of [a comment](https://github.com/fluxcd/flux2/issues/3766#issuecomment-1518644096) above); see [the Envoy Install Guide](https://gateway.envoyproxy.io/latest/install/install-helm/). 

To overcome this (not ideal, as it locks to a specific version), using an explicit version (no wildcards) works find. In the case of Envoy Gateway, I have:

```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway-release
  namespace: flux-system
spec:
  install:
    createNamespace: true
  interval: 1m
  targetNamespace: envoy-gateway
  storageNamespace: envoy-gateway
  chart:
    spec:
      chart: gateway-helm
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway-repo
      interval: 1m
      version: 'v1.1.0'
```

Which works as intended
