### ISSUE TITLE
"Error decoding from json" after upgrading to v2.0.0-rc.1

### ISSUE THREAD

**Issue by gandarez** [fluxcd/flux2#3775]
### Describe the bug

After running `flux bootstrap github` the kustomization fails to read previously created secrets. All secrets have been created using SOPS.

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 1m0s
  path: ./clusters/my-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

### Steps to reproduce

1. Install flux `v0.41.2`
2. Create some secrets with SOPS encryption
3. Update to flux `v2.0.0-rc.1`

### Expected behavior

It should keep reading secrets without errors.

### OS / Distro

k8s

### Flux version

v2.0.0-rc.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.25.6-gke.1000 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.32.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Additional context

```
Secret/api/my-secret validation error: error decoding from json: illegal base64 data at input byte 3
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandarez** [comment]
I realized it's not getting my `Kustomization` accordingly.

```shell
flux export kustomization flux-system
```

Returns:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2023-04-09T21:16:03.93343-03:00"
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/my-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

**Comment by somtochiama** [comment]
@gandarez  are you saying you have a kustomization yaml with sops decryption field set in git, but it is missing when you check the Kustomization in cluster?

**Comment by gandarez** [comment]
Exactly @somtochiama

**Comment by somtochiama** [comment]
okay. I will try to reproduce this but please cross check that the kustomization is applying the most recent git revision and that nothing changed in git.

**Comment by gandarez** [comment]
@somtochiama after upgrading from `v0.41.2` flux updated all components correctly with latest version and changed `apiVersion` to `v1` and removed `decryption` field from `gotk-sync.yaml`. Then I added it back but the resource never gets updated. I forced few times with `flux reconcile source git flux-system` and `flux reconcile kustomization flux-system` but never got success.

**Comment by somtochiama** [comment]
How did you upgrade? with `flux bootstrap`?

**Comment by gandarez** [comment]
Sure thing. I followed the instructions from [v2.0.0-rc.1](https://github.com/fluxcd/flux2/releases/tag/v2.0.0-rc.1).

**Comment by somtochiama** [comment]
It doesn't reconcile because the error from being unable to decrypt the secret prevents it from applying the commit. 
If you can afford the secret being recreated, you can remove the secret yaml from git so that it successfully applies the commit with the sops decryption field, and then add the secret yaml.
or IIRC, you can try editing the kustomization in-cluster to add the decryption field manually and then try to reconcile,

I will try to figure out why upgrading flux removed the decryption field. Thanks for reporting this

**Comment by somtochiama** [comment]
Oh I see the problem now. You shouldn't edit `gotk-*.yaml` files directly since they are overwritten when flux upgrades it.
Just re-read your comment and saw the decryption field is in `gotk-sync.yaml`

Please see the docs on [customizing flux manifests](https://fluxcd.io/flux/installation/#customize-flux-manifests) You should add patches to the `kustomization.yaml` file instead

**Comment by gandarez** [comment]
Oh got it @somtochiama thanks for the heads up. I've been trying since you replied in this thread with this kustomization:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- gotk-pvc.yaml

patches:
  - patch: |
      - op: add
        path: '/spec'
        value: 
          decryption:
            provider: sops
            secretRef:
              name: sops-gpg
    target:
      kind: Kustomization
      name: flux-system
```
But I'm getting another error. What am I missing?
```
✗ Kustomization/flux-system/flux-system dry-run failed, reason: Invalid, error: Kustomization.kustomize.toolkit.fluxcd.io "flux-system" is invalid: [spec.interval: Required value, spec.prune: Required value, spec.sourceRef: Required value]
```

**Comment by gandarez** [comment]
I managed it working by changing to
```yaml
patches:
  - patch: |
      apiVersion: v1
      kind: Kustomization
      metadata:
        name: flux-system
      spec:
        decryption:
          provider: sops
          secretRef:
            name: sops-gpg
    target:
      kind: Kustomization
      name: flux-system
```
