### ISSUE TITLE
Kustomization stuck unable to reconcile without traces

### ISSUE THREAD

**Issue by Maximebb** [fluxcd/flux2#3790]
### Describe the bug

On our production cluster, a kustomization manages about 200 individual resources spread across about 100 yaml files. This kustomization has been able to reconcile consistently over the past year or so. If I look at my average time to reconcile, it is at about 7s. I don't think this is a performance or kube api server issue.

At some point over the weekend, the kustomization stopped being able to reconcile and is now stuck at "reconciling in progress"
```
NAME    REVISION            SUSPENDED       READY         MESSAGE
app     app-branch/<hash>   False           Unknown       reconciliation in progress
```

The events are empty when running a `kubectl describe ks <app>`
```
Events:                       <none>
```

I bumped the log levels to `trace`, but I have absolutely no logs regarding this `app` kustomization. The only thing I can see is a logs traced twiced when restarting the pod.

```json
{
  "level": "error",
  "ts": "2023-04-11T18:03:56.223Z",
  "logger": "controller.kustomization",
  "msg": "Reconciler error",
  "reconciler group": "kustomize.toolkit.fluxcd.io",
  "reconciler kind": "Kustomization",
  "name": "app",
  "namespace": "flux-system",
  "error": "context canceled",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"
}
```

When I try to reconcile manually, I get the only hint as to why this is failing, and event then I think it's a client-side issue and red herring. I get this whether I run with default timeout, `--timeout 5m`, `--timeout 30m`, etc.
```
~$ flux reconcile ks app
► annotating Kustomization app in flux-system namespace
✔ Kustomization annotated
◎ waiting for Kustomization reconciliation
✗ client rate limiter Wait returned an error: context deadline exceeded
```
I went down the rabbit hole to figure out if the client-side throttling was because of a bad priority and fairness config, but it's all GKE defaults with proper `service-accounts` mapping.

Additional info:
`kubectl describe ks app -n flux-system`
```yaml
Name:         app
Namespace:    flux-system
Labels:       kustomize.toolkit.fluxcd.io/name=flux-system
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  reconcile.fluxcd.io/requestedAt: 2023-04-11T18:04:04.574798182Z
API Version:  kustomize.toolkit.fluxcd.io/v1beta2
Kind:         Kustomization
Metadata:
  <redacted>
Spec:
  Decryption:
    Provider:  sops
    Secret Ref:
      Name:  sops-gpg
  Force:     true
  Interval:  10m0s
  Path:      ./instances/prod
  Prune:     false
  Source Ref:
    Kind:   GitRepository
    Name:   app-repo
  Timeout:  5m0s
Status:
  Conditions:
    Last Transition Time:  2023-04-08T14:32:43Z
    Message:               reconciliation in progress
    Reason:                Progressing
    Status:                Unknown
    Type:                  Ready
  Inventory:
    Entries:
      <redacted>
  Last Applied Revision:      <redacted>
  Last Attempted Revision:    <redacted>
  Last Handled Reconcile At:  2022-08-08T14:06:20.437859-04:00
  Observed Generation:        41
Events:                       <none>
```

We have other kustomizations and helm releases all working on the same cluster. The repository in question hasn't changed at all at the time flux stopped being able to reconcile. If I use the same kustomization in another lab environment, I am able to get flux to reconcile it.

Any help with this is appreciated. I can't figure out next troubleshooting steps based on the doc only, none of the expected traces are there.

### Steps to reproduce

Not sure this is reproducible, seems like a typical use-case and it was working until randomly during the weekend.

1. Install flux
2. Create git repository resource, kustomization pointing to roughly 100 files with 200 resources
3. Flux reconcile the kustomization

### Expected behavior

Flux to reconcile the kustomization

### Screenshots and recordings

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/6494242/231269115-366d86e6-fd7b-41ee-a353-bd21dd64d8d4.png">

### OS / Distro

GKE

### Flux version

v0.38.2

### Flux check

► checking prerequisites
✗ flux 0.38.2 <2.0.0-rc.1 (new version is available, please upgrade)
✔ Kubernetes 1.24.9-gke.3200 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.22.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.26.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.24.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.25.5
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta1
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta1
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta1
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

Gitlab

### Container Registry provider

Google Artifact Registry

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Maximebb** [comment]
We've tried to delete the kustomization (with `prune: false`) and recreate it, but it's stuck without any applied revision.

**Comment by Maximebb** [comment]
Ok, before anyone tries to help too much, I've found our issue. A PVC was stuck at terminating, for some reason. Probably a CSI failure or someone manually deleted it without ensuring success. We fixed it.

I'll close the issue, but might be worth having more trace or debug logs to understand what it was trying to do. Presumably, flux was just waiting for an patch on a terminating resource, which would have led me to a resolution quicker. Food for thought.

**Comment by somtochiama** [comment]
Hey @Maximebb , Can you paste the status conditions on the Kustomization while it was stuck in the "reconciliation in progress" state?
 You can see them by running `k get ks <name> -oyaml`

**Comment by stefanprodan** [comment]
@somtochiama I suspect that `context canceled` comes from the force apply logic, we probably don’t wrap one of the select/delete/create errors, we must add the exact resource name that caused the timeout to the returned error. Can you please check `pkg/ssa` and see if we missed wraping `return err` anywhere?

**Comment by Maximebb** [comment]
I just gathered logs from yesterday, but I got nothing except the two logs when restarting the controller
```
~$ flux logs --kind=Kustomization --name=app -n flux-system --level=error
2023-04-11T14:03:56-04:00	{"level":"error","ts":"2023-04-11T18:03:56.222Z","logger":"controller.kustomization","msg":"Reconciler error","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"app","namespace":"flux-system","error":"context canceled","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
2023-04-11T14:03:56-04:00	{"level":"error","ts":"2023-04-11T18:03:56.223Z","logger":"controller.kustomization","msg":"Reconciler error","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"app","namespace":"flux-system","error":"context canceled","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```

For the status condition, it's in the original post, copied here for convenience:
```yaml
Name:         app
Namespace:    flux-system
Labels:       kustomize.toolkit.fluxcd.io/name=flux-system
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  reconcile.fluxcd.io/requestedAt: 2023-04-11T18:04:04.574798182Z
API Version:  kustomize.toolkit.fluxcd.io/v1beta2
Kind:         Kustomization
Metadata:
  <redacted>
Spec:
  Decryption:
    Provider:  sops
    Secret Ref:
      Name:  sops-gpg
  Force:     true
  Interval:  10m0s
  Path:      ./instances/prod
  Prune:     false
  Source Ref:
    Kind:   GitRepository
    Name:   app-repo
  Timeout:  5m0s
Status:
  Conditions:
    Last Transition Time:  2023-04-08T14:32:43Z
    Message:               reconciliation in progress
    Reason:                Progressing
    Status:                Unknown
    Type:                  Ready
  Inventory:
    Entries:
      <redacted>
  Last Applied Revision:      <redacted>
  Last Attempted Revision:    <redacted>
  Last Handled Reconcile At:  2022-08-08T14:06:20.437859-04:00
  Observed Generation:        41
Events:                       <none>
```
