### ISSUE TITLE
output the digest of the container image for further usage in flux push artifact command

### ISSUE THREAD

**Issue by developer-guy** [fluxcd/flux2#3852]
I've got an example of signing artifact pushed using `flux push artifact` command but to be able to do that I need to apply a workaround by using crane command, but we can add a new flag to output the digest to a file or stdout in `flux push artifact` command.

```YAML
 # Create OCI artifact with kubernetes manifests
      - name: Create OCI artifact
        id: create-oci-artifact
        run: |
          flux push artifact $OCI_REPO:$(git rev-parse --short HEAD) \
            --path="./k8s" \
            --source="$(git config --get remote.origin.url)" \
            --revision="$(git branch --show-current)/$(git rev-parse HEAD)"
      # Tag OCI artifact
      - name: Create OCI artifact tag
        run: |
          flux tag artifact $OCI_REPO:$(git rev-parse --short HEAD) --tag main
      # Install Crane
      - uses: imjasonh/setup-crane@v0.3

      # Install Cosign
      - uses: sigstore/cosign-installer@main

      - name: Get the digest of the OCI artifact
        id: crane
        run: |
# Here we are applying a workaround to find the digest, instead we can output the digest in `create-oci-artifact` step.
          DIGEST=$(crane digest $GHCR_REPO:$(git rev-parse --short HEAD)) 
          echo "DIGEST=$DIGEST" >> $GITHUB_OUTPUT

      # Cosign the OCI artifact
      - name: Sign the OCI artifact
        run: cosign sign $GHCR_REPO@${{ steps.crane.outputs.DIGEST }} -y
```

/cc @stefanprodan
