### ISSUE TITLE
flux check --pre net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by schmidp** [fluxcd/flux2#3865]
### Describe the bug

I have a freshly created cluster based on k3s and https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner.

When I run `flux check --pre` get the following error:

```
► checking prerequisites
✗ Kubernetes API call failed: Get "https://<ipv4>:6443/version": net/http: TLS handshake timeout
```

With the following content in `~/.kube/config
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <removed
    server: https://<IPv4>:6443
  name: cluster
contexts:
- context:
    cluster: cluster
    user: cluster
  name: cluster
current-context: cluster
kind: Config
preferences: {}
users:
- name: cluster
  user:
    client-certificate-data: <removed>
    client-key-data: <removed>
```

Kubeconfig is empty:
```
echo $KUBECONFIG

```

`kubectl` is able to connect:
```
kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.26.4+k3s1
```

### Steps to reproduce

1. Install k8s based on https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner
2. Store kubeconfig in `~/.kube/config`
3. Run `flux check --pre`

### Expected behavior

flux check is able to connect to the k3s API.

### OS / Distro

macOS 13.3.1 (a) (22E772610a)

### Flux version

v2.0.0-rc.2

### Flux check

► checking prerequisites
✗ Kubernetes API call failed: Get "https://<ipv4>:6443/version": net/http: TLS handshake timeout

### Git provider

GitLab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
