### ISSUE TITLE
ClusterRoleBinding/crd-controller-flux-system apply failed to patch clusterrolebindings when using flux install

### ISSUE THREAD

**Issue by JustinYeoh93** [fluxcd/flux2#3871]
### Describe the bug

Flux is unable to patch clusterrolebindings of Flux through Kustomization.

The below is what I got when I apply a set of manifests to manage flux.

```
flux-system   3s    False   ClusterRoleBinding/crd-controller-flux-system apply failed, error: clusterrolebindings.rbac.authorization.k8s.io "crd-controller-flux-system" is forbidden: User "system:serviceaccount:flux-system:kustomize-controller" cannot patch resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope...
sync          5s   True    Applied revision: some-new-version@some-new-tag
```

### Steps to reproduce

1. Install latest flux cli
2. Install flux using the cli `flux install`
3. Export the manifest using `flux install --export > flux-system.yaml`
4. Commit the file remotely
5. Use kubectl to apply a Git Repository and Kustomization to track the generated `flux-system.yaml` file

### Expected behavior

Flux to be able to patch clusterrolebinding.

### OS / Distro

AWS Linux 

### Flux version

v2.0.0-rc.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.12-eks-ec5523e >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.32.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

GitLab

### Additional context

I'd like to manage flux using flux. 

So, I've exported the flux using `flux install --export > flux-system.yaml` and store it in a remote repository.
I install flux using `flux install` and then applied an initial set of manifest to track the flux manifest generated above.

The final result looks like below
**Initial manifests**
```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: deployments-repo
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: deployments-repo
  url: some-gitlab-url
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sync
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: deployments-repo
  path: "./main-cluster"
  prune: true
  timeout: 1m

```
The layout I have is as below

**Repository layout**
```
| - main-cluster
|   | - sync.yaml
|   | - kustomization.yaml
| - sub-cluster
|   | - sync.yaml
|   | - kustomization.yaml
| - system
|   | - base
|        | - flux-system.yaml   <- manifest generated by flux install
|        | - kustomization.yaml
|   | - feature
|        | - kustomization.yaml
```

```
# main-cluster/sync.yaml
# Use flux to manage flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: deployments-repo
  path: "./system/feature"
  prune: true
  timeout: 1m
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
