### ISSUE TITLE
Variable substring replacement broken on RC2

### ISSUE THREAD

**Issue by GeorgeGedox** [fluxcd/flux2#3884]
### Describe the bug

I just upgraded flux to rc2 and I'm using variable substring replacement with certmanager to replace dots in my domain name with hyphens like so

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-production"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
```

Problem is that during reconciliation flux kustomization throws this instead of just working as expected
```
Certificate/networking/${SECRET_DOMAIN/./-}-production dry-run failed, error: invalid resource name "${SECRET_DOMAIN/./-}-production": [may not contain '/']
```

### Steps to reproduce

1. Use substring replacement on a variable for creating a new resource `${var/substring/replacement`
2. Flux reconcile

### Expected behavior

New resource should be created using the value it was given and with the replacements done

### OS / Distro

Debian 11

### Flux version

v2.0.0-rc.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.27.1+k3s1 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.32.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.33.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.27.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.2
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
