### ISSUE TITLE
Helm kustomize postRenderers have no effect

### ISSUE THREAD

**Issue by antoineco** [fluxcd/flux2#3913]
### Describe the bug

Neither the `patches` nor the `images` kustomize postRenderers seem to have any effect in Flux v1.0.0-rc.3.

While trying to update the image used inside a Deployment, none of the methods below cause a rewrite of the container's image.

### Steps to reproduce

<details><summary><code>kustomization.yaml</code></summary>
<p>

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secrets-injector
resources:
- secrets-injector.yaml
```

</p>
</details> 

<details><summary><code>secrets-injector.yaml</code> - patches variant</summary>
<p>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: secrets-injector
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 1password
spec:
  interval: 1h
  url: https://1password.github.io/connect-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-injector
spec:
  interval: 1h
  chart:
    spec:
      chart: secrets-injector
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: 1password
  postRenderers:
  - kustomize:
      patches:
      # Helm chart update pending. Fixes 1Password/kubernetes-secrets-injector#24
      - target:
          group: apps
          kind: Deployment
          name: secrets-injector
        patch: |
          - op: replace
            path: /spec/template/spec/containers/0/image
            value: 1password/kubernetes-secrets-injector:1.0.1
```

</p>
</details> 

<details><summary><code>secrets-injector.yaml</code> - images variant</summary>
<p>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: secrets-injector
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 1password
spec:
  interval: 1h
  url: https://1password.github.io/connect-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-injector
spec:
  interval: 1h
  chart:
    spec:
      chart: secrets-injector
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: 1password
  postRenderers:
  - kustomize:
      images:
      # Helm chart update pending. Fixes 1Password/kubernetes-secrets-injector#24
      - name: 1password/kubernetes-secrets-injector
        newName: 1password/kubernetes-secrets-injector
        newTag: 1.0.1
```

</p>
</details>

The image tag remains untouched:

```console
$ kubectl -n secrets-injector get deployment secrets-injector -o jsonpath='{.spec.template.spec.containers[0].image}'
1password/kubernetes-secrets-injector:1.0.0
```

### Expected behavior

After deploying the chart, I'm expecting the image tag to be updated.

```console
$ kubectl -n secrets-injector get deployment secrets-injector -o jsonpath='{.spec.template.spec.containers[0].image}'
1password/kubernetes-secrets-injector:1.0.1
```

### OS / Distro

N/A

### Flux version

v2.0.0-rc.3

### Flux check

► checking prerequisites
✔ Kubernetes 1.25.8-gke.500 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.33.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.3
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.3
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.3
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
