### ISSUE TITLE
Kustomization controller has deleted flux-system namespace

### ISSUE THREAD

**Issue by lzecca78** [fluxcd/flux2#3949]
### Describe the bug

I have the following kustomization crd :

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: epersonam-develop
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: example
  path: "./manifests/example/develop"
  prune: true
  timeout: 1m
  ```
  
  Everything was working as expected. For a new need I've added in the `kustomization.yaml` referenced by the GitRepository a `Namespace` resource like this one:
  
  ```yaml
  apiVersion: v1
  kind: Namespace
  metadata:
     name: develop-test
  ```
  and in the main `kustomization.yaml`, adding the resource in the resources array: 
  
  ```
  resources:
  ....
  - ns.yml
  ```
  
  testing locally with `kustomize build` the namespace was in the built output, as expected
  
  
  When I pushed these chages to the repo, kustomize was triggered, but no new namespace was created. No clear why.
  Analyzing the kustomize resource the Inventory in the `Status.Inventory` was like this:
  
  ```yaml
Status:
  Conditions:
    Last Transition Time:  2023-06-01T16:16:28Z
    Message:               Applied revision: feat/refactoring-helmcharts@sha1:cf661a9ac199611dc05c3f17904ef7db2a06789f
    Observed Generation:   1
    Reason:                ReconciliationSucceeded
    Status:                True
    Type:                  Ready
  Inventory:
    Entries:
      Id:                   _flux-system__Namespace
      V:                    v1
      Id:                   flux-system_example-values-ct7cdk67h4__ConfigMap
      V:                    v1
      Id:                   flux-system_example-develop-new_helm.toolkit.fluxcd.io_HelmRelease
      V:                    v2beta1
      Id:                   flux-system_example-policy-develop_image.toolkit.fluxcd.io_ImagePolicy
      V:                    v1beta2
      Id:                   flux-system_example-develop_image.toolkit.fluxcd.io_ImageRepository
      V:                    v1beta2
      Id:                   flux-system_example-helm-manifests-develop_image.toolkit.fluxcd.io_ImageUpdateAutomation
      V:                    v1beta1
      Id:                   flux-system_example-develop_kustomize.toolkit.fluxcd.io_Kustomization
      V:                    v1beta2
      Id:                   flux-system_example-helm-manifests-refactoring-helmcharts_source.toolkit.fluxcd.io_GitRepository
      V:                    v1beta2
      Id:                   flux-system_example-generic_source.toolkit.fluxcd.io_HelmRepository
      V:                    v1beta2
```
As you can see  in the entry referenced by Namespace, no name is set , but just `_flux-system__Namespace`.
Because the namespace added wasn't created, what i did, was to remove the namespace resource from kustomize. (the Namespace with `metadata.name` = `develop-test`).
Once I pushed the commit, kustomize was triggered, but what it did, was totally unexpected: it totally deleted the  `flux-system` namespace (with several issues because there were a lot of finalizers of flux resources that didn't allow to accomplish that), but the `flux-system` namespace manifest even wasn't in the kustomization.yaml.

  

### Steps to reproduce

Install flux
add a kustomization crd referring a GitRepository
add to the kustomization.yaml a namespace manifests

### Expected behavior

When I add a namespace manifest to the kustomization.yaml, I expect that the namespace referenced in the kustomize, is created, but even more important, if I remove it from kustomize, is not deleted another namespace (`flux-system`)

### OS / Distro

Amazon Linux 2 5.4.238-148.346.amzn2.x86_64 

### Flux version

flux: v0.41.1

### Flux check

flux check
► checking prerequisites
✗ flux 0.41.1 <2.0.0-rc.5 (new version is available, please upgrade)
✔ Kubernetes 1.23.17-eks-0a21954 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.31.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.31.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.26.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.35.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.33.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.36.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Git provider

Bitbucket

### Container Registry provider

aws ecr

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lzecca78** [comment]
@stefanprodan thanks for your reply, but  I don't understand.
 In the example you've referenced, there is also a namespace manifest very similar to the one I did: https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/apps/base/podinfo/namespace.yaml. 
As I said the problem was adding to the `kustomization.yaml` (that was already there) the new namespace manifest.

I don't understand why:
1. after adding it, even if it was in the `Inventory` of the Kustomize crd,  it was not created (`kubectl get namespace` there wasn't any new `develop-test` namespace)
2. after removing the namespace resource (because no new namespace was created), the flux kustomize controller have deleted the `flux-system` namespace, even if the namespace manifest I removed was the manifest with `metadata.name` `develop-test`) 

Everything was working unless I added/removed a new namespace (totally unrelated to the `flux-system` namespace), which is something that usually kustomize `vanilla` handles normally.
If I add/remove a manifest that contains a namespace called `develop-test`, I expect that flux kustomize  controller (that under the hood executes kustomize eventually) adds/removes that exact namespace, not the `flux-system` one.
Is this a bug or a normal behavior?

**Comment by lzecca78** [comment]
As far as I understood, the problem starts when the Kustomization CRD is created in a namespace while the namespace referenced in kustomization.yaml has another name.
I try to explain this:

1. the Kustomization CRD in my case was created in flux-system namespace (as `metadata.namespace` field is `flux-system`) 
2. the manifest resource added in the kustomization.yaml has a different name:

```yaml
apiVersion: v1
kind: Namespace
metadata:
   name: develop-test
```

When I've pushed the new change to the repo, the kustomize crd has detected the changes but didn't create the namespace specified (very weird, because locally in the `kustomize build` output, the namespace was there).
As I've described previously in the Inventory of the flux Kustomization CRD, the namespace was there, even though the namespace wasn't created:

```yaml
Status:
Conditions:
  Last Transition Time:  2023-06-01T16:16:28Z
  Message:               Applied revision: feat/refactoring-helmcharts@sha1:cf661a9ac199611dc05c3f17904ef7db2a06789f
  Observed Generation:   1
  Reason:                ReconciliationSucceeded
  Status:                True
  Type:                  Ready
Inventory:
  Entries:
    Id:                   _flux-system__Namespace
    V:                    v1
    Id:                   flux-system_example-values-ct7cdk67h4__ConfigMap
    V:                    v1

```
    
    
Once I've removed the `develop-test` namespace manifest from the kustomization.yaml  and pushed it to git, the kustomize controller has deleted the `flux-system` namespace.
    Why did the kustomize controller delete a totally different namespace when I removed a manifest that was declaring something different?
    Why didn't the kustomize controller create the new namespace when I added it to kustomization.yaml?
    
   Is this related with the namespace in which the Kustomization flux CRD was created? 
   
   Is there any constraint that doesn't allow to add/remove namespace resources when Kustomization CRD are used?
   
   Thanks in advance for any help,
