### ISSUE TITLE
Reconciler error failed to parse invalid numeric value '' 

### ISSUE THREAD

**Issue by nguyenlinh1999** [fluxcd/flux2#3962]
### Describe the bug

hi everyone. i have using fluxcd for gitops. i using Image Update Automations for auto update image. i have issue when i create Imagepolicy Resource. before it work for me. but today it have exception
please help me!

### Steps to reproduce

this is my manifest!

```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: example-repo
  namespace: flux-system
spec:
  interval: 1m0s
  image: gitlab-registry-repo
  secretRef:
    name: gitlab-secret
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: example-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: example-repo
  filterTags:
    pattern: '^test-[a-fA-F0-9]+-(?P.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
```

### Expected behavior

and new image my build have tag: test-ff28ff32-1671684624

### OS / Distro

Ubuntu-20.04

### Flux version

0.40.1

### Flux check

► checking prerequisites
✗ flux 0.40.1 <2.0.0-rc.5 (new version is available, please upgrade)
✔ Kubernetes 1.21.14-eks-0a21954 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.14.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.11.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.13.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.15.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.3
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta1
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta1
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta1
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

Gitlab

### Container Registry provider

Gitlab container registry

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nguyenlinh1999** [comment]
> 1671684624

hi @darkowlzz. thanks your reply
my docker image have tag: test-ff28ff32-1671684624
$ts => 1671684624 ('^test-[a-fA-F0-9]+-(?P.*)')
this policy it work before. but today it not work.
i don't have update policy or reconfig docker image tag builder

**Comment by nguyenlinh1999** [comment]
> 

thanks you so much! @darkowlzz 
i tried ^test-[a-fA-F0-9]+-(?P<ts>[0-9]+). and it work for me.

**Comment by nguyenlinh1999** [comment]
> It may be that one of the newly created tags contain non-numeric values at the end of the pattern and is being selected by the capture group for numerical sorting. Using `?P<ts>[0-9]+` would make sure only the tags that have numbers at that position get selected.

**Comment by nguyenlinh1999** [comment]
But i don't know.!
before i using pattern: '^test-[a-fA-F0-9]+-(?P<ts>.*)'. it work for many project. and now it's working for some projects

**Comment by 0xStarcat** [comment]
I think I found a reproducible example of this that has given me some insight which I hope helps the maintainers in solving this. It seems like the issue is isolated to the behavior of `policy.numerical` and its handling of capture groups that are _not_ numerical.

I received the error `failed to parse invalid numeric value 'rc'` with the following configuration, which was resolved when i changed to `policy.semver`:

```yaml
# failed in extracting rc2024.03.13.0-12345 or v2024.03.13.0-12345
  filterTags:
    pattern: (^rc|^v)(?P<year>.*)\.(?P<month>.*)\.(?P<day>.*)\.(?P<patch>.*)-(?P<job_id>.*) 
    extract: '$job_id'
  policy:
    numerical:
      order: asc
```

versus successful semver:

```yaml
# succeeds in extracting rc2024.03.13.0-12345 or v2024.03.13.0-12345
  filterTags:
    pattern: (^rc|^v)(?P<year>.*)\.(?P<month>.*)\.(?P<day>.*)\.(?P<patch>.*)-(?P<job_id>.*) 
    extract: 0.0.$job_id
  policy:
    semver:
      range: ">=0.0.0"
```
