### ISSUE TITLE
Unable to create chart from Gitlab Helm repo using urlencoded path

### ISSUE THREAD

**Issue by greenmaid** [fluxcd/flux2#3972]
### Describe the bug

Hello,

Flux has trouble downloading chart from Helm repository hosted in Gitlab.

Workaround is it use numerical Gitlab project ID when possible.

### Steps to reproduce

Using following config:

helmrepo.yaml
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: os-image-server
  namespace: os-image-server
spec:
  interval: 1h0m0s
  provider: generic
  timeout: 1m0s
  url: https://gitlab.com/api/v4/projects/sylva-projects%2Fsylva-elements%2Fhelm-charts%2Fos-image-server/packages/helm/devel
  
  # url: https://gitlab.com/api/v4/projects/46289097/packages/helm/devel
  # is a workaround

```

helmrelease.yaml
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: os-image-server
  namespace: os-image-server
spec:
  chart:
    spec:
      chart: os-image-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: os-image-server
      version: 0.0.0-first-version
  install:
    createNamespace: true
    remediation:
      remediateLastFailure: false
      retries: 2
  interval: 15m0s
  releaseName: os-image-server
  targetNamespace: os-images
```

Apply config 
```
kubectl apply -f helmrelease.yaml -f helmrepo.yaml
```

Helmchart is failing:
```
$ flux get all -A
NAMESPACE       NAME                            REVISION        SUSPENDED       READY   MESSAGE                                     
os-image-server helmrepository/os-image-server  sha256:9ca845c6 False           True    stored artifact: revision 'sha256:9ca845c6'

NAMESPACE       NAME                                            REVISION        SUSPENDED       READY   MESSAGE                                                                                                                                                                                                                                                          
os-image-server helmchart/os-image-server-os-image-server                       False           False   chart pull error: failed to download chart for remote reference: failed to fetch https://gitlab.com/api/v4/projects/sylva-projects/sylva-elements/helm-charts/os-image-server/packages/helm/devel/charts/os-image-server-0.0.0-first-version.tgz : 404 Not Found

NAMESPACE       NAME                            REVISION        SUSPENDED       READY   MESSAGE                                                                  
os-image-server helmrelease/os-image-server                     False           False   HelmChart 'os-image-server/os-image-server-os-image-server' is not ready
```

### Expected behavior

 I expect the helmchart to pas downloaded successfully and helmrelease to be installed 

### Screenshots and recordings

_No response_

### OS / Distro

WSL Ubuntu 22.04

### Flux version

v0.41.2

### Flux check

$ flux check
► checking prerequisites
✗ flux 0.41.2 <2.0.0-rc.5 (new version is available, please upgrade)
✔ Kubernetes 1.25.3 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.31.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.35.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.33.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.36.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Git provider

_No response_

### Container Registry provider

_No response_

### Additional context

Probably related to https://github.com/fluxcd/flux2/issues/3869

The issue seems to be in the processing of helm repo URL containing urlencoded %2F as gitlab product ID. This project ID must not be decoded:

```
$ curl https://gitlab.com/api/v4/projects/sylva-projects/sylva-elements/helm-charts/os-image-server/packages/hel
m/devel/charts/os-image-server-0.0.0-first-version.tgz
{"error":"404 Not Found"}⏎

$ curl https://gitlab.com/api/v4/projects/sylva-projects%2Fsylva-elements%2Fhelm-charts%2Fos-image-server/package
s/helm/devel/charts/os-image-server-0.0.0-first-version.tgz -o mychart.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5262  100  5262    0     0  17717      0 --:--:-- --:--:-- --:--:-- 17717
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
