### ISSUE TITLE
flux-system namespace continuously configured in OpenShift 4.11

### ISSUE THREAD

**Issue by sastorsl** [fluxcd/flux2#3995]
### Describe the bug

Managing fluxcd with flux has since OpenShift 4.11 introduced a continuous configuration / reconcile of the `flux-system` namespace.

https://docs.openshift.com/container-platform/4.11/authentication/understanding-and-managing-pod-security-admission.html

When flux reconciles it sets labels for pod-security, then OpenShift swiftly overwrites.

```diff
18,19c18,19
<     pod-security.kubernetes.io/warn: privileged
<     pod-security.kubernetes.io/warn-version: v1.24
---
>     pod-security.kubernetes.io/warn: restricted
>     pod-security.kubernetes.io/warn-version: latest
```

Output from the customize controller (slack)

```
kustomization/flux-system.flux-system
Namespace/flux-system configured
revision
os-sandbox@sha1:320c66d661ce313479a698f29d2d93a0f02314fa
```

### Steps to reproduce

1. Configure gotk-components with `flux install --export --components-extra="image-reflector-controller,image-automation-controller" > gotk-components.yaml`
2. Push changes

### Expected behavior

Namespace not being continuously configured.

### Screenshots and recordings

PS! Present in both versions `0.x` and `2.x`.

### OS / Distro

OpenShift 4.11

### Flux version

v2.0.0-rc.5

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.12+ceaf338 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.34.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.34.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.28.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.4
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.4
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.5
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

N/A

### Container Registry provider

N/A

### Additional context

It's not a **bug** pr se, but I should be managed.
It is also good to bring this to the attention of the user base.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
You can create a patch for bootstrap and set the labels like OpenShift wants them.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: flux-system
        labels:
           pod-security.kubernetes.io/warn: privileged
           pod-security.kubernetes.io/warn-version: v1.24  
    target:
      kind: Namespace
```

Please let me know if this works, I'll add it to https://fluxcd.io/flux/cheatsheets/bootstrap/#openshift-compatibility

**Comment by sastorsl** [comment]
Actually, patching the Namespace resource by **removing** the labels from the flux definition resolved this.
Added benefit is that one does not need to adapt to changes in OpenShift going forward.

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  # <spec-details-removed>
  patches:
    # OpenShift will overwrite these Namespace labels
    # Remove them from the flux definition and leave them to openshift.
    - target:
        kind: Namespace
        labelSelector: app.kubernetes.io/part-of=flux
      patch: |-
        - op: remove
          path: /metadata/labels/pod-security.kubernetes.io~1warn
        - op: remove
          path: /metadata/labels/pod-security.kubernetes.io~1warn-version
```

I could add that we also patch to remove the `seccompProfile`, but I'm leaving that out to keep this issue clean.

Perhaps this could be added to the docs under https://fluxcd.io/flux/use-cases/openshift/
