### ISSUE TITLE
Missing metric for Healthy condition

### ISSUE THREAD

**Issue by abrenk** [fluxcd/flux2#3999]
After adding a [health check for a Flux Kustomization](https://fluxcd.io/flux/components/kustomize/kustomization/#health-checks) I had hoped to get a new metric with `type="Healthy"` the same as `type="Ready"` is already provided and described in the [Monitoring with Prometheus](https://fluxcd.io/flux/guides/monitoring/#metrics) guide:

```
gotk_reconcile_condition{kind, name, namespace, type="Ready", status="True"} # does exist
gotk_reconcile_condition{kind, name, namespace, type="Healthy", status="True"} # does not exist
```

The Kustomization resource status does have this information:
```
status:
  conditions:
  - lastTransitionTime: "2023-06-22T07:20:28Z"
    message: 'Applied revision: main/23ef440ded8af1586c8402a658537cd815a16132'
    observedGeneration: 74
    reason: ReconciliationSucceeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-06-22T07:20:28Z"
    message: Health check passed in 140.305402ms
    observedGeneration: 74
    reason: Succeeded
    status: "True"
    type: Healthy
```

Is it possible to add this metric?
