### ISSUE TITLE
Kustomization patch doesn't update helmrelease

### ISSUE THREAD

**Issue by emily-zall** [fluxcd/flux2#4019]
### Describe the bug

The original helmrelease has version: "6.12.3". I have a Kustomization for one environment that patches the version to 6.20.3. The Kustomization reconciles but the helmrelease still shows version 6.12.3. I see no errors or warnings. Maybe this is an order of operations thing but the order looks right to me.

# /Users/emilyzall/repos/config/applications/external-dns/azure/kustomization.yaml
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - components.yaml
```
# components.yaml
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    simbachain.com/chartLink: |-
      https://github.com/helm/charts/tree/master/stable/external-dns
  name: ${release}-external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami.external-dns
      version: "6.12.3"
  install:
    remediation:
      retries: -1
  interval: 5m0s
  releaseName: ${release}-external-dns
  upgrade:
    remediation:
      retries: -1
<<snip>>
```
And
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kongtest-simbachain-com-external-dns
  namespace: external-dns
spec:
  interval: 1m0s
  path: ./applications/external-dns/azure
  postBuild:
    substitute:
      CLUSTER_NAME: ${CLUSTER_NAME}
      domain: kongtest.simbachain.com
      release: kongtest-simbachain-com
  prune: true
  sourceRef:
    kind: GitRepository
    name: applications
    namespace: flux-system
  patches:
    - target:
        kind: HelmRelease
        name: ${CLUSTER_NAME}-simbachain-com-external-dns
        namespace: external-dns
      patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: ${CLUSTER_NAME}-simbachain-com-external-dns
          namespace: external-dns
        spec:
          chart:
            spec:
              version: "6.20.3"
  targetNamespace: external-dns
  validation: client
```

### Steps to reproduce

Setup flux with the files above.

### Expected behavior

Helm release is patched to use version 6.20.3

### OS / Distro

Mac 12.6.6

### Flux version

v2.0.0-rc.5

### Flux check

emilyzall@Emilys-MBP config % flux check
► checking prerequisites
✔ Kubernetes 1.25.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.30.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.30.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.25.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.34.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.32.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.35.2
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Additional context

Looks like CLUSTER_NAME resolves correctly.

```
emilyzall@Emilys-MBP config % kubectl describe helmreleases -n external-dns kongtest-simbachain-com-external-dns
Name:         kongtest-simbachain-com-external-dns
```
# From the Kustomization
```
  Patches:
    Patch:  apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kongtest-us1-simbachain-com-external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      version: "6.20.3"
```
I don't see any warnings or errors
```
flux logs --all-namespaces --level=error --since 10m
kubectl logs kustomize-controller-676c75cf7f-47d2h -n flux-system --since=30m | grep -iE "error|warn|fail"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
