### ISSUE TITLE
Can't get a patch file to contain multiple patches?

### ISSUE THREAD

**Issue by belkevglaz** [fluxcd/flux2#4030]
### Describe the bug

Inline patches in kustomization.yaml allow to define multiple patches. At the same time, the same patches in a separate file will get errors.

Reconcile error
```
flux reconcile kustomization apps-base-gitrepository --with-source 
► annotating GitRepository flux-system in flux-system namespace
✔ GitRepository annotated
◎ waiting for GitRepository reconciliation
✔ fetched revision master@sha1:629fcf2c850c838d32eb114720b6750b9c863f88
► annotating Kustomization apps-base-gitrepository in flux-system namespace
✔ Kustomization annotated
◎ waiting for Kustomization reconciliation
✗ Kustomization reconciliation failed: kustomize build failed: trouble configuring builtin PatchTransformer with config: `
path: helmreleases-patch.yaml
`: unable to parse SM or JSON patch from [---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-one
  namespace: default
spec:
  values:
    app:
      replicaCount: 2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-two
  namespace: default
spec:
  values:
    app:
      replicaCount: 2]
```

### Steps to reproduce

`kustomizaion.yaml` with inline patches that workin well.
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/app-one
  - ../base/app-two
patches:
 - target:
     kind: HelmRelease
     name: app-one
   patch: |-
       apiVersion: helm.toolkit.fluxcd.io/v2beta1
       kind: HelmRelease
       metadata:
         name: app-one
       spec:
         values:
           app:
             replicaCount: 2
 - target:
     kind: HelmRelease
     name: app-two
   patch: |-
     apiVersion: helm.toolkit.fluxcd.io/v2beta1
     kind: HelmRelease
     metadata:
       name: app-two
     spec:
       values:
         app:
           replicaCount: 2
```

Second option wtih `kustomization.yaml` and `patch.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/app-one
  - ../base/app-two
patches:
  - path: patch.yaml
 ```
 patch.yaml
 ```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-one
  namespace: default
spec:
  values:
    app:
      replicaCount: 2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-two
  namespace: default
spec:
  values:
    app:
      replicaCount: 2
 ```

### Expected behavior

To be able to configure multiple patches in a patch file.

### OS / Distro

Ubuntu 23.04

### Flux version

flux: v2.0.0-rc.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.8 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.32.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.32.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.27.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

GitLab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
This is not supported by https://github.com/kubernetes-sigs/kustomize

**Comment by grrttedwards** [comment]
Just FYI https://github.com/kubernetes-sigs/kustomize/issues/5049

So this feature is now possible on flux 1.2.0+ ? 
https://github.com/fluxcd/kustomize-controller/blob/main/CHANGELOG.md#120

**Comment by stefanprodan** [comment]
Yes it should if that PR is included in Kustomize v.5.3. If it works locally by running `kustomize build` then it will also work with Flux as we use the same code as the kustomize CLI.

**Comment by manicole** [comment]
Hi, I tried using the aforementioned feature, without success ...
@stefanprodan could you please help ?

My Kustomization is the following, I try to patch a whole Secret file with another (my Secret is encrypted by SOPS, thus I can't patch just one line of it):
```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
[...]
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: /apps
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
  - path: apps-patch_enc.yaml
    target:
      kind: Secret
      name: "*-secrets_enc.yaml"
```

I get the following error :
`Kustomization/flux-system/apps dry-run failed: failed to create typed patch object (flux-system/apps; kustomize.toolkit.fluxcd.io/v1, Kind=Kustomization): .spec.patches[0].path: field not declared in schema`

Any clue ? Thanks a lot
