### ISSUE TITLE
Flux Action Token required for Github Enterprise users

### ISSUE THREAD

**Issue by ebini** [fluxcd/flux2#4060]
### Describe the bug

There was an update in the actions.yaml

https://github.com/fluxcd/flux2/commit/6f94ec728f7faedf2fbe7865b227967a468f1bbd

We are using Github Enterprise. With our Enterprise Runner Token we cannot access the Standard Github.
So we need the token, otherwise we cannot connect and now get  401 Unauthorized.

### Steps to reproduce

use actions pipeline on Github Enterprises
```
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
        with:
          token: ${{ secrets.MY_PERSONAL_TOKEN }}
```
### Expected behavior

Connect to Github with my personal Token

still working with
```
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@v2.0.0
        with:
          token: ${{ secrets.MY_PERSONAL_TOKEN }}
```

### OS / Distro

ubuntu (enterprise) runner

### Flux version

changed in main branch

### Flux check

N/A

### Git provider

GitHub Enterprise

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
