### ISSUE TITLE
Flux2 does not build with Kustomize due to MalformedYAMLError

### ISSUE THREAD

**Issue by argogitops** [fluxcd/flux2#4127]
### Describe the bug

Trying to build flux with kustomize fails due to MalformedYAMLError

### Steps to reproduce

1. Create a kustomize.yaml like so:
   ```
    apiVersion: kustomize.config.k8s.io/v1beta1
    bases:
      - https://github.com/fluxcd/flux2/tree/v2.0.1/manifests/install
    kind: Kustomization
   ```
2. run `kustomize build .`
3. see the following: 
    > Error: accumulating resources: accumulating resources from 'https://github.com/fluxcd/flux2/tree/v2.0.1/manifests/install': MalformedYAMLError: yaml: line 202: mapping values are not allowed in this context in File: https://github.com/fluxcd/flux2/tree/v2.0.1/manifests/install

### Expected behavior

should build

### OS / Distro

MacOS 12.3.1

### Flux version

2.0.1

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
The URL is wrong, should be:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/fluxcd/flux2/manifests/install?ref=v2.0.1
```

Or to make it faster:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/fluxcd/flux2/releases/download/v2.0.1/install.yaml
```
