### ISSUE TITLE
Failed to verify integrity of artifact: artifact has no digest

### ISSUE THREAD

**Issue by clrxbl** [fluxcd/flux2#4129]
### Describe the bug

Ever since updating from Flux 0.41 to 2.0.1, I've been getting these messages sent to my Slack/Discord webhooks everytime it finds and stores a new commit artifact:

```
gitrepository/flux-system.flux-system
failed to verify integrity of artifact: artifact has no digest
```

Is there a reason why this shows up? It seems to show up across 6 different Kubernetes clusters, all upgraded from 0.4x versions to 2.0.1.

### Steps to reproduce

1. Install Flux
2. Add Slack or Discord webhook notifications
3. Add a GitRepository
4. Push to said GitRepository and wait until Flux sees it

### Expected behavior

No integrity message shown.

### OS / Distro

N/A

### Flux version

2.0.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.27.4+k3s1 >=1.24.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.35.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.35.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.29.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

GitLab (self-hosted), GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
Any chance your source-controller instance is backed by a Persistent Volume?

**Comment by clrxbl** [comment]
> What `apiVersion` is your `GitRepository` object set to?

```
API Version:  source.toolkit.fluxcd.io/v1
```

**Comment by somtochiama** [comment]
Can you post the status of the `GitRepository` object? esp `status.artifact`?

**Comment by stefanprodan** [comment]
@clrxbl what you posted is from the cluster right? Can you post here the YAML from Git `gotk-sync.yaml`

**Comment by clrxbl** [comment]
> Can you post the status of the `GitRepository` object? esp `status.artifact`?

```
status:
  artifact:
    digest: sha256:be009e349e6cb6b41debd8ad2c80ad4e3a3a275153ce58e90a0f21fcd6a82250
    lastUpdateTime: "2023-08-04T01:06:06Z"
    path: gitrepository/flux-system/flux-system/2b4a17a0a4bd1b75ddf06191152920b68c767516.tar.gz
    revision: main@sha1:2b4a17a0a4bd1b75ddf06191152920b68c767516
    size: 76329
    url: http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/2b4a17a0a4bd1b75ddf06191152920b68c767516.tar.gz
  conditions:
  - lastTransitionTime: "2023-08-04T01:06:06Z"
    message: stored artifact for revision 'main@sha1:2b4a17a0a4bd1b75ddf06191152920b68c767516'
    observedGeneration: 4
    reason: Succeeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-08-04T01:06:06Z"
    message: stored artifact for revision 'main@sha1:2b4a17a0a4bd1b75ddf06191152920b68c767516'
    observedGeneration: 4
    reason: Succeeded
    status: "True"
    type: ArtifactInStorage
  lastHandledReconcileAt: 2023-08-04 01:06:04.0912251 +0000 UTC m=+715.622801018
  observedGeneration: 4
  ```

> @clrxbl what you posted is from the cluster right? Can you post here the YAML from Git `gotk-sync.yaml`

Correct. Here's the YAML:

```
# This manifest was generated by flux. DO NOT EDIT.
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/PaperMC/infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```
