### ISSUE TITLE
Flux Kustomization diff fails with local kustomization file that has multiple resources with the same name

### ISSUE THREAD

**Issue by mraerino** [fluxcd/flux2#4132]
### Describe the bug

When using `flux diff kustomization` with a local Kustomization yaml, the server diff fails with not found errors when the local kustomization yaml has another resource with the same name.

### Steps to reproduce

when i run `flux diff kustomization --path <manifests> --kustomize-file <yaml-file>`

with this `<yaml-file>`:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
spec:
  interval: 5m0s
  path: ./kustomize
  force: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
```

i get these failures:

```
[Deployment/podinfo namespace not specified: the server could not find the requested resource, HorizontalPodAutoscaler/podinfo namespace not specified: the server could not find the requested resource, Service/podinfo namespace not specified: the server could not find the requested resource, Secret/docker-secret namespace not specified: the server could not find the requested resource, Secret/secret-basic-auth-stringdata namespace not specified: the server could not find the requested resource, Secret/podinfo-token-77t89m9b67 namespace not specified: the server could not find the requested resource, Secret/db-user-pass-bkbd782d2c namespace not specified: the server could not find the requested resource]
```

### Expected behavior

I expect the diff to show me the resources that are changing.

### OS / Distro

macOS 13.5 (22G74)

### Flux version

v2.0.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.26.7+k3s1 >=1.24.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.35.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Additional context

I put a minimal reproduction into a unit test here: https://github.com/fluxcd/flux2/pull/4131

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
