### ISSUE TITLE
HelmRelease location - only root works?

### ISSUE THREAD

**Issue by irmomanie** [fluxcd/flux2#415]
Where do I find out what the desired or optimal folder structure is for a repo? I sort of get various sources and releases to work, by putting specs into yaml files into my cluster root folder in my git repo, but as soon as I want to structure it into subfolders I'm lost when it comes to HelmRelease resources. They don't seem to be picked up when placed in a subfolder, is that by design?

**Comment by stefanprodan** [comment]
Place all shared manifests in the repo root dir e.g. `./base/releases`, then for each cluster add a Kustomization that points to base:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: releases
  namespace: flux-system
spec:
  interval: 5m
  path: "./base/releases"
  prune: true
  validation: client
  sourceRef:
    kind: GitRepository
    name: flux-system
```

The above file should be committed to `./staging/releases.yaml`.
