### ISSUE TITLE
Question: Kustomization Patching

### ISSUE THREAD

**Issue by autarchprinceps** [fluxcd/flux2#417]
We are actively using Flux v1 in many clusters right now, and are looking at how to redesign our flux repos for v2.
First of all, looks pretty amazing already. We love dependencies, and combining them with health checks. We are intrigued about the GitRepository, and what that could mean for having entire products in individual repos reused for multiple clusters.

But especially in that case, but even in a more traditional flux-repo, in which we typically differentiate at least dev, preprod & prod environments, we run into the issue, that we need to modify minor details of the original for each environment, like the URL.
We do this with fluxv1 and kustomize right now, by telling it to run kustomize on the path it gets and specifying a kustomization.yaml like this:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../products/
patchesStrategicMerge:
- flux-patch.yaml
- traefik-patch.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: fluxcloud
    namespace: fluxcd
  path: fluxcloud-patch.yaml
```
with a file system layout like this:
products/helm-release-traefik.yaml, ...
patches/{dev,preprod,prod}/kustomization.yaml, patches...

and a flux config of
```yaml
version: 1
patchUpdated:
  generators:
    - command: kustomize build .
  patchFile: flux-patch.yaml
```

The Kustomization CRD does not have any patches or something comparable, as far as I could see though. Nor have I found another new Fluxv2 feature that would replace this.
It is still possible to use kustomize build after the Kustomization Toolkit Resource, by pointing the Kustomization Resource spec.path to the patches, and repeating the same kind of kustomization.yaml patching, but this breaks or impedes many of the feature I praised about the new design.
Having a single repository for the product (e.g. Traefik), becomes impossible, as the patchesStrategicMerge, etc. operate on local file levels, so they need to be in the same repo, forcing one to either distribute parts of the environments specs into many repos, or to repeat basic product definition and synchronise by other non-flux means.
Specifying dependencies and health checks works fundamentally, but on the wrong level. It needs to be repeated for each environment and cluster, instead of being a fundamental element of how a product is defined.

So my question is, am I missing something to use for this? Is there a small or large redesign I could do to handle the fundamental concept of minor differences between two almost identical flux deployments?

**Comment by stefanprodan** [comment]
When we'll release the image update feature for Flux v2 you will be able to do:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../products/
images:
  - name: traefik
    newName: traefik
    newTag: v2.3.2 # {"$imagepolicy": "default:traefik:tag"}
  - name: docker.io/my-org/my-app
    newName: docker.io/my-org/my-app
    newTag: v0.0.1 # {"$imagepolicy": "default:my-app:tag"}
```

Based on those comments, Flux will patch the kustomization.yaml with new tags in your git repo.

More info here:
- roadmap https://toolkit.fluxcd.io/roadmap/#flux-image-update-feature-parity
- controller https://github.com/fluxcd/image-automation-controller
