### ISSUE TITLE
Azure DevOps flux bootstrap git : repository parameter is missing

### ISSUE THREAD

**Issue by cyberjpb1** [fluxcd/flux2#4199]
### Describe the bug

When using flux boostrap with Azure DevOps Git, there is no parameter to set the name in the manifest except using namespace, it is the default "flux-system" value for the name of GitRepository and Kustomization which is not ideal because obviously we have several repos which cannot all have the same "flux-system" name.

### Steps to reproduce

Running command :

```
flux bootstrap git \
  --url=https://dev.azure.com/organization/project/_git/repos \
  --branch=master \
  --path=./clusters/testing \
  --password=${AZ_PAT_TOKEN} \
  --token-auth=true
```

### Expected behavior

we should have the option to use the parameter "repository" like this:

```
flux bootstrap git \
  --url=https://dev.azure.com/project/GitOps/_git/fleet-infra \
  --repository=fleet-infra \
  --branch=master \
  --path=./clusters/testing \
  --password=${AZ_PAT_TOKEN} \
  --token-auth=true
```

```

# This manifest was generated by flux. DO NOT EDIT.
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fleet-infra
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: https://dev.azure.com/organization/project/_git/repos
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fleet-infra
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/testing
  prune: true
  sourceRef:
    kind: GitRepository
    name: fleet-infra

```

### Screenshots and recordings

File gotk-sync.yaml:
```

# This manifest was generated by flux. DO NOT EDIT.
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: https://dev.azure.com/organization/project/_git/repos
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/testing
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

```
### OS / Distro

N/A

### Flux version

v2.0.1

### Flux check

N/A

### Git provider

Azure DevOps Git

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
