### ISSUE TITLE
failed to extract layer contents from artifact: tar file entry bin/arch contained unsupported file type Lrwxrwxrwx

### ISSUE THREAD

**Issue by djschny** [fluxcd/flux2#4209]
### Describe the bug

Using the following definition with redaction:

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: my-app
  namespace: flux-system
spec:
  interval: 1m
  url: oci://ghcr.io/<my_org>/<my_repo>
  ref:
    tag: staging
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: OCIRepository
    name: my-app
  path: /my-resources/
  ```
  
  The following error is produced:
  
 ```
kubectl get events -n flux-system
LAST SEEN   TYPE      REASON                            OBJECT                        MESSAGE
3m2s        Warning   OCIArtifactLayerOperationFailed   ocirepository/course-tapper   failed to extract layer contents from artifact: tar file entry bin/arch contained unsupported file type Lrwxrwxrwx
```

### Steps to reproduce

See above

### Expected behavior

It should succeed and/or error should be more relevant.

### OS / Distro

N/A

### Flux version

latest

### Flux check

N/A - not use flux CLI

### Git provider

N/A

### Container Registry provider

GitHub Packages

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
