### ISSUE TITLE
Image Update Automation not honouring exclusion list

### ISSUE THREAD

**Issue by 2fst4u** [fluxcd/flux2#4210]
I have the following ImageRepository and ImagePolicy applied to my cluster:

```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/prowlarr
  interval: 1h
  exclusionList:
    - "^.*\\.sig$"
    - "1.8.1259"
    - "1.7.1209"
    - "1.6.1196" 
    - "1.5.1164"
    - "1.4.1155"
    - "1.2.1"
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: prowlarr
  filterTags:
    pattern: '^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
  policy:
    semver:
      range: '^1.x'
```

My exclusion list contains tags which I know to be false semver for old versions with an implicit "0." at the start, so I have attempted to explicitly ignore them from being used. 

When I describe both my ImageRepository and ImagePolicy it reconciles to tag `1.8.1259` which is the first item in my exclusion list that I specifically don't want:

```
Name:         prowlarr
Namespace:    flux-system
Labels:       kustomize.toolkit.fluxcd.io/name=flux-system
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  <none>
API Version:  image.toolkit.fluxcd.io/v1beta1
Kind:         ImageRepository
Metadata:
  Creation Timestamp:  2023-08-31T02:01:38Z
finalizers.fluxcd.io
  Generation:        1
  Resource Version:  329066117
  UID:               39787277-38c3-4480-b543-f1d455d19630
Spec:
  Exclusion List:
    ^.*\.sig$
    1.8.1259
    1.7.1209
    1.6.1196
    1.5.1164
    1.4.1155
    1.2.1
  Image:     lscr.io/linuxserver/prowlarr
  Interval:  1h
Status:
  Canonical Image Name:  lscr.io/linuxserver/prowlarr
  Conditions:
    Last Transition Time:  2023-08-31T02:01:45Z
    Message:               successful scan, found 65763 tags
    Reason:                ReconciliationSucceeded
    Status:                True
    Type:                  Ready
  Last Scan Result:
    Scan Time:          2023-08-31T02:01:45Z
    Tag Count:          65763
  Observed Generation:  1
Events:                 <none>
```

```
Name:         prowlarr
Namespace:    flux-system
Labels:       kustomize.toolkit.fluxcd.io/name=flux-system
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  <none>
API Version:  image.toolkit.fluxcd.io/v1beta1
Kind:         ImagePolicy
Metadata:
  Creation Timestamp:  2023-08-31T02:01:38Z
  Finalizers:
    finalizers.fluxcd.io
  Generation:        1
  Resource Version:  329066060
  UID:               08a1eed2-5635-4b62-ae56-a43e2ef317e0
Spec:
  Filter Tags:
    Pattern:  ^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
  Image Repository Ref:
    Name:  prowlarr
  Policy:
    Semver:
      Range:  ^1.x
Status:
  Conditions:
    Last Transition Time:  2023-08-31T02:01:38Z
    Message:               Latest image tag for 'lscr.io/linuxserver/prowlarr' resolved to: 1.8.1259
    Reason:                ReconciliationSucceeded
    Status:                True
    Type:                  Ready
  Latest Image:            lscr.io/linuxserver/prowlarr:1.8.1259
  Observed Generation:     1
Events:
  Type     Reason  Age                 From                        Message
  ----     ------  ----                ----                        -------
  Warning  error   101s                image-reflector-controller  ImageRepository.image.toolkit.fluxcd.io "prowlarr" not found
  Normal   info    94s (x3 over 101s)  image-reflector-controller  Latest image tag for 'lscr.io/linuxserver/prowlarr' resolved to: 1.8.1259
```
