### ISSUE TITLE
1st PVC in manifest created but not the 2nd

### ISSUE THREAD

**Issue by orenzp** [fluxcd/flux2#428]
Hi
I'm running a test on flux2 (0.2.2) and I came across an issue where I have the following manifest with 2 persistent volume and persistent volume claim but for some reason when flux Kustomize controller tries to apply the manifest only the first PVC is created.

If I suspend the Kustomization, delete the manifest and its resources, and then do a simple apply then both PVC's are created.

What is the process of troubleshooting this kind of issue, I try to read the kustomization controller logs its not easy

Thanks in advance, this is a great project 

Here is my manifest structure:
**storageclass.yaml**
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
```

**pv-pvc.yaml**
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-local-etc-volume
  namespace: home-k3s
  labels:
    directory: etc
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local
  local:
    path: /media/storageclass/pihole/etc
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rpi-1
          - rpi-2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-local-etc-claim
  namespace: home-k3s
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      directory: etc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-local-dnsmasq-volume
  labels:
    directory: dnsmasq.d
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local
  local:
    path: /media/storageclass/pihole/dnsmasq
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rpi-1
          - rpi-2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-local-dnsmasq-claim
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      directory: dnsmasq.d
```

**deploy.yaml**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: home-k3s
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
        name: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "Asia/Jerusalem"
        - name: WEBPASSWORD
          value: "secret"
        volumeMounts:
        - name: pihole-local-etc-volume
          mountPath: "/etc/pihole"
        - name: pihole-local-dnsmasq-volume
          mountPath: "/etc/dnsmasq.d"
      volumes:
      - name: pihole-local-etc-volume
        persistentVolumeClaim:
          claimName: pihole-local-etc-claim
      - name: pihole-local-dnsmasq-volume
        persistentVolumeClaim:
          claimName: pihole-local-dnsmasq-claim
```
