### ISSUE TITLE
validate.sh unable to replace variables within kustomizations

### ISSUE THREAD

**Issue by jack1902** [fluxcd/flux2#4289]
### Describe the bug

Running `validate.sh` (https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/scripts/validate.sh) against my files, i encounter an issue with `kustomize` against a kustomization similar to the below:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example
resources:
  - namespace.yaml
  - release.yaml
  - ../../../secrets/${cluster}/password.yaml
```

### Steps to reproduce

Have a kustomization which requires flux' postBuild piece to run such as the above and simply run the `validate.sh`

### Expected behavior

Script should handle variables such that when kustomize does a build any variables are handled (i'm unsure how this works within flux itself since the `postBuild` i assume is something applied by flux after having ran `kustomize` itself

### OS / Distro

MacOS

### Flux version

v2.1.1

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
