### ISSUE TITLE
Adding custom annotations to flux2 services 

### ISSUE THREAD

**Issue by fliphess** [fluxcd/flux2#429]
Hey gitops devs! 

This is a feature request: 

We use kube2iam for separating the required permissions for pods and the assigned permissions to nodes.  
To allow flux access to our ECR registries, an annotation needs to be set to the deployments to make sure kube2iam knows which role to assign to allow access to ECR. 

How can I do this using the flux2 cli tools? For now I think of manually editting the flux deployments to add an annotation as I don't see a feature to accomplish this. 

Could this perhaps be integrated in the flux bootstrap process?

**Comment by stefanprodan** [comment]
Assuming you've bootstrap flux with `flux bootstrap --path=staging` you can add annotations via a patch:

```
./staging/
│   ├── gotk-components.yaml
│   ├── gotk-sync.yaml
│   └── kustomization.yaml
├── flux-system-patch.yaml
└── kustomization.yaml
```

flux-system-patch.yaml 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    metadata:
      annotations:
        custom: annotation
      labels:
        custom: label
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    metadata:
      annotations:
        custom: annotation
      labels:
        custom: label
```

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
patchesStrategicMerge:
  - flux-system-patch.yaml
```
