### ISSUE TITLE
Patches in `kustomization` are not applied

### ISSUE THREAD

**Issue by Omar-Alkesh** [fluxcd/flux2#4344]
### Describe the bug

Patches specified in the `Kustomization` fail to find the resource or simply to fail to apply silently.

Sample log of error: 
```
2023-10-19T17:52:07.705Z error Kustomization/flux2-sync-usm1-trunk.flux-system - Reconciliation failed after 607.923608ms, next try in 5m0s kustomize build failed: no matches for Id Kustomization.v1.kustomize.toolkit.fluxcd.io/flux2-sync-usm1-trunk.flux-system; failed to find unique target for patch Kustomization.v1.kustomize.toolkit.fluxcd.io/flux2-sync-usm1-trunk.flux-system
```

### Steps to reproduce

Add patches to the kustomization:

Fails to apply with no warning
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  ## ...
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: flux
    helm.sh/chart: flux2-sync-1.7.0
  name: flux2-sync-usm1-trunk
  namespace: flux-system
  ## ..
spec:
  ## ...
  - patch: |-
      - op: add
        path: /metadata/labels/test
        value: flux-test
    target:
      kind: Kustomization
      name: flux2-sync-usm1-trunk
      namespace: flux-system
      version: kustomize.toolkit.fluxcd.io/v1
  ## ...
```

Can't find the resource by Id: 
```yaml
 - patch: |-
     apiVersion: kustomize.toolkit.fluxcd.io/v1
     kind: Kustomization
     metadata:
       name: flux2-sync-usm1-trunk
       namespace: flux-system
       labels:
         test: flux-test
```

### Expected behavior

To apply the patches to the specified resources.

### OS / Distro

Using helm to apply flux

### Flux version

flux: v2.1.1

### Flux check

► checking prerequisites
✗ flux 2.1.1 <2.1.2 (new version is available, please upgrade)
✔ Kubernetes 1.27.6-eks-f8587cb >=1.25.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.36.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.36.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.30.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.1.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.1.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.1.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

GitHub

### Container Registry provider

AWS ECR

### Additional context

Original issue: https://github.com/fluxcd-community/helm-charts/issues/194

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
