### ISSUE TITLE
ImageUpdateAutomation should also allow update of `app.kubernetes.io/version`

### ISSUE THREAD

**Issue by rparree** [fluxcd/flux2#4360]
It would be great if the image update automation process would allow to change the value of `app.kubernetes.io/version`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-ns
  labels:
    app.kubernetes.io/name: my-app
  annotations:
    app.kubernetes.io/version: "v0.0.0" # {"$imagepolicy": "my-ns:my-app"}
spec:
  …
  template:
    spec:
      containers:
      - name: my-app
        image: my-app:v0.0.0 # {"$imagepolicy": "my-ns:my-app"}
```
