### ISSUE TITLE
Is is possible two kustomize maintatin one single configmap? thanks.

### ISSUE THREAD

**Issue by johnzheng1975** [fluxcd/flux2#4396]
### Describe the bug

I want to set two kustomize maintain one single configmap? thanks.
One kustomize include a configmap, like
```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-adv-features
  namespace: flux-system
spec:
  interval: 0m30s
  path: ./kustomize/istio-adv-features
```

In folder istio-adv-features, there is a configmap, this is for initial usage.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: ratelimit
data:
  config.yaml: |
    domain: onecloud-ratelimit
    descriptors:
```

--- Second phase
Later, after user define some parameter, this configmap will be re-generated, and overwrite the old
this time it use helmrelease
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: ratelimit
  name: configmap-sync
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ratelimit-sync
      #sourceRef:
      #  kind: HelmRepository
      #  name: onecloud-charts
      #  namespace: flux-system
      #version: ${ONECLOUD_CHARTS_VERSION}
      sourceRef:
        kind: GitRepository
        name: onecloud-charts-test
        namespace: flux-system
  timeout: 10m0s
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  valuesFrom:
    - kind: ConfigMap
      name: onecloud-dev-try01
    - kind: ConfigMap
      name: onecloud-itg-try01
  values:
    services:
      - name: onecloud-dev-try01
      - name: onecloud-itg-try01
    others: othervalue1
```
In the helm charts, this configmap will be generated again, and overwrite the old configmap.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: ratelimit
  #annotations:
  # meta.helm.sh/release-name: configmap-sync  
  #  meta.helm.sh/release-namespace: ratelimit
  #labels:
  #  app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    domain: onecloud-ratelimit
    descriptors:
```

Actual result:
Always raise error as below:
Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install: ConfigMap "ratelimit-config" in namespace "ratelimit" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "configmap-sync"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "ratelimit"

No matter I added below OR NOT, ALWAYS FAIL.
```
  #annotations:
  # meta.helm.sh/release-name: configmap-sync  
  #  meta.helm.sh/release-namespace: ratelimit
  #labels:
  #  app.kubernetes.io/managed-by: Helm
```
### Steps to reproduce

As upper 

### Expected behavior

seems no solution for this.
Note that I have two maintain this configmap in two different phase, 
the first phase is kustomization with simple file.
the second phase is using helmrelease.

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
