### ISSUE TITLE
ImageUpdateAutomation patches remove YAML start of document --- dashes

### ISSUE THREAD

**Issue by sharkymcdongles** [fluxcd/flux2#4435]
### Describe the bug

Say you have a deployment yaml like this:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  labels:
    app: docs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      name: docs
      labels:
        app: docs
    spec:
      containers:
      - name: docs
        image: harbor.com/docs:1.10.80 # {"$imagepolicy": "flux-system:docs"}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
            cpu: "500m"
```

when the automation runs to deploy latest version it will commit it like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  labels:
    app: docs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      name: docs
      labels:
        app: docs
    spec:
      containers:
      - name: docs
        image: harbor.com/docs:1.10.80 # {"$imagepolicy": "flux-system:docs"}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
            cpu: "500m"
```

I know this isn't a showstopper, but some people enforce proper YAML format in repos and the three dashes are technically correct. I assume since kyaml is used perhaps a flag is needed to allow it to preserve the dashes but I didn't dive into the code yet.

### Steps to reproduce

Use an ImageUpdateAutomation to update any deployment yaml with --- at the start.

### Expected behavior

--- dashes are preserved if they exist

### OS / Distro

N/A

### Flux version

v2.0.0

### Flux check

```
► checking prerequisites
✗ flux 2.0.0 <2.1.2 (new version is available, please upgrade)
✔ Kubernetes 1.26.7-gke.500 >=1.24.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.36.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.36.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.30.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.1.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.1.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.1.2
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed
```

### Git provider

gitlab

### Container Registry provider

harbor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
