### ISSUE TITLE
flux bootstrap environment variables

### ISSUE THREAD

**Issue by zs-dima** [fluxcd/flux2#4438]
Could be nice to be able to pass environment variables to the `flux bootstrap` command.

For example we can pass $DOMAIN, $EMAIL, etc parameters to 
`flux bootstrap github --env DOMAIN=domain.com --env EMAIL=info@mail.com`
or even using local .env file
`flux bootstrap github --env .env`

Then we can use `grafana.${DOMAIN}` variables in yaml files stored in the GitHub.

This way useful for variables we do not want to store in GitHub or re-use repository for different environments. 
It can be extended for secrets as well `flux bootstrap --secret DOMAIN=domain.com`

Current workaround is to create ConfigMap or Secret preparatory to execute `flux bootstrap`.
This workaround leads to too much unnecessary code:

kustomization.yaml in GitHub repository
```yaml
kind: Kustomization
vars:
  - name: DOMAIN
    objref:
      kind: ConfigMap
      name: my-config
      apiVersion: v1
    fieldref:
      fieldpath: data.DOMAIN
  - name: ANOTHER_VARIABLE
    objref:
      kind: ConfigMap
      name: my-config
      apiVersion: v1
    fieldref:
      fieldpath: data.ANOTHER_VARIABLE
# ... and so on for each variable
```

config_map.yaml created locally before `flux bootstrap`
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: my-namespace
data:
  DOMAIN: example.com
  ANOTHER_VARIABLE: ANOTHER_VARIABLE
```

Then we can use `grafana.$(DOMAIN)` in yamls

**Comment by zs-dima** [comment]
Alternative workaround is

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: root
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./root
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: variables-config
  patches:
    - target:
        kind: Kustomization
        group: kustomize.toolkit.fluxcd.io
      patch: |-
        - op: add
          path: /spec/postBuild
          value:
            substituteFrom:
              - kind: ConfigMap
                name: variables-config
```

Then we can use `grafana.${DOMAIN}` in yamls
