### ISSUE TITLE
Question - use a RAW values.yaml for a Helm release

### ISSUE THREAD

**Issue by 0x53fa29jhezc** [fluxcd/flux2#445]
Hey guys,
like flux so far but I struggle a bit at the moment with integrating big value.yaml config files

For example for bitnami MongoDB Chart the production-values.yaml is very long (500 lines).
I do not want to copy paste this into the helm release yaml file

What is the best way to do that?

there is this section with

```
spec:
  valuesFrom:
  - kind: ConfigMap
    name: prod-env-values
    valuesKey: values-prod.yaml
```

BUT I do not want to create a ConfigMap for every Helm chart. In my opinion this would be a bit confusing to have the values somewhere outside the git repo

is there kustomize magic which merges the "production-values.yaml" (without changing it)  into helm-release-yaml?

**Comment by stefanprodan** [comment]
If you want to use the `values-production.yaml` file from inside the chart then do:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
spec:
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
      valuesFile: "values-production.yaml"
```

> BUT I do not want to create a ConfigMap for every Helm chart. In my opinion this would be a bit confusing to have the values somewhere outside the git repo

All Kubernetes manifests should be in the Git repository, you can place the raw production-values.yaml inside the repo and use Kustomize to generate the configmap:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mongo-namespace.yaml
- mongo-helm-releases.yaml

configMapGenerator:
- name: mongo-config
  files:
    - values.yaml=configs/production-values.yaml
```

Then in mongo-helm-releases.yaml:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
spec:
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
  valuesFrom:
  - kind: ConfigMap
    name: mongo-config
```

**Comment by 0x53fa29jhezc** [comment]
Thank you very much!

with the additional option

generatorOptions:
  disableNameSuffixHash: true

otherwise there will be a suffix mongo-config-234234234 and the config map can not be found in the release



```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mongo-namespace.yaml
- mongo-helm-release.yaml

configMapGenerator:
- name: mongo-config
  files:
    - values.yaml=configs/production-values.yaml

generatorOptions:
  disableNameSuffixHash: true
```

**Comment by potto007** [comment]
I know you had this conversation a few months ago, but just wanted to add:

You don't _have_ to use `generatorOptions: disableNameSuffixHash: true` - if you want to use immutable configMaps, you just need to add an extra file to the directory where the configMap is being attached to your resource(s):

create a file called `kustomizeconfig.yaml` with contents resembling the following:

```
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/valuesFrom/name
    kind: HelmRelease
```

reference: https://toolkit.fluxcd.io/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize

**Comment by nlamirault** [comment]
I try with this configuration : 

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../namespace
- ./cert-manager.yaml
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=cert-manager-values.yaml
configurations:
  - kustomizeconfig.yaml
```

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io/
      chart: cert-manager
      version: v1.3.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 5m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
```

```yaml
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/valuesFrom/name
    kind: HelmRelease
```

```yaml
installCRDs: true
# extraArgs:
#   - --enable-certificate-owner-ref=true
#   - --dns01-recursive-nameservers=1.1.1.1:53
#   - --dns01-recursive-nameservers-only
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
```

Then build : 

```
kustomize build kubernetes/base/cert-manager/cert-manager/ |grep -v "#"
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
data:
  values.yaml: |

    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        labels:
          release: kube-prometheus-stack
kind: ConfigMap
metadata:
  name: cert-manager-values-2f6c4747hh
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.3.0
  interval: 5m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  valuesFrom:
  - kind: ConfigMap
    name: cert-manager-values
```

Perhaps due to : https://github.com/kubernetes-sigs/kustomize/issues/1301 @stefanprodan @potto007 ?
