### ISSUE TITLE
Flux Kustomizations not removed after deleting from Git Repository

### ISSUE THREAD

**Issue by tech1ndex** [fluxcd/flux2#4452]
### Describe the bug

Related to https://github.com/fluxcd/flux2/issues/2627

Using the latest version of Flux and v1 of the API this still appears to be a problem. In this case even with `prune: true` being set. Kustomizations are not removed when they are deleted from a GitRepository, instead we need to manually remove them using `kubectl` of `flux`CLI. Once we remove them, they do not come back on reconcile.

### Steps to reproduce

1. Install [podinfo](https://github.com/stefanprodan/podinfo/tree/master/kustomize) manifests using [Kustomization example](https://fluxcd.io/flux/get-started/#deploy-podinfo-application)
2. Reconcile Git Source and ensure Podinfo is installed
3. Delete Kustomization file from Git Repository
4. Reconcile Source and confirm it matches the commit of the deleted Kustomization
5. Reconcile Main Kustomization to install the `podinfo` Kustomization
6. List Kustomizations on the cluster

### Expected behavior

We would expect to no longer see the `podinfo` Kustomization or it's resources however they still persist even though the reconcile matches the commit.

### Screenshots and recordings

Commit: 
<img width="345" alt="image" src="https://github.com/fluxcd/flux2/assets/50547519/55044d1d-ecda-4c67-8c78-84928e4b28df">

Reconcile: 
<img width="596" alt="image" src="https://github.com/fluxcd/flux2/assets/50547519/116a28de-cde0-4d9a-8633-54ddeb841efc">

Kustomizations:
<img width="1133" alt="image" src="https://github.com/fluxcd/flux2/assets/50547519/9397097f-1f7b-4e97-ab25-b667e9f13918">

### OS / Distro

Amazon Linux 5.10.197-186.748.amzn2.x86_64

### Flux version

v2.1.2

### Flux check

<img width="772" alt="image" src="https://github.com/fluxcd/flux2/assets/50547519/5fd74169-b0f2-4c84-97b6-7b740d42c67a">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
> Delete Kustomization file from Git Repository

I guess you mean `kustomization.yaml`. Deleting that file will not make Flux remove anything, as it will generate it on its own, see: https://fluxcd.io/flux/components/kustomize/kustomizations/#generating-a-kustomizationyaml-file

**Comment by stefanprodan** [comment]
You need to delete all files and commit so `.gitkeep` file to that dir. Once the dir has no Kubernetes YAML, only then Flux will remove them from the cluster.

**Comment by tech1ndex** [comment]
Hmm, that will take care of the resources but what about the `Kustomization` itself? 
```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: main
  interval: 10m0s
  path: "./kubernetes/apps/podinfo"
  retryInterval: 2m
  targetNamespace: default
  timeout: 2m
  wait: true
  prune: true
```

The end goal is to be able to delete this file and have it not show up in the Kustomization list on the cluster?
