### ISSUE TITLE
Flux v2.2.0 Provider v1beta3 API is not backwards compatible with v1beta2

### ISSUE THREAD

**Issue by n-asenov** [fluxcd/flux2#4471]
### Describe the bug

 Upgrading a Provider from v1beta2 to v1beta3 API fails if the Provider has an interval field set in its spec.

### Steps to reproduce

Upgrade the following Provider from v1beta2 to v1beta3
```yaml
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: alertmanager
  namespace: flux-system
spec:
  interval: 10m
  type: alertmanager
  address: http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093/api/v2/alerts/
```
The upgrade fails with 
```
Provider/flux-system/alertmanager dry-run failed: failed to create typed patch object (flux-system/alertmanager; notification.toolkit.fluxcd.io/v1beta3, Kind=Provider): .spec.interval: field not declared in schema...
```

### Expected behavior

Provider v1beta3 API should be backward compatible with v1beta2 and the upgrade should pass without errors.

### OS / Distro

N/A

### Flux version

v2.2.0

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
