### ISSUE TITLE
Upgrading to 2.2.0, started getting "kustomize build failed: kustomization.yaml is empty"

### ISSUE THREAD

**Issue by joaocc** [fluxcd/flux2#4509]
### Describe the bug

Since upgrading to 2.2.0 (or 2.2.2) from 2.1.x, we started receiving the following errors `kustomize build failed: kustomization.yaml is empty`
This is from a Kustomization object (kustomize.toolkit.fluxcd.io/v1) pointing to a folder with no resources.
Previously these were silently ignored, and kustomizations would suceed.

### Steps to reproduce

```yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: level-1
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./res/level-1
  dependsOn:
    - name: level-0
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-own-git # this must match the name under which this repo has been created on the system
```

### Expected behavior

The kustomization would process an empty folder and would suceed

### OS / Distro

Ubuntu

### Flux version

v2.2.2

### Flux check

flux check
► checking prerequisites
✔ Kubernetes 1.28.4-eks-8cb36c9 >=1.26.0-0
► checking version in cluster
✔ distribution: flux-2.2.2
✔ bootstrapped: false
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.37.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.37.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.31.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.2.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.2.3
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.2.3
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

N/A

### Container Registry provider

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
The workaround is to place in the dir a kustomization.yaml like so:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
```

This will be fixed next year.

**Comment by joaocc** [comment]
Thanks for the prompt response. In this case, as a temporary workaround, i need to write an "empty" placeholder `kustomization.yaml`? That being the case, thanks for the workaround, and will look forward for the fix. Thanks

**Comment by joaocc** [comment]
Hi. 
I tried the workaround and I still got the same error. I was only able to solve the issue if, instead of `resources: []` I create a dummy file and point the `kustomization.yaml` there.
Is this expected?
Thanks

**Comment by cep21** [comment]
@stefanprodan Does this qualify as a breaking change?  Should it have had a version number increase?  We were hit by a similar issue when upgrading flux.

**Comment by mrparkers** [comment]
Just chiming in that the `resources: []` workaround worked for me.

**Comment by joawin** [comment]
Hi,
i have the same problem.
When creating the file kustomization.yaml in the empty gitrepo i still get the message 

"kustomize build failed: kustomization.yaml is empty"

kustomization.yaml in empty git repo
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
```

Kustomization File
```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-repo
  namespace: namespace
spec:
  interval: 1m
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: nameofrepo
  timeout: 2m
  serviceAccountName: m2m-sa
  decryption:
    provider: sops
    secretRef:
      name: tenant-agekey
```
