### ISSUE TITLE
Expose prometheus port for Services in k8s manifests YAML

### ISSUE THREAD

**Issue by rtrevi** [fluxcd/flux2#4526]
### Describe the bug

The `Service` objects in the release yamls only expose application port `http` but lack prometheus port `http-prom`:
```YAML
# https://github.com/fluxcd/source-controller/blob/main/config/manager/service.yaml
(...)
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
```
```YAML
# https://github.com/fluxcd/source-controller/blob/main/config/manager/deployment.yaml
(...)
        ports:
          - containerPort: 9090
            name: http
            protocol: TCP
          - containerPort: 8080
            name: http-prom
            protocol: TCP
          - containerPort: 9440
            name: healthz
            protocol: TCP
```
Lacking the http-prom port makes scraping with a prometheus-operator `ServiceMonitor` impossible.

I am aware of the `PodMonitor` example at: https://github.com/fluxcd/flux2-monitoring-example/blob/main/monitoring/configs/podmonitor.yaml but it's not an option for me until: https://github.com/prometheus-operator/prometheus-operator/issues/3922 as I need the support for file references in istio mTls config: 
```YAML
# From: https://istio.io/latest/docs/ops/integrations/prometheus/#tls-settings
scheme: https
tls_config:
  ca_file: /etc/prom-certs/root-cert.pem
  cert_file: /etc/prom-certs/cert-chain.pem
  key_file: /etc/prom-certs/key.pem
  insecure_skip_verify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod certificate
```

### Steps to reproduce

Get latest version of k8s yamls from v2.2.2 release: https://github.com/fluxcd/flux2/releases/download/v2.2.2/install.yaml

### Expected behavior

Services should expose the prometheus endpoint.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
