### ISSUE TITLE
`ImageRepository` does not resolve private docker images when encrypted by kustomize `secretGenerator`

### ISSUE THREAD

**Issue by martinfrancois** [fluxcd/flux2#4546]
### Describe the bug

When you add an `ImageRepository` which references a spec with a private docker image, specifying the name of the `secretRef` of a dockerconfig which is encrypted with GPG by using `secretGenerator` of kustomize results in an error, saying the secret is not being found. When adding the hash suffix that is appended by `secretGenerator` manually, it finds the secret and it works as expected. So I assume there's an issue that `secretRef` does not resolve the secret when defined by `secretGenerator`. Referencing the secret for the dockerconfig in the deployment itself as  `imagePullSecrets` works however as expected without the hash suffix, so this must be limited to `ImageRepository`.

### Steps to reproduce

(Note: not all steps might be necessary, I'm just writing it down as I was able to reproduce it in case it matters)

1. Install flux with additional image automation controllers and GPG decryption with SOPS
2. Create namespace `mynamespace`
3. Create a deployment in `mynamespace` with a private docker image that requires login at a docker registry
4. Encrypt docker's `config.json` using for example: `sops -e --config <(echo '') --pgp '<fingerprint>' --input-type=json --output-type=json ~/.docker/config.json > my.dockerconfigjson.encrypted`
5. Create a `kustomization.yaml` with `secretGenerator` as explained in: https://fluxcd.io/flux/components/kustomize/kustomizations/#kustomize-secretgenerator

    For example:
    ```yaml
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    namespace: mynamespace
    secretGenerator:
      - name: my-private-registry
        namespace: mynamespace
        type: kubernetes.io/dockerconfigjson
        files:
          - .dockerconfigjson=my.dockerconfigjson.encrypted
    resources:
      - my-deployment.yaml
    ```
6. Add the following to `spec.template.spec` in the deployment:
    ```yaml
          imagePullSecrets:
            - name: my-private-registry
    ```
  
7. Note: When pushing this, after reconciliation, pods should have been created successfully pulling the private docker image.
8. Create an `ImageRepository` referencing `my-private-registry` which you also add to the `kustomize.yaml`'s resources, for example:
    ```yaml
    apiVersion: image.toolkit.fluxcd.io/v1beta2
    kind: ImageRepository
    metadata:
      name: my-repo
      namespace: mynamespace
    spec:
      image: myregistry/mydockernamespace/myimage:tag # same as in deployment
      interval: 1m0s
      secretRef:
        name: my-private-registry
      accessFrom:
        namespaceSelectors:
          - matchLabels:
              kubernetes.io/metadata.name: flux-system
    ```
9. After pushing and waiting for reconciliation, the following error occurs:
    ```
    failed to configure authentication options: secrets "my-private-registry" not found
    ```

### Expected behavior

Reconciliation should finish successfully and image automation can successfully pull from `ImageRepository` just like the deployment can.

When running `kubectl get secrets -n mynamespace` to look up the actual name of the secret generated by `secretGenerator` with the hash suffix and using it in `secretRef` results in the the expected behavior, for example:
```yaml
      secretRef:
        name: my-private-registry-ktt7c24513
```
This is not something you should do for security reasons, but it proves there isn't an issue with the decryption or the generation of the secret, it purely seems to come down to not resolving the secret.

### OS / Distro

N/A

### Flux version

v2.2.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.28.2 >=1.26.0-0
► checking version in cluster
✔ distribution: flux-v2.2.2
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.37.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.37.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.31.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.2.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.2.3
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.2.3
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

Private GitHub repository

### Container Registry provider

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
You need to configure Kustomize so it knows about Flux CRDs. An example can be found here: https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-secret-generated-with-kustomize-and-sops

In your case the `kustomizeconfig.yaml` would look like this:

```yaml
nameReference:
- kind: Secret
  version: v1
  fieldSpecs:
  - path: spec/secretRef/name
    kind: ImageRepository
```
