### ISSUE TITLE
Helm targetNamespace partially overridden by metadata.namespace

### ISSUE THREAD

**Issue by smigii** [fluxcd/flux2#4574]
### Describe the bug

The Helm release I installed with Flux is shown as being installed in the namespace defined by `targetNamespace` (tsbconf) but is only accessible in the namespace defined in `metadata.namespace` (tsb-flux)

After installing a Helm chart with Flux, the output of `helm ls -A` shows my release

```
tsb-config-tnt-cos          	tsbconf           	1       	2024-01-29 02:25:12.180208029 +0000 UTC	deployed	tsb-tenant-config-0.0.3
```

If i try to use any command to get more information on the release, it fails saying the release was not found.

```
helm get manifest tsb-config-tnt-cos -n tsbconf           
Error: release: not found
```

If I even try listing the Helm releases in the `tsbconf` namespace, nothing shows up even with `-a`

```
helm ls -a -n tsbconf
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
```

However, if I set the namespace to be the one I used in `metadata.namespace`, it shows up and I can run commands on it.
```
helm ls -n flux-tsb                             
NAME              	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                  	APP VERSION
tsb-config-tnt-cos	tsbconf  	1       	2024-01-29 02:25:12.180208029 +0000 UTC	deployed	tsb-tenant-config-0.0.3
```

HelmRelease YAML, (values omitted)

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tsb-config-tnt-cos
  namespace: flux-tsb
spec:
  interval: 5m0s
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: tsb-tenant-config
      version: '0.0.3'
      sourceRef:
        kind: HelmRepository
        name: tsb-tenant-config
  releaseName: tsb-config-tnt-cos
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  targetNamespace: tsbconf
  values: OMITTED
```

HelmRepository YAML
```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tsb-tenant-config
  namespace: flux-tsb
spec:
  interval: 5m0s
  url: REDACTED
  secretRef:
    name: REDACTED
```

Deploying the Helm chart manually works as normal, so I assume this is specific to Flux

### Steps to reproduce

1. Installed Flux using the Terraform provider (version = "1.2.2")
2. Added HelmRelease and HelmRepository to the flux folder
3. Waited for reconcile, deploy looks okay, can't find any errors 

### Expected behavior

* `helm ls -n tsbconf` should display my Helm release
* `helm ls -n flux-tsb` should not display my Helm release
* Running `helm get manifest tsb-config-tnt-cos -n tsbconf` should work
* Running `helm get manifest tsb-config-tnt-cos -n flux-tsb` should not work

### Screenshots and recordings

![image](https://github.com/fluxcd/flux2/assets/62163458/ac8f628c-5659-4c12-863d-c35a2bace421)

### OS / Distro

CLI on MacOS apple silicon, Flux running on BottlrocketOS

### Flux version

v2.1.2

### Flux check

```
flux check -n flux-tsb
► checking prerequisites
✗ flux 2.1.2 <2.2.2 (new version is available, please upgrade)
✔ Kubernetes 1.27.8-eks-8cb36c9 >=1.25.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.37.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.2.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.2.3
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.2.3
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed
```

### Additional context

FWIW, the Helm chart we are using has all of it's resources in a single list (this was the only way we could get the chart to work with the CRDs we are using), similar to the following example from https://docs.tetrate.io/service-bridge/howto/gitops/flux#application-setup 

```yaml
apiVersion: v1
kind: List
items:
# Create an ingress gateway deployment that will be the entry point to
# the bookinfo application
- apiVersion: install.tetrate.io/v1alpha1
  kind: IngressGateway
  metadata:
    namespace: bookinfo
    name: tsb-gateway-bookinfo
  spec: {}
# Create the workspace and gateway group that capture the namespaces where
# the bookinfo application will run
- apiVersion: tsb.tetrate.io/v2
  kind: Workspace
  metadata:
    name: bookinfo
    annotations:
      tsb.tetrate.io/organization: your-org
      tsb.tetrate.io/tenant: your-tenant
  spec:
    namespaceSelector:
      names:
        - "*/bookinfo"
``` 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
