### ISSUE TITLE
ClusterRole with aggregation rules is detected as drifted

### ISSUE THREAD

**Issue by demikl** [fluxcd/flux2#4586]
### Describe the bug

Since flux2 v2.2.0, each reconciliation attempt of a ClusterRole that has some aggregation rules, but no inline rules defined, triggers an effective apply.

### Steps to reproduce

Create a kustomization `my-test` that has this two resources in its path:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-aggregate-destination
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      just-for: test
```

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-aggregate-source
  labels:
    just-for: test
rules:
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - get
```

### Expected behavior

First reconciliation will create cluster role `test-aggregate-destination`, and next reconciliation will do nothing. Instead, a diff is detected:

```
$ flux diff kustomization my-test --path .
✓  Kustomization diffing...
► ClusterRole/test-aggregate-destination drifted

rules
  ± type change from list to <nil>
    - - apiGroups:
        - events.k8s.io
        resources:
        - events
        verbs:
        - get
    + <nil>
```

Flux v2.1 does not detect a drift.

### OS / Distro

Linux Mint 21.3 (desktop) and Amazon Linux EKS AMI (kubernetes nodes)

### Flux version

v2.2.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.28.4-eks-8cb36c9 >=1.26.0-0
► checking version in cluster
✔ distribution: flux-v2.2.2
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► all-docker.artifact.cloud.socrate.vsct.fr/fluxcd/helm-controller:v0.37.2
✔ image-automation-controller: deployment ready
► all-docker.artifact.cloud.socrate.vsct.fr/fluxcd/image-automation-controller:v0.37.0
✔ image-reflector-controller: deployment ready
► all-docker.artifact.cloud.socrate.vsct.fr/fluxcd/image-reflector-controller:v0.31.1
✔ kustomize-controller: deployment ready
► all-docker.artifact.cloud.socrate.vsct.fr/fluxcd/kustomize-controller:v1.2.1
✔ notification-controller: deployment ready
► all-docker.artifact.cloud.socrate.vsct.fr/fluxcd/notification-controller:v1.2.3
✔ source-controller: deployment ready
► all-docker.artifact.cloud.socrate.vsct.fr/fluxcd/source-controller:v1.2.3
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
