### ISSUE TITLE
ImagePolicy semver with release-candidate filter

### ISSUE THREAD

**Issue by k11h-de** [fluxcd/flux2#4599]
### Describe the bug

First of all, flux is a great tool and has boosted our productivity a lot. Thanks a million for all the hard work and effort put into this!

We're using ImagePolicies and noticed a strange behavior. 
When working with semver and filters it looks like `-rc9` is considered higher than `-rc10`

### Steps to reproduce

1. create an ImagePolicy with following specs
```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: release-candidate
  namespace: blueprint-service1
spec:
  imageRepositoryRef:
    name: service1
  filterTags:
    pattern: '.*-rc.*'
  policy:
    semver:
      range: '>=v0.0.1-0'
```

2. push image to registry with tag `v1.0.1-rc9` -> resolves works perfectly fine

3. push image to registry with tag `v1.0.1-rc10` -> resolve fails. Most recent is still `-rc9` 

### Expected behavior

push image to registry with tag `v1.0.1-rc10` is considered a higher version that `v1.0.1-rc9`

### OS / Distro

Linux

### Flux version

2.2.2

### Flux check

N/A

### Container Registry provider

private

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
