### ISSUE TITLE
Run conformance tests for OpenShift

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#4625]
If we can get sponsorship to spin up OpenShift clusters, we could run the bootstrap test from https://github.com/fluxcd/flux2/blob/main/tests/bootstrap/main.go with the OpenShift patches from https://fluxcd.io/flux/installation/configuration/openshift/. 

Tasks:
- [x] find a sponsor that can give us free OpenShift clusters that we can spin in GitHub Actions
- [x] modify [the bootstrap patch](https://github.com/fluxcd/flux2/blob/main/tests/bootstrap/main.go) for OpenShift
- [x] create a dedicated GitHub workflow to run the above

**Comment by errordeveloper** [comment]
You may find this  terraform repo useful for sounding up clusters with OCP (the commercial stable edition, which comes with unlimited scale trial of 60days) as well as OKD (the community edition, which is not necessarily stable).
 https://github.com/cilium/openshift-terraform-upi

The repo is archived now, but it was all very generic.

You can use 'opening-install' otherwise, but it can be a bit limited. That terrform repo contains a script that can download the installed command from any given version/edition, which can be handy.

**Comment by errordeveloper** [comment]
I will share the role definition once I get to my desk.

**Comment by stefanprodan** [comment]
@errordeveloper my hope is that Marc can provide us with a free OpenShift clusters that we can spin from GH Actions https://x.com/mccode/status/1758126362647490856?s=20

**Comment by errordeveloper** [comment]
This is what you will want:
```YAML
apiVersion: v1
kind: List
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: flux-scc
    rules:
      apiGroups:
        - security.openshift.io
      resources:
        - securitycontextconstraints
      resourceNames:
        - nonroot
      verbs:
        - use
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: flux-scc-source-controller
      namespace: flux-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: flux-scc
    subjects:
      - kind: ServiceAccount
        name: flux-source-controller
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: flux-scc-kustomize-controller
      namespace: flux-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: flux-scc
    subjects:
      - kind: ServiceAccount
        name: flux-kustomize-controller
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: flux-scc-helm-controller
      namespace: flux-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: flux-scc
    subjects:
      - kind: ServiceAccount
        name: flux-helm-controller
```

In case you want to tweak a few things, I used this to generate the YAML above. 
```sh
cue export --out yaml - <<EOF
_controllers: [
	"source-controller",
	"kustomize-controller",
	"helm-controller",
]

_namespace: "flux-system"

_role: {
	apiVersion: "rbac.authorization.k8s.io/v1"
	kind:       "ClusterRole"
	metadata: name: "flux-scc"
	rules: {
		apiGroups: [
			"security.openshift.io",
		]
		resources: [
			"securitycontextconstraints",
		]
		resourceNames: [
			"nonroot",
		]
		verbs: [
			"use",
		]
	}
}

_roleBindings: {}

for c in _controllers {
	_roleBindings: (c): {
		apiVersion: "rbac.authorization.k8s.io/v1"
		kind:       "RoleBinding"
		metadata: {
			name:      "flux-scc-\(c)"
			namespace: _namespace
		}
		roleRef: {
			apiGroup: "rbac.authorization.k8s.io"
			kind:     "Role"
			name:     "flux-scc"
		}
		subjects: [{
			kind: "ServiceAccount"
			name: "flux-\(c)"
		}]
	}
}

apiVersion: "v1"
kind:       "List"
items: [
	_role,
	for _, roleBinding in _roleBindings {roleBinding},
]
EOF
```

I've not tested it, as I don't have an OpenShift cluster around right now, but it's very much trivial.
