### ISSUE TITLE
HelmRepository cannot refresh with large index.yaml 

### ISSUE THREAD

**Issue by essembeh** [fluxcd/flux2#4635]
### Describe the bug

I have installed  [Adminer](https://artifacthub.io/packages/helm/truecharts/adminer) from [TrueCharts](https://charts.truecharts.org) Helm repository.

But since their [index.yaml](https://charts.truecharts.org/index.yaml) has recently reached 50+MB, Flux cannot fetch the Helm Repository anymore and it does not upgrade my charts anymore, and I cannot install any new chart from the Repository.

See the actual size of the `index.yaml`
```sh
curl -so /dev/null https://charts.truecharts.org/index.yaml -w '%{size_download}'
50659543
```

I quickly browse the Flux code and found this [hardcoded limit](https://github.com/fluxcd/source-controller/blob/eb19b1d407b477003e2fd7b581291d1b6299a9e6/internal/helm/helm.go#L23C2-L23C14)
```go
package helm

// This list defines a set of global variables used to ensure Helm files loaded
// into memory during runtime do not exceed defined upper bound limits.
var (
	// MaxIndexSize is the max allowed file size in bytes of a ChartRepository.
	MaxIndexSize int64 = 50 << 20
	// MaxChartSize is the max allowed file size in bytes of a Helm Chart.
	MaxChartSize int64 = 10 << 20
	// MaxChartFileSize is the max allowed file size in bytes of any arbitrary
	// file originating from a chart.
	MaxChartFileSize int64 = 5 << 20
)
```

I might be interesting to allow users to configure their limits?

For example by exposing them in the `HelmRepository` specs like
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: truecharts
spec:
  interval: 60m0s
  url: https://charts.truecharts.org/
  maxIndexSize: 100000000
```

### Steps to reproduce

I use this `kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - namespace.yaml
  - helm.yaml
  - adminer.yaml
```

Here is the `namespace.yaml`
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: tools
```

Here is the `helm.yaml`
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: truecharts
spec:
  interval: 60m0s
  url: https://charts.truecharts.org/
```

Here is the `adminer.yaml`
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adminer
spec:
  chart:
    spec:
      chart: adminer
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: truecharts
      version: ">=5.0.0"
  values:
    service:
      main:
        ports:
          main:
            port: 80
            protocol: http
            targetPort: 8080
  interval: 1m0s
```

I get the error:
```sh
flux get all -A --status-selector ready=false

NAMESPACE	NAME	REVISION	SUSPENDED	READY	MESSAGE 

NAMESPACE	NAME	REVISION	SUSPENDED	READY	MESSAGE 

NAMESPACE	NAME                         	REVISION	SUSPENDED	READY	MESSAGE
tools    	helmchart/tools-adminer      	6.0.4   	False    	False	chart pull error: failed to get chart version for remote reference: failed to load index: failed to load index: /data/helmrepository/tools/truecharts/index-33485360.yaml exceeds the maximum index file size of 52428800 bytes


NAMESPACE	NAME                     	REVISION	SUSPENDED	READY	MESSAGE
tools    	helmrelease/adminer      	6.0.4   	False    	False	HelmChart 'tools/tools-adminer' is not ready

NAMESPACE	NAME	REVISION	SUSPENDED	READY	MESSAGE 

NAMESPACE	NAME	READY	MESSAGE 

NAMESPACE	NAME	SUSPENDED	READY	MESSAGE 

```

### Expected behavior

This chart is installed.

### OS / Distro

Linux, NixOS 23.11

### Flux version

flux: v2.1.2

### Flux check

► checking prerequisites
✗ flux 2.1.2 <2.2.3 (new version is available, please upgrade)
✔ Kubernetes 1.27.6+k3s1 >=1.25.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.36.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.1.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.1.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.1.2
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

GitLab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by essembeh** [comment]
Thanks @darkowlzz for the quick response.

Good news, there is already a way to solve my problem, and you're right it is more admin thing so my proposed solution is not the best.

Bad news, my `source-controller` is not working when I  increase the value 

Here is the path I applied
```yaml
patches:
  # target controllers by name
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --helm-index-max-size=60000000
    target:
      kind: Deployment
      name: "source-controller"
```

If I set `50000000`, the controller works but I get the error:
```
tools           helmrepository/truecharts                       False           False   failed to load Helm repository from index YAML: failed to load index: /tmp/chart-index-1421445662.yaml exceeds the maximum index file size of 50000000 bytes
```

If I set it to `60000000` (60MB), I get a **CrashLoopBackOff** on my pod.


```sh
kubectl describe -n flux-system pod/source-controller-78c8f7d89f-gfw8p

...
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  5m41s                   default-scheduler  Successfully assigned flux-system/source-controller-78c8f7d89f-gfw8p to minis
  Normal   Pulled     4m21s (x3 over 5m41s)   kubelet            Container image "ghcr.io/fluxcd/source-controller:v1.1.2" already present on machine
  Normal   Created    4m21s (x3 over 5m41s)   kubelet            Created container manager
  Normal   Started    4m20s (x3 over 5m41s)   kubelet            Started container manager
  Warning  Unhealthy  3m42s (x11 over 5m28s)  kubelet            Readiness probe failed: Get "http://10.42.0.14:9090/": dial tcp 10.42.0.14:9090: connect: connection refused
  Warning  BackOff    28s (x11 over 4m40s)    kubelet            Back-off restarting failed container manager in pod source-controller-78c8f7d89f-gfw8p_flux-system(098fff77-6eb9-4e31-96cf-d8d924cd8a43)
```

It gets `OOMKilled` because it reaches the memory limit set to `1Gi` by default.

I tried to set id to `2Gi`, I saw the used memory reach nearly the limit, but it seems to work.

I'm intrigued how increasing the helm index limit by 10Mi make the memory increase from `1Gi` to `2Gi` !

Maybe because I have the `truechart` HelmRepository declared in multiple namespace ... I don't know if there is a way to declare a HelmRepository once in a namespace and reference it in another?
