### ISSUE TITLE
flux 2.1.1 to 2.2.2 / 2.2.3 some alerts notification are missing 

### ISSUE THREAD

**Issue by Baitanik** [fluxcd/flux2#4649]
### Describe the bug

We have following Kustomization to point to Actual_ORValues.yaml ..
```
apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 
namespace: appilication-ns 
resources: 
  - release.yaml 
configMapGenerator: 
  - name: application-values
    files: 
      - ORValues.yaml=Actual_ORValues.yaml
configurations: 
  - kustomizeconfig.yaml 
```
And in HelmRelease then same configmap is mentioned to load the OR values yaml

```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease 
..... 
  valuesFrom: 
    - kind: ConfigMap 
      name: application-values
      valuesKey: ORValues.yaml 
```

While reconciling incase Actual_ORValues.yaml is an invalid yaml( e.g indentaion issue or any other invalid yaml format) 
in flux get all we get following error 

`
appilication-ns    helmrelease/app-name             9.0.0-51.0.3-7+2aaa31b50723     False           False   could not resolve ConfigMap chart values reference 'appilication-ns/application-values-86544g2h7d' with key 'ORValues.yaml': error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context
`

Till 2.1.1, for this error flux used to send one error event .  
alertname : FluxHelmReleaseError
Kind: HelmRelease
with the same error message ... 

We upgraded flux to 2.2.2. Now this error event notification is not longer sent to notification controller ..
Could you please help to check how we can enable error event like earlier we had in 2.1.1 ?

We tried upgrading 2.2.3 .. but issue persists .

NOTE: For other helmrelease  failure related alerts we are getting . e.g from helm-controller log 

**For following alert is getting send.**
`{"level":"error","ts":"2024-02-23T10:54:04.805Z","msg":"Reconciler error","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":{"name":"app-name","namespace":"application-ns"},"namespace":"application-ns","name":"application","reconcileID":"a2dfb244-5162-49c1-9ab0-64fb349cb07a","error":"error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:\n  line 18: mapping key \"app.kubernetes.io/name\" already defined at line 9","errorVerbose":"map[string]interface {}(nil): yaml: unmarshal errors:\n  line 18: mapping key \"app.kubernetes.io/name\" already defined at line 9\nerror while running post render on files\nhelm.sh/helm/v3/pkg/action.(*Configuration).renderResources\n\thelm.sh/helm/v3@v3.13.3/pkg/action/action.go:224\nhelm.sh/helm/v3/pkg/action.(*Upgrade).prepareUpgrade\n\thelm.sh/helm/v3@v3.13.3/pkg/action/upgrade.go:260\nhelm.sh/helm/v3/pkg/action............8"}`

For following event/alert is **NOT** getting  sent 
`{"level":"error","ts":"2024-02-23T11:12:49.889Z","msg":"Reconciler error","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":{"name":"app-name","namespace":"application-ns"},"namespace":"application-ns","name":"application","reconcileID":"8d0b49b2-578a-47e3-8ddd-14943b822604","error":"could not resolve ConfigMap chart values reference 'application-ns/application-values-h9kc8876tc' with key 'ORValues.yaml': error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context"}`

But in 2.1.1 , for both cases error event was getting generated

### Steps to reproduce

Mainly 4 files are required : 
1. kustomizeconfig.yaml
```
nameReference: 
- kind: ConfigMap 
  version: v1 
  fieldSpecs: 
  - path: spec/valuesFrom/name 
    kind: HelmRelease 
```

2.kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 
namespace: appilication-ns 
resources: 
  - release.yaml 
configMapGenerator: 
  - name: application-values
    files: 
      - ORValues.yaml=Actual_ORValues.yaml
configurations: 
  - kustomizeconfig.yaml 
```

3. release.yaml
```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease 
metadata: 
  name: app-name
  namespace: appilication-ns  
spec: 
  install:
    timeout: 5m
    disableWait:  true
  upgrade:
    timeout: 5m
    disableWait:  true
  chart:
    spec:
      chart: ./appilication.tgz
      reconcileStrategy: Revision 
      sourceRef: 
        kind: GitRepository 
        name: application-repository 
        namespace: flux-system 
  interval: 1m0s 
  valuesFrom: 
    - kind: ConfigMap 
      name: appilication-values
      valuesKey: ORValues.yaml 
```

4. alert.yaml
```
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: apps
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: helm-alert-application-ns
  namespace: flux-system
spec:
  eventSeverity: error
  eventSources:
  - kind: HelmRelease
    name: '*'
    namespace: application-ns
  - kind: HelmChart
    name: '*'
    namespace: application-ns
  - kind: HelmRepository
    name: '*'
    namespace: application-ns
  - kind: Kustomization
    name: '*'
    namespace: application-ns

  providerRef:
    name: flux-webhook
  summary: testing
~

```

### Expected behavior

Error Event should be send to notification controller for the above kind of error for latest flux version 2.2.2 or 2.2.3

### OS / Distro

Ubuntu 20.04.6 LTS

### Flux version

flux version 2.2.2

### Flux check

flux check
► checking prerequisites
✔ Kubernetes 1.28.0 >=1.26.0-0
► checking version in cluster
✔ distribution: flux-v2.2.3
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ericngxpacr.azurecr.io/fluxcd/helm-controller:v0.36.1
✔ kustomize-controller: deployment ready
► ericngxpacr.azurecr.io/fluxcd/kustomize-controller:v1.2.2
✔ notification-controller: deployment ready
► ericngxpacr.azurecr.io/fluxcd/notification-controller:v1.2.4
✔ source-controller: deployment ready
► ericngxpacr.azurecr.io/fluxcd/source-controller:v1.2.4
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
