### ISSUE TITLE
Promethus metrics gotk_reconcile_condition for kind="HelmRelease" is missing from 2.2.2 flux (helm-controller:v0.37.2) , it was available in 2.1.1

### ISSUE THREAD

**Issue by Baitanik** [fluxcd/flux2#4652]
### Describe the bug

Till flux version 2.1.1 following promethus metrics were generated for kind=HelmRelease from helm-controller ( helm-controller:v0.36.1) 

```
gotk_reconcile_condition{kind="HelmRelease",name="sealed-secrets",namespace="sealed-secrets",status="False",type="Ready"} 0
gotk_reconcile_condition{kind="HelmRelease",name="sealed-secrets",namespace="sealed-secrets",status="True",type="Ready"} 1
gotk_reconcile_condition{kind="HelmRelease",name="sealed-secrets",namespace="sealed-secrets",status="Unknown",type="Ready"} 0
```

After upgrading to 2.2.2/2.2.3 , this metrics **gotk_reconcile_condition**  is no more getting generated from helm controller, It used to give metrics information about the helmrelease

Could not find gotk_resource_info metrics also in prometheus. We are using separate promethues operator. & podmonitor to scrape the metrics from flux. 

### Steps to reproduce

1. install flux
2. Cluster already has prometheus operator
3. Add following podmonitor in promethus operator
https://github.com/fluxcd/flux2-monitoring-example/blob/main/monitoring/configs/podmonitor.yaml
```
spec:
  namespaceSelector:
    matchNames:
    - flux-system
  podMetricsEndpoints:
  - port: http-prom
    relabelings:
    - action: keep
      regex: Running
      sourceLabels:
      - __meta_kubernetes_pod_phase
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - helm-controller
      - source-controller
      - kustomize-controller
      - notification-controller
      - image-automation-controller
      - image-reflector-controller

```

### Expected behavior

HelmRelease information should come in prometheus metrics

### OS / Distro

Ubuntu 20.04.6 LTS

### Flux version

flux version 2.2.2

### Flux check

✗ flux 2.2.2 <2.2.3 (new CLI version is available, please upgrade)
✔ Kubernetes 1.28.0 >=1.26.0-0
► checking version in cluster
✔ distribution: flux-v2.2.2
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ericngxpacr.azurecr.io/fluxcd/helm-controller:v0.37.2
✔ kustomize-controller: deployment ready
► ericngxpacr.azurecr.io/fluxcd/kustomize-controller:v1.2.1
✔ notification-controller: deployment ready
► ericngxpacr.azurecr.io/fluxcd/notification-controller:v1.2.3
✔ source-controller: deployment ready
► ericngxpacr.azurecr.io/fluxcd/source-controller:v1.2.3
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
The `gotk_resource_info` is generated by kube-state-metrics, docs here: https://fluxcd.io/flux/monitoring/metrics/#resource-metrics

**Comment by Baitanik** [comment]
gotk_resource_info is also not coming or sending the HelmRelease kind metrics.
In the full metrics list no metrics is coming with "gotk_resource_info" .. 
we were using the **podmonitor** as mentioned above.
we already KSM enabled for other services... 
we have tried to to add servicemonitor also 
 ```
 namespaceSelector:
    matchNames:
    - flux-system
  endpoints:
  - honorLabels: true
    port: http
    relabelings:
    - action: replace
      regex: ^(.*)$
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      kustomize.toolkit.fluxcd.io/name: infrastructure
```

but not much help.. 
any thing we need to enable in ksm ?
till 2.1.1 all were coming properly.
