### ISSUE TITLE
configMapGenerator and components order

### ISSUE THREAD

**Issue by RagingPuppies** [fluxcd/flux2#4659]
### Describe the bug

Hi,
I'm dealing with some strange issue with flux, i'm trying to create deployments based on .env files.
when running `kustomize build .` everything passes smoothly, but when flux is trying to reconcile in k8s, i'm getting an error.
the component is trying to use replacements to replace a string by using the configmap as the source of the data.
it seems like flux is processing the component before the configmapgenerator is running (in flux, again kustomize passes locally):
```
"recursed accumulation of path '/tmp/kustomization-3635781431/fluxv2/base/Trino/base/components/set_environment': nothing selected by ConfigMap.[noVer].[noGrp]/environment.[noNs]:data.tags"
```
is this a known issue? or is there any simple solution for that?

### Steps to reproduce

create the following folder:
base/trino/test
kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trino-test

resources:
- ../base/


configMapGenerator:
- behavior: merge
  envs:
  - .env
  name: environment

components:
- ../components/set_environment/
```

.env
```
tags=whatever
```

components/set_environment
```
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component


replacements:
  - source:
      kind: ConfigMap
      name: environment
      fieldPath: data.tags
    targets:
      - select:
          kind: HelmRelease
          name: trino
        fieldPaths:
          - spec.values.blabla
```
base/
kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-null
resources:
  - HelmRelease-Trino-base.yaml

```

HelmRelease-Trino-base.yaml
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trino
spec:
  releaseName: trino
  interval: 2m
  values:
    blabla: lala
```

### Expected behavior

I would expect flux to first generate the configmap and once generated apply the components

### OS / Distro

N/A

### Flux version

v2.1.2

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
