### ISSUE TITLE
Rollback strategy if we are using ImageUpdateAutomation is it possible to do so ? any reference doc or repo to check

### ISSUE THREAD

**Issue by zameer712** [fluxcd/flux2#4676]
### Describe the bug

Present Configurations we are using 👍 

Due to below Configuration if we are rolling back the version to older image , Imageupdateautomation is pushing the latest image back to the repo and then deployment is getting rolled out

1. Image policy 

```
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: dummy-application-image-policy
spec:
  imageRepositoryRef:
    name: gitops-fluxcd-poc
  filterTags:
    pattern: '^main-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
```

2. ImageUpdateAutomation

```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: image-update-automation
spec: 
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: gitops-fluxcd-poc
    namespace: flux-system
  update:
    path: ./manifests
    strategy: Setters
```

3. Image Repo :- 

```
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: gitops-fluxcd-poc
spec:
  interval: 2m
  image: athtestacr1.azurecr.io/dummy-app-1
  secretRef:
    name: <token-name>
```

How to have an Rollback strategy applicable directly on imageupdateautomation instead of using canary kind of deployment 

please share your inputs so that we can build an concrete solution around this

### Steps to reproduce

How to have an Rollback strategy applicable directly on imageupdateautomation instead of using canary kind of deployment 

please share your inputs so that we can build an concrete solution around this

### Expected behavior

How to have an Rollback strategy applicable directly on imageupdateautomation instead of using canary kind of deployment 

please share your inputs so that we can build an concrete solution around this

### Screenshots and recordings

How to have an Rollback strategy applicable directly on imageupdateautomation instead of using canary kind of deployment 

please share your inputs so that we can build an concrete solution around this

### OS / Distro

Linux

### Flux version

v0.20.1

### Flux check

How to have an Rollback strategy applicable directly on imageupdateautomation instead of using canary kind of deployment 

please share your inputs so that we can build an concrete solution around this

### Git provider

github

### Container Registry provider

Azure container registry

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

@stefanprodan / @avoidalone please provide your valuable inputs here if possible
