### ISSUE TITLE
How to build kustomization.yaml that refers SOPS Secrets, by kustomize CLI?

### ISSUE THREAD

**Issue by dulltz** [fluxcd/flux2#469]
I cannot find the way to build the kustomization.yaml that references SOPS Secrets by `kustomize build`.

kustomize-controller accepts the kustomization.yaml that references SOPS Secrets at `resources`.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.enc.yaml # ← encrypted secret by SOPS
```

There is no lines for kustomize plugins, I think this design is clean and straightforward.

However, there doesn't seem to be a way to build the kustomization.yaml with the kustomize CLI,
because [the decryption logic is implemented by kustomize-controller](https://github.com/fluxcd/kustomize-controller/blob/cfcbbfdcee3c4f0f0fcb0b2af33aa8ddd8f72541/controllers/kustomization_controller.go#L514-L528).

I often want to see the result of `kustomize build` at local machine, so please let me know if anyone know how to do it.
