### ISSUE TITLE
helm-controller Install of Kong Chart Release fails, but works fine with standard Helm commands

### ISSUE THREAD

**Issue by rmccright-ms3** [fluxcd/flux2#471]
When attempting to make a release of this [Kong Chart](https://github.com/Kong/charts/tree/main/charts/kong) the helm-controller errors out when running a _helpers template. However, this Chart installs just fine via standard Helm commands.

`helm-controller  Helm install failed: template: kong/templates/migrations.yaml:41:10: executing "kong/templates/migrations.yaml" at <include "kong.wait-for-postgres" .>: error calling include: template: kong/templates/_helpers.tpl: │
│ 630:6: executing "kong.wait-for-postgres" at <include "kong.no_daemon_env" .>: error calling include: template: kong/templates/_helpers.tpl:599:15: executing "kong.renderEnv" at <.>: wrong type for value; expected map[string]interface {}; got string`

This is the Source/HelmRelease used

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: konghq
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.konghq.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  targetNamespace: kong
  interval: 1m
  chart:
    spec:
      #https://github.com/Kong/charts/tree/main/charts/kong
      chart: kong
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: konghq
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
```
