### ISSUE TITLE
The pod would not be restarted

### ISSUE THREAD

**Issue by arkadyb** [fluxcd/flux2#4719]
Hi, i am following the quick start guides to configure my repository to work with fluxcd. I have run the `bootstrap` command and added required yaml configuration files to sync with the repo. I can see FluxCD resources to be synchronised with the commit in GitHub repo. I am sure the container gets updated too however, the actual application pod would never be restarted. If i kill the pod manually, it gets restarted with the new version. What am i missing? 

Its all the same repo that has the fleet (flux-system) and the actual workload configuration.

The look of the clusters directory is:
```
> clusters/gke-1
   -> flux-system
         -> gotk-components.yaml
         -> gotk-sync.yaml
         -> kustomization.yaml
    -> the-project-kustomization.yaml
    -> the-project-source.yaml

> kustomize 
   -> kustomization.yaml
   -> service.yaml
   -> deployment.yaml
```

The overall configuration look simple with `flux get all` would return a list of resources updated to the latest commit sha:
```
> flux get all                                 
NAME                     	REVISION          	SUSPENDED	READY	MESSAGE                                           
gitrepository/flux-system	main@sha1:764c6643	False    	True 	stored artifact for revision 'main@sha1:764c6643'	
gitrepository/the-project	main@sha1:764c6643	False    	True 	stored artifact for revision 'main@sha1:764c6643'	

NAME                     	REVISION          	SUSPENDED	READY	MESSAGE                              
kustomization/flux-system	main@sha1:764c6643	False    	True 	Applied revision: main@sha1:764c6643	
kustomization/the-project	main@sha1:764c6643	False    	True 	Applied revision: main@sha1:764c6643
```

The content of configuration files
`gotk-sync.yaml`
```
# This manifest was generated by flux. DO NOT EDIT.
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/arkadyb/the-project
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/gke-1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

`the-project-source.yaml`
```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: the-project
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/arkadyb/the-project
```

`the-project-kustomization.yaml`
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: the-project
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kustomize
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: the-project
  targetNamespace: default
  timeout: 3m0s
  wait: true
```

`kustomization.yaml` in `kustomize` diretory:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
```
