### ISSUE TITLE
404 in GitHub Webhook

### ISSUE THREAD

**Issue by autarchprinceps** [fluxcd/flux2#477]
> When a Receiver is created, the controller sets the Receiver status to Ready and generates a URL in the format /hook/sha256sum(token+name+namespace).

This is what your documentation says about the Webhook Receiver in notification-controller and the example GitHub Receiver to create a GitHub Webhook to reduce the amount of polling on our primary source at least.
But I get a 404 for every understanding of that path I could think of. I tried just concatinating the token, Receiver name and namespace, actually writing + between them, as well as space, but all sha256sums are not valid.

This is what the relevant kubernetes resources look like:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token
  namespace: flux-system
data:
  token: random-string-in-base64
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: github-receiver
  namespace: flux-system
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: github-webhook-token
  resources:
    - kind: GitRepository
      name: flux-system
---
apiVersion: v1
kind: Service
metadata:
  name: github-webhook
  namespace: flux-system
spec:
  ports:
  - name: http-webhook
    port: 9292
    protocol: TCP
    targetPort: http-webhook
  selector:
    app: notification-controller
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: github-webhook
  namespace: flux-system
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: webhook.example.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: github-webhook
          servicePort: http-webhook
  tls:
  - hosts:
    - webhook.example.com
    secretName: webhook.example.com
```

Does someone know exactly what is meant by sha256sum(token+name+namespace) or why else we could be getting a 404, if the sha sum we use should be correct?
