### ISSUE TITLE
Improvement: dependency requeue delay 

### ISSUE THREAD

**Issue by juliusmh** [fluxcd/flux2#4808]
### Describe the bug

It would be useful to specify `requeue-dependency` timeout on a per-kustomization basis, e.g. in the CRD. While 30s make sense for "heavy" KSs, a light apply e.g. of CRDs doesn't need to wait the full 30s before requeuing its dependants. The controller wide level could serve as a default.

Another problem with `dependsOn` is the general delay it adds, even if depended KSs are unchanged. Therefore, a possible improvement could be to entirely skip the delay if no changes were done to a dependency.

I'm not familiar with the codebase hence I can't comment on feasibility for those ideas. If this is not desired, or impractical, feel free to close. Otherwise, I'd be happy to discuss and get involved.

Related: https://github.com/fluxcd/flux2/issues/4739

### Steps to reproduce

N/A

### Expected behavior

I could foresee extending the `kustomize.toolkit.fluxcd.io` CRD to allow for a specific timeout and skipping the dependency checks if they are "unchanged":

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
spec:
  dependsOn:
    - name: crds
      requeueAfter: 2s
      skipUnchanged: true
```

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
