### ISSUE TITLE
Flux installation with Openshift and OLM into a dedicated namespace

### ISSUE THREAD

**Issue by blezoray** [fluxcd/flux2#4816]
### Describe the bug

Hello,

I installed Flux v2.3.0 on my lab Openshift 4.14 platform into a dedicated namespace, mpms-fluxcd-operator, using Operator Livecycle Manager (OLM).

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: fluxcd-operator
  namespace: mpms-fluxcd-operator
spec:
  channel: stable
  installPlanApproval: Manual
  name: flux
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: flux.v2.3.0
```
But all the controllers have the default namespace `flux-system` hard-coded in their deployment args `--events-addr=http://notification-controller.flux-system.svc.cluster.local./`

```yaml
      labels:
        app: kustomize-controller
    spec:
      containers:
      - args:
        - --events-addr=http://notification-controller.flux-system.svc.cluster.local./
        - --watch-all-namespaces=true
        - --log-level=info
        - --log-encoding=json
        - --enable-leader-election
```
You should use the variable `RUNTIME_NAMESPACE` or replace the url by `--events-addr=http://notification-controller/`

### Steps to reproduce

- Create a dedicated namespace, different to flux-system
- Create an OperatorGroup to allow user to deploy operator in the namespace with OLM
```yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: fluxcd-operator
spec:
  targetNamespaces: []
```
- Create a Subscription
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: fluxcd-operator
spec:
  channel: stable
  installPlanApproval: Manual
  name: flux
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: flux.v2.3.0
```
- Check the deployments

### Expected behavior

Args should be :         - --events-addr=http://notification-controller.mpms-fluxcd-operator.svc.cluster.local./

### OS / Distro

OpenShift 4.14

### Flux version

2.3.0

### Flux check

no more details

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
