### ISSUE TITLE
Flux able to get helm repo index.yaml but failing to fetch chart - tls cert valid for a, not b

### ISSUE THREAD

**Issue by haahen** [fluxcd/flux2#4838]
### Describe the bug

Hi there,

we want to use Flux in combination with ZScaler (cloud-based security platform - act as a cloud proxy which do ssl inspection). Normally we are used to calling the certificate (ca.crt) in the API. Unfortunately, this is not sufficient for Flux. What did I also do?

```
kubectl get helmrepo -n platform prometheus-community
```
```
NAME                   URL                                                  AGE   READY   STATUS
prometheus-community   https://prometheus-community.github.io/helm-charts   41m   False   failed to fetch Helm repository index: failed to cache index to temporary file: Get "https://prometheus-community.github.io/helm-charts/index.yaml": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

It was obvious that we need to specify the certificate as in the Flux documentation (source.toolkit.fluxcd.io/v1 with type: HelmRepository). Therefore the following:

`spec.certSecretRef: Name: z-scaler-ca`

We have defined the certificate file as a secret using kubectl.

`kubectl create secret generic z-scaler-ca --from-file=ca.crt=path\to\zscaler_root_cert.crt -n platform`

The artifact and its index could then be successfully downloaded

```
kubectl get helmrepo -n platform prometheus-community
```
```
NAME                   URL                                                  AGE   READY   STATUS
prometheus-community   https://prometheus-community.github.io/helm-charts   44m   True    stored artifact: revision 'sha256:340e510761ee8b750a1915050cf12e0873cfa2f50185d2ca5da26256a89c805e
```

Then, and this is where it becomes incomprehensible to me, we examined the helmet release. Unfortunately we get the following answer:

```
kubectl get helmrelease -n platform kube-prometheus-stack
```
```
NAME                    AGE   READY   STATUS
kube-prometheus-stack   49m   False   HelmChart 'platform/platform-kube-prometheus-stack' is not ready: chart pull error: failed to download chart for remote reference: Get "https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-58.4.0/kube-prometheus-stack-58.4.0.tgz": tls: failed to verify certificate: x509: certificate is valid for github.com, www.github.com, not prometheus-community.github.io`
```

> **tls: failed to verify certificate: x509: certificate is valid for github.com, www.github.com, not prometheus-community.github.io**

Then I tried the same thing with the “pod-info” package as a test. Everything worked fine here.  Then I tried to find out what the differences are between “pod-info” and “kube-prometheus-stack”. So we downloaded the index.yaml. 

`curl -v https://stefanprodan.github.io/podinfo/index.yaml -o podinfo_index.yaml`
`curl -v https://prometheus-community.github.io/helm-charts/index.yaml -o comm_index.yaml`

And search after the URL tag in both files:
- podinfo:
  - https://stefanprodan.github.io/podinfo/podinfo-6.6.3.tgz
- kube-prometheus-stack: 
  - https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-60.0.2/kube-prometheus-stack-60.0.2.tgz

We realize that there is a reference to a .tgz in Index.yaml. We could see, that the url changed. 

For that we can compare:

- spec.url: https://stefanprodan.github.io/podinfo **VS.** 
  - https://stefanprodan.github.io/podinfo/podinfo-6.6.3.tgz
- spec.url: https://prometheus-community.github.io/helm-charts  **VS.** 
  - https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-60.0.2/kube-prometheus-stack-60.0.2.tgz

After that I found the following within [documentation](https://fluxcd.io/flux/components/source/api/v1beta2/#source.toolkit.fluxcd.io/v1beta2.HelmRepositorySpec). For that we added  (source.toolkit.fluxcd.io/v1 with type: HelmRepository):

`spec.passCredentials: True`

Unfortunately, it still didn't work after that. It seems that **tls cert valid for a, not b** is happening because of the index.yaml. 

Any guidance will be much appreciated.

Thanks

### Steps to reproduce

- Setup k3d with cert
- Setup flux with install.yaml from (https://github.com/fluxcd/flux2/releases/tag/v2.3.0)
- helmrepo with github
- check helmrepo is working fine, no auth issues, its able to pull index.yaml
- create helmrelease, verify it fails to pull helm chart due tls error
- Use curl to pull chart, verify it works

### Expected behavior

After specifying the certificate, the charts should be downloaded. 

### OS / Distro

win 10

### Flux version

2.3.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.28.8+k3s1 >=1.28.0-0
► checking version in cluster
✔ distribution: flux-
✔ bootstrapped: true
► checking controllers
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.3.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.3.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.38.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.32.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.3.0
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.0.1
► checking crds
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by souleb** [comment]
Please have a look at https://github.com/fluxcd/source-controller/issues/510. You will have to patch source-controller to put the certs into the pods trust store.

**Comment by haahen** [comment]
As indicated in [fluxcd/source-controller#510](https://github.com/fluxcd/source-controller/issues/510), I now have the following structure:

- `flux-system`                                                  
  - ` z-scaler-ca.yaml `                                
  - `install.yaml          # from this repo`
  - `kustomization.yaml`
  - `gotk-patches`
    - `helm-controller-certs-patch.yaml`
    - `notification-controller-certs-patch.yaml`
    - `source-controller-certs-patch.yaml`

---

I applied that with:

`kubectl apply -k .\flux\flux-system\`

looked inside the sourceccontroller:

`kubectl get pods -A && kubectl exec -it source-controller-f9968848f-nhzcd -n flux-system -- /bin/sh`

And checked whether the file is there (/etc/ssl/certs/Company-Root-CA.crt)  and has the correct content. 

```
-rw-r--r--    1 root     1337          1732 Jun 13 06:01 Company-Root-CA.crt
```
So the cmds have worked so far. I then checked whether the error had been rectified. **Unfortunately, the error still appears:**

```
kubectl apply -f \test\msteams.yaml
helmrepository.source.toolkit.fluxcd.io/prometheus-msteams configured
helmchart.source.toolkit.fluxcd.io/prometheus-msteams unchanged
flux get sources chart -A -w
NAMESPACE       NAME    REVISION        SUSPENDED       READY   MESSAGE
default prometheus-msteams              False   False   chart pull error: failed to download chart for remote reference: Get "https://github.com/prometheus-msteams/prometheus-msteams/releases/download/prometheus-msteams-1.3.4/prometheus-msteams-1.3.4.tgz": tls: failed to verify certificate: x509: certificate is valid for github.com, www.github.com, not prometheus-msteams.github.io
```
> tls: failed to verify certificate: x509: certificate is valid for github.com, www.github.com, not prometheus-msteams.github.io

What i've noticed while i applied the patch:

```
Warning: would violate PodSecurity 
"restricted:latest": allowPrivilegeEscalation != false (container "init-source-controller-certs" must set securityContext.allowPrivilegeEscalation=false), 
unrestricted capabilities (container "init-source-controller-certs" must set securityContext.capabilities.drop=["ALL"]),
runAsNonRoot != true (pod or container "init-source-controller-certs" must set securityContext.runAsNonRoot=true), 
seccompProfile (pod or container "init-source-controller-certs" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")

deployment.apps/source-controller configured
```

---

#### z-scaler-ca.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: z-scaler-ca
  namespace: flux-system
data:
  Company-Root-CA.crt: |+
    -----BEGIN CERTIFICATE-----
    MIIxxxxxx
    -----END CERTIFICATE-----
```

#### kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - z-scaler-ca.yaml
  - install.yaml
patches:
  - path: gotk-patches/helm-controller-certs-patch.yaml
  - path: gotk-patches/notification-controller-certs-patch.yaml
  - path: gotk-patches/source-controller-certs-patch.yaml
```

#### source-controller-certs-patch.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          volumeMounts:
            - name: cert-volume
              mountPath: /etc/ssl/certs/Company-Root-CA.crt
              subPath: Company-Root-CA.crt
              readOnly: false
      initContainers:
        - name: init-source-controller-certs
          image: debian
          command:
            ["sh", "-c", 'echo "$TRUSTED_CERT" > /var/tmp/Company-Root-CA.crt']
          env:
            - name: TRUSTED_CERT
              valueFrom:
                configMapKeyRef:
                  name: z-scaler-ca
                  key: Company-Root-CA.crt
          volumeMounts:
            - name: cert-volume
              mountPath: /var/tmp
      volumes:
        - name: cert-volume
          emptyDir: {}
```

#### helm-controller-certs-patch.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          volumeMounts:
            - name: cert-volume
              mountPath: /etc/ssl/certs/Company-Root-CA.crt
              subPath: Company-Root-CA.crt
              readOnly: false
      initContainers:
        - name: init-helm-controller-certs
          image: debian
          command:
            ["sh", "-c", 'echo "$TRUSTED_CERT" > /var/tmp/Company-Root-CA.crt']
          env:
            - name: TRUSTED_CERT
              valueFrom:
                configMapKeyRef:
                  name: z-scaler-ca
                  key: Company-Root-CA.crt
          volumeMounts:
            - name: cert-volume
              mountPath: /var/tmp
      volumes:
        - name: cert-volume
          emptyDir: {}
```

#### notification-controller-certs-patch.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          volumeMounts:
            - name: cert-volume
              mountPath: /etc/ssl/certs/Company-Root-CA.crt
              subPath: Company-Root-CA.crt
              readOnly: false
      initContainers:
        - name: init-notification-controller-certs
          image: debian
          command:
            ["sh", "-c", 'echo "$TRUSTED_CERT" > /var/tmp/Company-Root-CA.crt']
          env:
            - name: TRUSTED_CERT
              valueFrom:
                configMapKeyRef:
                  name: z-scaler-ca
                  key: Company-Root-CA.crt
          volumeMounts:
            - name: cert-volume
              mountPath: /var/tmp
      volumes:
        - name: cert-volume
          emptyDir: {}
```

#### msteams.yaml

```
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-msteams
  namespace: default
spec:
  interval: 1m
  url: https://prometheus-msteams.github.io/prometheus-msteams
  certSecretRef:
    name: z-scaler-ca
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: prometheus-msteams
  namespace: default
spec:
  interval: 1m0s
  chart: prometheus-msteams
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: prometheus-msteams
  version: '1.*.*'
```
