### ISSUE TITLE
issue in Drift Detection

### ISSUE THREAD

**Issue by cyberjpb1** [fluxcd/flux2#4960]
### Describe the bug

The Drift detection/correction seems to work well and if I try to change for example the replicas in the Deployment manifest directly in the cluster, FluxCD will put back the original value contained in the Git repo.

But in case I add a new container by changing Deployment manifest directly in the cluster, FluxCD/Helm does not seem to detect it.

### Steps to reproduce

Add this YAML code to de Deployment manifest directly in the cluster :

```
        - name: not-evil
          image: 'registry.io/alpine:3.16.0'
          command:
            - sh
            - '-c'
            - echo "I am not evil" ; sleep infinity
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
```

### Expected behavior

Flux should detect the addition of the new container in the deployment manifest and remove it since it does not exist in the Helm Chart deployment manifest under the Git repository.

### OS / Distro

Ubuntu 20.04

### Flux version

v2.3.0

### Flux check

N/A

### Git provider

Azure DevOps Git

### Container Registry provider

Azure Container Registry

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
