### ISSUE TITLE
SOPS decrypt does not work with flux and age key

### ISSUE THREAD

**Issue by k8s-1** [fluxcd/flux2#4982]
### Describe the bug

I'm getting reconcile errors trying to follow the official flux docs on age encryption, similar to #3210 .

```bash
flux logs --level=error --all-namespaces
```

`
2024-09-13T15:02:08.003Z error Kustomization/flux-system.flux-system - Reconciliation failed after 345.707826ms, next try in 10m0s Secret/podinfo/mysecret is SOPS encrypted, configuring decryption is required for this secret to be reconciled
`

### Steps to reproduce

1. install flux
2. generate agekey as documented in https://fluxcd.io/flux/guides/mozilla-sops/
```sh
age-keygen -o age.agekey
```
3. create kubernetes decryption secret
```sh
cat age.agekey |
kubectl create secret generic sops-age \
--namespace=flux-system \
--from-file=age.agekey=/dev/stdin
```
4.
create yaml for secret to encrypt
`kubectl create secret generic mysecret --dry-run=client -oyaml --from-literal foo=bar > basic-auth.yaml`
```sh
cat <<EOF>basic-auth.yaml
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  name: mysecret
EOF
```

5.
Encrypt kubernetes secret with the age public key
```
sops --age=age15nmgt4rdjw0jjj2l5lcw373tw50vw7q4mvt4a4xcj0k7atw5p4zqx3hk8e --encrypt --encrypted-regex '^(data|stringData)$' --in-place basic-auth.yaml 
```
6.
configure flux kustomization to use encryption method
```
flux-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 60m
  path: ./infra/podinfo
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
```

### Expected behavior

No error, flux can decrypt the secret

### OS / Distro

N/A

### Flux version

v2.3.0

### Flux check

```
► checking prerequisites
✔ Kubernetes 1.28.8 >=1.28.0-0
► checking version in cluster
✔ distribution: flux-v2.3.0
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.0.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.3.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.3.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.3.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed
```

### Git provider

Github Enterprise

### Container Registry provider

N/A

### Additional context
`kustomize build .`
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo
---
apiVersion: v1
data:
  values.yaml: |
    replicaCount: 1
kind: ConfigMap
metadata:
  name: values-configmap
  namespace: podinfo
---
apiVersion: v1
data:
  foo: ENC[AES256_GCM,data:oYqhpQ==,iv:HII96pwoas1IqdgpyKEjqWjqZNYtyP0x9aS//gyqHb0=,tag:5R8RIAQsXS/dP6xEGmxDPQ==,type:str]
kind: Secret
metadata:
  name: mysecret
  namespace: podinfo
sops:
  age:
  - enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvK25xZnhNcEd3a0t2SC9l
      c09Fam9FMno2aEQvek4yV25WWWlDQWl4bVQwClB6Nlh0dDRzZ2k5aFcraXY4bDhX
      M3hqTDhhbEt0MnVvRXZZZGpZU0dBRXcKLS0tIGVhL3NwaHVKdmxZekhpbVBxRGpt
      aTI1WElTU2tzODhnTitIUVVic2s2Tk0KA7d9WMGNJO9cCAqsz1Q6dM45/we+0KSm
      kQOebFhMD44/S8G/6QE/98CgJW6fZZyP9oLg3wbR2Ljkw9AUEEjD/Q==
      -----END AGE ENCRYPTED FILE-----
    recipient: age15nmgt4rdjw0jjj2l5lcw373tw50vw7q4mvt4a4xcj0k7atw5p4zqx3hk8e
  azure_kv: []
  encrypted_regex: ^(data|stringData)$
  gcp_kms: []
  hc_vault: []
  kms: []
  lastmodified: "2024-09-13T14:52:08Z"
  mac: ENC[AES256_GCM,data:I3LGc3lVFezo/go1S39Ff6wNYFFn5uWzihFm1hOrRYvhvLMIZnfQ/sFWZiX85MW6cXMOuZPoTLdYk9Z/UfjheuLrvhx7qy9FHZc62fVZ33QD69nkTovhD0BOINyk6bXL6Sj+gl5SJq4A9hd8/LHHDikm7e5doUgC3cChMt6/KeU=,iv:3EJhxd6JupzU4ElRSZaMMmx1qUvbGx9s1t+IT41pTrk=,tag:AkLTN4Avk5nRAuKNiSbh2g==,type:str]
  pgp: []
  version: 3.9.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 60m
  valuesFrom:
  - kind: ConfigMap
    name: values-configmap
    valuesKey: values.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 24h
  url: https://stefanprodan.github.io/podinfo
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
> error Kustomization/flux-system.flux-system

Your repo structure is wrong, the root Kustomization `flux-system` is not suppose to decrypt the secret but the `podinfo` one.

**Comment by k8s-1** [comment]
Hi,

I made a simple structure to reproduce this in https://github.com/k8s-1/flux-basics/tree/main/clusters/my-cluster. Everything works fine (git source, flux kustomization, syncing secret) up until the point of adding encryption.

Please, could you help me understand what is wrong with this setup?

```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sops
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: main
  url: https://github.com/k8s-1/flux-basics
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sops
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./clusters/my-cluster/sops
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: sops
  targetNamespace: default
  timeout: 2m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
```
