### ISSUE TITLE
Unable to upgrade HelmRelease version

### ISSUE THREAD

**Issue by CarmineDeloitte** [fluxcd/flux2#4993]
### Describe the bug

I have configured an oci repository to deploy my private helm chart on a kubernetes cluster: 

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm-repo
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  url: oci://xxx.amazon.com/helm
  provider: aws
 ```

Then I have my HelmRelease setup like this;

```yaml

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-apps
  namespace: apps
spec:
  chart:
    spec:
      chart: "my-apps"
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: flux-system
      version: ">=0.x.x-alpha"

  values: {...}

```

I put the version in this format  ```version: ">=0.x.x-alpha"``` since we deploy helm chart with alpha version on our dev environment for each deployment that we do.

Everything was working fine until our version surpassed the 3rd digit.

Basically, we were able to deploy everything until version 0.1.0-alpha99, when we it the 0.1.0-alpha100, 102, etc 
The only way to make it works is to put the full version, without any ">=" so, something like 0.1.0-alpha100

I tried something like``` version ">=0.1.0-alpha100"``` but it fell back to the 99 version.

I also tried to use a wildcard ( version: "*"), but it doesn't work, I'm getting

```
HelmChart 'flux-system/my-apps' is not ready: chart pull error: failed to get chart version for remote reference: could not locate a version matching provided version string *
```

Am I missing something?

### Steps to reproduce

- Adding on oci repository
- try to create a helm release specifying a version above 2 digits and a greater than and equal to 
- version: ">=0.x.x-alpha"
- In the moment you have a release with 3digits, helmcontroler will not updated it.

### Expected behavior

I'm expecting that the version field can match everything after the version put in place:
version: x.x.x-alpha

### OS / Distro

Kubernetes

### Flux version

2.3.0

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
