### ISSUE TITLE
Kustomize does it support direct variable substitution for resource paths?

### ISSUE THREAD

**Issue by omar-triguii** [fluxcd/flux2#5000]
### Describe the bug

# $DEV/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/$app1/
  - ../../components/$app2/
  - ../../components/$app3

### Steps to reproduce

flux installed!

### Expected behavior

i want to dynamically pass applications names in kustomization. but kustomize as i think gets them only in static way.
any solutions please! 

### OS / Distro

ubuntu

### Flux version

flux: v2.2.3

### Flux check

check

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gecube** [comment]
This is working as designed, on both the kustomize side and the Flux side — but there is an idiomatic Flux pattern that achieves what you want (details below).

**Why `$app1` in `resources:`/`components:` paths can't work:**

1. Kustomize resolves `resources`/`components` entries literally as filesystem paths and deliberately does not support any variable expansion or templating in `kustomization.yaml` — this is one of its explicitly [eschewed features](https://kubectl.docs.kubernetes.io/faq/kustomize/eschewed_features/) ("build-time side effects from CLI args or env variables"). With kustomize v5.8.1:

   ```
   Error: accumulating components: loader.New "must build at directory: not a valid directory:
   evalsymlink failure on '.../components/$app1': no such file or directory"
   ```

2. Flux's [post-build variable substitution](https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-variable-substitution) runs **after** `kustomize build`, on the rendered manifests — so it can never affect paths inside `kustomization.yaml`. Same result via `flux build kustomization ... --dry-run` even with `postBuild.substitute: {app1: ...}` set.

**The pattern that does work — parameterize a child Flux `Kustomization` instead:**

Since a Flux `Kustomization` CR is itself just a manifest, you can put `${app}` in its `metadata.name` and `spec.path` and let a parent Kustomization substitute it post-build:

```yaml
# apps/child-ks.yaml (applied by a parent Kustomization)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: "${app}"
  namespace: flux-system
spec:
  interval: 10m
  path: "./components/${app}"
  prune: true
  sourceRef:
    kind: GitRepository
    name: repo
```

```yaml
# parent Kustomization
spec:
  path: ./apps
  postBuild:
    substitute:
      app: app1   # or substituteFrom a per-cluster ConfigMap
```

Verified with flux v2.8.8: the parent renders the child with `name: app1` / `path: ./components/app1`. With `substituteFrom` pointing at a per-cluster ConfigMap you get exactly the "dynamically pass application names" behavior — one repo, per-cluster/env selection of which component paths get reconciled.

Alternatives, depending on your workflow:

- Keep per-env overlays static (list the components each env needs) — this is the kustomize-native answer and the easiest to review in Git.
- Generate the overlay `kustomization.yaml` in CI with `kustomize edit add component ../../components/$APP` before committing/pushing.

Since this is a usage question rather than a bug, it can probably be closed (or moved to Discussions).

cc @matheuscscp
