### ISSUE TITLE
help: go-git failed to checkout with tag and unstaged changes

### ISSUE THREAD

**Issue by khareyash05** [fluxcd/flux2#5027]
### Describe the bug

To set the context, we have a flux cd setup 
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: api-server-staging
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/......
  ref:
    branch: main
---
```
Since flux uses go-git, we are facing issue of 
`failed to checkout and determine revision: unable to checkout tag 'vX.X.X': worktree contains unstaged changes`

We did a backtrack of where this issue is and found it in https://github.com/fluxcd/pkg/blob/ac1007b57e37838e73b8bc95365dab9a0e856e8e/git/gogit/clone.go#L382

We then isolated it and created our own program simulating the same, and were able to replicate the issue.It looks like that go-git is able to checkout the code but not able to go to that specific tag because it does a sort of  `soft reset` ie. if we checkout 0.7.3 all the future commits to the branch move to the staging area and thus the former issue of `unstaged changes`

We want to create a Helm Chart citing the latest release , but since it fails at this step, we arent able to proceed further

### Steps to reproduce

Configure FluxCD for your environment

### Expected behavior

Cloning is done with working tree clean

### OS / Distro

Ubuntu

### Flux version

Latest

### Flux check

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
