### ISSUE TITLE
Flux and namespace issue

### ISSUE THREAD

**Issue by vacquah** [fluxcd/flux2#5033]
### Describe the bug

When flux deploys the cilium gateway api code below, it ends up in the kube-system namespace even when I set it to the "gateway" namespace ( which is already created ).  I had to manually apply  the gateway code below to make sure it ends up in the "gateway" namespace as intended. Did I miss any step?

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: shared-http-gateway
  namespace: gateway
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTP
      port: 80
      name: shared-gw
      hostname: "test.example.com"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-gateway-access: "true"

```

### Steps to reproduce

See description above

### Expected behavior

the gateway should be deployed into the "gateway" namespace

### OS / Distro

Ubunutu 24.04

### Flux version

v2.4.0

### Flux check

% flux check
► checking prerequisites
✔ Kubernetes 1.30.5+rke2r1 >=1.28.0-0
► checking version in cluster
✔ distribution: flux-v2.4.0
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.1.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.39.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.33.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.4.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.4.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.4.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

Github

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
