### ISSUE TITLE
traefik's HelmRelease stuck with 'Running 'install' action with timeout of 5m0s'

### ISSUE THREAD

**Issue by RoFz** [fluxcd/flux2#5052]
### Describe the bug

A vanilla (no custom values) installation of traefik's helm chart (version 33.0.0) via flux's HelmRelease leads to a successful deployment but an incorrect status on flux.

The HelmRelease moves from _Running 'install' action with timeout of 5m0s_ to _Helm install failed for release traefik/traefik with chart traefik@33.0.0: context deadline exceeded_.

Traefik's resources are correctly deployed (i.e. I cannot find any evidence about issues in the resources - kubectl describe/logs).

It seems that flux is unable to correctly identify when this particular helm chart finished its installation.

### Steps to reproduce

1. Install flux
```
❯ flux version
flux: v2.4.0
distribution: flux-v2.4.0
helm-controller: v1.1.0
kustomize-controller: v1.4.0
notification-controller: v1.4.0
source-controller: v1.4.1
```
2. Follow [this](https://github.com/fluxcd/flux2-kustomize-helm-example/tree/main) flux's directory hierarchy
3. infrastructure.yaml:
```yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 1m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers
  prune: true
  wait: true
```
4. ./infrastructure/controllers/kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics-server.yaml
  - traefik.yaml
  - cert-manager.yaml
```
5. ./infrastructure/controllers/traefik.yaml:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    toolkit.fluxcd.io/tenant: rofz
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: traefik
      version: "33.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 5m
  releaseName: traefik
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
```

Note 1: also tried with _test.enabled=false_ and got the same result.
Note 2: it's 100% reproducible in my cluster.

### Expected behavior

```
Every 2.0s: flux get all -A                                                                                                                                            RoFz-iMac.local: Thu Oct 31 21:35:31 2024

NAMESPACE       NAME                            REVISION                SUSPENDED       READY   MESSAGE
flux-system     gitrepository/flux-system       main@sha1:c2f7de10      False           True    stored artifact for revision 'main@sha1:c2f7de10'

NAMESPACE       NAME                            REVISION        SUSPENDED       READY   MESSAGE
cert-manager    helmrepository/cert-manager     sha256:9ea0a563 False           True    stored artifact: revision 'sha256:9ea0a563'
kube-system     helmrepository/metrics-server   sha256:2062cf07 False           True    stored artifact: revision 'sha256:2062cf07'
traefik          helmrepository/traefik           sha256:fdb7e677 False           True    stored artifact: revision 'sha256:fdb7e677'


NAMESPACE       NAME                                    REVISION        SUSPENDED       READY   MESSAGE
cert-manager    helmchart/cert-manager-cert-manager     v1.16.1         False           True    pulled 'cert-manager' chart with version 'v1.16.1'
kube-system     helmchart/kube-system-metrics-server    3.12.2          False           True    pulled 'metrics-server' chart with version '3.12.2'
traefik          helmchart/traefik-traefik                 33.0.0          False           True    pulled 'traefik' chart with version '33.0.0'


NAMESPACE       NAME                            REVISION        SUSPENDED       READY   MESSAGE
cert-manager    helmrelease/cert-manager        v1.16.1         False           True    Helm install succeeded for release cert-manager/cert-manager.v1 with chart cert-manager@v1.16.1
kube-system     helmrelease/metrics-server      3.12.2          False           True    Helm upgrade succeeded for release kube-system/metrics-server.v2 with chart metrics-server@3.12.2
traefik          helmrelease/traefik              33.0.0          False           True  Helm install succeeded for release...


NAMESPACE       NAME                            REVISION                SUSPENDED       READY   MESSAGE
flux-system     kustomization/flux-system       main@sha1:c2f7de10      False           True    Applied revision: main@sha1:c2f7de10
flux-system     kustomization/infra-controllers main@sha1:c2f7de10      False           True    Applied revision: main@sha1:c2f7de10
flux-system      kustomization/infra-controllers main@sha1:c567ab11      False           True  Applied revision: main@sha1:c2f7de10
```

### Screenshots and recordings

```
Every 2.0s: flux get all -A                                                                                                                                            RoFz-iMac.local: Thu Oct 31 21:22:33 2024

NAMESPACE       NAME                            REVISION                SUSPENDED       READY   MESSAGE
flux-system     gitrepository/flux-system       main@sha1:89638439      False           True    stored artifact for revision 'main@sha1:89638439'

NAMESPACE       NAME                            REVISION        SUSPENDED       READY   MESSAGE
cert-manager    helmrepository/cert-manager     sha256:9ea0a563 False           True    stored artifact: revision 'sha256:9ea0a563'
kube-system     helmrepository/metrics-server   sha256:2062cf07 False           True    stored artifact: revision 'sha256:2062cf07'
traefik          helmrepository/traefik           sha256:fdb7e677 False           True    stored artifact: revision 'sha256:fdb7e677'

NAMESPACE       NAME                                    REVISION        SUSPENDED       READY   MESSAGE
cert-manager    helmchart/cert-manager-cert-manager     v1.16.1         False           True    pulled 'cert-manager' chart with version 'v1.16.1'
kube-system     helmchart/kube-system-metrics-server    3.12.2          False           True    pulled 'metrics-server' chart with version '3.12.2'
traefik          helmchart/traefik-traefik                 33.0.0          False           True    pulled 'traefik' chart with version '33.0.0'

NAMESPACE       NAME                            REVISION        SUSPENDED       READY   MESSAGE
cert-manager    helmrelease/cert-manager        v1.16.1         False           True    Helm install succeeded for release cert-manager/cert-manager.v1 with chart cert-manager@v1.16.1
kube-system     helmrelease/metrics-server      3.12.2          False           True    Helm upgrade succeeded for release kube-system/metrics-server.v2 with chart metrics-server@3.12.2
traefik          helmrelease/traefik              33.0.0          False           Unknown Running 'install' action with timeout of 5m0s

NAMESPACE       NAME                            REVISION                SUSPENDED       READY   MESSAGE
flux-system      kustomization/flux-system        main@sha1:89638439      False           True    Applied revision: main@sha1:89638439
flux-system      kustomization/infra-controllers main@sha1:c567ab11      False           Unknown Reconciliation in progress
```

### OS / Distro

macOS Sonoma 14.5 + Docker Desktop 4.34.3 (170107) + Kubernetes v1.30.2 + minikube v1.34.0

### Flux version

flux: v2.4.0

### Flux check

❯ flux check
► checking prerequisites
✔ Kubernetes 1.31.0 >=1.28.0-0
► checking version in cluster
✔ distribution: flux-v2.4.0
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.1.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.4.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.4.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.4.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

GitHub (personal)

### Additional context

``` 
2024-10-31T21:31:29.743Z info GitRepository/flux-system.flux-system - no changes since last reconcilation: observed revision 'main@sha1:89638439ada68d15a6e06a8183137ab941b7a41f' 
2024-10-31T21:32:29.051Z info GitRepository/flux-system.flux-system - no changes since last reconcilation: observed revision 'main@sha1:89638439ada68d15a6e06a8183137ab941b7a41f' 
2024-10-31T21:33:30.849Z info GitRepository/flux-system.flux-system - no changes since last reconcilation: observed revision 'main@sha1:89638439ada68d15a6e06a8183137ab941b7a41f' 
2024-10-31T21:34:35.498Z info GitRepository/flux-system.flux-system - stored artifact for commit 'chore: no traefik' 
2024-10-31T21:35:34.179Z info GitRepository/flux-system.flux-system - garbage collected 1 artifacts 
2024-10-31T21:35:35.435Z info GitRepository/flux-system.flux-system - no changes since last reconcilation: observed revision 'main@sha1:c2f7de105568a0861a7d799b0efff0347d776746' 
2024-10-31T21:36:34.589Z info GitRepository/flux-system.flux-system - no changes since last reconcilation: observed revision 'main@sha1:c2f7de105568a0861a7d799b0efff0347d776746' 
2024-10-31T21:37:36.573Z info GitRepository/flux-system.flux-system - no changes since last reconcilation: observed revision 'main@sha1:c2f7de105568a0861a7d799b0efff0347d776746' 
2024-10-31T21:38:38.870Z info GitRepository/flux-system.flux-system - no changes since last reconcilation: observed revision 'main@sha1:c2f7de105568a0861a7d799b0efff0347d776746' 
2024-10-31T21:39:40.895Z info GitRepository/flux-system.flux-system - no changes since last reconcilation: observed revision 'main@sha1:c2f7de105568a0861a7d799b0efff0347d776746' 
2024-10-31T21:40:44.174Z info GitRepository/flux-system.flux-system - stored artifact for commit 'chore: traefik' 
2024-10-31T21:41:44.429Z info GitRepository/flux-system.flux-system - garbage collected 1 artifacts 
2024-10-31T21:41:45.691Z info GitRepository/flux-system.flux-system - no changes since last reconcilation: observed revision 'main@sha1:1960889e9f1581cfae87f87d5d13db47253a6826' 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
