### ISSUE TITLE
Helm chart with OCI dependency does not reconcile

### ISSUE THREAD

**Issue by MartinEmrich** [fluxcd/flux2#5100]
### Describe the bug

I tried to install another component from the Bitnami helm chart libary, "kubernetes-event-exporter".
But it won't install/reconcile, instead the HelmRelease get stuck in
```
HelmChart 'kube-system/kube-system-kubernetes-event-exporter' is not ready: latest generation of object has not been reconciled
```

The HelmChart itself complains:
```
chart pull error: failed to download chart for remote reference: Get "oci://registry-1.docker.io/bitnamicharts/kubernetes-event-exporter:3.2.16": unsupported protocol scheme "oci"
``` 

The only place where I found that "oci://registry-1.docker.io" URL is in the Bitnami helm repository *index.yaml* (https://charts.bitnami.com/bitnami/index.yaml)

Another, older helm chart from Bitnami (external-dns:6.8.2) has the same dependency, but has a http:// URL at that place, and that installs fine.

Should Flux be able to follow these oci:// dependency URLs?

### Steps to reproduce

1. Install Flux 2.4.0
2. install this example containing a HelmRepository for the Bitnami repo, and two HelmReleases:

```
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: kube-system
spec:
  interval: 1h
  provider: generic
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-event-exporter
  namespace: kube-system
spec:
  chart:
    spec:
      chart: kubernetes-event-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: kube-system
      version: 3.2.16
  interval: 60m
  timeout: 2m
  values:
    config:
      logFormat: json
      logLevel: info
      maxEventAgeSeconds: 10
      receivers:
      - file:
          path: /dev/stdout
        layout:
          component: '{{ .Source.Component }}'
          count: '{{ .Count }}'
          host: '{{ .Source.Host }}'
          kind: '{{ .InvolvedObject.Kind }}'
          message: '{{ .Message }}'
          name: '{{ .InvolvedObject.Name }}'
          namespace: '{{ .Namespace }}'
          reason: '{{ .Reason }}'
          type: '{{ .Type }}'
        name: dump
      route:
        routes:
        - match:
          - receiver: dump
    replicas: 1
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: '>=6.0.0 <7.0.0'
  interval: 15m
  values:
    policy: upsert-only
    provider: coredns
    registry: txt
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 256Mi
    serviceAccount:
      create: true
      name: external-dns
    sources:
    - service
    - ingress
    txtOwnerId: demo
```

The `kubernetes-event-exporter` HR will fail as described. The `external-dns` one will apply (though not reconcile, as the configuration is just some bogus for this demo).

### Expected behavior

Should either reconcile the HelmRelease, or provide a more direct error (like "Helm Charts with dependencies on OCI registries not supported").

### OS / Distro

Both AWS/EKS 1.30 as well as K3s 1.31

### Flux version

v2.4.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.31.2-eks-7f9249a >=1.28.0-0
► checking version in cluster
✔ distribution: flux-v2.4.0
✔ bootstrapped: false
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.1.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.39.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.33.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.4.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.4.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.4.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

N/A

### Container Registry provider

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Should be like this:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kubernetes-event-exporter
  namespace: kube-system
spec:
  interval: 1h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://registry-1.docker.io/bitnamicharts/kubernetes-event-exporter
  ref:
    semver: "3.2.x" # check for new patch versions every hour
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-event-exporter
  namespace: kube-system
spec:
  releaaseName: kubernetes-event-exporter
  chartRef:
    kind: OCIRepository
    name: kubernetes-event-exporter
```

**Comment by stefanprodan** [comment]
sub-chart dependencies are a build time concern, when you do `helm push oci://....` all sub-charts are bundled in the OCI artifact.

**Comment by MartinEmrich** [comment]
You are right, I used the word "dependency" wrong. I meant the helm repository. The (old) HTTP repo index.yaml contains:

````
  kubernetes-event-exporter:
  - annotations:
      category: Infrastructure
      images: |
        - name: kubernetes-event-exporter
          image: docker.io/bitnami/kubernetes-event-exporter:1.7.0-debian-12-r19
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 1.7.0
    created: "2024-12-04T06:04:53.909506237Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Kubernetes Event Exporter makes it easy to export Kubernetes events
      to other tools, thereby enabling better event observability, custom alerts and
      aggregation.
    digest: bbf636ab007d3bfb38fa9b932e0c89b45d71b6762c60b509815bfa4207586e9d
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/kubernetes-event-exporter/img/kubernetes-event-exporter-stack-220x234.png
    keywords:
    - alerting
    - event exporting
    - events
    - kubernetes events
    - monitoring
    - observability
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: kubernetes-event-exporter
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/kubernetes-event-exporter
    urls:
    - oci://registry-1.docker.io/bitnamicharts/kubernetes-event-exporter:3.2.16
    version: 3.2.16
````
So by "mixing" I meant having a `HelmRepository` with an https:// URL configured, but which references the actual chart artefacty by `oci://` URLs as in this example.

And your example worked, but I reworked it to use a HelmRepository. This works for me now (by consuming both the Repository index and the artefacts from the OCI registry), as I prefer having the version spec on the HelmReleases:

````
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-oci
  namespace: kube-system
spec:
  interval: "1h"
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-event-exporter
  namespace: kube-system
spec:
  values: "<removed for bevity>"
  interval: 60m
  timeout: 2m
  chart:
    spec:
      chart: kubernetes-event-exporter
      version: '3.2.16'
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: kube-system
````

Thanks again. If the behaviour is not a bug per se (but rather a non-standard behaviour of the URL mix in the Bitnami index file), I'll be happy to close this.
