### ISSUE TITLE
Helmrepository ready state is keeping false when use "oci" type

### ISSUE THREAD

**Issue by wei-z-git** [fluxcd/flux2#5149]
### Describe the bug

When I use helmrepository with "oci" type, the ready state is keeping false and shows "waiting to be reconciled"
But it could download the chart and installed successfully

Helmrepository Configurations:
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: default
spec:
  url: oci://<acr server>/helm-charts
  type: "oci"
  interval: 1440m #1day
  provider: azure
```

Helmrelease configurations:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 5m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  targetNamespace: grafana
  chart:
    spec:
      chart: grafana
      version: "8.3.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: default
```

Helmrepository state:
```
runtime@monitoring-preprd-admin:~f get sources helm  |grep grafana
grafana                                                         False           False   waiting to be reconciled   
```

Helmrelease state:
```
flux get helmreleases grafana 
NAME    REVISION        SUSPENDED       READY   MESSAGE                                                                                
grafana 8.3.2           False           True    Helm install succeeded for release grafana/grafana-grafana.v1 with chart grafana@8.3.2
```

### Steps to reproduce

1 Push chart into Azure ACR
2 install the helmrepository above
3 install the helmrelease above
4 flux get helm grafana, it shows the false state
```
runtime@monitoring-preprd-admin:~f get sources helm  grafana
NAME    REVISION        SUSPENDED       READY   MESSAGE                  
grafana                 False           False   waiting to be reconciled
```

### Expected behavior

When excute `flux get helm grafana`, it shows normal state

### OS / Distro

Ubuntu20.04

### Flux version

0.40.2

### Flux check

flux 0.40.2 <2.4.0 (new version is available, please upgrade)
✔ Kubernetes 1.30.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.37.4
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.37.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.31.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.2.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.2.4
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.2.4
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta2
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
