### ISSUE TITLE
[feature] allow more helm value sources

### ISSUE THREAD

**Issue by simonostendorf** [fluxcd/flux2#5167]
I would like to get helm values from other sources than ConfigMap or Secrets.

I think it would be really useful to allow every kind of kubernetes resource and specify a path where the value should be read from.

Example:

I have a CRD called `MyProviderNetwork`. The controller for this crd creates a new cloud provider network in the background and writes the id to `.status.networkId`. It would be really cool to read this value as a flux value.

Example Configuration for Flux:

```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
...
spec:
  valuesFrom:
    - kind: MyProviderNetwork
      name: resource-name
      valuesKey: helmValueWhereNetworkIdShouldBeWritten
      path: .status.networkId
      optional: false
```

**Comment by stefanprodan** [comment]
We'll need a diffrent field if we want to do this, as we can't break the current API. You can't refer to a custom resource by `kind`, you also need the exact `apiVersion`. In your example, you mixed up `valuesKey`, this field points to `.data` inside the ConfigMap/Secret, also there is no `path`, it's `targetPath` and this points to the Helm values. Docs here: https://fluxcd.io/flux/components/helm/helmreleases/#values 

My proposal would be to add a dedicated section  `valuesFromResource` e.g.

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
...
spec:
  valuesFromResource:
    - apiVersion: network.foo.bar/v1
      kind: NetworkProvider
      name: my-network
      sourcePath: "/status/networkID" # JSONPath for querying the custom resource 
      targetPath: "network.id" # YAML dot notation to the Helm values field
      optional: false
```

I'm not sure if JSONPath is the best query language, maybe CEL would be better.
