### ISSUE TITLE
GitRepository resource should not require double quotes for `commit` field

### ISSUE THREAD

**Issue by sgutwein** [fluxcd/flux2#5198]
## Describe the bug
When specifying a commit SHA in the `spec.ref.commit` field of a `GitRepository` resource, the value must be enclosed in double quotes. If not, the resource fails to apply correctly. This behavior is unexpected, as commit SHAs are alphanumeric strings that typically do not require quoting.

## To Reproduce
1. Create a `GitRepository` resource with the `commit` field specified without double quotes:
   ```yaml
   apiVersion: source.toolkit.fluxcd.io/v1
   kind: GitRepository
   metadata:
     name: my-repo
     namespace: flux-system
   spec:
     interval: 1m
     url: https://github.com/my-org/my-repo
     ref:
       commit: abcdef1234567890abcdef1234567890abcdef12
   ```
2. Apply the resource using `kubectl apply -f my-repo.yaml`.
3. Observe that the resource fails to apply with an error:
```
failed to checkout and determine revision: unable to clone 'https://github.com/my-org/my-repo': context deadline exceeded
```

## Expected behavior
The `GitRepository` resource should accept the `commit` field without requiring double quotes around the commit SHA.

## Additional context
- **Flux version**: v2.4.0
- **Kubernetes version**: v1.28.8
- **Git provider**: GitHub

## Suggestion
Modify the schema validation for the `commit` field in the `GitRepository` resource to accept unquoted alphanumeric strings.

**Additional Note on kubectl Behavior:**
When applying the GitRepository resource using `kubectl apply -f`, any double quotes around the commit SHA are **automatically removed**. This happens because Kubernetes processes YAML values according to its internal schema and omits unnecessary quotes for simple string values. Even explicitly specifying `!!str` in YAML does not prevent kubectl from stripping the quotes. This behavior can cause issues when Flux expects the commit SHA to be enclosed in quotes.

If the GitRepository resource requires the commit SHA in double quotes, there should be a way to ensure that kubectl does not alter this formatting.

**Comment by matheuscscp** [comment]
Works for me:

```yaml
k apply -f - <<EOF
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/my-org/my-repo
  ref:
    commit: abcdef1234567890abcdef1234567890abcdef12
EOF
gitrepository.source.toolkit.fluxcd.io/my-repo created
```
