### ISSUE TITLE
Improvement request: `NetworkPolicy` settings

### ISSUE THREAD

**Issue by t-khr** [fluxcd/flux2#5218]
I suggest improving the documentation about default `NetworkPolicy` settings.

## Situation

Currently, when bootstrapping Flux CD, several `NetworkPolicy` rules are installed by default:
- allow-egress
- allow-scraping
- allow-webhooks
See more: https://fluxcd.io/flux/flux-e2e/#fluxs-default-configuration-for-networkpolicy

While it's possible to disable this behavior using the `--network-policy false` switch, this is not officially recommended.
See more: https://fluxcd.io/flux/installation/configuration/optional-components/#network-policies

The Flux CD `Deployments` use `Liveness/Readiness` probes, which are exposed on ports `9440` or `9090`.

In the default configuration, `kubelet` cannot reach these probe endpoints because there is no `NetworkPolicy` that allows it.

This causes constant restarts of Flux CD deployments by Kubernetes, as they are considered unhealthy.

--
To fix this behavior, we created a special `NetworkPolicy` in our cluster that allows `kubelet` to reach ports `9440` or `9090` of the Flux CD deployments.

Here's an example of the policy file:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-health-checks
  namespace: flux-system
spec:
  ingress:
  - ports:
    - port: 9440
      protocol: TCP
    - port: 9090
      protocol: TCP
    from:
    - ipBlock:
         # GKE master CIDR range
        cidr: 172.16.0.0/28
    - ipBlock:
        # GKE nodes CIDR range
        cidr: 10.0.0.0/8
  podSelector: {}
  policyTypes:
  - Ingress
```

## Suggestions:

1. Explicitly document that it's necessary to create a `NetworkPolicy` to allow access to healthcheck endpoints, or alternatively suggest disabling network policies via `--network-policy false`.

2. The healthcheck ports differ between deployments (`9440` or `9090`).
   - Consider standardizing to use the same port for all deployments
   - Document these port numbers officially

3. Consider automating the policy creation with new flags that allow passing node CIDR ranges to authorize ingress for healthchecks.

--
Note: There is a related issue that was closed without resolution/answer: https://github.com/fluxcd/source-controller/issues/1290.

## Version
Flux CD version: 2.4.0

**Comment by stefanprodan** [comment]
> In the default configuration, kubelet cannot reach these probe endpoints because there is no NetworkPolicy that allows it.

I've never seen this on any clusters where we are running tests and we cover a wide range of configurations including Calico & Cilium on EKS, AKS, GKE, OpenShift, k3s and more.

**Comment by t-khr** [comment]
I understand your remark.

### A little story about it:

1. We are running our clusters at GKE
2. We have been using `Flux CD` for several years
3. We have never seen this behavior before

### The facts:

The same version of `Flux CD` behaves differently in different versions of GKE:
- GKE `1.30.6-gke.1125000`: there is no problem with reaching the healthchecks
- GKE `1.31.1-gke.2105000`: the healthchecks are not reachable by the kubelet, and K8s constantly restarts `Flux CD` workloads
- **After creating the policy** that I've shown above, the problem disappears immediately, and for the moment there are `0` workload restarts

### K8s

AFAIK, after research (I wouldn't claim myself as a K8s expert though):
1. By default (without any NetworkPolicy defined):
   - All Pods can communicate freely with each other within the cluster.
   - Any external entity that can reach the cluster network can communicate with the Pods.

2. When you define at least one NetworkPolicy in a namespace:
   - Any Pod that is selected by at least one NetworkPolicy will only allow traffic explicitly allowed by the policies.
   - Pods not selected by any NetworkPolicy will continue to allow all traffic (both ingress and egress).

---
I think, even if you are running tests across a wide range of K8s implementations, you cannot cover ALL versions.

Probably, this question should be addressed to K8s experts, but the fact is that this policy is necessary, and it seems we are not alone.

**Comment by stefanprodan** [comment]
I suggest you call Google support and report this bug in their CNI, the policy for blocking cross-namespace traffic shouldn’t effect kubelet.

**Comment by t-khr** [comment]
I agree with you that this is certainly related to GKE, although I've seen similar issues reported for AWS, Azure...

We have upgraded the cluster to `1.31.5-gke.1169000` and dropped the network policy we had created.
For the moment, there are no probe errors or related workload restarts. We will continue to monitor `Flux` to ensure that the issue does not return.

For notes, the installation details:

* GKE private cluster `1.31.1-gke.2105000`
* Enabled `Dataplane V2`

Even though it is certainly related to some issues at the GKE level, I suggest adding notes about this kind of issue and possible resolutions.
This may save somebody hours of research.

**Comment by mltii** [comment]
We're seeing the same issue with:
 - `Dataplane v2`
 -  GKE private cluster `1.32.4-gke.1353003`

@t-khr thank you for reporting this, you've indeed saved me hours of research. I've never seen probes fail because of NetworkPolicy.

I'll follow up if GKE support chooses to comment on that.

**Comment by matheuscscp** [comment]
I've seen that kind of problem in GKE with Data Plane v2 even without running Flux at all inside the cluster

**Comment by adelmoradian** [comment]
I had a similar issue with RKE2 (v1.32.1+rke2r1) and Calico on an on-prem cluster. I'm using flux v2.6.1.

Without network policies on my application's namespace everything works fine. Adding something like this to the application's namespace breaks healtchecks:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-policy
  namespace: my-app
spec:
  policyTypes:
  - Ingress
  - Egress
  Ingress:
  - from:
    - ipBlock:
        cidr: k8s api server endpoints
    ...
  egress:
  - to:
    - ipBlock:
        cidr: k8s api server endpoints
    ...
  ...
``` 

But if add all the worker nodes to the policy, that solves the problem.
