### ISSUE TITLE
flux debug helmrelease Fails to Resolve valuesFrom Secret Reference

### ISSUE THREAD

**Issue by DanielAntos90** [fluxcd/flux2#5221]
### Describe the bug

The new flux debug helmrelease feature fails when resolving valuesFrom references in a HelmRelease. We are using the grafana-k8s-monitoring Helm chart and passing authentication tokens via a Kubernetes Secret. The command fails with an unmarshalling error.

`✗ could not resolve Secret chart values reference 'grafana/grafana-k8s-monitoring-helm-values-secret' with key 'accessPolicyToken': error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type chartutil.Values
`

I have also tried podinfo helm chart without kind: Secret and it works fine.

### Steps to reproduce

1. Create a Kubernetes Secret with a key-value pair:

```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-k8s-monitoring-helm-values-secret
data:
  accessPolicyToken: my-secret-token-base-64
type: Opaque
```

2.Reference the secret in a HelmRelease

```
spec:
  valuesFrom:
    - kind: Secret
      name: grafana-k8s-monitoring-helm-values-secret
      valuesKey: accessPolicyToken
      targetPath: externalServices.prometheus.basicAuth.password
```

3.Run flux debug helmrelease <helmrelease-name>.
4.Observe the error.

### Expected behavior

The flux debug helmrelease command should successfully resolve the valuesFrom reference and apply the secret value without errors.

### OS / Distro

macOS 15.3.1

### Flux version

v2.5.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.30.10 >=1.30.0-0
► checking version in cluster
✔ distribution: flux-v2.5.1
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.2.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.5.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.5.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.5.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

GitHub

### Container Registry provider

GitHub 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
