### ISSUE TITLE
Imageupdate Automation deploys k8s ressources, then just deletes them during reconciliation

### ISSUE THREAD

**Issue by croneter** [fluxcd/flux2#5222]
### Describe the bug

Some automations work just fine, some do not and fail to deploy the respective k8s ressources or delete them during reconciliation. I fail to spot any differences between the ones failing and the ones working fust fine :-(

These resources seem to be deployed, but then get deleted during reconciliation:
```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: calibre
  namespace: calibre
spec:
  image: lscr.io/linuxserver/calibre
  interval: 118m57s

---

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: calibre
  namespace: calibre
spec:
  imageRepositoryRef:
    name: calibre
    namespace: calibre
  filterTags:
    pattern: '^\d+\.\d+\.\d+$'
  policy:
    semver:
      range: '>=6.0.0'

---

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: calibre
  namespace: calibre
spec:
  interval: 118m57s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.gitlab.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: calibre
  update:
    path: ./apps/base/admin/calibre
    strategy: Setters
```

Restarting the flux deployments in the flux-system namespace and QUICKLY checking for the above yields:
```bash
$ flux get images all --all-namespaces
NAMESPACE       NAME                            LAST SCAN                       SUSPENDED       READY   MESSAGE
...
calibre         imagerepository/calibre                                         False           False   waiting to be reconciled
...


NAMESPACE       NAME                            LATEST IMAGE                                            READY   MESSAGE
...
(no calibre imagepolicy)
...

NAMESPACE       NAME                                    LAST RUN                        SUSPENDED       READY   MESSAGE
...
calibre         imageupdateautomation/calibre                                           False           False   waiting to be reconciled
...
```
5 seconds later, the imagerepository and imageupdateautomation ressources are simply deleted and don't show up anymore using `flux get images all --all-namespaces`

I don't find anything useful in the flux logs. I even took a working automation, copy-pasted the YAMLs and just changed the names to calibre - did not work either. 

### Steps to reproduce

Sorry, can't reproduce as I fail to see why some automations work, others do not. ~~However, restarting flux reproduces the above behavior: `kubectl rollout restart -n flux-system deployment.apps/kustomize-controller `~~

### Expected behavior

Automations working OR meaningful error messages ;-). 

### OS / Distro

Talos 1.9.4

### Flux version

2.5.1

### Flux check

```bash
$ flux check
► checking prerequisites
✔ Kubernetes 1.31.6 >=1.30.0-0
► checking version in cluster
✔ distribution: flux-v2.5.1
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.2.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.5.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.5.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.5.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed
```

### Git provider

GitLab

### Container Registry provider

n/a

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
