### ISSUE TITLE
Validation of (not yet) available CRDs break flux bootstrap

### ISSUE THREAD

**Issue by IsNull** [fluxcd/flux2#523]
Flux bootstrap forces kustomize validation, but in some scenarios, validation is not easily possible. For example, when HelmReleases or custom Operators install CRDs, flux can not find the CRDs in bootstrap validation phase and fails. ([Strimzi's](https://strimzi.io/) KafkaCluster CRD would be one of these I encountered)

Current work around is to run flux bootstrap and then manually patch the kustomize validation to none `validation: none` in the generated kustomize.yaml, which is not very GitOpsy. :-P

Some ideas to solve this:

* Support a flag to disable validation in the `flux bootstrap` command, so no manual intervention is necessary.
* Even better, support a list of CRDs that should be ignored by validation, so validation can be kept for the standard resources.

**Comment by stefanprodan** [comment]
Flux offers a way to define the reconciliation order with [dependsOn](https://toolkit.fluxcd.io/components/kustomize/kustomization/#kustomization-dependencies), so you can install first the CRDs+controller and then custom resources.

Here is an examples from https://github.com/fluxcd/flux2-multi-tenancy

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/kyverno
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno
      namespace: kyverno
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  dependsOn:
    - name: kyverno
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/kyverno-policies
  prune: true
  validation: client
```
