### ISSUE TITLE
Missing metadata.name in object when installing Helm chart from OCI

### ISSUE THREAD

**Issue by rabejens** [fluxcd/flux2#5232]
### Describe the bug

I am trying to install a Helm chart from an OCI repository and get:

`failed to decode Kubernetes YAML from /tmp/kustomization-1456896604/flux/mynamespace/zookeeper.yaml: missing metadata.name in object {{helm.toolkit.fluxcd.io/v2 HelmRelease} {{ } map[] map[]}} <nil>`

### Steps to reproduce

1. Install Flux 2.4
2. Declare this `HelmRepository`:
```
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: default
spec:
  type: "oci"
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts
```
3. Declare this `HelmRelease`:
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metgadata:
  name: zookeeper
  namespace: default
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: zookeeper
      version: "13.7.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
  releaseName: zookeeper
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  values:
    replicaCount: 3
```
4. Let your setup reconcile

### Expected behavior

Zookeeper is deployed

### Screenshots and recordings

The `flux-system` kustomization fails with:

```
flux-system   7d13h   False   failed to decode Kubernetes YAML from /tmp/kustomization-1456896604/flux/default/zookeeper.yaml: missing metadata.name in object {{helm.toolkit.fluxcd.io/v2 HelmRelease} {{ } map[] map[]}} <nil>
```

### OS / Distro

Ubuntu 24.04

### Flux version

v2.4.0

### Flux check

► checking prerequisites
✗ flux 2.4.0 <2.5.1 (new CLI version is available, please upgrade)
✔ Kubernetes 1.31.5+rke2r1 >=1.28.0-0
► checking version in cluster
✔ distribution: flux-v2.4.0
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.1.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.4.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.4.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.4.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

GitLab

### Container Registry provider

DockerHub

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
