### ISSUE TITLE
[feature] HelmRelease load values from source controller artifact

### ISSUE THREAD

**Issue by hikaru-shindo** [fluxcd/flux2#5238]
**What problem would this feature solve**

Currently we are deploying configuration for the OIDC authentication and authorization (basically a mapping of OIDC user ids to ClusterRoles) of our cluster admins and some read-only users via a helm chart to a fleet of clusters. Most clusters have similar settings (there are only a few different sets).
As it stands now the helm-controller can only get the values (in this case the user id to cluster role mapping list) from either the release itself (values key) or a ConfigMap/Secret which has to be created first (as far as I understand it at least). We'd like to be able to share a set helm value files between different clusters via a separate artifact (which triggers a reconciliation of the user access on each affected cluster without us having to patch the values on each cluster ourselves).

**What feature am I suggesting**

For situations like this it would be nice if the HelmRelease resource/helm-controller could support pulling values from any artifact in the source controller. This could be realized with an API addition similar to this:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
...
spec:
  valuesRef:
    - kind: OCIRepository
      name: my-config
      path: ./admins-only.yaml
```
This design would be similar to sourceRef and chartRef and therefore consistent with other places in flux2.

**What issues might arise?**

The value precedence (values vs valuesFrom vs valuesRef) would need to be discussed. What overrides what?

**Additional Info**

This might (or might not) be a special case as in #5167 at least it points into a similar direction.

ArgoCD would allow to solve this with a multi-source app approach maybe this helps in understanding the problem space a bit better:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  sources:
    - chart: my-chart
      repoURL: https://charts.example.com
      helm:
        valueFiles: 
        - $values/my-custom-values.yaml
    - repoURL: ...
      ref: values
```
