### ISSUE TITLE
Upgrading with flux bootstrap does not preserve GitRepository/Kustomization options

### ISSUE THREAD

**Issue by kowalczykp** [fluxcd/flux2#524]
During the upgrade to 0.4.1, on an existing repository with the previous version of flux2, via `flux bootstrap` custom options on GitRepository( **spec.ignore** ) and Kustomization ( **spec.decryption.provider: sops**) were overwritten by flux with default generated manifests. This happened because flux does not check/rely on existing manifests, just idempotently overwrites all manifests.

A potential workaround for source ignoring could be: using the `.sourceignore` file.

I don't know of any existing workaround for preserving sops decryption. One option would be to add a flag to bootstrap, allowing to specify decryption provider. 

Alternatively, both issues can be addressed, by attempting to preserve those options while bootstrapping, yet this adds complexity. 

I'd be happy to PR a fix for this, once approved as an actual issue.

**Comment by stefanprodan** [comment]
Instead of editing the files in `flux-system` dir, you could customise your installation  as described in the docs https://toolkit.fluxcd.io/guides/installation/#customize-flux-manifests

In your case, `flux-system-patch.yaml` would look like this:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/deploy
    # exclude file extensions from deploy dir
    /deploy/**/*.md
    /deploy/**/*.txt
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  decryption:
    provider: sops
```
