### ISSUE TITLE
Improvement request

### ISSUE THREAD

**Issue by j-garcia-p** [fluxcd/flux2#5241]
### Situation
I have a Helm chart located in a Git repository and that chart has some dependencies located in a private Helm repository. In order to deploy my chart first I'm creating the GitRepository source where the chart is.
```
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: <repo-name>
  namespace: <app-ns>
spec:
  interval: 1m0s
  ref:
    branch: <branch-name>
  secretRef:
    name: <secret-name>
  url: <repository-url>
```
I also create a HelmRepository source of the private helm repo
```
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: <helm-repo-name>
  namespace: flux-system
spec:
  interval: 5m0s
  url: <helm-repository-url>
  secretRef:
    name: <secret-name>
```
When creating a HelmRelease resource in the app namespace I will run into the following error on the HelmChart creation: `dependency build error: failed to add remote dependency '<dependency-chart-name>': failed to get chart '<dependency-chart-name>' version '1.0.2' from '<helm-repo-url>': failed to cache index: failed to cache index to temp │
│ orary file: failed to fetch <helm-repo-url> : 401 Unauthorized`

My HelmRelease resource looks like this:
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: <release-name>
  namespace: <app-ns>
spec:
  interval: 1m
  chart:
    spec:
      chart: <chart-location-inside-the-repo>
      version: <chart-version>
      sourceRef:
        kind: GitRepository
        name: <repo-name>
        namespace: <app-ns>
      interval: 1m
```
Now, this issue can be prevented by creating the HelmRepository resource of the private repo in the app namespace, but I cant have a HelmRepository resource for each namespace. 

### Questions/Suggestions

Is there any way to let the HelmChart/Release communicate with the HelmRepository even though they are in different namespaces?, alternatively, is there any way to provide authentication in the HelmRelease resource so it manages to authenticate with the private repo when trying to resolve the dependencies? (I believe that when the sourceRef is a HelmRepository it should inherit the authentication, but with GitRepository looks like that is not the case)

I'm using flux v2.4.0, with Gitlab as the Git provider and EKS as the K8s solution.

**Comment by Elegant996** [comment]
There are two methods available here depending on if your repo is actually a repo or just contains the _layout_ of a repo.

You may have more success using `GitRepository` and then defining a `HelmChart` that references that repo:

```
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: container-image
spec:
  interval: 24h
  url: https://github.com/warm-metal/container-image-csi-driver
  ref:
    semver: '^2'
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: container-image
spec:
  interval: 12h
  chart: ./charts/warm-metal-csi-driver
  sourceRef:
    name: container-image
    kind: GitRepository
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: container-image
spec:
  interval: 30m
  releaseName: container-image
  chartRef:
    kind: HelmChart
    name: container-image
...
```

Otherwise, you should ensure your error is not due to a misuse/mistyping of the authentication method (try from CLI).
