### ISSUE TITLE
Discord notification failing due to wrong URL string

### ISSUE THREAD

**Issue by salmankhalid-plt** [fluxcd/flux2#5253]
### Describe the bug

I have set up discord channel to receive alerts but the alerts are failing with the following error message 
```
failed to send notification for Kustomization/flux-system/apps: postMessage failed: failed to execute request: 
POST https://discordapp.com/api/webhooks/xxx/xxx/slack giving up after 1 attempt(s): context deadline exceeded 
```
for some reason `/slack` has been appended to the discord URL hence this will fail as this url is invalid 

### Steps to reproduce

1. install flux controller with notification controller 
2. set up a channel in discord and get the web integration url 
3. use the following setup for discord 
```
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: discord-bot
  namespace: flux-system
spec:
  type: discord
  secretRef:
    name: discord-webhook
---
apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
  namespace: flux-system
stringData:
  address: "https://discordapp.com/api/webhooks/xxx/xxx"
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: on-call-webapp
  namespace: flux-system
spec:
  summary: "cluster addons"
  eventMetadata:
    env: "staging"
    cluster: "staging-cluster"
    region: "eu-east-1"
  providerRef:
    name: discord-bot
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
```

### Expected behavior

receive notification on discord 

### OS / Distro

ubuntu

### Flux version

v2.5.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.32.2 >=1.30.0-0
► checking version in cluster
✔ distribution: flux-v2.5.1
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.2.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.40.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.34.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.5.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.5.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.5.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
