### ISSUE TITLE
Helm Upgrade Fails When Template Variables Are In Yaml Field Names

### ISSUE THREAD

**Issue by Nyefan** [fluxcd/flux2#5264]
Helm Upgrade Fails When Template Variables Are In Yaml Field Names

### Describe the bug

An example of a failing chart: https://github.com/bitnami/charts/blob/328166c403f2d3b4a9a548561b25dc43efb7eebf/bitnami/kafka/templates/secrets.yaml#L71

```
...
  {{- range $i := until (int .Values.controller.replicaCount) }}
  controller-{{ $i }}-id: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-kraft" (include "common.names.fullname" $)) "key" "controller-{{ $i }}-id" "providedValues" (list "") "length" 22 "context" $) }}
  {{- end }}
...
```

The output of `k events --for helmrelease/kafka`

```
Last Helm logs:

2025-03-26T12:41:34.436695545Z: preparing upgrade for kafka
2025-03-26T12:41:34.533903676Z: resetting values to the chart's original version
8m19s (x6 over 24m)   Warning   UpgradeFailed        HelmRelease/kafka   (combined from similar events): Helm upgrade failed for release kafka/kafka with chart kafka@32.0.1+2b71ecd47ab5: execution error at (kafka/templates/controller-eligible/statefulset.yaml:42:38): 
PASSWORDS ERROR: The secret "kafka-kraft" does not contain the key "controller-{{ $i }}-id"
```

The output of `flux version`

```
flux: v2.5.1
distribution: flux-v2.5.1
helm-controller: v1.2.0
kustomize-controller: v1.5.1
notification-controller: v1.5.0
source-controller: v1.5.0
```

### Steps to reproduce

1. Apply the following resources to a cluster

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-kafka
  namespace: flux-system
spec:
  interval: 1h #minimize impact on bitnami's servers - users can `flux reconcile` if they manually screw with something
  url: oci://registry-1.docker.io/bitnamicharts/kafka
  ref:
    tag: "32.0.1"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: flux-system
spec:
  interval: 10m #this only hits the locally cached chart registry
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: bitnami-kafka
  releaseName: kafka
  targetNamespace: kafka
  storageNamespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
  values:
    controller:
      persistence:
        size: "512Mi"
      resources:
        requests:
          cpu: 100m
          ephemeral-storage: 50Mi
          memory: 128Mi
        limits:
          cpu: 500m
          ephemeral-storage: 1Gi
          memory: 1Gi
      resourcesPreset: "micro"
    broker:
      persistence:
        size: "512Mi"
      resources:
        requests:
          cpu: 100m
          ephemeral-storage: 50Mi
          memory: 128Mi
        limits:
          cpu: 1
          ephemeral-storage: 2Gi
          memory: 2Gi
      service:
        type: "ClusterIP"
    externalAccess:
      enabled: false
      service:
        type: "ClusterIP"
    provisioning:
      enabled: true
      topics:
        - name: "saasaparilla_notification_received"
          partitions: 1
          replicationFactor: 1
          config:
            max.message.bytes: 64000
            flush.messages: 1
    namespaceOverride: "kafka"
---

```

2. Await reconciliation (installation works, just not upgrades)
3. Edit one of the `.spec.values` of the `HelmRelease`

This behavior persists with any combination of `.spec.upgrade.preserveValues` and `.spec.upgrade.force` in my testing using a kind cluster defined as

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: saasaparilla-notification
# https://github.com/kubernetes-sigs/kind/releases
nodes:
  - role: control-plane
    image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
  - role: worker
    image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
  - role: worker
    image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
  - role: worker
    image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
```

### Expected behavior

The install parser and the upgrade parser should have identical behavior.  Either the bitnami-kafka chart v32.0.1 should fail to install, or a change that does not impact the templating of this section should not block the upgrade.

### OS / Distro

kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f

### Flux version

flux: v2.5.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.32.2 >=1.30.0-0
► checking version in cluster
✔ distribution: flux-v2.5.1
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.2.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.5.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.5.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.5.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

N/A

### Container Registry provider

N/A

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by matheuscscp** [comment]
Can you please check if you can reproduce this using only the `helm` CLI without Flux? We use the Go Helm SDK and don't do any templating logic ourselves, so this could actually be a bug in Helm

**Comment by Nyefan** [comment]
Sure.  It seems this must be upstream.

```yaml
# values.yaml
controller:
  persistence:
    size: "512Mi"
  resources:
    requests:
      cpu: 100m
      ephemeral-storage: 50Mi
      memory: 128Mi
    limits:
      cpu: 500m
      ephemeral-storage: 1Gi
      memory: 1Gi
broker:
  persistence:
    size: "512Mi"
  resources:
    requests:
      cpu: 100m
      ephemeral-storage: 50Mi
      memory: 128Mi
    limits:
      cpu: 500m
      ephemeral-storage: 1Gi
      memory: 1Gi
  service:
    type: "ClusterIP"
externalAccess:
  enabled: false
  service:
    type: "ClusterIP"
provisioning:
  enabled: true
  topics:
    - name: "saasaparilla_notification_received"
      partitions: 1
      replicationFactor: 1
      config:
        max.message.bytes: 64000
        flush.messages: 1
namespaceOverride: "kafka"
```

```shell
> helm install kafka oci://registry-1.docker.io/bitnamicharts/kafka:32.0.2 -f values.yaml --create-namespace --namespace kafka

Pulled: registry-1.docker.io/bitnamicharts/kafka:32.0.2
Digest: sha256:d95d7ba679ba0f61ee85e9d1403ee5041e3fe8f9a9d466ae7c165052c4343945
NAME: kafka
LAST DEPLOYED: Wed Mar 26 10:29:32 2025
NAMESPACE: kafka
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: kafka
CHART VERSION: 32.0.2
APP VERSION: 4.0.0

# NOTES

> helm upgrade kafka oci://registry-1.docker.io/bitnamicharts/kafka:32.0.2 -f values.yaml

Pulled: registry-1.docker.io/bitnamicharts/kafka:32.0.1
Digest: sha256:2b71ecd47ab5293f13d27fab408dd7b2b16588a3578f229bea0b17b963cf52f0
Error: UPGRADE FAILED: execution error at (kafka/templates/controller-eligible/statefulset.yaml:42:38): 
PASSWORDS ERROR: The secret "kafka-kraft" does not contain the key "controller-{{ $i }}-id"
```
