### ISSUE TITLE
[notification/alert] eventSource name may not be longer than 53 characters

### ISSUE THREAD

**Issue by networkhell** [fluxcd/flux2#5265]
### Describe the bug

I just noticed that spec.eventSources.[*].name of an Alert (API notification.toolkit.fluxcd.io/v1beta3) has the strange limitation of 53 chars.

The alert config
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: testalert
  namespace: flux-system
spec:
  summary: "test"
  providerRef:
    name: rocket
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: flux-system
    - kind: GitRepository
      name: '*'
      namespace: garden-runtime-dev-wavestack-muc5
   - kind: HelmChart
      name: 'garden-runtime-staging-wavestack-muc5-garden-runtime-staging'
      namespace: garden-runtime-staging-wavestack-muc5
   - kind: HelmRelease
      name: '*'
      namespace: garden-runtime-staging-wavestack-muc5
``` 

produces the following log / error
```
Alert.notification.toolkit.fluxcd.io "testalert" is invalid: spec.eventSources[3].name: Too long: may not be longer than 53
```

Just to make that clear - I am aware of helms release name limitation of 53 characters. But this is neither a Chart name nor a release name but only the name of the auto generated helmchart CR. 

### Steps to reproduce

1. Install flux with notifocation controller
2. create the alert listed above

### Expected behavior

Flux should not restrict the length of any strings when not technically necessary. 

### OS / Distro

flatcar container linux 4081.3.1

### Flux version

2.5.1

### Flux check

flux check
► checking prerequisites
✔ Kubernetes 1.31.6 >=1.30.0-0
► checking version in cluster
✔ distribution: flux-2.5.1
✔ bootstrapped: false
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.2.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.40.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.34.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.5.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.5.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.5.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
