### ISSUE TITLE
kustomize diff --recursive wrong path for additional local-sources

### ISSUE THREAD

**Issue by bozho** [fluxcd/flux2#5298]
Hi,

I'm testing out a 3-repo architecture for my clusters (infra, apps, fleet).

Locally, I have the 3 repos checked out into a common top-level directory:
```
<some dir>
  search-apps
  search-fleet
  search-infra
```

`search-fleet` has the following structure:
```
search-fleet
   clusters
      <clusters>
   tenants
      apps
      infra
         components
            kustomization.yaml
            # These contain flux Kustomizations referencing relevant paths in the search-infra GitRepository, eg. components/monitoring/controllers/${PLATFORM}/${ENVIRONMENT}
            monitoring.yaml
            networking.yaml
            storage.yaml
```

`search-infra` has the following structure:
```
search-infra
   components
      monitoring
         configs
         controllers
            # We target both different platforms (EKS, proxmox), and different envs on these platforms.
            base
            proxmox
               base
               dev
      networking
      storage
      ...
```

I would now like to test a local change in `search-infra`'s `monitoring` component using `flux diff kustomization`. I `cd` into `search-fleet` directory and run:

```
flux diff kustomization flux-infra-tenant --path .\tenants\infra\ --recursive --local-sources GitRepository/flux-system/flux-infra=../search-infra
```

For each of the components in `search-infra`, I'll get an error like:
```
failed to generate kustomization.yaml: failed to save original kustomization.yaml: open ..\search-infra\components\monitoring\controllers\proxmox\search-infra\components\monitoring\controllers\proxmox\dev\kustomization.yaml.original: The system cannot find the path specified. <nil> <nil>
```

Notice how `search-infra\components\monitoring\controllers\proxmox` part of the path is  duplicated (`proxmox` is `${PLATFORM}`, `dev` is `${ENVIRONMENT}`

`flux-infra-tenant` `Kustomization` is:
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-infra-tenant
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 12h
  retryInterval: 3m
  wait: true
  timeout: 15m
  path: ./tenants/infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
```

Inside `./tenants/infra/components` directory, `kustomization.yaml` is:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - monitoring.yaml
  - storage.yaml
  - networking.yaml
  - ...
```

And, for example, `monitoring.yaml` is:
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
spec:
  serviceAccountName: flux-infra
  interval: 5m
  retryInterval: 2m
  timeout: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: components/monitoring/controllers/${PLATFORM}/${ENVIRONMENT}
```

`${PLATFORM}` and `${ENVIRONMENT}` are substituted from the `flux-runtime-info` `ConfigMap`.
