### ISSUE TITLE
InitContainer update not working in helmrelease

### ISSUE THREAD

**Issue by anebi** [fluxcd/flux2#5307]
### Describe the bug

I am using keycloak condecentric helm chart to install keycloak. In the helm release I have 2 extra initContainers and I have set the extra comment for the image automation.

`
      - name: theme-provider
        image: registry.xxxx.tld/keycloak/kc-xxxx-theme:20250416-151448 # {"$imagepolicy": "flux-system:kc-xxx-theme-prod"}
        command:
          - sh
        args:
          - -c
          - |
            echo "Copying themes..."
            cp -R /theme/xxx-theme/* /theme-xxx/
            chown 1000 -R /theme-*
        volumeMounts:
          - name: theme-xxx
            mountPath: /theme-xxx
`

The image repo and policy defined like this:

`
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: kc-xxx-theme-prod
  namespace: flux-system
spec:
  image: registry.satse.es/keycloak/kc-xxx-theme
  interval: 3m0s
  secretRef:
    name: gitlab-xxx
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: kc-xxx-theme-prod
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kc-xxx-theme-prod
  filterTags:
    pattern: '^(?P<date>[0-9]{8})-(?P<time>[0-9]{6}).*'
    extract: '$date$time'
  policy:
    numerical:
      order: asc
`

Image reflector detects that there is newer image but nothing happens after that:

`
{"level":"info","ts":"2025-04-16T17:32:00.722Z","msg":"Latest image tag for 'registry.xxx.tld/keycloak/kc-xxx-theme' updated from 20250416-151448 to 20250416-170317","controller":"imagepolicy","controllerGroup":"image.toolkit.fluxcd.io","controllerKind":"ImagePolicy","ImagePolicy":{"name":"kc-xxx-theme-prod","namespace":"flux-system"},"namespace":"flux-system","name":"kc-xxx-theme-prod","reconcileID":"d6b7bf51-412e-46a1-8c78-afda0d53adcc"}
`

### Steps to reproduce

- Install flux version 2.5.1 on K8S cluster
- Deploy keycloak using codecentric helm chart or any other app using helmrelease
- In the helmrelease values section define initContainers and set them to be with autoupdate using flux
- Define ImageRepo and ImagePolicy
- Push a new docker image tag to the image registry for the init container
- Monitor Flux repo updates and monitor also flux pods logs

### Expected behavior

Flux should detect that the initContainer got an updated tag and push the update to the Git Repo. From there let Flux update the deployment/stateful set on k8s with the new initContainer version

### OS / Distro

MacOS 15.3.2

### Flux version

2.5.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.31.5+rke2r1 >=1.30.0-0
► checking version in cluster
✔ distribution: flux-v2.5.1
✔ bootstrapped: false
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.2.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.40.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.34.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.5.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.5.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.5.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

GitLab - self-hosted

### Container Registry provider

GitLab - self-hosted

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by niveau0** [comment]
@anebi  just to be sure: do you have an imageupdateautomation? 

https://fluxcd.io/flux/components/image/imageupdateautomations/#writing-an-imageupdateautomation-spec

**Comment by anebi** [comment]
Hello, thank you for your reply. Yes, i have image automation. It was created during the flux setup. It is like this:

```
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@mydomain.tld
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: /
    strategy: Setters
```

The image update is working fine for the main container images. It is not working only for init containers.

**Comment by gecube** [comment]
Hi @anebi 👋

I triaged this with a local reproduction (Flux v2.8.8, local GitLab + registry), and the behavior is reproducible — but the root cause is not init containers. **It's that `extraInitContainers` in the codecentric keycloak/keycloakx charts is a *string*, not structured YAML.**

## Root cause

The `Setters` update strategy parses every YAML file and looks for `# {"$imagepolicy": ...}` as a **YAML comment attached to a field node** (kyaml setters). The codecentric charts declare `extraInitContainers` as a string ([`values.yaml#L91`](https://github.com/codecentric/helm-charts/blob/master/charts/keycloakx/values.yaml#L91)) rendered through `tpl` ([`statefulset.yaml#L71-L72`](https://github.com/codecentric/helm-charts/blob/master/charts/keycloakx/templates/statefulset.yaml#L71-L72)), so in your HelmRelease the whole block is a single literal block scalar:

```yaml
values:
  extraInitContainers: |   # <- everything below is ONE string value
    - name: theme-provider
      image: registry.xxx.tld/keycloak/kc-xxx-theme:20250416-151448 # {"$imagepolicy": ...}
```

Inside a block scalar the `# {...}` is string *content*, not a YAML comment — the setter never sees a marker there and silently skips it. Your main container images work because they are set via structured values, i.e. real YAML fields with real comments.

## Repro

One repo, one ImagePolicy (your exact `filterTags`/`numerical` policy), three files, one automation run:

| file | marker location | updated |
|---|---|---|
| plain Deployment | `containers[].image` + `initContainers[].image` (structured) | ✅ both |
| HelmRelease | `values.initContainers[].image` (structured list) | ✅ |
| HelmRelease | inside `values.extraInitContainers: \|` (string block) | ❌ untouched |

So neither init containers nor HelmRelease values are the boundary — the string block is.

## Workaround

keycloakx renders `extraInitContainers` with `tpl . $` (root context), so you can hoist the image into a structured value and reference it from the block:

```yaml
values:
  themeProviderImage: registry.xxx.tld/keycloak/kc-xxx-theme:20250416-151448 # {"$imagepolicy": "flux-system:kc-xxx-theme-prod"}
  extraInitContainers: |
    - name: theme-provider
      image: {{ .Values.themeProviderImage }}
      ...
```

The marker now sits on a real YAML field, so the automation updates it, and the chart's `tpl` injects the value into the init container at render time.

I verified this workaround end-to-end on the same repro: the automation committed the tag bump on `themeProviderImage`, and `helm template` of keycloakx rendered the init container with the updated image:

```yaml
      initContainers:
        - name: theme-provider
          image: 192.168.97.97:5000/kc-theme:20250416-170317
```

## Related

This is working as designed — same class of problem as fluxcd/image-automation-controller#96 (marker inside a literal value, closed), and the open feature request covering image refs embedded in larger strings is fluxcd/image-automation-controller#97.

One unrelated heads-up for when you upgrade: your `messageTemplate` uses `{{range .Updated.Images}}` — the `.Updated` field has since been removed, and on current Flux (tested v2.8.8) the automation fails with `RemovedTemplateField`. Switch to `.Changed`.
