### ISSUE TITLE
Kustomization healthcheck fails while looking for wrong apiVersion

### ISSUE THREAD

**Issue by chrede88** [fluxcd/flux2#5311]
### Describe the bug

I've defined a custom healthCheckExprs for a `ClusterSecretStore` resource. The health check fails and flux reports that it can't find the resource. The error message suggests that flux is looking for the wrong apiVersion (which doesn't exsist on the cluster).

Here is the kustomization definition:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-store
  namespace: flux-system
spec:
  healthChecks:
    - apiVersion: external-secrets.io/v1
      kind: ClusterSecretStore
      name: onepassword
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1
      kind: ClusterSecretStore
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  wait: false
```

And here is the `ClusterSecretStore` I've deployed (with current status included):
```yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
  namespace: external-secrets
status:
  capabilities: ReadOnly
  conditions:
  - lastTransitionTime: "2025-02-13T18:38:07Z"
    message: store validated
    reason: Valid
    status: "True"
    type: Ready
```

The reconciliation fails for this `kustomization` with the following error:
```
health check failed after 5m0.027995928s: timeout waiting for: [ClusterSecretStore/onepassword status: 'Unknown': no matches for kind "ClusterSecretStore" in version "external-secrets.io/v1alpha1"]
```

I don't know why flux is looking for an apiVersion that isn't specified and also doesn't exsist on the cluster. I've verfied that the crd version is `external-secrets.io/v1`.

### Steps to reproduce

1. Define `kustomization` with `healthCheckExprs` for a `ClusterSecretStore` type resource.
2. Reconciliation fails.

### Expected behavior

Flux looks for the correct apiVersion.

### OS / Distro

macOS 15.3.2

### Flux version

v2.5.1

### Flux check

► checking prerequisites
✔ Kubernetes 1.32.3 >=1.30.0-0
► checking version in cluster
✔ distribution: flux-v2.5.1
✔ bootstrapped: false
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.2.0@sha256:62eaa9c9a9296a22684f9a77befa4f7fbf850fc314da47b3d6c28ad2e34ba965
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.5.1@sha256:b89935f9428764c389c5192fdb8f6c53b66e365fa09ac8cec597e82273e9f518
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.5.0@sha256:9fe4b5fb312eace22e43969975938deca08d64282c9a1e2783afe91be3da2869
✔ source-controller: deployment ready                                                                                          ► ghcr.io/fluxcd/source-controller:v1.5.0@sha256:00cd9316a3790f3e212132f38c849f87d6e6eeca6272ec9557387be3cec054be
► checking crds                                                                                                                ✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1                                                                                          ✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1                                                                                       ✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1                                                                                 ✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2                                                                             ✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1                                                                                  ✔ all checks passed

### Git provider

Github

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
