### ISSUE TITLE
failed to determine artifact digest: GET https://ghcr.io/v2/stefanprodan/charts/podinfo/manifests/6.0.0: MANIFEST_UNKNOWN: manifest unknown

### ISSUE THREAD

**Issue by atharrvv** [fluxcd/flux2#5329]
> Please read the docs: https://fluxcd.io/flux/guides/helmreleases/#oci-repository 

I am refring https://fluxcd.io/flux/guides/helmreleases/#oci-repository
but its returning this error.
It will be helpful for me to understand if you provide me a structure for OCI pull 

![Image](https://github.com/user-attachments/assets/3944be6d-2c7b-4f6d-a3d9-3bdbad454c6b)

 _Originally posted by @matheuscscp in [#5328](https://github.com/fluxcd/flux2/issues/5328#issuecomment-2841574249)_

**Comment by stefanprodan** [comment]
This is a typo in our docs, the version is too old, there was no Helm OCI chart for podinfo back at 6.0.0

Use:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 10m
  url: oci://ghcr.io/stefanprodan/charts/podinfo
  ref:
    semver: ">=6.5.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 10m
  releaseName: podinfo
  chartRef:
    kind: OCIRepository
    name: podinfo
  values:
    replicaCount: 2
```
