### ISSUE TITLE
Flux reconcile helmrelease but kustomization flux-system is suspended

### ISSUE THREAD

**Issue by Nicola-Sergio** [fluxcd/flux2#5341]
### Describe the bug

Helmrelease got helm charts updates with **reconcileStrategy: Revision** despite flux-system kustomization being suspended. 

### Steps to reproduce

For a project to deploy I used the following structure of Git Repository on Azure DevOps Services:

├───charts
│   ├───microservice
│   │   └───templates
└───flux
    ├───stage
    │   ├───flux-system
    │   └───helmrelease-1.yaml #application deployed
    │   └───helm-charts-gitrepository.yaml #gitrepository deployed
    └───dev
        ├───flux-system
        └───helmrelease-1.yaml #application deployed
        └───helm-charts-gitrepository.yaml #gitrepository deployed

1.  I bootstrapped flux on DEV AKS Cluster with the command:
`flux bootstrap git \
  --token-auth=true \
  --url=https://dev.azure.com/<org>/<project>/_git/Intermediazione \
  --branch=main \
  --path=flux/dev`

2.  I bootstrapped flux on STAGE AKS Cluster with the command:
`flux bootstrap git \
  --token-auth=true \
  --url=https://dev.azure.com/<org>/<project>/_git/Intermediazione \
  --branch=main \
  --path=flux/stage`

Both flux installation use the same helm chart (**microservice**) located under the **/charts** folder.
All **helmreleases** resources in both **/flux/col ** and **/flux/dev** reference the  **helm-charts-gitrepository.yaml** to fetch the shared chart **microservice**

`helm-charts-gitrepository.yaml` :

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: helm-charts
  namespace: flux-system
spec:
  ignore: |
    # exclude all
    /*
    # include /deploy/helm directory
    !/charts
  interval: 24h00m
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://dev.azure.com/<org>/<project>/_git/Intermediazione 
```

`helmrelease-1.yaml` (identical in both clusters):

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app1
  namespace: intermediazione
spec:
  storageNamespace: intermediazione
  install:
    remediation:
      retries: -1
  targetNamespace: intermediazione
  releaseName: app1
  chart:
    spec:
      chart: ./charts/microservice
      version: '1.0.6'
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: helm-charts
        namespace: flux-system
  interval: 1m
``` 
Then I performed the following steps:
3. I suspended **flux-system kustomization** on **Stage cluster**
4. I modified the **microservice** chart
5. I forced a reconcile of **flux-system** kustomization  with **--source** flag
6. The **HelmRelease** was updated on the **DEV cluster**, as expected.
7. No update occurred on the **STAGE cluster** at that time, as expected.

However, the next day, I noticed that the **HelmRelease** was updated automatically on the **STAGE cluster**, despite the **flux-system** Kustomization still being suspended. The update was triggered by a refresh of the GitRepository source (**helm-charts**) as defined in `helm-charts-gitrepository.yaml`.

What could have been happened?

### Expected behavior

I expected that there would be no updates to the helm release on **STAGE environment** until I had done the **flux-system kustomization resume**.

### OS / Distro

Ubuntu 22.04.5 LTS

### Flux version

v2.3.0

### Flux check

► checking prerequisites
✗ flux 2.3.0 <2.5.1 (new CLI version is available, please upgrade)
✔ Kubernetes 1.30.3 >=1.28.0-0
► checking version in cluster
✔ distribution: flux-v2.3.0
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.0.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.3.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.3.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.3.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
