### ISSUE TITLE
Grafana provider only allows HTTPS with a verified Root CA

### ISSUE THREAD

**Issue by Tuurkevg** [fluxcd/flux2#5348]
### Describe the bug

Hi,
I want to implement a Grafana alert and provider to send my Flux events to a Grafana instance. However, my Grafana server uses a certificate signed by a root authority that is unknown to the Flux notification controller.

Is there an option to disable TLS verification?

Here are the logs from the notification controller:
```
.toolkit.fluxcd.io/v2","resourceVersion":"19899636"},"Alert":{"name":"grafana-errors","namespace":"flux-system"},"error":"postMessage failed: failed to execute request: POST https://grafana.excentis.com/api/annotations giving up after 1 attempt(s): Post \"https://grafana.excentis.com/api/annotations\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
````

### Steps to reproduce

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: grafana
  namespace: flux-system
spec:
  type: grafana
  address: https://grafana.excentis.com/api/annotations
  secretRef:
    name: grafana-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: grafana-errors
  namespace: flux-system
spec:
  providerRef:
    name: grafana
  eventMetadata:
    summary: Cluster errors
    env: prod
    cluster: excgenkube
    region: europe-west1
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'      
```

### Expected behavior

I expected the Notification Controller to skip certificate verification and send the alert regardless.

### OS / Distro

Debian 12 

### Flux version

flux version 2.5.1

### Flux check

[admin@kube|flux-system] arthur@Laptop-gbLKZw9v:~$ flux check
► checking prerequisites
✔ Kubernetes 1.32.3+k3s1 >=1.30.0-0
► checking version in cluster
✔ distribution: flux-v2.5.1
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.2.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.40.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.34.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.5.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.5.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.5.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

### Git provider

azure

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
