### ISSUE TITLE
ObservedPolicies are parsed wrong when image name contains colon (e.g. port of private registry)

### ISSUE THREAD

**Issue by xGerTowelie** [fluxcd/flux2#5350]
### Describe the bug

Hey,

I use the ImageAutomation of flux to fetch tags of my private registry (gitlab ee). My gitlab registry is available via a custom port:
```
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: nextjs
  namespace: flux-system
spec:
  image: gitlab.private.com:5001/nextjs-test/nextjs  # private registry with port
  interval: 1h
  secretRef:
    name: gitlab-registry       # credentials for registry (type: kubernetes.io/dockerconfigjson)

```

The ImageRepository is pulled correctly:

```
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: nextjs
  namespace: flux-system
spec:
  exclusionList:
  - ^.*\.sig$
  image: gitlab.private.com:5001/nextjs-test/nextjs
  interval: 1h
  provider: generic
  secretRef:
    name: gitlab-registry
status:
  canonicalImageName: gitlab.private.com:5001/nextjs-test/nextjs
  lastScanResult:
    latestTags:
    - latest
    - 1.0.9
    - 1.0.7
    - 1.0.6
    - 1.0.5
    - 1.0.4
    - 1.0.3
    - 1.0.2
    - 1.0.1
    - 1.0.0
    scanTime: "2025-05-14T13:53:31Z"
    tagCount: 10
```

But the ImageUpdateAutomation split the image name and tag incorrect. I assume it's a simple split by the first colon, but I think splitting by the last colon would be correct.  (or manual check to skip port)

```
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  creationTimestamp: "2025-05-14T13:42:04Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
    toolkit.fluxcd.io/tenant: lit-beratung
  name: flux-system
  namespace: flux-system
  resourceVersion: "281994"
  uid: 889b4794-715b-43a3-82fa-6387560df783
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: marcel.maier@lit-beratung.de
        name: Flux Automation
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println
        .NewValue}}{{end}}'
    push:
      branch: main
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./apps/production
    strategy: Setters
status:
  conditions:
  - lastTransitionTime: "2025-05-14T13:42:05Z"
    message: repository up-to-date
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: Ready
  lastAutomationRunTime: "2025-05-14T13:53:27Z"
  observedGeneration: 1
  observedPolicies:
    flux-system:
      name: gitlab.private.com                        # the port is missing
      tag: 5001/nextjs-test/nextjs:1.0.9          # missing part of url plus tag
  observedSourceRevision: main@sha1:a044492c48dcd4bfc3f74e20767f7be88c77900c
```



### Steps to reproduce

Use any port in the image repo url for `Spec.Image` and trigger image update mechanism 

### Expected behavior

Expected values for Observed Policies:
```
 Observed Policies:                                                                                                                                                                                                                                     
     Flux - System:                                                                                                                                                                                                                                       
       Name:               gitlab.private.com:5001/nextjs-test/nextjs                                                                                                                                                                                      
       Tag:                   1.0.9 
```

but got this instead:

```
 Observed Policies:                                                                                                                                                                                                                                     
     Flux - System:                                                                                                                                                                                                                                       
       Name:               gitlab.private.com                                                                                                                                                                                                      
       Tag:                   5001/nextjs-test/nextjs:1.0.9 
```

### Screenshots and recordings

_No response_

### OS / Distro

Ubuntu 24.04.2 LTS x86_64

### Flux version

v2.5.1

### Flux check

```
❯ flux check
► checking prerequisites
✔ Kubernetes 1.32.4+k3s1 >=1.30.0-0
► checking version in cluster
✔ distribution: flux-v2.5.1
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.2.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.40.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.34.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.5.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.5.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.5.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed
```

### Git provider

GitLab self-hosted

### Container Registry provider

GitLab self-hosted

### Additional context

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
