### ISSUE TITLE
Flux losts track of ExternalSecret after upgrade

### ISSUE THREAD

**Issue by blindrood** [fluxcd/flux2#5374]
### Describe the bug

Related bug on external-secrets-operator: [here](https://github.com/external-secrets/external-secrets/issues/4848)

**Describe the bug**
I have recently migrated from 0.10.0 to 0.16.2 and upgraded API versions everywhere to v1. All works great.
Now I'm migrating to 0.17.0 and suddenly fluxcd is unable to sync them properly

**To Reproduce**
secret definition in my repo

```yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gcp-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: app-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: stage-k8s
```

fluxcd syncs periodically cluster. Up until 0.16.2 all works great.
After migration to 0.17.0 ExternalSecret resources look ok from my point of view but suddenly fluxcd keeps returning

```
health check failed after 10m0.02452782s: timeout waiting for: [ExternalSecret/namespace/gcp-secret status: 'NotFound']
```

**Expected behavior**
fluxcd should still sync properly secrets

### Steps to reproduce

1. Configure external secret with eso 0.16.2
2. upgrade eso to 0.17.0

### Expected behavior

fluxcd should still properly sync ExternalSecret resources

### OS / Distro

N/A

### Flux version

N/A

### Flux check

I'm not using cli

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
