### ISSUE TITLE
Flux v2.6.0 - flux push with Azure identity no longer working

### ISSUE THREAD

**Issue by Layer8Err** [fluxcd/flux2#5375]
### Describe the bug

After upgrading from flux version 2.5.1 to 2.6.0 we are unable to push artifacts to an Azure Container Registry using the Azure identity assigned to the VM.

Switching back to version 2.5.1 resolves the authentication issue shown by flux.

### Steps to reproduce

Install flux with version 2.6.0:
```bash
curl -s https://fluxcd.io/install.sh | sudo FLUX_VERSION=2.6.0 bash
```

Using Azure Devops Agent and pipeline. Here are the relevant portions:

```yaml
- task: Bash@3
  displayName: "Agent install flux"
  retryCountOnTaskFailure: 3
  inputs:
      targetType: inline
      workingDirectory: "$(Agent.ToolsDirectory)"
      script: |
        curl -s https://fluxcd.io/install.sh | sudo FLUX_VERSION=2.6.0 bash
        flux --version

- task: AzureCLI@2
   displayName: 'Push repo artifact to ACR'
   inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: "$(System.DefaultWorkingDirectory)"
        addSpnToEnvironment: true
        inlineScript: |
          echo "[+] Pushing artifact $(version) to $(repositoryName) repository..."
          flux push artifact oci://$(containerRegistry).azurecr.io/$(repositoryName):$(version) \
            --path="." \
            --source="$(git config --get remote.origin.url)" \
            --revision="$(git branch --show-current)/$(git rev-parse HEAD)" \
            --provider=azure \
            --ignore-paths="[pipelines/,docs/,GitVersion.yml,README.md]"

          echo "[+] Tagging latest OCI source artifact"
          sleep 5s
          flux tag artifact oci://$(containerRegistry).azurecr.io/$(repositoryName):$(version) \
            --tag latest \
            --provider azure
```

### Expected behavior

Expect flux to be able to authenticate using identity assigned to running ADO agent.

### Screenshots and recordings

Error output:

Pushing artifact:

```txt
► logging in to registry with provider credentials
✗ error during login with provider: failed to create provider access token for the controlller: ManagedIdentityCredential: failed to authenticate a system assigned identity. The endpoint responded with {"error":"invalid_request","error_description":"Identity not found"
```

Tagging artifact:

```txt
► logging in to registry with provider credentials
✗ error during login with provider: could not login to provider azure with url <containerRegistry>.azurecr.io/<repositoryName>:<version>: failed to create provider access token for the controlller: ManagedIdentityCredential: failed to authenticate a system assigned identity. The endpoint responded with {"error":"invalid_request","error_description":"Identity not found"}
```

### OS / Distro

Ubuntu 24.04

### Flux version

v2.6.0

### Flux check

N/A

### Container Registry provider

AzureCR.io

### Additional context

The issue is resolved by rolling back to v2.5.1

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by matheuscscp** [comment]
But, essentially, what you need to do as a workaround is documented here:

https://fluxcd.io/flux/integrations/azure/#for-workload-identity-federation-1

You just need to set the environment variables documented right after "If the cluster is not AKS", they are:

* `AZURE_TENANT_ID`
* `AZURE_CLIENT_ID`
* `AZURE_AUTHORITY_HOST` (this one you can probably just set to `https://login.microsoftonline.com/`)
* `AZURE_FEDERATED_TOKEN_FILE`

While setting the first 3 variables is trivial, I'm still looking into how you can set `AZURE_FEDERATED_TOKEN_FILE`, but essentially it needs to be a file containing an OIDC token issued by your CI environment. This OIDC token will be exchanged for an Azure Access Token.

Question: Did you configure a Managed Identity for this CI environment?

**Comment by Layer8Err** [comment]
No, the CI uses an Azure DevOps "azureSubscription" `$(azureSubscription)`. The Service Connection is created using a Service Principal account (clientId/clientSecret) and is used to authenticate with the AzureRM. The full docs can be found on the [Microsoft learn page](https://learn.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops).

In this particular environment, I do not have a way of using something other than a clientId/clientSecret for a Service Principal used to create the ADO Service Connection. Unfortunately, I cannot use Federated Credentials due to limited access.

**Comment by Layer8Err** [comment]
I no longer have access to the `AZURE_CLIENT_SECRET`, but if setting those environment variables will allow flux to authenticate with the ACR I'll give it a try at some point. For now, I need to keep flux set at version 2.5.1.

Not sure if there could potentially be a way to allow an "azure-legacy" auth method that can use the old Azure auth method, or if maybe it could be added as a fallback if the modern auth method doesn't work?

**Comment by matheuscscp** [comment]
Before making any promises, I'd like to know more about your use case and what are the actual reasons why you can't go for the more secure option (OIDC/workload identity federation), if you're allowed/want to share.

**Comment by MUlfers** [comment]
Hello everyone.
We are facing the same issue. We are using azure pipelines to push flux artifacts into a azure container registry.
We are using a azure resource manager service connection for that. The recommended way to set up such a service connection is app registration + workload identity federation. 

![Image](https://github.com/user-attachments/assets/2e1c2370-93bb-4bef-ab5b-57bcb74304ef)

That way the pipeline code looks like this

```
- task: AzureCLI@2
    displayName: "push flux artifacts"
    inputs:
        azureSubscription: <service-connection-name>
        scriptType: "bash"
        scriptLocation: "scriptPath"
        scriptPath: "./scripts/package_and_push_flux.sh"
        ......
```
and inside the script we then call 
```
flux push artifact "oci://...... --provider azure
```
This approach stopped working with v2.6.0 of the CLI.
