### ISSUE TITLE
GitRepository fails after upgrade to 2.6

### ISSUE THREAD

**Issue by artyom-p** [fluxcd/flux2#5415]
### Describe the bug

After upgrading to FluxCD 2.6 from 2.5 via Flux Operator, my git repository started to fail and stopped reconciling commits.

Status message on a GitRepository:

```
Failed to configure authentication options: app ID must be provided to use github app authentication
```
I'm not using the GitHub app. I'm just using a username and password (PAT).

### Steps to reproduce

Install flux 2.5 and upgrade to 2.6 using following resources:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: git-token-auth
  namespace: flux-system
spec: {}
data:
  password: password
  username: username
type: Opaque
```

```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: Ignore
  finalizers:
    - finalizers.fluxcd.io
  generation: 1
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/managed-by: flux-operator
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v2.6.2
    fluxcd.controlplane.io/name: flux
    fluxcd.controlplane.io/namespace: flux-system
  name: my-git-repository
  namespace: flux-system
spec:
  interval: 1m0s
  provider: github
  ref:
    name: refs/heads/master
  secretRef:
    name: git-token-auth
  timeout: 60s
  url: my-gh-repo-url
```

### Expected behavior

GitRepository should continue working

### OS / Distro

EKS 1.33 Bottlerocket OS 1.40 arm64

### Flux version

v2.6.2

### Flux check

```sh
flux check
► checking prerequisites
✔ Kubernetes 1.33.1-eks-7308294 >=1.31.0-0
► checking version in cluster
✔ distribution: flux-v2.6.2
✔ bootstrapped: false
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.3.0@sha256:db55d9d9f9b5106acd8c21da6916b8e285fcfc5572f214361ececd1a8571a4f0
✔ helm-controller-x-staging: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.3.0@sha256:db55d9d9f9b5106acd8c21da6916b8e285fcfc5572f214361ececd1a8571a4f0
✔ helm-controller-x-test: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.3.0@sha256:db55d9d9f9b5106acd8c21da6916b8e285fcfc5572f214361ececd1a8571a4f0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.6.0@sha256:d8c5445003196791441354f2d549e96cc6e69bb9ef6c5a7e440918dab0503776
✔ kustomize-controller-x-staging: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.6.0@sha256:d8c5445003196791441354f2d549e96cc6e69bb9ef6c5a7e440918dab0503776
✔ kustomize-controller-x-test: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.6.0@sha256:d8c5445003196791441354f2d549e96cc6e69bb9ef6c5a7e440918dab0503776
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.6.1@sha256:a9dbd7872344ceadea48a89ea24c8a761a2a1008a2cdbbc1ffa3ed95dd2a00ce
✔ source-controller-x-staging: deployment ready
► ghcr.io/fluxcd/source-controller:v1.6.1@sha256:a9dbd7872344ceadea48a89ea24c8a761a2a1008a2cdbbc1ffa3ed95dd2a00ce
✔ source-controller-x-test: deployment ready
► ghcr.io/fluxcd/source-controller:v1.6.1@sha256:a9dbd7872344ceadea48a89ea24c8a761a2a1008a2cdbbc1ffa3ed95dd2a00ce
► checking crds
✔ buckets.source.toolkit.fluxcd.io/v1
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1
✔ all checks passed
```

### Git provider

GitHub

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
