### ISSUE TITLE
authorization failed

### ISSUE THREAD

**Issue by karnain1803** [fluxcd/flux2#5419]
**### pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed**

```
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cache
  namespace: flux-system
spec:
  interval: 5m0s
  type: oci
  url: oci://example.com/devops/helm-repo/charts/cache-service
  secretRef:
    name: regcred
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cache
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cache-service
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cache
      version: 1.0.0
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: hpa-values
  values:
    # envFrom:
    #   - secretRef:
    #       name: 
    image:
      repository: example.com
      tag: 1.0.0 
    imagePullSecrets:
      - name: regcred
```
kubectl get secret regcred -n flux-system -o jsonpath="{.data.\.dockerconfigjson}" | base64 -d                                                                                

{"auths":{"git.example.com:5050":{"username":"user","password":"token","email":"123@mail.ru","auth":"RGF2aWQ6Z2xwYXQtZjhYdkJHZi02Rno="}}}%

I have no idea why it is doesnt work. Full permissions on the token from GitLab its PAT.
