### ISSUE TITLE
Unable to deploy Helm from private chart repo

### ISSUE THREAD

**Issue by zonnie** [fluxcd/flux2#564]
**Issue**

Using JFrog private Helm repo is not working with `flux` but works with `helm install`

**Reproduction**
Using following configuration
Helm repo
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jfrog-helm
  namespace: flux-system
spec:
  interval: 1m
  secretRef:
    name: jfrog-helm-creds
  url: https://xxxx.jfrog.io/artifactory/helm
```

Using following release
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: test-9
spec:
  interval: 1m
  releaseName: elasticsearch
  chart:
    spec:
      chart: elastic/elasticsearch
      version: 7.9.2
      sourceRef:
        kind: HelmRepository
        name: jfrog-helm
        namespace: flux-system
      interval: 1m
  values:
    clusterName: "elasticsearch"
    nodeGroup: "master"
    replicas: 1
    minimumMasterNodes: 1
    image: "docker.elastic.co/elasticsearch/elasticsearch"
    imageTag: "6.8.8"
    imagePullPolicy: "IfNotPresent"
    overideName: "elasticsearch"
    esJavaOpts: "-Xmx1g -Xms1g"
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Gi
    resources:
      requests:
        cpu: "1000m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "3Gi"
    lifecycle:
      postStart:
        exec:
          command:
             - bash
             - -c
             - |
               #!/bin/bash
               ES_URL=http://localhost:9200
               while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' $ES_URL)" != "200" ]]; do sleep 1; done
               curl -XPOST "$ES_URL/_scripts/connections_threshold" -H 'Content-Type: application/json' -d'{"script": {"lang": "painless","source": "return params.total >= params.threshold;"}}'
               curl -XPOST "$ES_URL/_scripts/misconfigurations_threshold" -H 'Content-Type: application/json' -d'{"script": {"lang": "painless","source": "return params.misconfigurations_count >= params.threshold;"}}'

```

The helm release fails deployment because the chart is not fetched:
```
➜  fluxv2_test git:(main) kubectl get helmcharts.source.toolkit.fluxcd.io -A
NAMESPACE     NAME                   CHART                   VERSION   SOURCE KIND      SOURCE NAME   READY     STATUS                       AGE
flux-system   test-9-elasticsearch   elastic/elasticsearch   7.9.2     HelmRepository   jfrog-helm    Unknown   reconciliation in progress   14m
➜  fluxv2_test git:(main) kubectl get helmcharts.source.toolkit.fluxcd.io -A
NAMESPACE     NAME                   CHART                   VERSION   SOURCE KIND      SOURCE NAME   READY   STATUS                                                                                                                                                                                                                             AGE
flux-system   test-9-elasticsearch   elastic/elasticsearch   7.9.2     HelmRepository   jfrog-helm    False   storage error: symlink /data/helmchart/flux-system/test-9-elasticsearch/elastic/elasticsearch-7.9.2.tgz /data/helmchart/flux-system/test-9-elasticsearch/elastic/elastic/elasticsearch-latest.tgz.tmp: no such file or directory   14m
```

**Notes**
- Secret `jfrog-helm-creds` is set correctly 
- Using `helm install` with the same configuration (i.e. password, repo and chart) works prefectly
- Using a public repo (i.e. `bitnami`) with the above resources works

Any idea how to resolve this ?
My hair is turning even grayer....and it's pretty gray already... 😢
