### ISSUE TITLE
Force Kustomization targetNamespace default value

### ISSUE THREAD

**Issue by Jimmy-Newtron** [fluxcd/flux2#639]
While experimenting with Flux2 as Kubernetes Continuous Deployment, I encountered a corner case without a clear solution.

**Context**

The experiment goal was to create a multi-cluster/multi-namespace/multi-application folder layout

```bash
.
├── apps
│   ├── collections
│   │   ├── app-collection-example
│   │   │   ├── app1.yaml
│   │   │   └── app2.yaml
│   └── standalone
│       ├── app1
│       │   ├── helm-release.yaml
│       │   └── kustomization.yaml
│       ├── app2
│       │   ├── helm-release.yaml
│       │   └── kustomization.yaml
├── clusters
│   ├── minikube
│   │   ├── flux-system
│   │   │   ├── gotk-components.yaml
│   │   │   ├── gotk-sync.yaml
│   │   │   └── kustomization.yaml
│   │   ├── namespaces
│   │   │   ├── namespace-A
│   │   │   │   ├── app-collection-kustomization.yaml
│   │   │   │   └── namespace.yaml
│   │   └── sources
│   │       └── sources.yaml
└── sources
    ├── git-repositories
    │   └── git-repo.yaml
    └── helm-repositories
        ├── helm-incubator.yaml
        └── helm-stable.yaml
```

The `app-collection-kustomization.yaml` is a Kustomization with a well known `targetNamespace` 

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app-collection-kustomization
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: sources
  path: ./fluxcd/apps/collections/app-collection-example
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  targetNamespace: namespace-A
```

The files `app1.yaml` and `app2.yaml` are meant to be Kustomization and the namespace will be overridden by the `app-collection-kustomization`

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app1
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: sources
  path: ./fluxcd/apps/standalone/app1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
```

**Problem**

All the resources managed by `app1.yaml` and `app2` are no more constrained to the `targetNamespace`

**Expectation**

Allow to set a field in the files `app1.yaml` and `app2.yaml` that allows to keep the parent `targetNamespace` as it was defined in the `app-collection-kustomization`

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app1
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: sources
  path: ./fluxcd/apps/standalone/app1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  limitToNamespace: true
```

where `limitToNamespace` is a boolean that when `true` overrides the `targetNamespace` value by the Kustomization resource namespace.

This feature will help to have consistency with the HelmRelease behavior of the same targetNamespace field.
