### ISSUE TITLE
CPU limit of 1 is inadequate for kustomize-controller at scale

### ISSUE THREAD

**Issue by funkypenguin** [fluxcd/flux2#685]
Hey guys!

We're possibly stretching the limits of the intended behaviour here, but we're trying to reconcile 52 kustomizations:

```
root@cowboy:~# kubectl get kustomizations.kustomize.toolkit.fluxcd.io  -A | wc -l
52
root@cowboy:~#
```

They're all based on paths in the same git resource, so when we update the repo, all the kustomizations try to reconcile at once, and we get errors like:

```
flux-system   kube-prometheus-stack                False     Get "https://10.96.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions": context canceled
```

Here's a handy graph which illustrates what I think the problem is:

![image](https://user-images.githubusercontent.com/1524686/104244649-bf525080-54c7-11eb-8db8-1f777d79dc6c.png)

The clusters are bootstrapped using the cli `flux bootstrap` command, which seems to set a default CPU limit of 1. I can bootstrap a cluster, and then go into the repo and adjust its CPU limits, but the next time the (idempotent) bootstrap command is run, the CPU limit will get reset to 1 again.

Can we please add the option to explicitly set the resources during the bootstrap process?

(I'm open to other solutions here too, but I can't avoid the single-repo, multi-kustomization design)

Cheers!
D

**Comment by philoserf** [comment]
I chose to flux export then kubectl apply -k from source rather than bootstrap. By taking on the responsibility for the install, I can modify the manifests as required.

That said, I’d still consider this a bug. The controller should have a rate limit.

**Comment by funkypenguin** [comment]
FWIW, when I bumped the limit to 10 CPU, I reconciled all 52 kustomizations in < 3 min, and CPU for kustomize-controller went as high as 5.5

**Comment by funkypenguin** [comment]
@philoserf how do you initially produce the flux manifests, if you don't bootstrap?

**Comment by stefanprodan** [comment]
You can change any field of Flux manifests with Kustomize patches without interfering with bootstrap, please read the docs https://toolkit.fluxcd.io/guides/installation/#customize-flux-manifests

**Comment by r4j4h** [comment]
Just to follow up for anyone running into this sort of issue, the simplest way of modifying resources locally without bootstrapping first is:

1. `mkdir flux-setup`
1. `flux install --export > flux-setup/flux-system.yaml`
1.
    ```
    cat <<EOF > flux-setup/kustomization.yaml
    patchesJson6902:
    - target:
        version: v1
        kind: Deployment
        name: source-controller
      patch: |-
        - op: remove
          path: /spec/template/spec/containers/0/resources
    - target:
        version: v1
        kind: Deployment
        name: helm-controller
      patch: |-
        - op: remove
          path: /spec/template/spec/containers/0/resources
    - target:
        version: v1
        kind: Deployment
        name: kustomize-controller
      patch: |-
        - op: remove
          path: /spec/template/spec/containers/0/resources
    - target:
        version: v1
        kind: Deployment
        name: notification-controller
      patch: |-
        - op: remove
          path: /spec/template/spec/containers/0/resources
    resources:
    - flux-system.yaml
    EOF
    ```
1. `kubectl kustomize ./flux-setup | kubectl apply -f -`

The above removes all resource limits/requests so that it can easily be started on minikube. In your case you would change the patch operations but hopefully that is enough to get you going.
