### ISSUE TITLE
GitRepository based HelmRelease failes at pulling old stable helm chart

### ISSUE THREAD

**Issue by autarchprinceps** [fluxcd/flux2#706]
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  name: somerelease
  namespace: somens
spec:
  chart: .
  interval: 22m0s
  sourceRef:
    kind: GitRepository
    name: product-helm-chart
  version: '*'
status:
  conditions:
  - lastTransitionTime: "2021-01-14T09:46:18Z"
    message: 'failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml
      : 403 Forbidden'
    reason: ChartPullFailed
    status: "False"
    type: Ready
  observedGeneration: 1
```

We are getting a failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml: 403 Forbidden even though we are not only not using that url, we are not using a helm chart repo to begin with, we use a GitRepository with a helm chart in a path.

**Comment by stefanprodan** [comment]
Post here the HelmRelease manifest

**Comment by stefanprodan** [comment]
> We are getting a failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml: 403 Forbidden even though we are not only not using that url, we are not using a helm chart repo to begin with, we use a GitRepository with a helm chart in a path.

My guess is that your chart depends on some other chart from stable, check `requirements.yaml` and `Chart.yaml`.

**Comment by autarchprinceps** [comment]
Sure.

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/checksum: 6498b22491782ea71c844e527178897640306271
    kustomize.toolkit.fluxcd.io/name: somerelease
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: somerelease
  namespace: somens
spec:
  chart:
    spec:
      chart: .
      interval: 22m
      sourceRef:
        kind: GitRepository
        name: product-helm-chart
        namespace: somens
      version: '*'
  interval: 9m
  releaseName: somerelease
  values:
    somevalues: set
status:
  conditions:
  - lastTransitionTime: "2020-11-20T08:23:25Z"
    message: Helm upgrade succeeded
    reason: UpgradeSucceeded
    status: "True"
    type: Released
  - lastTransitionTime: "2020-12-22T09:39:10Z"
    message: HelmChart 'somens/somerelease' is not ready
    reason: ArtifactFailed
    status: "False"
    type: Ready
  failures: 1511
  helmChart: somens/somerelease
  lastAppliedRevision: 0.1.6
  lastAttemptedRevision: 0.1.6
  lastAttemptedValuesChecksum: 2c6f6ef12ac9c597a1583dcaf1bd63c40c067303
  lastReleaseRevision: 9
  observedGeneration: 5
```
