### ISSUE TITLE
kustomize build failed

### ISSUE THREAD

**Issue by echel0n** [fluxcd/flux2#725]
I get the following error when attempting to bootstrap my cluster with customizations for postgresql-operator:
`kustomize build failed: json: unknown field "spec"`

I've got flux-system v0.5.3

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  interval: 5m
  path: "./postgresql/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: postgres-operator
      namespace: pgo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: pgo-discourse
  namespace: flux-system
spec:
  dependsOn:
    - name: postgres-operator
      namespace: pgo
  interval: 10m0s
  path: ./postgresql/discourse/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
```
