### ISSUE TITLE
 HelmChart is not ready 

### ISSUE THREAD

**Issue by frank-bee** [fluxcd/flux2#735]
I get the the following error message 
➜  flux-system git:(master) ✗ flux get helmreleases --all-namespaces --verbose                           
NAMESPACE       NAME    READY   MESSAGE                                                 REVISION        SUSPENDED 
traefik         traefik False   HelmChart 'flux-system/traefik-traefik' is not ready                    False 

how can I debug this ?
(when I install the chart with helm3 it works)

I used the following deklarations to install this repo and chart 
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1m
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 9.12.3
  interval: 10m0s
```
