### ISSUE TITLE
Repetitive error: failed to download repository index: stream error: stream ID 1; INTERNAL_ERROR

### ISSUE THREAD

**Issue by jacek-jablonski** [fluxcd/flux2#746]
Hi,
I'm using bitnami helm repository declared like this:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.bitnami.com/bitnami
```

In logs I can see this message several times a day:
```json
{
  "insertId": "e5lizjg357oh06",
  "jsonPayload": {
    "namespace": "flux-system",
    "error": "failed to download repository index: stream error: stream ID 1; INTERNAL_ERROR",
    "reconciler group": "source.toolkit.fluxcd.io",
    "reconciler kind": "HelmRepository",
    "msg": "Reconciler error",
    "ts": "2021-01-19T16:33:56.999Z",
    "logger": "controller.helmrepository",
    "name": "bitnami",
    "level": "error"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "project_id": "x",
      "cluster_name": "x",
      "namespace_name": "flux-system",
      "pod_name": "source-controller-599cf6974b-8l4c8",
      "location": "europe-west4-c",
      "container_name": "manager"
    }
  },
  "timestamp": "2021-01-19T16:33:56.999658148Z",
  "severity": "ERROR",
  "receiveTimestamp": "2021-01-19T16:33:59.013671636Z"
}
```

Am I missing something here? What could be causing this error?
