### ISSUE TITLE
No matches for kind ImageRepository

### ISSUE THREAD

**Issue by andrei-dascalu** [fluxcd/flux2#759]
Hello,

I'm trying to setup automatic image update with a simple yaml for ImageRepository as such

```
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: mobile-test-repo
  namespace: flux-system
spec:
  image: <id>.dkr.ecr.<zone>.amazonaws.com/<myrepo>
  interval: 1m0s
```

However, I am getting the following error:

```
error: unable to recognize "flux-image-registry.yml": no matches for kind "ImageRepository" in version "image.toolkit.fluxcd.io/v1alpha1"
```

Flux was setup simply using `flux bootstrap gitlab`
