### ISSUE TITLE
Azure DevOps flaky network: Error waiting on socket

### ISSUE THREAD

**Issue by frank-bee** [fluxcd/flux2#760]
I see these error logs popping up sometimes in my alert notification
```
unable to clone 'ssh://git@ssh.dev.azure.com/v3/...', error: SSH could not read data: Error waiting on socket
flux-system.flux-system
```

**Comment by frank-bee** [comment]
this is my repo def.: 
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  gitImplementation: libgit2
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  timeout: 20s
  url: ssh://git@ssh.dev.azure.com/v3/...
```

In general it works fine
