### ISSUE TITLE
kustomize error: unknown field "sops" in io.k8s.api.core.v1.Secret

### ISSUE THREAD

**Issue by frank-bee** [fluxcd/flux2#797]
How to reproduce:

Encrypt a Secret with
```
sops --encrypt \
--pgp=1F3D1CED2F865F5E59CA564553241F147E7C5FA4 \
--encrypted-regex '^(data|stringData)$' \
--in-place basic-auth.yaml
```
Push the secret to a git source, e.g.

```
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:QknYD968mrzfURnH,iv:b8AqN/dpUq4GWp8OuYZeYkXDxsJDqvzWV3xaaXuYpKQ=,tag:+BUrGnd4IwaO6wLuQSQZvA==,type:str]
    user: ENC[AES256_GCM,data:rgwSOoYdxxE=,iv:JcY+Qd8+tzquL4/MJ5eE4Bfie3d3QWZW/wcUSyP02Hg=,tag:hp5mdFBOuWUsM7cieDYCow==,type:str]
kind: Secret
metadata:
    name: basic-auth
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-27T07:43:13Z'
    mac: ENC[AES256_GCM,data:Noir7Ooe1E8FJrUtFTa7bSz+l/ncxe3XyIhKRETIaTESsL2fPjRqfXptf3dfDWfWHT02SKDkWSxkQxR1sJG1Ci43qcMT+JqI3zbIqerkK6yRLY/sCNsI2h/Xjn/eJNmtnVVpZaB6nJ1n2zNES2ZoDDbF95tzZdHGKv5Sw/najoY=,iv:JudjRARsqeFhvXZ/dEAmIBncXqVJMnrKPIUBJgwBbpY=,tag:rHn86pykU3O77YJMf+SJUQ==,type:str]
    pgp:
    -   created_at: '2021-01-27T07:43:13Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA2nFZDLpk95/AQwAowDzisoF9HL0omi10ZrV2Tj2kfW1asmokt5KoL1vKLZi
            KDqyf6ZggyW4UdHz+cVY7lFgHoncP9R/nLi/KmRykUP7MK8XZdx9GE6FGTqLQOMJ
...
            pXoYe5ClHiaFjwje48WY
            =bTBn
            -----END PGP MESSAGE-----
        fp: B8B4F2592C7D75899AC8D1FA8D5A0B9B9392ACF6
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1

```

**Comment by stefanprodan** [comment]
Please see the SOPS guide on how to enable decryption https://toolkit.fluxcd.io/guides/mozilla-sops/#configure-secrets-decryption

**Comment by frank-bee** [comment]
now it works...

I initially thought  it is enough to have this is the main Kustomization for the cluster
```
  validation: none
  decryption:
    provider: sops
    secretRef:
      name: sops-pgp
``` 

After declaring this in the child Kustomizations ( for e.g. "app" / "infrastructure" ) , it works fine.

but validation I have to switch of , correct? 
Ideally I don't want to have extra Kustomizations only for the secrets (but could do that as well)
