### ISSUE TITLE
Deploying in custom namespace fails due to wrong namespace in ClusterRoleBinding

### ISSUE THREAD

**Issue by langecode** [fluxcd/flux2#801]
Running `flux install -n custom-namespace` ends up with the deployment not working due to issue with the namespace on the subjects in the created `ClusterRoleBinding`

This can easily be seen doing:
```
flux install -n custom-namespace --export
```

Note the namespace of the subjects is still `flux-system`:

```
...
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: customer-namespace
    app.kubernetes.io/version: latest
  name: cluster-reconciler-customer-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kustomize-controller
  namespace: flux-system
- kind: ServiceAccount
  name: helm-controller
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: customer-namespace
    app.kubernetes.io/version: latest
  name: crd-controller-customer-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-controller-customer-namespace
subjects:
- kind: ServiceAccount
  name: kustomize-controller
  namespace: flux-system
- kind: ServiceAccount
  name: helm-controller
  namespace: flux-system
- kind: ServiceAccount
  name: source-controller
  namespace: flux-system
- kind: ServiceAccount
  name: notification-controller
  namespace: flux-system
- kind: ServiceAccount
  name: image-reflector-controller
  namespace: flux-system
- kind: ServiceAccount
  name: image-automation-controller
  namespace: flux-system
...
```

A workaround is piping the manifests through `sed`

```bash
flux install -n custom-namespace --export | sed 's/namespace: flux-system/namespace: custom-namespace/' | kubectl apply -f -
```
